### ISSUE TITLE
Update icon for Fleet Server and Elastic Agent

### ISSUE THREAD

**Issue by mostlyjason** [elastic/integrations#1001]
Right now we just have the default icon of a box for Fleet Server. Can we pick an icon that better reflects its function? To clarify, it should be an icon, not a logo.

Update 2021-07-29 We have icons now for Fleet Server and Elastic Agent

CC @hbharding

**Comment by mostlyjason** [comment]
@jen-huang should fleet team take this one since we are updating the dashboard for elastic agent anyway?

**Comment by nchaulet** [comment]
@mostlyjason I am about to update the dashboard for elastic agent, if you know where I can find the assets I can update the icons too.

**Comment by jen-huang** [comment]
@nchaulet Here's the associated EUI ticket https://github.com/elastic/eui/issues/4981
