### ISSUE TITLE
How do I add integration to the elastic stack? To make OpenCTI available in the list of integrations via Kibana?

### ISSUE THREAD

**Issue by SokolSec** [elastic/integrations#10023]
Hello!
I asked a question earlier. But they didn't help me.

https://github.com/elastic/integrations/issues/9973

**Comment by SokolSec** [comment]
HEEEEELPPPPP PLEASEEEEE!!!!!!!!!!

**Comment by aliabbas-elastic** [comment]
@SokolSec What is your stack version? I can see the support of `OpenCTI` integration is from `8.9.0`. Is that the version you are searching the integration in?

**Comment by SokolSec** [comment]
@aliabbas-elastic Hello! v.8.13.4. Full stack. If I don't have it displayed, can I manually install this integration? If yes, please send the instructions

**Comment by andrewkroh** [comment]
Duplicate: https://github.com/elastic/integrations/issues/9973
