### ISSUE TITLE
[SentinelOne Cloud Funnel] Improve data stream management for events

### ISSUE THREAD

**Issue by adrianchen-es** [elastic/integrations#10036]
Description
The SentinelOne Cloud Funnel integration collects logs for the thirteen events, but it is currently combined in one data stream named `event`.
Events Currently Combined
- Command Script
- Cross Process
- DNS
- File
- Indicator
- Login
- Module
- Network Action
- Process
- Registry
- Scheduled Task
- Threat Intelligence Indicator
- URL

It would be beneficial to have the option—via toggles or other means—to allow customers with sufficiently large datasets to split out the different event types to improve their experience when creating detections and subsequent IR-related searches. 

For example, an optional toggle for each event type. 
When the toggle is not enabled, it will continue to be combined in the `event` data stream.
When the toggle is enabled, that event type will go to its own data stream. 

Problem
For customers with a large SentinelOne deployment, the centralised grouping makes it challenging to set retention for different event types separately or perform actions on a specific event type —customers currently need to create custom artefacts to achieve this. 

To further support large deployments, it would also be beneficial to have an option to conditionally set to namespace based on a target field. For example, a field that indicates the endpoint type.

**Comment by efd6** [comment]
The change at #10258 allows users to split event categories out of the `sentinel_one_cloud_funnel.event` data stream into a separate data stream named from the `event.category`. This allows e.g. large event categories to be sent to a separate data stream away from the rest, improving search efficiency. The name of the field under `sentinel_one_cloud_funnel. …` remains `event` for two reasons: 1. specialising the name to match the data stream name would take the `event` data stream field count above the 2048 field limit; and 2. search terms would be different between cases using split data streams and unsplit data streams — as it is currently, the only change between searches would be the `datastream.dataset` term.
