### ISSUE TITLE
[Oracle integration] Tablespace total bytes calculation is wrong

### ISSUE THREAD

**Issue by norgro2601** [elastic/integrations#10077]
In the Oracle integration, the calculation for the field "oracle.tablespace.space.total.bytes" is wrong. 

**Results in Discover**

![image](https://github.com/elastic/integrations/assets/13552087/0020b371-b06f-4d02-a78a-e2f7905199f3)

**Results in Oracle client**

![image](https://github.com/elastic/integrations/assets/13552087/c3d43aeb-0804-43c9-8134-275022cb9de4)

Kind regards
Norbert

**Comment by gurbelunder** [comment]
Definitive +1 vote for changing this! One SELECT against an Oracle database for clear information to tablespaces would be:

`SELECT a.tablespace_name as tablespace_name, (a.used_space * b.block_size) as used_space, (a.tablespace_size * b.block_size) as actual_max_size, a.used_percent FROM dba_tablespace_usage_metrics a join dba_tablespaces b ON a.tablespace_name = b.tablespace_name
ORDER BY a.used_percent DESC;`

**Comment by niraj-elastic** [comment]
Hey @norgro2601 & @gurbelunder,
We are working on which new metrics can be added to integration as enhancement to our current oracle integration. But till than you can derive important information from current fields, As for now our current query also provides required metrics i.e user can get extended size of datafile from [MAX_BYTES](https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/DBA_DATA_FILES.html#:~:text=Autoextensible%20indicator-,MAXBYTES,-NUMBER) metrics and also total_space for any individual tablespace can also be calculated by summing up used_space and free_space.

**Comment by niraj-elastic** [comment]
The support of extended space metrics is provided now in integration.
PR :- https://github.com/elastic/integrations/pull/10671
