### ISSUE TITLE
[akamai.siem] Various pipeline errors

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#10084]
There are various pipeline failures occurring while processing data from Akamai SIEM. I'm working on getting `event.original` samples that I can share.

Package: 2.23.2
Stack: 8.13.4

-------
> Processor 'convert' failed with message 'For input string: \"\"'

The original value has an empty `userRiskData.score` like:

```json
{
  "userRiskData": {
    "score": ""
  }
}
```

-------

> Processor 'conditional' with tag 'kv_userRiskData_general' failed with message 'field [json.userRiskData.general] does not contain value_split [:]'

-------
> Processor 'script' with tag 'script_base64_decode_attackData_rule' failed with message 'Input byte array has wrong 4-byte ending unit'

-------
> Processor 'urldecode' with tag 'urldecode_httpMessage_query' failed with message 'URLDecoder: Incomplete trail escape (%) pattern'

**Comment by efd6** [comment]
Change [here](#10158), but waiting for non-fabricated test inputs.
