### ISSUE TITLE
[Juniper JUNOS] Syslog Message 

### ISSUE THREAD

**Issue by daniterras** [elastic/integrations#10093]
Kibana version: 8.13.3
Elasticsearch version: 8.13.3

My syslog messages have the following format:

"<132>Jun  5 16:58:16 host01 inetd[1169]: %DAEMON-4: /usr/sbin/sshd[91073]: exited, status 255"

The hostname field appears empty.
The pipeline for the lastest junos integration (version 1.2.0) is not analysing messages correctly.

**Comment by norrietaylor** [comment]
Hello @daniterras, the Juniper JUNOS integration was released in an experimental state and is now deprecated. The recommendation is to use the SRX package instead. 

I see you have opened an [issue](https://github.com/elastic/integrations/issues/10094) for that integration. I will close this issue and the team will follow up with your concerns there.
