### ISSUE TITLE
[RFC] Crowdstrike unified Device ID

### ISSUE THREAD

**Issue by tomsonpl** [elastic/integrations#10121]
Hey 👋 
In Defend Workflows team we are working towards implementing bi-directional actions against Crowdstrike. For most of the actions we need to know the crowdstrike device id but it is held in different crowdstrike fields and not always mapped to ECS.
Was there a reason for not mapping it to one unified field? If not, it would help us with maintaining the consistency on our side. 
If you're busy, I am happy to do it myself, but wanted to get your feedback first, and a suggested unified field name :) 

Fields: 
1. Alert -  `crowdstrike.alert.device.id` (I think it's being mapped to `device.id`)
2. Falcon - `crowdstrike.event.DeviceId` (I don't think it's being mapped)
3. FDR - `crowdstrike.DeviceId` (I don't think it's being mapped)

Thank you in advance!

**Comment by kcreddy** [comment]
> Falcon - crowdstrike.event.DeviceId (I don't think it's being mapped)

The `device.id` for Falcon seems to be mapped from `crowdstrike.event.SensorId` as per https://github.com/elastic/integrations/blob/8cbfb3f7eea589f4dcca8195f84f0589c095dd26/packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/mobile_detection_summary.yml#L107-L111
But this only seems to be applicable for [`MobileDetectionSummaryEvent`](https://github.com/elastic/integrations/blob/main/packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/default.yml#L208-L211)

Looking at the difference between [SensorId](https://github.com/elastic/integrations/blob/main/packages/crowdstrike/data_stream/falcon/fields/fields.yml#L308-L311) and [DeviceId](https://github.com/elastic/integrations/blob/main/packages/crowdstrike/data_stream/falcon/fields/fields.yml#L667-L670), I couldn't make any difference. I don't have the documentation with me, but a publicly available document for [Crowdstrike Falcon](https://www.crowdstrike.com/wp-content/uploads/2022/12/CrowdStrike-Falcon-Device-Technical-Add-On-Guide-v3.1.5.pdf) suggests they are the same thing as per:
> It’s important to keep in mind that a ‘device’ in CrowdStrike is identified by the sensor ID

Also, based on the sample logs, I don't see `SensorId` and `DeviceId` inside the same event. It could be that certain versions of the device have `SensorId`, while others `DeviceId`.

If thats the case, we could possibly have somewhere in `default.yml` after pipeline [MobileDetectionSummaryEvent](https://github.com/elastic/integrations/blob/main/packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/default.yml#L208-L211)
```
  - rename:
      field: crowdstrike.event.DeviceId
      target_field: device.id
      ignore_missing: true
      tag: rename_deviceid
      if: ctx.device?.id == null
```

> FDR - crowdstrike.DeviceId (I don't think it's being mapped)

This is true. But, here again there are 2 fields `SensorId` and `DeviceId`, which could be mapped to `device.id` similarly.

@tomsonpl if you haven't started working on it yet, I can come up with a PR later today and get feedback from the team.

**Comment by tomsonpl** [comment]
Interesting, I didn't notice the `sensorId` field, but it makes sense. Our end goal would be to have one unified field for device/sensor id's value, so regardless the type of the document we can use it as our parameters to API requests. 
I haven't started working on it, wanted to get your opinion first, so I'll happily wait for your outcome. 
Thank you very much @kcreddy 🙇

**Comment by tomsonpl** [comment]
Thank you @kcreddy 👍
