### ISSUE TITLE
[AWS] AWS ELB metrics integration OOTB Dashboard does not reflect ALBs data for Inbound and Outbound Traffic Visualisations

### ISSUE THREAD

**Issue by seahsiungee** [elastic/integrations#10149]
The Visualisations for Inbound and Outbound traffic in this OOTB dashboard utilises data from `source.bytes` and `destination.bytes` fields. 

The integration's [ingest pipeline](https://github.com/elastic/integrations/blob/dfc057e4908d28fbe9f676ee4e3e0bdbe67cd35b/packages/aws/data_stream/elb_logs/elasticsearch/ingest_pipeline/default.yml) is currently only parsing and populating these fields for TCP Logs from Classic ELB & NLB.

It seems the values parsed from ALB logs to populate `http.request.body.bytes` and `http.response.body.bytes` fields should also be used to populate `source.bytes` and `destination.bytes` fields to address this issue.

**Comment by agithomas** [comment]
Related issue : https://github.com/elastic/integrations/issues/5953

**Comment by Dariaus999** [comment]
@agithomas - any update on this case? If it does, please kindly give us a status update 🙏

**Comment by agithomas** [comment]
@Dariaus999 , there are a few related issues which are tracked under [here](https://github.com/elastic/integrations/issues/10151) 

I have requested the team to include the tasks in the upcoming sprints. [Reference](https://github.com/elastic/integrations/issues/10151#issuecomment-2180421534)

**Comment by Dariaus999** [comment]
@agithomas - sorry to bother you, but the customer pinged me for this case, so how is the progress for the sprints so far?
Is there anything you'd be able to share with the customer at this point?

**Comment by agithomas** [comment]
Hello @Dariaus999 , @anil-elastic  is presently working on the enhancements. 

The PR details are [here](https://github.com/elastic/integrations/pull/10444). 

As you can see, the existing dashboard shows data from all three categories of Load balancers, which causes confusion among the users - why certain panels are not populated. So, we are splitting the dashboards into three, one for each specific category. As part of the change, we will additionally include the `http.request.body.bytes` and `http.response.body.bytes` to ALB dashboard.

Adding @lalit-satapathy to help to prioritise the task.

**Comment by agithomas** [comment]
@Dariaus999 / @lalit-satapathy ,

if the customer is very keen to have an immediate solution, we can think of having `http.request.body.bytes` and `http.response.body.bytes` added to the existing (unified) dashboard. And, the long-term approach mentioned [here](https://github.com/elastic/integrations/issues/10149#issuecomment-2224298460) will follow.

**Comment by Dariaus999** [comment]
@agithomas - Thank you for getting back to me so quickly.
Just the customer is frustrated for so long without any progress, I guess.
I will share your information with customer and contact again if necessary

**Comment by anil-elastic** [comment]
This fix will be available in AWS package version 2.19.0 but customer can also update the dashboard manually.

- Make sure to use the default space.
- Go to the Stack Management->Saved Object and search for the [Logs AWS] ELB Access Log Overview and delete it.
- After doing this import the below provided ndjson (This ndjson is default ndjson that is provided by default in package, it has correct ID mappings)
- Filename: export.ndjson
-  You can download the file here:
-  https://upload.elastic.co/d/19bc2a5f5c70644fb1cd1fef0b7d0bc0fd38f4e6a6b1420b58bf63f21c2260ef
-  Use this Authorization Token: ab85fa6d5acbb66f

**Comment by Dariaus999** [comment]
@anil-elastic - Thank you for your update 🙏 
I will share information with the customer

**Comment by Dariaus999** [comment]
Hi @anil-elastic 

The customer sent me feedback as follows
`Following the steps, you provided the [Logs AWS] ELB Access Log Overview, however, it cannot be deleted because it is an Elastic Managed Object
Please suggest how to delete it.`


- Make sure to use the default space.
- Go to the Stack Management->Saved Object and **search for the [Logs AWS] ELB Access Log Overview and delete it.**
