### ISSUE TITLE
Prepare requested resources visualizations for Kubernetes Observability

### ISSUE THREAD

**Issue by eedugon** [elastic/integrations#1014]
On Kubernetes is very common to take a look at the overall resources `requested / reserved` (not in use) at different levels:
- Cluster wide
- Per node.

When doing `kubectl describe node` we can clearly see something like:

```
  Resource                   Requests      Limits
  --------                   --------      ------
  cpu                        1073m (27%)   2210m (56%)
  memory                     6924Mi (52%)  7324Mi (55%)
  ephemeral-storage          0 (0%)        0 (0%)
  hugepages-2Mi              0 (0%)        0 (0%)
  attachable-volumes-gce-pd  0             0
```

Today the majority of dashboards for Kubernetes monitoring allow the user to visualize quickly the overall (or per node) amount of CPU and memory requested.

In our current dashboards we focus on resource `in use`, which is nice but we don't have anything about `requested` resources or limits (maybe limits is not that interesting).

Taking a look at the documented metrics from our Metricbeat module and doing some tests I guess that we have defined the metrics:
- kubernetes.container.cpu.request.cores
- kubernetes.container.cpu.request.nanocores

But I believe (i could be wrong) we are not populating them.

So if we want to achieve this we probably need to solve both parts (receiving the metrics + preparing the UI at some level (dashboards, observability app, ...)

**Comment by sorantis** [comment]
cc @ChrsMark

**Comment by MichaelKatsoulis** [comment]
> Taking a look at the documented metrics from our Metricbeat module and doing some tests I guess that we have defined the metrics:
> 
> * kubernetes.container.cpu.request.cores
> * kubernetes.container.cpu.request.nanocores
> 
> But I believe (i could be wrong) we are not populating them.
> 

@eedugon you are right that we are collecting these metrics but the reason you don't see them populated is probably the version of `kube-state-metrics`.  Since `v2.0.0` they  deprecated those fields (they are replaced with new. Thy used to co-exist for some versions). [breaking changes](https://github.com/kubernetes/kube-state-metrics/blob/master/CHANGELOG.md#v200-alpha--2020-09-16)
There is an issue https://github.com/elastic/beats/issues/21520 to support these changes and we will focus on that in the near future. 
After the issue is fixed we could also add a visualisation

**Comment by eedugon** [comment]
Awesome! Great analysis, thanks!

**Comment by MichaelKatsoulis** [comment]
> Awesome! Great analysis, thanks! El El jue, 12 ago 2021 a las 15:43, Michael Katsoulis < ***@***.***> escribió:
> […](#)

In matter of fact we are already working on https://github.com/elastic/beats/pull/27552 to support the newer versions of kube-state-metrics and populate the fields.

**Comment by ChrsMark** [comment]
We are in an effort to improve/optimise our dashboards at https://github.com/elastic/beats/issues/31021. @MichaelKatsoulis maybe these metrics are some to consider too?

**Comment by MichaelKatsoulis** [comment]
Yes indeed. These are useful metrics we could visualise.
