### ISSUE TITLE
Microsoft Exchange Online Message Trace documentation

### ISSUE THREAD

**Issue by NeuvilleM** [elastic/integrations#10145]
Please update the respective documentation to contain the following information:

The App Registration should contain the following API permissions:
- Office 365 Exchange Online > ReportingWebService.Read.All (application)
https://learn.microsoft.com/en-gb/previous-versions/office/developer/o365-enterprise-developers/jj984325(v=office.15)#specify-the-permissions-your-app-requires-to-access-the-reporting-web-service

The supported roles are Global Reader and Security Reader according to the Microsoft documentation.
https://learn.microsoft.com/en-gb/previous-versions/office/developer/o365-enterprise-developers/jj984325(v=office.15)#assign-azure-ad-roles-to-the-application

https://github.com/elastic/integrations/tree/efc03f6d264ee8287587f19eee7e83ed66ba94e4/packages/microsoft_exchange_online_message_trace#service-app-configuration

**Comment by efd6** [comment]
@NeuvilleM The text in the documentation includes "NOTE: Make sure that at least one role includes the ReportingWebService.Read.All permission. For detailed steps, see [Microsoft's Assign Azure AD Roles to Users](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/manage-roles-portal) topic." and the Global Reader and Security Reader are listed in the roles above that sentence.

Can you clarify what you think is missing and should be added?

**Comment by NeuvilleM** [comment]
@efd6 The text refers to a role while it's the app registration that (also) requires the permission. See the following screenshots for reference.

![image](https://github.com/elastic/integrations/assets/6162251/46221ae3-da15-443d-b869-35a5847e592b)

I even doubt that the application itself must be granted one of the roles, but currently not verified.
Following the procedures as in the docs, it only worked after assigning the permissions (application permission should be sufficient) as in the screenshot.

**Comment by efd6** [comment]
@NeuvilleM Thanks. Before I make a change it would be good to confirm the minimum set of permissions.

**Comment by NeuvilleM** [comment]
@efd6 I've tested two setup and a successful integration required both of the following:

1. App registration must be added to either the security readers role, or global reader role.
2. The API permission must be added to the app registration.

![image](https://github.com/elastic/integrations/assets/6162251/609af779-ae7b-4738-9198-3bb74dbb5e8e)
![image](https://github.com/elastic/integrations/assets/6162251/5c18cd0c-656a-4ac1-8d80-f6977fe0cfe4)

After that, message flow reporting is working.
