### ISSUE TITLE
RabbitMQ - add shovel status

### ISSUE THREAD

**Issue by a03nikki** [elastic/integrations#1015]
**Describe the enhancement:**

Add the [shovel status](https://www.rabbitmq.com/shovel.html#status) to the metrics collected for RabbitMQ.

**Describe a specific use case for the enhancement or feature:**

This status indicates if messages are being picked up and dropped off from the queue.  Checking this plugin is included in the [RabbitMQ monitoring guide](https://www.rabbitmq.com/monitoring.html#readiness-probes).

**Comment by ritalwar** [comment]
Need to decide if we want to implement the other way i.e in integrations only by using http input for shovel data stream in integrations, so that no dependency on beats change.
