### ISSUE TITLE
logs-panw.panos-3.26.0-gtp CSV Processor does not parse for action_source

### ISSUE THREAD

**Issue by dparker61** [elastic/integrations#10167]
While the panw.panos.action_source mapping was added in 3.26, the GTP ingest pipeline has not had its CSV processor updated to accommodate the action source value, leading to this pipeline error:

Text '0' could not be parsed at index 0, Text 'from-policy' could not be parsed at index 0, Text 'from-policy' could not be parsed at index 0, For input string: "2024/06/17 09:35:10", For input string: "2024/06/17 09:35:10"

This is an example message with IP addresses removed:
1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4,Apple Business Manager Site - URL,xxx\username,,web-browsing,vsys1,GlobalProtect VPN,Untrust,tunnel.10,ethernet1/1,default,2024/06/17 09:39:28,698539,1,54616,443,12161,443,0x140001c,tcp,allow,Unknown,,,Unknown,,,0,0,0,0,Unknown,0,0,0,0,0,7374809256434710405,0x8000000000000000,Azure VPN,United States,,11,0,0,0,,pgazpdinfpafw01,0,,0,,HTTP2-CONNECTION,12219,3714,8505,39,21,18,0,0,0,0,0,0,tcp-fin,from-policy,2024/06/17 09:35:10,241,,,0,21eed2b5-bce8-4cd3-bf75-5cbeb0f88e5c,0,,,,,,,,,2024-06-17T09:39:28.834-07:00,0,0,0,internet-utility,general-internet,browser-based,4,"used-by-malware,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use",,web-browsing,no,no

**Comment by pkoutsovasilis** [comment]
hello @dparker61 👋 

according to [pan-os official documentation](https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/gtp-log-fields) `Action Source` is not part of GTP logs where for [Traffic logs](https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/traffic-log-fields) this is there. To have a better look on this one can you supply us with the full raw log entry?

**Comment by dparker61** [comment]
The raw log entry is in the original post, or are you looking for something else? Perhaps the event was miscategorized to GTP?

**Comment by pkoutsovasilis** [comment]
I think that the raw log entry should start with `2024/06/17 09:35:10` and not `1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4`, right?

**Comment by dparker61** [comment]
Oh, I see what you mean, sorry. That was from the message field. I need to turn on preserve original on the agent, and I will post shortly. Thanks!

**Comment by dparker61** [comment]
Here is event.original. I overwrote the IP addresses and hostname because the customer was concerned about having that blowing around the internet :-) 

<14>1 2024-06-18T09:52:29-07:00 customer.xxxx - - - - 1,2024/06/18 09:52:29,007157000004949,GTP,end,2562,2024/06/18 09:52:29,1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4,Apple Business Manager Site - URL,opuc\gdmartin,,web-browsing,vsys1,GlobalProtect VPN,Untrust,tunnel.10,ethernet1/1,default,2024/06/18 09:52:29,110512,1,53420,443,60127,443,0x140001c,tcp,allow,Unknown,,,Unknown,,,0,0,0,0,Unknown,0,0,0,0,0,7374809256434782247,0x8000000000000000,Azure VPN,United States,,11,0,0,0,,pgazpdinfpafw01,0,,0,,HTTP2-CONNECTION,9881,3708,6173,39,21,18,0,0,0,0,0,0,tcp-fin,from-policy,2024/06/18 09:48:14,240,,,0,21eed2b5-bce8-4cd3-bf75-5cbeb0f88e5c,0,,,,,,,,,2024-06-18T09:52:29.506-07:00,0,0,0,internet-utility,general-internet,browser-based,4,"used-by-malware,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use",,web-browsing,no,no

**Comment by dparker61** [comment]
Customer is running PANOS 10.2.9-h1

**Comment by pkoutsovasilis** [comment]
Hi again @dparker61 after analysing the message you posted above I found that there is an extra `comma` that makes fields not aligned with the official pan-os documentation. Take a look below to the field `Elapsed Time` this should be one row up. And as a matter of fact if I replace the substring of `hostname01,0,,0` with `hostname01,0,0` in your original message this is getting digested just fine. 

| GTP Log Fields               | message field                                                                                        | GPT csv mapping                            |
| ---------------------------- | ---------------------------------------------------------------------------------------------------- | ------------------------------------------ |
| FUTURE_USE                   | 1 2024-06-18T09:52:29-07:00 customer.xxxx - - - - 1                                                  |                                            |
| Receive Time                 | 2024/06/18 9:52:29                                                                                   |                                            |
| Serial Number                | 7157000004949                                                                                        |                                            |
| Type                         | GTP                                                                                                  |                                            |
| Threat/Content Type          | end                                                                                                  |                                            |
| FUTURE_USE                   | 2562                                                                                                 |                                            |
| Generated Time               | 2024/06/18 9:52:29                                                                                   |                                            |
| Source Address               | 1.1.1.1                                                                                              | \- panw.panos.source.ip                    |
| Destination Address          | 2.2.2.2                                                                                              | \- panw.panos.destination.ip               |
| FUTURE_USE                   | 3.3.3.3                                                                                              | \- \_temp_.future_use1                     |
| FUTURE_USE                   | 4.4.4.4                                                                                              | \- \_temp_.future_use2                     |
| Rule Name                    | Apple Business Manager Site - URL                                                                    | \- panw.panos.ruleset                      |
| FUTURE_USE                   | domain\\username                                                                                     | \- \_temp_.future_use3                     |
| FUTURE_USE                   |                                                                                                      | \- \_temp_.future_use4                     |
| Application                  | web-browsing                                                                                         | \- panw.panos.network.application          |
| Virtual System               | vsys1                                                                                                | \- panw.panos.virtual_sys                  |
| Source Zone                  | GlobalProtect VPN                                                                                    | \- panw.panos.source.zone                  |
| Destination Zone             | Untrust                                                                                              | \- panw.panos.destination.zone             |
| Inbound Interface            | tunnel.10                                                                                            | \- panw.panos.inbound_interface            |
| Outbound Interface           | ethernet1/1                                                                                          | \- panw.panos.outbound_interface           |
| Log Action                   | default                                                                                              | \- panw.panos.log_profile                  |
| FUTURE_USE                   | 2024/06/18 9:52:29                                                                                   | \- \_temp_.future_use5                     |
| Session ID                   | 110512                                                                                               | \- panw.panos.flow_id                      |
| FUTURE_USE                   | 1                                                                                                    | \- \_temp_.future_use6                     |
| Source Port                  | 53420                                                                                                | \- panw.panos.source.port                  |
| Destination Port             | 443                                                                                                  | \- panw.panos.destination.port             |
| FUTURE_USE                   | 60127                                                                                                | \- \_temp_.future_use7                     |
| FUTURE_USE                   | 443                                                                                                  | \- \_temp_.future_use8                     |
| FUTURE_USE                   | 0x140001c                                                                                            | \- \_temp_.future_use9                     |
| Protocol                     | tcp                                                                                                  | \- panw.panos.protocol                     |
| Action                       | allow                                                                                                | \- panw.panos.action                       |
| GTP Event Type               | Unknown                                                                                              | \- panw.panos.event_type                   |
| MSISDN                       |                                                                                                      | \- panw.panos.msisdn                       |
| Access Point Name            |                                                                                                      | \- panw.panos.access_point.name            |
| Radio Access Technology      | Unknown                                                                                              | \- panw.panos.radio_access_technology_type |
| GTP Message Type             |                                                                                                      | \- panw.panos.message_type                 |
| End User IP Address          |                                                                                                      | \- panw.panos.end_ip_address               |
| Tunnel Endpoint Identifier1  | 0                                                                                                    | \- panw.panos.tunnel_endpoint.identifier1  |
| Tunnel Endpoint Identifier2  | 0                                                                                                    | \- panw.panos.tunnel_endpoint.identifier2  |
| GTP Interface                | 0                                                                                                    | \- panw.panos.interface                    |
| GTP Cause                    | 0                                                                                                    | \- panw.panos.cause_code                   |
| Severity                     | Unknown                                                                                              | \- panw.panos.severity                     |
| Serving Country MCC          | 0                                                                                                    | \- panw.panos.mcc                          |
| Serving Network MNC          | 0                                                                                                    | \- panw.panos.mnc                          |
| Area Code                    | 0                                                                                                    | \- panw.panos.area_code                    |
| Cell ID                      | 0                                                                                                    | \- panw.panos.cell.id                      |
| GTP Event Code               | 0                                                                                                    | \- panw.panos.event_code                   |
| FUTURE_USE                   | 7374809256434782247                                                                                  | \- \_temp_.future_use10                    |
| FUTURE_USE                   | 0x8000000000000000                                                                                   | \- \_temp_.future_use11                    |
| Source Location              | Azure VPN                                                                                            | \- \_temp_.srcloc                          |
| Destination Location         | United States                                                                                        | \- \_temp_.dstloc                          |
| FUTURE_USE                   |                                                                                                      | \- \_temp_.future_use12                    |
| FUTURE_USE                   | 11                                                                                                   | \- \_temp_.future_use13                    |
| FUTURE_USE                   | 0                                                                                                    | \- \_temp_.future_use14                    |
| FUTURE_USE                   | 0                                                                                                    | \- \_temp_.future_use15                    |
| FUTURE_USE                   | 0                                                                                                    | \- \_temp_.future_use16                    |
| FUTURE_USE                   |                                                                                                      | \- \_temp_.future_use17                    |
| FUTURE_USE                   | hostname01                                                                                           | \- \_temp_.future_use18                    |
| Tunnel ID/IMSI               | 0                                                                                                    | \- panw.panos.imsi                         |
| Monitor Tag/IMEI             |                                                                                                      | \- panw.panos.imei                         |
| FUTURE_USE                   | 0                                                                                                    | \- \_temp_.future_use19                    |
| FUTURE_USE                   |                                                                                                      | \- \_temp_.future_use20                    |
| FUTURE_USE                   | HTTP2-CONNECTION                                                                                     | \- \_temp_.future_use21                    |
| FUTURE_USE                   | 9881                                                                                                 | \- \_temp_.future_use22                    |
| FUTURE_USE                   | 3708                                                                                                 | \- \_temp_.future_use23                    |
| FUTURE_USE                   | 6173                                                                                                 | \- \_temp_.future_use24                    |
| FUTURE_USE                   | 39                                                                                                   | \- \_temp_.future_use25                    |
| FUTURE_USE                   | 21                                                                                                   | \- \_temp_.future_use26                    |
| FUTURE_USE                   | 18                                                                                                   | \- \_temp_.future_use27                    |
| FUTURE_USE                   | 0                                                                                                    | \- \_temp_.future_use28                    |
| FUTURE_USE                   | 0                                                                                                    | \- \_temp_.future_use29                    |
| FUTURE_USE                   | 0                                                                                                    | \- \_temp_.future_use30                    |
| FUTURE_USE                   | 0                                                                                                    | \- \_temp_.future_use31                    |
| FUTURE_USE                   | 0                                                                                                    | \- \_temp_.future_use32                    |
| FUTURE_USE                   | 0                                                                                                    | \- \_temp_.future_use33                    |
| FUTURE_USE                   | tcp-fin                                                                                              | \- \_temp_.future_use34                    |
| Start Time                   | from-policy                                                                                          | \- panw.panos.start_time                   |
| Elapsed Time                 | 2024/06/18 9:48:14  🔴 **This should be one row up**                                                 | \- panw.panos.elapsed_time                 |
| Tunnel Inspection Rule       | 240          🔴 **This should be one row up**                                                        | \- panw.panos.tunnel_inspection_rule       |
| Remote User IP               |                                                                                                      | \- panw.panos.remote_user.ip               |
| Remote User ID               |                                                                                                      | \- panw.panos.remote_user.id               |
| UUID for rule                | 0                                                                                                    | \- panw.panos.rule_uuid                    |
| PCAP ID                      | 21eed2b5-bce8-4cd3-bf75-5cbeb0f88e5c                                                                 | \- panw.panos.pcap_id                      |
| High Resolution Timestamp    | 0                                                                                                    | \- \_temp_.high_res_timestamp              |
| A Slice Service Type         |                                                                                                      | \- panw.panos.nsdsai_sst                   |
| A Slice Differentiator       |                                                                                                      | \- panw.panos.nsdsai_sd                    |
| Application Subcategory      |                                                                                                      | \- panw.panos.application.sub_category     |
| Application Category         |                                                                                                      | \- panw.panos.application.category         |
| Application Technology       |                                                                                                      | \- panw.panos.application.technology       |
| Application Risk             |                                                                                                      | \- panw.panos.application.risk_level       |
| Application Characteristic   |                                                                                                      | \- panw.panos.application.characteristics  |
| Application Container        |                                                                                                      | \- panw.panos.application.container        |
| Application SaaS             | 2024-06-18T09:52:29.506-07:00                                                                        | \- panw.panos.application.is_saas          |
| Application Sanctioned State | 0                                                                                                    | \- panw.panos.application.is_sanctioned    |
|                              | 0                                                                                                    |                                            |
|                              | 0                                                                                                    |                                            |
|                              | internet-utility                                                                                     |                                            |
|                              | general-internet                                                                                     |                                            |
|                              | browser-based                                                                                        |                                            |
|                              | 4                                                                                                    |                                            |
|                              | used-by-malware,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use |                                            |
|                              |                                                                                                      |                                            |
|                              | web-browsing                                                                                         |                                            |
|                              | no                                                                                                   |                                            |
|                              | no                                                                                                   |                                            |

**Comment by dparker61** [comment]
Hmmm. The format seems to map to a [Tunnel Inspection log](https://docs.paloaltonetworks.com/pan-os/11-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/tunnel-inspection-log-fields), but the type field is GTP where the type for Tunnel Inspection logs should be START or END, according to the doc.

The value in "from-policy" in our example is definitely an Action Source value, and the CSV does not include it, so I'm not sure why you think it is an extra comma rather than the from-policy value that is throwing things off. But I take your point that Action Source is not documented as part of the GTP log.

Thank you for looking into this. I would like to keep the ticket open while I investigate if there were local customizations, because the type of log record is clearly GTP. I will post what we find with further questions or close with comment. Thanks again!

**Comment by pkoutsovasilis** [comment]
> The value in "from-policy" in our example is definitely an Action Source value, and the CSV does not include it, so I'm not sure why you think it is an extra comma rather than the from-policy value that is throwing things off. But I take your point that Action Source is not documented as part of the GTP log.

yep you are right, maybe that's the extra field that throws off the rest of the fields. Not sure why this comma got my attention 😄

> Thank you for looking into this. I would like to keep the ticket open while I investigate if there were local customizations, because the type of log record is clearly GTP. I will post what we find with further questions or close with comment. Thanks again!

of course no prob at all! looking forward to hearing any updates from your investigation

**Comment by pkoutsovasilis** [comment]
hi @dparker61 👋  any news? can we close this issue?

**Comment by dparker61** [comment]
The customer is STILL going back and forth with Palo Alto support. Support
have finally been convinced that the logs being sent by the device a) do
not confirm to their documentation, and b) are being stamped with type GTP
even though GTP is not enabled anywhere in the customer’s network. Another
team in the Palo Alto side is getting involved.

I am still planning to update this ticket with final result, but it’s also
fine with me if it needs to be closed - the issue is clearly not with the
integration 😎

**Comment by pkoutsovasilis** [comment]
thanks for the update @dparker61 this is really helpful. I will leave it up to @qcorporation to decide whether to close or not this issue. To this end, even if this issue is closed you can always post the final result here or re-open it in case the latest findings point to an integration issue

**Comment by qcorporation** [comment]
@dparker61 and @pkoutsovasilis, great collab and getting to the root cause. I'm interested in the results from Palo Alto support. Let's close the issue, but please reopen it and comment when you get a conclusion @dparker61 to the issue.
