### ISSUE TITLE
[Cisco Duo] Mapping flattened fields 

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#10176]
We are currently mapping an two important Cisco Duo field, `cisco_duo.admin.flattened` and `cisco_duo.auth.access_device.security_agents` to flattened. Although that flattened field contains valuable security information, users can't build detections from that field as it's flattened. We have sample data for `admin` but not `security_agents`

Could we fully parse the field into ECS (where possible) to ensure users can get value from it

Sample data:
```
{
  "Admins removed": 0,
  "Errors": "Admin email@domain.com (cn=test,ou=it_security,ou=standard_user_accounts,ou=it_only,ou=test_accounts,dc=test,dc=test,dc=com): Existing Duo administrator with Owner role cannot be synced\nAdmin email@domain.com (cn=test sheets,ou=office users,ou=test_accounts,dc=test,dc=test,dc=com): Existing Duo administrator with Owner role cannot be synced\nAdmin email@domain.com (cn=test ,ou=windows10,ou=test,ou=test,ou=it_only,ou=test,dc=test,dc=test,dc=com): Existing Duo administrator with Owner role cannot be synced\nAdmin test@domain.com (cn=test ,ou=windows10,ou=test,ou=test,ou=it,ou=test,dc=test,dc=test,dc=com): Existing Duo administrator with Owner role cannot be synced\nAdmin test@domain.com (cn=test,ou=office users,ou=test,dc=test,dc=test,dc=com): Existing Duo administrator with Owner role cannot be synced",
  "Admins added": 0,
  "Admins seen": 17,
  "Sync Ref. Code": "0b6698e1489fe98319d2ff931070bb0f",
  "Duration": "0:00:01",
  "Admins modified": 0
}
```

**Comment by efd6** [comment]
Can I clarify that that data is a partial component of the administrator logs. It looks like it is the Duo "description" field and this matches the ingest pipeline.

It's not clear to me how much we can get from that field. The documentation for it in [admin logs](https://duo.com/docs/adminapi#administrator-logs) says that it is a

> String detailing what changed, either as free-form text or serialized JSON.
>
> When the description contains JSON it may be either a serialized object or a serialized array of objects. Each key in the object(s) corresponds to a property that was changed. This JSON is intended only to summarize the change, not to be de-serialized.
>
> The first example below is for a "user_update" action. The object that changed was a user whose Duo username is "jsmith". The change saved new values for the user's "notes" and "realname" fields, overwriting the previous values if any were set. They correspond to the similarly named fields in the Modify User call in the Admin API and the User Details page in the Duo Admin Panel.
> ```
> {
>   "stat": "OK",
>   "response": [{
>       "action": "user_update",
>       "description": "{\"notes\": \"Joe asked for their nickname to be displayed instead of Joseph.\", \"realname\": \"Joe Smith\"}",
>       "isotimestamp": "2020-01-24T15:09:42+00:00",
>       "object": "jsmith",
>       "timestamp": 1579878582,
>       "username": "admin"
>   }]
> }
> ```
> The second example shows an "admin_login_error" action. The administrator's login attempt failed because the admin attempted to use SSO but, as indicated by the "error" in the description, SAML login is disabled for administrators on that account.
> ```
> {
>   "stat": "OK",
>   "response": [{
>       "action": "admin_login_error",
>       "description": "{\"ip_address\": \"10.1.23.116\", \"error\": \"SAML login is disabled\", \"email\": \"narroway@example.com\"}",
>       "isotimestamp": "2020-01-23T16:18:58+00:00",
>       "object": null,
>       "timestamp": 1579796338,
>       "username": ""
>   }]
> }
> ```

The issue is that it is explicitly free-form. So there could be anything in the text, even non JSON data (which we currently assume that it will be.

The second field is only described in the [legacy authentication logs](https://duo.com/docs/adminapi#authentication-logs-(legacy-v1)) and the description is very brief

> Reports the security agents present on the endpoint as detected by Duo Desktop. 

It gives no example beyond a couple of cases where it shows up as a `[]`.

**Comment by cpascale43** [comment]
Spoke with @AliciaKell today to gather more samples from the customer who reported this.

**Comment by AliciaKell** [comment]
Hi team:

Here is some additional sample data 
`{
  "Admins removed": 0,
  "Errors": "Admin user@company.com (cn=john doe,ou=team,ou=team_team,ou=team_team,ou=team_team,dc=team,dc=company,dc=com): Existing Duo administrator with Owner role cannot be synced\nAdmin user2@company.com (cn=jane doe,ou=location office users,ou=team_team,dc=company,dc=company,dc=com): Existing Duo administrator with Owner role cannot be synced\nAdmin user3@company.com (cn=user3 name,ou=user,ou=user_group,ou=user_group,ou=user_group,ou=user_group,dc=company,dc=company,dc=com): Existing Duo administrator with Owner role cannot be synced\nAdmin user4@company.com (cn=user5 name,ou=user,ou=user_group,ou=user_group,ou=user_group,ou=user_group,dc=location,dc=company,dc=com): Existing Duo administrator with Owner role cannot be synced\nAdmin user5@company.com (cn=user5 name,ou=location office users,ou=user_user,dc=location,dc=company,dc=com): Existing Duo administrator with Owner role cannot be synced",
  "Admins added": 0,
  "Admins seen": 17,
  "Sync Ref. Code": "c1b0d0f4b11d53705174032f496d2fe5",
  "Duration": "0:00:01",
  "Admins modified": 0
}`

`{
  "Sync Ref. Code": "e8b059eb3a7789cdb8db51aa57bb0f93"
}`

`{
  "saml_idp": "Okta",
  "role": "Help Desk",
  "ip_address": "0.0.0.0",
  "factor": "sms",
  "device": "000-000-0000",
  "primary_auth_method": "Single Sign-On"
}`

`{
  "ip_address": "0.0.0.0",
  "factor": "sms",
  "error": "Invalid passcode.",
  "email": "user@company.com"
}`

`{
  "uname": "user.name",
  "Sync Ref. Code": "1b5b4124fe810e88c9d131c83fc77785",
  "status": "Active"
}`

`{
  "Users seen": 1592,
  "Sync Ref. Code": "e12d8115153a4316206497d371bdb1b1",
  "Users added": 0,
  "Users modified": 0,
  "Duration": "0:00:27",
  "Users removed": 0
}`

`{
  "Sync Ref. Code": "8093bfc68e644bc323636675484f9f66",
  "realname": "Jane Doe"
}`

`{ "saml_idp": "Okta", "role": "Owner", "ip_address": "0.0.0.0", "factor": "webauthn", "device": "devicename", "primary_auth_method": "Single Sign-On" }`

**Comment by AliciaKell** [comment]
@cpascale43 @efd6 Please let me know if these help or if you need more :)

**Comment by cpascale43** [comment]
@narph added some sample data, do you think this still needs PM clarification?

**Comment by narph** [comment]
all good for now, thanks @cpascale43
