### ISSUE TITLE
[Threat Intelligence] [OpenCTI] Multiple issues on normalization pipelines

### ISSUE THREAD

**Issue by AlessioPaternoster** [elastic/integrations#10195]
# Overview

In our organization, we are integrating the OpenCTI platform into our Elastic Stack environment.

During these integration phases we found some issues in the OpenCTI Elastic integration, which will be explained below.

# Issues

### Handling of empty `createdBy.` OpenCTI field

`createdBy.` fields may be set to _null_ in some raw OpenCTI indicators. Currently, the `default` pipeline do not handle such a case.

The problem is related to some `rename` processors. They don't check whether the `createdBy` property is null or not.

Problematic `rename` processors could be found on lines 156, 159 in the `default` pipeline.

https://github.com/elastic/integrations/blob/main/packages/ti_opencti/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml

These `rename` processors must be changed in this way :

```
  - rename:
      field: createdBy.name
      target_field: threat.indicator.provider
      if: ctx.createdBy != null
      ignore_missing: true

  - rename:
      field: createdBy.identity_class
      target_field: opencti.indicator.creator_identity_class
      if: ctx.createdBy != null
      ignore_missing: true
```

Raw event example:

```
{"confidence":15,"created":"2022-06-21T07:08:58.222Z","createdBy":null,"description":"Simple indicator of observable {34.118.99.36}","externalReferences":{"edges":[]},"id":"a1f3e8b3-d1c0-4fca-929b-81d3570a4c3c","is_inferred":false,"killChainPhases":[],"lang":"en","modified":"2022-07-21T08:13:19.927Z","name":"34.118.99.36","objectLabel":[],"objectMarking":[],"observables":{"edges":[{"node":{"entity_type":"IPv4-Addr","id":"25ee0d9d-d68e-49e9-bf5e-ec530baa8604","observable_value":"34.118.99.36","standard_id":"ipv4-addr--b4c90ba2-9df9-50ca-870c-093d6883fb88","value":"34.118.99.36"}}],"pageInfo":{"globalCount":1}},"pattern":"[ipv4-addr:value = '34.118.99.36']","pattern_type":"stix","pattern_version":null,"revoked":true,"standard_id":"indicator--8e4329db-e015-541d-8397-3b3816d7473a","valid_from":"2022-06-21T08:11:01.786Z","valid_until":"2022-07-21T08:11:01.785Z","x_opencti_detection":false,"x_opencti_main_observable_type":"IPv4-Addr","x_opencti_score":50}
```

### Wrong dissect pattern `%{_tmp_registry.hive}\\%{_tmp_registry.key}` for Windows registry items

Sometimes, the registry hive is not specified or is not part of the key in OpenCTI Windows registry observables.

An example of this scenario is represented by the following `attribute_key` value : `{59031A47-3F72-44A7-80C5-5595FE6B30EE}`.

The dissect pattern in `ecs_from_windows_registry_key` pipeline will thrown an error if a value like the one above is found in the event.

This is due to an erroneous dissect pattern which requires the hive to be present. This behaviour breaks all remaining parsing steps.

Problematic `dissect` could be found on line 5 in the `ecs_from_windows_registry_key` pipeline.

https://github.com/elastic/integrations/blob/main/packages/ti_opencti/data_stream/indicator/elasticsearch/ingest_pipeline/ecs_from_windows_registry_key.yml

The dissect patten should be converted into a grok expression like this one : 
```
^(%{WORD:_tmp_registry.hive}\\)?%{GREEDYDATA:_tmp_registry.key}$
```

The grok expression related to the hive part could be also made more specific, by specifing the list of hives (contracted / extended form).

### Missing `event.module` field

The `event.module` field should be mandatory in threat intelligence integrations in order to use `Threat Intel * Indicator Match` rules.

`Threat Intel * Indicator Match` rules query threat intelligence events by filtering `ti_` values in `event.module` field.

A `set` processor for `event.module` should be included in the `default` pipeline with `ti_opencti` value.

```
  - set:
      field: event.module
      value: ti_opencti
```

# System Information

Development:
Elastic Stack: v. 8.11.3
OpenCTI integration: v. 2.0.0

Production
OpenCTI: v. 6.1.10 (Community)

**Comment by chrisberkhout** [comment]
Hi @AlessioPaternoster, thanks for the great clarity, examples, and suggested fixes! I'll open a PR to resolve these issues.

**Comment by AlessioPaternoster** [comment]
Thank you @chrisberkhout 👍🏻. I have a question about the PR. Is it possible to backport the fixes in the version _2.0.X_ ?

I ask because of breaking change introduced in version _2.1.0_ that now requires Elastic Stack _v8.12.X_ or above.

**Comment by chrisberkhout** [comment]
Hey @AlessioPaternoster,

The PR is https://github.com/elastic/integrations/pull/10203.

The extra null check in your suggested rename processors isn't necessary. Using `ignore_missing: true` should cover that.

I did do the specific matching of hive names and normalize them to the abbreviated form for the ECS field.

The `event.module` field was already added recently (and updated with the correct value more recently). A constant value like that can be set in the field definition. It's done [here](https://github.com/elastic/integrations/blob/efff6d2566bdda09f9f85c0bb4f9bac89f238116/packages/ti_opencti/data_stream/indicator/fields/ecs.yml#L210-L213) (and for the transform [here](https://github.com/elastic/integrations/blob/efff6d2566bdda09f9f85c0bb4f9bac89f238116/packages/ti_opencti/elasticsearch/transform/latest_ioc/fields/ecs.yml#L210-L213)).

For integrations we follow semvar but we only have one current release and don't do any backports. The change in 2.1.0 was to reduce the risk of secrets leaking out of config. That was broken in some previous versions of Kibana. If you can't upgrade the stack, you can apply this diff and build a version of the package for yourself that should work on earlier stack versions:
```diff
diff --git a/packages/ti_opencti/manifest.yml b/packages/ti_opencti/manifest.yml
index bdce9bbee3..0d58afb109 100644
--- a/packages/ti_opencti/manifest.yml
+++ b/packages/ti_opencti/manifest.yml
@@ -11,7 +11,7 @@ categories:
   - threat_intel
 conditions:
   kibana:
-    version: "^8.12.0"
+    version: "^8.10.1"
 screenshots:
   - src: /img/screenshot1.png
     title: "Dashboard: OpenCTI Overview"
@@ -57,7 +57,6 @@ policy_templates:
             multi: false
             required: false
             show_user: true
-            secret: true
           - name: oauth2
             type: yaml
             title: OAuth2 Configuration
```

Thanks again!
