### ISSUE TITLE
Fortigate Admin login successfully

### ISSUE THREAD

**Issue by janniten** [elastic/integrations#10193]
Hello,
Yesterday I was writing an EQL rule in order to detect a successfully brute force on admin account sequencing n failed logins and the one successfully login, (sequence by source.ip and user.name)
I realized that successfully login are not properly parsed: event.action, user.name and event.outcome are empty for event.code 0100032001

![image](https://github.com/elastic/integrations/assets/33020901/d3d60502-840b-4f3d-8cf6-7a59683f014d)

Adding in a custom pipeline the specific parsing for this event solved my problem (see below).
Searching for the part in the pipeline that parses the login failed (event 0100032002) I realized that the dissect is based on how the message starts and not in the event.code.
IMHO, we can take advantage of Fortinet having specific logs ids: one for login success and one for failed in order to be more precise.
From Fortinet docs:

![image](https://github.com/elastic/integrations/assets/33020901/40e8eaa2-1ec9-4f4e-9f4b-1ba52d1aeadb)

![image](https://github.com/elastic/integrations/assets/33020901/fe916595-b631-421b-a1e1-de57f05fb7da)

After adding this in my custom pipeline

```
PUT _ingest/pipeline/logs-fortinet_fortigate.log@custom
{
  "processors": [
    {
      "set": {
        "field": "event.action",
        "value": "login",
        "if": "ctx?.event?.code == '0100032001'"
      }
    },
        {
      "set": {
        "field": "event.outcome",
        "value": "success",
        "if": "ctx?.event?.code == '0100032001'"
      }
    },
     {
        "dissect": {
          "field": "message",
          "tag": "parse login success ",
          "pattern": "%{_tmp.user.roles} %{user.name} logged in %{event.outcome}fully from %{}",
         "if": "ctx?.event?.code == '0100032001'",
          "on_failure": [
            {
              "append": {
                "field": "error.message",
                "value": "Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.pipeline}}} failed with message: {{{_ingest.on_failure_message}}}"
              }
            }
          ],
          "description": "Administrator user logged in successfully from ssh(10.1.1.1)"
        }
      }
  ]
}
```
![image](https://github.com/elastic/integrations/assets/33020901/0c1b26b3-2dd9-481a-b464-e315238b29b9)

Thank you!

**Comment by pkoutsovasilis** [comment]
Hello @janniten 👋 thanks for reporting this. We have some testing logs with event code `0100032001` [here](https://github.com/elastic/integrations/blob/e0d7f6c35e03d30f024fbd15a9509290b63ee78d/packages/fortinet_fortigate/data_stream/log/_dev/test/pipeline/test-fortinet-6-2.log#L5) and they are being ingested correctly as shown [here](https://github.com/elastic/integrations/blob/e0d7f6c35e03d30f024fbd15a9509290b63ee78d/packages/fortinet_fortigate/data_stream/log/_dev/test/pipeline/test-fortinet-6-2.log-expected.json#L450). Could you update the issue description with the version of fortinet_fortigate integration and a raw log entry so we can try reproduce your findings on our end?

**Comment by janniten** [comment]
Hello @pkoutsovasilis, the event is ingested but what I said is that are not properly categorized (and I'm not seeing it in the example)

![image](https://github.com/elastic/integrations/assets/33020901/e3e0bb5b-6ba5-49d2-992c-9eca19b6ddb9)


Since is an administrator authentication login sucess IMHO it should be 
```
event.category: authentication
event.outcome: success
```

In fact event 0100032002 that is Administrator login failed **is** properly categorized as

```
event.category: authentication
event.outcome: failure
```

Thank you

**Comment by pkoutsovasilis** [comment]
Hi @janniten 👋 sorry for taking some time to look into this. So the issue is that when there two alternations of messages that capture a successful login one that contains `login` and another with `logged in` instead. Our integration didn't accommodate for the latter but I have prepared a fix PR for it 🙂
