### ISSUE TITLE
[sentinel_one] Fetch agents by UUID to enrich alert data with agent ID

### ISSUE THREAD

**Issue by chrisberkhout** [elastic/integrations#10204]
In the `sentinel_one` integration, the `alert` data stream fetches data from the `/web/api/v2.1/cloud-detection/alerts` endpoint. The response contains no agent ID, but it includes the field `agentDetectionInfo.uuid`, which we then store in `observer.serial_number`.

We'd like to use that UUID to fetch a corresponding agent ID. The `/web/api/v2.1/agents` endpoint does allow filtering for particular UUIDs.

### Additional details

We could use the request chaining functionality of the HTTP JSON input to make an additional request for the agent related to each alert, then produce an event from the parent response (use `.parent_last_response`) that includes the ID from the chained response. It would be easier to do this enrichment in CEL, but that may not offer a smooth migration path.

There are some things to verify using a [test account](https://github.com/elastic/integrations/issues/9879#issuecomment-2173796650):
- Do agent ID value differ from agent UUID values?  
  The examples in the API documentation suggest this is the case.  
  They show agent data with `"id": "13491234512345", "uuid": "XXX35XXX8Xfb4aX0X1X8X12X343X8X30"`
- Is the `agentDetectionInfo.uuid` value actually an agent UUID, or is it a UUID for a detection info record or something else?

For a bit more background on this issue, read from https://github.com/elastic/integrations/issues/9879#issuecomment-2173587844.

**Comment by kcreddy** [comment]
Working on the `/web/api/v2.1/cloud-detection/alerts` API, the response contains `agentRealtimeInfo` similar to `threat` dataset. We are currently not parsing this `agentRealtimeInfo` into `alert` dataaset. 

This `agentRealtimeInfo` object already contains the `id` related to the agent. Using the test environment, I have also verified that this `id` is same as `agent.id` obtained from calling the `/web/api/v2.1/agents` endpoint using the Agent UUID.

Created PR: https://github.com/elastic/integrations/pull/10345 to process `agentRealtimeInfo` and extract relevant fields, thus subsequently meeting requirement to add `agent.id`.
