### ISSUE TITLE
Add data_stream.dataset filters for cloud packages

### ISSUE THREAD

**Issue by milan-elastic** [elastic/integrations#10200]
As part of this task, need to add the data_stream.dataset filter across all the integrations.
Other completed infra-obs-integrations are covered as part of https://github.com/elastic/integrations/issues/9323
Following integration will be covered as part of this 
This issue will cover the cloud integration datastreams those has owner obs-infraobs-integrations 

### AWS
- [x] #10324 
- apigateway_logs
- apigateway_metrics
- billing
- cloudfront_logs
- cloudtrail
- dynamodb
- elb_logs
- elb_metrics
- emr_logs
- emr_metrics
- kinesis
- lambda
- natgateway
- rds
- redshift
- s3_storage_lens
- sns
- sqs
- transitgateway
- usage
- vpn

### Azure
- [x] #10379 
- activitylogs
- auditlogs
- identity_protection
- platformlogs
- provisioning
- signinlogs
- springcloudlogs

### GCP
- [x] #10398
- billing
- cloudrun_metrics
- cloudsql_mysql
- cloudsql_postgresql
- cloudsql_sqlserver
- dataproc
- firestore
- loadbalancing_logs
- loadbalancing_metrics
- redis

### Azure OpenAI (entire package)

- In the Azure OpenAI package Overview dashboard, the visualizations are using both metrics and logs indices. But in the dashboard level filters we can provide only one indices. There are no option to add or condition on both indices in the same filter. Hence not able to support dashboard level filter on Azure OpenAI Overview dashboard.

**Comment by harnish-elastic** [comment]
All PRs are approved and merged. Hence closing this issues
