### ISSUE TITLE
[Cisco ASA] Error in mapping UserAgent from log code 722055 to ECS field

### ISSUE THREAD

**Issue by srilumpa** [elastic/integrations#10220]
Hello,

I don't have the raw logs any more so it might be difficult to give some example but I can try to give a few pointers. Here is however the event after being processed by the pipeline:

```json
{
  "source": {
    "address": "REDACTED",
    "ip": "REDACTED",
    "user": {
      "name": "REDACTED",
      "group": {
        "name": "REDACTED"
      }
    }
  },
  "observer": {
    "hostname": "REDACTED",
    "product": "asa",
    "vendor": "Cisco",
    "type": "firewall"
  },
  "@timestamp": "2024-06-24T08:34:36.000Z",
  "ecs": {
    "version": "8.11.0"
  },
  "related": {
    "hosts": ["REDACTED"],
    "ip": ["REDACTED"],
    "user": ["REDACTED"]
  },
  "data_stream": {
    "namespace": "default",
    "type": "logs",
    "dataset": "cisco_asa.log"
  },
  "host": {
    "hostname": "REDACTED"
  },
  "event": {
    "severity": 6,
    "agent_id_status": "missing",
    "ingested": "2024-06-24T08:34:39Z",
    "code": "722055",
    "kind": "event",
    "timezone": "UTC",
    "category": ["network"],
    "type": ["connection", "info"],
    "dataset": "cisco_asa.log"
  },
  "user_agent": "Cisco AnyConnect VPN Agent for REDACTED"
}
```

It appears that the UserAgent is processed from Cisco ASA logs with code 722055 from [pipeline on line 970](packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L970) but does not seem to be normalized afterward. This breaks the ECS mapping of the (very few) logs and generates a conflict in our data views.

I am not entirely sure but may be this can be fixed by adding `722055` to the `id` array [on line 1532](https://github.com/elastic/integrations/blob/main/packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L1532), even though I don't totally get what this part of the pipeline is doing.

Thank you

**Comment by taylor-swanson** [comment]
It looks like the grok pattern for 722055 is extracting the user agent to `user_agent` instead of `user_agent.original`. I'll get a fix for that up shortly.
