### ISSUE TITLE
[qualys_vmdr.asset_host_detection] Align `cloud.*` fields with Qualys data and not elastic agent metadata

### ISSUE THREAD

**Issue by clement-fouque** [elastic/integrations#10277]
When ingesting vulnerability data, `cloud.*` fields are a mix of the Elastic agent metadata and Qualys vulnerability data. I didn't find a way to disable metadata coming from Elastic agent (`publisher_pipeline.disable_host` seems to apply to field `host` only). 

A decision must be made to either have no cloud fields set, either have only the data coming from Qualys, either from the elastic agent metadata.

I have a strong preference to remove any properties set by the elastic agent and only have data from Qualys. If we want to build dashboard with data coming from different scanning solutions (Qualys, Tenable, Snyk, ...), we'll heavily rely on ECS fields. 

We might have a rule that if the field `tags` contains `forwarded`, we use only the data from Qualys. 

Here is an example of what I'm getting
```json
"cloud": {
  "availability_zone": "us-central1-a", # Elastic agent metadata
  "instance": {
    "name": "gke-xxx", # Elastic agent metadata
    "id": "12346789" # Qualys vulnerability data
  },
  "provider": "GCP", # Qualys vulnerability data
  "service": {
    "name": "Compute Engine" # Qualys vulnerability data
  },
  "project": {
    "id": "my-project" # Elastic agent metadata
  },
  "region": "us-central1", # Elastic agent metadata
  "account": {
    "id": "my-project" # Elastic agent metadata
  }
}
```

**Comment by efd6** [comment]
@clement-fouque Would you be satisfied with setting the env var `BEATS_ADD_CLOUD_METADATA_PROVIDERS=""`? This has the effect of turning off the processor as can be seen here https://github.com/elastic/beats/blob/1ce84438ece3bfdd94fd8868365fb4fbf750256e/libbeat/processors/add_cloud_metadata/providers.go#L86-L91

**Comment by andrewkroh** [comment]
If the qualy integration can set `cloud.*` fields it sounds like we would never want to cloud fields from the Agent's environment. I think we could unconditionally remove the `cloud` field before continuing to parse the qualys JSON.

**Comment by clement-fouque** [comment]
I prefer the solution proposed by @efd6 as it gives the control to user on what he wants to do. I don't see a use case where users would want to keep elastic agent metadata but it's good to have the option though.

The ideal solution would be to have an option in the UI to select what we want to do: either set agent data, either set Qualys data.

**Comment by clement-fouque** [comment]
I'm proposing the following fields mapping as following:

| Field | Value | Comment |
|--------|--------|--------|
| cloud.account.id | qualys_vmdr.asset_host_detection.metadata.ec2.attribute (latest/dynamic/instance-identity/document/accountId) | |
| cloud.account.name | | |
| cloud.availability_zone | qualys_vmdr.asset_host_detection.metadata.google.attribute (zone)<br/> qualys_vmdr.asset_host_detection.metadata.ec2.attribute (latest/dynamic/instance-identity/document/availabilityZone) | Extract value from the attribute array |
| cloud.instance.id | qualys_vmdr.asset_host_detection.cloud_resource_id | ✅ Already implemented |
| cloud.instance.name | qualys_vmdr.asset_host_detection.dns_data.hostname | | 
| cloud.machine.type | qualys_vmdr.asset_host_detection.metadata.google.attribute (machineType) <br/> qualys_vmdr.asset_host_detection.metadata.ec2.attribute (latest/dynamic/instance-identity/document/instanceType)| Extract value from the attribute array | 
| cloud.project.id | qualys_vmdr.asset_host_detection.metadata.google.attribute (projectIdNo) <br/> qualys_vmdr.asset_host_detection.metadata.azure.attribute (subscriptionId) | Extract value from the attribute array | 
| cloud.project.name | qualys_vmdr.asset_host_detection.metadata.google.attribute (projectId) | Extract value from the attribute array | 
| cloud.provider | qualys_vmdr.asset_host_detection.cloud_provider | ✅ Already implemented |
| cloud.region | qualys_vmdr.asset_host_detection.metadata.ec2.attribute (latest/dynamic/instance-identity/document/region) <br/>  qualys_vmdr.asset_host_detection.metadata.azure.attribute (location) | No field available for GCP | 
| cloud.service.name | qualys_vmdr.asset_host_detection.cloud_service | ✅ Already implemented |

**Comment by efd6** [comment]
@clement-fouque Can you clarify the significance of the values in parens in the Value column and also provide test data (XML is fine) that includes the source values for testing? Also, I don't see any field in the XSD that looks like it would give a value for the `cloud.account.name` field. Is there one?

**Comment by clement-fouque** [comment]
@efd6 I've shared raw data privately with you. For the record, here are some examples. 

## AWS
```xml
<HOST_LIST_VM_DETECTION_OUTPUT>
    <RESPONSE>
        <HOST_LIST>
            <HOST>
                <METADATA>
                    <EC2>
                        <ATTRIBUTE>
                            <NAME><![CDATA[latest/dynamic/instance-identity/document/accountId]]></NAME>
                            <LAST_STATUS>Success</LAST_STATUS>
                            <VALUE><![CDATA[123456789123]]></VALUE>
                            <LAST_SUCCESS_DATE>2024-07-25T13:50:30Z</LAST_SUCCESS_DATE>
                            <LAST_ERROR_DATE></LAST_ERROR_DATE>
                            <LAST_ERROR><![CDATA[]]></LAST_ERROR>
                        </ATTRIBUTE>
                        <ATTRIBUTE>
                            <NAME><![CDATA[latest/dynamic/instance-identity/document/availabilityZone]]></NAME>
                            <LAST_STATUS>Success</LAST_STATUS>
                            <VALUE><![CDATA[us-west-2b]]></VALUE>
                            <LAST_SUCCESS_DATE>2024-07-25T13:50:30Z</LAST_SUCCESS_DATE>
                            <LAST_ERROR_DATE></LAST_ERROR_DATE>
                            <LAST_ERROR><![CDATA[]]></LAST_ERROR>
                        </ATTRIBUTE>
                    </EC2>
                </METADATA>
            </HOST>
        </HOST_LIST>
</HOST_LIST_VM_DETECTION_OUTPUT>
```

## Azure
```xml
<HOST_LIST_VM_DETECTION_OUTPUT>
    <RESPONSE>
        <HOST_LIST>
            <HOST>
                <METADATA>
                    <AZURE>
                        <ATTRIBUTE>
                            <NAME><![CDATA[location]]></NAME>
                            <LAST_STATUS>Success</LAST_STATUS>
                            <VALUE><![CDATA[eastus2]]></VALUE>
                            <LAST_SUCCESS_DATE>2024-07-25T12:24:57Z</LAST_SUCCESS_DATE>
                            <LAST_ERROR_DATE></LAST_ERROR_DATE>
                            <LAST_ERROR><![CDATA[]]></LAST_ERROR>
                        </ATTRIBUTE>
                        <ATTRIBUTE>
                            <NAME><![CDATA[subscriptionId]]></NAME>
                            <LAST_STATUS>Success</LAST_STATUS>
                            <VALUE><![CDATA[00000000-0000-0000-0000-000000000000]]></VALUE>
                            <LAST_SUCCESS_DATE>2024-07-25T12:24:57Z</LAST_SUCCESS_DATE>
                            <LAST_ERROR_DATE></LAST_ERROR_DATE>
                            <LAST_ERROR><![CDATA[]]></LAST_ERROR>
                        </ATTRIBUTE>
                    </AZURE>
                </METADATA>
            </HOST>
        </HOST_LIST>
    </RESPONSE>
</HOST_LIST_VM_DETECTION_OUTPUT>
```

## GCP
 ```xml
<HOST_LIST_VM_DETECTION_OUTPUT>
    <RESPONSE>
        <HOST_LIST>
            <HOST>
                <METADATA>
                    <GOOGLE>
                        <ATTRIBUTE>
                            <NAME><![CDATA[machineType]]></NAME>
                            <LAST_STATUS>Success</LAST_STATUS>
                            <VALUE><![CDATA[custom-2-3072]]></VALUE>
                            <LAST_SUCCESS_DATE>2024-07-25T12:05:04Z</LAST_SUCCESS_DATE>
                            <LAST_ERROR_DATE></LAST_ERROR_DATE>
                            <LAST_ERROR><![CDATA[]]></LAST_ERROR>
                        </ATTRIBUTE>
                        <ATTRIBUTE>
                            <NAME><![CDATA[projectIdNo]]></NAME>
                            <LAST_STATUS>Success</LAST_STATUS>
                            <VALUE><![CDATA[123456789123]]></VALUE>
                            <LAST_SUCCESS_DATE>2024-07-25T12:05:04Z</LAST_SUCCESS_DATE>
                            <LAST_ERROR_DATE></LAST_ERROR_DATE>
                            <LAST_ERROR><![CDATA[]]></LAST_ERROR>
                        </ATTRIBUTE>
                    </GOOGLE>
                </METADATA>
            </HOST>
        </HOST_LIST>
    </RESPONSE>
</HOST_LIST_VM_DETECTION_OUTPUT>
```

> Also, I don't see any field in the XSD that looks like it would give a value for the cloud.account.name field. Is there one?

I don't think we have any option at the moment.
