### ISSUE TITLE
Create GitHub ISSUE_TEMPLATE form for bug reports

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#10284]
To improve the quality of bug reports, I propose we add an [issue template form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) to prompt the user for the information that we need to solve the issue.

- integration name - choose from `yq '[.name]' packages/*/manifest.yml`
- integration version
- agent version
- agent output type - choose from elasticsearch or logstash
- elasticsearch version
- os version and architecture
- software or api version the integration is interacting with
- error.message
- event.original - For pipeline errors, please enable "Preserve original event" and provide an `event.original` value that can recreate the problem.

**Comment by efd6** [comment]
For elasticsearch version, do you mean kibana version? Suggest also relevant beat version since that sometimes lags and this can be the cause of issues.

**Comment by andrewkroh** [comment]
PR for review: #10552
