### ISSUE TITLE
Add owner field to packages

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#103]
In https://github.com/elastic/package-registry/pull/536 the support for an owner field was added. We should add it to all our package. The value should be the team "owning" the package.

**Comment by exekias** [comment]
Is this meta used anywhere (ie UI). I wonder what should we do about packages owned by multiple teams

**Comment by ruflin** [comment]
@exekias Not yet. Do we have an example where a package is owned by multiple teams?

**Comment by exekias** [comment]
So for instance, in googlecloud we have some datasets developed by SIEM, some others by the Integrations team. Same for AWS, envoy or cisco modules

**Comment by ruflin** [comment]
Do we also need an `owner` for the datasets? But even if we do this, I think there should be a single overall owner of a package. In case of a bug, there should be a single point of contact that can route it to the right place.

**Comment by mtojek** [comment]
Merged, resolving.
