### ISSUE TITLE
[AWS][ELB] Create a dashboard panel for TargetResponseTime metrics

### ISSUE THREAD

**Issue by anil-elastic** [elastic/integrations#10326]
Create a new dashboard panel for showing the TargetResponseTime metrics . This is applicable only for Application Load Balancer. 
This issue must be taken up after resolving https://github.com/elastic/integrations/issues/4800, to avoid issues such as panels not displaying data when a non-ALB type LB is configured

@agithomas

**Comment by agithomas** [comment]
Closing the issue as the requirement is handled with this [PR](https://github.com/elastic/integrations/pull/10181)
