### ISSUE TITLE
[Meta][AWS] Create AWS Bedrock Metrics Dataset

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#10323]
### Goal

Create AWS Bedrock dataset to capture metrics. 

### Existing System Behaviour

AWS Bedrock logs are already part of AWS Bedrock integration package.[ Pull Request](https://github.com/elastic/integrations/pull/9667)

### Requirement

- [ ] Create a new dataset to fetch and store cloudwatch metrics
- [ ] Create an AWS Bedrock overview dashboard to display key metrics and logs data

### Reference:
- [Metrics Reference](https://docs.aws.amazon.com/bedrock/latest/userguide/monitoring-cw.html#runtime-cloudwatch-metrics)
- [PR link](https://github.com/elastic/integrations/pull/10451)

**Comment by agithomas** [comment]
@tommyers-elastic  / @lalit-satapathy / @ishleenk17 

Kindly refer to the [comment](https://github.com/elastic/integrations/pull/9667#pullrequestreview-2037126807) on the naming convention of the fields already followed for AWS Bedrock invocation dataset.
 
**Qn: Should the same naming convention be followed for the metrics dataset as well?** 

[Semantic convention for GenAI related metrics Reference](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/gen-ai/gen-ai-metrics.md)

If yes, i consider following the below field names. Please review.

| AWS Field name     | Fields Description    | Proposed Field Name |
|--------------------|-----------------------|---------------------|
| Invocations | Number of requests to the [Converse](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_Converse.html), [ConverseStream](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_ConverseStream.html), [InvokeModel](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModel.html), and [InvokeModelWithResponseStream](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModelWithResponseStream.html) API operations. |`gen_ai.server.request.count`. Similar to [gen_ai.server.request.*](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/gen-ai/gen-ai-metrics.md#metric-gen_aiserverrequestduration)|
| InvocationLatency | Latency of the invocations. | `gen_ai.performance.invocation_latency` (As part of invocation dataset, `gen_ai.performance.*` metrics are added) |
| InvocationClientErrors | Number of invocations that result in client-side errors. | `gen_ai.client.invocation.error_count` [Name Reference Example](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/messaging/azure-messaging.md#azure-event-hubs)| 
| InvocationServerErrors | Number of invocations that result in AWS server-side errors. | `gen_ai.server.invocation.error_count`. [Name Reference Example](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/messaging/azure-messaging.md#azure-event-hubs)|
| InvocationThrottles | Number of invocations that the system throttled. | `gen_ai.performance.invocation.throttle_count` |
| InputTokenCount | Number of tokens of text input. | `gen_ai.input.text_token_count`. The `aws_bedrock.invocation.input.input_token_count` added as part of elastic's invocation dataset for aws bedrock seem to represent the same information |
| LegacyModelInvocations | Number of invocations using [Legacy](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_FoundationModelLifecycle.html) models.  | `gen_ai.performance.legacymodel_invocation_count`. The other metrics added as part of clodwatch_log's invocation dataset include `gen_ai.performance.request_size`, `gen_ai.performance.request.size`, `gen_ai.performance.response_time`.|
| OutputTokenCount | Number of tokens of text output. | `gen_ai.output.text_token_count`. Similar to InputTokenCount, there exists a field `aws_bedrock.invocation.output.output_token_count` added as part invocation dataset, capturing the token count |
| OutputImageCount | Number of output images. | `gen_ai.output.image_count`|

**Comment by ishleenk17** [comment]
@agithomas 
Do we already have the equivalent fields in OTEL for the ones we are proposing? 
Or are we saying we are going to follow almost similar naming conventions, considering those fields will get added in OTEL collector in future ?

**Comment by lalit-satapathy** [comment]
>Qn: Should the same naming convention be followed for the metrics dataset as well?

Yes, We can use the _gen_ai*_ field if it is available, otherwise use _aws_bedrock.*_

Adding @muthu-mps for any feedbacks.

**Comment by agithomas** [comment]
> Yes, We can use the gen_ai* field if it is available, otherwise use aws_bedrock.*

Thanks @lalit-satapathy for your input. What confused me was the` gen_ai.performance.*` metrics, the definition not available under the [semconv](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/gen-ai/gen-ai-metrics.md) currently . After going through some discussions, I think, I now have a better understanding of these metrics.

As you mentioned, i would go with `gen_ai.*` fields, if it is available in semconv. If not, `aws_bedrock.*`  prefix will be used.

**Comment by muthu-mps** [comment]
@agithomas - You can take a look into this [issue](https://github.com/open-telemetry/semantic-conventions/issues/1007) for more information.

**Comment by agithomas** [comment]
After verifying the aggregation functions and statistics value used in Cloudwatch OOTB dashboard for AWS Bedrock using cloudwatch metrics, following would be fields and their respective aggregations, that will be used 


**Sum Aggregation**
  - Invocations
  - InvocationClientErrors
  - InvocationServerErrors
  - LegacyModelInvocations
  - InputTokenCount
  - OutputTokenCount
  - OutputImageCount
  - InvocationThrottles

**Avg Aggregation**
  - InvocationLatency

**Comment by agithomas** [comment]
Regarding the dimensions, below is the extract from [AWS Bedrock documentation](https://docs.aws.amazon.com/bedrock/latest/userguide/monitoring-cw.html#runtime-cloudwatch-metrics) 

> ModelId – all metrics
> 
> ModelId + ImageSize + BucketedStepSize – OutputImageCount

It appears there are some differences in the dimensions generated from what is documented. The BucketedStepSize is not something i could generate even when I tried with the Diffusion model such as `Stability.ai`, evaluating with both Image Generation and Variation. 

**AWS Cloudwatch dashboard view selection**

<img width="1684" alt="image" src="https://github.com/elastic/integrations/assets/101976829/791eeb52-f2b5-4df9-a634-e3a3644bec76">


**Attached image for reference**

![image](https://github.com/elastic/integrations/assets/101976829/c10c9e15-9c48-4722-9fac-42c7e0556012)
