### ISSUE TITLE
Possible issue in Integration "System" with Constant event.dataset

### ISSUE THREAD

**Issue by WildDogOne** [elastic/integrations#10348]
I have noticed that I get the following error on some of the logs pulled via the integration "System"
```
"reason"=>"[constant_keyword] field [event.dataset] only accepts values that are equal to the value defined in the mappings [system.security]
but got [windows.security]"}}}}}
```

This has to do with the fact that in the component template logs-system.security@package the event.dataset is set to a constant of "system.security".
However it seems that Windows Agents sometimes deliver logs with the event.dataset set to windows.security.
I am not 100% sure yet where this issue is comming from.
I am on the newest package version, however I am not on the newest Agent version (8.13.2)

**Comment by andrewkroh** [comment]
Do you have a more complete error? Where is this error being logged? 

Are you using Logstash (e.g. Agent->LS->ES)? If so, what processing and output steps do you have?


Any data being sent to logs-system.security@package should have an `event.dataset` value injected by the agent that is `system.security`. If you collect and [Agent diagnostic](https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html#trb-collect-agent-diagnostics) you should be able to see that their is an `add_fields` processor that sets the `event.dataset` field from the components/winlog*/beat-rendered-config.yml file.

**Comment by WildDogOne** [comment]
I suspect it's actually an issue of the heavily broken stack we are using at the moment. I have temporarily fixed the issue by overwritting the field, and will circle back as soon as I have time
