### ISSUE TITLE
[New Integration] Canva Audit Logs

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#10441]
### Description
Canva have recently added audit logs to their platform (currently in beta). These logs can be useful for compliance audits, monitoring for unauthorized activity, and other matters that require details about the creation, access, and deletion of data in Canva.

### Architecture
Canva stores audit log data in an [Amazon S3 bucket](https://aws.amazon.com/s3/) that your organization owns and manages. We add events to your S3 bucket every minute as a gzipped archive containing [JSONL](https://jsonlines.org/) content. More information about the audit logs, including the schema, can be found [here](https://www.canva.dev/docs/audit-logs/audit-events/). Canva have also supplied us with sample events and index templates which we can use as part of this integration (will share internal link when building the integration)

Audit logs are only available with a Canva Enterprise license and needs to be stated in our integration docs. 

### Dashboard ideas
- Line graph showing audit events over time (e.g. last 24 hours)
- Top 10 users by number of events
- Top 10 teams by number of events
- Pie chart by action category 
- Possibly have a dashboard per action type?
   - e.g. "User" dashboard focusing on all the [sub-actions](https://www.canva.dev/docs/audit-logs/actions/users/) under 'User'
   - Visualisations would include User Creations/Deletions/Updates over time
   - User logins by user, login_type, oauth platform
# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by piyush-elastic** [comment]
@jamiehynds - Thanks for adding new Integration, we have started doing analysis on this.
