### ISSUE TITLE
Pipeline Errors Daily

### ISSUE THREAD

**Issue by thateriksson** [elastic/integrations#10478]
Client is using Cisco FTD integration:
https://www.elastic.co/docs/current/integrations/cisco_ftd
They are processing logs and pipelines seem to work but are seeing various pipeline errors daily.

They are using default Cisco logs messages coming directly from the devices and they have not been modified.  The expectation is that these out of the box items should not be generating so many errors.

We addressed these by manually modifying some processors but trying to understand why these might not be working.   We have made some changes to the processors which cleans up some error but hard to do this one a time.  I will provide some example log errors some that (we believe are addressed after modifying processor) some that are new.  (It is also possible our changes didn't work but there just has not been a recent entry to trigger it.)

`Unable to find match for dissect pattern: Teardown stub %{network.transport} connection for %{_temp_.cisco.source_interface}:%{source.address}/%{source.port} to %{_temp_.cisco.destination_interface}:%{destination.address}/%{destination.port} duration %{_temp_.duration_hms} forwarded bytes %{network.bytes} %{event.reason} against source: Teardown director TCP connection for LIBWIFI:10.177.68.158/51508 to OUTSIDE:104.16.40.28/443 duration 0:03:29 forwarded bytes 0 Cluster flow with CLU closed on owner`

`Provided Grok expressions do not match field value: [Teardown TCP state-bypass connection 1114160035 from GIGA_DMZ_IN:198.143.54.11/43692 to GIGA_DMZ_OUT:10.61.230.39/443 duration 0:02:06 bytes 14204 TCP FINs]`

Based on the log snippet, there appear to be two values for the dissector to match on:
```
"Jun 18, 2024 @ 15:15:00.000","Unable to find match for dissect pattern: Teardown stub %{network.transport} connection for %{_temp_.cisco.source_interface}:%{source.address}/%{source.port} to %{_temp_.cisco.destination_interface}:%{destination.address}/%{destination.port} duration %{_temp_.duration_hms} forwarded bytes %{network.bytes} %{event.reason} against source: Teardown director TCP connection for LIBWIFI:10.177.61.182/53331 to OUTSIDE:185.151.204.7/443 duration 0:00:30 forwarded bytes 0 Cluster flow with CLU closed on owner","<166>Jun 18 2024 22:15:00 WIZCENIC : %FTD-6-302023: Teardown director TCP connection for LIBWIFI:10.177.61.182/53331 to OUTSIDE:185.151.204.7/443 duration 0:00:30 forwarded bytes 0 Cluster flow with CLU closed on owner

"Jun 18, 2024 @ 15:15:00.000","Unable to find match for dissect pattern: Teardown stub %{network.transport} connection for %{_temp_.cisco.source_interface}:%{source.address}/%{source.port} to %{_temp_.cisco.destination_interface}:%{destination.address}/%{destination.port} duration %{_temp_.duration_hms} forwarded bytes %{network.bytes} %{event.reason} against source: Teardown backup TCP connection for LIBPUB:10.173.117.101/51003 to OUTSIDE:54.186.166.193/443 duration 0:00:00 forwarded bytes 5282 Cluster flow with CLU closed on owner","<166>Jun 18 2024 22:15:00 WIZCENIC : %FTD-6-302023: Teardown backup TCP connection for LIBPUB:10.173.117.101/51003 to OUTSIDE:54.186.166.193/443 duration 0:00:00 forwarded bytes 5282 Cluster flow with CLU closed on owner
```
So, it is looking for "Teardown stub", but finding "Teardown director" and "Teardown backup".  I think you need to adjust the dissect pattern to match the structure of the log message differently. Here's an example of a dissect pattern that matches the provided source string:
Teardown %{+action->} %{network.transport} connection for %{_temp_.cisco.source_interface}:%{source.address}/%{source.port} to %{_temp_.cisco.destination_interface}:%{destination.address}/%{destination.port} duration %{_temp_.duration_hms} forwarded bytes %{network.bytes} %{event.reason}
In this pattern:

%{+action->} is used to capture the words "backup TCP" and "director TCP" into the action field and skip any additional words until the next part of the pattern.
%{network.transport} should match "TCP" from the source string.

We believe the above was resolved, but we still have these errors as well.
[Provided Grok expressions do not match field value - LU allocate xlate.csv](https://github.com/user-attachments/files/16198753/Provided.Grok.expressions.do.not.match.field.value.-.LU.allocate.xlate.csv)

Please let us know if you require something specific I have an agent diagnostic, but it is hard to update the integration with custom pipelines each time we are seeing processor errors.

**Comment by taylor-swanson** [comment]
As a note, I wasn't able to reproduce this issue:
```
Provided Grok expressions do not match field value: [Teardown TCP state-bypass connection 1114160035 from GIGA_DMZ_IN:198.143.54.11/43692 to GIGA_DMZ_OUT:10.61.230.39/443 duration 0:02:06 bytes 14204 TCP FINs]
```
Otherwise, the other errors mentioned should be fixed by #11257, which will be available in `cisco_ftd 3.4.1`
