### ISSUE TITLE
[F5][ASM] SIEM problems with event.kind set to alert by default

### ISSUE THREAD

**Issue by Oddly** [elastic/integrations#10528]
Hello,

We have turned on F5 BIG-IP ASM logging recently and with the last update everything is parsing correctly, thanks for that. 
The problem with the update, is that event.kind is always set on "alert" in the ingest pipeline. This makes the built in "external alerts" SIEM rule go crazy, because it creates an alert for every log message that comes from ASM. 
Can the value of event.kind be made dependent on fields like f5_bigip.log.violation.rating, so it is only set to alert when an alert really has to be raised and "info" otherwise?

**Comment by piyush-elastic** [comment]
Hey @Oddly - I could see `violation.rating` is an integer field , can you help us with which number refers to Alert?

**Comment by Oddly** [comment]
I didn't find information on `violation.rating`, but I did find `json.severity` and the following documentation:
https://clouddocs.f5.com/api/irules/ASM__severity.html

In the ingest pipeline for ASM, the `json.severity` field is converted to `f5_bigip.log.severity.name` and to `log.level`.

It seems the possible values of this fields (based on the docs linked above) would be:
```
        Emergency
        Alert
        Critical
        Error
        Warning
        Notice
        Informational
```
My suggestion would be to set `event.kind` to "event" when `log.level` is one of the following:
```
        Notice
        Informational
```

And set `event.kind` to "alert" when `log.level` is one of the following:
```
        Emergency
        Alert
        Critical
        Error
        Warning
```

If `log.level` does not exist, set `event.kind` to "event".

**Comment by mohitjha-elastic** [comment]
Looking at the sample output of [ASM](https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/output-example.html#asm-request-log) category, there exist only two fields related to threat which itself does not signify that it is of type threat.
However, we have raised [PR](https://github.com/elastic/integrations/pull/10540) for the change of event.kind for the ASM category.
Thanks for the suggestion!

**Comment by Oddly** [comment]
I beg to differ though, the following fields are related to threats IMO:
- attack_types
- virus_name
- violations
- sub_violations

They are all results from policies in ASM which are designed especially to stop threats.

**Comment by Oddly** [comment]
Correction, `event.category` and "malware" is probably a better fit for virus_name.

**Comment by mohitjha-elastic** [comment]
@Oddly The output [example](https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/output-example.html#afm-request-log) shows it is of firewall data hence the `event.category` should be mapped with network. In case, if `virus_name` field is present and contains some value then we can map `event.category` as malware.

**Comment by Oddly** [comment]
@mohitjha-elastic I think you're right, network seems to be the best option here.
