### ISSUE TITLE
[Cisco ISE] Improve ECS mappings

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#10538]
Some of the fields in our Cisco ISE integration are not-complaint with ECS and can be improved upon. Below are the fields which require improvements, based on customer request:

`event.category: authentication` and `event.outcome: success` needs to be set for events where `cisco_ise.log.category.name: CISE_Passed_Authentications` (currently this is missing)
`event.category: authentication` and `event.outcome: failure` is missing for events where `event.code is [5404, 5434,5413]`
`event.kind: event` is not being being set for any events
Rename `cisco_ise.log.endpoint.mac.address` to `client.mac`

Can request sample data if required.

**Comment by aleksmaus** [comment]
I checked the latest pipeline tests
for 
```
  "category": {
      "name": "CISE_Passed_Authentications"
  },
```

the `event.category` is already set to `authentication`
https://github.com/elastic/integrations/blob/d77064994ee3acb7555a504158e23e1534d84fbc/packages/cisco_ise/data_stream/log/_dev/test/pipeline/test-pipeline-passed-authentications.log-expected.json#L204

adding `event.outcome: success` under the same conditionds as the event.category
```
      if: ctx.cisco_ise?.log?.message?.code != null && ['5200','5231','5233','5239'].contains(ctx.cisco_ise.log.message.code)
```

adding `event.outcome: failure for events where event.code is [5404, 5434,5413]`

`event.kind` is already set
https://github.com/elastic/integrations/blob/d77064994ee3acb7555a504158e23e1534d84fbc/packages/cisco_ise/data_stream/log/_dev/test/pipeline/test-pipeline-passed-authentications.log-expected.json#L207

Adding:
* Set `cisco_ise.log.endpoint.mac.address` to `client.mac`
* Set `cisco_ise.log.ep.mac.address` to `client.mac`

Will have PR shortly.
Let me know if anything is missing.

**Comment by aleksmaus** [comment]
It would be helpful if you have some example logs for `event.code is [5404, 5434,5413]`. Didn't see anything in the existing logs, so I just added the lines with this code, but some sample data might be better to have.
