### ISSUE TITLE
[f5][ASM] HTTP endpoint messages end up under json field

### ISSUE THREAD

**Issue by Oddly** [elastic/integrations#10543]
I'm having a bit trouble with ingesting our ASM logging with the agent. 

We are ingesting logging with the HTTP Endpoint, but the whole event is being put into a `json` field in the root of the message. This then gets ingested and the default(.yml) ingest pipeline in the F5 BIG-IP integration copies the `event.original` to the `json` field, resulting in `json.json` fields in all events.

I think I've tracked the problem down to this thread, but I'm not sure:
https://discuss.elastic.co/t/cant-put-http-endpoint-messages-to-root/290527

I did see an exclusion in the above ingest pipeline, where the copy action of the message from `event.original` to the `json` field is NOT executed when:
```
ctx.event.original.contains('device_product="Application Security Module"') || ctx.event.original.contains('device_product=ASM')
```

My normal ASM logging (not the "bot and dos" logging) doesn't have this string in event.original, so the `json` field in the root field gets copied into another `json` field, resulting in `json.json...`

When I include an exclusion that matches my ASM logging, the logging gets parsed fine.

**Comment by kcreddy** [comment]
@Oddly, 

Could you share a sample document (sanitized for sensitive data) containing the `event.original` field to verify this? 
The [target_field](https://www.elastic.co/guide/en/elasticsearch/reference/current/json-processor.html#:~:text=to%20be%20parsed.-,target_field,-no) option in the [default pipeline's json processor](https://github.com/elastic/integrations/blob/main/packages/f5_bigip/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L19-L31) should be overwritten, but not written into. Maybe the source message itself is nested inside a field named `json`, it would be nice to verify this with sample document having the issue.

Curious to know if the issue occurred after an integration upgrade? Or is it a first time setup?

**Comment by Oddly** [comment]
I'll give some more context on why I think this is probably an issue with the integration.

This is a new installation, with a recent version (>15.0.0) of ASM sending logging to an agent with the HTTP endpoint. Everything was being parsed properly (after the "na" fix), until I switched the "Preserve original event" switch on.  Then, the issues I detailed above (the nested JSON field) appeared, that's how I figured the JSON processor is actually adding to the JSON field instead of overwriting.

I've added a set processor in the beginning of the pipeline to copy the `message` field to a `debug.event.original`, giving me the raw message coming into Elastic. I'll post this message here later today.

One thing that's curious is that when I exclude my ASM events by changing the "if:" statement in the JSON processor in the default ingest pipeline, everything works as intended and the problem seems to be fixed. This is what I ended up with:

`
ctx.event.original.contains('device_product="Application Security Module"') || ctx.event.original.contains('device_product=ASM') || ctx.event.original.contains('"telemetryEventCategory":"ASM"')
`

This is the addition to the above:
`|| ctx.event.original.contains('"telemetryEventCategory":"ASM"')` 

Can you give some details why the original exclusion is here?

**Comment by Oddly** [comment]
This is the redacted message from the `debug.event.original` field I talked about. Note that we send our Elastic Agent logging from the Agent to Logstash and then to elastic. Let me know if you need any information or if I need to include some information about a redacted field.

`
{
    "data_stream": {
        "namespace": "default",
        "dataset": "f5_bigip.log",
        "type": "logs"
    },
    "input": {
        "type": "http_endpoint"
    },
    "tags": [
        "preserve_original_event",
        "forwarded",
        "f5_bigip-log",
        "beats_input_raw_event"
    ],
    "topic_id": "***",
    "project_name": "***",
    "json": {
        "uri": "/***/***/***/***",
        "policy_name": "/***/***",
        "tap_event_id": "N/A",
        "staged_threat_campaign_names": "N/A",
        "http_class_name": "***",
        "violation_rating": "***",
        "sig_cves": "N/A",
        "microservice": "N/A",
        "src_port": "***",
        "websocket_message_type": "N/A",
        "protocol": "***",
        "staged_sig_cves": "N/A",
        "tap_vid": "N/A",
        "request_status": "***",
        "attack_type": "N/A",
        "policy_apply_date": "***",
        "route_domain": "***",
        "query_string": "",
        "method": "***",
        "date_time": "***",
        "x_forwarded_for_header_value": "***",
        "tenant": "***",
        "device_id": "N/A",
        "geo_location": "***",
        "support_id": "***",
        "ip_address_intelligence": "N/A",
        "staged_sig_ids": "N/A",
        "web_application_name": "***",
        "username": "N/A",
        "violations": "N/A",
        "blocking_exception_reason": "N/A",
        "severity": "***",
        "fragment": "",
        "ip_client": "***",
        "websocket_direction": "N/A",
        "management_ip_address": "***",
        "vs_name": "***",
        "telemetryEventCategory": "ASM",
        "captcha_result": "***",
        "session_id": "***",
        "sig_ids": "N/A",
        "originalRawData": "***",
        "dest_port": "***",
        "hostname": "***",
        "sub_violations": "N/A",
        "response_code": "200",
        "request": "***",
        "dest_ip": "***",
        "management_ip_address_2": "N/A",
        "virus_name": "N/A",
        "staged_sig_names": "N/A",
        "sig_names": "N/A",
        "threat_campaign_names": "N/A"
    },
    "elastic_agent": {
        "id": "***",
        "snapshot": false,
        "version": "8.13.4"
    },
    "cloud": {
        "provider": "***",
        "region": "***",
        "machine": {
            "type": "***"
        },
        "availability_zone": "***",
        "instance": {
            "id": "***",
            "name": "***"
        },
        "account": {
            "id": "***"
        },
        "service": {
            "name": "***"
        }
    },
    "agent": {
        "id": "***",
        "ephemeral_id": "***",
        "version": "8.13.4",
        "name": "***",
        "type": "filebeat"
    },
    "ecs": {
        "version": "8.0.0"
    },
    "event": {
        "dataset": "f5_bigip.log",
        "original": "{\"attack_type\":\"N/A\",\"blocking_exception_reason\":\"N/A\",\"captcha_result\":\"***\",\"date_time\":\"2024-07-23T09:04:33.000Z\",...."
    },
    "@version": "1",
    "@timestamp": "2024-07-23T09:04:37.434Z"
}
`

**Comment by piyush-elastic** [comment]
@Oddly  - We observed that `event.orignal` contains JSON logs instead of actual raw log, when we supported HTTP Endpoint we expect logs in raw format only. Thats the reason it's not hitting pipeline. So, my be you can try removing JSON processor on raw log and push raw logs directly.

**Comment by Oddly** [comment]
@piyush-elastic I'm already excluding my logs in the builtin JSON processor, is that what you mean? This works, but is not a good solution because it will get overwritten on integration updates.

In the integration [configuration manual](https://www.elastic.co/docs/current/integrations/f5_bigip#configuration-of-telemetry-streaming-in-f5) it is clearly stated to setup a Generic_HTTP consumer with the following header:

```
        "headers": [
            {
                "name": "content-type",
                "value": "application/json"
            }
```

Does this not imply that the data that is being sent to the HTTP endpoint is JSON?

**Comment by Oddly** [comment]
This problem is described and fixed in the latest version of the integration: https://github.com/elastic/integrations/commit/4c8d204d479d251f74a98e6ab92e2eaa44f4acfe

**Comment by Oddly** [comment]
Another piece of the puzzle, I think this issue is related to this problem:
https://github.com/elastic/beats/issues/39539

**Comment by Oddly** [comment]
I'm not sure what happened, but this issue got resolved once I reinstalled the integration. Thank you everyone for your time, I'm going to close this now.
