### ISSUE TITLE
[google_workspace]: pipeline error: field [id] not present as part of path [json.id.time]

### ISSUE THREAD

**Issue by buzzdeee** [elastic/integrations#10577]
### Integration Name

Google Workspace [google_workspace]

### Integration Version

2.23.0

### Agent Version

8.14.2

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.14.2

### OS Version and Architecture

Ubuntu 22.04.4 LTS

### Error Message

field [id] not present as part of path [json.id.time]

### Event Original

{"etag":"\"-roQ5YNyqtVnJTuIfcddtIsUY9W3r0o3wv8vGq722Ls/5a_VrpP5GxwJ1rXepa75AIwoF8I\"","kind":"admin#reports#activities"}

**Comment by tehbooom** [comment]
I am seeing this error as well in `google_workspace.user_accounts`

**Comment by narph** [comment]
@ShourieG you've dealt with this one recently, can you provide some direction there?

**Comment by ShourieG** [comment]
@tehbooom, The source event in this case seems to be malformed, hence the error. The pipeline is working as expected. We need to check why the logs are coming malformed, this is most likely something to do with Google workspace directly and not the integration. cc: @narph

**Comment by narph** [comment]
@shourieg , can we provide a more clear message that the json is malformed on our side? the error message atm just mentions the particular id field is missing

**Comment by ShourieG** [comment]
> @shourieg , can we provide a more clear message that the json is malformed on our side? the error message atm just mentions the particular id field is missing


@narph, so the event.original sample provided here in the issue shows that the crucial data is missing. The event only contains etag and kind attributes.

**Comment by narph** [comment]
@buzzdeee, do you need any additional info, else we'll close the issue
