### ISSUE TITLE
[arista_ngfw,windows] Replace legacy visualizations with Lens

### ISSUE THREAD

**Issue by angorayc** [elastic/integrations#10578]
### Integration Name

Beat [beat] - All kinds of Beats

### Integration Version

all

### Agent Version

all

### Agent Output Type

elasticsearch

### Elasticsearch Version

*

### OS Version and Architecture

*

### Error Message

Visualizations installed with Beats are out dated. Their types are `visualization`, should be migrated to `lens`. 
Visualization type is not compatible in Serverless Kibana. 

Please find here to view the error:
https://github.com/elastic/kibana/issues/169810

We should change all the visualizations installed with Beats to `lens`.
For example, the visualizations here should be re-generated and created in `lens`.
https://github.com/elastic/integrations/tree/main/packages/windows/kibana/visualization

**Comment by angorayc** [comment]
https://github.com/user-attachments/assets/212db286-4406-46f9-b0c2-98567bee989c

**Comment by angorayc** [comment]
> @angorayc I think you describing a problem with Elastic Beats (elastic/beats) and Fleet integrations. The "Average Uptime [Auditbeat System] ECS" visualization is from https://github.com/elastic/beats/blob/c86330a88d6aba199863ad250fcbea74671d01bc/x-pack/auditbeat/module/system/_meta/kibana/7/visualization/4d0485f0-18da-11e9-9094-c50574723088-ecs.json#L41. I suggest opening an issue in elastic/beats to cover those if that was your intent.
> 

At the beginning, it was found from a Security Project with [windows] Engine and command started visualizaiton https://github.com/elastic/kibana/issues/169810

I tested locally with Auditbeat and found the same behaviour.

We should probably check in both elastic/integration and elastic/beats folders.

**Comment by andrewkroh** [comment]
The believe steps to edit a dashboard are:

1. Install the package with `elastic-package install`.
2. Make the dashboard editable. See [howto-make-dashboards-editable-in-kibana](https://github.com/elastic/elastic-package/blob/1fbc6f7f05771d7bf10b6497478fc1beab4b8beb/docs/howto/make_dashboards_editable.md#howto-make-dashboards-editable-in-kibana).
3. Open the dashboard.
4. Click Edit visualization in Lens.
5. Save the visualization.
6. Repeat step 4-5 for each visualization.
7. Save the dashboard.
8. Repeat for each dashboard.
9. Export the dashboards back into the git repo with `elastic-package export dashboards`.

**Comment by andrewkroh** [comment]
Closing in favor of

- #10584
- #10585
