### ISSUE TITLE
[Threat Intelligences Utilities]: Intelligence Dashboard in Elastic Security Broken

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#10612]
### Integration Name

Threat Intelligence Utilities [ti_util]

### Integration Version

1.6.0

### Agent Version

8.14.1

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.14.3

### OS Version and Architecture

Elastic Cloud Hosted GCP Belgium

### Error Message

![capture_d___e__cran_2024-07-25_a___10 10 41_720](https://github.com/user-attachments/assets/cbea5903-8cd8-4c88-b191-72fef618e948)

### What did you do?

Nothing special 
Upgraded to the latest integrations 

### What did you see?

A conflicting type is at the origin of the issue 

![capture_d___e__cran_2024-07-25_a___10 14 55_720](https://github.com/user-attachments/assets/47bb7180-a828-4897-ad22-10ce2833e96b)

![capture_d___e__cran_2024-07-25_a___10 16 02_720](https://github.com/user-attachments/assets/d38a8b19-c25d-4866-ac8e-27c2ab2f3146)

![capture_d___e__cran_2024-07-25_a___10 50 21_720](https://github.com/user-attachments/assets/96ccd393-2f66-4102-9653-8ba6a6d56a22)

### What did you expect to see?

Actually if we take the logs-ti_abusech.threatfox template, it is made of the following component templates

- logs@settings
- logs-ti_abusech.threatfox@package
- logs-ti_abusech.threatfox@custom
- ecs@mappings
- .fleet_globals-1
- .fleet_agent_id_verification-1

In none of them , first_seen or last_seen is explicitely defined as a date

Please is it possible to set explicitely in the mappings of all threat intelligence templates or in ecs@mappings that the fields  threat.indicator.first_seen and threat.indicator.last_seen  are typed as date ? 

Thank you

**Comment by jamiehynds** [comment]
Thanks for reporting @Danouchka 

@kcreddy could this be a result of the transforms added to the TI packages, and the dashboard needs adjusting as a result?

**Comment by kcreddy** [comment]
The threat ECS fields such as `last_seen`, `first_seen`, `modified_at` are not mapped into `ecs@mappings` component template as they don't seem to match any patterns defined in [here](https://github.com/elastic/elasticsearch/blob/2e0d0e2c90304dffea68415ff294700d9d95e1cf/x-pack/plugin/core/template-resources/src/main/resources/ecs%40mappings.json#L138-L161). 

While this gets fixed inside the `ecs@mappings`, I created a temporary fix for the AbuseCH integration: https://github.com/elastic/integrations/pull/10637

**Comment by kcreddy** [comment]
The fixes are also needed for rest of the `ti_*` packages.

**Comment by kcreddy** [comment]
@Danouchka,
The PR for Abusech: https://github.com/elastic/integrations/pull/10637 is merged and the mapping fix available in `2.3.1`
Also MISP is also fixed in https://github.com/elastic/integrations/pull/10638 and available in version `1.35.1`.

**Comment by kcreddy** [comment]
Closing this issue as fixed by: 
https://github.com/elastic/integrations/pull/10637 (for Abusech), 
https://github.com/elastic/integrations/pull/10638 (for MISP) 
https://github.com/elastic/integrations/pull/10674 (for all other TI providers)

**Comment by kcreddy** [comment]
Closing this issue as fixed by: 
https://github.com/elastic/integrations/pull/10637 (for Abusech), 
https://github.com/elastic/integrations/pull/10638 (for MISP) 
https://github.com/elastic/integrations/pull/10674 (for all other TI providers)
