### ISSUE TITLE
[FortiProxy] Improved ECS mappings

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#10659]
Based on some user feedback on community Slack, there's some Fortiproxy fields not currently mapped to ECS, but could be. 

`fortinet.proxy.url` could be mapped to an ECS field such as 'url.domain', `url.full` and/or `url.extension`

Session id is not mapped - may need a sample event to validate?

Slack thread is here, if more information is needed from the user: https://elasticstack.slack.com/archives/C018PDGK6JU/p1721999486567249

**Comment by taylor-swanson** [comment]
Current list of changes:

- Remap `fortinet.proxy.url` to `url.original`
- Run `uri_parts` on `url.original` to get rest of url fields
- Remap `devname` to `observer.name` instead of `observer.hostname` (also aligns with `fortinet_fortigate` integration

**Comment by taylor-swanson** [comment]
All issues should be addressed with the exception of the session ID. We don't have any session IDs mappings in ECS as far as I know as of right now.
