### ISSUE TITLE
[Suricata]: TLS Handshake Failure message parsing error

### ISSUE THREAD

**Issue by pcollardez** [elastic/integrations#10690]
### Integration Name

Suricata [suricata]

### Dataset Name

suricata.eve

### Integration Version

2.21.1

### Agent Version

8.14.3

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.14.3

### OS Version and Architecture

Debian 11.10 (x86_64)

### Software/API Version

Suricata 7.0.6

### Error Message

field [tls] not present as part of path [suricata.eve.tls.version]

### Event Original

```
{"timestamp":"2024-08-02T14:04:47.332695+0200","flow_id":2012041113054354,"in_iface":"igb1","event_type":"alert","src_ip":"1.2.3.4","src_port":443,"dest_ip":"5.6.7.8","dest_port":27299,"proto":"TCP","pkt_src":"wire/pcap","alert":{"action":"allowed","gid":1,"signature_id":2029340,"rev":2,"signature":"ET INFO TLS Handshake Failure","category":"Potentially Bad Traffic","severity":2,"metadata":{"attack_target":["Client_Endpoint"],"created_at":["2020_01_30"],"deployment":["Perimeter"],"signature_severity":["Informational"],"updated_at":["2020_01_30"]}},"app_proto":"tls","direction":"to_client","flow":{"pkts_toserver":3,"pkts_toclient":2,"bytes_toserver":290,"bytes_toclient":127,"start":"2024-08-02T14:04:47.009712+0200","src_ip":"5.6.7.8","dest_ip":"1.2.3.4","src_port":27299,"dest_port":443}}
```

### What did you do?

Default configuration.

### What did you see?

Dashboards > [Elastic Agent] Integrations : [Elastic Agent] Integration Errors

KQL :
```
data_stream.dataset : "suricata.eve" and network.protocol : "tls" and error.message :* 
```
=> many log entries

### What did you expect to see?

No parsing error

### Anything else?

At the line 278, the default ingest pipeline checks for the `network.protocol` only to call the sub-pipeline `tls` :

https://github.com/elastic/integrations/blob/9e3ecf27b8bf39d5a0948d9b029a909883c8c209/packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml#L278

The message from Suricata indicates that the TLS handshake has failed, and the TLS information are not provided in the message.

Changing the test to `ctx?.network?.protocol == "tls" && ctx?.suricata?.eve?.tls != null` fixes the parsing error.

**Comment by aleksmaus** [comment]
This is already fixed here
https://github.com/elastic/integrations/commit/7e635a413441b03199acdd2048d3d1ba9e7dc075#diff-eaf05e8a97023a476d1baeee385cd28fb345fdf853c6c8b34203d44139d93215R278
