### ISSUE TITLE
[watchguard_firebox]: Ingest pipeline fails to parse syslog timestamp when timestamp includes extra spaces

### ISSUE THREAD

**Issue by agmic** [elastic/integrations#10704]
### Integration Name

WatchGuard Firebox [watchguard_firebox]

### Dataset Name

All

### Integration Version

0.1.0

### Agent Version

8.13.4

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.13.4

### OS Version and Architecture

Elasticsearch Service

### Error Message

Cannot index event ...  {"type":"document_parsing_exception","reason":"[1:1721] failed to parse field [@timestamp] of type [date] in document with id 'XXX'. Preview of field's value: 'Aug  6 08:29:55'","caused_by":{"type":"illegal_argument_exception","reason":"failed to parse date field [Aug  6 08:29:55] with format [strict_date_optional_time||epoch_millis]","caused_by":{"type":"date_time_parse_exception","reason":"date_time_parse_exception: Failed to parse with all enclosed parsers"}}}, dropping event!

### Event Original

<142>Aug  6 08:51:27 WatchGuard-Firebox FVE6035FD3AE3 (2024-01-10T09:49:05) firewall[10]: msg_id="3000-0148" Allow Firebox 0-External 52 tcp 20 127 10.0.1.2 81.2.69.192 62443 80 offset 8 S 832026162 win 8192 (HTTP-00)

### What did you do?

Standard configuration of watchguard and integration according to documentation

### What did you see?

Indexing failure as timestamp was not parsed by the ingest pipeline

### What did you expect to see?

Syslog timestamp to be indexed to @timestamp 

### Anything else?

The watchguard integration was ingesting and indexing correctly in July. On the switch to August syslog timestamp parsing failed. On investigation, the watchguard syslog was adding an extra space between Month and Day (Aug  6). This causes the timestamp not to be parsed out as the format doesn't match - resulting in the document not being indexed
 https://github.com/elastic/integrations/blob/0e4459d5ccd7c66bc7de7d9a49015a127ca87f54/packages/watchguard_firebox/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L65

I don't see an option in the watchguard configuration to adjust this so it probably needs to be handled in the ingest pipeline, either by stripping the extra spaces or adding a date format with the extra space "MMM  d HH:mm:ss" 

note: in the example I included there are 2 spaces between "Aug" and "6"

**Comment by piyush-elastic** [comment]
@agmic - we did analyse the issue. Also I could see in the sample log you have attached contains `single space`. As you have mentioned July logs parsed and ingested successfully. It would be better to connect with `Watchguard` and see whats causing this issue? @jamiehynds - let me know WDYT on this?

**Comment by agmic** [comment]
@piyush-elastic - i think it is just html eating the extra spaces. The log does have 2 spaces between month and day

`<142>Aug  6 08:51:27 WatchGuard-Firebox FVE6035FD3AE3 (2024-01-10T09:49:05) firewall[10]: msg_id="3000-0148" Allow Firebox 0-External 52 tcp 20 127 10.0.1.2 81.2.69.192 62443 80 offset 8 S 832026162 win 8192 (HTTP-00)`

I agree this should be handled at watchguards end, but regardless it is sending these logs with this format.

**Comment by agmic** [comment]
@piyush-elastic Looks like the cisco_ios integration does something similar here: https://github.com/elastic/integrations/blob/ca5e7bf67c83218985fdbfe603fa9fc0ccb377f2/packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L67
