### ISSUE TITLE
Unable to access Apache Integration overview page.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#1074]
**Kibana version:** 7.14.0 Snapshot Kibana staging environment

**Host OS and Browser version:** Windows 10, All

**Preconditions:**
1. 7.14.0 Snapshot Kibana staging environment should be available.

**Build Details:**
```
Build: 41403
Commit: 4f0781737cdb5cf9b5dfa624368b4306b5d6bcb0
```
2. Default policy must have System and Endpoint Security.

**Steps to reproduce:**
1. Login to Kibana Cloud environment.
2. Navigate to Integrations>All Integrations tab.
3. Click on Apache integration.
4. Observe 'Unknown language: `$json` is not registered' error page shows up.

**Expected Result:**
Overview page should be accessible.

**Screenshots:**
![image](https://user-images.githubusercontent.com/72375798/120640630-57a99b80-c490-11eb-8085-f1447cbf9d15.png)

**Whats working:**
- able to add Apache integration through policies tab> add integration button link.
- able to access policies and settings tab for Apache integration after installing it under any policy.

**Comment by dikshachauhan-qasource** [comment]
@karanbirsingh-qasource Please review

**Comment by dikshachauhan-qasource** [comment]
hi @EricDavisX 

Same issue is observed on **AWS, Azure, auditd , haproxy, IIS, google_workspace, Google cloud Platform** integrations Overview tab.

Screenshot:
![image](https://user-images.githubusercontent.com/72375798/120641478-457c2d00-c491-11eb-8ac4-365c65a7c2e2.png)

**Comment by jen-huang** [comment]
This was fixed yesterday in https://github.com/elastic/kibana/pull/101187. It should be available in the next snapshot.

**Comment by dikshachauhan-qasource** [comment]
Hi @jen-huang 

Thanks for the confirmation. We will validate and provide confirmation on linked pull ticket.

Thanks
QAS
