### ISSUE TITLE
[entityanalytics_ad]: LDAP size limit exceeded

### ISSUE THREAD

**Issue by meganlear** [elastic/integrations#10769]
### Integration Name

Active Directory Entity Analytics [entityanalytics_ad]

### Dataset Name

entityanalytics_ad.user

### Integration Version

0.1.0

### Agent Version

8.15.0

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.0

### OS Version and Architecture

Ubuntu 22.04.4 LTS (x86_64)

### Error Message

```
Error running incremental update
failed to get user details: LDAP Result Code 4 "Size Limit Exceeded": 
```

### What did you do?

We set up the integration with the default settings, using an OU which contains most of our users as the Base DN setting.

### What did you see?

The integration didn't ingest any data.

### What did you expect to see?

We expected the integration to ingest user data for the users in the OU we specified.

### Anything else?

I believe this is happening because the default `MaxPageSize` setting in AD is 1000, and there are more than 1000 users in the OU we want to use. We tried changing the Base DN to a different OU with around 200 users, and that did work, so there are no issues with connecting to our AD server and it seems like the only relevant difference is the number of users in the OU. I think you could use paging to be able to retrieve more than 1000 users without having to change the settings on the AD server.

**Comment by efd6** [comment]
Duplicate of elastic/beats#40482. This should be fixed by #10762.

**Comment by meganlear** [comment]
Thanks for fixing this!

**Comment by nicpenning** [comment]
@meganlear did this work for you? What did you set your paging size to? How long did it take to ingest your results and how many results did you have?

I am expecting over 16K results but it crashes and never finishes.

**Comment by meganlear** [comment]
@nicpenning It's working for us but we don't have nearly that many users. We got about 1030 results and the full sync took under a minute to ingest everything, with paging size set to 500.

**Comment by nicpenning** [comment]
Thanks for reporting back!

**Comment by nicpenning** [comment]
@meganlear may I ask if your agent was Windows or Linux? Also, was your agent joined to the domain?

**Comment by meganlear** [comment]
@nicpenning Our agent is on Linux (Ubuntu) and it is domain joined.
