### ISSUE TITLE
[Citrix ADC]: Grok failure for logs without timezone

### ISSUE THREAD

**Issue by Linu-Elias** [elastic/integrations#10782]
In Citrix ADC `citrix_adc.log` datastream,  found that the grok pattern has `timezone` which is not optional hence below log formats are failing

`<123> 10/08/2024:09:38:41  SYSLOGHOST 0-PPE-1 : default TCP CONN_TERMINATE 6715345 0 :  Source 127.1.2.1:80 - Destination 127.1.1.2:20714 - Start Time 10/08/2024:09:37:54  - End Time 10/08/2024:09:38:41  - Total_bytes_send 1 - Total_bytes_recv 1 \n `

Suggested fix is to make `timezone` optional in the grok pattern

**Comment by jvalente-salemstate** [comment]
@Linu-Elias Can you check out #10403 ? I also have an open PR for the timezone issue as well as a few other cases (varying formats, user names as email address, and Citrix gateway).

**Comment by ishleenk17** [comment]
@jvalente-salemstate : Thanks for the contribution. 
For now we would like to proceed with this PR as its an urget requirement.
We can review your PR as well after that.
