### ISSUE TITLE
[Jamf Protect]: Dashboard queries not matching data in ES

### ISSUE THREAD

**Issue by spfagetty** [elastic/integrations#10791]
### Integration Name

Jamf Protect [jamf_protect]

### Dataset Name

jamf_protect.alerts

### Integration Version

2.3.0

### Agent Version

8.15.0

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.0

### OS Version and Architecture

n/a

### What did you do?

Using the dashboard and executing the query for
`(observer.product : "Jamf Protect" and event.module : "Alerts" and event.severity : 1) or (observer.product :"Jamf Protect" and event.module :"Threat Events Stream" and event.severity : 4)`

From the dashboard: https://github.com/elastic/integrations/blob/4523d07944016a504075bf9f8957675492242409/packages/jamf_protect/kibana/dashboard/jamf_protect-e9b86210-c65c-11ee-882f-57f79af43d7f.json#L116C1-L117C1

### What did you see?

I did not see any alerts populated.

### What did you expect to see?

The data I actually have in ES (saved by the agent integration).

### Anything else?

I checked the ingest pipelines and `event.module : "Alerts"` is never mentioned.

**Comment by efd6** [comment]
@spfagetty It looks like this should be `(data_stream_dataset : "jamf_protect.alerts" and event.severity : 1) or (data_stream_dataset : "jamf_protect.web_threat_events" and event.severity : 4)`. Can you confirm that this gives the results that you would expect? (The doubt here comes from the name of the threat stream data stream).

**Comment by spfagetty** [comment]
@efd6 yes, I can confirm that this returns proper data. Likely it has to be adapted also for other queries in the dashboard as well.
