### ISSUE TITLE
[Akamai]: Add support for specifying ingest timeline 

### ISSUE THREAD

**Issue by narph** [elastic/integrations#10812]
### Integration Name

Akamai [akamai]

### Dataset Name

siem

### Integration Version

2.25.0

### Agent Version

8.15

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15

### OS Version and Architecture

ALL

### Software/API Version

v1

### What did you do?

Currently there is no support for specifying a custom ingestion timeline although the Akamai SIEM integration API can support it.

### What did you see?

In the [api docs](https://techdocs.akamai.com/siem-integration/reference/get-configid) the `from` and `to` params can be used to set a custom interval.
Current integration setup maps `from` param if offset is missing and `to`  to present time. 

### What did you expect to see?

Add support for explicitly setting the initial and end  ingesting intervals.

**Comment by efd6** [comment]
The current code is using the convetional approach to this; it has a look-back that it uses to prime the collection and then after the first request the periods are from the end of the last response to now. The `from` and `to` query parameters are used to implement this behaviour. I think this is working as intended.

**Comment by andrewkroh** [comment]
The proposal here was in response to an error condition encountered where the persisted offset became invalid. I think we should address that specific problem such that no workaround is required. The integration should be able to automatically recover from the error state. We will open a separate issue to handle the [HTTP 416](https://techdocs.akamai.com/siem-integration/reference/416) "offset-to-old" error.
