### ISSUE TITLE
[New Integration] Vertex AI 

### ISSUE THREAD

**Issue by cpascale43** [elastic/integrations#10856]
## Description
Vertex AI is Google’s platform offering AI and machine learning computing as a service. The integration enables monitoring and analysis of AI/ML operations.

## Architecture
The integration collects Vertex AI audit events and model endpoint logs from Google Cloud Logging. We can ship these logs to Elastic using our existing Google Cloud integration framework.
- [Vertex AI audit logging information](https://cloud.google.com/vertex-ai/docs/general/audit-logging)
- [Model endpoint audit logs](https://cloud.google.com/vertex-ai/generative-ai/docs/enable-audit-logs)

## Dashboard Ideas
- Time series of Vertex AI API calls by event type
- Bar chart of model endpoint usage over time
- Heatmap of prediction requests by model and time
- Line graph showing dataset operations over time
- Stacked area chart of successful vs. failed operations 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists, [useful guidelines](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md) to follow
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

**Comment by haetamoudi** [comment]
@cpascale43 
VertexAI generates audit logs, which are already handled by the GCP integration.

The integration already fetches all the data from the request and response fields, meaning there are no changes specific to VertexAI required. I have done some testing, and all the logs generated by VertexAI are ingested through the existing integration with no changes needed.

As far as I understand, it is not possible to create visualizations based on fields that are dynamically mapped (flattened).

FYI, while testing, I noticed some audit logs fields were missing, so I opened a PR to enhance the integration: https://github.com/elastic/integrations/pull/10886


VertexAI logs ingested using the integration:
![Image](https://github.com/user-attachments/assets/57011682-57c7-4741-99dc-cd63c632ef3f)


![Image](https://github.com/user-attachments/assets/6c1fa887-ba6b-40c3-aeab-7b49d8fc2fe7)

**Comment by cpascale43** [comment]
@haetamoudi thanks for looking into this! Good news that we are already collecting these logs.

Do the ECS mappings look correct?

If everything looks good then we'd just want to create documentation nested under Google Cloud + a separate log source tile, kind of like we [did](https://www.elastic.co/docs/current/integrations/aws_bedrock) with AWS Bedrock.

**Comment by haetamoudi** [comment]
@cpascale43 The ECS mappings look correct to me, and [this PR](https://github.com/elastic/integrations/pull/10886) will add some missing fields that aren't specific to Vertex.

Regarding the documentation, VertexAI generates audit logs just like many other Google services, without any unique characteristics (besides the content of `request` and `response` which are dynamically handled). It seems odd to single out Vertex in the documentation when other Google Cloud services that also produce audit logs are handled by the same integration.

What do you think about including a link to the Google documentation that lists all services producing audit logs, rather than mentioning Vertex specifically? This would make it clear that logs from all those services are supported by our current integration. Here's the link: https://cloud.google.com/logging/docs/audit/services.

**Comment by haetamoudi** [comment]
@cpascale43 Let me know what you think about the suggestion—adding a link to the Google Cloud list of services that support audit logs instead of add documentation specific to Vertex.

**Comment by cpascale43** [comment]
Closing for now as this was deprioritized in favor of the Observability-led integration: https://github.com/elastic/observability-dev/issues/3905
