### ISSUE TITLE
ForgeRock Identity Platform

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1085]
### Description
ForgeRock is a modern identity platform which helps organizations radically simplify identity and access management (IAM) and identity governance and administration (IGA).

### Architecture
ForgeRock Identity Platform provides an API which works across the platform to provide access to audit logs. The audit service includes events such as system access\activity, authentication and configuration changes. Relevant documentation can be found [here ](https://backstage.forgerock.com/docs/idm/7/audit-guide/index.html#preface). Information on their JSON Audit Event handler available [here](https://backstage.forgerock.com/docs/idm/7/audit-guide/audit-config-prop-json.html). 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by a03nikki** [comment]
A user told me that they were named to the access management magic quadrant by Gartner as a reason why we should have this integration.

https://www.forgerock.com/about-us/press-releases/forgerock-named-leader-2021-gartner-magic-quadrant-access-management
