### ISSUE TITLE
[Kubernetes]Overview dashboard - total cpu and memory usage are incorrect

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#10887]
Used breakdown based on `kubernetes.container.name` field, the issue is that for DaemonSet container name is the same for all pods, instead should be used something more unique - like `container.id`

![Image](https://github.com/user-attachments/assets/64d5c2db-8065-4678-916a-0ccd3f564256)

We also should check why `kubernetes.container.id` is missing, if it is expected

**Comment by gizas** [comment]
I have made some checks, with container.id everyhting seems to work fine. I will retest with a mutliple node cluster
(see below duplicate visualisations of memory and cpu)
![Image](https://github.com/user-attachments/assets/874e4850-14cf-43c0-b95f-fe56e2226ab2)


> We also should check why kubernetes.container.id is missing, if it is expected

To clarify this, the kubernetes.container.id is a field present in `kubernetes.state_container` datastream. The `kubernetes.container.id` and container.id have been aligned in previous [34516](https://github.com/elastic/beats/pull/34516#discussion_r1099893308)

![Image](https://github.com/user-attachments/assets/8cfbf387-1652-40ab-a66d-3b0d8eb89e4c)

In this visualisations we use the kubernetes.container datastream (and not the `kubernetes.state_container` mentioned before) as it contains the kubernetes.container.memory.* and kubernetes.container.cpu.* metrics needed

**Comment by gizas** [comment]
Testing with a 3 node cluster, indeed either kubernetes.pod.name or kubernetes.container.id are good candidates (the kubernetes.container.name is the same for daemonsets)

![Image](https://github.com/user-attachments/assets/764f2dbb-b684-41ba-98ec-66c212a8abfc)

**Comment by tetianakravchenko** [comment]
> indeed either kubernetes.pod.name or kubernetes.container.id are good candidates

`kubernetes.pod.name` can be not unique enough in the cluster
did you mean `container.id` here?
when used `kubernetes.container.id` there is no data:
![Image](https://github.com/user-attachments/assets/42f9e490-7c4d-458c-8296-ccc755f11241)

**Comment by gizas** [comment]
Yes edited my [answer](https://github.com/elastic/integrations/issues/10887#issuecomment-2311901213)

kubernetes.pod.name is unique inside a specific daemonset. See image in the answer above.  But yes to avoid conflicts I also prefered the container.id

kubernetes.container.id is actlually a kube_state container.id and exists only in state_container. But we can not use this datastream as it does not include the memory/ cpu metrics that kubernetes.container does
