### ISSUE TITLE
[cisco_ios]: Grok parser does not match

### ISSUE THREAD

**Issue by IanLee1521** [elastic/integrations#10909]
### Integration Name

Cisco IOS [cisco_ios]

### Dataset Name

cisco_ios.log

### Integration Version

1.26.10

### Agent Version

8.14.3

### Agent Output Type

logstash

### Elasticsearch Version

8.14.3

### OS Version and Architecture

Elastic Agent on RHEL 8 x86_64

### Error Message

We are getting errors in our logs due to the integration failing to properly match the following messages:

```
<46>: 2024 Aug 27 21:40:50 PDT: %SNMPD-6-INFO: SNMP log informational : Processing packet for non-MTS (sockets)
```

The `error.message` is:

```
Processor "grok" with tag "grok_header" in pipeline "logs-cisco_ios.log-1.26.10" failed with message "Provided Grok expressions do not match field value: [<46>: 2024 Aug 27 21:40:50 PDT: %SNMPD-6-INFO: SNMP log informational : Processing packet for non-MTS (sockets) ]"
```

Note to self, this is: `_id: 5gZJl5EBEAlRcXfZU5O7 AND _index: .ds-logs-cisco_ios.log-default-2024.08.12-000016`

### Event Original

<46>: 2024 Aug 27 21:40:50 PDT: %SNMPD-6-INFO: SNMP log informational : Processing packet for non-MTS (sockets)

### What did you do?

Nothing special, default configuration.

### What did you see?

```
Processor "grok" with tag "grok_header" in pipeline "logs-cisco_ios.log-1.26.10" failed with message "Provided Grok expressions do not match field value: [<46>: 2024 Aug 27 21:40:50 PDT: %SNMPD-6-INFO: SNMP log informational : Processing packet for non-MTS (sockets) ]"
```

### What did you expect to see?

A properly parsed document

**Comment by aleksmaus** [comment]
The issue is with the timestamp that has the year value first. Fixing.

**Comment by IanLee1521** [comment]
Thank you!
