### ISSUE TITLE
No meta info for groups

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#1091]
In https://github.com/elastic/kibana/issues/82273 the issue was raised that units are set on a group object: https://github.com/elastic/integrations/blob/master/packages/system/data_stream/fsstat/fields/fields.yml#L15-L16 

First, I think this should not happen and we should fix the package. @fearful-symmetry I guess this falls on your plate?

Second, we should have a discussion if we should validate this also in the package spec?  @mtojek @ycombinator 

Last, to support also older packages, do we need a workaround in Kibana (@Zacqary )?

**Comment by mtojek** [comment]
> Second, we should have a discussion if we should validate this also in the package spec? 

I think this can be handled with semantic validation rules.

**Comment by fearful-symmetry** [comment]
So, is the issue that we don't want `unit` and `metric_type` in `groups` at all? Agreed we should add some validation rules, until then @mtojek should I just start fixing things manually?

**Comment by mtojek** [comment]
> So, is the issue that we don't want unit and metric_type in groups at all? 

Yes.

> Agreed we should add some validation rules, until then @mtojek should I just start fixing things manually?

It's up to you. You can start fixing the system package if you know all these places. Otherwise please wait until the PR for semantic validation is merged, so it will detect all these places.

**Comment by ruflin** [comment]
@fearful-symmetry What I'm trying to understand on my end is: Do we need the units? I assume we put them there for a reason?

**Comment by fearful-symmetry** [comment]
> @fearful-symmetry What I'm trying to understand on my end is: Do we need the units? I assume we put them there for a reason?

@ruflin most of those fields weren't added by me if I remember correctly, so I really can't say. It looks like @exekias added most of the ones to `system`.

**Comment by ruflin** [comment]
Are we in agreement we don't need this and we should get rid of it?

**Comment by fearful-symmetry** [comment]
Agreed. Unless there's a blocker, I'm going to wait for the validation PR before trying to clear things out.

**Comment by mtojek** [comment]
@fearful-symmetry I will try to update it in the elastic/integrations as well.
