### ISSUE TITLE
[squid] Follow up items for Squid rewrite

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/integrations#10920]
The Squid integration was rewritten to use ingest pipelines in #10770. There are a few more tasks needing to be done:

- Build a dashboard for Squid (there was no existing dashboard)
- Improve the README/documentation

## Acceptance Criteria

- Dashboard for Squid has been added
- Documentation for Squid has been improved. Includes at the very least:
  - Setup instructions on the Squid side
  - Supported formats (only Access log at the moment)
  - Field documentation
  - Sample event

**Comment by andrewkroh** [comment]
Is #6768 relevant for squid after the rewrite? If not, can you amend that issue to make that clear.
