### ISSUE TITLE
[Squid Proxy]: Parsing Regression noticed on version 0.20.0

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#10951]
### Integration Name

Squid Proxy [squid]

### Dataset Name

squid.log

### Integration Version

0.20.0

### Agent Version

8.15.0

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.0

### OS Version and Architecture

Centos 7 for agent , Elastic Cloud for Elasticsearch

### Event Original

Before Integration Upgrade, my saved search was showing the following fields properly 
![Image](https://github.com/user-attachments/assets/dfbadb09-2b38-4cbe-817a-9a2004b2a8b0)

Exemple of JSON Stored 
> {
  "_index": ".ds-logs-squid.log-default-2024.08.25-000193",
  "_id": "7NGQopEBkyYJz9-4oVt4",
  "_version": 1,
  "_score": 0,
  "_source": {
    "server": {
      "registered_domain": "google.com",
      "top_level_domain": "com",
      "domain": "www.google.com",
      "subdomain": "www"
    },
    "rsa": {
      "internal": {
        "messageid": "CONNECT",
        "hcode": "HIER_NONE"
      },
      "web": {
        "alias_host": "www.google.com"
      },
      "investigations": {
        "ec_subject": "NetworkComm",
        "ec_theme": "ALM"
      },
      "time": {
        "event_time_str": "1725009253",
        "duration_time": 0,
        "event_time": "2024-08-30T09:14:13.000Z"
      },
      "misc": {
        "content_type": "text/html",
        "action": [
          "TCP_DENIED",
          "CONNECT"
        ],
        "result_code": "407"
      },
      "network": {
        "domain": "www.google.com"
      }
    },
    "agent": {
      "name": "sa-da-proxy-01",
      "id": "50a1c0bc-f736-44e7-8913-e5d42740c464",
      "ephemeral_id": "7ccdf85c-d666-444e-a9c2-da0e7a866acc",
      "type": "filebeat",
      "version": "8.15.0"
    },
    "log": {
      "file": {
        "path": "/var/log/squid/access.log"
      },
      "offset": 84239
    },
    "elastic_agent": {
      "id": "50a1c0bc-f736-44e7-8913-e5d42740c464",
      "version": "8.15.0",
      "snapshot": false
    },
    "source": {
      "geo": {
        "continent_name": "Europe",
        "region_iso_code": "DE-HE",
        "city_name": "Frankfurt am Main",
        "country_iso_code": "DE",
        "country_name": "Germany",
        "region_name": "Hesse",
        "location": {
          "lon": 8.7147,
          "lat": 50.1103
        }
      },
      "as": {
        "number": 49581,
        "organization": {
          "name": "Tube-Hosting"
        }
      },
      "bytes": 3974,
      "ip": "176.97.210.30"
    },
    "url": {
      "registered_domain": "google.com",
      "original": "www.google.com:443",
      "top_level_domain": "com",
      "domain": "www.google.com",
      "subdomain": "www"
    },
    "tags": [
      "preserve_original_event",
      "squid-log",
      "forwarded"
    ],
    "cloud": {
      "availability_zone": "europe-west1-b",
      "instance": {
        "name": "sa-da-proxy-01",
        "id": "3371506256334554537"
      },
      "provider": "gcp",
      "service": {
        "name": "GCE"
      },
      "machine": {
        "type": "c2-standard-4"
      },
      "project": {
        "id": "elastic-sa"
      },
      "region": "europe-west1",
      "account": {
        "id": "elastic-sa"
      }
    },
    "input": {
      "type": "log"
    },
    "observer": {
      "product": "Proxy",
      "vendor": "Squid",
      "type": "Proxies"
    },
    "@timestamp": "2024-08-30T09:14:13.000Z",
    "ecs": {
      "version": "8.11.0"
    },
    "related": {
      "hosts": [
        "www.google.com"
      ],
      "ip": [
        "176.97.210.30"
      ],
      "user": [
        "-"
      ]
    },
    "data_stream": {
      "namespace": "default",
      "type": "logs",
      "dataset": "squid.log"
    },
    "event": {
      "agent_id_status": "verified",
      "ingested": "2024-08-30T09:14:33Z",
      "original": "1725009253.289      0 176.97.210.30 TCP_DENIED/407 3974 CONNECT www.google.com:443 - HIER_NONE/- text/html",
      "code": "CONNECT",
      "timezone": "+02:00",
      "action": "TCP_DENIED",
      "dataset": "squid.log"
    },
    "user": {
      "name": "-"
    }
  },
  "fields": {
    "elastic_agent.version": [
      "8.15.0"
    ],
    "server.subdomain": [
      "www"
    ],
    "url.original.text": [
      "www.google.com:443"
    ],
    "rsa.misc.action": [
      "TCP_DENIED",
      "CONNECT"
    ],
    "cloud.availability_zone": [
      "europe-west1-b"
    ],
    "observer.vendor": [
      "Squid"
    ],
    "rsa.misc.result_code": [
      "407"
    ],
    "agent.name.text": [
      "sa-da-proxy-01"
    ],
    "server.top_level_domain": [
      "com"
    ],
    "source.geo.region_name": [
      "Hesse"
    ],
    "cloud.service.name.text": [
      "GCE"
    ],
    "source.ip": [
      "176.97.210.30"
    ],
    "agent.name": [
      "sa-da-proxy-01"
    ],
    "url.top_level_domain": [
      "com"
    ],
    "event.agent_id_status": [
      "verified"
    ],
    "source.geo.region_iso_code": [
      "DE-HE"
    ],
    "source.geo.city_name": [
      "Frankfurt am Main"
    ],
    "event.original": [
      "1725009253.289      0 176.97.210.30 TCP_DENIED/407 3974 CONNECT www.google.com:443 - HIER_NONE/- text/html"
    ],
    "cloud.region": [
      "europe-west1"
    ],
    "cloud.instance.name.text": [
      "sa-da-proxy-01"
    ],
    "input.type": [
      "log"
    ],
    "rsa.investigations.ec_theme": [
      "ALM"
    ],
    "log.offset": [
      84239
    ],
    "url.subdomain": [
      "www"
    ],
    "data_stream.type": [
      "logs"
    ],
    "related.user": [
      "-"
    ],
    "tags": [
      "preserve_original_event",
      "squid-log",
      "forwarded"
    ],
    "rsa.web.alias_host": [
      "www.google.com"
    ],
    "cloud.machine.type": [
      "c2-standard-4"
    ],
    "cloud.provider": [
      "gcp"
    ],
    "event.code": [
      "CONNECT"
    ],
    "agent.id": [
      "50a1c0bc-f736-44e7-8913-e5d42740c464"
    ],
    "cloud.service.name": [
      "GCE"
    ],
    "ecs.version": [
      "8.11.0"
    ],
    "observer.type": [
      "Proxies"
    ],
    "rsa.internal.messageid": [
      "CONNECT"
    ],
    "rsa.internal.hcode": [
      "HIER_NONE"
    ],
    "agent.version": [
      "8.15.0"
    ],
    "related.hosts": [
      "www.google.com"
    ],
    "source.as.number": [
      49581
    ],
    "rsa.time.duration_time": [
      0
    ],
    "url.registered_domain": [
      "google.com"
    ],
    "rsa.investigations.ec_subject": [
      "NetworkComm"
    ],
    "user.name": [
      "-"
    ],
    "source.geo.location": [
      {
        "coordinates": [
          8.7147,
          50.1103
        ],
        "type": "Point"
      }
    ],
    "cloud.instance.id": [
      "3371506256334554537"
    ],
    "agent.type": [
      "filebeat"
    ],
    "event.module": [
      "squid"
    ],
    "related.ip": [
      "176.97.210.30"
    ],
    "source.geo.country_iso_code": [
      "DE"
    ],
    "observer.product": [
      "Proxy"
    ],
    "elastic_agent.snapshot": [
      false
    ],
    "event.timezone": [
      "+02:00"
    ],
    "source.bytes": [
      3974
    ],
    "server.registered_domain": [
      "google.com"
    ],
    "source.as.organization.name.text": [
      "Tube-Hosting"
    ],
    "elastic_agent.id": [
      "50a1c0bc-f736-44e7-8913-e5d42740c464"
    ],
    "data_stream.namespace": [
      "default"
    ],
    "rsa.time.event_time": [
      "2024-08-30T09:14:13.000Z"
    ],
    "rsa.misc.content_type": [
      "text/html"
    ],
    "source.as.organization.name": [
      "Tube-Hosting"
    ],
    "source.geo.continent_name": [
      "Europe"
    ],
    "event.action": [
      "TCP_DENIED"
    ],
    "event.ingested": [
      "2024-08-30T09:14:33.000Z"
    ],
    "url.original": [
      "www.google.com:443"
    ],
    "@timestamp": [
      "2024-08-30T09:14:13.000Z"
    ],
    "server.domain": [
      "www.google.com"
    ],
    "cloud.account.id": [
      "elastic-sa"
    ],
    "data_stream.dataset": [
      "squid.log"
    ],
    "log.file.path": [
      "/var/log/squid/access.log"
    ],
    "rsa.network.domain": [
      "www.google.com"
    ],
    "url.domain": [
      "www.google.com"
    ],
    "agent.ephemeral_id": [
      "7ccdf85c-d666-444e-a9c2-da0e7a866acc"
    ],
    "source.geo.country_name": [
      "Germany"
    ],
    "event.dataset": [
      "squid.log"
    ],
    "rsa.time.event_time_str": [
      "1725009253"
    ],
    "cloud.instance.name": [
      "sa-da-proxy-01"
    ],
    "cloud.project.id": [
      "elastic-sa"
    ],
    "user.name.text": [
      "-"
    ]
  }
}

Now I get this 

![Image](https://github.com/user-attachments/assets/3b033f1d-5a66-474e-bccc-4a7507c7c0fc)

Exemple of JSON 

> {
  "_index": ".ds-logs-squid.log-default-2024.09.01-000195",
  "_id": "NCU4rpEBkyYJz9-4GX9O",
  "_version": 1,
  "_score": 0,
  "_source": {
    "agent": {
      "name": "sa-da-proxy-01",
      "id": "50a1c0bc-f736-44e7-8913-e5d42740c464",
      "type": "filebeat",
      "ephemeral_id": "7847ab21-1fa6-45c5-a9d8-923b066f9f63",
      "version": "8.15.0"
    },
    "log": {
      "file": {
        "inode": "35192373",
        "path": "/var/log/squid/access.log",
        "device_id": "2050"
      },
      "offset": 48814
    },
    "elastic_agent": {
      "id": "50a1c0bc-f736-44e7-8913-e5d42740c464",
      "version": "8.15.0",
      "snapshot": false
    },
    "destination": {
      "bytes": 6880
    },
    "source": {
      "address": "86.245.8.29",
      "ip": "86.245.8.29",
      "user": {
        "name": "dabitbol"
      }
    },
    "url": {
      "original": "data.kameleoon.io:443"
    },
    "tags": [
      "preserve_original_event",
      "squid-log",
      "forwarded"
    ],
    "cloud": {
      "availability_zone": "europe-west1-b",
      "instance": {
        "name": "sa-da-proxy-01",
        "id": "3371506256334554537"
      },
      "provider": "gcp",
      "machine": {
        "type": "c2-standard-4"
      },
      "service": {
        "name": "GCE"
      },
      "project": {
        "id": "elastic-sa"
      },
      "region": "europe-west1",
      "account": {
        "id": "elastic-sa"
      }
    },
    "input": {
      "type": "filestream"
    },
    "observer": {
      "product": "Squid",
      "vendor": "Squid",
      "type": "proxy"
    },
    "@timestamp": "2024-09-01T15:32:57.978Z",
    "ecs": {
      "version": "8.11.0"
    },
    "related": {
      "ip": [
        "86.245.8.29"
      ],
      "user": [
        "dabitbol"
      ]
    },
    "data_stream": {
      "namespace": "default",
      "type": "logs",
      "dataset": "squid.log"
    },
    "http": {
      "request": {
        "method": "CONNECT",
        "body": {
          "bytes": 6880
        }
      }
    },
    "squid": {
      "status_code": 200,
      "peer_status": "HIER_DIRECT",
      "peer_host": "65.109.36.162",
      "result_code": "TCP_TUNNEL"
    },
    "event": {
      "duration": 100929000000,
      "agent_id_status": "verified",
      "ingested": "2024-09-01T15:33:17Z",
      "original": "1725204777.978 100929 86.245.8.29 TCP_TUNNEL/200 6880 CONNECT data.kameleoon.io:443 dabitbol HIER_DIRECT/65.109.36.162 -",
      "kind": "event",
      "category": [
        "web"
      ],
      "type": [
        "access"
      ],
      "dataset": "squid.log",
      "outcome": "success"
    }
  },
  "fields": {
    "elastic_agent.version": [
      "8.15.0"
    ],
    "event.category": [
      "web"
    ],
    "url.original.text": [
      "data.kameleoon.io:443"
    ],
    "cloud.availability_zone": [
      "europe-west1-b"
    ],
    "observer.vendor": [
      "Squid"
    ],
    "squid.result_code": [
      "TCP_TUNNEL"
    ],
    "http.request.method": [
      "CONNECT"
    ],
    "source.user.name.text": [
      "dabitbol"
    ],
    "agent.name.text": [
      "sa-da-proxy-01"
    ],
    "cloud.service.name.text": [
      "GCE"
    ],
    "source.ip": [
      "86.245.8.29"
    ],
    "agent.name": [
      "sa-da-proxy-01"
    ],
    "event.agent_id_status": [
      "verified"
    ],
    "event.kind": [
      "event"
    ],
    "event.outcome": [
      "success"
    ],
    "event.original": [
      "1725204777.978 100929 86.245.8.29 TCP_TUNNEL/200 6880 CONNECT data.kameleoon.io:443 dabitbol HIER_DIRECT/65.109.36.162 -"
    ],
    "cloud.region": [
      "europe-west1"
    ],
    "cloud.instance.name.text": [
      "sa-da-proxy-01"
    ],
    "squid.peer_status": [
      "HIER_DIRECT"
    ],
    "input.type": [
      "filestream"
    ],
    "log.offset": [
      48814
    ],
    "data_stream.type": [
      "logs"
    ],
    "related.user": [
      "dabitbol"
    ],
    "tags": [
      "preserve_original_event",
      "squid-log",
      "forwarded"
    ],
    "cloud.machine.type": [
      "c2-standard-4"
    ],
    "cloud.provider": [
      "gcp"
    ],
    "agent.id": [
      "50a1c0bc-f736-44e7-8913-e5d42740c464"
    ],
    "cloud.service.name": [
      "GCE"
    ],
    "ecs.version": [
      "8.11.0"
    ],
    "observer.type": [
      "proxy"
    ],
    "agent.version": [
      "8.15.0"
    ],
    "squid.status_code": [
      200
    ],
    "destination.bytes": [
      6880
    ],
    "source.user.name": [
      "dabitbol"
    ],
    "http.request.body.bytes": [
      6880
    ],
    "source.address": [
      "86.245.8.29"
    ],
    "cloud.instance.id": [
      "3371506256334554537"
    ],
    "agent.type": [
      "filebeat"
    ],
    "event.module": [
      "squid"
    ],
    "related.ip": [
      "86.245.8.29"
    ],
    "log.file.device_id": [
      "2050"
    ],
    "observer.product": [
      "Squid"
    ],
    "elastic_agent.snapshot": [
      false
    ],
    "elastic_agent.id": [
      "50a1c0bc-f736-44e7-8913-e5d42740c464"
    ],
    "data_stream.namespace": [
      "default"
    ],
    "squid.peer_host": [
      "65.109.36.162"
    ],
    "event.duration": [
      100929000000
    ],
    "event.ingested": [
      "2024-09-01T15:33:17.000Z"
    ],
    "url.original": [
      "data.kameleoon.io:443"
    ],
    "@timestamp": [
      "2024-09-01T15:32:57.978Z"
    ],
    "cloud.account.id": [
      "elastic-sa"
    ],
    "log.file.inode": [
      "35192373"
    ],
    "data_stream.dataset": [
      "squid.log"
    ],
    "event.type": [
      "access"
    ],
    "log.file.path": [
      "/var/log/squid/access.log"
    ],
    "agent.ephemeral_id": [
      "7847ab21-1fa6-45c5-a9d8-923b066f9f63"
    ],
    "event.dataset": [
      "squid.log"
    ],
    "cloud.instance.name": [
      "sa-da-proxy-01"
    ],
    "cloud.project.id": [
      "elastic-sa"
    ]
  }
}

### What did you do?

Nothing special except upgrading the integrations

### What did you see?

See above 

### What did you expect to see?

The source.ip should be geo ip resolved.
The domains should be extracted 
The destination ip should be filled and geo ip resolved as well 

### Anything else?

My /var/log/squid/access.log is attached below 

[access.log](https://github.com/user-attachments/files/16829536/access.log)

**Comment by Danouchka** [comment]
below an image of my discover showing differences before and after


![Image](https://github.com/user-attachments/assets/5b3d8ace-883f-4d6c-a341-8c6c8ee35331)

**Comment by taylor-swanson** [comment]
Hey @Danouchka:

> The destination ip should be filled and geo ip resolved as well

In most situations I saw, the destination is a URL. If we can get an IP from that, I can run that through geoip, but I'm very hesitant to attempt to resolve a hostname to an IP, since there's no guarantee that the resolved IP is going to match the real IP that matches the log. I'd rather it not be present at all than get it wrong. The referrer/peer can also be an IP, so I can look into running that through geoip  as well.

**Comment by Danouchka** [comment]
Yes, the most important is the source.ip ie the one that is getting access to the proxy to go to internet as the destination ip is your proxy whose ip (the one seen by the agent) may be private.

**Comment by taylor-swanson** [comment]
> destination ip is your proxy whose ip (the one seen by the agent) may be private.

Just so I understand correctly, is that the peer address from the log? For example, `65.109.36.162` from this log:

`1725204777.978 100929 86.245.8.29 TCP_TUNNEL/200 6880 CONNECT data.kameleoon.io:443 dabitbol HIER_DIRECT/65.109.36.162 -`

**Comment by Danouchka** [comment]
86.245.8.29 is the source.ip in your case, the one requesting the internet URL 
65.109.36.162  is the ip of data.kameleoon.io (so the peer ip or destination ip ? )

**Comment by taylor-swanson** [comment]
I did some digging in the previous version and it did map the peer IP to destination IP (which makes sense to me). In the case there is no peer IP (and it went directly out to the URL), I'll place the URL's host into destination.address and copy it to destination.ip if it is an IP (and do geoip on it as well).

**Comment by Danouchka** [comment]
Hi @taylor-swanson 

seems _tmp variables are not cleaned by the integration 

![Image](https://github.com/user-attachments/assets/44dc1bcf-7b6f-48d0-a46e-ca6b09890031)

**Comment by taylor-swanson** [comment]
@Danouchka, are there errors being reported for those documents? There's a [remove processor](https://github.com/elastic/integrations/blob/main/packages/squid/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L232) that runs at the end of the pipeline that removes `_tmp`, but that won't run if the pipeline fails earlier.

**Comment by Danouchka** [comment]
Yes but I dont have any pipeline error in the records

**Comment by Danouchka** [comment]
Some more errors 
[Untitled discover search.csv](https://github.com/user-attachments/files/17281298/Untitled.discover.search.csv)

**Comment by Danouchka** [comment]
It happens when we have this kind of logs

> 1728218769.799      0 80.82.70.133 TAG_NONE/400 4191 o %84%B4,%85%AFn%E3Y%BBbhl%FF(=%27:%A9%82%D9o%C8%A2%D7%93%98%B4%EF%80%E5%B9%90 - HIER_NONE/- text/html

[search_squid.csv](https://github.com/user-attachments/files/17283030/search_squid.csv)

**Comment by taylor-swanson** [comment]
Looking at `search_squid.csv`, the issue is that TLS payloads are being recorded in the log:

![Image](https://github.com/user-attachments/assets/2af80b0c-475a-49a6-a5f5-8098b5089bac)

The hex sequence `0x16 0x03 0x01` forms the first part of a TLS Client Hello. The rest of the data afterward (and what uri_parts is trying to decode), is the rest of the client hello. Considering the status code is 400, it seems like this is a TLS/HTTPS request being sent to a non-TLS listener. This seems wrong, Squid really shouldn't be logging the raw bytes like this... but that's a question for the folks that maintain Squid.

**Comment by Danouchka** [comment]
Otherwise we can leave this way ...if it's too much complex

**Comment by taylor-swanson** [comment]
I suppose we could, it's worth noting that the message is a bit mangled, and at least another field is going to be incorrect (the http method is reported as `0x16 0x03 0x01`). I'm not sure how I feel about ignoring the failure. While it's nice for a situation like this, it will prevent other, legitimate issues from surfacing, making troubleshooting harder. You should be able to go in and modify the pipeline yourself to ignore errors. A warning, though, is that if you upgrade, you lose your local changes.

That said, the rest of the processors are just renames/sets and they don't appear to rely on the uri_parts processor (or can tolerate a field being absent). It's pretty trivial to move these processors around, so I'll work on a change to do that. I can also add the remove processor for _tmp to the failure handler, so if it does blow up, it will at least remove the _tmp fields.

**Comment by taylor-swanson** [comment]
I just merged a change (squid 1.0.2) which will silence the errors from uri_parts (but will still copy the value to `url.original`) and I also added remove processor which will clean up the _tmp fields if anything else goes wrong pipeline.
