### ISSUE TITLE
[crowdstrike.fdr]: Handle empty string in crowdstrike.aip

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#11050]
### Integration Name

CrowdStrike [crowdstrike]

### Dataset Name

crowdstrike.fdr

### Integration Version

1.40.0

### Agent Version

8.15.1

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.1

### OS Version and Architecture

AWS Linux on EC2

### Error Message

> Processor 'convert' with tag '' failed with message '' is not an IP string literal.

### Event Original

I don't have an `event.original`, but the event that was stored by the integration had:

```
"crowdstrike": {
  "ActiveDirectoryAuthenticationMethod": "0",
  "ActivityId": "E654B5F9-9FCD-4E9A-9F18-E433DB7ACBAC",
  "AuthenticationActivityId": "0737DAC6-66AE-42DE-B10A-FD151AE99B86",
  "ContextTimeStamp": "1970-01-20T23:16:31.471Z",
  "SourceAccountDomain": "EXAMPLE.COM",
  "SourceAccountObjectGuid": "62915660-5725-4B71-A494-46793F88877A",
  "SourceAccountObjectSid": "S-1-5-21-333333333-333333333-3333333333-333333",
  "SourceAccountSamAccountName": "bar",
  "SourceEndpointAccountObjectGuid": "9FF5B4D9-4FAD-47E7-89C0-0B06299F0AE8",
  "SourceEndpointAccountObjectSid": "S-1-5-21-222222222-222222222-2222222222-222222",
  "SourceEndpointAddressIP4": "192.168.0.1",
  "SourceEndpointHostName": "FOO",
  "SourceEndpointNetworkTag": "AWS-XXX",
  "SourceEndpointNetworkType": "1",
  "TargetDomainControllerObjectGuid": "11111111-1111-1111-1111-111111111111",
  "TargetDomainControllerObjectSid": "S-1-5-21-111111111-111111111-1111111111-111111",
  "aip": "",
  "cid": "11111111111111111111111111111111",
  "event_platform": "Win",
  "name": "ActiveDirectoryInteractiveDomainLogonV2",
  "timestamp": "2024-08-01T11:31:27.123Z"
}
```

### What did you do?

Ingested FDR data from an AWS S3 bucket.

### What did you see?

Some events that had `error.message`.

### What did you expect to see?

No `error.message` in any events.

**Comment by efd6** [comment]
@andrewkroh Is the timestamp there as seen in the original event? No other test examples use RFC3339.

**Comment by andrewkroh** [comment]
I am glad you asked because I grabbed the value last week and stuck it into my notes without much context. It looks like that was not a clean `event.original`, but was actually what the integration wrote as the value of the `crowdstrike` object. So I don't have an `event.original`, only evidence that the `aip` was an empty string. Sorry about that.

**Comment by efd6** [comment]
From events that I can see online, all timestamps in crowdstrike events are actually always fractional unix time (even the cases in `timestamp` which we have as RFC3339, but just handle because we natively do). I've altered the `ContextTimeStamp` in the test case to match that.
