### ISSUE TITLE
[discuss] Backporting and testing strategies

### ISSUE THREAD

**Issue by marc-gr** [elastic/integrations#1115]
In some situations, we might need to make fixes to packages that have released versions targeting multiple stacks.
Since we do not have a backport strategy for packages, we ended up with the following set of steps in the past:

- Doing the changes to the released packages targeting the older stack versions directly to package storage,
  eg: https://github.com/elastic/package-storage/pull/1273 and https://github.com/elastic/package-storage/pull/1372
- Later, doing them on integrations to the package targeting the latest stack version,
  eg: https://github.com/elastic/integrations/pull/986 and https://github.com/elastic/integrations/pull/1089

Among other issues, the process of backporting fixes to versions targeting older stacks is manual, and the PRs in package storage are really hard to review since they bring in all files in the package.

To improve this process, we might want to discuss some improvements around backporting strategies, testing in CI that acknowledge the stack constraints in the packages to avoid inadvertent breaking changes, etc.

**Comment by mtojek** [comment]
I'm afraid that the process will remain a bit manual, but we can improve it with tooling. Recently we've talked about it with @ruflin.

Let's try to describe steps for pushing a bugfix for an older package.

Initial state:

Package in ver. A: uses Kibana 7.13.0
Package in ver. C: uses Kibana 7.14.0

Goal:

We need to push a bugfix for A and release it as ver. B, which still uses Kibana 7.13.0.

Steps:

1. (elastic/integrations) Find the point in Git history for package that needs a fix, just before bumping up the Kiban constraint.
   For example last commit for the package revision using 7.13.0, not 7.14.0.
2. Create a branch out of it and name it `<package_name>-<stack_version>`. For example: `mysql-7.13.0`.
3. Apply necessary bugfixes and open a PR for it to the `<package_name>-<stack_version>` branch.
4. Once merged, the CI will kick off the job and publish the fixed package revision to Package Storage.

Once we agree on the steps, we can think about scripting around this.

**Comment by leehinman** [comment]
Another thing that might be nice is a check on semantic versioning.  If the `kibana.version` is a bump in MINOR version number then the package `version` should also be a bump in the MINOR version number.  That way we will have PATCH version numbers available.

## Good
|Package Version|Kibana Version| Date |
|-|-|-|
| 0.6.0 | ^9.1.0 | Jan 01, 2030 |
| 0.7.0 | ^9.2.0 | August 01, 2030 |
| 0.6.1 | ^9.1.0 | September 01, 2030 |

## Bad
|Package Version|Kibana Version| Date |
|-|-|-|
| 0.6.0 | ^9.1.0 | Jan 01, 2030 |
| 0.6.1 | ^9.2.0 | August 01, 2030 |
| 0.6.2 | ^9.1.0 | September 01, 2030 |

**Comment by andrewkroh** [comment]
Regarding the steps involved here's what I am thinking. The main change from what @mtojek proposed is to introduce tags.

1. Find the git tag that corresponds to the version that needs fix (okta-1.0.0).
2. Create a release branch to make the fix (release/okta-1.0.1).
3. Merge the a PR to the release branch.
4. Create a new git tag for the new release (okta-1.0.1).
5. Delete the release branch.

The tags make it easy to find the specific commit that corresponds to a package version.
