### ISSUE TITLE
[AWS] Update documentation to reference the information related to the applicable charges

### ISSUE THREAD

**Issue by muthu-mps** [elastic/integrations#11171]
### Summary

Currently, AWS integration points to refer the AWS integration to know more about the charges applied when we use APIs to fetch logs and metrics. But this note doesn't include the reference link to go to that documentation to look at more details.

![Image](https://github.com/user-attachments/assets/d2de628b-e260-4816-9eed-3fe2eaadb572)

we need to attach link which points to the actual documentation that has information related to the charges applied.

### Integrations List

- [x] Amazon Kinesis
- [x] AWS API Gateway
- [x] AWS Billing
- [x] AWS Cloudfront
- [x] AWS Cloudtrial
- [x] AWS Cloudwatch
- [x] Amazon DynamoDB
- [x] Amazon EBS
- [x] Amazon EC2
- [x] Amazon ECS
- [x] Amazon ELB
- [x] Amazon EMR
- [x] Amazon NetworkFirewall
- [x] Amazon Managed Streaming for Apache Kafka (MSK)
- [x] AWS Inspector
- [x] AWS Lambda
- [x] AWS NAT gateway
- [x] Amazon RDS
- [x] Amazon Redshift
- [x] AWS Route 53
- [x] Amazon S3
- [x] Amazon S3 Storage Lens
- [x] Security Hub
- [x] AWS SNS
- [x] AWS SQS
- [x] AWS Transit Gateway
- [x] AWS Usage
- [x] AWS VPC Flow
- [x] AWS VPN
- [x] AWS WAF
- [x] AWS Bedrock

Relates to https://github.com/elastic/integrations/issues/11389

**Comment by alaudazzi** [comment]
@muthu-mps 
I found this page https://docs.aws.amazon.com/whitepapers/latest/best-practices-api-gateway-private-apis-integration/cost-optimization.html#:~:text=You%20may%20incur%20additional%20charges,transfer%20data%20out%20of%20AWS.&text=Free%20tier%3A%20one%20million%20API,month)%3A%20%243.50%20(per%20million). Is there anything better you can suggest?

**Comment by alaudazzi** [comment]
Relates to https://github.com/elastic/integrations/pull/11244

**Comment by alaudazzi** [comment]
@muthu-mps 
Can you please confirm that for all the pages listed in the root comment, we need to reference the https://www.elastic.co/docs/current/integrations/aws#api-requests?

**Comment by alaudazzi** [comment]
Relates to https://github.com/elastic/integrations/issues/11389

**Comment by muthu-mps** [comment]
> [@muthu-mps](https://github.com/muthu-mps) Can you please confirm that for all the pages listed in the root comment, we need to reference the https://www.elastic.co/docs/current/integrations/aws#api-requests?

The above link has mention about all the API Requests and links the AWS documentation for pricing. One of the sub category covers `metrics collection and cost consideration`. Here we try to update the cost specific information only. So I would recommend to update the generic document to have a separate section for usage costs and then we can link the same in different integrations. WDYT?

cc: @agithomas

**Comment by alaudazzi** [comment]
@muthu-mps @agithomas 
quick recap of our chat today:

1. On the page [API requests](https://www.elastic.co/docs/current/integrations/aws#api-requests), move these two lines to the top of the table:
    Each of these APIs may generate extra charges on your AWS Account. Please refer to [AWS Princing](https://aws.amazon.com/pricing) for more information.
2. In the **IMPORTANT** note of each page listed in the root comment of this ticket, add a reference to the  [API requests](https://www.elastic.co/docs/current/integrations/aws#api-requests).
