### ISSUE TITLE
[GitLab] Add support for other GitLab logs

### ISSUE THREAD

**Issue by IanLee1521** [elastic/integrations#11218]
Hi there!

Early adopter of the Beta GitLab integration here.

I would like to request that you add support for some of [the other logs that GitLab produces](https://docs.gitlab.com/ee/administration/logs/), especially including the `nginx` logs it writes out (https://docs.gitlab.com/ee/administration/logs/#nginx-logs).

Others that seem to be prevalent producers, in our environment at least, include:

- [sidekiq](https://docs.gitlab.com/ee/administration/logs/#sidekiq-logs)
- [GitLab Pages logs](https://docs.gitlab.com/ee/administration/logs/#pages-logs)

**Comment by IanLee1521** [comment]
Thanks for adding these @tehbooom ! #11234 doesn't actually address the nginx part of this request though, so hoping to inquire further about that log specifically?

**Comment by tehbooom** [comment]
> Thanks for adding these @tehbooom ! #11234 doesn't actually address the nginx part of this request though, so hoping to inquire further about that log specifically?

Hey @IanLee1521 

You can add the nginx integration to the same policy of GitLab and add the paths for [access and error logs](https://docs.gitlab.com/ee/administration/logs/#nginx-logs).
