### ISSUE TITLE
[AWS] Support owning account for cross account monitoring

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#11260]
This issue is to track the work for adding `owning_account` config parameters into AWS integration for metrics data streams.
This parameter is already added in Beats: https://github.com/elastic/beats/pull/40691

**Comment by Kavindu-Dodan** [comment]
Beats version containing the change - [v8.15.2](https://www.elastic.co/guide/en/beats/libbeat/8.15/release-notes-8.15.2.html)
