### ISSUE TITLE
[squid]: squid integration grok error caused by unkown logformat

### ISSUE THREAD

**Issue by UweW** [elastic/integrations#11279]
### Integration Name

Squid Proxy [squid]

### Dataset Name

squid.log

### Integration Version

1.0.0

### Agent Version

8.15.2

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.2

### OS Version and Architecture

Fedora 39 x86_64

### Error Message

Hi,
squid integration fails with grok parsing error:
`Processor grok with tag grok_message in pipeline logs-squid.log-1.0.0 failed with message: Provided Grok expressions do not match field value: [<166>Sep 30 20:25:30 www.xxxx.xx(squid-1)[72246]: 1727720730.913     70 192.168.254.238 TCP_MISS/204 206 HEAD http://connectivitycheck.gstatic.com/generate_204 - ORIGINAL_DST/142.250.181.227 -]`

In the Integration overview you say:
```
Setup
[Configure Squid](https://wiki.squid-cache.org/Features/LogModules#Module:_System_Log) to export access logs using one of the supported methods (file (Module: Standard I/O), udp (Module: UDP Receiver), or tcp (Module: TCP Receiver)).
```
But the important infomation about the logformat is missing! Squid has at least 5 diffrent default formats.
What is the format the integration expects ? 
It would be best if the grok patterns were considered for all standard squid log formats in the pipeline.

Best regards
Uwe

### Event Original

<166>Sep 30 20:25:30 www.xxxx.xx (squid-1)[72246]: 1727720730.913     70 192.168.254.238 TCP_MISS/204 206 HEAD http://connectivitycheck.gstatic.com/generate_204 - ORIGINAL_DST/142.250.181.227 -

### What did you do?

configured firewall appliance to send squid logs to elastic-agent
```
  | TCP(4) | 192.168.250.2 | squid für fed:9004 - squid plugin
```

### What did you see?

grok parsing error

### What did you expect to see?

correctly parsed grok pattern.
It would be best if the grok patterns were considered for all standard squid log formats in the pipeline.

### Anything else?

correct dokumentation as well

**Comment by taylor-swanson** [comment]
Hey @UweW, the Squid integration currently supports the "native" format [described here](https://wiki.squid-cache.org/Features/LogFormat#squid).

I'll submit a change to update the documentation to reflect this.

You mention that there are 5 different formats. I see two listed on that page I linked (`native` and `common` formats). I know that squid can also be configured with a custom, user-defined pattern, but it is unlikely we'll support custom patterns like this. If there are other well-documented predefined patterns, we can certainly add that as an enhancement request for the squid integration to support them.

**Comment by qcorporation** [comment]
@UweW, the documentation has been submitted; if you require other format support, please create a ticket within elastic/integrations as an enhancement request.

Thank you for the issue and support for integrations!
