### ISSUE TITLE
[PANW]: Missing parsing of the suspicious domain and DNS query in the threat logs

### ISSUE THREAD

**Issue by willem-dhaese** [elastic/integrations#11291]
### Integration Name

Palo Alto Next-Gen Firewall [panw]

### Dataset Name

panw.panos*

### Integration Version

4.0.3

### Agent Version

8.14.3

### Agent Output Type

logstash

### Elasticsearch Version

8.14.3

### OS Version and Architecture

RHEL9

### Software/API Version

10.x

### Error Message

The domain and DNS Query which is suspicious in the PANW threat logs is not parsed. In the example doc, the value `*.r2[dot]dev` and `internshes[dot]com` is not stored in a separate field. Please put it for example in `url.original` ?

### Event Original

**Suspicious Domain**

`10.24.14.10,8.8.8.8,0.0.0.0,0.0.0.0,A_DST_L7D_DNS,domain\user01,,dns-base,vsys1,Data Groep,Servers,ae1.490,ae2.493,Panorama-Elastic,2024/10/01 10:43:54,34891187,2,59020,53,0,0,0x3000,tcp,sinkhole,"*.r2.dev",Suspicious Domain(12000000),any,medium,client-to-server,7401113521124350246,0x8000000000000000,10.0.0.0-10.255.255.255,10.0.0.0-10.255.255.255,,,0,,,0,,,,,,,,0,0,0,0,0,Core,AC5250,,,,,0,,0,,N/A,domain-edl,AppThreat-0-0,0x0,0,4291167295,,,5e791170-7507-4ab1-a951-79ebed0dad21,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,2024-10-01T10:43:55.308+02:00,,,,infrastructure,networking,network-protocol,3,"used-by-malware,has-known-vulnerability,pervasive-use",dns,dns-base,no,no,_reportid`

**Suspicious DNS Query**

`10.24.14.10,8.8.8.8,0.0.0.0,0.0.0.0,A_DST_L7D_DNS,,,dns-base,vsys1,Data Groep Gent,Servers,ae1.490,ae2.493,Panorama-Elastic,2024/10/01 10:32:30,34891187,2,52526,53,0,0,0x2000,udp,sinkhole,,Suspicious DNS Query (generic:internshes.com)(597246549),any,medium,client-to-server,7401113521124350246,0x8000000000000000,10.0.0.0-10.255.255.255,10.0.0.0-10.255.255.255,,,0,,,0,,,,,,,,0,0,0,0,0,Core,AC5250,,,,,0,,0,,N/A,dns,AppThreat-4957-5475,0x0,0,4291167295,,,5e791170-7507-4ab1-a951-79ebed0dad21,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,2024-10-01T10:32:30.409+02:00,,,,infrastructure,networking,network-protocol,3,"used-by-malware,has-known-vulnerability,pervasive-use",dns,dns-base,no,no,_reportid`

### What did you do?

Search for suspicious domains or suspicious DNS queries

### What did you see?

The suspicious domain or DNS query is not parsed.

### What did you expect to see?

The suspicious domain to be parsed in for example `url.original`, `dns.question.name`, 'dns.question.top_level_domain' etc..

**Comment by willemdh** [comment]
Any update? We are missing important info which is really necessary during IR.

**Comment by JoeySec** [comment]
I have been going through similar issues with the panw integration.

For both of these logs, what is the panw.panos.type and panw.panos.sub_type?

Within the pipeline using the sample Suspicious Domain log provided, the domain is contained in panw.panos.misc, which is removed at the end of the logs-panw.panos-4.0.4 pipeline. For other logs, this field is parsed out as a file or url based on the panw.panos.sub_type. I think there needs to be additional logical to check if pamw.panos.threat_category is "domain-edl", which  indicates a URL exists in the panw.panos.misc per Palo Alto's docs over at https://docs.paloaltonetworks.com/pan-os/11-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/threat-log-fields.

For the Suspicious DNS Query, the DNS name is within the panw.panos.threat.name field. You could create a custom pipeline (logs-panw.panos@custom) to parse that info out using dissect/grok and registered_domain processors. I would recommend getting a larger sample size and taking a look at Palo Alto's documentation on that signature for how the rule name can be structured.

**Comment by mjwolf** [comment]
Hi @willemdh, could you clarify what PAN-OS log format you're using, or if it's a custom log format?  From [here](https://docs.paloaltonetworks.com/pan-os/11-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/threat-log-fields), every log format begins with `FUTURE_USE, Receive Time, Serial Number, Type,...`. Your provided logs appear to begin with IP addresses, so I'm not sure what format they are.

**Comment by mjwolf** [comment]
Hi @JoeySec, I think your issue is a bit different than the originally reported problem here, but I'll look into it.

**Comment by willemdh** [comment]
> Hi [@willemdh](https://github.com/willemdh), could you clarify what PAN-OS log format you're using, or if it's a custom log format? From [here](https://docs.paloaltonetworks.com/pan-os/11-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/threat-log-fields), every log format begins with `FUTURE_USE, Receive Time, Serial Number, Type,...`. Your provided logs appear to begin with IP addresses, so I'm not sure what format they are.

Hmm you are right. Something is incorrect. It's very probable a miscopy. It's the normal log format threat logs. I'll try to find some extra examples asap, but drowing in work atm, so could take some time.
