### ISSUE TITLE
[Azure Logs] Certain fields are not being extracted

### ISSUE THREAD

**Issue by sheridansmall** [elastic/integrations#11306]
### Integration Name

Azure Logs [azure]

### Dataset Name

AZFWNetworkRule

### Integration Version

1.17.0

### Agent Version

8.14.3

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.14.3

### OS Version and Architecture

rhel

### Error Message

No error message but the ingest pipeline expects 35 fields e.g. "json.properties.DestinationIp" where the data is at other fields e.g. "json.DestinationIp".
The 35 expected fields are not found, and the data from the other fields is not ingested.

### Event Original

```
{
    "Action": "Allow",
    "DestinationIp": "[redacted]",
    "DestinationPort": 1234,
    "Policy": "[redacted]",
    "Protocol": "UDP",
    "Rule": "[redacted]",
    "RuleCollection": "[redacted]",
    "RuleCollectionGroup": "[redacted]",
    "SourceIp": "[redacted]",
    "SourcePort": 1234,
    "TenantId": "[redacted]",
    "TimeGenerated": "2024-10-02T10:23:00.0400850Z",
    "Type": "AZFWNetworkRule",
    "_Internal_WorkspaceResourceId": "[redacted]",
    "_ItemId": "[redacted]",
    "_ResourceId": "[redacted]"
}
```

### What did you do?

Default install with minimum configuration

### What did you see?

None of the expected 35 fields

### What did you expect to see?

The some or all of the expected 35 fields like "destination.ip"

### Anything else?

In the Ingest Pipeline there is for example:
```
  {
    "json": {
      "field": "event.original",
      "target_field": "json",
      "ignore_failure": true
    }
  }
```
then
```
  {
    "rename": {
      "field": "json.properties.DestinationIp",
      "target_field": "destination.ip",
      "ignore_missing": true
    }
  }
```
but there is no "properties" in "event.original"

**Comment by zmoog** [comment]
Hey @sheridansmall , my apologies for the delay.

How are you forwarding the firewall logs to the event hub? Are you using diagnostic settings, data collection rules, or logs analytics?

**Comment by sheridansmall** [comment]
Hi @zmoog,
Thanks for the reply.
We have a diagnostic setting on the firewall that sends the logs to a log analytics workspace and then we have a data export rule in place on the log analytics workspace that exports the same log data to the event hub.

**Comment by zmoog** [comment]
> Hi [@zmoog](https://github.com/zmoog), Thanks for the reply. We have a diagnostic setting on the firewall that sends the logs to a log analytics workspace and then we have a data export rule in place on the log analytics workspace that exports the same log data to the event hub.

Okay, it makes sense. My first guess was DCR, with log analytics workspace second.

Unfortunately, the log analytics workspace exports log events using a format other than the diagnostic settings (DS). As of today, the Azure Logs integration supports the DS logs format.

In the short term, I see two options available:

1. adapt the log event from log analytics workspace to the DS format using an agent processor (unfortunately, we can't use a custom ingest pipeline since Elasticsearch executes it _after_ the main pipeline)
2. add an additional DS to export the firewall logs directly to the event hub

**Comment by sheridansmall** [comment]
Thanks @zmoog,
We are going to look at option 2 "add an additional DS to export the firewall logs directly to the event hub"
