### ISSUE TITLE
Palo Alto Prisma Cloud

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1132]
### Description
Prisma Cloud is a cloud infrastructure security solution that enables you to address risks and secure your workloads in a heterogeneous environment (hybrid and multicloud) from a single console. It provides complete visibility and control over risks within your public cloud infrastructure—Amazon Web Services (AWS), Microsoft Azure, Google Cloud Platform (GCP), Oracle Cloud Infrastructure (OCI), Alibaba Cloud— and enables you to manage vulnerabilities, detect anomalies, ensure compliance, and provide runtime defense in heterogeneous environments, such as Windows, Linux, Kubernetes, Red Hat OpenShift, AWS Lambda, Azure Functions, and GCP Cloud Functions.

### Architecture
Prisma supports syslog, steps to configure syslog forwarding [here ](https://docs.paloaltonetworks.com/saas-security/saas-security-admin/saas-security-api/syslog-and-api-integration/syslog-integration/configure-syslog-monitoring.html) and syslog field descriptions [here](https://docs.paloaltonetworks.com/saas-security/saas-security-admin/saas-security-api/syslog-and-api-integration/syslog-integration/syslog-field-descriptions). 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by jamiehynds** [comment]
Keeping this open.

**Comment by amemkdm** [comment]
We just received a request from one of our customers to integrate prisma logs in to the siem for monitoring.

**Comment by leandrojmp** [comment]
Hello,

We are starting to use Prisma and need to ingest the data in your Elastic, but since there is no integration for it we will need to collect and parse the data ourselves.

Since the tags _In Progress_ and _8.11 candidate_ are added to this issue, I'm assuming that the work on this has started, is there any place where I can look how the work is going on, to use the same field names/mappings on our Logstash pipeline?

**Comment by jamiehynds** [comment]
Hi @leandrojmp - correct, we are actively working on a Prisma Cloud integration in partnership with Palo Alto. Unfortunately, I don't have a pipeline to share just yet, but we're expecting the PR to be raised very soon and you'll be able to see the mappings at that point. 

Just so we're on the page, is it Prisma Cloud or Prisma Access you want to ingest data from? We're working on Cloud, but have plans to focus on Access in a future release.

**Comment by jamiehynds** [comment]
@leandrojmp Prisma Cloud PR is up, if you'd like to check out the mappings, etc https://github.com/elastic/integrations/pull/8135

PR will be going through our review process and will be available as soon as it's merged. Happy to hear any feedback you may have on the mappings, dashboards, etc.

**Comment by jamiehynds** [comment]
@leandrojmp the integration is now available. Ingest pipelines are included, with dashboards to follow shortly. Stack version 8.10.1 is required. Happy to discuss any feedback you might have!

**Comment by leandrojmp** [comment]
Hello @jamiehynds,

We are on 8.10.2, so we can test this, I will ask the cloud team for the API credentials, but I got one question.

The Incident Audit dataset only works when using TCP/UDP inputs?  Is that right?

**Comment by jamiehynds** [comment]
@leandrojmp the Incident Audit events are not yet supported, as we couldn't generate the events manually. We're working with Palo Alto to get our hands on some sample events so we can add support. Do you happen to have some sample Incident Audit events you could share (privately)?
