### ISSUE TITLE
[forgerock]: Logs being pulled for wrong date time range

### ISSUE THREAD

**Issue by igrujic-ap** [elastic/integrations#11331]
### Integration Name

ForgeRock [forgerock]

### Integration Version

1.18.2

### Agent Version

8.15.2

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.2

### OS Version and Architecture

Elastic agent POD

### Error Message

There are no error messages however we see that elastic integration with ForgeRock is building request params with wrong values.

### What did you do?

We upgraded ForgeRock integration from 1.18.0 to 1.18.2

### What did you see?

we see in elastic logs that no events were published with message "request finished: 0 events published" but when we directly query ForgeRock we can see that logs are being published and are available.

In elastic logs we also see that we have request from 2. October with query string parameters in request begintime 3.October and endtime 4.October![Image](https://github.com/user-attachments/assets/4f734734-892e-4e13-90dc-9e3533d21279)

### What did you expect to see?

Logs from ForgeRock being ingested.

### Anything else?

We think it could be related to this pull request https://github.com/elastic/integrations/pull/11240/commits/b4e121092fa95c86bb941e089c2cb60f4142e19a

We think it is building endtime parameter incorrectly.

Before this PR endtime was built as 
value: '[[formatDate (now) "2006-01-02T15:04:05-07:00"]]'

so let's say last request was on October 1st at 12:00. This date and time will be used as begintime on next request and if we are running this every 10 minutes endtime in new request will be October 1st at 12:10 and it will pull only logs from these 10 minutes.

However after the change endtime is built as
value: '[[formatDate ((parseDate .cursor.last_timestamp "2006-01-02T15:04:05-07:00").Add (parseDuration "24h"))  "2006-01-02T15:04:05-07:00" ]]'

this means that for same example next request will have begintime on October 1st 12:00 and instead of trying to pull logs for next ten minutes it will put endtime as October 2nd at 12:00. This would also pull logs only for 10 minutes. but next request would use this date and time as begintime. This would cause request on October 1st at 12:10 to create request with begintime October 2nd at 12:00 and endtime as October 3rd at 12:00 which is in the future and no logs would be retrieved. This is what we see is happening.

As a proposal to fix this issue we think it should utilize both old and new logic (which is trying to address different issue). If current date and time (old logic) is less then 24 hours before begintime then use that as endtime. Otherwise use new logic where endtime will be calculated as time span of 24 hours from begintime to avoid ForgeRock rules violation of span bigger then 24 hours.

**Comment by efd6** [comment]
@igrujic-ap Thank you for reporting this. The issue is due to the use of the last `endTime` parameter, rather than the use of time of the last event. This is obviously incorrect as you point out. Unfortunately the API does not return the actual end of the request, so we will need to ensure that the range is correct in the parameter.
