### ISSUE TITLE
[Sublime Security]: Duplicate Data Ingestion when using API

### ISSUE THREAD

**Issue by christophercutajar** [elastic/integrations#11363]
### Integration Name

Sublime Security [sublime_security]

### Dataset Name

logs-sublime_security.audit-default

### Integration Version

1.0.0

### Agent Version

8.15.2

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.2

### OS Version and Architecture

GCP Kubernetes Engine (Standalone agent)

### What did you do?

Analyzing the agent config, we could not understand how the agent stores the state to avoid data duplication. Looking at the ingest pipeline, it was noticed that the `_id` of the document is computed at runtime.

![Image](https://github.com/user-attachments/assets/726e394e-7368-4ec8-adcb-6b813cf500d5)

We triggered a roll over task to the datastream using `POST logs-sublime_security.audit-default/_rollover`

Rollover response:

```
{
  "acknowledged": true,
  "shards_acknowledged": true,
  "old_index": ".ds-logs-sublime_security.audit-default-2024.10.04-000001",
  "new_index": ".ds-logs-sublime_security.audit-default-2024.10.07-000002",
  "rolled_over": true,
  "dry_run": false,
  "lazy": false,
  "conditions": {}
}
```

After the datastream was rolled-over, we restated the agent and checked the data.

Now it can be seen that the same documents ingested in the previous index, were re-ingested in the new index

![Image](https://github.com/user-attachments/assets/d57b931b-aa91-4d1f-a112-a47460077f29)

### What did you see?

Data ingested multiple times after an index roll-over.

### What did you expect to see?

Agent would keep the state of the data already ingested and would not re-ingest all the data.

### Anything else?

Policy Configuration:

![Image](https://github.com/user-attachments/assets/72d83169-a168-4162-8d36-266538af14e4)

**Comment by efd6** [comment]
It's unclear to me what it is that is wanted here. Can you explain what the current system does not do that you would want and why this is important?

**Comment by christophercutajar** [comment]
> It's unclear to me what it is that is wanted here. Can you explain what the current system does not do that you would want and why this is important?

Currently, the agent is re-ingesting all the data on every datastream rollover as the document ID is not found in the new datastream.  We would expect that the agent knows the last data ingested and continues ingesting from that point onwards.

**Comment by efd6** [comment]
Thanks. The [API provides a mechanism to start a request at an offset](https://docs.sublime.security/reference/listeventsinauditlog). It's not clear what the scope of time this offset is valid for. Currently the API collector makes use of this offset for pagination and does not persist the offset it keeps into the pagination for subsequent periodic collections (i.e. no cursor state is kept). We could keep the offset in the cursor, but there is nothing to indicate that this would be valid at an arbitrary time in the future, and if we do and it becomes invalid we would be guaranteeing that we will lose events. I think this needs clarification from Sublime.

**Comment by efd6** [comment]
@christophercutajar The change is [here](https://github.com/elastic/integrations/pull/11623). Can you take a look at it and check your endpoint to see whether the required invariants are held by the API?

**Comment by christophercutajar** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/60098546?s=64&amp;u=b5dfc00cc3216fd7ab52e38953be1458a16fd3df&amp;v=4">@christophercutajar](https://github.com/christophercutajar) The change is [here](https://github.com/elastic/integrations/pull/11623). Can you take a look at it and check your endpoint to see whether the required invariants are held by the API?

Apologies for the late reply, going to upgrade and test in our environment

**Comment by christophercutajar** [comment]
@efd6 I'm still seeing data being ingested multiple times. The below is the timeline of events on how to replicate the issue:

- 5 days ago I've upgraded the integration and the agent config
- Today I've triggered a rollover `POST logs-sublime_security.audit-default/_rollover`

```
{
  "acknowledged": true,
  "shards_acknowledged": true,
  "old_index": ".ds-logs-sublime_security.audit-default-2024.11.06-000004",
  "new_index": ".ds-logs-sublime_security.audit-default-2024.11.12-000005",
  "rolled_over": true,
  "dry_run": false,
  "lazy": false,
  "conditions": {}
}
```

- After the rollover, I've restarted the agent. It seems that the same documents ingested in the previous index, were re-ingested in the new index again. This is highlighted in the `event.ingested`

![Image](https://github.com/user-attachments/assets/72aac55f-f6c9-43d0-aecf-1d71ff1d73d6)

**Comment by efd6** [comment]
The way the change work requires that it has seen a high-water so that it can compare to it. When you upgraded, the cursor state would not have that information and so any events that would have been filtered will not be. Try again now that you have done the collection. If it still does not work, I will need to see debug-level logging. Please make that available internally since it will contain secrets. Ideally, the agent should only be running this integration in order to simplify the investigation.

**Comment by christophercutajar** [comment]
@efd6 can confirm that this is working perfectly! Great work 🚀
