### ISSUE TITLE
[AWS] Complete the API requests table with SQS API costs

### ISSUE THREAD

**Issue by alaudazzi** [elastic/integrations#11389]
On the integration doc page https://www.elastic.co/docs/current/integrations/aws#api-requests, address the following feedback:

"if we rely on that table to explain the costs associated monitoring then I think we need an new issue to ensure that the table is complete. When reading invocation logs, this integration may rely on SQS depending on configuration settings. The table doesn't account for SQS API costs related to reading S3 notifications (i.e. sqs:ReceiveMessage, sqs:DeleteMessage, sqs:ChangeMessageVisibility)."

CC @andrewkroh

**Comment by alaudazzi** [comment]
@muthu-mps @andrewkroh 
Where can I find the info required to complete the [API Requests](https://www.elastic.co/docs/current/integrations/aws#api-requests) table?

**Comment by muthu-mps** [comment]
@agithomas - Can you include the information other than @andrewkroh suggested need to be updated in the table.

**Comment by agithomas** [comment]
PR link : https://github.com/elastic/integrations/pull/12072

**Comment by agithomas** [comment]
Closing the issue as the PR is merged.
