### ISSUE TITLE
Duo Integration: receiving pipeline errors for Auth Logs

### ISSUE THREAD

**Issue by gtgod1** [elastic/integrations#11405]
### Integration Name

Cisco Duo [cisco_duo]

### Dataset Name

cisco_duo.auth

### Integration Version

v2.0.1

### Agent Version

8.15.2

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.2

### OS Version and Architecture

rhel 8

### Error Message

{
  "_index": ".ds-logs-cisco_duo.auth-default-2024.09.24-000012",
  "_id": "Sjk2gZIBB1Q8elu1qNlw",
  "_version": 1,
  "_score": 0,
  "_source": {
    "input": {
      "type": "cel"
    },
    "agent": {
      "name": "elkapxxxxx.xxxc.org",
      "id": "048da647-43d1-47dc-be17-733883f03e64",
      "type": "filebeat",
      "ephemeral_id": "6ee94f74-de3f-4e9d-be76-9eeaf9947487",
      "version": "8.15.2"
    },
    "@timestamp": "2024-10-12T14:51:31.274Z",
    "ecs": {
      "version": "8.11.0"
    },
    "data_stream": {
      "namespace": "default",
      "type": "logs",
      "dataset": "cisco_duo.auth"
    },
    "elastic_agent": {
      "id": "048da647-43d1-47dc-be17-733883f03e64",
      "version": "8.15.2",
      "snapshot": false
    },
    "error": {
      "message": [
        "failed eval: ERROR: <input>:51:54: no such overload: string(list)\n |     ).do_request().as(resp, (resp.StatusCode == 200) ?\n | .....................................................^",
        "field [original] not present as part of path [event.original]",
        "field [user] not present as part of path [user]"
      ]
    },
    "event": {
      "agent_id_status": "verified",
      "ingested": "2024-10-12T14:51:35Z",
      "kind": "pipeline_error",
      "category": [
        "authentication"
      ],
      "type": [
        "info"
      ],
      "dataset": "cisco_duo.auth",
      "outcome": "failure"
    },
    "tags": [
      "forwarded",
      "cisco_duo-auth"
    ]
  },
  "fields": {
    "elastic_agent.version": [
      "8.15.2"
    ],
    "event.category": [
      "authentication"
    ],
    "agent.type": [
      "filebeat"
    ],
    "event.module": [
      "cisco_duo"
    ],
    "agent.name.text": [
      "xxxx.xxxxx.org"
    ],
    "agent.name": [
      "xxxx.xxxxx.org"
    ],
    "elastic_agent.snapshot": [
      false
    ],
    "event.agent_id_status": [
      "verified"
    ],
    "event.kind": [
      "pipeline_error"
    ],
    "event.outcome": [
      "failure"
    ],
    "elastic_agent.id": [
      "048da647-43d1-47dc-be17-733883f03e64"
    ],
    "data_stream.namespace": [
      "default"
    ],
    "input.type": [
      "cel"
    ],
    "data_stream.type": [
      "logs"
    ],
    "tags": [
      "forwarded",
      "cisco_duo-auth"
    ],
    "event.ingested": [
      "2024-10-12T14:51:35.000Z"
    ],
    "@timestamp": [
      "2024-10-12T14:51:31.274Z"
    ],
    "agent.id": [
      "048da647-43d1-47dc-be17-733883f03e64"
    ],
    "ecs.version": [
      "8.11.0"
    ],
    "error.message": [
      "failed eval: ERROR: <input>:51:54: no such overload: string(list)\n |     ).do_request().as(resp, (resp.StatusCode == 200) ?\n | .....................................................^",
      "field [original] not present as part of path [event.original]",
      "field [user] not present as part of path [user]"
    ],
    "data_stream.dataset": [
      "cisco_duo.auth"
    ],
    "event.type": [
      "info"
    ],
    "agent.ephemeral_id": [
      "6ee94f74-de3f-4e9d-be76-9eeaf9947487"
    ],
    "agent.version": [
      "8.15.2"
    ],
    "event.dataset": [
      "cisco_duo.auth"
    ]
  }
}

### Event Original

i turned the preserve original event on but there are no fields present 

### What did you do?

configure both the3 api v1 and v2 sections

### What did you expect to see?

expected to see parsed logs

**Comment by gtgod1** [comment]
![Image](https://github.com/user-attachments/assets/7e99a1cf-e106-47ce-a226-2c6af3ecfa8c)

**Comment by efd6** [comment]
This is happening due to an attempt to convert a list to a string. There are a few places where this could be happening in the collector. Though none are obvious causes (least unlikely candidates are `response.metadata.next_offset` and `message_detail`; if it's the latter it hints that the configuration is incorrect).

I think we will need the integration configuration and some debugging data to be able to resolve this. Please post a redacted copy of the relevant part of the pre-config.yaml from a diagnostic bundle. It would also be helpful to see the input to the collector evaluation. This can be obtained from a debug logs (need to set log level to DEBUG) and searching for a log line with the message "request state". The contents are redacted, but please ensure that no sensitive information is included when you post it.

If these do not indicate a cause, looking at the request trace logs for the integration would be the next step. These _do_ include sensitive information, so let's not move there until we need to. If you want to take a look at these, they show the communication between the client and the endpoint. The HTTP status codes should all be 200, if they are not, this should help identify the issue.

**Comment by gtgod1** [comment]
This is the pre-config.yml section for duo auth . Hopefully I capured the relevant section. I will work on setting the log level to debug and getting the input to the collector evaluation.


id: cel-cisco_duo-xxxxxxxxxx-dddddddddddddddd
      meta:
        package:
            name: cisco_duo
            version: 2.0.1
      name: cisco_duo-1
      package_policy_id: xxxxxxxxxxxxx-d1de-4ddddddddddddd
      revision: 3
      streams:
        - config_version: 2
          data_stream:
            dataset: cisco_duo.auth
            type: logs
          id: cel-cisco_duo.auth-xxxxxxxxxxxxxxxxxxxxxxxxxx
          interval: 1m
          program: |
            (
                state.want_more ?
                    state
                :
                    state.with({
                        "mintime": state.?cursor.last_published.orValue(int(now - duration(state.initial_interval)) * 1000),
                        "maxtime": int(now - duration("2m")) * 1000,
                        "date": now.format(time_layout.RFC1123Z),
                    })
            ).as(state, state.with(
                request(
                    "GET",
                    state.?want_more.orValue(false) ?
                        state.next_url
                    :
                        state.url.trim_right("/") + "/admin/v2/logs/authentication?" + {
                            "limit": [string(int(state.limit))],
                            "maxtime": [string(int(state.maxtime))],
                            "mintime": [string(int(state.mintime))],
                            "sort": ["ts:asc"],
                        }.format_query()
                ).with(
                    {
                        "Header": {
                            "Content-Type": ["application/x-www-form-urlencoded"],
                            "Date": [state.date],
                            "Authorization": ["Basic " + (
                                state.integration_key + ":" + (
                                    [
                                        state.date,
                                        "GET",
                                        state.url.trim_prefix("https://"),
                                        "/admin/v2/logs/authentication",
                                        {
                                            "limit": [string(int(state.limit))],
                                            "maxtime": [string(int(state.maxtime))],
                                            "mintime": [string(int(state.mintime))],
                                            ?"next_offset": has(state.next_offset) ?
                                                optional.of([string(state.next_offset)])
                                            :
                                                optional.none(),
                                            "sort": ["ts:asc"],
                                        }.format_query()
                                    ].join("\n")
                                    .hmac("sha1", bytes(state.secret_key))
                                    .hex()
                                )
                            ).base64()],
                        },
                    }
                ).do_request().as(resp, (resp.StatusCode == 200) ?
                    bytes(resp.Body).decode_json().as(body, has(body.?response.authlogs) && size(body.response.authlogs) > 0 ?
                        {
                            "events": body.response.authlogs.map(item,
                                {
                                    "message": item.encode_json(),
                                }
                            ),
                            "url": state.url,
                            "integration_key": state.integration_key,
                            "secret_key": state.secret_key,
                            "limit": state.limit,
                            "mintime": state.mintime,
                            "maxtime": state.maxtime,
                            "date": now.format(time_layout.RFC1123Z),
                            "want_more": has(body.?response.?metadata.next_offset),
                            ?"next_offset": (has(body.?response.?metadata.next_offset) && body.response.metadata.next_offset != null) ?
                                                optional.of(string(body.response.metadata.next_offset))
                                            :
                                                optional.none(),
                            "next_url": (has(body.?response.?metadata.next_offset) && body.response.metadata.next_offset != null) ?
                                (
                                    state.url.trim_right("/") + "/admin/v2/logs/authentication?" + {
                                        "limit": [string(int(state.limit))],
                                        "maxtime": [string(int(state.maxtime))],
                                        "mintime": [string(int(state.mintime))],
                                        "next_offset": [string(body.response.metadata.next_offset)],
                                        "sort": ["ts:asc"],
                                    }.format_query()
                                )
                            :
                                state.url,
                            "cursor": {
                                ?"last_published": (has(body.?response.?metadata.next_offset) && body.response.metadata.next_offset != null) ?
                                    optional.of(body.response.metadata.next_offset.re_find("next_offset_timestamp"))
                                :
                                    optional.none(),
                            }
                        }
                    :
                        {
                            "events":[],
                            "want_more": false,
                        }

                    )
                :
                    bytes(resp.Body).decode_json().as(body,
                        {
                            "events": {
                                "error": {
                                    "code": has(body.code) ? string(body.code) : string(resp.StatusCode),
                                    "id": string(resp.Status),
                                    "message": "GET: " +
                                    (
                                        (has(body.message) && body.message != "") ?
                                            string(body.message) +
                                                (has(body.message_detail) ?
                                                    ": " + string(body.message_detail)
                                                :
                                                    ""
                                                )
                                        :
                                            string(resp.Status) + " (" + string(resp.StatusCode) + ")"
                                    ),
                                },
                            },
                            "want_more": false,
                        }
                    )
                )
            ))
          publisher_pipeline.disable_host: true
          redact:
            fields:
                - secret_key
          regexp:
            next_offset_timestamp: ^\d+
          resource.url: https://api-xxxxxxxxxx.duosecurity.com
          state:
            initial_interval: 4320h
            integration_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            limit: 100
            secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            url: https://api-xxxxxxxxxxxxxxxxxxxxxxx.duosecurity.com
            want_more: false
          tags:
            - preserve_original_event
            - forwarded
            - cisco_duo-auth

**Comment by efd6** [comment]
Thanks, that is exactly the part that I wanted (I added marks so that it is formatted correctly).

Unfortunately nothing there stands out as being the cause of this.

Debug logging is enabled in the fleet logging UI at the bottom of the page:

![Image](https://github.com/user-attachments/assets/351ca0b7-7779-4c8f-8cb8-3f1e5e96def7)

When you look at the debug logs, you should see log messages with the `message` field holding "request state". These will look something like this (note that the secrets are redacted, but the logging may include information that you consider sensitive, so if it does please redact before posting):

`{"log.level":"debug","@timestamp":"2024-10-14T22:32:15.611Z","message":"request state","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"cel-default","type":"cel"},"log":{"source":"cel-default"},"input_url":"http://svc-cisco_duo:8080","log.logger":"input.cel","log.origin":{"file.line":250,"file.name":"cel/input.go","function":"github.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run.func1"},"service.name":"filebeat","input_source":"http://svc-cisco_duo:8080","id":"cel-cisco_duo.auth-d829ac54-6888-455d-944f-75012ed7806d","cel":{"ecs.version":"1.6.0","state":"{\"initial_interval\":\"4320h\",\"integration_key\":\"temp_integration_key\",\"limit\":100,\"secret_key\":\"*\",\"url\":\"http://svc-cisco_duo:8080\",\"want_more\":false}"},"ecs.version":"1.6.0"}`

Shortly after this, you should see a log message with the `message` field holding "response state". This will be less informative here since it will just contain the error that we already know is happening :

`{"log.level":"debug","@timestamp":"2024-10-14T22:32:15.617Z","message":"response state","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"cel-default","type":"cel"},"log":{"source":"cel-default"},"id":"cel-cisco_duo.auth-d829ac54-6888-455d-944f-75012ed7806d","input_url":"http://svc-cisco_duo:8080","cel":{…`

For request trace logging, you need to edit the integration's configuration and toggle on the "Enable request tracing":

![Image](https://github.com/user-attachments/assets/77a65835-d125-4f74-bfac-086030aa6649)

Then, after running the integration for a period to allow some logs to accrue, go to the fleet agent management UI and go to the Diagnostics tab and "Request diagnostic .zip" and download it.

![Image](https://github.com/user-attachments/assets/a3a4b479-1981-4a69-9e32-f0a42cf917e9)

The request traces will be in "logs/data/cel", e.g.

![Image](https://github.com/user-attachments/assets/0f3a2335-8ee1-467c-9973-2aa81f304afb)

**Comment by gtgod1** [comment]
@efd6 I hope it captured something i can rerun again in the morning if it didn't.

[{log.leveldebug,@timestamp2024-10-1.txt](https://github.com/user-attachments/files/17370946/log.leveldebug.%40timestamp2024-10-1.txt)

**Comment by efd6** [comment]
@gtgod1 Please rotate your creds for that instance.

**Comment by efd6** [comment]
All the requests in that set of traces were successful (200, with data that looked like it had been redacted). So as far as I can see, you are getting logs in. How often do you see errors? I think this is going to need more careful examination of the debug logs (not the trace logs).

**Comment by gtgod1** [comment]
@efd6 I grabbed a snippet of what I think relates to the duo auth in the debug logs. I can share the entire debug log securely with you directly. A lot to redact lol 

[{log.leveldebug,@timestamp2024-10-1 snippet.txt](https://github.com/user-attachments/files/17378155/log.leveldebug.%40timestamp2024-10-1.snippet.txt)

**Comment by daletuttle** [comment]
We are also seeing this same issue. All incoming logs have this error.

**Comment by efd6** [comment]
@gtgod1 Please do send me the complete log; there is no error in the snippet that is posted, but it is the correct file. You can send me a DM on the community slack.

**Comment by efd6** [comment]
@gtgod1 and @daletuttle Do you get logs into the index? I would like to understand if this is a complete block of collection or a cosmetic logging error (both are significant, but knowing this will help narrow down which part of the code is at fault).

**Comment by gtgod1** [comment]
@ efd6 The telephony logs look fine with no errors and that is also in the v2 section of the API configuration.  

if I filter out the error field 

![Image](https://github.com/user-attachments/assets/c9c8c413-17c8-4c92-bc11-f7414195123a)

**Comment by efd6** [comment]
The telephony logs are not expected to be affected by this error mode. The only data stream that can be is the auth data stream.

**Comment by efd6** [comment]
I have found the issue.

From the request trace logs we see this.
```
...{"next_offset": ["1713397726733", "REDACTED"], "total_objects": 17683955}}, "stat": "OK"}
```

The next_offset field is an array, but the code is attempting to convert it to a string. This is not a valid conversion.

**Comment by daletuttle** [comment]
This is still broken it seems. I have a new error - 

[
  failed eval: ERROR: <input>:10:5: type conversion error from 'string' to 'int'
   | ).as(state, state.with(
   | ....^,
  field [original] not present as part of path [event.original]
]

**Comment by ae-oh-200** [comment]
@chrisberkhout  I updated to 2.0.3 this morning.

**Comment by gtgod1** [comment]
@chrisberkhout The same for me. on 2.0.3   failed eval: ERROR: <input>:51:54: type conversion error from 'string' to 'int'
   |     ).do_request().as(resp, (resp.StatusCode == 200) ?
   | .....................................................^,
  field [original] not present as part of path [event.original]

**Comment by sberkee** [comment]
We are also experiencing the error above since the update to 2.0.2/3.

I have opened an elastic support case for this issue.

**Comment by chrisberkhout** [comment]
@ae-oh-200 @gtgod1 @sberkee Thanks for the updates. I am working on a fix for this issue and will post here when it's ready.

**Comment by anniegale9538** [comment]
Thanks for working this @chrisberkhout ! Just noting 01768971 is also getting the same error of:

```
[
failed eval: ERROR: <input>:51:54: type conversion error from 'string' to 'int'
| ).do_request().as(resp, (resp.StatusCode == 200) ?
| .....................................................^,
field [original] not present as part of path [event.original]
]
```
Elastic Agent v8.15.2
Cisco Duo integration v2.0.3

**Comment by chrisberkhout** [comment]
Please try cisco_duo version 2.0.4 for the fix for the `type conversion error from 'string' to 'int'` issue in `auth`.

**Comment by gtgod1** [comment]
installed v 2.0.4  and nothing from the auth data stream since. Not even the errors.

**Comment by ae-oh-200** [comment]
I am at 2.0.4 now, I have a new error.

[GET:{"code": 42901, "message": "Too Many Requests", "stat": "FAIL"}, field [original] not present as part of path [event.original]]

**Comment by chrisberkhout** [comment]
@ae-oh-200 That is what Duo responds with when there are too many requests. It should now do no more than 30 requests per minute, so this is unexpected. I will open a PR to make the limit configurable so you can try slowing it down further.

**Comment by ae-oh-200** [comment]
The default is 100 on the integration. I dropped it to 25 and still have to many request errors.

**Comment by gtgod1** [comment]
i will try that as well

**Comment by chrisberkhout** [comment]
> The default is 100 on the integration. I dropped it to 25 and still have to many request errors.

The limit of 100 is the number of items to fetch in each request (lowering this actually means you need more requests to get your data).

Now in 2.0.5 you can lower the rate of requests per second:

![Image](https://github.com/user-attachments/assets/d255f042-8d90-4cce-a0c1-5c2aed37eab4)

**Comment by ae-oh-200** [comment]
It started to work but was pulling logs from April, even though my interval was set to 24 hours. I removed the integration from my policy, then added it back. Now I have a new error, and trace logs will not work - 

[
  failed eval: ERROR: <input>:9:5: type conversion error from 'string' to 'google.protobuf.Duration'
   | ).as(state, state.with(
   | ....^,
  field [original] not present as part of path [event.original]
]

**Comment by gtgod1** [comment]
rate limit of 0.2 worked for me

**Comment by tbeermann** [comment]
On cisco_duo version 2.2.0 in the cisco_duo.auth datastream.  Still seeing errors after having tried many different adjustments to Interval and Rate Limit:

`[GET:{"code": 42901, "message": "Too Many Requests", "stat": "FAIL"}, field [original] not present as part of path [event.original]]`

**Comment by chrisberkhout** [comment]
@tbeermann It seems that you're still sending too many requests to the Duo API. This integration is expected to run on one agent only. If you're running it on multiple agents, that will be duplicating work, but also it can easily exceed the allowed request rate. The Duo API documentation suggests a rate of up to 50 requests per minute is allowed. If the integration is set to not exceed that, and it's only running in one place, then look for other sources of requests, for example, another script that's using the same credentials.
