### ISSUE TITLE
[m365_defender]: Answer Parsing Errors

### ISSUE THREAD

**Issue by Oliver-Re** [elastic/integrations#11412]
### Integration Name

Microsoft M365 Defender [m365_defender]

### Dataset Name

m365_defender.event

### Integration Version

2.14.1

### Agent Version

8.14

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.14.3

### OS Version and Architecture

Kube

### Error Message

field [answers] not present as part of path [m365_defender.event.additional_fields.answers]

### What did you do?

use integration

### What did you see?

Error message

### What did you expect to see?

no error messages

### Anything else?

following error message in logs, can a check be added to ensure answers exist

**Comment by efd6** [comment]
There is not enough information here to be able to know what the problem is. Can you provide the `event.original` for a failing parse?

**Comment by Oliver-Re** [comment]
Nvm just seen this has been fixed by - https://github.com/elastic/integrations/pull/10947 we haven't got the latest's integration (thought we did) as we still on 8.14.3
