### ISSUE TITLE
[CISCO_IOS]: Custom grok pattern CISCO_HOSTNAME cannot handle FQDNs

### ISSUE THREAD

**Issue by ebonybubbles** [elastic/integrations#11436]
Integration Name
Cisco IOS [Cisco IOS]

Dataset Name
cisco_ios.log

Integration Version
1.27.2

Agent Version
8.14.3

Agent Output Type
elasticsearch

Elasticsearch Version
8.15.2

OS Version and Architecture
ESS

Software/API Version
No response

Error Message
Processor "grok" with tag "grok_header" in pipeline "logs-cisco_ios.log-1.27.2" failed with message "Provided Grok expressions do not match field value: [<event.original>]

Event Original
<189>Oct 16 07:41:48 foo-bar-host.foo.bar.gov 157475316: *Oct 16 2024 07:39:09.425 UTC: %AUTHMGR-5-SECURITY_VIOLATION: Security violation on the interface GigabitEthernet1/0/13, new MAC address (0015.5d9c.3d01) is seen.AuditSessionID  Unassigned

What did you do?
Tested event original in the ingest pipeline UI

What did you see?
GROK error

What did you expect to see?
Expected the pattern to be able to handle FQDN

Anything else?
n/a

**Comment by qcorporation** [comment]
From @efd6 recommendations:

Recommend just fork out the IPORHOST that's in the canonical definitions and define that as CISCO_HOSTNAME, making the change to HOST so that we accept the Cisco variants.

Note/warning: this may break grok ordering...
