### ISSUE TITLE
[NetFlow Records]: Dashboard links broken

### ISSUE THREAD

**Issue by ulab** [elastic/integrations#11448]
### Integration Name

NetFlow Records [netflow]

### Dataset Name

netflow.log

### Integration Version

2.19.1

### Agent Version

8.15.2

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.2

### OS Version and Architecture

Debian 11.11

### Error Message

404 Dashboard not found

### What did you do?

We tried clicking on "Dashboard Navigation [Logs Netflow]" links.

### What did you see?

A "404 Dashboard not found" page.

### What did you expect to see?

The other dashboards that are linked.

### Anything else?

The dashboard links "Dashboard Navigation [Logs Netflow]" ("Overview", "Conversation Partners", "Traffic Analysis", "Top-N", "Geo Location", "Autonomous Systems", "Flow Exporters", "Raw Flow Records") are not working (404). 

We tried removing the existing ones and re-installing the assets without any change.

**Comment by mjwolf** [comment]
Hi @ulab, I haven't been able to reproduce this problem. As you can see below, all of the links are working for me. This is with 8.15.2 elastic stack and v2.19.1 of the netflow integration. Do you know of any other details that might be needed to reproduce this?

https://github.com/user-attachments/assets/64352ca5-1100-44ca-a9d9-000cfb68ce70

**Comment by andrewkroh** [comment]
@ulab, Can we get a sanitized [HAR](https://www.elastic.co/blog/generating-browser-har-file-kibana-troubleshooting) file from your browser or some other demonstration to see what paths it is trying to load that result in a 404.

@mjwolf, We should replace the markdown panel with a [Links Panel](https://www.elastic.co/guide/en/kibana/current/dashboard-links.html#add-links-panel) which has better handling of relative paths. For example, if you load the netflow dashoard from inside the security app (Security -> Dashboards -> [Logs Netflow] Overview), none of the links work. But with a Links Panel they should work.

**Comment by ulab** [comment]
Do these URLs help already? If not, I'll look into generating a HAR file.

What I do:
- Kibana homepage
- Use search bar to search for Netflow 
- Select `[Logs Netflow] Overview` (`/app/dashboards#/view/91d5754e-5763-4443-8d69-3c11612986e7?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-15m,to:now))`)
- Click `Conversation Partners` (`/app/dashboards#/dashboard/netflow-acd7a630-0c71-4840-bc9e-4a3801374a32`)
- 404 Dashboard not found

If after the search I select `[Logs Netflow] Conversation Partners`, it loads `/app/dashboards#/view/807a7afc-797a-4d9c-a0b5-ebe366e5514b?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-15m,to:now))` which works. 

Clicking on `Overview` on that page, then results in 404 again (`/app/dashboards#/view/netflow-34e26884-161a-4448-9556-43b5bf2f62a2`).

Same happens when I use Analytics / Dashboards:
- search for `Netflow`
- select `[Logs Netflow] Overview` (`/app/dashboards#/view/91d5754e-5763-4443-8d69-3c11612986e7?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-15m,to:now))`
- `Conversation Partners` (`/app/dashboards#/dashboard/netflow-acd7a630-0c71-4840-bc9e-4a3801374a32`)
- 404 Dashboard not found

**Comment by mjwolf** [comment]
I see the error when I access it from the security dashboard. I'll work to replace the navigation panel with a Links panel
