### ISSUE TITLE
Microsoft Defender for Cloud

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1148]
### Description
Microsoft Defender for Cloud (formerly Azure Security Center) assesses hybrid IT environments and enables security professionals to understand the status of their resources, and whether they are secure. It aids with threat protection by assessing workloads and raises threat prevention recommendations and security alerts. An overview of Defender for Cloud can be found [here](https://docs.microsoft.com/en-us/azure/security-center/security-center-introduction). 

### Architecture
Streaming alerts to Azure Event Hubs and Microsoft's Security Graph API are possible, we should aim to support both. More information available [here](https://docs.microsoft.com/en-us/azure/security-center/export-to-siem). 

Defender for Cloud Alerts reference here: https://learn.microsoft.com/en-us/azure/defender-for-cloud/alerts-reference

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by gils3nan** [comment]
Adding a +1 to follow this issue
