### ISSUE TITLE
[Prometheus] Improve documentation

### ISSUE THREAD

**Issue by muthu-mps** [elastic/integrations#11490]
The prometheus integration documentation needs to be enhanced to follow the documentation guidelines. As part of this improvement we need to address the issues listed below.

The configurations has references to Metricbeat in multiple places.

The highlighted section would show the Tips section isn't aligned properly.

![Image](https://github.com/user-attachments/assets/76009058-4b9a-4f7d-805f-0c118faeb4ed)

![Image](https://github.com/user-attachments/assets/7890915b-3a40-4c10-a08d-1b6b9449f671)

**Comment by alaudazzi** [comment]
@muthu-mps Many formatting issues reported in this ticket are automatically solved as soon as the migration from MDX → AsciiDoc is completed (https://github.com/elastic/integration-docs/pull/579). 

> The configuration has references to Metricbeat in multiple places.
What do you propose to fix here?
