### ISSUE TITLE
Adjust input.type 

### ISSUE THREAD

**Issue by michalpristas** [elastic/integrations#115]
In https://github.com/elastic/beats/pull/19360 we transitioned to use `logfile` as an input type for gathering logs from file. 

Previously we were using `logs`. As for now both options are supported but we will move to only support `logfile` soon.
DoD for this issue is having all `input.type` replaced from `logs` to `logfile`

**Comment by mtojek** [comment]
@michalpristas is there any deadline for this change?

**Comment by ruflin** [comment]
If we get it in in the next two weeks, we can also remove it from the agent and don't need to support it moving forward.

**Comment by ruflin** [comment]
I opened https://github.com/elastic/integrations/pull/119 as a draft to see the effort and effects of it.

**Comment by mtojek** [comment]
Resolving.
