### ISSUE TITLE
[Integrations Update] Add `okta.debug_context.debug_data.privilegeGranted` field to the Okta system integration

### ISSUE THREAD

**Issue by sodhikirti07** [elastic/integrations#11508]
### Description
The Okta system integration provides valuable context on IAM activities, as well as group and user account management events. The SecML team plans to leverage this information to develop several security use cases.

One of these use cases is privilege escalation detection, for which we need to request a field that isn’t directly available in the integration: `okta.debug_context.debug_data.privilegeGranted`. While this flag exists within the `okta.debug_context.debug_data.flattened field`, the lack of mappings for it means we can't perform runtime calculations to extract just this value. Additionally, most of the other information in the flattened field isn't relevant to us.

Furthermore, we've requested similar data from InfoSec for model development, and they are only comfortable providing access to the `privilegeGranted` value as a separate field (`okta.debug_context.debug_data.privilegeGranted`), due to the presence of other sensitive information in it. This field would help us assess the level of privilege assigned to users, which would be highly valuable for our model.

cc: @pantea-elastic 

#### Additional Context:
https://github.com/elastic/seceng/issues/8509#issuecomment-2435946335

**Comment by efd6** [comment]
This should already be possible by using the "Remove flattened debug data" option (set to true).

**Comment by sodhikirti07** [comment]
@efd6 I tried enabling the "Remove flattened debug data" flag on a test cluster, but I'm still not seeing a field related to `privilegeGranted`. There is, however, a field for `privilegeRevoked`, specifically `okta.debug_context.debug_data.privilegeRevoked`.

**Comment by sodhikirti07** [comment]
> This should already be possible by using the "Remove flattened debug data" option (set to true).

@efd6 Thank you, the above suggestion worked. Closing this issue as completed.
