### ISSUE TITLE
Box

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1151]
### Description
Box is a secure cloud storage and collaboration service that allows businesses and individuals to easily share files. Each time files are uploaded, accessed, or modified in Box, data is generated. By ingesting Box activity logs, you're able to monitor the authentication activity as well as monitoring data movement to the cloud. Combining this data with other events can lead to the detection of data exfiltration attacks.

### Architecture
The Box API can be leveraged for SIEM integration, reference guide [here](https://developer.box.com/reference/). Sample 'event' response [here](https://developer.box.com/reference/resources/events). 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [x] Supported versions of the monitoring target are documented
- [x] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to:

### New Package

- [x] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [x] Dashboards exists
- [x] Screenshots added or updated
- [x] Datastream filters added to visualizations

### Log dataset changes

- [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [x] Generated output for at least 1 log file exists
- [x] Sample event (`sample_event.json`) exists

**Comment by djptek** [comment]
Screenshot of the "Add Integration" page

<img width="428" alt="image" src="https://user-images.githubusercontent.com/11043991/179966646-1d0b1c51-2405-481a-8a5f-6bd2eef197ac.png">

**Comment by djptek** [comment]
Adding [multiple data streams](https://github.com/elastic/integrations/pull/3677#issuecomment-1232626535) for the Box Shield events

**Comment by djptek** [comment]
Box Shield Alert Streams looking good and Flagged for review

**Comment by epixa** [comment]
@jamiehynds Can this be closed now that we have the new integration? We should probably track follow up work as new issues.
