### ISSUE TITLE
[Falco]: Dashboard seems to be broken

### ISSUE THREAD

**Issue by nick-alayil** [elastic/integrations#11511]
### Integration Name

Falco [falco]

### Dataset Name

falco.alerts

### Integration Version

1.0.2

### Agent Version

8.16

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.16

### OS Version and Architecture

Amazon Linux 2023

### What did you do?

Ingest falco data in to Elastic using Falcosidekick but it could be done using falco integration as well. In the context of the issue, I assume how data is ingested have less relevance. I may be wrong here. Irrespective of the ingestion methodology it run through the same pipelines and would end up populated in the dashboard.

### What did you see?

Falco dashboard seems to be broken by looking at `log-*` index pattern, which ends up showing broken widgets / cards in the dashboard. Also, in `Alerts by Host - Top 10 [Logs Falco]` widget / card, table is expecting `host.hostname` field, which is in fact not present in the falco.alerts datastream. I tried to duplicate the dashboard and edited it to look specifically at `logs-falco* ` index pattern by creating a new data view and made most of the widgets / cards look at the new data view, which fixed many broken experiences. The details of this explanation is visible in the attached recording. Sorry for the lengthy 2.10mints recording.

https://upload.elastic.co/d/9a180431a47a43b55c42881fc6cfef3c1c79f6944bdf9427cf500313f1820108
AuthZ token: f92143b2d591efab

### What did you expect to see?

Expectation is to see only data from logs-falco* reflected in all the widgets / cards inside the falco dashboard.

**Comment by nick-alayil** [comment]
Summary of sync w/ @chemamartinez 

Confirmed that dashboard filter by default to `data_stream.dataset : falco.alerts` showing only falco content. However, if an user remove the filter, of course it'll populate data from all `logs-*` indices. The real problem is dashboard `reset` button seems to showcase only in some cases to revert to default / original state.

Alerts by Host widet is broken because of changes made in [this PR](https://github.com/elastic/integrations/pull/11051). We need to modify this widge to look for `host.name` instead of `host.hostname`

`event.original` column of Alert Stream widget/card seems to be showing no value since the file data stream is missing it. We need to make sure we populate that field as it's value to see the raw event.

**Comment by chemamartinez** [comment]
I've found several issues when forwarding directly from Falco Sidekick to Elastic without using the integration. The incoming events don't follow the expected format for the ingest pipeline, as the ingest pipeline expects to parse events that are read by the integration.

This leads to a few issues, the main problem is that Filebeat inputs encapsulate every event into the message field, so the ingest pipeline starts working on that field. Sidekick sends directly a JSON with the Falco data in the root object, so:
- `event.original` is not populated.
- some fields are in conflict with ECS, for example Falco includes a field called `rule` that is in conflict with the ECS rule parent field.
- some other important fields are not mapped to ECS.
- visualizations depending on these fields get broken.

Working on a fix to adapt the integration's ingest pipeline to be compatible with events ingested directly from Falco Sidekick.
