### ISSUE TITLE
Crowdstrike Falcon Data Replicator

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1156]
### Description
Our existing Crowdstrike integration ingests real-time detections/alerts from the Falcon platform via the Streaming API. While ingesting detections into Elastic SIEM is hugely valuable, we see some Crowdstrike customers with a requirement for more granular visibility into endpoint activity and long-term storage of raw event data from endpoints.

Falcon Data Replicator (FDR) provides raw event data and telemetry for deeper visibility and long-term storage of events in a SIEM. 

### Architecture
Crowdstrike provides a managed S3 bucket to users for short-term storage, as well as an SQS account. Raw events are delayed by up to 5 days, however we have seen customers with near-real time events. FDR repo [here](https://github.com/CrowdStrike/FDR). 

Sample events has been provided by customers, available internally.

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [x] Supported versions of the monitoring target are documented
- [x] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to: 7.15

### New Package

- [x] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [x] Dashboards exists
- [x] Screenshots added or updated
- [x] Datastream filters added to visualizations

### Log dataset changes

- [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [x] Generated output for at least 1 log file exists
- [x] Sample event (`sample_event.json`) exists

**Comment by andrewkroh** [comment]
PR: https://github.com/elastic/integrations/pull/1522
