### ISSUE TITLE
[Proofpoint On Demand] Investigate adding forward proxy support

### ISSUE THREAD

**Issue by cpascale43** [elastic/integrations#11581]
Currently, the Proofpoint On Demand integration doesn't support proxying websocket connections. This is necessary to prevent the integration from being blocked by the user's firewalls.

Investigation is needed as to what changes are needed to support forward proxying.

**Comment by ShourieG** [comment]
@cpascale43, I'm looking into this. Forward proxy with (optional) TLS support will need to be implemented at the input level.

**Comment by ShourieG** [comment]
@cpascale43, support for forward proxy and TLS based authentication have now been added to the input. Will update the integration accordingly when the changes go live.

**Comment by cpascale43** [comment]
Closing as completed
