### ISSUE TITLE
Hashicorp Vault

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1158]
### Description
HashiCorp Vault is a secrets management tool specifically designed to control access to sensitive credentials in a low-trust environment. It can be used to store sensitive values and at the same time dynamically generate access for specific services/applications on lease.

One of the Mitre Att&ck techniques, [T1555.005](https://attack.mitre.org/techniques/T1555/005/), is "Credentials from Password Stores: Password Managers". 

### Architecture
Logging via file, syslog and socket are supported. Relevant documentation available [here](https://www.vaultproject.io/docs/audit). 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by andrewstucki** [comment]
For the format of the audit and operational logs, this article seems helpful (the configuration docs don't document the payload structure):

https://support.hashicorp.com/hc/en-us/articles/360000995548-Audit-and-Operational-Log-Details
