### ISSUE TITLE
[Custom Threat Intelligence]Intelligence tab in Security Solution UI is not populated correctly

### ISSUE THREAD

**Issue by narph** [elastic/integrations#11586]
The Intelligence tab in Security Solution UI is not populated correctly although documents are coming in.

![Image](https://github.com/user-attachments/assets/69c5e287-d252-4879-bcfc-50ccdf6b9c14)

ask @narph for sample data

**Comment by chemamartinez** [comment]
Main issue on this topic is the lack of the field `thread.feed.name` when configuring the integration to connect to an external API. Trend visualisation in the Intelligence UI tab requires that field by default to display indicators:
![Image](https://github.com/user-attachments/assets/cc1945e5-f0be-4131-b5d7-4b04ca0b2482)

Missing options were added at https://github.com/elastic/integrations/pull/11867.
