### ISSUE TITLE
Add configurable retry policy for GCS integration connection failures

### ISSUE THREAD

**Issue by cpascale43** [elastic/integrations#11580]
Currently, when the GCS integration encounters connection issues, it has a [fixed retry policy](https://www.elastic.co/docs/current/integrations/google_cloud_storage) of 2 retries (3 total attempts) for file downloads. This is not configurable by users, which can lead to integration failures when encountering temporary network instability.

Example error: 
```
elastic_agent.filebeat [elastic_agent.filebeat][error] Input 'gcs' failed with: input.go:130: input gcs-google_cloud_storage failed: read tcp: connection reset by peer
```

Investigation is needed to:
- Determine if adding configurable retry settings is possible
- Assess which retry parameters could be exposed/which aspects of retry behavior are controlled by Elastic vs. GCS 

See: https://github.com/elastic/enhancements/issues/22943

**Comment by ShourieG** [comment]
@cpascale43, So the current retry only applies to failed jobs that we store internally in our registry. I believe the configurable retry should apply to the gcs sdk operations that work directly with the api. I will make an update exposing that in the config. But the failed jobs retry is something that we do internally separate from what is provided via the sdk. Making that configurable can cause negative effects by increasing the amount of error logs to an unwanted extent. Ideally implementing retriers at the sdk levels will reduce the number of failed jobs automatically by a big amount.
