### ISSUE TITLE
[AWS docs] Required permissions under AWS custom logs

### ISSUE THREAD

**Issue by octavioranieri** [elastic/integrations#11603]
Currently we only mention the required permissions under the parent AWS integration, which would cover all the AWS integrations:
https://www.elastic.co/docs/current/integrations/aws#aws-permissions

Users may need more granular of what’s _required_ for the specifics instead of having all the permissions.

[AWS custom logs docs](https://www.elastic.co/docs/current/integrations/aws_logs) should have the specific required permissions, similar to the Filebeat module:
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-aws-s3.html#_aws_permissions_2

**Comment by lucabelluccini** [comment]
The request here could be expanded further, where we should have a way to include the documentation associated to a specific input in all integrations using it.

E.g. `aws-s3` input  is used in several integrations (O11y & Security owned) and in all of them generally the settings and prerequisites are similar.

**Comment by lucabelluccini** [comment]
FYI @alaudazzi / @eedugon do you know what might be the best way to put this under the radar?

**Comment by alaudazzi** [comment]
@lucabelluccini Thanks for raising this! It makes sense to provide more granular info where needed and consolidate similar settings to facilitate discoverability. I can follow up on this ticket.

**Comment by alaudazzi** [comment]
@lucabelluccini 
I'm working on this ticket and I try to recap below what is needed:
- be more specific about the required permissions (check the [Filbeat module](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-aws-s3.html#_aws_permissions_2) as a good example)
- replicate/reference them in all the integrations that apply

Can you confirm this is correct?
Who can provide the input to update the docs?

**Comment by alaudazzi** [comment]
@lucabelluccini 
Thank you for your feedback. It makes sense to track the second part in a separate issue: https://github.com/elastic/integrations/issues/11793.

**Comment by alaudazzi** [comment]
CC @kaiyan-sheng
