### ISSUE TITLE
Adopting Wildcard Fields 

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1163]
Wildcard is a data type for Elasticsearch string fields introduced in Elasticsearch 7.9. Wildcard optimizes performance for queries using wildcards (*) and regex, allowing users to perform grep-like searches without the limitations of the existing text and keyword types. 

ECS is supporting wildcards ([RFC here](https://github.com/ebeahan/ecs/blob/wildcard-rfc-stage-2/rfcs/text/0001-wildcard-data-type.md#identified-wildcard-fields)) for the following fields:

| Field Set | Field(s) |
| --------- | -------- |
| [`error`](0001/error.yml) | `error.stack_trace` |
| [`http`](0001/http.yml) | `http.request.body.content`<br> `http.response.body.content` |
| [`process`](0001/process.yml) | `process.command_line` |
| [`registry`](0001/registry.yml) | `registry.data.strings` |
| [`url`](0001/url.yml) | `url.full`<br> `url.original`<br> `url.path` |

There is an impact on indexing throughput (5% decrease on average) and storage (5% increase on average) based on our performance testing of wildcard fields. 

With a set of security integrations GA'ing in 7.14, we will update these integrations to change keyword fields to wildcard in 7.14. Beats modules will not be updated to ensure existing Beats users are not impacted. 

**Integrations to be updated for 7.14**
- [x] Windows Security (System integration) https://github.com/elastic/integrations/pull/1185
- [x] Windows PowerShell https://github.com/elastic/integrations/pull/1161
- [x] Windows Sysmon https://github.com/elastic/integrations/pull/1161
~- [ ] auditd~
- [x] Suricata https://github.com/elastic/integrations/pull/1162
- [x] Zeek https://github.com/elastic/integrations/pull/1164
- [x] Netflow https://github.com/elastic/integrations/pull/1179
- [x] O365 https://github.com/elastic/integrations/pull/1180
- [x] Cisco https://github.com/elastic/integrations/pull/1181
- [x] Palo Alto https://github.com/elastic/integrations/pull/1182
~- [ ] Okta~
- [x] Fortinet https://github.com/elastic/integrations/pull/1183

**Comment by mtojek** [comment]
While working on the https://github.com/elastic/package-spec/issues/63 I introduced a simple dependency management to import ECS field definitions (name, type, description) directly from ECS repository. I will try to enable this feature for some packages in elastic/integrations.

For reference: https://github.com/elastic/elastic-package/blob/master/test/packages/nginx/data_stream/access/fields/ecs.yml#L6

Is it something that will be useful here?
