### ISSUE TITLE
[CrowdStrike Falcon Intelligence]: IOC enrichment failed for custom IOCs except IP

### ISSUE THREAD

**Issue by sitharhlaing** [elastic/integrations#11688]
### Integration Name

CrowdStrike [crowdstrike]

### Dataset Name

ti_crowdstrike.ioc

### Integration Version

v1.1.7

### Agent Version

8.13.3

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.13.3

### OS Version and Architecture

Oracle Linux Server 9.4

### Error Message

<html>
<body>

Ignored value (The value in this field is malformed and can't be searched or filtered)
--

</body>
</html>

### Event Original

{"action":"no_action","applied_globally":false,"created_by":"me@mydomain.com","created_on":"2024-11-11T09:17:03.445826361Z","deleted":false,"description":"Test hash IOC","expired":false,"from_parent":false,"host_groups":["my_host_group"],"id":"a3redactedredactedredactedredactedredactedef21","metadata":{},"modified_by":"me@mydomain.com","modified_on":"2024-11-11T09:17:03.445826361Z","platforms":["windows"],"severity":"medium","type":"md5","value":"65efdcbd4bc64e6e48d82bfa31f710fd"}

### What did you do?

I added custom IOCs of different types (hashes, domains, IPs) in crowdstrike portal
![Image](https://github.com/user-attachments/assets/86ea127b-cc43-416d-9fa2-aaf009343b65)

### What did you see?

In kibana, I found the IOC values are just enriched to IPs regardless of the original type which caused this issue if the IOC type is not IP address
![Image](https://github.com/user-attachments/assets/2bcdd885-1686-4542-abd5-fb570e0c9c12)

Just IP address IOC types are enriched as intended.
![Image](https://github.com/user-attachments/assets/d4de1a29-24ec-47d8-9a08-ca09d5dfb0e6)

### What did you expect to see?

All the IOC types should enriched as intended.

### Anything else?

To search, filter and correlate with ti_crowdstrike.ioc.value field, we need that field to be well enriched regardless of the IOC type.

**Comment by efd6** [comment]
@sitharhlaing Thank you for reporting this. I have sent a [change](https://github.com/elastic/integrations/pull/11703). Unfortunately, this will require that you re-index to pick up the fix.
