### ISSUE TITLE
ESET Protect Cloud

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1175]
### Description
ESET PROTECT Cloud allows you to manage ESET products on workstations and servers in a networked environment with up to 10,000 devices from one central location. Using the ESET PROTECT Cloud Web Console, you can deploy ESET solutions, manage tasks, enforce security policies, monitor system status and quickly respond to problems or threats on remote computers.

### Architecture
Syslog is supported, with JSON being a supported format. Documentation available [here](https://help.eset.com/protect_admin/80/en-US/admin_server_settings_export_to_syslog.html). 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by presianbg** [comment]
Hi,

Is there something we (users of ESET) can do to speed-up the integration process ?

Cheers,
PY

**Comment by jamiehynds** [comment]
Hey @presianbg! A sample data set would give us a great head start when developing this ESET integration. If you're willing to provide a broad set of sample events (sanitised and ideally JSON formatted) it would be a big help.

**Comment by presianbg** [comment]
Great! 

Sure, I totally can do that - collecting as much as possible sanitized and anonymized ESET Protect generated events in a json format. 
Should I upload them here or there is more suitable place to do so ?

**Comment by jamiehynds** [comment]
Great - thanks! If they are sanitized and you're happy to upload here, that's fine, but if you prefer to send them to me directly, I can provide my contact details.

**Comment by presianbg** [comment]
@jamiehynds , I will need one more week due traveling and etc... 
I will ping here again once the datasets are ready for you.

**Comment by dmaasland** [comment]
For what it's worth I did a mapping of these fields to normalized fields for Azure Sentinel:

https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ESETPROTECT/Parsers/ESETPROTECT.txt

I would be happy to help creating an ECS mapping as well.

**Comment by jamiehynds** [comment]
Hey @dmaasland - sounds great! If you'd like to develop an integration for ESET, I'd be happy to walk you through our partnership program whereby we can provide support from our developers as you build the integration, as well as promotion of the integration, etc.

**Comment by dmaasland** [comment]
Sounds cool, hit me up :)

**Comment by presianbg** [comment]
> Hi! We just realized that we haven't looked into this issue in a while. We're sorry! We're labeling this issue as `Stale` to make it hit our filters and make sure we get back to it as soon as possible. In the meantime, it'd be extremely helpful if you could take a look at it as well and confirm its relevance. A simple comment with a nice emoji will be enough `:+1`. Thank you for your contribution!

Yes, this integration is still highly demanded among Elastic users.

**Comment by gord-lyr** [comment]
Hey - any update on this? I see that someone contributed log samples back in Oct 2021, and the elasticbot came through marking it as stalled (then removed the stalled marker), but I can't find an integration and no updates...

**Comment by jamiehynds** [comment]
@dmaasland @presianbg @gord-lyr if you're still interested in an Eset Protect integration, we've just shipped our integration which includes ECS mappings, dashboards, etc and developed in partnership with ESET. Elastic v8.12 is required.
