### ISSUE TITLE
[Github] Add support for enterprise audit events in github integration

### ISSUE THREAD

**Issue by narph** [elastic/integrations#11776]
> When enabling GitHub Audit Integration
> https://www.elastic.co/docs/current/integrations/github
> 
> we noted it only supports organizations- but we need the audit events for our enterprise as noted here:
> https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/audit-log-events-for-your-enterprise
> 
> Is there a way the integration can be upgraded to grab audit events from enterprise as well?
> 
> We believe it might be as easy as adding `{{api_url}}/enterprise/{{enterprise}}/audit-log`
> instead of `{{api_url}}/orgs/{{organization }}/audit-log`
> to the integration.

**Comment by kcreddy** [comment]
Related: https://github.com/elastic/integrations/issues/6643.
