### ISSUE TITLE
[AWS][ELB] Create support for Connection Logs under Amazon ELB dataset

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#11770]
ELB_LOGS dataset under AWS package presently supports Access Log only. 

Add support for Connection Logs for Application Load Balancers.

To Enable Connection Logs : `EC2 -> Load Balancer -> Attributes -> Connection Logs`

Connection Log Syntax : [AWS Documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-connection-logs.html#connection-log-entry-format)

**Comment by agithomas** [comment]
Related PR: https://github.com/elastic/integrations/pull/11933

**Comment by lalit-satapathy** [comment]
@agithomas 

Can this be closed?

**Comment by agithomas** [comment]
Closed as all the planned tasks are now complete
