### ISSUE TITLE
Provide self-managed package-registry that backs integrations UI

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#1178]
Not all Elastic Stack setups have access to the internet. For the Ingest Manager to fully function, access to `https://epr.elastic.co` is required. To work around this, it is possible to modify the URL to which Kibana connects. This can be done through `xpack.fleet.registryUrl: 'http://localhost:8080'`. Today this mainly used for the development of the package registry and testing of new packages before they are released. 

IMPORTANT: This config should not be used by users yet and is not supported!

With the above config, it is is possible to run a registry on prem. The package registry with packages is available as docker container under `docker.elastic.co/package-registry/distribution:production` for production. This is currently compatible with 7.10.0 deployment of Kibana. To run this registry locally, the following command can be used: `docker run -p 8080:8080 docker.elastic.co/package-registry/distribution:production`

Even though all of the above is possible today, it is not supported and for development only. This issue is to discuss further on what the open issues are to make it supported and how to solve them.

Issues that are still open:

* As long as epr.elastic.co is used, we can guarantee the registry is always the newest version. As soon as it is run on prem, Kibana must enforce a minimal version of the registry to properly work. What is our compatibility matrix?
* What is the recommended upgrade scenario for on prem registry users? How often will these users need / get updates for the packages?
* What version do we recommend on prem users to use?
* What is our recommended way of running the registry?

**Comment by simitt** [comment]
When running elastic-agent in airgapped environments, we need to be able to recommend running their own package registry to users. This can be a requirement already today for ECE with apm deployments >= 7.13. 
@masci can the work on this be prioritized?

**Comment by mtojek** [comment]
Currently we have this guide: https://github.com/elastic/package-storage#air-gapped-environments

**Comment by simitt** [comment]
Thanks @mtojek! Is there an overview around missing steps to make this GA and officially supported?

**Comment by mtojek** [comment]
Let me pass this question to @akshay-saraswat . I remember that there were few items in the "brainstorm" doc (e.g. proper Docker tags).

**Comment by ruflin** [comment]
The 4 points I made in the initial issue description still apply.

**Comment by akshay-saraswat** [comment]
> Thanks @mtojek! Is there an overview around missing steps to make this GA and officially supported?

@simitt Please refer [this document](https://docs.google.com/document/d/1FvI13YLBpPLG6MtBZvYE2Il0jC2oIygu38nKtpn5JXY) for the GA plan. With the 7.15 release, we plan to announce the beta version.

**Comment by jsoriano** [comment]
Updating docs for 7.16 in https://github.com/elastic/observability-docs/pull/1287.

**Comment by akshay-saraswat** [comment]
I believe, with self-managed EPR GA in 7.16, we have accomplished the scope of this ticket. Does anyone have any objection if I close this issue?
