### ISSUE TITLE
[Juniper SRX] Add event.category and event.outcome to failed SSH login attempt

### ISSUE THREAD

**Issue by Oddly** [elastic/integrations#11834]
We have added Juniper switches to this integration, but we see no SIEM alerts on failed SSH attempts to this switch.
Looking at this integration, it seems like this can be added easily by doing the following steps.

Original event:
```
<37>1 2024-11-22T12:45:00.207+01:00 ams-edge-sw-003 sshd - SSHD_LOGIN_FAILED [junos@2636.1.1.1.4.82.30 username="user1" source-address="192.168.0.3"]
```
This are the relevant fields as parsed by the integration:

juniper.srx.tag: SSHD_LOGIN_FAILED
source.user.name: user1

It seems to me that by filtering for "SSHD_LOGIN_FAILED" and then setting event.category (authentication) and event.outcome (failed ?) this can be easily added to existing SIEM alerts.

**Comment by laraMorenoIgle** [comment]
Testing with the sample data provided above, I verified that `event.category` is populated withe value `network` using Juniper SRX integration version `1.21.2.``
`event.outcome` is not populated  though.

**Comment by Oddly** [comment]
Hi Lara,

The above PR pushes the version of the integration to `1.21.3` and populates `event.outcome` and `event.category` with relevant changes.
