### ISSUE TITLE
microsoft_exchange_online_message_trace: indexing errors due to duplicate documents

### ISSUE THREAD

**Issue by efd6** [elastic/integrations#11911]
It seems that in some cases documents are not uniquely identified by the set of fields that are used to [fingerprint during ingest](https://github.com/elastic/integrations/blob/fc1c51338d9966a24b581f38f52e87a5d692db5f/packages/microsoft_exchange_online_message_trace/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L290-L301)

- email.from.address
- email.to.address
- email.message_id
- email.local_id
- email.subject
- event.outcome
- email.attachments.file.size

We need to investigate the what set makes a reasonable identification for unique documents (`event.original` has been suggested, but we should see if we can get away with a smaller signal if possible).

**Comment by jvalente-salemstate** [comment]
Are you able to tell if the duplicate documents have differing delivery statuses? That one bit is not included in the fingerprint, while it's the one that is likely changing and causing duplicate documents. 

These 3 may be enough to identify each uniquely:

- email.local_id
- email.to.address
- microsoft.online_message_trace.Status

The first two are generally "good enough" for identifying a unique message but the message trace may also have Pending/Getting Status as an initial status before being updated to Delivered/Quarantined/etc.

**Comment by efd6** [comment]
Thanks for that suggestion @jvalente-salemstate.
