### ISSUE TITLE
Cybereason

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1192]
### Description
Cybereason EDR is a full-featured EDR solution designed to catch, analyze, and defend against highly advanced network threats in real-time directly at the endpoint. Cybereason allows organizations to correlate data across machines and generate contextualized alerts to monitor threats as they’re discovered at any point in the attack chain.

### Architecture
An API is available, but no public documentation. Users have to request an API key directly from Cybereason. Sample event available [here](https://docs.rapid7.com/insightidr/cybereason/). 

Worth noting, an existing [experimental FortiClient integration](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-fortinet.html#_clientendpoint_fileset_settings) exists. This will be deprecated upon release of a new FortiClient integration. 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by SourinPaul** [comment]
@jamiehynds this issue is currently not in the security-teams repo. Hence, I was unable to assign the `v8.13.0` label to this issue. 

Can you please update this label after re-organizing? Thanks!

**Comment by jamiehynds** [comment]
@SourinPaul label added.
