### ISSUE TITLE
[Cloudtrail] Important changes to CloudTrail events for AWS IAM Identity Center

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#11940]
Evaluate the impact of the below-mentioned changes on the existing dataset - AWS Cloudtrail

Effective January 13, 2025, IAM Identity Center will stop emitting userName and principalId fields under the [user identity element](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-user-identity.html) in CloudTrail events. These fields will be excluded from the CloudTrail events that are initiated when users sign in to IAM Identity Center, use the [AWS access portal](https://docs.aws.amazon.com/singlesignon/latest/userguide/using-the-portal.html), and access AWS accounts through the [AWS CLI](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/sso.html). Instead, IAM Identity Center now emits user ID and Identity Store Amazon Resource Name (ARN) fields to replace the userName and principalId fields, simplifying user identification. IAM Identity Center CloudTrail events will also specify IdentityCenterUser as the [identity](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-user-identity.html) type instead of Unknown, providing a clear identifier for users.

Reference : https://aws.amazon.com/blogs/security/modifications-to-aws-cloudtrail-event-data-of-iam-identity-center/

**Comment by andrewkroh** [comment]
Sounds like a duplicate of #11882 ?

**Comment by agithomas** [comment]
> Sounds like a duplicate of https://github.com/elastic/integrations/issues/11882 ?

Yes, you are right. Closing this issue.
