### ISSUE TITLE
[Okta]: Ingest pipeline not parsing `okta.debug_context.debug_data.flattened.tunnels`

### ISSUE THREAD

**Issue by procule** [elastic/integrations#11955]
### Integration Name

Okta [okta]

### Integration Version

3.0.0

### Agent Version

8.15.3

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.3

### OS Version and Architecture

COS 117 LTS (GKE)

### What did you do?

Configured normally to retrieve Okta logs via API.

I was able to create a runtime field that show the text with:
```
def tunnels = doc['okta.debug_context.debug_data.flattened.tunnels'];
if (tunnels != null) {
    emit(tunnels.value)
}
```

Also, using this Ingest pipeline correctly parse the text into an "object":

```
{
  "json": {
    "field": "okta.debug_context.debug_data.flattened.tunnels",
    "target_field": "okta.debug_context.debug_data.flattened.tunnels",
    "if": "ctx.okta?.debug_context?.debug_data?.flattened?.tunnels != null"
  }
}
```

### What did you see?

Not the full original but only the relevant part. 

Note that the `tunnels` attribute is only present when `okta.security_context.is_proxy == true`

```
      "debug_context": {
        "debug_data": {
          "flattened": {
            "tunnels": "[{\"anonymous\":true,\"operator\":\"NORD_VPN\",\"type\":\"VPN\"}]",
            "authnRequestId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "oktaUserAgentExtended": "okta-auth-js/7.8.1 okta-signin-widget-7.25.0",
            .....
```

```
    "okta.debug_context.debug_data.flattened": [
      {
        "tunnels": "[{\"anonymous\":true,\"operator\":\"NORD_VPN\",\"type\":\"VPN\"}]",
        "authnRequestId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "oktaUserAgentExtended": "okta-auth-js/7.8.1 okta-signin-widget-7.25.0",
       ...
```

### What did you expect to see?

The JSON text being parsed in the `flattened` field and a new `okta.debug_context.debug_data.tunnels` field:

```
"debug_context": {
  "debug_data": {
    "flattened": {
      "tunnels": [
        {
          "anonymous": true,
          "operator": "NORD_VPN",
          "type": "VPN"
        }
      ],
...
```
```
"okta.debug_context.debug_data.tunnels": [
    {
      "anonymous": true,
      "operator": "NORD_VPN",
      "type": "VPN"
    }
 ]
```

### Anything else?

Related: https://github.com/elastic/integrations/pull/11396

**Comment by procule** [comment]
From the Okta System Logs:

```
...
  "published": "2033-01-01T22:44:35.333Z",
  "securityContext": {
    "isProxy": true
  },
  "severity": "INFO",
  "debugContext": {
    "debugData": {
      "tunnels": "[{\"anonymous\":true,\"operator\":\"NORD_VPN\",\"type\":\"VPN\"}]",
      "authnRequestId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
...
```

**Comment by efd6** [comment]
@procule Have you tried using ["Remove flattened debug data"](https://github.com/elastic/integrations/blob/1fcc9e02dd9f651f6a894186fae67f3564c3e49a/packages/okta/data_stream/system/manifest.yml#L23-L30)? When this is set to true, the data are stored in a non-flattened object in `okta.debug_context.debug_data`.

**Comment by procule** [comment]
> [@procule](https://github.com/procule) Have you tried using ["Remove flattened debug data"](https://github.com/elastic/integrations/blob/1fcc9e02dd9f651f6a894186fae67f3564c3e49a/packages/okta/data_stream/system/manifest.yml#L23-L30)? When this is set to true, the data are stored in a non-flattened object in `okta.debug_context.debug_data`.

I changed the setting but still, the `tunnels` field is not parsed:

```
      "debug_context": {
        "debug_data": {
          "tunnels": "[{\"anonymous\":true,\"operator\":\"WARP_VPN\",\"type\":\"VPN\"}]",
```

**Comment by procule** [comment]
Oh, forgot to add that one:

```
    "okta.debug_context.debug_data.tunnels": [
      "[{\"anonymous\":true,\"operator\":\"WARP_VPN\",\"type\":\"VPN\"}]"
    ],
```

**Comment by procule** [comment]
I tried some simulation of the "logs-okta.system" ingest pipeline and that would work for both "flattened" and "not flattened":

```
    {
      "pipeline": {
        "if": "ctx._conf?.remove_flattened_debug != true",
        "name": "logs-okta.system-2.13.0-use_flattened_debug"
      }
    },
    {
      "pipeline": {
        "if": "ctx._conf?.remove_flattened_debug == true",
        "name": "logs-okta.system-2.13.0-no_use_flattened_debug"
      }
    },
    {
      "rename": {
        "field": "json.debugContext.debugData.tunnels",
        "target_field": "okta.debug_context.debug_data.tunnels",
        "if": "ctx.json?.debugContext?.debugData?.tunnels != null"
      }
    },
    {
      "json": {
        "field": "okta.debug_context.debug_data.tunnels",
        "target_field": "okta.debug_context.debug_data.tunnels",
        "if": "ctx.okta?.debug_context?.debug_data?.tunnels != null"
      }
    },
    {
      "json": {
        "field": "okta.debug_context.debug_data.flattened.tunnels",
        "target_field": "okta.debug_context.debug_data.flattened.tunnels",
        "if": "ctx.okta?.debug_context?.debug_data?.flattened?.tunnels != null"
      }
    }
```

If `_conf.remove_flattened_debug == true`:

![Image](https://github.com/user-attachments/assets/82232d74-6949-4cee-9f2a-60ecc6e4d577)

![Image](https://github.com/user-attachments/assets/dde4ebde-e000-44d8-b0bc-87d4fb9f25cf)


If `_conf.remove_flattened_debug == false`:

![Image](https://github.com/user-attachments/assets/cde8aab3-c4a9-46c5-a179-ea5df21abd51)

![Image](https://github.com/user-attachments/assets/dd6e6d4f-e3f7-4603-9f48-c8a83a9b24f3)

**Comment by efd6** [comment]
OK. Thanks.
