### ISSUE TITLE
Proofpoint On Demand

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1196]
### Description
Proofpoint Email Protection helps you secure and control inbound and outbound email through an easy-to-use cloud-based solution. On Demand is their SaaS offering, and is based upon their Messaging Security Gateway appliances.  

### Architecture
Proofpoint On Demand API can be used for SIEM integration. Integration guide available [here](https://help.proofpoint.com/Threat_Insight_Dashboard/API_Documentation/SIEM_API). 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by andrewkroh** [comment]
This API uses WebSockets and Filebeat does not currently support it. Tracking that in https://github.com/elastic/beats/issues/30991.

**Comment by harwinds** [comment]
If this can be prioritized, that would be great.

**Comment by jamiehynds** [comment]
Hi @harwinds - while we now have a Proofpoint TAP integration, POD is certainly something we would like to also support. Unfortunately, Proofpoint do not provide POD access to technology partners such as Elastic, and therefore our ability to develop this integration is hindered. If you are willing to share some sample events from POD, we could certainly look into an integration based on the event sample.

**Comment by jamiehynds** [comment]
Still valid. @ShourieG working on websocket support in Filebeat which will enable us to support the OnDemand API and build an integration.
