### ISSUE TITLE
[google_workspace] Add Chrome audit events to the Google Workspace integration

### ISSUE THREAD

**Issue by cpascale43** [elastic/integrations#11989]
# Description
The Google Workspace integration within Elastic currently lacks the capability to collect and analyze Chrome log events. These events are critical for security monitoring, as they provide insights into user activities that could indicate security threats, such as the downloading of malicious software or accessing suspicious URLs. Incorporating Chrome log events into the integration significantly enhances the ability of security teams to monitor, detect, and respond to potential threats in a timely manner.

See: Useful event types/fields in [Chrome logs](https://cloud.google.com/chronicle/docs/ingestion/default-parsers/collect-chrome-management)

## Use Cases
- Security teams will be able to detect and investigate security incidents more efficiently.
- Organizations can ensure compliance with security policies and regulations that require monitoring of web activities.
- IT departments can monitor and enforce corporate browsing policies.

# Architecture 
The enhancement can be implemented by extending the existing Google Workspace integration to include access to Chrome audit events via the Activity Reports API.

### References
- [Chrome Audit Activity events](https://developers.google.com/admin-sdk/reports/v1/appendix/activity/chrome)
- [Activity Reports API](https://developers.google.com/admin-sdk/reports/reference/rest/v1/activities/list)

**Comment by farbod-sec** [comment]
Hi team, Airbnb was wondering if they could get an expected ETA on this so they can plan accordingly.

**Comment by piyush-elastic** [comment]
@farbod-sec  - This PR is merged, Integration should be available to use for chrome events with latest version 2.29.0.
