### ISSUE TITLE
Cisco Secure Email

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1199]
### Description
The Cisco Email Security Appliance is an email security gateway product. It is designed to detect and block a wide variety of email-borne threats, such as malware, spam, and phishing attempts. Because so many of today's attacks occur through email messages, having an email security gateway has become a necessity for most organizations.

### Architecture
Syslog is supported - relevant documentation [here](https://www.cisco.com/c/en/us/td/docs/security/esa/esa11-1/user_guide/b_ESA_Admin_Guide_11_1/b_ESA_Admin_Guide_chapter_0100110.html). 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by LaZyDK** [comment]
I would like to support this integration.

**Comment by jamiehynds** [comment]
Thanks @LaZyDK! We're actually just finalising this integration, and a PR will be available soon. I'll ping the PR to you when it's available for your review. Would also appreciate your feedback once the integration is available.

**Comment by jamiehynds** [comment]
Closing, as our Secure Email Gateway integration is now available: https://docs.elastic.co/integrations/cisco_secure_email_gateway

**Comment by LaZyDK** [comment]
How about support for the cloud version of this appliance, called Cisco Cloud Email Security/Cisco Secure Email Cloud Gateway?

**Comment by jamiehynds** [comment]
I'll create a new issue to track support for the Cloud Gateway. We have yet to research an integration, but I assume [these Logging API's](https://www.cisco.com/c/en/us/td/docs/security/esa/esa14-0/api/b_ESA_API_Guide_14-0/b_ESA_API_Guide_chapter_010.html#Cisco_Concept.dita_484044c4-26aa-43b4-aa4d-094a995691e2) are the preferred method?

**Comment by LaZyDK** [comment]
You got it. :)
And I know that @P1llus already gave it some thoughts at our dev session a while back.

**Comment by jamiehynds** [comment]
Thanks for confirming. New issue here: https://github.com/elastic/integrations/issues/3325
