### ISSUE TITLE
pfSense

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1206]
### Description
pfSense is a free, open source customized distribution of FreeBSD specifically tailored for use as a firewall and router that is entirely managed via web interface. In addition to being a powerful, flexible firewalling and routing platform, it includes a long list of related features and a package system allowing further expandability without adding bloat and potential security vulnerabilities to the base distribution.

Draft PR from @legoguy1000 available here: https://github.com/elastic/integrations/pull/1286

### Architecture
Syslog (both RFC3164 and RFC5424) is supported - relevant documentation [here](https://docs.netgate.com/pfsense/en/latest/monitoring/logs/remote.html). 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by legoguy1000** [comment]
@jamiehynds What kind of logs is this integration intended to parse? just the firewall events or everything as PFsense can send practically all its logs to syslog including its Suricata logs (if you have it).

**Comment by jamiehynds** [comment]
Good question @legoguy1000. Firewall events are certainly the priority, OpenVPN may be worth capturing also. Will check to see if our existing Suricata module will suffice for Surricata logs via pfsense.

**Comment by legoguy1000** [comment]
The only issue I had with sending the suricate logs via syslog is that the json was so long, syslog was cutting it off so I just started sending it to Kafka instead and ingesting it separately. I have an ingest pipeline for my pfsense firewall for the firewall logs, wouldn't be hard to update it for other types.

**Comment by a3ilson** [comment]
> The only issue I had with sending the suricate logs via syslog is that the json was so long, syslog was cutting it off so I just started sending it to Kafka instead and ingesting it separately. I have an ingest pipeline for my pfsense firewall for the firewall logs, wouldn't be hard to update it for other types.

@pfelk had the same issue which is a result of the rfc’s being enforced (specified message length). This was overcome by installing syslog-ng which shows for larger messages lengths (won’t truncate suricata messages).

**Comment by vpiserchia** [comment]
> @pfelk had the same issue which is a result of the rfc’s being enforced (specified message length). This was overcome by installing syslog-ng which shows for larger messages lengths (won’t truncate suricata messages).
This is known and addressed here:

https://github.com/pfelk/pfelk/issues/111
