### ISSUE TITLE
Azure Spring Cloud Observability with Elastic

### ISSUE THREAD

**Issue by hemantmalik** [elastic/integrations#1285]
### **Description**
Azure Spring Cloud service is a managed, cloud-based service for Spring Boot developers. It's a service built and operated in partnership between Microsoft and VMWare. It is a cornerstone service in Java on Azure story. In efforts to continuously improve Elastic Observability turn-key experience for Azure Services - there is mutual interest in developing and promoting this integration.

### Observability
**Logs**
Azure Spring Cloud provides

1. AppConsoleLogs - These are the logs from customer applications. While these could vary and hard to anticipate format - there is a possibility for the generically applicable value for all applications that can be provided OOTB. Below is an example (Kusto Query) from Azure Spring Cloud in what would be meaningful for logs from any Azure Spring Cloud Application 
```
// Show the error and exception number of each application 
// Show a pie chart of the number of the logs containing the "error" or "exception" terms in the last 24 hours, per application. 
// To create an alert for this query, click '+ New alert rule'
AppPlatformLogsforSpring 
| where TimeGenerated > ago(24h)
| where Log contains "error" or Log contains "exception"
| extend FullAppName = strcat(ServiceName, "/", AppName)
| summarize count_per_app = count() by FullAppName, ServiceName, AppName, _ResourceId
| sort by count_per_app desc 
| render piechart
```
sample ApplicationConsole log 
`{ "time": "2021-07-01T19:30:30.535404056Z", "LogFormat": "RAW", "resourceId": "/SUBSCRIPTIONS/EDD63B67-0BA2-4837-A4EB-CD484E9FF623/RESOURCEGROUPS/SA-HEMANT/PROVIDERS/MICROSOFT.APPPLATFORM/SPRING/HM-SC-PETCLINIC", "operationName": "Microsoft.AppPlatform/Spring/logs", "category": "ApplicationConsole", "level": "Informational", "location": "westus2", "properties": {"Log":"2021-07-01 19:30:30.535 INFO 1 --- [oundedElastic-9] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=admin-server, profiles=[mysql], label=null, version=638a1af7fc8d331d7eb26a571275e954632717e8, state=null\n","Stream":"stdout","AppName":"admin-server","InstanceName":"admin-server-default-12-8459d44f68-g4b5f","ServiceId":"c41fd000b1a5450eb234039376da26de","ServiceName":"hm-sc-petclinic"}`

2. SystemLogs: Currently, only Spring Cloud Config Server logs in this category. (Need to validate this)

Based on preliminary testing it looks like that we are able to parse this into `azure.platformlogs.properties.Log` field.
sample SystemLog
`Get config server actuator health status UP.`

With Marketplace++/Native Integration the ability to capture these logs into Elastic has become frictionless - however, with the lack of any meaningful parsing of this data - there is no turn-key experience for end-users.
![image](https://user-images.githubusercontent.com/26748353/124179536-d847c180-da67-11eb-881c-01e223e6c2ba.png)

**Metrics**
One way today to capture these will be to leverage the Azure module's support to get custom metrics to fill the gap. It's an important metricset to provide Azure Spring Cloud users the ability to correlate their application issues with the service issues.

**APM**
With the lack of OOTB integration for Elastic APM for Azure Spring Cloud service, currently, the only option available to users is sideloading method. It is error-prone and cumbersome. Better support for Azure Spring Cloud Logs and Metrics helps make the case stronger for Azure Spring Cloud's OOTB support for Elastic APM.

cc: @osmanis @cyrille-leclerc

**Comment by narph** [comment]
https://github.com/elastic/integrations/pull/1355

**Comment by narph** [comment]
Data stream created
