### ISSUE TITLE
Linux package data streams from system metrics settings are not generated properly.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#1296]
**Kibana version:** 7.14 BC1 Kibana Cloud-QA environment

**Host OS and Browser version:** Chrome, Firefox and edge

**Preconditions:**
1. 7.14 BC1 Kibana Cloud-QA environment should be available.

**Build Details:**
```
BUILD 42292
COMMIT 071a74e02f82b79a4a10026b5c9e02d593112fd4
Artifact link: https://staging.elastic.co/7.14.0-8eba2f5f/downloads/beats/elastic-agent/elastic-agent-7.14.0-linux-x86_64.tar.gz
```
2. **Add Linux integration with default settings to any policy**.

**Steps to reproduce:**
	- Login to Kibana.
	- Install a Linux Agent using above policy.
	- After for few minutes, till agent starts streaming data on Data Stream tab.
	- Apply filter for linux integration.
	- Observe, Only two metrics datasets stream data out of three default metrics.

**Expected result:**
- No data event for linux.network_summary is displayed for Linux centos and Ubuntu machines.

**NOTE: Issue reproducible on 7.14 Snapshot too. Build details:**
```
BUILD 42333
COMMIT d2904ca073e91582a2c5fa6ef6e712491cf3521f
artifact link used: https://snapshots.elastic.co/7.14.0-204f3365/downloads/beats/elastic-agent/elastic-agent-7.14.0-SNAPSHOT-linux-x86_64.tar.gz
```
**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/124741314-2f063d00-df39-11eb-84ff-e35426cf8fa1.png)

**Observation on Ubuntu:**
![image](https://user-images.githubusercontent.com/72375798/124741563-74c30580-df39-11eb-8946-6d61b2599e6a.png)

**Comment by fearful-symmetry** [comment]
@dikshachauhan-qasource can you get me logs from the agent on the host? Also, can you give me the exact releases of ubuntu and centos you're using here?

**Comment by dikshachauhan-qasource** [comment]
Hi @fearful-symmetry 

Please find the required details below:

- Ubuntu Version:

```
zeus@mainqa-atlcolo-10-0-6-236:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
```

- Centos Version:
```
[zeus@mainqa-atlcolo-10-0-7-186 ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
```

Further logs from host are:
- [centos10-0-7-186.log](https://github.com/elastic/integrations/files/6783080/centos10-0-7-186.log)
- [Ubuntu16.log](https://github.com/elastic/integrations/files/6783076/Ubuntu16.log)

Further, we have reattempted to on latest 7.14 bc1 build on cloud-qa env and found same observations.

Build details:
```
BUILD 42367
COMMIT d417b7aaba7d337fd45da08ed75dcc2c7fdf56cb

```

machine details:
```
[zeus@mainqa-atlcolo-10-0-6-189 elastic-agent-7.14.0-linux-x86_64]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"

```

logs: 
[centos10-0-6-189.log](https://github.com/elastic/integrations/files/6783225/centos10-0-6-189.log)


Please let us know if anything is required.

Thanks
QAS

**Comment by fearful-symmetry** [comment]
Okay, I can't seem to reproduce this. Also, these look like the wrong logs. Metricbeat writes to its own logs, which will be in a subdirectory, usually called `data` or something, under the directory where the agent logs are.

**Comment by amolnater-qasource** [comment]
Hi @fearful-symmetry 
We are able to reproduce this issue on 7.14.0 Snapshot Kibana cloud-qa environment.

OS: Ubuntu 20

**Build details:**
```
Build: 42405
Commit: d449412c8ca14a87a10527ffdc3967d42c12f34a
Artifact Link: https://snapshots.elastic.co/7.14.0-9d60d2cb/downloads/beats/elastic-agent/elastic-agent-7.14.0-SNAPSHOT-linux-x86_64.tar.gz
```

**Logs:**
[logs.zip](https://github.com/elastic/integrations/files/6791081/logs.zip)

Thanks
QAS

**Comment by fearful-symmetry** [comment]
Alright, found the issue. Helps if I actually test the right version. Fix incoming.

**Comment by fearful-symmetry** [comment]
Okay, nevermind, I actually don't get this. @andrewkroh you might be able to understand this. This is the error QA is seeing:
```
(status=400): {\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse field [event.module] of type [constant_keyword] in document with id 'ozsWi3oBSbvOjVRwjE8V'. Preview of field's value: 'system'\",\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"[constant_keyword] field [event.module] only accepts values that are equal to the value defined in the mappings [linux], but got [system]\"}}","service.name":"metricbeat","event.dataset":"metricbeat-json.log",
```

However, this is the config in the agent:
```
- name: event.module
  type: constant_keyword
  description: Event module
  value: linux
```

I'm honestly not sure what's going on here, and I still can't seem to reproduce it.

**Comment by fearful-symmetry** [comment]
Okay, so, I'm testing this on 7.14 snapshot, and it seems to be behaving in a way that's different. Instead, the event is being ingested, but `event.module` is set to `system`, apparently overriding the config I posted above.

**Comment by andrewkroh** [comment]
It sounds like Metricbeat is setting `event.module: system` and that conflicts with the `value: linux` in the mapping. If that's true then I'd recommend adding a simple ingest node pipeline to the data stream to drop `event.module` from the document before it gets indexed.

**Comment by fearful-symmetry** [comment]
> It sounds like Metricbeat is setting event.module: system and that conflicts with the value: linux in the mapping. If that's true then I'd recommend adding a simple ingest node pipeline to the data stream to drop event.module from the document before it gets indexed.

Yep, finally managed to (properly) reproduce that and figure it out.

**Comment by fearful-symmetry** [comment]
Alright, so, it works with a processor. Will need to fix this in a few places, as it's ultimately an issue with how metricbeat is organized on the backend, which is something I'm working to fix.

**Comment by fearful-symmetry** [comment]
Alright, there we go. Fix here: https://github.com/elastic/integrations/pull/1317

**Comment by dikshachauhan-qasource** [comment]
Hi @fearful-symmetry 

Thanks for taking some time to review and fixing this out. As merges are not available now, so we will retest it once build is available.

Thanks
QAS

**Comment by EricDavisX** [comment]
it is in linux 0.4.1 version.  it will need to go through the promotion cycles, etc.  and we are possibly seeing quirks with the initial add of Integrations to snapshot from Integration repo.

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource please use latest 7.14 snapshot code on cloud-staging to test this out, the fix should be visible in the new package there.  Thanks.

**Comment by fearful-symmetry** [comment]
Oh, my bad! Once again forgot to do the promotion. PR here: https://github.com/elastic/package-storage/pull/1607

**Comment by EricDavisX** [comment]
I published them, thanks Alex.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

cc @fearful-symmetry we have validated it on latest 7.14 snapshot build on cloud-staging and found it fixed now.

Build details:

```
BUILD 42541
COMMIT 325493c86b4f58c308a3eb1f8bcfe5994a54533a
``` 

- Now all the metrics for linux integration are getting generated on data streams tab.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/125743522-80dc5949-cbaa-48bb-b076-dd0a1144ef00.png)

Hence, we closing this out.

Thanks
QAS
