### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1305]
### Description
At the core, Cloudflare is a Content Delivery Network (CDN) composed of hundreds of data centers located in more than 100 countries. Cloudflare has grown to handle five to ten percent of the global internet traffic, making Cloudflare one of the largest CDNs in the world.

Since all traffic to your website first passes through the Cloudflare network, malicious traffic such as DDoS attacks, comment spam, or content scraping can be detected and filtered or rerouted without ever reaching your server in the first place.

Malicious agents are detected using a variety of identifiers, including previous known malicious IP addresses, the type of requests made, any malicious payloads that may be included in the request, or even the timing and frequency of their connections. This is weighed against the security level you’ve set up on your site to determine whether a visitor is let through, if additional verification on the visitor’s browser is required, or if the visit is blocked entirely.

### Architecture
Cloudflare has both a 'Log Pull' and 'Log Push' option for SIEM integration. Log pull exposes a REST API, documentation available [here](https://developers.cloudflare.com/logs/logpull/). Log push can push events directly to a SIEM, and is the newer of the two options - documentation [here](https://developers.cloudflare.com/logs/about). Log pull is the priority, but we should aim to support both Push and Pull architectures to provide flexibility to users. 

Worth noting there is a Cloudflare integration [available on Github](https://github.com/cloudflare/cloudflare-elastic) but hasn't been maintained and has known issues. This new integration will be the preferred way to integration Cloudflare + Elastic. 

We have a Cloudflare instance available for testing. @legoguy1000 has a draft PR here: https://github.com/elastic/integrations/pull/984

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [x] Supported versions of the monitoring target are documented
- [x] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to: 7.15

### New Package

- [x] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [x] Dashboards exists
- [x] Screenshots added or updated
- [x] Datastream filters added to visualizations

### Log dataset changes

- [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [x] Generated output for at least 1 log file exists
- [x] Sample event (`sample_event.json`) exists

**Comment by legoguy1000** [comment]
@jamiehynds now that u guys have the cloudflare instance, can u send me a variety of sample logs of the 3 different types; firewall, http, spectrum??

**Comment by P1llus** [comment]
@legoguy1000 I will send you some samples outside of github, no worries! :)
