### ISSUE TITLE
[Kubernetes] Tune package's data_streams to leverage leaderelection by default

### ISSUE THREAD

**Issue by ChrsMark** [elastic/integrations#1311]
Currently the package does not leverage the leaderelection functionality. This means that in a mutlinode k8s cluster, cluster-wide data_streams like state_* should be applied on all of the Daemonset Agent Pods. We can tackle this by adding an extra setting `leaderelection: true` to the data_streams so as to indicate that that these specific data_streams should be enabled only when leadership lock is obtained. To achieve this we also need to enable the leaderelection provider by default for Agents we deploy on k8s.

@MichaelKatsoulis let me know what you think.

**Comment by MichaelKatsoulis** [comment]
Sounds good. I can take that one over!
