### ISSUE TITLE
[Fleet]: Custom logs integration accepts invalid path in Log file path field.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#1315]
**Kibana version:** 7.14.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
Build: 42405
Commit: d449412c8ca14a87a10527ffdc3967d42c12f34a
```

**Preconditions:**
1. 7.14.0 Snapshot Kibana cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Integrations tab>Custom Logs integration> Add Custom Logs.
3. Add Log file path as character 'a' or any.
4. Click Save Integration.
5. Observe Integration is added to Default policy with invalid Log file path.

**Expected Result:**
Custom logs integration should at least accept a valid path format in Log file path field.

**Screenshot:**
![7](https://user-images.githubusercontent.com/77374876/125059411-ea111080-e0c8-11eb-9ea1-656d7c53095f.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jen-huang

CC: @EricDavisX

**Comment by jen-huang** [comment]
This is expected behavior. We don't do this level of validation yet. Closing.

**Comment by amolnater-qasource** [comment]
Hi
Thanks for the confirming the expected behaviour @jen-huang.
