### ISSUE TITLE
Prometheus README contains invalid code block language

### ISSUE THREAD

**Issue by jen-huang** [elastic/integrations#1322]
Related to https://github.com/elastic/kibana/pull/105498 and https://github.com/elastic/kibana/issues/101168. Prometheus README file has `$yml` set for some code blocks, which is invalid and causes Kibana to throw an error (there is an ER for better error handling in https://github.com/elastic/eui/issues/4849).

`$yml` should be replaced with `yml`.

**Comment by mtojek** [comment]
I will handle the production release.
