### ISSUE TITLE
[Elastic Agent] "Beta" & "Experimental" tags to be removed before GA

### ISSUE THREAD

**Issue by nimarezainia** [elastic/integrations#1329]
Fleet-Server and Elastic-Agent integrations need to have their tiles updated so the keywords Experimental and beta are removed before their GA in 7.14. The versions also need to be updated to 1.0

![image](https://user-images.githubusercontent.com/13442829/125987089-1e10a9fe-2dae-4b5a-97e4-c31b3e26c965.png)

![image](https://user-images.githubusercontent.com/13442829/125987177-ae2c3911-e40c-427c-86eb-97e5bdf1868e.png)
 

- [ ] Remove "Experimental" from Elastic-Agent integration
- [ ] Update the version to 1.0 for Elastic-Agent integration
- [ ] Remove "Beta" from Fleet-Server integration
- [ ] Update the version to 1.0 for Fleet-Server integration

**Comment by nimarezainia** [comment]
I see that these are simple changes in the manifest file:

![image](https://user-images.githubusercontent.com/13442829/125987877-adda70b5-1404-4872-9e6c-8102aa1b0d99.png)



![image](https://user-images.githubusercontent.com/13442829/125987931-ceefc818-f4c3-4c62-aaeb-5168ea9471ae.png)

**Comment by ruflin** [comment]
++ on this change. @nimarezainia want to open 2 PR's for it directly?

I started some of this change in https://github.com/elastic/integrations/pull/1298 but we should not block on this PR, I will just rebase.
