### ISSUE TITLE
[Metricbeat]: No Data for linux tar package is displayed on [Metricbeat System] Containers overview ECS dashboard after metricbeat installation.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#1339]
**Kibana version:** 7.14 BC3 Kibana Cloud-staging environment![image](https://user-images.githubusercontent.com/72375798/126317451-571bf181-2da6-44f8-b208-597d785dbd0c.png)
**Host OS and Browser version:** Chrome, Firefox and edge

**Preconditions:**
1. 7.14 BC3 Kibana Cloud-staging environment should be available.

**Build Details:**
```
Build: 42545
Commit c314921a9893e0b46d9a3958f5520e3d6b1ce7d5

```
- metricbeat is installed using linux tar package.

Artifact link: https://staging.elastic.co/7.14.0-682a8012/downloads/beats/metricbeat/metricbeat-7.14.0-linux-x86_64.tar.gz

**Steps to reproduce:**
	- Login to Kibana.
	- Navigate to Discover tab.
	- Click on metricbeat-*.
	- Observe, metricbeat logs are displayed.
	- Navigate, Dashboard tab> select [Metricbeat System] Containers overview ECS.
	- Observe, no data is displayed.

**Reference testcase:**	
https://elastic.testrail.io/index.php?/tests/view/586357

**Actual Result:**
No Data for linux tar is displayed on [Metricbeat System] Containers overview ECS dashboard.

**Expected Result:**
Data for linux tar should be displayed on [Metricbeat System] Containers overview ECS dashboard.

**What's working:**
Data for linux tar is displayed on 
- [Metricbeat System] Host overview ECS dashboard.
- [Metricbeat System] overview ECS dashboard.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/126317396-9bc5b806-7c49-4b96-989c-9cf7b1cc706d.png)

**Discover tab:**
![image](https://user-images.githubusercontent.com/72375798/126317451-571bf181-2da6-44f8-b208-597d785dbd0c.png)

**[Metricbeat System] Host overview ECS dashboard:**
![image](https://user-images.githubusercontent.com/72375798/126317741-59c1a987-f82d-4b2d-82ba-4b730c12d385.png)

**[Metricbeat System] overview ECS dashboard:**
![image](https://user-images.githubusercontent.com/72375798/126317917-d25479a6-6a4f-4d62-81b9-78e21851a198.png)

**Comment by jen-huang** [comment]
What @fearful-symmetry said.

Also, not sure why this was filed in the Kibana repo as this doesn't even touch the Fleet & managed agents workflow.

**Comment by dikshachauhan-qasource** [comment]
hi @fearful-symmetry 

The host on which we have installed metricbea, is also running 7.14 agent along side with system integration in agent policy. 

thus, we can confirm we are ingesting events from the system/process metricset for this host. Please correct us if something else is addressed here.

@jen-huang we reported it in kibana because metricbeat is running fine at all place, issue here is just data being not visible on above mentioned dashboard. If you consider it better to be moved under beats we can update that.

Please let us know if anything else is required.

**Comment by EricDavisX** [comment]
I see the confusion now, Alex's post made me re-read it better.  This wans't actually tested with 'containers' just regular host vms.  I'll close as WAD and user-error unless someone can surprise me that we had some Docker usage in play?

And we do try to get issues to the right repo, it is harder sometimes and is an error prone process- thanks for the note so we can do better.

**Comment by dikshachauhan-qasource** [comment]
hi @fearful-symmetry cc @EricDavisX 

Thanks for the feedback on reported issue. We will update our testcases accordingly.

Thanks
QAS
