### ISSUE TITLE
Revisit AWS categories 

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#1342]
AWS package at the [package level](https://github.com/elastic/integrations/blob/master/packages/aws/manifest.yml#L8) has 4 category tags: aws, cloud, network, and security. Inside the AWS package, there are multiple policy templates and each policy template can also have its own category tags. For example: [DynamoDB](https://github.com/elastic/integrations/blob/master/packages/aws/manifest.yml#L142) has a database category tag. With how `package-registry` works, the individual policy template also inherits category tags from the package level. Therefore for all policy templates in the AWS package, they are all by default in aws, cloud, network, and security categories. 

My proposal is to only keep `aws` and `cloud` for the AWS package level categories and then add the `security` category tag to the policy template level category instead.

**Comment by kaiyan-sheng** [comment]
@exekias @andrewkroh WDYT?

**Comment by andrewkroh** [comment]
SGTM

**Comment by exekias** [comment]
:+1: thanks for taking this!
