### ISSUE TITLE
Adjust categories of packages

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#135]
In https://github.com/elastic/package-registry/pull/534 the supported categories were adjusted in the registry and support for metrics / logs will be removed. For this, packages in package-storage were updated: https://github.com/elastic/package-storage/pull/97

All new packages now must be adjusted to have the new categories in before released.

**Comment by ruflin** [comment]
@mostlyjason Please provide which packages need which categories.

**Comment by mostlyjason** [comment]
I would encourage the authors of each package to review and select appropriate categories for their package. We have a list of categories that we use on elastic.co/integrations https://docs.google.com/spreadsheets/d/1_WZG4StHdg6abERjZImXx1JaZfdiHJBtadN6tvcrO9Y/edit#gid=0. However, this was a quick first pass to get it launched and was primarily filled by marketing and PM. I think the package creators will have better technical and subject matter expertise, and will do a better job selecting the categories. Our goal is to use the package registry as the source of truth for the website in the future.

**Comment by ycombinator** [comment]
Right now it's not possible to spin up the [integrations testing environment](https://github.com/elastic/integrations/tree/master/testing/environments) locally by running `cd testing/environments && docker-compose -f snapshot.yml up --force-recreate`. The following error is thrown:

```
package-registry_1  | 2020/07/01 22:27:46 reading packages from filesystem failed: loading package failed (path: /registry/packages/integrations/apache/0.1.0): invalid category: logs accessing config
```

Until this issue here is resolved, should we remove `categories` from existing packages under https://github.com/elastic/integrations/tree/master/packages?

**Comment by ycombinator** [comment]
> Until this issue here is resolved, should we remove categories from existing packages under https://github.com/elastic/integrations/tree/master/packages?

If this sounds good to you, I've created https://github.com/elastic/integrations/pull/144 to do it.

**Comment by mtojek** [comment]
Fixed with https://github.com/elastic/integrations/pull/147

Resolving
