### ISSUE TITLE
[Integration] Flickering 'Edit Integration' on Clicking edit integration of any integration under action menu of Policy page.

### ISSUE THREAD

**Issue by vipulsrivastava-qasource** [elastic/integrations#1351]
**Kibana version:** 7.14 BC-4 Kibana cloud environment

**Host OS and Browser version:** All, All

**Preconditions:**

1. 7.14.0 BC-4 Kibana cloud environment should be available.
2. Default policy or newly created policy having integrations(let say : system, Kafka and RabbitMQ) should exist.

```
Build Details:
Build: 42656
Commit: 82a4f6a7fa23946667599787cdb1b2d82c1d0dfb

```
**Steps to reproduce:**

1. Login to Kibana.
2. Navigate to Fleet-> Agent policies tab.
3. Click on Default policy or newly created policy.
4. Click `...` under actions column of any integration present.
5. Click on 'Edit Integration' icon.
6. Observe flickering "Edit integration" and then 'Edit < integration name > integration' is visible.

**Actual Result**
Flickering 'Edit Integration' on Clicking edit integration of any integration under action menu of Policy page.

**Expected Result**
After clicking edit integration of any integration under action menu of Policy page 'Edit < integration name > integration' should displayed and no Flickering 'Edit Integration' should displayed.

**Screen Recording**

https://user-images.githubusercontent.com/69579402/126952075-b63b21cf-9d32-4f0e-8e4b-e4c5f6af21db.mp4

**Comment by vipulsrivastava-qasource** [comment]
@manishgupta-qasource : Please review the Bug.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jen-huang 

CC: @EricDavisX

**Comment by jen-huang** [comment]
This is fine as it's just the loading state. Closing.
