### ISSUE TITLE
[Integrations]: Cross icons are not colored as red under 'Elastic APM' overview page.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#1352]
**Kibana version:** 7.14 BC4 Kibana Cloud-staging environment

**Host OS and Browser version:** Chrome, Firefox and edge

**Preconditions:**
1. 7.14 BC4 Kibana Cloud-staging environment should be available.

**Build Details:**
```
BUILD 42656
COMMIT 82a4f6a7fa23946667599787cdb1b2d82c1d0dfb
artifact link : https://staging.elastic.co/7.14.0-b3779639/summary-7.14.0.html

```

**Steps to reproduce:**
	- Login to Kibana.
	- Navigate to Integrations tab.
	- Select 'Elastic APM' and navigate to integration overview page.
	- Scroll down and Observe, cross icons are not colored as red.
	

**Expected result:**
- Cross icons should be colored in Red as right ticks are colored in green.

**Screenshot:** 
![image](https://user-images.githubusercontent.com/72375798/126962079-3abd6758-e4f0-4976-9995-ea4c38d11b96.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jen-huang 

CC: @EricDavisX

**Comment by jen-huang** [comment]
This is expected behavior as this is exactly what is defined in the APM package: https://github.com/elastic/apm-server/tree/master/apmpackage/apm/docs
