### ISSUE TITLE
Exported fields with wildcards not rendered correctly

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#1366]
I just noticed that Fleet doesn't render fields correctly with wildcard (`*`):

<img width="881" alt="Zrzut ekranu 2021-07-28 o 10 24 06" src="https://user-images.githubusercontent.com/14044910/127289725-5bd7d1ef-8ee5-4ba2-881f-be20586401b1.png">

Behind the scenes it's:

```
**Exported fields**

| Field | Description | Type |
|---|---|---|
| @timestamp | Event timestamp. | date |
| aws.*.metrics.*.* | Metrics that returned from Cloudwatch API query. | object |
| aws.billing.AmortizedCost.amount | Amortized cost amount. | double |
| aws.billing.AmortizedCost.unit | Amortized cost unit. | keyword |
```

It seems it's in *italics* accidentally :)

**Comment by mtojek** [comment]
I will adjust elastic-package to escape `*`.

**Comment by mtojek** [comment]
@bmorelli25 discovered more fields in https://github.com/elastic/integrations/pull/1401#issue-699890603

> Eventually, it'd be awesome if we could add rules to automatically escape <, >, {, and } -- similar to what I see being done in elastic/elastic-package#451.

**Comment by bmorelli25** [comment]
Thanks, @mtojek 

It's worth noting that this appears to be impacting not just the new docs system, but also the current md readme files. At least in GitHub, the markdown rendering for anything inside unescaped <> silently fails. As an example, take a look at this line in the redis readme:

https://github.com/elastic/integrations/blame/a171a03e5d9c03ea2d9cb9866d21623a0f1bae5e/packages/redis/docs/README.md#L558

```
| redis.key.id | Unique id for this key (With the form <keyspace>:<name>). | keyword |
```

Renders as:
<img width="931" alt="Screen Shot 2021-07-30 at 10 43 27 AM" src="https://user-images.githubusercontent.com/5618806/127691802-14e54b79-fdce-4f77-a3a5-80badede1358.png">

Note that the above example has already been fixed.

**Comment by mtojek** [comment]
I looked at redis [README.md](https://github.com/elastic/integrations/tree/master/packages/redis). It seems that it renders `redis.key.id` correctly, but there is a fix needed for field descriptions (escaped < >).

**Comment by bmorelli25** [comment]
I think this is fixed—at least on the docs side
