### ISSUE TITLE
Broken documentation syntax in mdx

### ISSUE THREAD

**Issue by bmorelli25** [elastic/integrations#1400]
Our new documentation system doesn't support the following characters unless they're smushed inside backticks: `<`, `>`, `{`, and `}`.

The following packages have documentation that uses these characters:

- [x] **cef**
https://github.com/elastic/integrations/blame/master/packages/cef/docs/README.md#L60
- [x] **Docker**
https://github.com/elastic/integrations/blame/master/packages/docker/docs/README.md#L28
- [x] **Kubernetes**
https://github.com/elastic/integrations/blob/master/packages/kubernetes/data_stream/state_job/fields/fields.yml#L65
- [x] **network_traffic**
https://github.com/elastic/integrations/blame/master/packages/network_traffic/docs/README.md#L940
- [x] **Postgresql**
https://github.com/elastic/integrations/blame/master/packages/postgresql/docs/README.md#L9
- [x] **Rabbitmq**
https://github.com/elastic/integrations/blame/master/packages/rabbitmq/docs/README.md#L637
- [x] **Redis**
https://github.com/elastic/integrations/blame/master/packages/redis/docs/README.md#L11
https://github.com/elastic/integrations/blame/master/packages/redis/docs/README.md#L558
- [x] **Zeek**
https://github.com/elastic/integrations/blame/master/packages/zeek/docs/README.md#L13

cc @goodroot @glitteringkatie

**Comment by goodroot** [comment]
```
/integrations/cef | "md5 is not defined"
/integrations/docker | ??
/integrations/kubernetes/kube-state-metrics | "Cannot close `tableData`"
/integrations/network_traffic | ??
/integrations/postgresql | "Cannot close `tableData`"
/integrations/rabbitmq | "syncing is not defined"
/integrations/redis | "Cannot close `tableData`"
/integrations/zeek | ??
```

* `is not defined` == likely something inbetween curly braces `{helpme}`
*  `Cannot close `tableDate`` == something in table, like `<thing>`
* `??` == Perhaps asciidoc syntax, like `<<thing>>`, or perhaps `<number` or `number>`
