### ISSUE TITLE
AWS RDS Logs

### ISSUE THREAD

**Issue by franktatjana** [elastic/integrations#1436]
A user wants to collect AWS RDS logs with Filebeat. Currently, only metrics is collected with https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-aws-rds.html.  If a user can deploy Filebeat into AWS to collect RDS logs (postgres module https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-postgresql.html), that might work. But if a user wants to use AWS module in Filebeat to collect Postgres logs from CloudWatch, then that’s not supported yet.

**Comment by ravikesarwani** [comment]
This should be available by using the Filebeat aws-cloudwatch input.
Also we have "Custom AWS log" integration for Elastic agent to handle log collection where we don't have a specific OOTB integration yet.
