### ISSUE TITLE
Add system tests to MongoDB

### ISSUE THREAD

**Issue by masci** [elastic/integrations#1440]
Integration package is missing system tests.

**Comment by rameshelastic** [comment]
@ManojS-shetty is this good to be closed?

**Comment by ManojS-shetty** [comment]
> @ManojS-shetty is this good to be closed?

No Ramesh. There are few other issues related to mongodb integration [SDH issue](https://github.com/elastic/sdh-beats/issues/2550) needs to be addressed before merging the system test.
