### ISSUE TITLE
Screenshot shows [object Object] of [object Object]

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#1442]
When testing elastic stack with `7.15.0-SNAPSHOT`, I see in the documentation page, next to the screenshots, there is `[object Object] of [object Object]` instead of the page number. 

<img width="1232" alt="Screen Shot 2021-08-03 at 3 58 25 PM" src="https://user-images.githubusercontent.com/14081635/128093129-1c214f7a-af08-47a3-9c6c-2c0a77f8beca.png">

This seems to also happen in other integrations.

**Comment by kaiyan-sheng** [comment]
@jen-huang Is this a regression?

**Comment by jen-huang** [comment]
I believe this was a bad EUI change, it should be fixed now.
