### ISSUE TITLE
[Meta] Salesforce Observability Integration

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#1450]
This issue describes the requirements for automatically collecting salesforce logs, parsing events, and indexing them in Elastic Cloud for observability. The goal of this work is to provide the user a simple and straightforward way to monitor Salesforce org performance and adoption through the user's account with Elastic.

**Platform Events**
Salesforce provides [event monitoring](https://trailhead.salesforce.com/content/learn/modules/event_monitoring) to collect, analyze, and manage the usage of the Salesforce applications. When any action is executed, an event is recorded and added to the event log. It gives Salesforce customers insights into how their users interact with Salesforce via different [platform event types](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_eventlogfile_supportedeventtypes.htm) collected. Users can access these events as an event log file through the [Lightning Platform REST APIs](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_what_is_rest_api.htm). These event log files are only made available [daily or hourly](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/event_log_file_hourly_diff.htm) and retained for 30 days.

**Real-Time Events**
A subset of events, named [real-time events](https://help.salesforce.com/articleView?id=real_time_event_monitoring_overview.htm&type=5), are available for event monitoring in real-time through [Streaming APIs](https://developer.salesforce.com/docs/atlas.en-us.232.0.api_streaming.meta/api_streaming/intro_stream.htm). This functionality stream some of the events (that would usually be logged) as platform events. That means users can consume these events in the same way as platform events via an external subscriber. [Not all real-time events](https://help.salesforce.com/articleView?id=real_time_event_monitoring_streaming.htm&type=5) can be subscribed to via triggers or declarative tools.

![image](https://user-images.githubusercontent.com/14043218/130114312-c0fd657e-40fb-4a32-a099-5acb183c2e15.png)

### Salesforce-Elastic Integration
Salesforce is much more than just a popular CRM platform. It’s an ecosystem capable of leveraging thousands of integrations alongside its library of services. Salesforce customers can build precisely what they need when they need it. To enhance their operational efficiency and customer experience, Businesses may need
- **Visibility into user journeys:** Understanding why something went wrong and what went wrong with user workflows.
- **Coherent UX:** Salesforce integrates with almost every service that businesses could use which takes care of consistency but not workflow confusion or buried resources. Uncovering such insights could lead to impressive UX.
- **Mitigation of cost of failures:** Components that fail can rapidly disrupt operations, leading to thousands of dollars lost per minute. Identifying failures before they happen may save a lot of costs.

This is where Elastic Observability could help. This integration will enable customers to have one source of truth for Salesforce event monitoring through the relevant data. Elastic O11y dashboards and visualizations will help users in gleaning insights to act upon. Alerting will help them in noticing deteriorating platform health and workflow conditions that should never realize.

### Integration Arch

![image](https://user-images.githubusercontent.com/14043218/130490846-2f6dade5-9f94-4080-95f2-7bb8dcd5996a.png)

- https://github.com/elastic/integrations/issues/3939
- https://github.com/elastic/integrations/issues/3940

[Product brief](https://docs.google.com/document/d/1o5cmSM-o3Nzjvmxr0KsQXcad09nl665WGoYffCYPrhM/edit?usp=sharing)

cc: @pmeresanu85 @rameshelastic

**Comment by akshay-saraswat** [comment]
[Notes from Aug 16 call with PepsiCo team.](https://docs.google.com/document/d/1fK4GKFUcaaXoycVswp0JxDWTSk9bs01Yn9WajIG0fb8/edit?usp=sharing)

**Comment by sorantis** [comment]
@akshay-saraswat we try not to attach private docs to public issues. Can you link it to the ER instead?
