### ISSUE TITLE
Rename directories to not contain - in packages

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#150]
To unify the naming of all directories and configs, only `_` are used moving forward. This means the `ingest-pipeline` directories must be renamed to `ingest_pipeline`. In the package storage this was already done by duplicating the directories: https://github.com/elastic/package-storage/pull/108 Adjustments to Kibana are here: https://github.com/elastic/kibana/pull/70320

I wanted now to adjust it in integrations repository. Copying the directories / renaming is easy, here is a leftover script: https://github.com/elastic/package-storage/blob/master/packages/main.go But it was unclear to me where it happens in the generation code. It seems it already takes the name from the Beat as I couldn't find `ingest-pipeline` directory creation in the code.

**Comment by mtojek** [comment]
> But it was unclear to me where it happens in the generation code. It seems it already takes the name from the Beat as I couldn't find `ingest-pipeline` directory creation in the code.

https://github.com/elastic/integrations/blob/master/dev/import-beats/packages.go#L328

**Comment by ruflin** [comment]
@mtojek Glad you pointed me to this. Seems like this one went missing during the renaming. Lets get in https://github.com/elastic/package-registry/pull/581 first then.

**Comment by ruflin** [comment]
I filed https://github.com/elastic/integrations/pull/153 as draft so we can continue the work as soon as the registry is changed.

**Comment by mtojek** [comment]
@ruflin can we close this issue?

**Comment by ruflin** [comment]
@mtojek Yes.

@ycombinator Could we make sure this is "enforced" also in the package spec somehow for all directories?

**Comment by ycombinator** [comment]
I just checked the 1.0 spec and this is already enforced:

- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/spec.yml#L23-L24
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/spec.yml#L28-L29
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/spec.yml#L32-L33
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/dataset/spec.yml#L5-L6
- https://github.com/elastic/package-spec/blob/master/versions/1/dataset/spec.yml#L17-L18
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/dataset/spec.yml#L22-L23
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/dataset/spec.yml#L28-L29
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/dataset/spec.yml#L33-L34
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/dataset/spec.yml#L38-L39
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/dataset/spec.yml#L62-L63
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/dataset/spec.yml#L66-L67
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/kibana/spec.yml#L5-L6
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/kibana/spec.yml#L14-L15
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/kibana/spec.yml#L23-L24
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/kibana/spec.yml#L32-L33
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/kibana/spec.yml#L41-L42
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/dataset/_dev/spec.yml#L5-L6
- https://github.com/elastic/package-spec/blob/f45b05c887b5d62dea8f5c21577520a0e113716c/versions/1/dataset/_dev/test/spec.yml#L5-L6

**Comment by ruflin** [comment]
@ycombinator As usual, you are a step ahead 🎉
