### ISSUE TITLE
System Integration - Incorrect dashboard IDs (URLs) for navigation visualizations

### ISSUE THREAD

**Issue by FauxPrada** [elastic/integrations#1524]
Hello,

See [this discussion](https://discuss.elastic.co/t/system-integration-navigation-visuals-use-all-the-wrong-urls-ids/281180) on forum for more detail.

The "Dashboard links" visualisations provided by System Integration use incorrect URLs and thus return with `Could not locate that dashboard (id: windows-035846a0-a249-11e9-a422-d144027429da)` for example.

I believe these should actually be `system-123456-...` and not `windows-123456-...`, but the following IDs are still incorrect anyway.

These where added fresh using a full 7.14.0 setup.

Visualizations affected:
* Dashboard links [Windows System Security]
* Dashboard links - Simple [Windows System Security]

ty

**Comment by fearful-symmetry** [comment]
Fix incoming.
