### ISSUE TITLE
Investigate switching to `filestream` input for container logs

### ISSUE THREAD

**Issue by exekias** [elastic/integrations#1526]
[Filestream](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-filestream.html) input is now GA, and it brings [many improvements](https://www.elastic.co/blog/read-active-log-files-more-quickly-and-easily-with-the-new-filestream-input-in-filebeat?ultron). One of the things we expect this will fix is the issue with [forever growing registry files](https://github.com/elastic/beats/issues/13140).

We should investigate taking advantage of this input to also collect container logs. The obvious missing pieces would be around parsing the docker json and CRI formats, we may need to add new parsers to the input to support these.

**Comment by exekias** [comment]
@kvch I was having a look to the [docs](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-filestream.html) and I see parsers mentioned but the topic is no further developed. Are there any plans to expose them?

**Comment by kvch** [comment]
They are exposed, but for some reason I have forgotten about the documentation? I will add it to filestream docs. Thanks for noticing it. :facepalm:
