### ISSUE TITLE
Azure Spring Cloud integration tweaks

### ISSUE THREAD

**Issue by osmanis** [elastic/integrations#1532]
Some feedback for the new [Azure Spring Cloud logs integration](https://github.com/elastic/integrations/tree/master/packages/azure/data_stream/springcloudlogs).
- Update the logo to match the official logo: [Azure spring cloud_icon.svg.zip](https://github.com/elastic/integrations/files/6993498/Azure.spring.cloud_icon.svg.zip)
- In the [integration description](https://github.com/elastic/integrations/blob/fe65d143379467c73c8ed38945eacffa446eefee/packages/azure/_dev/build/docs/springcloudlogs.md), it would be very helpful to guide native integration users as well since the flow is very different, but easier, for them to ingest Azure Spring Cloud logs. For example the requirements are different as they don't need to set up Event Hub manually.

@sorantis @narph @hemantmalik

**Comment by sorantis** [comment]
We'll update the logo. For the second point we'll only link to the [existing documentation](https://www.elastic.co/guide/en/observability/current/monitor-azure.html) that describes the steps. I'd rather we avoid adding more elaborate description to the package documentation.

**Comment by osmanis** [comment]
@sorantis Sounds good to me.

**Comment by osmanis** [comment]
Also noted that `cloud` is not capitalized on the Spring Cloud tile on the integrations page. It should be capitalized as it's part of the full product name: `Azure Spring Cloud`.
![image](https://user-images.githubusercontent.com/43759819/129948208-9f526e6c-d76a-4975-b8ee-1bd7df3e7536.png)

**Comment by narph** [comment]
> Also noted that `cloud` is not capitalized on the Spring Cloud tile on the integrations page. It should be capitalized as it's part of the full product name: `Azure Spring Cloud`.
> ![image](https://user-images.githubusercontent.com/43759819/129948208-9f526e6c-d76a-4975-b8ee-1bd7df3e7536.png)

took care of it in the PR linked
