### ISSUE TITLE
Move text fields to match_only_text

### ISSUE THREAD

**Issue by jpountz** [elastic/integrations#1551]
ECS has been updated to map a number of `text` fields as `match_only_text` instead: https://github.com/elastic/ecs/blob/master/rfcs/text/0023-match_only_text-data-type.md.

Elasticsearch's built-in templates have already been updated to use `match_only_text` on message fields, let's also migrate mappings that are managed by our integrations now?

cc @ruflin

**Comment by ruflin** [comment]
@exekias @masci I suggest in a first step we focus on converting `message` and `error.message` which hopefully is a find / replace and then can continue to the other fields.

@epixa I assume your team also plans to adjust the integrations?

**Comment by epixa** [comment]
Yep, we update all of our integrations with ECS changes every release. The match_only_text stuff will ship in ECS 8.0, so that's where we'll update our integrations too.
