### ISSUE TITLE
Need a fix for Cisco Firepower malware event that should not be an alert

### ISSUE THREAD

**Issue by LaZyDK** [elastic/integrations#1556]
All file events with the event id 430005 are classified as alerts, and are alerted on by the default Kibana SIEM alert called `External Alerts`. 
This is giving a lot of false positives. 

Reference log line:
```
<113>2021-08-25T14:55:13Z   %FTD-1-430005: DeviceUUID: c20ef000-c4f3-11e9-9b57-c6a90fda2892, InstanceID: 3, FirstPacketSecond: 2021-08-25T14:55:06Z, ConnectionID: 44560, SrcIP: 172.16.0.2, DstIP: 8.253.98.120, SrcPort: 65000, DstPort: 80, Protocol: tcp, FileDirection: Download, FileAction: Malware Cloud Lookup, FileSHA256: 2e05c13906b7435e80b6128c2bf86ba0644b0e6205efb96f3c14e52afd75f1c9, SHA_Disposition: Unknown, SperoDisposition: Spero detection not performed on file, ThreatName: Invalid ID, FileName: 34990729_2caabbb9f7956d24f8b6124641b1df788e3ea127.cab, FileType: MSCAB, FileSize: 7179, ApplicationProtocol: HTTP, Client: Windows Update, WebApplication: Microsoft Update, User: Not Found, FilePolicy: FILE POLICY, URI: http://download.windowsupdate.com/d/msdownload/update/others/2021/08/34990729_2caabbb9f7956d24f8b6124641b1df788e3ea127.cab, IngressVRF: Global, EgressVRF: Global
```

This is the classifying line in the ingest pipeline:
https://github.com/elastic/integrations/blob/985167239ef20f159cd3dc79c6d67d6b6b5b1849/packages/cisco/data_stream/ftd/elasticsearch/ingest_pipeline/default.yml#L1211
Effectively making the event an alert by setting these two ECS event fields:
`event.category`: malware
`event.kind`: alert
when they should be:
`event.category`: file
`event.kind`: event

There should be another check on the `cisco.ftd.securiy.SHA_Disposition` field.
If that field is either `Custom Detection` or `Malware` this should be an alert. Or else it is just a file event.

Reference documentation on the log types regarding event 430005: https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/security-event-syslog-messages.html

**Comment by r00tu53r** [comment]
@LaZyDK I am thinking if it is better to set `event.kind => alert` for the case when `SHA_Disposition` is `Unavailable` ? Considering AMP is unavailable. It's better to err on the side of caution ?

**Comment by LaZyDK** [comment]
@r00tu53r I would oppose that opinion. Usualle when the SHA disposition is unavailable it means that the file is new and never seen before. This would be most files. 
We should only alert when we are sure that something is malicious.
