### ISSUE TITLE
[Panw] Adding timezone in Fleet UI

### ISSUE THREAD

**Issue by P1llus** [elastic/integrations#1564]
The data from the PANW integration does not include timezone, and there is no easy way to add a custom timezone to the ingest pipeline.

We should add in 2 options to the package:
1. A integration setting in the UI to define timezones in the format expected by the date ingest pipeline processor.
2. Default to `add_locale ~` if no timezone has been set

Related discuss topic: https://discuss.elastic.co/t/panw-integration-timezone-offset-problem/282978

**Comment by legoguy1000** [comment]
I ran into the same issue with the Snort integration, https://github.com/elastic/integrations/pull/1575.  I added an input that I found from one of the other modules to set the time zone in the  +HH:mm format.
