### ISSUE TITLE
Single place for changing registry dependency

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#157]
In https://github.com/elastic/integrations/pull/156 the integrations repo was attached to a specific version of the registry. Currently this is defined in 4 places:

* Golang vendor
* Docker for testing
* Testing environment
* K8s manifest

It would be nice to only need to update in a single places so it does not happen by accident that the versions diverge.

**Comment by mtojek** [comment]
Originally, I had plans to extend the elastic package tool. We might need this one (if only the team still considers it useful).
