### ISSUE TITLE
Add daily jenkins pipeline to run tests with latest snapshots

### ISSUE THREAD

**Issue by jsoriano** [elastic/integrations#1581]
After https://github.com/elastic/integrations/pull/1541, integrations are tested with the oldest supported version of the stack. This helps on reproducibility and stability of builds for integrations developers, and it will also help to detect when version constraints need to be updated. But with this we are not testing integrations with the most recent version of the stack.
Add a daily job that runs the CI pipeline with latest snapshots of the stack.

**Comment by mtojek** [comment]
There are nightly jobs configured for the master branch. If you look at the Jenkins board: https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/master/ , these are builds run around 3:52 AM.

**Comment by jsoriano** [comment]
> There are nightly jobs configured for the master branch. If you look at the Jenkins board: https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/master/ , these are builds run around 3:52 AM.
> 
> EDIT:
> 
> Ok, I realized you're referring to "latest" snapshots, so it's a valid issue.

Ok, it would be to modify the pipeline to allow selecting a version of the stack, and modify this job to use the 8.0 and/or 7.x snapshots.
