### ISSUE TITLE
Proposal: Update release script

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#161]
Thanks to the new release process https://github.com/elastic/package-storage/issues/86 we now have 3 branches: production, staging, snapshot. The current release script in integrations opens a PR against the production branch. But instead we should start to promote the packages through the stages. As soon as a package is in the snapshot branch, we should have a promote script to move it to staging / production. This is covered by this issue here: https://github.com/elastic/package-storage/issues/123 Here I want to focus on a proposal on how moving forward the release script to get things into snapshot could be adjusted.

The basic assumption is, that every time a PR is merged for a package, it can be released as snapshot. So going from a merged PR to the snapshot branch and publishing it should be fully automatic. This means, changes to packages can be tested by anyone in the Kibana snapshot builds after a few minutes.

The release script would to the following changes after a PR is merged:

* Build package to bring it in the correct format
* Get most recent snapshot branch
* Copy package into snapshot branch. If package with same version already exists, overwrite it.
* Run all checks on the `snapshot` branch.
* If all checks are green, commit and push change to snapshot branch

This will automatically trigger CI which builds a container and releases it to `epr-snapshot.elastic.co` and makes it available in the SNAPSHOT stack builds. The same version can be pushed multiple times. As soon as a version is ready to release, it is promoted to staging and the package version should be incremented in the manifest.

I wonder what happens if a PR changes multiple packages? Will it do one commit per package or push all packages together? Always pushing all together might simplify things. In the end, only the diff matters.

**Comment by exekias** [comment]
> The same version can be pushed multiple times. As soon as a version is ready to release, it is promoted to staging and the package version should be incremented in the manifest.

Would this happen with a commit in this repo? I understand we will need to bump versions and tag them for later consumption

**Comment by ruflin** [comment]
The version increment would happen with a commit / PR in this repo. The promotion to staging I would expect to happen manually by an engineer through triggering the promotion script.

**Comment by mtojek** [comment]
Resolving in favor of https://github.com/elastic/package-storage/issues/123
