### ISSUE TITLE
Modifying of Integrations' Kibana asset ids in Ingest Manager

### ISSUE THREAD

**Issue by ph** [elastic/integrations#163]
When an Integration gets installed we will be modifying the ids of the Kibana assets in Ingest Manager to avoid conflicts from a Beats installation of the same assets.  Please see PR #7052 .  Package authors will need to modify any visualization that has hardcoded markdown links.  For example: https://github.com/elastic/integrations/blob/master/packages/nginx/kibana/visualization/97109780-a2a5-11e7-928f-5dbe6f6f5519-ecs.json#L14.  

These often appear as links in a Dashboard:
![unnamed](https://user-images.githubusercontent.com/640/86838915-bdb65480-c06e-11ea-9172-46742aad449d.png)

I've searched and found three Integrations that need to be updated:  Nginx, System, and Netflow.

reported by @neptunian 

cc @andresrc

**Comment by neptunian** [comment]
The ID just needs to be prepended with the package name, separated by a dash.   So for example this link in the Nginx package:
`[Nginx logs overview](#/dashboard/55a9e6e0-a29e-11e7-928f-5dbe6f6f5519-ecs) `would become `[Nginx logs overview](#/dashboard/nginx-55a9e6e0-a29e-11e7-928f-5dbe6f6f5519-ecs)`

**Comment by exekias** [comment]
@ycombinator I understand this can be closed after https://github.com/elastic/integrations/pull/171. is there anything pending?

**Comment by ycombinator** [comment]
Yes, I think this can be closed now. There was discussion about updating tooling to help with _new_ packages going forward but I think that can be treated as a separate issue.

Closed via #171.
