### ISSUE TITLE
No Proxy URL config for httpjson or AWS-S3 imputs

### ISSUE THREAD

**Issue by legoguy1000** [elastic/integrations#1647]
With the migration of Filebeat modules to packges, the option to use a proxy with the httpjson and aws-s3 inputs as well as the AWS metric sets are missing.

**Comment by legoguy1000** [comment]
@kaiyan-sheng Can u close this? I mistyped in the related PR to auto close it.

**Comment by kaiyan-sheng** [comment]
@legoguy1000 Will do! Thank you again for adding this!!!
