### ISSUE TITLE
Tenable.sc

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1724]
### Description
SecurityCenter is a comprehensive vulnerability management solution that provides complete visibility into the security posture of your distributed and complex IT infrastructure. SecurityCenter consolidates and evaluates vulnerability data from across your entire IT infrastructure, illustrates vulnerability trends over time, and assesses risk with actionable context for effective remediation prioritization.

### Architecture
Tenable.sc exposes events via a REST API, with documentation available [here](https://docs.tenable.com/tenablesc/api/index.htm). 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by NateUT99** [comment]
Is it possible to expand this integration to include their cloud offering, Tenable.io?

**Comment by jamiehynds** [comment]
Hey @NateUT99 - thanks for the suggestion. Tenable.io is certainly on our radar after we do .sc, but it will be treated as a separate integration as it leverages a different API.

**Comment by craiglawson** [comment]
I have been waiting for this for some time after @P1llus mentioned it to me at Blackhat I think, happy to support any testing

**Comment by jamiehynds** [comment]
Thanks @craiglawson, we're aiming to start the Tenable.sc integration pretty soon, so will definitely be in touch to get some early feedback from you.

**Comment by jamiehynds** [comment]
Closed via https://github.com/elastic/integrations/pull/2188

**Comment by craiglawson** [comment]
Oh - closed, how do we get to review this? or do we need to be running 8.x?

**Comment by jamiehynds** [comment]
Hey @craiglawson, you're quick off the mark :)

We've just merged the [Tenable.sc PR ](https://github.com/elastic/integrations/pull/2188) and will be making it publicly available over the coming days. You'l need to be running 7.16, and will also need Elastic Agent. I'll ping you as soon as the integration is live. Looking forward to hearing your feedback once you have it up and running.

**Comment by jamiehynds** [comment]
Hi @craiglawson - our Tenable.sc integration is now live. Once you're running 7.16, you'll see it under integrations :)
