### ISSUE TITLE
Cloudflare Log Push 

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1727]
### Description
At the core, Cloudflare is a Content Delivery Network (CDN) composed of hundreds of data centers located in more than 100 countries. Cloudflare has grown to handle five to ten percent of the global internet traffic, making Cloudflare one of the largest CDNs in the world.

Since all traffic to your website first passes through the Cloudflare network, malicious traffic such as DDoS attacks, comment spam, or content scraping can be detected and filtered or rerouted without ever reaching your server in the first place.

Malicious agents are detected using a variety of identifiers, including previous known malicious IP addresses, the type of requests made, any malicious payloads that may be included in the request, or even the timing and frequency of their connections. This is weighed against the security level you’ve set up on your site to determine whether a visitor is let through, if additional verification on the visitor’s browser is required, or if the visit is blocked entirely.

### Architecture
Our existing Cloudflare integration is based on their Log Pull technology. Next steps is to support Log Push. Log push can push events directly to a SIEM, and is the newer of the two options - documentation [here](https://developers.cloudflare.com/logs/about).

Worth noting there is a Cloudflare integration [available on Github](https://github.com/cloudflare/cloudflare-elastic) but hasn't been maintained and has known issues. This new integration will be the preferred way to integration Cloudflare + Elastic. 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by CyberTaoFlow** [comment]
Yeah this is absolutely the only way to get WAF and CF firewall data.  While it is loosely implied in their documentation I have confirmed this with CF support.

![image](https://user-images.githubusercontent.com/7001917/168908592-209eaf42-0ea7-447c-ad50-b40a15cf6e8e.png)
