### ISSUE TITLE
Gitlab

### ISSUE THREAD

**Issue by legoguy1000** [elastic/integrations#1741]
Gitlab produces a number of different logs as seen here, https://docs.gitlab.com/ee/administration/logs.html.

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to: 7.16

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists

**Comment by legoguy1000** [comment]
not stall

**Comment by IanLee1521** [comment]
Hi @legoguy1000 ! Just curious what "release-pending" means, given that label was added in 2021?

**Comment by IanLee1521** [comment]
I think that one of the main ones that would be nice to include would be the gitlab access logs.. that uses an embedded nginx server. 

I have the following ingest pipeline that I'd written that seems to be working... not sure what it would take to convert this to an integration. @kpollich and I had talked about this at one point though

```json
PUT _ingest/pipeline/gitlab.access
{
  "processors": [
    {
      "append": {
        "field": "tags",
        "value": [
          "gitlab.access"
        ],
        "allow_duplicates": false,
        "ignore_failure": true
      }
    },
    {
      "set": {
        "field": "data_stream.dataset",
        "value": "gitlab.access",
        "ignore_empty_value": true,
        "ignore_failure": true
      }
    },
    {
      "set": {
        "field": "event.ingested",
        "value": "{{_ingest.timestamp}}"
      }
    },
    {
      "set": {
        "field": "ecs.version",
        "value": "8.11.0"
      }
    },
    {
      "dissect": {
        "field": "message",
        "pattern": "%{source.ip} - %{user.name} [%{http.access_time}] \"%{http.request.method} %{url.path} HTTP/%{http.version}\" %{http.response.status_code} %{http.response.body.bytes} \"%{http.request.referrer}\" \"%{tmp_user_agent}\" %{tmp}",
        "on_failure": [
          {
            "dissect": {
              "field": "message",
              "pattern": "%{source.ip} - %{user.name} [%{http.access_time}] \"%{http.request.method} %{url.path} %{http.version}\" %{http.response.status_code} %{http.response.body.bytes} \"%{http.request.referrer}\" \"%{tmp_user_agent}\" %{tmp}",
              "ignore_failure": true
            }
          }
        ]
      }
    },
    {
      "set": {
        "field": "related.user",
        "copy_from": "user.name",
        "ignore_empty_value": true,
        "ignore_failure": true
      }
    },
    {
      "user_agent": {
        "field": "tmp_user_agent",
        "extract_device_type": true,
        "ignore_missing": true,
        "ignore_failure": true
      }
    },
    {
      "remove": {
        "field": "tmp_user_agent",
        "ignore_missing": true,
        "ignore_failure": true
      }
    }
  ],
  "on_failure": [
    {
      "append": {
        "field": "tags",
        "value": [
          "_failed-gitlab.access"
        ],
        "allow_duplicates": false,
        "ignore_failure": true
      }
    }
  ]
}
```

**Comment by andrewkroh** [comment]
A [Gitlab](https://www.elastic.co/docs/current/en/integrations/gitlab) integration has been created.
