### ISSUE TITLE
[System] `system.core` dataset missing `template_path`

### ISSUE THREAD

**Issue by jen-huang** [elastic/integrations#175]
As the title says, `system.core` dataset doesn't have `template_path` property which Kibana uses to build the agent config yaml. I do see `/package/system/0.3.0/dataset/core/agent/stream/stream.yml.hbs` available so I think it's just a matter of adding `template_path: stream.yml.hbs` to the manifest:

```
    {
      "type": "metrics",
      "name": "system.core",
      "title": "System core metrics",
      "release": "experimental",
      "streams": [
        {
          "input": "system/metrics",
          "vars": [
            {
              "name": "period",
              "type": "text",
              "title": "Period",
              "multi": false,
              "required": true,
              "show_user": true,
              "default": "10s"
            },
            {
              "name": "core.metrics",
              "type": "text",
              "title": "Core Metrics",
              "description": "How to report core metrics. Can be \"percentages\" or \"ticks\"\n",
              "multi": true,
              "required": true,
              "show_user": true,
              "default": [
                "percentages"
              ]
            }
          ],
          "title": "System core metrics",
          "description": "Collect System core metrics",
          "enabled": false
        }
      ],
      "package": "system",
      "path": "core"
    }
```

This causes an error in Kibana when trying to add it:

![image](https://user-images.githubusercontent.com/1965714/87458250-90156200-c5be-11ea-8b7c-7f7ffdd8c355.png)

I created an issue in package registry to validate the existence of `template_path` on streams: https://github.com/elastic/package-registry/issues/595

**Comment by hendry-lim** [comment]
The same error encountered for all disabled metricsets:

- `system.entropy`
- `system.filesystem`
- `system.fsstat`
- `system.network_summary`
- `system.raid`
- `system.service`
- `system.socket`
- `system.users`

**Comment by ruflin** [comment]
I opened https://github.com/elastic/package-registry/pull/600 with a bug fix.

**Comment by jen-huang** [comment]
Closing as elastic/package-registry#600 is merged. I also tested Kibana locally with enabling all system metricsets and saving/editing was successful with no errors.
