### ISSUE TITLE
Imperva Cloud WAF

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1763]
### Description
Imperva provides a cloud security solution that protects applications, APIs, and Databases on Amazon Web Services, Microsoft Azure, and Google Cloud, with one pane of glass for application and data security. Overview available [here](https://docs.imperva.com/bundle/cloud-application-security/page/introducing/overview.htm). 

### Architecture
Imperva supports both API or S3 based integration, with documentation available [here](https://docs.imperva.com/bundle/cloud-application-security/page/settings/log-integration.htm). Supporting both would be nice to have for optionality, however the priority is API to ensure we don't limit non-AWS users from availing of the integration. 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by kcreddy** [comment]
Hey @janvi-elastic and @piyush-elastic 

Regarding the issue of [Index File](https://docs.imperva.com/bundle/cloud-application-security/page/settings/log-integration.htm#:~:text=stored%20per%20account.-,Log%20index%20file%3A,-Imperva%20provides%20a) API call:
AWS S3 (push-based) approach should not be having this problem in my understanding, so you can keep working on that in the meantime.

After discussion with @P1llus and @andrewkroh about the issue, we first need to clarify below questions. If we don't have answers yet, we should check with Imperva.

1. Is the Index file API always follows sort order? 
   - This needs to be verified for both old and new file formats. If it follows sort order, what would be the order in which files are listed (especially for new format using UUIDs)?

2. Is late file availability possible? 
   - By this, I mean can a filename that was supposed to be appearing in current fetch actually gets delayed and appears in the next fetch. For example: 
       - Fetch 1: `xxxx_156.log, xxxx_157.log, xxxx_159.log` (note missing 158.log)
       - Next Fetch: `xxxx_156.log, xxxx_157.log, xxxx_158.log, xxxx_159.log, xxxx_160.log`

If both 1 and 2 are true, i.e., API follows sort order with no late files, then we can live with CEL state only storing the last filename as you mentioned. 
But in other cases, we would need to store all filenames.

**Proposed solution (I can think of):**
1.  Store all filenames in CEL state. Although CEL input can read from a file currently, it doesn't have functionality to write to/create a file. So, we can only leverage internal CEL state at this point. With all the filenames, this state could grow to a large number that can impact the performance. 
2. Store all filenames in CEL state with finite amount of buckets `{"<bucket>": [<list of filenames in that fetch>]}` and purge/overwrite the last bucket used. 
3. Enhance CEL input to write to the local file and store all filenames inside a local file. Need to check with Dan if this option is any better.

In any solution, if we end up storing all filenames, we should be performance testing CEL input at max load.

**Comment by jamiehynds** [comment]
Closing as our Imperva Cloud WAF integration is now available.
