### ISSUE TITLE
Add Integration Change log in docs and Kibana Integrations UI

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#1769]
_Use Case: As an Elastic Apps User, I want to see information about the changes introduced in each integration that I am consuming so that I could make a self-serve decision - whether to upgrade to a specific version or not._

We should support adding release notes and changes in the Integration guide or Kibana Integrations UI to let the users know what has changed and whether they should upgrade an integration or not and in some cases ( offline registry) whether to enable their users to use a specific integration version or not.

**Comment by jamiehynds** [comment]
Closing if favor of https://github.com/elastic/integrations/issues/5142
