### ISSUE TITLE
[Discuss] Include Packetbeat with agent download package

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1771]
Now that we have integrated Packetbeat with Elastic Agent, via our 'Network Packet Capture' agent integration, I'd like to propose bundling Packetbeat with Elastic Agent to simplify deployment. Currently, if a user enables the integration, the agent will download the necessary binary. This slows down deployment, but is also a blocker in air-gapped environments. 

Packetbeat downloads page [here](https://www.elastic.co/downloads/beats/packetbeat), for visibility into installer size.

**Comment by jamiehynds** [comment]
@nimarezainia would be great to get your thoughts here.

**Comment by nimarezainia** [comment]
Hi @jamiehynds 
Similar discussions in regards to osquery being included. My initial reaction is that this approach is plugging a gap that exist in not having an airgap package registry available (beta today).

We do have an elastic-agent-complete binary that could be used to bundle these integrations if required.

Has there been a customer request in this regard?  thanks!

**Comment by jamiehynds** [comment]
Thanks @nimarezainia. There hasn't been a customer request yet, but huge demand to migrate Packetbeat to Agent which we've now done. I believe we include Filebeat, Metricbeat, etc with Agent, so seems logical to include Packetbeat also. 

Is there a formal process to getting Packetbeat bundling approved? cc: @andrewkroh

**Comment by nimarezainia** [comment]
We're having this exact discussion for osquery. I'll add you both to that thread. We don't want that image size to grow but you are right - this is a core beat we need in there.

**Comment by jamiehynds** [comment]
Closing as Packetbeat is now bundled with Agent as of 8.6
