### ISSUE TITLE
Investigate and capture design for autodiscovery conditions in integrations UI

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#1867]
We need a way for Elastic users to add or edit autodiscovery conditions right from the integrations UI in Kibana. This will make the configuration user experience seamless.

**Comment by ChrsMark** [comment]
I will try to break it down into pieces. First of all let's see how an input based on provider's conditions looks like today at [standalone agent](https://github.com/elastic/beats/blob/master/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L423):

```
- name: redis
  type: redis/metrics
  use_output: default
  meta:
    package:
      name: redis
      version: 0.3.6
  data_stream:
    namespace: default
  streams:
    - data_stream:
        dataset: redis.info
        type: metrics
      metricsets:
        - info
      hosts:
        - '${kubernetes.pod.ip}:6379'
      idle_timeout: 20s
      maxconn: 10
      network: tcp
      period: 10s
      condition: ${kubernetes.labels.app} == 'redis'
```
As we can see the only thing that is added to the input as produced from the package's datastream spec is the `condition`: `condition: ${kubernetes.labels.app} == 'redis'`.

This means that if we have a way from the UI to extend the basic package's input section and be able to add additional conditions then we should be covered. This would also be useful for defining conditions in general and only for k8s related conditions. Today I don't have a way as user to add a custom condition to a random datastream, for example if I want to start `mongodb` integration only when a specific condition is true.

So in my opinion this issue fallbacks to `Adding support for defining conditions from Fleet UI` and it's not a k8s specific one.

Another thing that we need support for is to be able to configure providers' configuration for example to add advanced settings for metadata addition, set the scope and all the settings that we can leverage today only from standalone mode.

**Comment by ChrsMark** [comment]
@mukeshelastic @akshay-saraswat @jen-huang any plans on moving this one forward? We keep getting questions about supporting "autodiscovery" in managed mode which should be solved by this one. 

Another way to support this would be to add `condition` inputs for all the packages in the package spec like https://github.com/elastic/integrations/blob/master/packages/redis/manifest.yml.

**Comment by jen-huang** [comment]
@mostlyjason have you looked at this from Fleet UI perspective?

**Comment by ChrsMark** [comment]
2 things that we also need to verify here: 
1. what will happen in case of an integration already defines condition in it's package spec? Will the old and new condition be somehow combined with an AND logic?
2. What needs to be changed in the package's side? Even if we add the condition on the UI how the values will be added to the actual package's input in the end? @mtojek @jsoriano any thoughts/concerns here?

**Comment by jsoriano** [comment]
> * what will happen in case of an integration already defines condition in it's package spec? Will the old and new condition be somehow combined with an AND logic?

Yes, if a template already contains a condition, I think that both conditions should be combined with an AND in the final policy.

> * What needs to be changed in the package's side? Even if we add the condition on the UI how the values will be added to the actual package's input in the end? @mtojek @jsoriano any thoughts/concerns here?

I don't think this affects to how packages are defined. I think this only affects how policies are generated.

**Comment by mostlyjason** [comment]
@akshay-saraswat Mukesh mentioned you'd own definition for this one? I'd love to see it when you're ready to share.

**Comment by akshay-saraswat** [comment]
@mostlyjason I am unassigning myself from this issue and would be happy to assist you further as needed.

**Comment by ChrsMark** [comment]
@akshay-saraswat @mostlyjason will we need a new owner for this one? Also what is the status of this?

**Comment by mostlyjason** [comment]
@ChrsMark I'm working on a proposal for this feature

**Comment by ChrsMark** [comment]
> @ChrsMark I'm working on a proposal for this feature

Cool! Let me know if I can help in any way.

**Comment by ChrsMark** [comment]
@gizas @mlunadia do we have any updates on this? 
At the moment (without this feature in the Fleet UI) we cannot provide any kind of dynamic monitoring (based on conditions) on k8s when Agent is managed by fleet, while the feature is already supported by the backend (and in standalone mode) for quite some time now.

**Comment by ChrsMark** [comment]
Closing in honor of https://github.com/elastic/elastic-agent/issues/707
