### ISSUE TITLE
[O365] Add support for Microsoft Authentication Library (MSAL)

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1868]
Our Office365 integration currently utilizes Azure Active Directory Authentication Library (ADAL) for authentication and authorization. Microsoft has announced that ADAL will become deprecated on June 30 2023. As such, it is recommended to migrate ADAL authentication to the Microsoft Authentication Library (MSAL). Additional details regarding this announcement can be found below.

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration

The above announcement also contains the following warning:

`
If you choose not to migrate to MSAL before ADAL support ends on June 30, 2023, you put your app's security at risk. Existing apps that use ADAL will continue to work after the end-of-support date, but Microsoft will no longer release security fixes on ADAL.
`

**Comment by andrewkroh** [comment]
Am I correct in thinking that we should begin the deprecation process for the Filebeat [o365audit](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-o365audit.html) input for the same reason? It's using https://github.com/Azure/go-autorest/ which says "NOTE: The modules in this repo will go out of support by March 31, 2023."

**Comment by jamiehynds** [comment]
While the module should be deprecated, I'm wary of an immediate deprecation of a GA'd module. Could we add a notice to the docs to (1) advise users to move to the O365 integration, (2) make them aware of the go-autorest end of support and (3) set a date or stack release where the module will be deprecated.

**Comment by jamiehynds** [comment]
Closing as we have migrated the O365 integration to use the CEL input and no longer rely on the MSAL for authentication.
