### ISSUE TITLE
[META] Update title and description based on guidelines for Beats integrations

### ISSUE THREAD

**Issue by alexfrancoeur** [elastic/integrations#1883]
In 7.16, we are planning to introduce the unified integrations view. The primary goal of this view is to improve the discoverability for all data ingest options at Elastic. As part of this initiative, we'd like to improve the titles and descriptions of each integration card and do so in a uniform way. 

## Guidelines
These are the general guidelines we plan to use for the integration cards

![image](https://user-images.githubusercontent.com/25181823/136435492-1ccf2666-a20c-4b95-af0c-80d1e784f82a.png)

## Beats example
Here's an example for how beats can leverage these guidelines, but please follow the guidelines as you see fit.
| Current Title     | Current Description                                                        | New Title          | New Description                                           |
|-------------------|----------------------------------------------------------------------------|--------------------|-----------------------------------------------------------|
| ActiveMQ logs     | Collect ActiveMQ logs with Filebeat                                        | ActiveMQ Logs      | Collect logs from ActiveMQ servers with Filebeat.         |
| ActiveMQ metrics  | Fetch monitoring metrics from ActiveMQ instances.                          | ActiveMQ Metrics   | Collect metrics from ActiveMQ servers with Metricbeat.    |
| Aerospike metrics | Fetch internal metrics from the Aerospike server.                          | Aeropspike Metrics | Collect metrics from Aerospike databases with Metricbeat. |
| Apache logs       | Collect and parse access and error logs created by the Apache HTTP server. | Apache Logs        | Collect logs from Apache servers with Filebeat.           |
| Apache metrics    | Fetch internal metrics from the Apache 2 HTTP server.                      | Apache Metrics     | Collect metrics from Apache servers with Metricbeat.      |
| Auditbeat         | Collect audit data from your hosts.                                        | Auditbeat Events   | Collect events from your servers with Auditbeat.          |
| Auditd logs       | Collect logs from the Linux auditd daemon.                                 | Auditd Logs        | Collect logs from the Linux audit daemon with Filebeat.   |

@akshay-saraswat will follow up with the appropriate folks

**Comment by akshay-saraswat** [comment]
Don't have an owner for it yet on the integrations team. It is difficult to find spare bandwidth close to FF. @joshdover offered help to update the codebase. And I am working on providing a spreadsheet with titles and descriptions.

**Comment by akshay-saraswat** [comment]
Here is the spreadsheet with new Titles and Descriptions. Please review.
https://docs.google.com/spreadsheets/d/1MbI69al5y9xCDmyu0SP63gOw9RuKPsgeoiB8vZa95IY
