### ISSUE TITLE
Update title and description based on guidelines for Elastic Agent based Security integrations

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#1900]
In 7.16, we are planning to introduce the unified integrations view. The primary goal of this view is to improve the discoverability for all data ingest options at Elastic. As part of this initiative, we'd like to improve the titles and descriptions of each integration card and do so in a uniform way. 

## Guidelines
These are the general guidelines we plan to use for the integration cards

![image](https://user-images.githubusercontent.com/25181823/136435492-1ccf2666-a20c-4b95-af0c-80d1e784f82a.png)

## Elastic Agent example
Here's an example for how agent can leverage these guidelines, but please follow the guidelines as you see fit.

| Current Title | Current Description                                                              | New Title   | New Description                                                       |
|---------------|----------------------------------------------------------------------------------|-------------|-----------------------------------------------------------------------|
| ActiveMQ      | ActiveMQ Integration                                                             | ActiveMQ    | Collect logs and metrics from ActiveMQ servers with Elastic Agent.    |
| Apache        | This Elastic integration collects logs and metrics from Apache servers           | Apache      | Collect logs and metrics from Apache servers with Elastic Agent.      |
| Auditd        | This Elastic integration collects and parses logs from the Audit daemon (auditd) | Auditd      | Collect logs from the Linux audit daemon with Elastic Agent.          |
| AWS           | This integration collects logs and metrics from Amazon Web Services (AWS)        | AWS         | Collect logs and metrics from Amazon Web Services with Elastic Agent. |
| AWS Billing   |                                                                                  | AWS Billing | Collect logs and metrics from AWS Billing with Elastic Agent.         |
| Azure Logs    | This Elastic integration collects logs from Azure                                | Azure       | Collect logs from Microsoft Azure with Elastic Agent.                 |

**Comment by andrewkroh** [comment]
I have started a Sheet with this content above to use for tracking the proposed changes.

https://docs.google.com/spreadsheets/d/1R7Tx3Gpz8Ql5IRbC-fPEDM07rsTw69auA6g7JiGmEJ8/edit?usp=sharing

**Comment by alexfrancoeur** [comment]
@jamiehynds thank you for the bump, I missed this the first time around 😉 

There are a few integrations that don't map directly to beats / agent ingest. EMS boundaries, sample data and file upload to name a few. We are addressing those [here](https://github.com/elastic/kibana/issues/114336#issuecomment-943509158). If we can, I think we could fine tune to align with the guidelines as much as possible. I've taken a stab at applying these below as an example.

With the amount of time we have before FF, I'd be fine with leaving the descriptions as-is. But if we can apply the guidelines, it'd be great for alignment. How the guidelines are applied are completely up to the team.

| Current Title | Current Description                                                              | New Title   | New Description                                                       |
|---------------|----------------------------------------------------------------------------------|-------------|-----------------------------------------------------------------------|
| Osquery Manager     | This Elastic integration lets you centrally manage osquery deployments, run live queries and schedule recurring queries                                                            | Osquery Manager    | Centrally manage and query osquery deployments with Elastic Agent.   |
| Endpoint Security        | Protect your hosts with threat prevention, detection and deep security visibility          | Endpoint Security     | Protect your hosts with threat prevention, detection and deep security visibility with Elastic Agent.      |

**Comment by andrewkroh** [comment]
I was doing a final review and ome things got merged while we were working this and they are not correct. Also there was an issue with two of the ones we did change. So we'll need to fix these:

|Title|Desc|
|-----|-------|
|1Password Events Reporting|This Elastic integration collects events from 1Password Events Reporting.|
|Cisco Duo|Collect logs from Cisco Duo with Elastic Agent. This Elastic integration collects logs from Cisco Duo|
|GitHub|GitHub Integration|
|Network Packet Capture|Collect logs from Network Packet Capture with Elastic Agent.|
|AbuseCH API|This Elastic integration collects threat intelligence from AbuseCH API endpoints|
|Anomali|This Elastic integration collects events from Anomali|
|Alienvault OTX|This Elastic integration collects threat intelligence from Alienvault OTX API endpoints|

**Comment by andrewkroh** [comment]
This should be the final result after https://github.com/elastic/integrations/pull/1997 is merged.

|Title|Desc|
|-----|-------|
|1Password Events Reporting|Collect events from 1Password Events API with Elastic Agent.|
|Auditd|Collect logs from the Linux auditd daemon with Elastic Agent.|
|Barracuda|Collect logs from Barracuda with Elastic Agent.|
|Blue Coat Director|Collect logs from Blue Coat Director with Elastic Agent.|
|VMware Carbon Black EDR|Collect logs from VMware Carbon Black EDR with Elastic Agent.|
|CEF Logs|Collect logs from CEF Logs with Elastic Agent.|
|Check Point|Collect logs from Check Point with Elastic Agent.|
|Cisco|Deprecated. Use a specific Cisco package instead.|
|Cisco ASA|Collect logs from Cisco ASA with Elastic Agent.|
|Cisco Duo|Collect logs from Cisco Duo with Elastic Agent.|
|Cisco FTD|Collect logs from Cisco FTD with Elastic Agent.|
|Cisco IOS|Collect logs from Cisco IOS with Elastic Agent.|
|Cisco Meraki|Collect logs from Cisco Meraki with Elastic Agent.|
|Cisco Nexus|Collect logs from Cisco Nexus with Elastic Agent.|
|Cisco Secure Endpoint (AMP)|Collect logs from Cisco Secure Endpoint (AMP) with Elastic Agent.|
|Cisco Umbrella|Collect logs from Cisco Umbrella with Elastic Agent.|
|Cloudflare|Collect logs from Cloudflare with Elastic Agent.|
|CrowdStrike Falcon|Collect logs from CrowdStrike Falcon with Elastic Agent.|
|Cyber-Ark|Deprecated. Use CyberArk Privileged Access Security instead.|
|CyberArk Privileged Access Security|Collect logs from CyberArk Privileged Access Security with Elastic Agent.|
|CylancePROTECT|Collect logs from CylancePROTECT with Elastic Agent.|
|F5 BIG-IP|Collect logs from F5 BIG-IP with Elastic Agent.|
|Fortinet|Collect logs from Fortinet software with Elastic Agent.|
|Google Cloud Platform|Collect logs from Google Cloud Platform with Elastic Agent.|
|GitHub|Collect events from GitHub with Elastic Agent.|
|Google Workspace|Collect logs from Google Workspace with Elastic Agent.|
|Hashicorp Vault|Collect logs from Hashicorp Vault with Elastic Agent.|
|Imperva SecureSphere|Collect logs from Imperva SecureSphere with Elastic Agent.|
|Infoblox NIOS|Collect logs from Infoblox NIOS with Elastic Agent.|
|Iptables|Collect logs from Iptables with Elastic Agent.|
|Juniper|Collect logs from Juniper devices with Elastic Agent.|
|Microsoft|Deprecated. Use a specific Microsoft package instead.|
|Microsoft Defender for Endpoint|Collect logs from Microsoft Defender for Endpoint with Elastic Agent.|
|Microsoft DHCP|Collect logs from Microsoft DHCP with Elastic Agent.|
|NetFlow|Collect logs from NetFlow with Elastic Agent.|
|Arbor Peakflow SP|Collect logs from Arbor Peakflow SP with Elastic Agent.|
|Network Packet Capture|Collect packets from network interfaces with Elastic Agent.|
|Office 365|Collect logs from Office 365 with Elastic Agent.|
|Okta|Collect logs from Okta with Elastic Agent.|
|Osquery|Collect logs from Osquery with Elastic Agent.|
|Palo Alto PAN-OS|Collect logs from Palo Alto PAN-OS with Elastic Agent.|
|Palo Alto Cortex XDR|Collect logs from Palo Alto Cortex XDR with Elastic Agent.|
|pfSense|Collect logs from pfSense with Elastic Agent.|
|Proofpoint Email Security|Collect logs from Proofpoint Email Security with Elastic Agent.|
|Radware DefensePro|Collect logs from Radware DefensePro with Elastic Agent.|
|Google Santa|Collect logs from Google Santa with Elastic Agent.|
|Snort|Collect logs from Snort with Elastic Agent.|
|SonicWall FW|Collect logs from SonicWall FW with Elastic Agent.|
|Sophos|Collect logs from Sophos with Elastic Agent.|
|Squid|Collect logs from Squid with Elastic Agent.|
|Suricata|Collect logs from Suricata with Elastic Agent.|
|AbuseCH|Collect threat intelligence from AbuseCH API with Elastic Agent.|
|Anomali|Collect threat intelligence from Anomali APIs with Elastic Agent.|
|AlienVault OTX|Collect threat intelligence from AlienVault OTX with Elastic Agent.|
|Apache Tomcat|Collect logs from Apache Tomcat with Elastic Agent.|
|Custom Windows event logs|Collect event logs from Windows with Elastic Agent.|
|Zeek|Collect logs from Zeek with Elastic Agent.|
|ZeroFox|Collect logs from ZeroFox with Elastic Agent.|
|Zoom|Collect logs from Zoom with Elastic Agent.|
|Zscaler NSS|Collect logs from Zscaler NSS with Elastic Agent.|
