### ISSUE TITLE
[Discuss] libbeat monitoring metrics in beats logs

### ISSUE THREAD

**Issue by leehinman** [elastic/integrations#1909]
Currently libbeat outputs monitoring info in the filebeat/metricbeat logs that are monitored by elastic-agent.  But this monitoring info is not parsed.  Also customers have noticed and requested that these log entries have `event.kind: metric` set.  Couple ideas on how to handle this

### One

Suppress the monitoring output when running under elastic agent

### Two

Add pipelines for these data streams so the metric info is pulled out.

### Others???

**Comment by simitt** [comment]
The config option is `logging.metrics.enabled`.
