### ISSUE TITLE
[Snort] grok pattern not matching log message

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#1910]
There was a test failure on the main branch for the Snort package.

`one or more errors found in documents stored in logs-snort.log-ep data stream: [0] found error.message in event: Provided Grok expressions do not match field value: [[**] [1:1000004:0] Pinging... [**]\n[Classification: Attempted Information Leak] [Priority: 2] \n09/04-21:53:15.299988 10.100.10.190 -> 172.217.1.142\nICMP TTL:64 TOS:0x0 ID:6922 IpLen:20 DgmLen:84 DF]`

https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/master/988/tests

**Comment by efd6** [comment]
The input to the grok processor there is missing the final line.

**Comment by legoguy1000** [comment]
Weird. When I made it in #1575, all the checks passed. Has anything changed that would cause this. @P1llus
