### ISSUE TITLE
Apache integration documentation inconsistent with related pipeline

### ISSUE THREAD

**Issue by jeanfabrice** [elastic/integrations#1918]
### integration
Apache 1.1.0

### description
The [Apache fleet agent integration documentation](https://github.com/elastic/integrations/blob/master/packages/apache/docs/README.md?plain=1#L185) mentions `url.domain` as a field produced by the Apache Error data stream, but the related [Apache pipeline](https://github.com/elastic/integrations/blob/master/packages/apache/data_stream/error/elasticsearch/ingest_pipeline/default.yml) doesn’t set such field.

**Comment by mtojek** [comment]
Thanks for opening the issue.

I suppose that there might be a typo and the `error` data stream doesn't provide `url.domain`, but the documentation has been copied from another data stream. Anyway, let's start with confirming this guess.

**Comment by jeanfabrice** [comment]
👍

**Comment by jeanfabrice** [comment]
Still relevant: https://github.com/elastic/integrations/blob/main/packages/apache/docs/README.md?plain=1#L218

**Comment by jeanfabrice** [comment]
Fixed by https://github.com/elastic/integrations/pull/10162
