### ISSUE TITLE
Investigate whether K8s integration already ships audit logs

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#1919]
We received an [enhancement request](https://github.com/elastic/enhancements/issues/13824) to ingest K8s audit logs that could be used in our SIEM offering. We have to find out whether our K8s integration already ingests K8s audit logs or not. If not, we will respond with the details of what needs to be done to extract audit logs.

**Comment by MichaelKatsoulis** [comment]
@akshay-saraswat  I investigated this. Setting up k8s audit logs is done through `kube-api-server` configuration where the admin sets an audit policy and an audit backend [(doc).](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/)

I set up [kind](https://kind.sigs.k8s.io/docs/user/auditing/) cluster with audit logs enabled to test that.
By default k8s integration and system integration do not collect those logs.
It is possible to be collected using the auditd integration and set the audit log path that k8s is writing to. But that integration is used to collect logs from the auditd daemon and the logs are in different [format](https://github.com/elastic/integrations/blob/master/packages/auditd/_dev/deploy/docker/sample_logs/audit.log) than the [ones](https://github.com/elastic/enhancements/files/7098211/example-kube-audit-logs.json.txt) `kube-api-server`

**Comment by ChrsMark** [comment]
@MichaelKatsoulis @akshay-saraswat what is the status on this? Are we planning to do any more work on this or we can close this one?

**Comment by MichaelKatsoulis** [comment]
@akshay-saraswat we could create a new data stream in kubernetes package for the k8s audit logs if we want to have everything in one place.

**Comment by akshay-saraswat** [comment]
Since we own this integration and there is a need for this datastream, I think we should create one. But that is not a high priority for us at the moment. My suggestion is to close this issue and create a new one for the development of a new datastream because the acceptance criteria for this issue was investigating whether we support audit logs and we have already done that. If you agree, I'll close this and create a new issue for the follow-up work.

**Comment by akshay-saraswat** [comment]
As discussed, closing this issue. We'll create another issue for the addition of a new datastream dedicated to audit logs.
