### ISSUE TITLE
[AbuseCH] Package icon is not visible in Integrations app

### ISSUE THREAD

**Issue by joshdover** [elastic/integrations#1922]
Related to https://github.com/elastic/integrations/pull/1866

The AbuseCH logo is white on a transparent background which currently is not visible in the Integrations app in Kibana. This is especially ugly because alphabetically, this is the first integration in the list now. 
<img width="978" alt="image" src="https://user-images.githubusercontent.com/1813008/137309910-b7be35aa-4736-4008-ba98-a0c1c6496963.png">

<img width="460" alt="image" src="https://user-images.githubusercontent.com/1813008/137309870-d5710013-26be-4323-95aa-2088bbf4e914.png">

Would it be possible to have this icon modified to use the same background color they use on their website?

<img width="195" alt="image" src="https://user-images.githubusercontent.com/1813008/137310007-1da82f7f-6001-4144-8a74-4de878eeb88b.png">

cc @P1llus

**Comment by P1llus** [comment]
Closing this in favour of #1935
