### ISSUE TITLE
Add Pulse Secure Connect integration support

### ISSUE THREAD

**Issue by olmanolsztyn** [elastic/integrations#1927]
Hi,

There was a need to integrate with pulse secure connect. What is needed to create an integration for this solution in elastic solution.
I am ready to provide any necessary information to do so.

Best regards

**Comment by olmanolsztyn** [comment]
I mean o my own i cant create fleet integration.  🙂 Whats needed to create fleet integration for pulse secure? Logs from pulse secure looks similiar for users, admin, system etc.

**Comment by legoguy1000** [comment]
> I mean o my own i cant create fleet integration. 🙂 Whats needed to create fleet integration for pulse secure? Logs from pulse secure looks similiar for users, admin, system etc.

Community members (like myself) can create and submit integrations.  Just fork and clone the repo, make changes and submit pull request.  If u can provide me with the required inputs, documentation, sample logs.... I can try to make one.

**Comment by olmanolsztyn** [comment]
@legoguy1000 did you change field names or finally there will be as i suggested in grok? Sorry im not so familiar in it. :)

**Comment by olmanolsztyn** [comment]
> 
> 
> > Ok looks fine to me. So we need wait for next elk stack release for this integration? What do you think about use pulse_secure.* indice ? This solution can run as vpn (pulse connect secure - pcs) or nac (pulse policy secure - pps). Can be expanded in the future. Similiar like juniper integration.
> 
> That's the kind of feedback I need since I don't use the product. I still need to add more parsing and anymore details on the format/parsing of the log messages would awesome.

I dont use Pulse Secure in PPS mode unfortunately. In case PCS i didn't see more type of logs so far, but they looks similiar as you see.

**Comment by olmanolsztyn** [comment]
I installed experimental integration and got grok parser errors.
Below are examples of logs where:

**z.z.z.z - pulse secure connect ip address
username - name of the user
REALM - name of the realm
ROLE - name of the role (can be empty)
x.x.x.x - ip address of connected host
pcs-name - hostname
HC_POLICY - host checker policy name
XX-XX-XX-XX-XX-XX - client host mac address**

Provided Grok expressions do not match field value: [<174>1 2022-01-19T10:19:35+01:00 z.z.z.z PulseSecure: - - - 2022-01-19 10:19:35 - pcs-name - [x.x.x.x] username(REALM)[ROLE] - Primary authentication successful for username/REALM from x.x.x.x]

Provided Grok expressions do not match field value: [<174>1 2022-01-19T10:23:16+01:00 z.z.z.z PulseSecure: - - - 2022-01-19 10:23:16 - pcs-name - [x.x.x.x] username(REALM)[ROLE] - Host Checker policy 'HC_POLICY' passed on host 'x.x.x.x' address 'XX-XX-XX-XX-XX-XX'  for user 'username'.]

Provided Grok expressions do not match field value: [<174>1 2022-01-19T10:24:04+01:00 z.z.z.z PulseSecure: - - - 2022-01-19 10:24:04 - pcs-name - [x.x.x.x] username(REALM)[ROLE] - Syslog server y.y.y.y (facility LOCAL5, filter Standard, type UDP, interface Global) removed from Events logs]

Provided Grok expressions do not match field value: [<174>1 2022-01-19T10:23:06+01:00 z.z.z.z PulseSecure: - - - 2022-01-19 10:23:06 - pcs-name - [127.0.0.1] System()[] - The current virus signature list imported successfully.]

Provided Grok expressions do not match field value: [<174>1 2022-01-19T10:23:06+01:00 z.z.z.z PulseSecure: - - - 2022-01-19 10:23:06 - pcs-name - [127.0.0.1] System()[] - The current virus signature list downloaded successfully from 'https://download.pulsesecure.net/software/av/uac/epupdate_hist.xml']
