### ISSUE TITLE
Sysmon for Linux

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1930]
### Description
Microsoft has recently released Sysmon for Linux - an open-source system monitor tool developed to collect security events from Linux environments using eBPF (Extended Berkeley Packet Filter) and sending them to Syslog for easy consumption. Project available [here](https://github.com/Sysinternals/SysmonForLinux). 

While the project appears to be a work in progress, we should aim to support syslog from Sysmon for Linux as soon as possible. At launch, there are 7 events supported:

Event ID | Description
1 | Process Creation
3 | Network Connect
5 | Process Terminate
9 | RAW access read
11 | File Create / Overwrite 
16 | Sysmon config change
23 | File Delete

### Architecture
All logs are written as an XML event to the syslog file. The Sysinternals team also included the sysmonLogView utility for parse the data in a more readable format on the local system.

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by shelladdection** [comment]
> @jamesspi did some testing and confirmed you can use our existing sysmon for windows pipeline, with the “decode_xml_wineventlog” processor. Should make a Sysmon for Linux integration pretty straight forward.

how to apply this change to filebeat ?

**Comment by mttaggart** [comment]
For those using Elastic Agent, I went ahead and wrote an ingest pipeline that can tack on to the existing Syslog pipeline. This will extract Sysmon data from the log message: https://gist.github.com/mttaggart/efc870e02eb603943e0dae8ebd54d3dc

**Comment by sSharonV** [comment]
> For those using Elastic Agent, I went ahead and wrote an ingest pipeline that can tack on to the existing Syslog pipeline. This will extract Sysmon data from the log message: https://gist.github.com/mttaggart/efc870e02eb603943e0dae8ebd54d3dc

After seeing your video on youtube I've tried to figure out how to use the existing pipelines of sysmon for windows for the linux dists'.

When you modify the setting of winlog pipeline you can define the syslog file (or any other log file) as an input.
In additional to this step you just need to do the following:
1. From the "wineventlog" you need to copy the processors section: 
`- decode_xml_wineventlog:
      field: event.original
      target_field: winlog`
2. Copy it to the processor section of the pipeline.
3. (Optional) You can duplicate the existing syslog pipeline in order to not harming another integrations.

Hopes it will help :)
> 2.
