### ISSUE TITLE
[Fortinet] Split fortinet integration based on products

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#1936]
Current the Fortinet integration covers log collection for Firewall, FortiMail, FortiManager, Fortinet Client and Endpoint. To follow the pattern of one package per product this fortinet package should be deprecated and new packages created.

- [ ] Fortinet FortiGate (Network Security Platform) - assuming "Firewall" is the same as FortiGate
- [ ] Fortinet FortiMail (Messaging Security Server)
- [ ] Fortinet FortiManager (Centralized Management Platform)
- [ ] Fortinet FortiClient (Advanced Endpoint Security)

#### References

- https://www.fortinet.com/content/dam/fortinet/assets/data-sheets/Fortinet_Product_Matrix.pdf

**Comment by legoguy1000** [comment]
@andrewkroh These PRs are ready for review.

**Comment by jamiehynds** [comment]
Closing - thanks to @legoguy1000
