### ISSUE TITLE
Deprecate Microsoft package

### ISSUE THREAD

**Issue by adriansr** [elastic/integrations#1937]
Legacy Microsoft package has been split into separate packages:
- Microsoft DHCP (https://github.com/elastic/integrations/pull/1793)
- Microsoft Defender for Endpoint (https://github.com/elastic/integrations/pull/1777)

Now the Microsoft package needs to be marked as deprecated.

Depends on https://github.com/elastic/integrations/issues/1900 to figure out our title guidelines for deprecated packages (see comment https://github.com/elastic/integrations/issues/1900#issuecomment-945889319).

**Comment by mtojek** [comment]
@adriansr I think we need to decide on the https://github.com/elastic/package-spec/issues/227 first. Would you share your thoughts regarding the timeline?

**Comment by andrewkroh** [comment]
Lacking closure on https://github.com/elastic/package-spec/issues/227, we have marked any packages that we are treating as deprecated with a `description` field that begins with `Deprecated.` For example:

https://github.com/elastic/integrations/blob/a69ce2a4f7196b6064b44296aea9303c261fedf7/packages/microsoft/manifest.yml#L5

https://github.com/elastic/integrations/blob/8359e92cbf339649139ea6cad396609369819d16/packages/zscaler/manifest.yml#L5
