### ISSUE TITLE
UpdatePackageStorage doesn't work anymore

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#196]
With latest changes in the package-storage, the mage target `UpdatePackageStorage` doesn't work anymore. It used the single target branch to compare and spot the differences between packages.

Now, the concept behind package-storage is different, there are no packages at the https://github.com/elastic/package-storage/tree/snapshot (which was the source of truth).

@ruflin any ideas how to solve the promotion? Previously, the script was able to present differences between particular revision. This is broken now.

**Comment by mtojek** [comment]
Another thought:

How can I easily find the latest deployed version of a package to any environment without navigating through them?

**Comment by ycombinator** [comment]
> How can I easily find the latest deployed version of a package to any environment without navigating through them?

What about using the snapshot registry API (with `?experimental=true` set)? Since the snapshot registry is backed by all three branches, it will "look" in all of them before returning the latest deployed version of a given package, yes?

**Comment by mtojek** [comment]
It should work, but it's a workaround. We will use two sources of knowledge (pushing to Git, pulling from the deployment release) and the latest set of packages may not be deployed to the registry. Not sure if we want to go this way.

Using the endpoint will not allow for showing differences between revisions. Such PRs are not easily reviewable (pushing all files as new ones, but fixing a typo in a single place).

**Comment by ycombinator** [comment]
Fair point, especially given that sometimes there can be a lag between when a package lands in a repo branch and when it actually gets deployed to the service. Long term I think we should exclusively use the service APIs for publishing, etc. but we're not there yet (and it's open to discussion of course). But for now, I agree that mixing the two methods could lead to unexpected results some times.

Perhaps then we have no choice but to check out all three branches of the git repo and search in each of them for the latest version? Not great but I can't think of a better solution.

**Comment by mtojek** [comment]
It will be a bit tangled implementation to review all three branches, but definitely doable. On the other hand if the current design involving 3 branches is deprecated in a month or three, maybe it's fair to plan ahead a reasonable solution.

I can fix the script, but would like to do this at most once ;)

**Comment by ycombinator** [comment]
I think we need to fix the script right now as it's already available for use and currently broken. If the package storage design is changed, we update the script accordingly again. It's not ideal, I know, but it's a buggy and unexpected experience for anyone who's trying to use this script today (this was me last week!).

**Comment by mtojek** [comment]
I will dive into this and try to adjust to the current design.

**Comment by ruflin** [comment]
I think with the introduction of the 3 branches, also where the diff might be useful has changed. Let me brainstorm:

The diff is really important in the integrations repo per PR for others to review. One release of a package will have multiple PRs. My expectation is that each change of a package should be in the future automatically pushed to snapshot branch  and it gets merged without a human review (PR or commit does not matter). This means, the diff is not helpful here. Same will happen when promoting to staging, no human interaction.

I think the diff will becoming interesting when pushing to production. What is the diff between the existing and the most recent package that should get released?

So my current thinking is, we should get rid of the diff from an integrations to package-storage script, but the script that will do the promotion to production, will need to be able to create the diff.

In addition to the above, using the changelog in the packages will help too.

**Comment by ycombinator** [comment]
Good point about the diff being more relevant at the time of _developing_ packages, not at the time of _publishing_ / _promoting_ them.

This is why I'd like us to abstract the publishing/promotion behind an API call in the future. For now, however, does that mean the `UpdatePackageStorage` script needs to simply make a PR to the `snapshot` branch of the `package-storage` repo(not a commit, so CI can run)?

**Comment by mtojek** [comment]
> For now, however, does that mean the UpdatePackageStorage script needs to simply make a PR to the snapshot branch of the package-storage repo(not a commit, so CI can run)?

Simple use case - I wanted to release MongoDB integrations as 0.1.1 version and had to jump over branches to find out if this version is already released, so it's not a simply copy over :)

**Comment by ycombinator** [comment]
@mtojek Correct, to summarize the last few comments I think there need to be two parts here:

1. Figuring out the latest version to validate that it is older than the one about to be promoted. For this, we will have to check out all three branches of `package-storage` and find the latest version.

2. Assuming the above version check passes, copying over the built contents of the package (results of `mage build`) to the `snapshot` branch of the `package-storage` repo via a PR. For this it is a simple copy over, right?

**Comment by mtojek** [comment]
Yes, that's the plan.

To simplify the idea I think I will disable temporarily comparing changes between revisions. It may require a deeper analysis (e.g. no package A in snapshot, package A v1.1 in staging, package A v.1.0 in production)

**Comment by ruflin** [comment]
@mtojek I wonder if we could solve the issue with finding which version is released in a different way. In the best case, you should not need to know. Lets assume you are developing package foo-1.3.2. The version 1.3.2 is in the package manifest and each PR you do against integrations is going to push to `snapshot` as `foo-1.3.2`. As soon as you are happy with the package, it is pushed to staging. In the optimal case, from here on you don't have to touch it anymore. This means the version of the package `foo` is bumped to 1.3.3 as soon as it is in staging so you can always rely on the version there. Unfortunately this causes other problems, what if staging comes back, finds a bug and wants changes again on 1.3.2? The solution here could be, that development on a new version should only start when it made it into production, becuase it should never be overwritten there ...

++ on your proposal above.

**Comment by ycombinator** [comment]
> This means the version of the package foo is bumped to 1.3.3 as soon as it is in staging so you can always rely on the version there. Unfortunately this causes other problems, what if staging comes back, finds a bug and wants changes again on 1.3.2? The solution here could be, that development on a new version should only start when it made it into production, becuase it should never be overwritten there ...

Correct me if I'm wrong but it sounds like you're suggesting that some automated process will be in charge of bumping up versions. I don't think anything should be in charge of automatically bumping up versions because this process needs human input — e.g. how can we assume a patch version bump each time? What if there were breaking changes requiring a major version version bump? Etc.

I think the version should be set by a human in the package manifest and then the package is published to the registry. Once it is in the registry — regardless of which stage/branch of it — the version is immutable. And so the version validation at package publishing time is necessary. FWIW, this is how other package registries like `npm` work too.

**Comment by ycombinator** [comment]
General comment: I feel like we are trying to reinvent the wheel here. Why not look at what existing registries (npm, gem, docker hub, etc.) are doing and follow their idioms unless something specific doesn't work for us?

**Comment by ruflin** [comment]
@ycombinator I think we are mostly on the same page. Agree that it is best to manually change to the next version, I assume that is also the case with others like npm etc. But if you keep the same version, it will just overwrite your existing one which is expected.

**Comment by ycombinator** [comment]
> But if you keep the same version, it will just overwrite your existing one which is expected.

It would be nice if this were only possible via a flag like `--force` or, since this is a mage target, I guess an environment variable like `FORCE_VERSION_OVERWRITE`.

**Comment by mtojek** [comment]
The original issue is fixed. Would you prefer to keep this thread open and rename the title?

**Comment by ruflin** [comment]
@mtojek As the initial problem is fixed, I suggest we close this and rather open a follow up issue for discussion.
