### ISSUE TITLE
Link in Kubernetes docs 404s

### ISSUE THREAD

**Issue by dedemorton** [elastic/integrations#2006]
The link to the example manifest in the [Kubernetes documentation](https://docs.elastic.co/en/integrations/kubernetes) is broken. I guess at some point, we created 2 manifests (and removed the original path):

![image](https://user-images.githubusercontent.com/14206422/138343819-bf5a7910-365e-4869-ad75-cad83ca1c7f4.png)

The docs need to be updated to reflect the new paths.

**Comment by ChrsMark** [comment]
@dedemorton can you highlight where is the broken link you are referring to? In [Kubernetes documentation](https://docs.elastic.co/en/integrations/kubernetes) I cannot find any reference 🤔 . 
If we verify this I can fix this along with https://github.com/elastic/integrations/pull/2657

**Comment by dedemorton** [comment]
Looks like the link has been removed in the latest version of the docs, so I will close this issue. Thanks!
