### ISSUE TITLE
Breaking changes are not documented

### ISSUE THREAD

**Issue by david-kow** [elastic/integrations#2028]
Kubernetes integration had a [breaking change](https://github.com/elastic/integrations/commit/a8f6c82ea2a131bfa8d20b70842cbcd405b89380) (default change) introduced between `0.14.0` and `0.14.1`. I believe this is currently not documented nor communicated to users in any way. It would be great if change log is exposed in Kibana and breaking changes are visibly marked. 

In this case, user updating patch version (which is expected to be safe) that didn't have `hosts` setting specified would get proxy part of their configuration not working. Also, I'm not sure how this plays with autoupgrades of integrations.

**Comment by ChrsMark** [comment]
Thank you for raising this @david-kow  and sorry for the delay here, we failed to triage this properly and missed that in our inbox.

I believe that the patch version change here was not correct and should be from `0.14.0` to `0.15.0`. But in general I don't think we have a well defined process to properly handle such cases in packages. 
In addition, I'm not sure how doable it is to expose the change log in Fleet UI but maybe this is something that @akshay-saraswat @mukeshelastic @jen-huang can answer better.

**Comment by akshay-saraswat** [comment]
@david-kow Thanks for submitting this issue. Please help me understand why this is deemed a breaking change. Is it preventing or resulting in a failure? From what I could comprehend from the linked PR, we are getting the default value from an environment variable instead of just relying on the default "localhost" in case of the first-time integration addition. The upgrade should retain the value as it was before the upgrade. If the existing user values are not retained after the upgrade, I think that's a bug and we should handle it differently. We should not just document it. Please let me know your opinion.

**Comment by david-kow** [comment]
Hey @akshay-saraswat, sorry to reply late, I've missed the notification email.

So from the user perspective - they have a manifest with config for their ES and Kibana (and possibly other apps). They might pin to a minor or major version, for example (this is pseudo-code, but it can be translated to actual ECK manifest):
```
Elasticsearch: 7.16.*
Kibana: 7.16.*
Elastic Agent: 7.16.*
Kubernetes integration: 0.*
```

I think that the natural expectation is that no matter if they deploy today or in a year from now, that manifest will result in successfully created ES, Kibana, Agent and correctly installed/running integrations. But with such a change it's not the case. Does this make sense? I'd be happy to chat more.

**Comment by joshdover** [comment]
> In this case, user updating patch version (which is expected to be safe) that didn't have `hosts` setting specified would get proxy part of their configuration not working. Also, I'm not sure how this plays with autoupgrades of integrations.

I think there's a pretty important distinction here in that the 0.14.0 version of this package wasn't yet GA (it was marked experimental) so breaking changes are expected.

I agree we need should have tooling for tracking (or preferably, preventing) breaking changes to integrations, but I'm not sure this case should be considered unexpected.

**Comment by joshdover** [comment]
Worth noting that changelogs are now displayed in Kibana
