### ISSUE TITLE
Promote activemq package to staging and production

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#2036]
The _Activemq_ package has never been promoted to staging or production. It's an oversight that has to be fixed.

![image](https://user-images.githubusercontent.com/14043218/138912566-22382bea-5ff7-4865-b5da-4808dd9e1e23.png)

**Comment by endorama** [comment]
promotion to **production**: https://github.com/elastic/package-storage/pull/2736
removal from **staging**: https://github.com/elastic/package-storage/pull/2737
