### ISSUE TITLE
Carbon Black - update logo

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#2042]
VMware have granted us permission to use their logo as part of our Carbon Black EDR integration. Can we please update the integration with the attached image

https://cdn.freelogovectors.net/wp-content/uploads/2020/04/carbon-black-logo.png

**Comment by adriansr** [comment]
The provided logo works poorly with our UI:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/15056957/146732880-97cc05dc-d250-4d58-9ff0-9f9dbfc02654.png">

and

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/15056957/146732941-18900a16-ce89-484c-bd32-605c98ee3fb3.png">

Any chance they can provide something more adequate? Also an SVG version will be much better than PNG as we don't support this natively and have to convert using a third party tool.

For now I will update with this logo as it's better than no logo at all.
