### ISSUE TITLE
Cisco package Needs sync with Beats module

### ISSUE THREAD

**Issue by adriansr** [elastic/integrations#2116]
There's a bunch of fixes to the Cisco module in Filebeat (esp. ASA and FTD) that haven't made their way into the cisco package:

- [ ] https://github.com/elastic/beats/pull/28325
- [ ] https://github.com/elastic/beats/pull/26879
- [ ] https://github.com/elastic/beats/pull/24744

Possibly more.

We should review the differences with the Filebeat module and update accordingly.

**Comment by legoguy1000** [comment]
#1740 exists but is probably out of date  with teh split of the packages into individual integrations and the other PRs.

**Comment by leehinman** [comment]
the #1583 commit has the elastic/beats#24744 changes in it, so that does not need to be backported.

**Comment by leehinman** [comment]
The #1891 commit has the elastic/beats#28325 changes in it, so that does not need to be backported.

**Comment by leehinman** [comment]
elastic/beats#26975 needs to ported to integration

**Comment by leehinman** [comment]
elastic/beats#29698 needs to ported to integration

**Comment by efd6** [comment]
It looks like the Cisco FTD package did not receive this.
