### ISSUE TITLE
[microsoft_dhcp] Handle DHCPv6 logs

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#2136]
I was testing the DHCP integration and had some feedback:

- It would be nice if the module could collect the DHCPv6 logs from `C:\Windows\System32\dhcp\DhcpV6SrvLog-*.log`.
- The default path of the integration does not match the case of what the service uses (`C:\Windows\System32\dhcp`). NTFS is case-sensitive, but the win32 api calls are not so it will work as is.
- The module adds the `forwarded` tag so you don't get `add_host_metadata`, but I want to know information about the server where the service is running. Perhaps the module can use `add_observer_metadata`? It doesn't look like it's safe to remove the `forwarded` tag since the ingest pipeline writes to `host.*` (you'd get mixed data in `host.*`).
- There are several events with `error.message` because the beginning of the log files have header. Perhaps those can be filtered or allowed to pass through the pipeline without an attempt to parse (and fail).
- `_conf` and `_tmp` should be removed on_failure too. We don't want that being indexed when a parse failure occurs.

<details>
<summary>Header parse failure:</summary>

```json
{
  "@timestamp": "2021-11-04T18:24:34.853Z",
  "_conf": {
    "tz_offset": "local"
  },
  "_tmp_": {
    "timestamp": " "
  },
  "agent": {
    "ephemeral_id": "4d0e7350-1cbb-4595-bbe8-e7116789e7cc",
    "hostname": "akroh-win2012",
    "id": "b3fb7d14-5c9a-4b73-8b37-5e3782e9f7cb",
    "name": "akroh-win2012",
    "type": "filebeat",
    "version": "7.16.0"
  },
  "cloud": {
    "account": {
      "id": "foo"
    },
    "availability_zone": "us-central1-a",
    "instance": {
      "id": "123",
      "name": "akroh-win2012"
    },
    "machine": {
      "type": "e2-standard-2"
    },
    "project": {
      "id": "foo"
    },
    "provider": "gcp",
    "service": {
      "name": "GCE"
    }
  },
  "data_stream": {
    "dataset": "microsoft_dhcp.log",
    "namespace": "default",
    "type": "logs"
  },
  "ecs": {
    "version": "1.12.0"
  },
  "elastic_agent": {
    "id": "b3fb7d14-5c9a-4b73-8b37-5e3782e9f7cb",
    "snapshot": true,
    "version": "7.16.0"
  },
  "error": {
    "message": [
      "date processor failed to convert the timestamp",
      "For input string: \\\"17\\tA lease was expired and DNS records for an expired leases have not been deleted.\\\""
    ]
  },
  "event": {
    "agent_id_status": "verified",
    "code": "17\tA lease was expired and DNS records for an expired leases have not been deleted.",
    "dataset": "microsoft_dhcp.log",
    "ingested": "2021-11-04T18:24:35Z",
    "kind": "event",
    "original": "17\tA lease was expired and DNS records for an expired leases have not been deleted.",
    "timezone": "+00:00"
  },
  "input": {
    "type": "log"
  },
  "log": {
    "file": {
      "path": "C:\\Windows\\System32\\DHCP\\DhcpSrvLog-Thu.log"
    },
    "offset": 487
  },
  "tags": [
    "preserve_original_event",
    "forwarded",
    "microsoft_dhcp"
  ]
}
```

</details>

**Comment by andrewkroh** [comment]
I wasn't actually serving any DHCP requests, but I started up the service. This at least shows the header at the start of the file.

[DhcpV6SrvLog-Thu.log.txt](https://github.com/elastic/integrations/files/7486333/DhcpV6SrvLog-Thu.log.txt)
[DhcpSrvLog-Thu.log.txt](https://github.com/elastic/integrations/files/7486334/DhcpSrvLog-Thu.log.txt)

**Comment by jamiehynds** [comment]
@pemontto might be of interest :)
