### ISSUE TITLE
[Snyk] Parse the snyk.projects field

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#2137]
We currently include a number of fields within snyk.projects including name, id, packagemanager, source, url and targetfile. These fields are valuable to Snyk users and should be properly parsed. 

@michaelhyatt has used runtime fields to parse the fields, but our ingest pipeline needs to be updated. Michael has also provided a screenshot and sample document:

![image (1)](https://user-images.githubusercontent.com/62879768/140524358-ff34537d-f3b4-4b76-a8c3-ae4ea851bf80.png)

[snyk_doc_1.txt](https://github.com/elastic/integrations/files/7486595/snyk_doc_1.txt)

**Comment by michaelhyatt** [comment]
@papicella ^^

**Comment by legoguy1000** [comment]
I created #2162 to migrate the Snyk filebeat module to the agent integration.  What kind of parsing is wanted for this field.  Since this is an array of objects, I'm curious what runtime fields are being used?

**Comment by jamiehynds** [comment]
Thanks @legoguy1000! @michaelhyatt can you share which runtime fields you used, and whether those fields were based on ECS fields?

**Comment by P1llus** [comment]
I see the only issue here is that projects is an array of objects, so we cannot put them directly under snyk.*, because there might be multiple projects involved :(
