### ISSUE TITLE
Daily job "7.16" should ignore packages with ^8.0.0  compatibility only

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#2144]
Spotted during community/build manager duty:

It seems that the daily job "7.16" includes also `ti_*` packages which are compatible only with 8.0.

job: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/master/1147/pipeline/

cc @jsoriano

**Comment by jsoriano** [comment]
Ah yes, thanks for opening the issue, adding it as part of https://github.com/elastic/integrations/issues/2134.
