### ISSUE TITLE
Socket metrics in System integration in Fleet

### ISSUE THREAD

**Issue by JaoKlintone** [elastic/integrations#2150]
Please add `socket metrics` to `System` integration like they exist in metricbeat agents: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-system-socket.html
`Socket_summary` metrics are already added but not `socket` metrics.

![image (29)](https://user-images.githubusercontent.com/77189755/141128470-9732921f-0127-42a8-ba41-1dbfdb6a0d00.png)
![image (28)](https://user-images.githubusercontent.com/77189755/141128475-4f287313-1fc1-4cce-8228-6c8d517c2870.png)

**Comment by andrewkroh** [comment]
I think using the Endpoint integration would provide richer, more reliable socket data. The Metricbeat implementation depends on polling so it can miss should lived connections. Meanwhile the Endpoint integration hooks into the OS and does not miss short-lived connection and it is implemented on more OSes than Metricbeat system/socket.

**Comment by andrewkroh** [comment]
And another alternative is the osquery integration. It can collect socket data too, but Endpoint is going to provide the most rich data.

**Comment by andrewkroh** [comment]
Given we have better options I think we should close this and steer users in those directions.
