### ISSUE TITLE
[Enhancement] Move Custom Logs integration to GA

### ISSUE THREAD

**Issue by seang-es** [elastic/integrations#2195]
We've had requests from users to move the Custom Logs integration from experimental state to GA.  I haven't found it on any of the other lists of integrations slated for GA, so wanted to make sure it's on the radar.

**Comment by pozezanc** [comment]
Hi - Johnson and Johnson has requested an update on our plans to transition custom logging in the Elastic Agent to GA.  Anything I can share with them on our criteria or planning?
