### ISSUE TITLE
Recorded Future

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#2204]
### Description
The Recorded Future Intelligence Platform delivers an end-to-end view of threats across the enterprise, from attacker to midpoint to target. It includes a unique combination of feeds, open source intelligence, dark web and human-generated intelligence, and proprietary technical sources -- all delivered on a centralized platform and integrated directly into dozens of third-party security solutions.

This integration will replace our current RF integration. 

### Architecture
Our current integration does not follow RF best practice for data ingestion. Their preferred approach is to ingest a CSV file periodically (which can be up to 700mb). Based on initial research, our current ingest pipeline may be re-used as part of this integration. 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by jamiehynds** [comment]
@adriansr are we still on track to update the RF integration in 8.1 to support their supported ingest method? (for when you're back from PTO!)

**Comment by MarkSettleES** [comment]
@adriansr and @jamiehynds, will 8.1 introduce an integration for threat intelligence from Recorded Future?
