### ISSUE TITLE
Adoption of data streams

### ISSUE THREAD

**Issue by kvch** [elastic/integrations#2218]
[Data streams](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-streams.html#data-streams) are used for storing append-only time-series data. The advantage of using them is that it provides a single name to access all data in the backing indices. There is no need for loading/handling aliases. Read and write requests are automatically forwarded to the appropriate indices.

One of the limitations we have to address is that they **only support create operation type**. However, some integrations/modules rely on index operation to update existing documents in indices. In Beats, we are introducing it in https://github.com/elastic/beats/pull/28450. Thus, modules will insert new documents instead of updating existing ones.

With integrations, we have to discuss how to solve this problem.

#### Always use indices

All integrations send data to regular indices, not leveraging the extra features data streams provide. This is basically the current approach (if I understood correctly).

#### Opt-out of data streams

Alternatively, we could default to sending events to data streams. But integration developers have a way to opt-out, if the documents have to be updated later.

#### Always use data streams

We could also use only data streams. If a document has to be updated, we can either [update by query](https://www.elastic.co/guide/en/elasticsearch/reference/master/use-a-data-stream.html#update-docs-in-a-data-stream-by-query) or [update the document directly in the backing index](https://www.elastic.co/guide/en/elasticsearch/reference/master/use-a-data-stream.html#update-delete-docs-in-a-backing-index). However, it requires a bit more work on our side.

@ruflin @P1llus @SpencerLN

**Comment by ruflin** [comment]
Elastic Agent is designed around the [data stream naming scheme](https://www.elastic.co/blog/an-introduction-to-the-elastic-data-stream-naming-scheme) so all data shipped by Elastic Agent its processes goes into data streams. This is something we enforce today I'm aware of only one exception to this in the endpoint case for transforms.

I'm taking "Always us data streams" as the basis of shipping data. What I would like to better understand is what are the scenarios where a different op_type is needed. Can this be done in Elasticsearch itself with transforms or similar?

@andrewkroh FYI

**Comment by andrewkroh** [comment]
`op_type: index` is used in two Filebeat modules - threatintel and synk. The threatintel module has been updated (https://github.com/elastic/beats/pull/29014) in master to no longer use `op_type` which matches up with how it operates in Fleet. Synk has not been changed, but AFAIK there's nothing stopping us from removing op_type from that module too. Consumers of the data will need to adjust their queries to account for updates being include as separate documents.

#### Remaining op_type uses in master

- https://github.com/elastic/beats/blob/17745e25ed0be07e8905734ad2443ef319837452/x-pack/filebeat/module/snyk/audit/config/config.yml#L75

- https://github.com/elastic/beats/blob/17745e25ed0be07e8905734ad2443ef319837452/x-pack/filebeat/module/snyk/vulnerabilities/config/config.yml#L98

**Comment by kvch** [comment]
I have already updated snyk module in my PR in Beats:
- https://github.com/elastic/beats/pull/28450/files#diff-868e65be6e84f4a10f34349c5af4e1bf46d1ba2706508124748c322e10ceb7cd
- https://github.com/elastic/beats/pull/28450/files#diff-4fc6681ad28077519be73dab96ee4ff9fb0b7fc4b5c6aff54fab0b668e7f5e42

**Comment by andrewkroh** [comment]
Thanks @kvch . I didn't meant to distract from the conversation around `op_type` usage in integrations (I thought this was an elastic/beats issue 🤦 ).

In summary, what we've done with Fleet integrations that previously used `op_type` in Beats was to adopt the "Always use data streams" solution and append updates as new documents. The trade-off being that queries are more difficult to construct because you want only return the most up-to-date document (e.g. you can sort by ingest time and then collapse based on `event.id`). On the plus side, you now have the full history of updates made to the data over time.

**Comment by SpencerLN** [comment]
As a consumer of Filebeat, I am left wondering what the recommended approach is for ingesting data sources where we do not need or want duplicate data ingested and only want the most current state of a given entity. 

An example use-case of ours that comes to mind is GitHub data. We currently ingest Issue/PR data from several GitHub repositories on an hourly schedule and use `op_type: index` to replace/update the existing documents each time the job runs. This allows us to view the current state of the issues/PRs and create visualizations that enable us to gain insights into our current workload/progress/etc. It isn't clear how we would update some of these visualizations where we only want to see the state of the most recently ingested document for a given Issue.

A potential approach that we have discussed is using a [Latest Transform](https://www.elastic.co/guide/en/elasticsearch/reference/current/transform-overview.html#latest-transform-overview) to create a second index that has the "current state" view. That said, this seems like a significant amount of additional work and creates some other questions:
- How do we separate the "raw" data from the "current state" data? Perhaps separate indices (`raw-github-issues` vs. `github-issues`)
- What happens with the "raw" data datastream? How does it get cleaned up so we aren't storing unneeded data?
- How do we create/maintain/monitor the transforms for all of the current/future data sources that need this approach (we currently have 14 using `op_type: index`)?
- etc.

**Comment by ruflin** [comment]
@jpountz Pulling you in here as the problems that @SpencerLN describes are common across a few use cases. Maybe you have some ideas?

**Comment by jpountz** [comment]
Good question.

There have been a few discussions about this in the past in the context of metrics data, where there was an intuition that TSDB could help solve this problem. For instance, it's a common use-case for PromQL to retrieve recent data points per time series I believe. The way that TSDB uses index sorting makes it easy to filter the last data point per time series, something that cannot be done easily with data streams in general short of collecting all the data.

This GitHub issues/PRs example is interesting because it's not a metrics dataset. I'll chat with the analytics team to get more thoughts, ie. is it something that we can make cheap at query time like with TSDB, or is a separate index the best approach, and then what are best practices.

**Comment by kvch** [comment]
In 8.0 we are only supporting data streams in Beats as the new major version is coming out rather soon. But in a later release, we are open to adding better support for updating existing documents in indices.

The suggested workaround in the meantime is to use your own index for storing data that is constantly updated. To load the same fields as Beats load, export the template loaded by the Beat and edit the template so it does not create data streams but regular indices:
1. Remove the key-value pair `"data_stream"` from the JSON
2. Edit list of `"index_patterns"` so it matches your indices

Once you have your template file, you can load it using Beats `setup.template.json.*` options. Also, set the option `index` either under the output or module, so Beats knows what index it should send events to. We also suggest you configure ILM for your indices using the UI in Kibana.

**Comment by jpountz** [comment]
After discussing with @jimczi about this, I realize I've probably been making assumptions about what you are trying to do with the GitHub integration. Is there somewhere I can read more about it? What does the data model look like today and what sort of questions do you want to be able to answer with the data?

For instance, if you only care about aggregating at the issue/PR level, then you will want to have issues/PR as documents. And while your documents could have a `@timestamp` that corresponds to the last edit, this wouldn't be a time-based index, it would be a regular index that just happens to have a `@timestamp` field and that is more similar to what we're seeing with the Enterprise Search solution.
