### ISSUE TITLE
Fill in known type and dataset value into fields.yml

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#226]
For most datasets inside a package, we know in advance the type and the dataset value. But currently we do not publish it in the fields.yml: https://github.com/elastic/integrations/blob/master/packages/nginx/dataset/access/fields/base-fields.yml#L1 Instead this could look as following:

```
- name: data_stream.type
  type: constant_keyword
  description: Data stream type.
  value: log
- name: data_stream.dataset
  type: constant_keyword
  description: Data stream dataset.
  value: nginx.access
```
 
The benefit of prepopulating is that it would ensure no wrong values get put into it and if incompatible data already exists, Ingest Manager would rollover the data stream when the package is installed.

An alternative idea is that Ingest Manager adds it as all the info already exists in the manifest.

**Comment by mtojek** [comment]
@ruflin is this still valid call? Should we prioritize it?

**Comment by ruflin** [comment]
I think it still applies as we didn't do it in Ingest Manager either. Would be great to get this in.
