### ISSUE TITLE
Cisco Umbrella Enhancements

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#2295]
Our current Umbrella integration is currently experimental, and requires some enhancements before we move towards beta/GA. Cisco managed buckets and V6 logs are now supported, and have been removed from the original blockers list. 

Remaining items:

- **Audit logs:** the integration currently supports Proxy, Cloud Firewall, IP Logs and DNS logs. The [Audit log](https://docs.umbrella.com/deployment-umbrella/docs/admin-audit-log-report) records changes made by admins within Umbrella and should be added to our integration. 

- **AWS Role Support** add AWS Role support for authentication within our [fileset settings](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-cisco.html#_umbrella_fileset_settings).

**Comment by LaZyDK** [comment]
Is this not fixed by https://github.com/elastic/integrations/pull/2462 ?

**Comment by jamiehynds** [comment]
@LaZyDK the support for Cisco-managed buckets is addressed, but will still need to add other items such as Version 6 logs, audit logs and AWS Role Support. We'll aim to move this to Beta in the short-term now that Cisco managed buckets are supported.

**Comment by legoguy1000** [comment]
Version 6 logs was added by @P1llus at the same time as the Cisco managed buckets.  V6 just added a couple additional fields to the proxy logs. I just opened PR for the Audit logs.
