### ISSUE TITLE
Sync PANW integration with Beats module

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#2306]
Our [Beats module](https://github.com/elastic/beats/tree/master/x-pack/filebeat/module/panw/panos/ingest) supports several PANW event types, including hip match, userid and Global Protect. However, these additions were not reflected in our PANW agent integration, which is still limited to Threat and Traffic logs. 

Can we sync the Beats module and integration, so they support the same log types?

**Comment by andrewkroh** [comment]
There was a bug fix in https://github.com/elastic/beats/pull/29154 that is also missing IIUC.

History: https://github.com/elastic/integrations/commits/main/packages/panw/data_stream/panos/elasticsearch/ingest_pipeline
