### ISSUE TITLE
[8.0]: Linux integration is not available on 8.0 Snapshot.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#2321]
**Kibana version:**  8.0 Snapshot Kibana Cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
BUILD: 48594
COMMIT: ad3660f3acbfe6eb809d869b908221edf2846313
```

**Preconditions:**
1. 8.0 Snapshot Kibana Cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Integrations tab and search Linux integration.
3. Observe Linux integration is not available.

**Expected Result:**
Linux integration was available till last 8.0 Snapshot build and also available on 7.16.0.

**Screenshot:**

![13](https://user-images.githubusercontent.com/77374876/145156128-b01e13a9-59a9-477e-8189-3e52fa4db451.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed and mention to @jen-huang 

CC: @EricDavisX

**Comment by fearful-symmetry** [comment]
So, I'm assuming this is because the linux package never got promoted to production? Let me try putting it in staging at least.

**Comment by jen-huang** [comment]
@manishgupta-qasource Thank you for correctly identifying that this is an integrations issue. There is no need to tag me in this case, you may tag @masci instead.

**Comment by EricDavisX** [comment]
@fearful-symmetry presuming this got pushed to staging (and/or production) - @amolnater-qasource would you please re-test?  Thank you.

**Comment by fearful-symmetry** [comment]
Looks like it, yah.

**Comment by amolnater-qasource** [comment]
Hi @fearful-symmetry 
We have revalidated this issue on 8.0 Snapshot and found `Linux Metrics` integration available now.

**Screenshots:**
![15](https://user-images.githubusercontent.com/77374876/149890932-73669b43-b7e6-421b-8dd1-584e0c59d7e1.JPG)

**Build details:**
BUILD: 49040
COMMIT: 155e06787e48de9a8de4345d86a826e95edf32ec

Hence we are **closing** this issue.
Thanks

**Comment by dikshachauhan-qasource** [comment]
Hi @masci 

While performing testing on 8.0 rc2 build on onprem environment, we observed Linux integration is not available under integrations tab.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/150331420-ef829c0b-30e2-4596-86c5-c325572b998e.png)

![image](https://user-images.githubusercontent.com/72375798/150331590-25a9d45b-9844-4aea-8dc4-8cf2c7950d95.png)

**Build details:**
BUILD 49092
COMMIT 93d9bd54452711c449fe07e4f23c43a4a0e519c3

Further, later build was available on cloud too and we have validated there too. However, could not find Linux Integration there too.

Hence, we are re-opening it.

Thanks
QAS

**Comment by EricDavisX** [comment]
Quick guess... is that the BC used more recently is pulling from the Production group, and the noted version is not pushed to Production yet.  I'll ping Alex to see if they saw this.

**Comment by fearful-symmetry** [comment]
Yep, forgot to promote to prod. PR here: https://github.com/elastic/package-storage/pull/3328

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource you can retest I assume, let's do that and close this out. thanks

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX @fearful-symmetry 

Thanks for updates and fixing above merges.

We are now able to fetch linux integration under Integrations tab on 8.0 RC2 BC2 build.

Build details:
BUILD: 49157
COMMIT: 01d4a6a088cae588e542623a47054bc76cfb2a6d

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/151321878-96b8bdd5-5628-49a1-9925-083bf5c8e925.png)

Hence, closing this out.

Thanks
QAS
