### ISSUE TITLE
Tenable.io

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#2338]
### Description
Tenable.io allows security and audit teams to share multiple Nessus, Nessus Agent, and Nessus Network Monitor scanners, scan schedules, scan policies, and scan results among an unlimited set of users or groups. Tenable is comparable to Tenable.sc in terms of functionality, but based in the cloud and delivered as SaaS. 

### Architecture
Tenable.io provides an API - https://developer.tenable.com/docs/get-started

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by LaZyDK** [comment]
Any updates to this one? :)

**Comment by NateUT99** [comment]
Is this still actively being worked on? Would love to be able to take advantage of Kibana for vulnerability reporting.

**Comment by jamiehynds** [comment]
@LaZyDK @NateUT99 we'll be starting on the Tenable.io shortly. We were blocked until recently, as we needed to modify our httpjson input to cater for the way Tenable's API works. I'll update you both as soon as we have something to share.
