### ISSUE TITLE
Kubernetes - audit_logs datastream: add dashboard and tests

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#2343]
Related to the PR: https://github.com/elastic/integrations/pull/2317

For more details see the comment: https://github.com/elastic/integrations/pull/2317#pullrequestreview-832430436

Tests:
- for adding system tests it is needed to adjust kind-config to enable audit logs and add audit policies -it should be smth similar to https://github.com/elastic/elastic-package/pull/322/files

**Comment by tetianakravchenko** [comment]
Tests:
1. Add audit policy to the https://github.com/elastic/elastic-package, and add audit policy to kind-config - branch https://github.com/elastic/elastic-package/compare/main...tetianakravchenko:kind-enable-audit-logs?expand=1
2. Add test config:
```
input: filestream
data_stream:
  vars:
    paths:
      - "/var/log/kubernetes/kube-apiserver-audit.log"
```
getting an error:
```
Error: error running package system tests: could not complete test run: could not add data stream config to policy: could not add package to policy; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"Input template not found, unable to find input type filestream"}
```
error seems to come from https://github.com/elastic/kibana/blob/9df685acbe15ce97cc3882d89a0d6b3c1a41500e/x-pack/plugins/fleet/server/services/package_policy.ts#L936

**Comment by ChrsMark** [comment]
We should check if after the changes described at https://www.kubernetes.dev/blog/2022/05/25/contextual-logging/ we need to adjust our side too.

In addition, maybe we can get advantage of `Structured logging` described there.
