### ISSUE TITLE
System integration for Logs and Metrics is not configured to pickup Mac OS logs

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/integrations#2346]
The system logs from Mac OS are available in `/var/log/system.log`.  The 7.16.1 System integration looks in logs appropriate for Linux (the version of Debian I have in a VM at least), but not `/var/log/system.log`.  If this integration is meant to collect data from both server and desktop machines, then I think that the defaults should include Mac and Windows (I don't have any idea how Windows works for logging, and probably the Elastic Agent deploys Winlogbeat and this is not an issue).  

Note: Metrics works fine out of the box.

**Comment by DanRoscigno** [comment]
@ruflin can you help me get this fixed please?

**Comment by DanRoscigno** [comment]
still an issue in 8.1.2

**Comment by DanRoscigno** [comment]
Hi @ruflin 
Just update the paths.  It would be good to add a test to check to see if the dashboards work.  I have verified that the syslog dashboard is good once the path is added, but I have not verified the others.

**Comment by ruflin** [comment]
@cmacknz @jlind23 This falls into your team as it is a change the likely has to happen in the system package.

**Comment by michalpristas** [comment]
PR merged, not sure if this should be closed, windows system logs are mentioned

**Comment by cmacknz** [comment]
We use the winlog input type on Windows, I believe we can close this.

https://github.com/elastic/integrations/blob/main/packages/system/data_stream/system/agent/stream/winlog.yml.hbs
