### ISSUE TITLE
[tenable_sc] Set specific User-Agent for requests

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#2348]
The Tenable.sc integration needs to set a specific User-Agent string in it's request as per https://developer.tenable.com/docs/user-agent-header.

`Integration/1.0 (Elastic; Tenable.sc; Build/0.1.0) Elastic-Filebeat/8.1.0 (darwin; amd64; 9b893e88cfe109e64638d65c58fd75c2ff695402; 2021-12-15 13:20:00 +0000 UTC)`

where

`Tenable.sc` is the title of our integration within our ecosystem,
`0.1.0` is the current version of the Elastic Tenable.sc integration, and
`Elastic-Filebeat/8.1.0 (darwin; amd64; 9b893e88cfe109e64638d65c58fd75c2ff695402; 2021-12-15 13:20:00 +0000 UTC)` is Filebeat's standard UA string.

References

- https://developer.tenable.com/docs/user-agent-header

Related

- Depends: https://github.com/elastic/beats/issues/29453
- Depends: https://github.com/elastic/kibana/issues/121310 (so we don't have to hard-code the integration version, but we could proceed without it and use the feature when it's available)

**Comment by adriansr** [comment]
@andrewkroh I understand this was closed by https://github.com/elastic/integrations/pull/2718
