### ISSUE TITLE
Remove `dataset` field from logs package

### ISSUE THREAD

**Issue by jen-huang** [elastic/integrations#238]
With the changes done to change `dataset.*` fields to `data_stream.*` in https://github.com/elastic/kibana/pull/74414 and https://github.com/elastic/beats/pull/20420, we should remove the `dataset` field definition in logs package:

https://github.com/elastic/integrations/blob/master/packages/log/dataset/log/manifest.yml#L19
https://github.com/elastic/integrations/blob/master/packages/log/dataset/log/agent/stream/stream.yml.hbs#L7

While grepping, I found one other instance of a similar field in netflow package, but I'm not sure if this needs to be removed as it's part of ECS fields:
https://github.com/elastic/integrations/blob/master/packages/netflow/dataset/log/fields/ecs.yml#L940

**Comment by ruflin** [comment]
I'm trying to fix this in https://github.com/elastic/integrations/pull/234

For the ECS fields in netflow: This is expected.

**Comment by jen-huang** [comment]
Closing as #234 is merged.
