### ISSUE TITLE
OPNsense/pfSense Integration

### ISSUE THREAD

**Issue by a3ilson** [elastic/integrations#2401]
Thanks for adding the pfSesne Integration! It is obvious the work from from @pfelk was copied without credit...would you like the @pfelk repo transferred too - you can certainly maintain that project until you've replicated within the pfSense integration.

**Comment by legoguy1000** [comment]
@a3ilson I created the integration and 100% started from your project. I used your project for my own at home elk deployment a year or 2 ago and contributed a little to the project during the conversion to ECS. I went from there with additional modifications.

**Comment by a3ilson** [comment]
Great! Looking forward to it graduating out of the experimental phase and redirecting @pfelk this way. I would ask that you include @OPNsense support. After the initial grok, the message for both pf and @opnsense is the same albeit I wish @pfSense would migrate away from their legacy syslog (e.g. @syslog-ng).

**Comment by legoguy1000** [comment]
@a3ilson If u can provide me samples of open sense logs, I have no problem updating the integration to make it compatible. I just focused on pfsense since that's all I have to test with. Also if u can provide sample captive portal logs from pfsense, I'll add that to the the ingest pipeline too. Again I don't have that enabled to test which is why I didn't add it. I will also look at the php-fpm logs since I can get those my my firewall.

**Comment by legoguy1000** [comment]
I would reopen this to track the enhancements you'd like.

**Comment by a3ilson** [comment]
Below are OPNsense syslog-ng logs being sent to an Elasticstack:

```
<134>Jan 1 02:21:38 firewall.opnsense.net filterlog[97530]:
<134>Dec 31 22:02:55 firewall.opnsense.net filterlog[15307]:
<190>Dec 31 22:06:16 firewall.opnsense.net dhcpd[40152]:
<30>Dec 31 22:06:33 firewall.opnsense.net unbound[75499]:
```
* The contents after the colon are exactly the same as pfSense. The first grok pattern is the only one that has to factor the various differences (i.e. the optional grok parameters).

@pfELK's GROK pattern for pfSense and OPNsense:
```
<%{POSINT:[log][syslog][priority]}>?(%{INT:[log][syslog][version]}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{SYSLOGHOST:[host][name]}\s+)?%{PROG:[process][name]}\s*?(\[)?%{POSINT:[process][pid]}(\]:)?\s*(\-\s*\-)?\s*%{GREEDYDATA:filter_message}
```

It's a bit messy but it parses all pfSense and OPNsense output options. However, to parse Suricata (pfSense only) that are being sent via syslog-ng, you'll need the following grok pattern (Suricata via OPNsense works fine but pfSense requires syslog-ng as the Suricata logs become truncated [RFC5424/RFC3164 specify the length of messages])
```
<%{POSINT:[log][syslog][priority]}>?(%{INT:[log][syslog][version]}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{SYSLOGHOST:[host][name]}\s+)?%{PROG:[process][name]}\s*?(\[)?(%{POSINT:[process][pid]}(\]:)?)?\s*(\-\s*\-)?\s*%{GREEDYDATA:filter_message}
```
* Suricata logs being sent via syslog-ng do not contain the [process][pid] element.
* Example Suricata log being sent via pfSense & syslog-ng: ```<13>Dec 30 15:03:18 pfsensevc suricate: {.......```

**Comment by legoguy1000** [comment]
@a3ilson draft PR opened.  Add TCP/TLS support for OPNsense and php-fpm logs.  If u can send captive portal logs, I can add that too.

**Comment by a3ilson** [comment]
Captive logs for both pfSense and OPNsense are similar with the exception of the syslog message header (i.e. pfSense message log formats).

pfSense
```
<166>Jan 1 04:05:23 logportalauth[67572]:
```
* The initial message may change due to pfSense optional message log outputs (e.g. hostname and timestamp)

OPNsense
```
<165>Jan 1 03:45:14 firewall.opnsense.dev captiveportal[68837]:
```


The remaining of the messages/logs are the same and both parse with the same grok pattern

**Comment by fabiogermann** [comment]
@legoguy1000 can I help in some way? I know a few people that would be thrilled to see this update.

**Comment by legoguy1000** [comment]
> @legoguy1000 can I help in some way? I know a few people that would be thrilled to see this update.

What piece specially, the OPNsense support?

**Comment by a3ilson** [comment]
## pfSense 
pfSense uses three different logs outputs
- rfc3164 (default)
- rfc5424 with rfc3339 micro precision timestamp
- syslog-ng 
## OPNsense
OPNsense uses two different log outputs
- syslog-ng (default)
- rfc5424 - added with v22+

## Other comments
After the initial syslog messages, the remaining program specific messages all parse the same (I.e. same grok pattern). Ideally @pfsense should transition to syslog-ng but until then multiple options are needed to parse ask the variations. 

Within the past few weeks the @pfelk project added nginx enrichment (grok) with dashboards.

looking forward to seeing OPNsense being supported and this module maturing.
