### ISSUE TITLE
[github] Unknown parameter include=all on Github Enterprise

### ISSUE THREAD

**Issue by samjo-nyang** [elastic/integrations#2461]
https://github.com/elastic/integrations/blob/master/packages/github/data_stream/audit/agent/stream/httpjson.yml.hbs#L32

This sends include=all query string to Github Enterprise servers as follows:
```
Jan  4 04:27:12 <censored> haproxy[14135]: <censored>:48927 [04/Jan/2022:04:27:12.045] https_protocol~ web_unicorns/localhost 0/0/0/20/20 404 1061 - - ---- 154/151/1/1/0 0/0 {<censored>||Elastic-Filebeat/7.16.2 (linux; amd64; 3c518f4d17a|TLSv1.3} "GET /api/v3/orgs/<censored>/audit-log /api/v3/orgs/<censored>/audit-log?include=all&order=asc&per_page=100&phrase=created%3A%3D%3E20220104T03%3A27%3A11%2B0000"
```
However, there are no such query option in Github Enterprise.
https://docs.github.com/en/enterprise-server@3.3/rest/reference/orgs#get-audit-log

It makes 404, so Github Audit integration cannot be used with Github Enterprise server.

Current Elastic Version: 7.16.2
Current Github Audit Integration Version: 0.2.0

**Comment by legoguy1000** [comment]
Correct. This integration was not tested against GitHub enterprise server and was not expected to work with Enterprise Server as the backend is different from public GitHub.

**Comment by andrewkroh** [comment]
We could add a note to the integration's readme to highlight that this is not compatible with the Github Enterprise server.
