### ISSUE TITLE
[Question]: MySQL and Redis integration not available for Elastic Agent only.

### ISSUE THREAD

**Issue by samratbhadra-qasource** [elastic/integrations#2467]
**Question:**

The MySQL and Redis integration is not available for Elastic Agent only however both of the integration is available for Beats only. As the integrations is not available for Elastic Agent, user is not able to add the integrations.
So, could you please let us know if this is expected behavior.

**Screenshot:**

- MySQL and Redis integration not available on Elastic Agent only.

![Screenshot (439)](https://user-images.githubusercontent.com/84007952/147471396-d4dff129-f646-4c0b-8e43-8ae8e7aac88d.png)

![Screenshot (442)](https://user-images.githubusercontent.com/84007952/147471669-069bf02c-4cd0-433b-9ffa-8c938a8570ac.png)

- MySQL and Redis integration available on Beats only.

![Screenshot (441)](https://user-images.githubusercontent.com/84007952/147471456-a1a9e2b6-711f-4bc7-9470-6ae6bd634658.png)

![Screenshot (438)](https://user-images.githubusercontent.com/84007952/147471461-3057d9af-9ceb-4b8a-aae3-31c1f3364b50.png)

**Comment by jen-huang** [comment]
Integration availability is not a Fleet UI issue. Transferred to integrations repo and tagging @elastic/integrations-platforms   team.

**Comment by kaiyan-sheng** [comment]
Hello @samratbhadra-qasource, what version of elastic cloud are you using? I have a test environment for 7.16.1 and I'm able to see both MySQL and Redis integrations for the agent:
<img width="1200" alt="Screen Shot 2022-01-04 at 2 54 01 PM" src="https://user-images.githubusercontent.com/14081635/148128919-fd327db3-617a-4aa2-a020-1f804bab781a.png">

**Comment by samratbhadra-qasource** [comment]
Hi @kaiyan-sheng, 
I have tested this issue on 8.0.0-Snapshot environment and this issue is still occurring. Please find below the testing details:

**Build Details:**
```
VERSION: 8.0.0-SNAPSHOT
BUILD: 48889
COMMIT: bacb608a62bbea2b732c5e704c450a1b40c66bc1
```
**Screen-Recording:**

https://user-images.githubusercontent.com/84007952/148163999-1bd4ba5c-4854-4081-9c4a-469938b6b47f.mp4

Please let us know if anything else is required from our end.
Thanks!

**Comment by kaiyan-sheng** [comment]
Thanks! I was able to reproduce this issue. Looking at the package registry endpoints, MySQL and redis are missing the kibana version 8.0.0 from the prod and staging endpoint.
For example https://epr-snapshot.elastic.co/search?package=mysql returns
```
[
  {
    "name": "mysql",
    "title": "MySQL",
    "version": "1.2.1",
    "release": "ga",
    "description": "Collect logs and metrics from MySQL servers with Elastic Agent.",
    "type": "integration",
    "download": "/epr/mysql/mysql-1.2.1.zip",
    "path": "/package/mysql/1.2.1",
    "icons": [
      {
        "src": "/img/logo_mysql.svg",
        "path": "/package/mysql/1.2.1/img/logo_mysql.svg",
        "title": "logo mysql",
        "size": "32x32",
        "type": "image/svg+xml"
      }
    ],
    "policy_templates": [
      {
        "name": "mysql",
        "title": "MySQL logs and metrics",
        "description": "Collect logs and metrics from MySQL instances"
      }
    ],
    "conditions": {
      "kibana": {
        "version": "^7.14.0 || ^8.0.0"
      }
    },
    "owner": {
      "github": "elastic/integrations"
    },
    "categories": [
      "datastore"
    ]
  }
]
```
But in production endpoint https://epr.elastic.co/search?package=mysql :
```
[
  {
    "name": "mysql",
    "title": "MySQL",
    "version": "1.1.0",
    "release": "ga",
    "description": "This Elastic integration collects logs and metrics from MySQL instances",
    "type": "integration",
    "download": "/epr/mysql/mysql-1.1.0.zip",
    "path": "/package/mysql/1.1.0",
    "icons": [
      {
        "src": "/img/logo_mysql.svg",
        "path": "/package/mysql/1.1.0/img/logo_mysql.svg",
        "title": "logo mysql",
        "size": "32x32",
        "type": "image/svg+xml"
      }
    ],
    "policy_templates": [
      {
        "name": "mysql",
        "title": "MySQL logs and metrics",
        "description": "Collect logs and metrics from MySQL instances"
      }
    ],
    "conditions": {
      "kibana": {
        "version": "^7.14.0"
      }
    },
    "owner": {
      "github": "elastic/integrations"
    },
    "categories": [
      "datastore"
    ]
  }
]
```
I will create a PR to promote MySQL and redis integrations and that should solve this issue.

**Comment by kaiyan-sheng** [comment]
https://github.com/elastic/package-storage/pull/3226
https://github.com/elastic/package-storage/pull/3228

**Comment by samratbhadra-qasource** [comment]
Hi @kaiyan-sheng,
We have revalidated this issue on the latest 8.1.0-BC5 build and found that the issue is **fixed** now. Please find below the testing details:

- MySQL and Redis integration is available for Elastic Agent only.

**Screen-Recording:**

https://user-images.githubusercontent.com/84007952/156344381-35bf2c19-a554-49ba-a254-16b4cf6e3767.mp4

**Build Details:**
VERSION: 8.1.0-BC5
BUILD: 50459
COMMIT: 23423b0db7d5ffae1d0578e8d9e2c1afab90cdcf
ARTIFACT: https://staging.elastic.co/8.1.0-d9cd3df6/summary-8.1.0.html

Hence, we are closing this issue and marking it as QA Validated!

Thanks!
