### ISSUE TITLE
[System] Link to System Overview broken

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#248]
I'm navigating the to System Dashboard, select a specific host an end up in "[Metrics System] Host overview ECS" dashboard. When I click now on "System Overview" link on the left top I get redirected to the Dashboards list page and get the following error:

![Screenshot 2020-08-19 at 14 07 21](https://user-images.githubusercontent.com/244900/90632828-55d65a80-e225-11ea-808f-3bd346e7f0f3.png)

**Comment by fearful-symmetry** [comment]
I swear, every time we fix the dashboard links they find a new way to break.

Okay, when you select a dashboard from the Dashboards UI you get `[hostname]/app/dashboards#/view/Metrics-system-overview-ecs`. That works for everything, as far as I can tell.

The navigation UI in the dashboard uses a slightly different URL: `[hostname]/app/dashboards#/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8-ecs` This URL works fine for the dashboards save the overview dashboard: `[hostname]/app/dashboards#/dashboard/system-Metrics-system-overview-ecs`

We can see this in the vis code: `[System Overview](#/dashboard/system-Metrics-system-overview-ecs)`

It looks like this PR #171 somehow missed appending `system-` the dashboard ID.

**Comment by fearful-symmetry** [comment]
#251 has been merged, closing
