### ISSUE TITLE
in-product instructions for deploying an agent need to be spread to multiple commands

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/integrations#249]
In this screenshot, the reader will expect that they can copy and paste the instructions into their terminal:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/25182304/90640153-a1750e00-e1fd-11ea-90a3-88e8a5c64d36.png">

Unfortunately, the reader has to confirm twice to enroll the agent, which prevents the second and third lines from being run:

```
root@roscigno-obs:/home/dan_roscigno# elastic-agent enroll https://3a2655533eXXXXXXXXX55f9d7576.us-west1.gcp.cloud.es.io:443 UXBMWXXXXXXXXXXXXXseFBmRFJaUUQyQQ==
The Elastic Agent is currently in BETA and should not be used in production
This will replace your current settings. Do you want to continue? [Y/n]:
Please write 'y' or 'n'
This will replace your current settings. Do you want to continue? [Y/n]:y
2020-08-19T13:15:59.489Z	DEBUG	kibana/client.go:170	Request method: POST, path: /api/ingest_manager/fleet/agents/enroll
Successfully enrolled the Agent.
root@roscigno-obs:/home/dan_roscigno#
```

In the above, the commands to `enable` and `start` are not run.  Additionally, in my experience making one choice uppercase indicates that this is the default, and hitting Enter should suffice.  I do acknowledge that there is [no credible reference](https://stackoverflow.com/questions/7803728/standard-format-for-yes-no-questions-in-the-terminal) for this.

**Comment by DanRoscigno** [comment]
@ph can you point me to the PR that fixed this please?

**Comment by ph** [comment]
@DanRoscigno https://github.com/elastic/beats/pull/21206 and the doc was udpated.
