### ISSUE TITLE
O365 | Adjust directory domains mapping input

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#2548]
Our O365 integration requires a user to input a 'directory domains mapping', and we include an incorrect example of the format we expect for the field. We imply that you need to input 'tenant-id: domain name' but all that's actually required is 'domain name', as stated in our docs:

"Add your tenant ID(s) to the Directory (tenant) IDs field, then add the hostname that this tenant identifies to the Directory (tenant) domains field. For example:
Directory IDs: my-id-a my-id-b
Directory domains: a.onmicrosoft.com b.onmicrosoft.com"

Can we adjust the hint in the domain mapping textbox to make it clearer than only the domain name is required. 

<img width="383" alt="Screenshot 2022-01-20 at 11 59 04" src="https://user-images.githubusercontent.com/62879768/150360017-da651b47-f5d4-4c77-9131-2d88b1ac4e74.png">

**Comment by nicpenning** [comment]
Jamie, I am confirming that both are still required. We were deceived as we thought that it was not working, but instead the events were just taking a long time to show up in Elasticsearch. A single domain will work, but not entirely. Having just the domain causes this issue: https://github.com/elastic/integrations/issues/2550

Either way, this would be good to explain in detail on the Overview Office 365 Logs integrations page as well:
![image](https://user-images.githubusercontent.com/5582679/150605204-b7b0b379-b137-41f6-b206-eca3a556c4b9.png)

Sorry that I added some confusion here, but things are starting to make sense.

Thanks!

**Comment by jamiehynds** [comment]
Thanks for clarifying @nicpenning and glad you are up and running now. To avoid confusion, I'll close this issue and create a new one for the suggested enhancement.
