### ISSUE TITLE
Move field cisco_duo.offline_enrollment.user.name to ECS field

### ISSUE THREAD

**Issue by r00tu53r** [elastic/integrations#2553]
The `cisco_duo` package uses field `cisco_duo.offline_enrollment.user.name` which can be stored in the ECS field `user.name` instead.

**Comment by vinit-elastic** [comment]
The name of the user is already mapped to the `user.name` field.

Ref. : https://github.com/elastic/integrations/blob/6756b38c8373c4287a61ae2c29fb01347aff9ef4/packages/cisco_duo/data_stream/offline_enrollment/elasticsearch/ingest_pipeline/default.yml#L37
