### ISSUE TITLE
[Libbeat] Ship EC2 instance name for AWS provider

### ISSUE THREAD

**Issue by kylemclaren** [elastic/integrations#2559]
Currently, we do not ship the instance name for EC2 instances and the `cloud.instance.name` field is therefore not exported with other `cloud.x` metadata when using Filebeat:

https://github.com/elastic/beats/blob/master/libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc

The Libbeat cloud metadata processor for EC2 pulls metadata from the AWS [instance identity document](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html): 

https://github.com/elastic/beats/blob/c570227b30f34c63c889895108d5ebc579bdb52b/libbeat/processors/add_cloud_metadata/provider_aws_ec2.go#L36

EC2 instance names are set when specifying a `Name` key:value tag on an instance. So to retrieve that tag, you'd need to hit `/latest/meta-data/tags/instance/Name` on the instance.

I propose extending the AWS EC2 provider to pull the instance name and export it as the expected `cloud.instance.name` field.

cc/ @kaiyan-sheng

**Comment by kylemclaren** [comment]
Related: https://github.com/elastic/beats/issues/22739

**Comment by endorama** [comment]
Related to https://github.com/elastic/beats/issues/23637
