### ISSUE TITLE
Automatically mask passwords

### ISSUE THREAD

**Issue by sorantis** [elastic/integrations#257]
Provide an automatic way to identify and mask sensitive information such as a password when used with the SQL based database integrations, such as Oracle module.

**Comment by mtojek** [comment]
There is password field which masks the phrase with `****` in Kibana. Do you think about something more sophisticated? If so, then it might affect Kibana too /cc @ruflin .

**Comment by sorantis** [comment]
[Oracle events](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-oracle-performance.html#_example_events) contain sensitive information that customers consider as a risk
```
    "service": {
        "address": "oracle://sys:passwordlocalhost/ORCLPDB1.localdomain",
        "type": "oracle"
    }
```

**Comment by mtojek** [comment]
Elastic Agent uses Metricbeat and Filebeat to generate such data, so it's not an issue with Integrations, but with Metricbeat/Filebeat.

Field definitions stored in Integrations are used mostly to generate Kibana UI and config files. I suppose this should be fixed on the events collector level to strip it and do not leak passwords anywhere.

**Comment by andrewkroh** [comment]
In Metricbeat it looks like `event.host` is copied into `service.address`. And `event.host` is not using the sanitized URI. This would probably fix Metricbeat, but needs tested. Could @elastic/integrations-platforms please look into the issue.

```patch
diff --git a/metricbeat/mb/module/wrapper.go b/metricbeat/mb/module/wrapper.go
index 2ea0d2b60..f0d1552c8 100644
--- a/metricbeat/mb/module/wrapper.go
+++ b/metricbeat/mb/module/wrapper.go
@@ -392,7 +392,7 @@ func (r reporterV2) Event(event mb.Event) bool {
        }
 
        if event.Host == "" {
-               event.Host = r.msw.Host()
+               event.Host = r.msw.HostData().SanitizedURI
        }
 
        if event.Error == nil {
```
