### ISSUE TITLE
ti_anomali invalid policy template

### ISSUE THREAD

**Issue by jsoriano** [elastic/integrations#2575]
Tests for the `ti_anomali` integration are failing with current snapshots of the stack with the following error:
```
Error: error running package system tests: could not complete test run: could not add data stream config to policy: could not add package to policy; API status code = 400; response body = {"statusCode":400,"error":"Bad Request","message":"Package policy is invalid: inputs.http_endpoint.streams.ti_anomali.threatstream.vars.content_type: Webhook path is required"}
```

It can be reproduced locally, it has failed too in the following PRs:
* https://github.com/elastic/integrations/pull/2446
* https://github.com/elastic/integrations/pull/2568

**Comment by mtojek** [comment]
@jsoriano The issue has been already triaged, and identified as bug in Kibana. Fix: https://github.com/elastic/kibana/issues/123596

**Comment by mtojek** [comment]
Fixed: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/70/pipeline/640

Resolving
