### ISSUE TITLE
Prometheus integration is missing some field mappings

### ISSUE THREAD

**Issue by exekias** [elastic/integrations#258]
Now that mappings are split per data stream we need to propagate common fields to all the datasets that may use them. This is the case for the Prometheus `remote_write` dataset, which is missing mappings for labels and metrics:

https://github.com/elastic/integrations/blob/58ef46d6857b0f2e53e5680faf19412dcd9bf7f6/packages/prometheus/dataset/remote_write/fields/fields.yml

While they are mostly present in the `collector`:

https://github.com/elastic/integrations/blob/58ef46d6857b0f2e53e5680faf19412dcd9bf7f6/packages/prometheus/dataset/collector/fields/fields.yml

We need to review all the Prometheus datasets and make sure any possible output is mapped. I also think that labels are not correctly mapped as keywords with the current definition.

**Comment by ChrsMark** [comment]
@exekias hey! I miss the point here 🙂 . From what I see `labels.*` and `metrics.*` are present in `remote_write`'s fields 🤔 , the only difference is in the fields that are related to the types which is a valid point and should be handled in https://github.com/elastic/integrations/pull/243/files.

I will check if labels are mapped as keywords or not.

**Comment by exekias** [comment]
For the existing ones, I think they miss something? I only see `type: object`, probably this should be added:

```
object_type: double
object_type_mapping_type: "*"
```

**Comment by ChrsMark** [comment]
> For the existing ones, I think they miss something? I only see `type: object`, probably this should be added:
> 
> ```
> object_type: double
> object_type_mapping_type: "*"
> ```

Ah, gotcha! Thanks for catching this! I'm pushing a fix.
