### ISSUE TITLE
[Discuss] Organize packages by the products they monitor

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#259]
From a usage perspective I think the most important thing to show to the user when they open a package are the "products" it can monitor. For example when you open the AWS package the two top-level options are for logs and metrics. I think the most important item is to show that the package supports CloudTrail, CloudWatch, EC2, ELB, etc. Then below the products offer the option of collecting logs and metrics.

The current hierarchy is more reflective of the underlying software architecture (and possibly team structure).

<img width="594" alt="aws-package" src="https://user-images.githubusercontent.com/4565752/91612269-14dbf580-e94b-11ea-8c35-68e03cc577e4.png">

I propose a structure like:

- AWS Package
  - Billing
    - Metrics
  - CloudTrail
    - Logs
  - CloudWatch
    - Logs
    - Metrics

As another example, the Cisco module would be better organized around products. Currently it's organized around input types so at the top level you have syslog, udp, tcp, file. **The makes the actual products supported much less discoverable.**

- Cisco
  - ASA
    - Logs
  - FTD
    - Logs
  - IOS
    - Logs
  - Nexus
    - Logs

<img width="591" alt="cisco-package" src="https://user-images.githubusercontent.com/4565752/91612069-9c753480-e94a-11ea-85ae-cb551274c7f0.png">

### Actions

- Determine if there is agreement on this proposed layout.
- Figure out what changes would be necessary to implement this.

**Comment by andresrc** [comment]
The logs / metrics structure is ok for packages that target monitoring of a single "product", it's pretty clear that we will need something different for things like the cloud integrations

**Comment by kaiyan-sheng** [comment]
Good point! If we organize AWS package by products/services, it's one less layer for users to see what we actually support.

**Comment by ruflin** [comment]
@andrewkroh I stumbled also over this for the AWS package, good (bad?) to know Cisco is also hitting it. The initial reasoning was around enabling metrics and logs separately but this obviously does not work in all cases.

The current package format is focused on grouping "inputs" together as the common configs are shared on the input level. 

I think there are 2 solutions moving forward:

1. Build independent dataset grouping into packages
2. Build specific UIs for some packages

For AWS I personally lean in the direction of option 2 as I think there more opportunities to opimise then just grouping and I do not want to overdo the form building in the package itself as it might get out of hand. But there might well be a low hanging fruit for 1 to not have to build too many custom UI's.

**Comment by andrewstucki** [comment]
> The current package format is focused on grouping "inputs" together as the common configs are shared on the input level.

@ruflin so one thing to note that I've been running across implementing some of the packages--many of the inputs, while they ideally _should_ share configurations, in practice, they can't. See the comment here:

https://github.com/elastic/integrations/pull/240#discussion_r466633462

Namely, for `filebeat`, there's not really internal routing logic that conditionally splits off input to different modules/processors--meaning that the core configurations (log file location, port bindings, etc.) really can't be shared. What that really comes down to then is that, for the most part only "metadata"-like things like tags, etc. can be shared.

**Comment by ruflin** [comment]
@andrewstucki Interesting point around the routing. Could you file and issue in Beats for this as I think we could use this in multiple places to route events from to multiple datasets. The alternative here is that we do it in ingest pipelines. Would be nice to have an example on how your ideal config would look like and we can work backward from there.

**Comment by ruflin** [comment]
@mostlyjason I assigned this to you as you have thought about this recently quite a bit and are best to comment on where we are heading here.

**Comment by andrewkroh** [comment]
We can close this now. Through `policy_templates` the AWS products support by integrations are now much more discoverable.

<img width="933" alt="Screen Shot 2021-09-09 at 8 44 35 AM" src="https://user-images.githubusercontent.com/4565752/132688135-1a7c5b62-787a-459b-b8ee-8bf628fc7a75.png">

And for Cisco we are creating separate packages for the various products.
