### ISSUE TITLE
[Cisco IOS] ASR Log Format does not match grok pattern

### ISSUE THREAD

**Issue by fgierlinger** [elastic/integrations#2607]
**Description**
The syslog format for ASR920 Router does not match the existing grok pattern of the cisco_ios integration.

```
<165>7433: ASR920: 007439: 2y10w: %SEC_LOGIN-5-LOGIN_SUCCESS: Login Success [user: username] [Source: 192.168.0.1] [localport: 22] at 07:57:58 VIENNA Thu Jan 27 2022

<165> = Syslog header
7433 = Syslog Counter
ASR920 = Device Name
007435 = ?
2y10w = Uptime
%SEC_LOGIN-5-LOGIN_SUCCESS = Event Category
Login Success ... = Event Message
```

The existing grok pattern do match this message and since `ignore_failure: true` they do not lead to an error. Nonetheless, some vital information as the hostname are not beeing processed.

https://github.com/elastic/integrations/blob/7326c1646a54bf36b20d6d3c8cd02771015de9c6/packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L28-L35

The following grok pattern should match the ASR920 header part (everything up to the % sign). The `event.sequence` is an optional field and can be disabled in the IOS configuration with `no logging message-counter syslog` .

```
^<%{NONNEGINT:[log][syslog][priority:long}>%{NUMBER:[event][sequence]:int}?: %{SYSLOGHOST:[log][syslog][hostname]:keyword}: %{NUMBER:unknown_field:int}: %{NOTSPACE:uptime}:
```

Here are some more log messages of the ASR920:

```
<165>7433: ASR920: 007439: 2y10w: %SEC_LOGIN-5-LOGIN_SUCCESS: Login Success [user: username] [Source: 192.168.0.1] [localport: 22] at 07:57:58 VIENNA Thu Jan 27 2022
<166>7432: ASR920: 007438: 2y10w: %SYS-6-LOGOUT: User username has exited tty session 3(192.168.0.1)
<166>7431: ASR920: 007437: 2y10w: %SYS-6-LOGOUT: User CPI has exited tty session 1(192.168.0.1)
<166>7424: ASR920: 007430: 2y10w: %SYS-6-TTY_EXPIRE_TIMER: (exec timer expired, tty 1 (192.168.0.1)), user username
<165>7422: ASR920: 007428: 2y10w: %SYS-5-CONFIG_I: Configured from console by username on vty1 (192.168.0.1)
```

We have messages from other ASR920 routers which follow the already defined message format (including the date instead of the Number and the uptime), but we are not aware where this difference is coming from. As soon as we have figured this out, I will post an update. Nonetheless both formats should be supported by the cisco_ios integration.

Unfortunately I couldn't find any official documentation about the logging format of the ASR920.

**Actual behaviour**
When syslog messages are sent without date specification, only the message part (everything after the percent sign) is parsed successfully. Information about the sending host or the event number are lost because the existing grok patterns does not match.

**Expected behaviour**
Syslog messages from the ASR920 are parsed successfully.

**Comment by efd6** [comment]
@fgierlinger From the [post here](https://community.cisco.com/t5/network-management/syslog-sequence-numbering/td-p/1559916), it looks like what we are calling the sequence number is the message count. Unfortunately the link provided by the user posting the answer no longer works and the page in not retained by the wayback machine.

This is supported though by the [docs here](https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/bsm/configuration/15-mt/bsm-15-mt-book/bsm-xml-syslog-mess.html) which show the sequence number having a zero-padding, and also [here](https://www.cisco.com/c/en/us/td/docs/routers/access/wireless/software/guide/SysMsgLogging.html).

Are you able to confirm that turning off "service sequence-numbers" removes the second number? Just as `no logging message-counter syslog` removes the first.

The question becomes how should we deal with recording the two different, but similar, event numbers. It looks like we are using the event count in place of the sequence number, but I think making a change now would be more confusing than helpful.

I have a draft PR at #3694.

**Comment by fgierlinger** [comment]
@efd6 I can confirm that when turning off the service sequence numbers (`no service sequence-number`) the second numbers (7433, 7432, 7431, 7424, 7422 of my code sample above) disappear.

> The question becomes how should we deal with recording the two different, but similar, event numbers. It looks like we are using the event count in place of the sequence number, but I think making a change now would be more confusing than helpful.

I‘m not sure if it is possible to match all options. There are multiple switches to change the log format

* `service timestamps log uptime` vs `service timestamps log datetime`
* `service sequence-number` vs `no service sequence-number`

just to name a few. There should be at least a hint in the documentation of the Cisco module which log format is expected. Or better: which confit options need to be set.

**Comment by efd6** [comment]
Thanks. I agree, I think documenting the expected sequence number to use sounds like the best way forward. I'll send a PR for that soon. If you can provide the text that is shown in the device config options that gives us the desired seq numbers, I will use that in the docs to reduce the possibility of user confusion.

**Comment by fgierlinger** [comment]
We currently have the following configuration active
```
service timestamps debug datetime msec localtime
service timestamps log datetime msec localtime
```

The following configuration items have been removed with the `no` command
```
no service sequence-numbers
no service timestamps log uptime
no service timestamps uptime
```

Here are some syslog messages that are being generated with our current configuration that are all parsed without error:
```
<165>2029: ASR920: Aug 3 08:11:02.204: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/0/7, changed state to up
<166>352134: ASR920: Aug 3 08:08:47.142: %SEC-6-IPACCESSLOGP: list ACL_CE-SECURITY denied udp 203.0.113.1(0) -> 224.0.0.252(0), 1 packet
<166>352133: ASR920: Aug 3 08:04:47.140: %SEC-6-IPACCESSLOGNP: list ACL_CE-SECURITY denied 112 203.0.113.252 -> 224.0.0.18, 295 packets
<163>81681: CORE: Aug 3 08:09:55.769: %SNMP-SW1-3-RESPONSE_DELAYED: processing Get of cefcFRUPowerStatusEntry.1.2030 (4620 msecs)
 ```

**Comment by efd6** [comment]
I think I have a reasonable strategy; would you be able to provide a couple of log lines with both `no service sequence-numbers` and `no service message-counter` so that I can include them in the tests and confirm that the docs I have written will be correct.

**Comment by fgierlinger** [comment]
@efd6 Here is our current logging configuration:

```
logging discriminator NOLFDSB mnemonics drops NOLFDSB
logging buffered discriminator NOLFDSB 65536
logging rate-limit all 600
logging console discriminator NOLFDSB
logging monitor discriminator NOLFDSB
!
logging history debugging
logging alarm informational
logging trap debugging
logging origin-id hostname
logging facility local4
logging source-interface Loopback0
logging host 192.0.2.1 discriminator NOLFDSB
logging host 192.0.2.2
logging host 192.0.2.3 transport udp port 9517
```

which results in the following logs

```
<165>8178: ASR920: Aug 23 06:49:01.310: %SSH-5-SSH_COMPLIANCE_VIOLATION_RSA_KEY_SIZE: SSH RSA Key Size compliance violation detected. Kindly note that the usage of keys smaller than 2048 bits will be deprecated in the upcoming releases. Please revise your key configuration accordingly to avoid service impact.
<166>395519: ASR920: Aug 23 06:47:47.152: %SEC-6-IPACCESSLOGP: list ACL_CE-SECURITY denied udp 192.0.2.100(0) -> 224.0.0.251(0), 1 packet 
<166>395518: ASR920: Aug 23 06:45:47.150: %SEC-6-IPACCESSLOGNP: list ACL_CE-SECURITY denied 112 192.0.2.101 -> 224.0.0.18, 347 packets 
<165>395517: ASR920: Aug 23 06:44:30.861: %LINEPROTO-5-UPDOWN: Line protocol on Interface BDI1079, changed state to up
<165>395516: ASR920: Aug 23 06:44:30.846: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/0/11, changed state to up
<165>229: ASR920: Aug 23 00:02:21.811: %SEC_LOGIN-5-LOGIN_SUCCESS: Login Success [user: USER] [Source: 192.0.2.102] [localport: 22] at 00:02:21 VIENNA Tue Aug 23 2022
<166>1114: ASR920: Aug 23 00:04:03.472: %SYS-6-LOGOUT: User CPI has exited tty session 2(192.0.2.102)
```

**Comment by efd6** [comment]
Thanks. They all appear to be parsed correctly with the new processor. Please take a look at the docs that I have added to describe the set-up. If there is anything wrong with them, please open a new issue.
