### ISSUE TITLE
[Auth0] Icon and title don't show nicely in Integrations UI

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#2618]
* Stack version: 8.1.0-SNAPSHOT

The icon of oauth seems to be streched and the text is breaking twice (likely too long):

![Screenshot 2022-01-31 at 09 32 45](https://user-images.githubusercontent.com/244900/151761901-1378f47d-48ac-427d-95b4-9ccee8070d5f.png)

**Comment by jamiehynds** [comment]
FYI @r00tu53r

**Comment by zikphil** [comment]
@ruflin Is there anything that would prevent this integration to be made available in 8.0.x as opposed to 8.1? :)
