### ISSUE TITLE
[Cisco FTD] Flattened Mapping cisco.ftd.security

### ISSUE THREAD

**Issue by nicpenning** [elastic/integrations#2621]
A conversation in the community has started about the behavior of the Cisco FTD Integration via Elastic Agent and how to handle flattened fields. https://elasticstack.slack.com/archives/CNEDGGJQ3/p1643393837480969?thread_ts=1642804410.096600&cid=CNEDGGJQ3

Currently, we are trying to migrate away from Filebeat 7.13.2 to Elastic Agent and the Cisco FTD Integration, however, there are fields we have built dashboards with that are only found in the cisco.ftd.security flattened field.

Flattened data:
![image](https://user-images.githubusercontent.com/5582679/151887610-56b09c04-756e-4d06-9de6-d434dec9bda8.png)

This brings us to the core issue:
- We can't use our dashboards natively as the current field mapping doesn't allow visualizations.

To combat this, we have thought about the following:
1. If we modify the current ingest pipeline (logs-cisco_ftd.log-1.2.2) from out of the box then when we upgrade this integration it will need to be modified again and after every upgrade which will add overhead to the upgrade process.
2. If we push this to a new pipeline and make those changes, then we would need to ensure that any upgraded pipelines will need to be adjusted for the new pipeline to work.
3. Instead of adjusting the pipeline, what if we just adjusted the mapping to use an object instead of flattened and everything will just work until an upgrade comes through with a new set of mappings.

We want to understand the proper way to move forward by using all the fields available to us and get away from flattened mappings as they are not useful in their raw form for data visualization.

**Comment by LaZyDK** [comment]
@P1llus Can you help with this one? The flattened view is in the way of excluding within SIEM rules also.

**Comment by nicpenning** [comment]
Possible fields from the cisco.ftd.security:


 "security": {
                 "properties": {
                   "ac_policy": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "access_control_rule_action": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "access_control_rule_name": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "access_control_rule_reason": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "application_protocol": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "classification": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "client": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "client_version": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "connection_duration": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "dns_query": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "dns_record_type": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "dns_response_type": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "dns_ttl": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "dst_ip": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "dst_port": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "egress_interface": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "egress_zone": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "file_action": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "file_count": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "file_direction": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "file_name": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "file_policy": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "file_sandbox_status": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "file_sha256": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "file_size": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "file_storage_status": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "file_type": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "first_packet_second": {
                     "type": "date",
                     "format": "strict_date_optional_time"
                   },
                   "gid": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "http_referer": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "http_response": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "icmp_code": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "icmp_type": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "ingress_interface": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "ingress_zone": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "initiator_bytes": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "initiator_packets": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "inline_result": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "intrusion_policy": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "ip_reputation_si_category": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "ips_count": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "message": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "nap_policy": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "original_client_src_ip": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "prefilter_policy": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "priority": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "protocol": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "referenced_host": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "responder_bytes": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "responder_packets": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "revision": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "sec_int_matching_ip": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "sha_disposition": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "sid": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "spero_disposition": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "src_ip": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "src_port": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "threat_name": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "threat_score": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "uri": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "url": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "urlsi_category": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "user": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "user_agent": {
                     "type": "keyword",
                     "ignore_above": 1024
                   },
                   "web_application": {
                     "type": "keyword",
                     "ignore_above": 1024
                   }
                 }
               }

**Comment by nicpenning** [comment]
Closing since there probably have been lots of updates since then and we never did migrate, plus there is no longer a need for this integration.
