### ISSUE TITLE
[github] Possible incorrect 'created' query operator

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#2622]
It looks like the query might be using an invalid operator. The code contains `=>`, but that's not listed in the docs. It should use `>=`.

https://github.com/elastic/integrations/blob/d5e563c66644ba675ccd12c612c2ca161ef7786a/packages/github/data_stream/audit/agent/stream/httpjson.yml.hbs#L25-L26

> You can use >, >=, <, and <= to search for values that are greater than, greater than or equal to, less than, and less than or equal to another value.

References

- https://docs.github.com/en/organizations/keeping-your-organization-secure/reviewing-the-audit-log-for-your-organization#search-based-on-time-of-action

- https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax#query-for-values-greater-or-less-than-another-value

**Comment by legoguy1000** [comment]
Ya looks like I typo'd that. That's awkward.
