### ISSUE TITLE
Add github codeowners

### ISSUE THREAD

**Issue by jsoriano** [elastic/integrations#2631]
Add github codeowners file to assign ownership for the files of each package on this repository. Ownership will be used to require review of the owners for changes on their packages.

Keep codeowners synchronized with the github owner indicated in the manifest file.

**Comment by jsoriano** [comment]
> Keep codeowners synchronized with the github owner indicated in the manifest file.

@elastic/observablt-robots would you have a recommendation for this?

**Comment by epixa** [comment]
Big +1 from me on this.

However, I do urge treating the synchronization issue separately from the initial codeowners implementation. Other projects at Elastic with more teams working on them have been manually managing codeowners for years now without considerable overhead or problems. There are no doubt times when code paths aren't tracked accurately and such, but the impact is small and the file just gets fixed. Automation can be added at any time to help keep it in sync.

**Comment by jsoriano** [comment]
Here it is not so much about manually managing it or not, but about keeping both things synchronized.

I agree that we could start with a fully manual approach in any case, and evolve it later if needed.

**Comment by jsoriano** [comment]
> What is going to happen to packages that have multiple ownership?

An option by now can be to add multiple owners to the CODEOWNERS file, as we don't expect to have automatic synchronization with the owner indicated in the manifest.

We may later discuss about the possible needing to indicate multiple owners in the manifest file.
