### ISSUE TITLE
fields yaml files typos

### ISSUE THREAD

**Issue by efd6** [elastic/integrations#2643]
While working on a package/ECS yaml file analyser I found a collection of field name typos in a variety of field description files:

- [x] default_fields (?) — packages/network_traffic/data_stream/tls/fields/protocol.yml
- [ ] descriiption — packages/mimecast/data_stream/audit_events/fields/ecs.yml
- [ ] descripion — 
     - [ ] packages/elastic_agent/data_stream/apm_server_metrics/fields/beat-fields.yml
     - [ ] packages/elastic_agent/data_stream/auditbeat_metrics/fields/beat-fields.yml
     - [ ] packages/elastic_agent/data_stream/elastic_agent_metrics/fields/beat-fields.yml
     - [ ] packages/elastic_agent/data_stream/endpoint_security_metrics/fields/beat-fields.yml
     - [ ] packages/elastic_agent/data_stream/filebeat_metrics/fields/beat-fields.yml
     - [ ] packages/elastic_agent/data_stream/fleet_server_metrics/fields/beat-fields.yml
     - [ ] packages/elastic_agent/data_stream/heartbeat_metrics/fields/beat-fields.yml
     - [ ] packages/elastic_agent/data_stream/metricbeat_metrics/fields/beat-fields.yml
     - [ ] packages/elastic_agent/data_stream/osquerybeat_metrics/fields/beat-fields.yml
     - [ ] packages/elastic_agent/data_stream/packetbeat_metrics/fields/beat-fields.yml
- [ ] dimensiont — packages/kubernetes/data_stream/state_replicaset/fields/base-fields.yml
- [ ] dimensions (?) — packages/kubernetes/data_stream/state_statefulset/fields/base-fields.yml

**Comment by ruflin** [comment]
@jsoriano @mtojek Is this something we could potentially catch during validation?

**Comment by jsoriano** [comment]
> Is this something we could potentially catch during validation?

I guess we could set `additionalProperties: false` in the fields spec, I have opened a PR for this: https://github.com/elastic/package-spec/pull/281

Is there any reason to don't do this?

**Comment by ruflin** [comment]
As long as the spec is fully up-to-date with which fields are allowed, it should be fine. It likely will mean as soon as the package-spec is updated, some packages will need adjustment but this is a good thing.

**Comment by jsoriano** [comment]
I have created https://github.com/elastic/package-spec/issues/282 to follow up on stricter validation of fields properties.
