### ISSUE TITLE
[system] security - Add support for network share audit events

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#2645]
Add support for event ID 5140 and 5145 to the system security data stream.

https://windows-event-explorer.app.elstc.co/publisher/Microsoft-Windows-Security-Auditing/event/5140/v1
https://windows-event-explorer.app.elstc.co/publisher/Microsoft-Windows-Security-Auditing/event/5145/v0

**Comment by randomuserid** [comment]
So when file & object access auditing is enabled, a file server writes a number of events to the Security log. Event 5140 looks like this, with the calling username in the Account Name field:
```


A network share object was accessed.
	
Subject:
	Security ID:		S-1-5-21-4256129798-270769626-1418745944-1109
	Account Name:		baltar
	Account Domain:		SKYNET1
	Logon ID:		0x18178B20

Network Information:	
	Object Type:		File
	Source Address:		10.128.0.55
	Source Port:		50319
	
Share Information:
	Share Name:		\\*\Engineering
	Share Path:		\??\C:\Shares\Engineering

Access Request Information:
	Access Mask:		0x1
	Accesses:		ReadData (or ListDirectory)
				</body></html>
```

Event 5145 looks like this, with the calling username in the same field:
```

A network share object was checked to see whether client can be granted desired access.
	
Subject:
	Security ID:		S-1-5-21-4256129798-270769626-1418745944-1109
	Account Name:		baltar
	Account Domain:		SKYNET1
	Logon ID:		0x172B499C

Network Information:	
	Object Type:		File
	Source Address:		::1
	Source Port:		62615
	
Share Information:
	Share Name:		\\*\Engineering
	Share Path:		\??\C:\Shares\Engineering
	Relative Target Name:	\

Access Request Information:
	Access Mask:		0x100080
	Accesses:		SYNCHRONIZE
				ReadAttributes
				
Access Check Results:
	SYNCHRONIZE:	Granted by	D:(A;OICI;FA;;;WD)
				ReadAttributes:	Granted by	D:(A;OICI;FA;;;WD)
				</body></html>
```

The Share Name field indicates the name of the file share that was touched.

**Comment by randomuserid** [comment]
here is how the event comes in today:

```
{
  "_index": ".siem-signals-default-000020",
  "_id": "26be5a63dd962e7741cf5bed4463dc3609f2811b088a002a07f3067efa64802e",
  "_version": 1,
  "_score": 1,
  "_source": {
    "job_id": "rare-share-user-5",
    "result_type": "record",
    "probability": 0.00029347681070475873,
    "multi_bucket_impact": 0,
    "record_score": 83.54205120572678,
    "initial_record_score": 83.54205120572678,
    "bucket_span": 900,
    "detector_index": 0,
    "is_interim": false,
    "timestamp": 1643913900000,
    "by_field_name": "winlog.event_data.SubjectUserName",
    "by_field_value": "baltar",
    "function": "rare",
    "function_description": "rare",
    "typical": [
      0.00029347681070475873
    ],
    "actual": [
      1
    ],
    "influencers": [
      {
        "influencer_field_name": "winlog.event_data.SubjectUserName",
        "influencer_field_values": [
          "baltar"
        ]
      },
      {
        "influencer_field_name": "winlog.event_data.ShareName",
        "influencer_field_values": [
          "\\\\*\\Engineering",
          "\\\\*\\Engineering (ITAR)"
        ]
      },
      {
        "influencer_field_name": "winlog.event_data.IpAddress",
        "influencer_field_values": [
          "::1"
        ]
      }
    ],
    "winlog": {
      "event_data": {
        "SubjectUserName": [
          "baltar"
        ],
        "ShareName": [
          "\\\\*\\Engineering",
          "\\\\*\\Engineering (ITAR)"
        ],
        "IpAddress": [
          "::1"
        ]
      }
    },
    "@timestamp": "2022-02-04T20:30:38.732Z",
    "all_field_values": [
      "baltar",
      "rare-share-user-5",
      "baltar",
      "\\\\*\\Engineering",
      "\\\\*\\Engineering (ITAR)",
      "::1"
    ],
    "event": {
      "kind": "signal"
    },
    "signal": {
      "_meta": {
        "version": 57
      },
      "parents": [
        {
          "id": "rare-share-user-5_record_1643913900000_900_0_-54090546375116357554324348050114245565_6",
          "type": "event",
          "index": ".ml-anomalies-custom-rare-share-user-5",
          "depth": 0
        }
      ],
      "ancestors": [
        {
          "id": "rare-share-user-5_record_1643913900000_900_0_-54090546375116357554324348050114245565_6",
          "type": "event",
          "index": ".ml-anomalies-custom-rare-share-user-5",
          "depth": 0
        }
      ],
      "status": "open",
      "rule": {
        "id": "4c6410e0-85f9-11ec-8e96-e5140fc18fd2",
        "actions": [],
        "interval": "10m",
        "name": "Suspicious File Share Activity",
        "tags": [
          "ueba"
        ],
        "enabled": true,
        "created_by": "elastic",
        "updated_by": "elastic",
        "throttle": null,
        "created_at": "2022-02-04T20:30:32.434Z",
        "updated_at": "2022-02-04T20:30:33.484Z",
        "description": "Suspicious File Share Activity",
        "risk_score": 73,
        "severity": "high",
        "license": "",
        "output_index": ".siem-signals-default",
        "meta": {
          "from": "3000m",
          "kibana_siem_app_url": "https://a2dc3df85d2f4037bd1915c4d607e288.us-west1.gcp.cloud.es.io:9243/app/security"
        },
        "author": [],
        "false_positives": [],
        "from": "now-180600s",
        "rule_id": "6cde6e78-b3aa-4d61-a40d-830a1507fb7b",
        "max_signals": 100,
        "risk_score_mapping": [],
        "severity_mapping": [],
        "threat": [],
        "to": "now",
        "references": [],
        "version": 1,
        "exceptions_list": [],
        "immutable": false,
        "type": "machine_learning",
        "anomaly_threshold": 75,
        "machine_learning_job_id": [
          "rare-share-user-5"
        ]
      },
      "reason": "event created high alert Suspicious File Share Activity.",
      "depth": 1,
      "parent": {
        "id": "rare-share-user-5_record_1643913900000_900_0_-54090546375116357554324348050114245565_6",
        "type": "event",
        "index": ".ml-anomalies-custom-rare-share-user-5",
        "depth": 0
      },
      "original_time": "2022-02-03T18:45:00.000Z"
    }
  },
  "fields": {
    "signal.rule.output_index": [
      ".siem-signals-default"
    ],
    "kibana.alert.severity": [
      "high"
    ],
    "signal.parent.type": [
      "event"
    ],
    "signal.rule.type": [
      "machine_learning"
    ],
    "kibana.alert.rule.updated_by": [
      "elastic"
    ],
    "signal.ancestors.depth": [
      0
    ],
    "kibana.alert.ancestors.id": [
      "rare-share-user-5_record_1643913900000_900_0_-54090546375116357554324348050114245565_6"
    ],
    "winlog.event_data.IpAddress": [
      "::1"
    ],
    "kibana.alert.rule.description": [
      "Suspicious File Share Activity"
    ],
    "kibana.alert.rule.tags": [
      "ueba"
    ],
    "signal.rule.machine_learning_job_id": [
      "rare-share-user-5"
    ],
    "signal.rule.created_by": [
      "elastic"
    ],
    "kibana.alert.rule.to": [
      "now"
    ],
    "signal.rule.interval": [
      "10m"
    ],
    "kibana.alert.rule.created_by": [
      "elastic"
    ],
    "winlog.event_data.ShareName": [
      "\\\\*\\Engineering",
      "\\\\*\\Engineering (ITAR)"
    ],
    "signal.rule.enabled": [
      "true"
    ],
    "kibana.alert.ancestors.depth": [
      0
    ],
    "signal.rule.id": [
      "4c6410e0-85f9-11ec-8e96-e5140fc18fd2"
    ],
    "signal.rule.max_signals": [
      "100"
    ],
    "bucket_span": [
      900
    ],
    "signal.rule.risk_score": [
      73
    ],
    "signal.reason": [
      "event created high alert Suspicious File Share Activity."
    ],
    "signal.rule.updated_at": [
      "2022-02-04T20:30:33.484Z"
    ],
    "kibana.alert.risk_score": [
      73
    ],
    "function": [
      "rare"
    ],
    "kibana.alert.rule.name": [
      "Suspicious File Share Activity"
    ],
    "record_score": [
      83.54205120572678
    ],
    "signal._meta.version": [
      57
    ],
    "signal.status": [
      "open"
    ],
    "event.kind": [
      "signal"
    ],
    "actual": [
      1
    ],
    "signal.rule.tags": [
      "ueba"
    ],
    "signal.rule.created_at": [
      "2022-02-04T20:30:32.434Z"
    ],
    "kibana.alert.workflow_status": [
      "open"
    ],
    "kibana.alert.rule.uuid": [
      "4c6410e0-85f9-11ec-8e96-e5140fc18fd2"
    ],
    "probability": [
      0.00029347681070475873
    ],
    "multi_bucket_impact": [
      0
    ],
    "kibana.alert.rule.interval": [
      "10m"
    ],
    "kibana.alert.rule.type": [
      "machine_learning"
    ],
    "kibana.alert.reason": [
      "event created high alert Suspicious File Share Activity."
    ],
    "signal.parents.depth": [
      0
    ],
    "influencers.influencer_field_name": [
      "winlog.event_data.SubjectUserName",
      "winlog.event_data.ShareName",
      "winlog.event_data.IpAddress"
    ],
    "detector_index": [
      0
    ],
    "signal.ancestors.id": [
      "rare-share-user-5_record_1643913900000_900_0_-54090546375116357554324348050114245565_6"
    ],
    "signal.original_time": [
      "2022-02-03T18:45:00.000Z"
    ],
    "signal.rule.meta.from": [
      "3000m"
    ],
    "kibana.alert.rule.immutable": [
      "false"
    ],
    "by_field_value": [
      "baltar"
    ],
    "signal.rule.severity": [
      "high"
    ],
    "kibana.alert.ancestors.index": [
      ".ml-anomalies-custom-rare-share-user-5"
    ],
    "signal.rule.from": [
      "now-180600s"
    ],
    "kibana.alert.depth": [
      1
    ],
    "kibana.alert.rule.enabled": [
      "true"
    ],
    "kibana.alert.rule.version": [
      "1"
    ],
    "influencers.influencer_field_values": [
      "baltar",
      "\\\\*\\Engineering",
      "\\\\*\\Engineering (ITAR)",
      "::1"
    ],
    "kibana.alert.rule.from": [
      "now-180600s"
    ],
    "kibana.alert.ancestors.type": [
      "event"
    ],
    "signal.rule.version": [
      "1"
    ],
    "signal.rule.meta.kibana_siem_app_url": [
      "https://a2dc3df85d2f4037bd1915c4d607e288.us-west1.gcp.cloud.es.io:9243/app/security"
    ],
    "by_field_name": [
      "winlog.event_data.SubjectUserName"
    ],
    "signal.ancestors.index": [
      ".ml-anomalies-custom-rare-share-user-5"
    ],
    "is_interim": [
      false
    ],
    "signal.depth": [
      1
    ],
    "signal.parents.type": [
      "event"
    ],
    "signal.rule.immutable": [
      "false"
    ],
    "signal.parent.index": [
      ".ml-anomalies-custom-rare-share-user-5"
    ],
    "signal.rule.name": [
      "Suspicious File Share Activity"
    ],
    "signal.rule.rule_id": [
      "6cde6e78-b3aa-4d61-a40d-830a1507fb7b"
    ],
    "signal.parents.index": [
      ".ml-anomalies-custom-rare-share-user-5"
    ],
    "kibana.alert.rule.license": [
      ""
    ],
    "all_field_values": [
      "baltar",
      "rare-share-user-5",
      "baltar",
      "\\\\*\\Engineering",
      "\\\\*\\Engineering (ITAR)",
      "::1"
    ],
    "signal.rule.anomaly_threshold": [
      75
    ],
    "timestamp": [
      1643913900000
    ],
    "result_type": [
      "record"
    ],
    "kibana.alert.rule.max_signals": [
      "100"
    ],
    "kibana.alert.rule.updated_at": [
      "2022-02-04T20:30:33.484Z"
    ],
    "signal.rule.description": [
      "Suspicious File Share Activity"
    ],
    "winlog.event_data.SubjectUserName": [
      "baltar"
    ],
    "signal.parent.id": [
      "rare-share-user-5_record_1643913900000_900_0_-54090546375116357554324348050114245565_6"
    ],
    "signal.rule.to": [
      "now"
    ],
    "signal.rule.updated_by": [
      "elastic"
    ],
    "kibana.alert.rule.created_at": [
      "2022-02-04T20:30:32.434Z"
    ],
    "@timestamp": [
      "2022-02-04T20:30:38.732Z"
    ],
    "initial_record_score": [
      83.54205120572678
    ],
    "job_id": [
      "rare-share-user-5"
    ],
    "signal.parents.id": [
      "rare-share-user-5_record_1643913900000_900_0_-54090546375116357554324348050114245565_6"
    ],
    "typical": [
      0.00029347681070475873
    ],
    "signal.parent.depth": [
      0
    ],
    "signal.rule.license": [
      ""
    ],
    "signal.ancestors.type": [
      "event"
    ],
    "kibana.alert.rule.rule_id": [
      "6cde6e78-b3aa-4d61-a40d-830a1507fb7b"
    ],
    "kibana.alert.original_time": [
      "2022-02-03T18:45:00.000Z"
    ],
    "function_description": [
      "rare"
    ]
  }
}
```

**Comment by randomuserid** [comment]
here is how 5140 comes in today:
`{
  "_index": "winlogbeat-7.12.0-2022.01.13-000006",
  "_id": "mwHtwH4BsEiXS7nYBptz",
  "_version": 1,
  "_score": 1,
  "_source": {
    "@timestamp": "2022-02-03T18:51:03.941Z",
    "ecs": {
      "version": "1.8.0"
    },
    "cloud": {
      "availability_zone": "us-central1-a",
      "project": {
        "id": "elastic-siem"
      },
      "account": {
        "id": "elastic-siem"
      },
      "provider": "gcp",
      "instance": {
        "id": "5957135645790541702",
        "name": "skynet"
      },
      "machine": {
        "type": "e2-medium"
      }
    },
    "event": {
      "action": "File Share",
      "created": "2022-02-03T18:51:05.143Z",
      "outcome": "success",
      "kind": "event",
      "code": 5140,
      "provider": "Microsoft-Windows-Security-Auditing"
    },
    "host": {
      "hostname": "skynet",
      "architecture": "x86_64",
      "os": {
        "kernel": "10.0.14393.4886 (rs1_release.220104-1735)",
        "build": "14393.4886",
        "type": "windows",
        "platform": "windows",
        "version": "10.0",
        "family": "windows",
        "name": "Windows Server 2016 Datacenter"
      },
      "id": "02204c11-8982-468a-b4a9-535251873a58",
      "name": "skynet.skynet.local",
      "ip": [
        "10.128.0.23",
        "fe80::5efe:a80:17",
        "fe80::ffff:ffff:fffe"
      ],
      "mac": [
        "42:01:0a:80:00:17",
        "00:00:00:00:00:00:00:e0",
        "00:00:00:00:00:00:00:e0"
      ]
    },
    "log": {
      "level": "information"
    },
    "message": "A network share object was accessed.\n\t\nSubject:\n\tSecurity ID:\t\tS-1-5-21-4256129798-270769626-1418745944-1109\n\tAccount Name:\t\tbaltar\n\tAccount Domain:\t\tSKYNET1\n\tLogon ID:\t\t0x172B499C\n\nNetwork Information:\t\n\tObject Type:\t\tFile\n\tSource Address:\t\t::1\n\tSource Port:\t\t62594\n\t\nShare Information:\n\tShare Name:\t\t\\\\*\\Engineering (ITAR)\n\tShare Path:\t\t\\??\\C:\\Shares\\Engineering (ITAR)\n\nAccess Request Information:\n\tAccess Mask:\t\t0x1\n\tAccesses:\t\tReadData (or ListDirectory)\n\t\t\t\t",
    "winlog": {
      "opcode": "Info",
      "event_data": {
        "SubjectUserName": "baltar",
        "AccessList": "%%4416\n\t\t\t\t",
        "IpPort": "62594",
        "ShareLocalPath": "\\??\\C:\\Shares\\Engineering (ITAR)",
        "AccessMask": "0x1",
        "ShareName": "\\\\*\\Engineering (ITAR)",
        "SubjectUserSid": "S-1-5-21-4256129798-270769626-1418745944-1109",
        "SubjectLogonId": "0x172b499c",
        "SubjectDomainName": "SKYNET1",
        "ObjectType": "File",
        "IpAddress": "::1"
      },
      "event_id": 5140,
      "task": "File Share",
      "provider_guid": "{54849625-5478-4994-A5BA-3E3B0328C30D}",
      "computer_name": "skynet.skynet.local",
      "provider_name": "Microsoft-Windows-Security-Auditing",
      "keywords": [
        "Audit Success"
      ],
      "version": 1,
      "api": "wineventlog",
      "record_id": 116140907,
      "process": {
        "pid": 4,
        "thread": {
          "id": 11816
        }
      },
      "channel": "Security"
    },
    "agent": {
      "type": "winlogbeat",
      "version": "7.12.0",
      "hostname": "skynet",
      "ephemeral_id": "2832b75e-6338-4996-9c3f-80a0c6894fd2",
      "id": "b29fc13d-367e-4372-a530-17ca28ce69ff",
      "name": "skynet"
    }
  },
  "fields": {
    "host.os.name.text": [
      "Windows Server 2016 Datacenter"
    ],
    "winlog.event_data.IpAddress": [
      "::1"
    ],
    "winlog.provider_name": [
      "Microsoft-Windows-Security-Auditing"
    ],
    "winlog.provider_guid": [
      "{54849625-5478-4994-A5BA-3E3B0328C30D}"
    ],
    "host.hostname": [
      "skynet"
    ],
    "winlog.computer_name": [
      "skynet.skynet.local"
    ],
    "host.mac": [
      "42:01:0a:80:00:17",
      "00:00:00:00:00:00:00:e0",
      "00:00:00:00:00:00:00:e0"
    ],
    "winlog.process.pid": [
      4
    ],
    "cloud.availability_zone": [
      "us-central1-a"
    ],
    "winlog.event_data.ShareName": [
      "\\\\*\\Engineering (ITAR)"
    ],
    "winlog.keywords": [
      "Audit Success"
    ],
    "host.os.version": [
      "10.0"
    ],
    "winlog.record_id": [
      "116140907"
    ],
    "host.os.name": [
      "Windows Server 2016 Datacenter"
    ],
    "log.level": [
      "information"
    ],
    "agent.name": [
      "skynet"
    ],
    "host.name": [
      "skynet.skynet.local"
    ],
    "event.kind": [
      "event"
    ],
    "event.outcome": [
      "success"
    ],
    "winlog.version": [
      1
    ],
    "winlog.event_data.AccessMask": [
      "0x1"
    ],
    "host.os.type": [
      "windows"
    ],
    "winlog.event_data.IpPort": [
      "62594"
    ],
    "agent.hostname": [
      "skynet"
    ],
    "host.architecture": [
      "x86_64"
    ],
    "event.provider": [
      "Microsoft-Windows-Security-Auditing"
    ],
    "cloud.provider": [
      "gcp"
    ],
    "cloud.machine.type": [
      "e2-medium"
    ],
    "event.code": [
      "5140"
    ],
    "agent.id": [
      "b29fc13d-367e-4372-a530-17ca28ce69ff"
    ],
    "ecs.version": [
      "1.8.0"
    ],
    "event.created": [
      "2022-02-03T18:51:05.143Z"
    ],
    "agent.version": [
      "7.12.0"
    ],
    "host.os.family": [
      "windows"
    ],
    "winlog.event_data.SubjectUserSid": [
      "S-1-5-21-4256129798-270769626-1418745944-1109"
    ],
    "winlog.process.thread.id": [
      11816
    ],
    "host.os.build": [
      "14393.4886"
    ],
    "host.ip": [
      "10.128.0.23",
      "fe80::5efe:a80:17",
      "fe80::ffff:ffff:fffe"
    ],
    "cloud.instance.id": [
      "5957135645790541702"
    ],
    "winlog.event_data.AccessList": [
      "%%4416\n\t\t\t\t"
    ],
    "agent.type": [
      "winlogbeat"
    ],
    "winlog.event_data.SubjectLogonId": [
      "0x172b499c"
    ],
    "host.os.kernel": [
      "10.0.14393.4886 (rs1_release.220104-1735)"
    ],
    "winlog.api": [
      "wineventlog"
    ],
    "host.id": [
      "02204c11-8982-468a-b4a9-535251873a58"
    ],
    "winlog.task": [
      "File Share"
    ],
    "winlog.event_data.ObjectType": [
      "File"
    ],
    "winlog.event_data.SubjectUserName": [
      "baltar"
    ],
    "message": [
      "A network share object was accessed.\n\t\nSubject:\n\tSecurity ID:\t\tS-1-5-21-4256129798-270769626-1418745944-1109\n\tAccount Name:\t\tbaltar\n\tAccount Domain:\t\tSKYNET1\n\tLogon ID:\t\t0x172B499C\n\nNetwork Information:\t\n\tObject Type:\t\tFile\n\tSource Address:\t\t::1\n\tSource Port:\t\t62594\n\t\nShare Information:\n\tShare Name:\t\t\\\\*\\Engineering (ITAR)\n\tShare Path:\t\t\\??\\C:\\Shares\\Engineering (ITAR)\n\nAccess Request Information:\n\tAccess Mask:\t\t0x1\n\tAccesses:\t\tReadData (or ListDirectory)\n\t\t\t\t"
    ],
    "winlog.event_id": [
      "5140"
    ],
    "winlog.event_data.ShareLocalPath": [
      "\\??\\C:\\Shares\\Engineering (ITAR)"
    ],
    "event.action": [
      "File Share"
    ],
    "@timestamp": [
      "2022-02-03T18:51:03.941Z"
    ],
    "winlog.channel": [
      "Security"
    ],
    "host.os.platform": [
      "windows"
    ],
    "cloud.account.id": [
      "elastic-siem"
    ],
    "winlog.opcode": [
      "Info"
    ],
    "agent.ephemeral_id": [
      "2832b75e-6338-4996-9c3f-80a0c6894fd2"
    ],
    "winlog.event_data.SubjectDomainName": [
      "SKYNET1"
    ],
    "cloud.project.id": [
      "elastic-siem"
    ],
    "cloud.instance.name": [
      "skynet"
    ]
  }
}`
