### ISSUE TITLE
[8.0] AWS & 1Password Integrations are creating Index field conflicts

### ISSUE THREAD

**Issue by zikphil** [elastic/integrations#2684]
From a vanilla installation when I enabled the following integrations:
- 1Password
- AWS
- ~Kubernetes~

I get field conflicts when viewed from 'Data View' in Kibana. See screenshots.

<img width="772" alt="CleanShot 2022-02-11 at 16 53 30@2x" src="https://user-images.githubusercontent.com/1538854/153675655-8e0c8c9b-1c9d-41ea-b051-ce468d5e761e.png">

<img width="775" alt="CleanShot 2022-02-11 at 16 53 15@2x" src="https://user-images.githubusercontent.com/1538854/153675660-e6572993-a3e1-4339-b43b-bf8753ec39b6.png">

<img width="1124" alt="CleanShot 2022-02-11 at 16 55 29@2x" src="https://user-images.githubusercontent.com/1538854/153675745-20d833e1-59d6-4834-8033-abd7434d488e.png">

**Comment by andrewkroh** [comment]
Thanks for the detailed report. You mentioned k8s but I didn’t see that in any of the images?

**Comment by legoguy1000** [comment]
Opened a PR for AWS and 1Password.  I guess still need the K8S conflicts.
