### ISSUE TITLE
Add data_stream fields to ECS

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#270]
The fields `data_stream.type`, `data_stream.dataset` and `data_stream.namespace` are used as the foundation of the new indexing strategy. These should also be added to ECS.

**Comment by ph** [comment]
@webmat Is that something that you could take in your team?

**Comment by webmat** [comment]
This is already in progress via the RFC process here https://github.com/elastic/ecs/pull/980

**Comment by ph** [comment]
Oh wow thanks @roncohen

**Comment by ebeahan** [comment]
The [`data_stream.*` fields RFC ](https://github.com/elastic/ecs/blob/master/rfcs/text/0009-data_stream-fields.md) has advanced to finished, and its changes are being implemented to the schema in https://github.com/elastic/ecs/pull/1307.
