### ISSUE TITLE
Typos in modsecurity integrations

### ISSUE THREAD

**Issue by lcawl** [elastic/integrations#2728]
There are a few places where "modsecurity" is misspelled:

- https://docs.elastic.co/en/integrations/modsecurity see "ModSecuirty" 
- https://github.com/elastic/integrations/blob/main/packages/modsecurity/manifest.yml see "description: "ModSecuirty Audit Log Integration"
- https://github.com/elastic/integrations/blob/main/packages/modsecurity/_dev/build/docs/README.md see "Modsecuriy Integration"

**Comment by olivia-zh-xm** [comment]
I will work on this and submit pr later.

**Comment by michael12312** [comment]
@lcawl 
I will fix this and submit PR later.
