### ISSUE TITLE
Test kubernetes integration (package & features) against ECK and helm-charts

### ISSUE THREAD

**Issue by ChrsMark** [elastic/integrations#2734]
At the moment we only test our kubernetes integration by testing the kubernetes package itself under integrations repository through the elastic-package capabilities: https://github.com/elastic/integrations/tree/main/packages/kubernetes
In addition we test Autodiscover features with the e2e suite (https://github.com/elastic/e2e-testing/tree/main/e2e/_suites/kubernetes-autodiscover/features) under Beats repository.

It would be useful to have the package and autodiscover feature tested with ECK and heml-charts too.

cc: @elastic/obs-cloudnative-monitoring @elastic/observablt-robots @ruflin

**Comment by akshay-saraswat** [comment]
cc: @ruflin
