### ISSUE TITLE
Darktrace

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#2754]
### Description
Darktrace's Enterprise Immune System uses proprietary machine learning and AI algorithms to build a so-called "pattern of life" for every network, device, and user within an organization. It then employs correlation techniques to classify and cross-reference these models, establishing a highly accurate understanding of 'normal activity' within that particular environment. From this evolving understanding of 'normal', it can then detect potential threats as they emerge in real time.

### Architecture
Darktrace supports an alert output in JSON format. 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by RobertGleaden** [comment]
+1 Would like to see this

**Comment by jamiehynds** [comment]
Thanks for the +1 @RobertGleaden. We've had some discussions with Darktrace and will be starting development on an integration soon. Will update this ticket as soon as it's available. Look forward to getting your feedback when the integration ships.

**Comment by craiglawson** [comment]
Adding a +1 to follow this issue

**Comment by gils3nan** [comment]
Adding +1 - would be a cool integration to have

**Comment by jamiehynds** [comment]
@RobertGleaden @craiglawson @gils3nan PR for Darktrace has been raised (see above). Will let you know as soon as it's merged and the integration becomes available :)

**Comment by RobertGleaden** [comment]
Nice! This is awesome! Thanks!

**Comment by craiglawson** [comment]
Good timing, we have a client requiring this integration in September

**Comment by aletsche** [comment]
We have a client requiring this integration in September or October as well

**Comment by jamiehynds** [comment]
@RobertGleaden @craiglawson @gils3nan @aletsche - the Darktrace integration is now available. It requires Elastic v8.2.1 or later, so provided you meet that criteria, you should be able to see it within the integrations page in Kibana. Please let us know how it goes once you enable it, any feedback would be greatly appreciated :)
