### ISSUE TITLE
[Fleet] Perform and Document tests for System Integration package (all of the various metrics and logs that can be collected)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/integrations#276]
This ticket is implemented to go deeper on what support is already in the Ingest Manager / Fleet & Agent tests.  We have little so far, and we need more.  So I'll itemize the items that I see in the Integration that we can add.  

Note, not all of the below are turned on by default, so a policy change in those cases is required as part of the scenario.  To be safer, we could put in a 'set this option if not set' step.  Asserting which are on or off by default itself could be a useful test, but maybe not very interesting or error prone (not sure).  

-------------
Logs:

- [ ] System auth logs (log) - /var/log/auth.log*  or /var/log/secure*

- [ ] System syslog logs (log) - /var/log/messages* or /var/log/syslog*

Metrics
- [x] System core metrics
- [x] System cpu metrics
- [ ] System diskio metrics
- [ ] System entropy metrics
- [ ] System filesystem metrics
- [ ] System fsstat metrics
- [ ] System load metrics
- [ ] System network metrics
- [ ] System network summary metrics
- [ ] System process_summary metrics
- [ ] System raid metrics
- [ ] System service metrics
- [ ] System socket metrics
- [ ] System socket_summary metrics
- [ ] System uptime metrics
- [ ] System users metrics

**Comment by fearful-symmetry** [comment]
Sorry, I'm just jumping into the conversation here, what we need is docs for the various optional config fields and example valid values?

**Comment by EricDavisX** [comment]
I appreciate you jumping in, I tried to summarize... thanks Alex.  Yes, that would help. I also admit that we'll currently be making assumptions about the ES doc details that will come in... like how to verify the changes and how to ensure the docs are ingested that relate to a given option.  Its a big question and basically amounts to training us up about what this feature is that we've implemented.  So thank you for your time and patience.  :)

A separate question is, do you think there is value in trying any negative input values?  Like do you wish us to try to 'break' the Integration or do we know it will fail in a given way if the input isn't in an expected format?

Thanks

**Comment by fearful-symmetry** [comment]
Yah, a lot of these small options aren't well documented, and it's almost a UX issue first. I've tried to fix some of the Integration config where it's not clear what a given dataset config is supposed to be, but "clear" might be a tad relative. I wonder if the best place to start is to spin up a cluster and test that first.


> A separate question is, do you think there is value in trying any negative input values? Like do you wish us to try to 'break' the Integration or do we know it will fail in a given way if the input isn't in an expected format?

That question is probably a tad above my pay grade. Right now we _know_ that Fleet isn't very good at sending errors up to the users, so if you break things there's going to be some ugliness. Those will also be errors in metricbeat itself, which is something we've tested much more.

**Comment by EricDavisX** [comment]
@fearful-symmetry - I agree, we could discuss it at the Ingest level for how to push UX on this.  I don't know what priority that will be. 

And regarding testing, we can certainly test and report back what we find, if its ugly and known then its not a surprise, but if it breaks in a new way it may be helpful to know.  @ph whats your guidance here?  We can do more tests and just see what comes, as an easy start if you agree.

**Comment by muskangulati-qasource** [comment]
Hi @EricDavisX , 

We did tested for the optional fields and provided input as numerical, strings and special characters(Also combination of the three). But there was no validation on UI. Also we could successfully update the policy by enabling the toggle for each field having random inputs(Eg : 12@yhi or negative numericals).

Please do keep us posted on how to validate the required & optional fields and also what documents to look into or to trigger when we update these fields. 

Thanks!

**Comment by fearful-symmetry** [comment]
A lot of these problems are fundamental to fleet. UI input validation, sending backend errors up to the user, and so on.

**Comment by EricDavisX** [comment]
Hi thanks Muskan and Alex.  I want to confirm, we do not expect input validation to change, it is a separate concern.  We should be able to set the values and see the expected changes occur.  

Any help with that is appreciated, and I am checking with PH as to how he wants to prioritize this depth of testing for now.

**Comment by EricDavisX** [comment]
Hi, I spoke with @ph and we decided to call this good enough for now.  @muskangulati-qasource fyi.  we did good.  :)  

The question of ownership over this package is mostly clear, the Ingest Manager / Fleet team will help test it (always) but we will also defer some of the depth of the testing on it to the Integrations team who are (other folks beyond Alex) working to get all of the Integrations tested in a new automation framework.  So, that can expect to cover the final depth of testing we're talking about.
 
Along with that, the System Integration is being refactored for a coming release (tbd) and when it is ready for testing we can re-open the question of documenting the options that still exist (I think some options may be trimmed out to enhance usability and clarity) and we can work with Alex and team at that time.  For now... I'm closing this out, as good enough and done.  Thanks again!

**Comment by EricDavisX** [comment]
I had a quick chat with Jason about our environment cert testing and with Alex about the System Integration as part of that testing and am re-opening this now as we have re-factored System package and are shipping it out and we want to re-do some amount of tests, and add test content to document it.  I have updated the short desc for this and assigned @rahulgupta-qasource.

I'll send an email with more details, but the short start is that - I want to add a row in the testrail file for each field [ ] bullet point above, and we can therefore communicate which are covered manually.

**Comment by rahulgupta-qasource** [comment]
Hi Eric

We have validated the ticket on 7.10 BC4 Kibana cloud environment and 7.10.0 BC4 agent with system integration 0.9.0

Created 13 testcases under section https://elastic.testrail.io/index.php?/suites/view/27&group_by=cases:section_id&group_order=asc&group_id=9196
and executed them under Testrun https://elastic.testrail.io/index.php?/runs/view/816&group_by=cases:section_id&group_order=asc

Please let us know if anything is missing from our end.

**Comment by EricDavisX** [comment]
@rahulgupta-qasource thanks for our chat. This coverage is great - for ease of review:
 the test content cites 13 separate test cases for different fields and whether or not it is available on Windows / mac / Linux.  The test also cites that it will be run on (up to) 3 separate Kibana cloud instances (depending on if we want to run all of OSes).  This way the data-streams can be validated independently of each other, and the field data in the documents is much easier to review.

The team reports it takes... approximately an hour to run the test against 1 OS (abou5 2.5 hr for all 3).

The next step I'd like to take is to increase the coverage we have documented and tested to include:
 turning off/ and on the different fields, and setting any of the specific values that we can reasonably validate (some are hard like the RAID system values).  Let us just add what we can and evaluate again.  

Thank you!

**Comment by rahulgupta-qasource** [comment]
Hi Eric 

Thank you for sharing the feedback.

We have validated the ticket on 7.10 BC4 Kibana cloud environment and 7.10.0 BC4 agent with system integration 0.9.0

As we have 14 fields in total(for logs and metrics under System integration), hence we have created a separate testcase for auth and syslogs fields to have a testcase per each field.

Moreover, we have created 14 separate testcases for validating the logs and metrics by turning OFF and ON each field under System integration and executed them under Turn OFF and ON different fields of 0.9.0 system integration
https://elastic.testrail.io/index.php?/runs/view/818&group_by=cases:section_id&group_order=asc  

Observations:
1. RAID metrics is not available in 0.9.0 System Integration. Following are the 12 supported metrics datasets as per System integration detail page:
https://efe9e264de294909884de338855436ee.europe-west1.gcp.cloud.es.io:9243/app/ingestManager#/integrations/detail/system-0.9.0

(a) core
(b) cpu
(c) diskio
(d) filesystem
(e) fsstat
(f) load
(g) memory
(h) network
(i) process
(j) process summary
(k) socket summary
(l) uptime

2. We have provided and changed the value in period field for above datasets and found that the data did not updated for that particular data streams until it crossed the period time provided.

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource Let us re-confirm if there is anything for 7.11+ System / Windows / Linux Integration that we want to document from this ticket and then we can close it out as done done done.

**Comment by EricDavisX** [comment]
I believe the manual test content is updated with this and it has changed / is ever-evolving little by little anyhow - and Alex is part of the Data Control plane team in Agent so this should be the same covered regularly and get a good focus.  with no updates on this in about a year I am closing it out as testing done.
