### ISSUE TITLE
Fix use of removed fields in Kafka dashboard in 8.x

### ISSUE THREAD

**Issue by jsoriano** [elastic/integrations#2770]
Some deprecated fields removed in 8.0 are still being used in some dashboards. These fields were replaced by other fields in previous versions.

At least the following changes need to be done:
* `kafka.consumergroup.topic` -> `kafka.topic.name`
* `kafka.partition.broker.id` -> `kafka.broker.id`

These fixes need to be done Beats and in the Kafka package. 

Fields were removed from beats in https://github.com/elastic/beats/pull/27938

**Comment by lalit-satapathy** [comment]
Also: - kafka.consumergroup.partition -> kafka.partition.id
