### ISSUE TITLE
Elastic-Agent Kafka Integration event.created mapping

### ISSUE THREAD

**Issue by iamhowardtheduck** [elastic/integrations#2782]
### Description

The Kafka integration for Elastic-Agent lacks mapping for the event.created field and causes conflicts when used with other integrations; will you please update the mapping?  Confirmed in version 8.0.0

**Comment by kaiyan-sheng** [comment]
@iamhowardtheduck Thanks for reporting this issue! Do you have a specific data stream(broker or consumergroup or log or partition) you are using in Kafka integration? 

I looked at the kafka integration and found `event.created` is missing (along with several other `event.*` fields) in `log` data stream.

**Comment by iamhowardtheduck** [comment]
Yes, this is the native logs-kafka integration, I've found others as well with logs-ti_abusech.malware & logs-ti_abusech.malwarebazaar (missing: event.created, event.id, event.start & event.end.

Would it be possible to just include every ECS field within the logs index and/or component template?  That way every dataset already has the predefined & synchronized ECS mapping?

![image](https://user-images.githubusercontent.com/11168913/157239021-f864c639-1f69-43b0-a35d-273c3f50bd9b.png)

Which causes:
![image](https://user-images.githubusercontent.com/11168913/157239930-d9d0b8cf-3c9e-4950-8e1c-a2e30e923441.png)

**Comment by iamhowardtheduck** [comment]
The logs-cef.log integration also has this issue.

**Comment by iamhowardtheduck** [comment]
![image](https://user-images.githubusercontent.com/11168913/157241582-5a9a47de-fc44-4273-8d32-8fc972aab426.png)

**Comment by kaiyan-sheng** [comment]
Hi @iamhowardtheduck , thanks for the comments. We don't include the whole ECS mainly because the size of all the fields will be introduced. When users use a specific integration, these mappings will be installed first. If we chose to include all ECS fields in all integrations, then it will be a very heavy load for the users for a lot of fields they don’t even need. 

Could you open a new issue for the other integrations that are missing fields please? Let's keep this one for Kafka only. Thank you!!

**Comment by iamhowardtheduck** [comment]
Will do @kaiyan-sheng, issues opened are:

CEF
[https://github.com/elastic/integrations/issues/2805](https://www.google.com/url?q=https://github.com/elastic/integrations/issues/2805&sa=D&source=calendar&ust=1647296237422764&usg=AOvVaw2GKJIj07N9rioDxrmwTI3G)

AbuseCH
[https://github.com/elastic/integrations/issues/2807](https://www.google.com/url?q=https://github.com/elastic/integrations/issues/2807&sa=D&source=calendar&ust=1647296237422764&usg=AOvVaw2BMUjrdvAftICH94KI53Ke)
