### ISSUE TITLE
Elastic-Agent Kafka Integration event.created mapping

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#2783]
## Description

The Kafka integration for Elastic-Agent lacks mapping for the event.created field and causes conflicts when used with other integrations; will you please update the mapping? Confirmed in version 8.0.0

This issue is originally reported by @iamhowardtheduck in https://github.com/elastic/elasticsearch/issues/84167

**Comment by kaiyan-sheng** [comment]
The original issue has been transferred into the integrations repo. I will close this issue then!

**Comment by andrewkroh** [comment]
Relates: https://github.com/elastic/elastic-package/issues/147
