### ISSUE TITLE
Infoblox Logs: log host.name missing / used for wrong data?

### ISSUE THREAD

**Issue by ulab** [elastic/integrations#2796]
Hello,

we think the `host.name` field might be used for the wrong values in this integration.

According to the [ECS documentation](https://www.elastic.co/guide/en/ecs/current/ecs-host.html), 

> ECS host.* fields should be populated with details about the host on which the event happened, or from which the measurement was taken. 

We understand this as the host the log data is coming from and regularly use it as filter to single out log sources.

Instead the integration uses this field for the hostname of a client an action is based upon (for example a `DHCPREQUEST`).

Since we are not ECS experts, we are not sure what field to use instead, but feel the `client` fields might be more appropriate since it is a client asking the DHCP server for a lease.

The hostname itself is parsed, since it lands in the `related.hosts` field.

**Comment by jamiehynds** [comment]
@ulab thanks for your suggestion. We've actually just developed a new Infoblox integration, which will replace the current integration which has been in Tech Preview for some time. As you can see in the pipeline ([here](https://github.com/elastic/integrations/blob/main/packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dhcp.yml#L28)), `DHCPREQUEST` events are now using the `client` fields as suggested. 

The integration is currently on Github, but will available within Kibana very soon. https://github.com/elastic/integrations/tree/main/packages/infoblox_nios
