### ISSUE TITLE
support all available fields in AWS VPC flow logs for vpcflow logs integration

### ISSUE THREAD

**Issue by milanage** [elastic/integrations#2821]
Currently AWS VPC flow logs integration supports up to 21 fields - the integration won't work properly if the VPC flow logs enable all 29 fields. 

Can we make the integration to support all fields?

**Comment by felix-lessoer** [comment]
That would be great.
Here is one example with more than 21 fields that don't work at all with v1.12.1

`5 vpc-09676f97xxxxxb8a7 subnet-02d645xxxxxxxdbc0 i-0axxxxxx1ad77 eni-069xxxxxb7a490 64xxxxx7617 IPv4 138.000.000.248 10.200.0.0 50041 33004 138.000.000.248 10.200.0.80 17 52 1 164000066 1640000297 REJECT 0 OK ingress us-east-1 use1-az5`

**Comment by legoguy1000** [comment]
Any fields that aren't included in the default would be difficult as the integration has no way to know what additional fields were added by the user. No good way to plan for that unless there is a default format that includes all the fields??

**Comment by andrewkroh** [comment]
The flexibility in the format is problematic in that we cannot easily support an infinite set of log formats. The integration could document that is accepts the default format and one other format that includes all of the fields available today. That format would be listed in the readme for the user to copy into their AWS config if they want get all fields.

Then the pipeline just needs to be able to handle the two formats automatically, which I think is reasonable.

**Comment by legoguy1000** [comment]
Do we have an example of a pattern with all the fields??

**Comment by andrewkroh** [comment]
Based on this list of 29 fields extracted from https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html#flow-logs-fields

- version
- account-id
- interface-id
- srcaddr
- dstaddr
- srcport
- dstport
- protocol
- packets
- bytes
- start
- end
- action
- log-status
- vpc-id
- subnet-id
- instance-id
- tcp-flags
- type
- pkt-srcaddr
- pkt-dstaddr
- region
- az-id
- sublocation-type
- sublocation-id
- pkt-src-aws-service
- pkt-dst-aws-service
- flow-direction
- traffic-path

the format would be:

`${version} ${account-id} ${interface-id} ${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${packets} ${bytes} ${start} ${end} ${action} ${log-status} ${vpc-id} ${subnet-id} ${instance-id} ${tcp-flags} ${type} ${pkt-srcaddr} ${pkt-dstaddr} ${region} ${az-id} ${sublocation-type} ${sublocation-id} ${pkt-src-aws-service} ${pkt-dst-aws-service} ${flow-direction} ${traffic-path}`

I haven't tested that flow format in AWS.

**Comment by legoguy1000** [comment]
PR opened using the pattern above
