### ISSUE TITLE
modsecurity integration is missing from Kibana

### ISSUE THREAD

**Issue by stefanpinter** [elastic/integrations#2832]
Hi!

I remember seeing the experimental integration of modsecurity in Kibana/Elasticsearch integrations but it is gone for a few weeks now... I guess this depends on a central repository where something is wrong and all I can do is telling you, right?

It would be very great if I could try this integration! 

Thank you!

**Comment by P1llus** [comment]
I am pushing out a fix for this, as there is currently no version requirements for 8.x on the package.

Once it merges and the issue closes, it should be available in kibana a little while later

**Comment by P1llus** [comment]
The package is now available @stefanpinter :)

**Comment by stefanpinter** [comment]
thank you @P1llus :)
i installed it already (modsecurity 2 with apache though) but it doesn't give me many new fields to work with :(
how can I troubleshoot this?

> The package is now available @stefanpinter :)
