### ISSUE TITLE
[google_workspace] Add config option alternatives that don't depend on reading local files

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#2834]
As a user I'd like to fully configure the integration through Fleet. Currently the `jwt_file` setting require writing a local file to the host running Elastic Agent. I would like to be able to put that data into the Fleet UI so I can more easily deploy the integration.

**Comment by insukcho** [comment]
I would like to see this feature! Much better UX without considering where the user should put the file, physically!

**Comment by efd6** [comment]
A possible option for this is to first try the stat the string that is provided by the user as a path and if that fails, but the string is a valid JSON value, treat it as a JWT. This would retain backwards compatibly for all sensible™ file paths that people might have used, but would require some additional documentation to explain.

**Comment by legoguy1000** [comment]
Why not just create a new configuration option for an online jwt file contents?? It follows the pattern that already exists with the credential_file and credential_json options.
