### ISSUE TITLE
Create IBM Websphere Application Server Integration

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#2847]
[WebSphere Application Server (WAS)](https://www.ibm.com/products/software) is a software framework and middleware that hosts [Java](https://www.java.com/en/) based web applications. It is the flagship product within IBM's WebSphere software suite. Elastic and IBM's shared customers would like to integrate these softwares and ingest the following data via Elastic Agent

#### Metrics
- JMX metrics
- JDBC metrics
- ThreadPool metrics
- System metrics
- Servlet metrics
- Session Manager metrics

#### Logs
- Logging events
- Server logs (status, trace, error, and exception logs)

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

**Comment by kush-elastic** [comment]
Hey @akshay-saraswat,
There are few questions/queries. can you help me with those?
1. We researched a bit in IBM Websphere Application Server and wanted confirmation on which repositories to focus on from below: [Main Link](https://www.ibm.com/cloud/blog/websphere-trial-options-and-downloads)
    - [WebSphere Liberty repository](https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_ins_repositories.html)
    - [Traditional WebSphere repository](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_9.0.5/com.ibm.websphere.installation.base.doc/ae/cins_repositories.html)
    Note: Please look at offerings both provide from this links.
2. We have setup and configured [Traditional WebSphere repository](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_9.0.5/com.ibm.websphere.installation.base.doc/ae/cins_repositories.html). To collect metrics from WebSphere Application Server, we need to enable [metrics.ear](https://www.ibm.com/docs/en/was/9.0.5?topic=mosh-displaying-pmi-metrics-in-prometheus-format-metrics-app) application runtime from admin console. It enables us to collect Below mentioned metrics. plus those metrics comes in as Prometheus format. We can collect those using Prometheus Metricbeat Module. is that ok with you?
    - JDBC metrics
    - ThreadPool metrics
    - System metrics
    - Servlet metrics
    - Session Manager metrics
3. We found below mentioned MBeans from that are available in JMX. Can you let us know which ones to focus for the current scope?:
    - #domain = IBM MQ:
        - IBM MQ:name=PropertyStoreControl,type=CommonServices
        - IBM MQ:name=TraceControl,type=CommonServices
    - #domain = JMImplementation:
        - JMImplementation:type=MBeanServerDelegate
    - #domain = WebSphere:
        - WebSphere:name=LeakAdmin,type=MemoryLeakAdmin
        - WebSphere:name=LeakConfig,type=MemoryLeakConfig
    - #domain = com.ibm.lang.management:
        - com.ibm.lang.management:type=JvmCpuMonitor
    - #domain = com.ibm.virtualization.management:
        - com.ibm.virtualization.management:type=GuestOS
        - com.ibm.virtualization.management:type=Hypervisor
    - #domain = java.lang:
        - java.lang:name=J9 non-heap manager,type=MemoryManager
        - java.lang:name=JIT code cache,type=MemoryPool
        - java.lang:name=JIT data cache,type=MemoryPool
        - java.lang:name=class storage,type=MemoryPool
        - java.lang:name=global,type=GarbageCollector
        - java.lang:name=miscellaneous non-heap storage,type=MemoryPool
        - java.lang:name=nursery-allocate,type=MemoryPool
        - java.lang:name=nursery-survivor,type=MemoryPool
        - java.lang:name=scavenge,type=GarbageCollector
        - java.lang:name=tenured,type=MemoryPool
        - java.lang:type=ClassLoading
        - java.lang:type=Compilation
        - java.lang:type=Memory
        - java.lang:type=OperatingSystem
        - java.lang:type=Runtime
        - java.lang:type=Threading
    - #domain = java.nio:
        - java.nio:name=direct,type=BufferPool
        - java.nio:name=mapped,type=BufferPool
    - #domain = java.util.logging:
        - java.util.logging:type=Logging
    - #domain = openj9.lang.management:
        - openj9.lang.management:type=OpenJ9Diagnostics
    - #domain = org.apache.logging.log4j2:
        - org.apache.logging.log4j2:component=Appenders,name=CONSOLE,type=9558b54a
        - org.apache.logging.log4j2:component=Appenders,name=ERROR,type=9558b54a
        - org.apache.logging.log4j2:component=Appenders,name=FILE,type=9558b54a
        - org.apache.logging.log4j2:component=ContextSelector,type=9558b54a
        - org.apache.logging.log4j2:component=Loggers,name=,type=9558b54a
        - org.apache.logging.log4j2:component=StatusLogger,type=9558b54a
        - org.apache.logging.log4j2:type=9558b54a

Let me know if you have any doubts.
Thanks

**Comment by kush-elastic** [comment]
Hey @akshay-saraswat,
As per our analysis so far we found that there are 2 types of repositories available with IBM WebSphere Application Server,
1. [Traditional](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_9.0.5/com.ibm.websphere.installation.base.doc/ae/cins_repositories.html)
2. [Liberty](https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_ins_repositories.html)

As we are able to collect all those metrices listed here in the Traditional edition but in Liberty we are still not getting required metrics mentioned in PRD.
so as per this integration scope, need to confirm if we can proceed with traditional repository.

**Comment by akshay-saraswat** [comment]
> We researched a bit in IBM Websphere Application Server and wanted confirmation on which repositories to focus on

Traditional variant is more popular and prevalent than Liberty as far as I know. And none of our customer enhancement requests for WAS mention liberty which is a more specific and newer variant. [Referring to this for the current state of adoption](https://stackshare.io/stackups/websphere-vs-websphere-liberty).

> We have setup and configured [Traditional WebSphere repository](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_9.0.5/com.ibm.websphere.installation.base.doc/ae/cins_repositories.html). To collect metrics from WebSphere Application Server, we need to enable [metrics.ear](https://www.ibm.com/docs/en/was/9.0.5?topic=mosh-displaying-pmi-metrics-in-prometheus-format-metrics-app) application runtime from admin console. It enables us to collect Below mentioned metrics. plus those metrics comes in as Prometheus format. We can collect those using Prometheus Metricbeat Module. is that ok with you?

If we are receiving the data in Prometheus format only then I believe we don't have an option. We'll have to go for the Prometheus module. @mtojek do you have any suggestions or concerns about that?

> We found below mentioned MBeans from that are available in JMX. Can you let us know which ones to focus for the current scope?

I think we should support all of them and let the customer select which one of these they want to enable or disable because all of these domains provide different data and could cater to different use-cases depending on the target user persona as far as I know. But if it is not possible to collect all of them or if we are looking for a set of enabled domains by default, please consider these -  java.lang and com.ibm.lang.management

**Comment by mtojek** [comment]
I'm not sure if we need two channels of metrics to support if there is any of them enabled by default, either JMX or Prometheus. Is that the thing here?

If not, then I don't have a preference, whatever is easier to implement.
