### ISSUE TITLE
non-existing aws.billing.metrics.EstimatedCharges.max field referenced in AWS integration visualizations

### ISSUE THREAD

**Issue by gbanasiak** [elastic/integrations#2848]
In https://github.com/elastic/integrations/pull/1606 `aws.billing.metrics.EstimatedCharges.max` field was changed to `aws.billing.metrics.EstimatedCharges`, but the following visualisations were not fixed:
* [Top 10 Billing per Service Name [Metrics AWS]](https://github.com/elastic/integrations/blob/5176089e30cf2932d6e5ca7c90caa2ab9a237bee/packages/aws/kibana/visualization/aws-31a4ea90-152b-11ea-841c-01bf20a6c8ba.json)
* [Estimated Billing Pie Chart [Metrics AWS]](https://github.com/elastic/integrations/blob/5176089e30cf2932d6e5ca7c90caa2ab9a237bee/packages/aws/kibana/visualization/aws-749cd470-1530-11ea-841c-01bf20a6c8ba.json)

This broke viz and `[Metrics AWS] Billing Overview` dashboard.

**Comment by craiglawson** [comment]
Thanks for raising @gbanasiak

**Comment by kaiyan-sheng** [comment]
This is fixed by https://github.com/elastic/integrations/pull/2946.
