### ISSUE TITLE
[ti_anomali] Type conflicts for threat.indicator.file.x509.not_after / not_before

### ISSUE THREAD

**Issue by iamhowardtheduck** [elastic/integrations#2852]
The Anomali integration does not include the following mappings in the Security Data View:

-threat.indicator.file.x509.not_after 
-threat.indicator.file.x509.not_before

This was configuration was established with 8.0 then migrated to 8.1; possible that it did not propagate during upgrade? 

![image](https://user-images.githubusercontent.com/11168913/159142159-d4f4e8e4-c1e3-476d-b9ca-760c4220179c.png)

**Comment by andrewkroh** [comment]
@iamhowardtheduck I looked at the pipelines for the Anomali integration and did not find any locations where those two mentioned fields are generated. Can you confirm the indices that contain the conflicts by using the fields API.

`GET logs*/_mapping/field/threat.indicator.file.x509.not_after`

`GET logs*/_mapping/field/threat.indicator.file.x509.not_before`

**Comment by andrewkroh** [comment]
The only place I found those fields used is with the AbuceCH integration and the mapping is correct since 1.2.1.

https://github.com/elastic/integrations/blob/eeae688e1b52261b7b351aeb95294b2f29baf2bb/packages/ti_abusech/changelog.yml#L12-L16

**Comment by andrewkroh** [comment]
I cannot reproduce so I'm closing. If you are still having the issue please provide the mapping info requested [above](https://github.com/elastic/integrations/issues/2852#issuecomment-1102518397) to help diagnose.
