### ISSUE TITLE
[gcp] GKE audit log data differs between GCP integrations

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/integrations#2857]
My colleague and I discovered, while building a lab for developing k8 detections, that the GCP generic pub-sub integration provides the full scope of k8 audit data, required to detect malicious or suspicious behavior, while the GCP audit integration only provides a small subset of that data. The GCP generic pub-sub integration supplies the needed data but it does not map the data to fields in ECS leaving it all condensed together in the message field essentially making it useless in regards to writing any detection logic or analysis. The GCP audit integration on the other hand, like I said, supplies only a small subset of the data provided by the GKE audit logs leaving out many critical data fields required for observability and security. Below I have included events from both integrations as an example. You can see that the GCP generic pub-sub k8 audit log event message field contains a great deal more data than the GCP audit log event fields provide. 

[GCP generic pub-sub](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-gcp.html) k8 audit log event:
[gcp-gen-pub-sub-event.txt](https://github.com/elastic/integrations/files/8319125/gcp-gen-pub-sub-event.txt)

vs.

[GCP audit](https://docs.elastic.co/en/integrations/gcp#audit) log event:
[gcp-audit-event.txt](https://github.com/elastic/integrations/files/8319130/gcp-audit-event.txt)

**Comment by andrewkroh** [comment]
> You can see that the GCP generic pub-sub k8 audit log event message field contains a great deal more data than the GCP audit log event fields provide.

The integration should not matter here. The raw data read from Pub/Sub should be same no matter if it's read by the `gcp.audit` or the `gcp_pubsub.generic` data streams. The difference lies in the Ingest Pipelines. The generic data stream doesn't apply any processing and the `gcp.audit` one doesn't pass through some of the data from the `event.original` value.

I ran the raw data from the two events through the `gcp.audit` 1.4.2 pipeline and [attached](https://github.com/elastic/integrations/files/8319320/test-audit-gke.log-expected.json.txt) the output. There's data in the original event that's not represented anywhere else.

I think two things should be done:

1. Preserve data that is not used elsewhere in a [flattened](https://www.elastic.co/guide/en/elasticsearch/reference/current/flattened.html) field.
2. Add ECS mappings for the k8s audit log data.

Attachments

- [test-audit-gke.log-expected.json.txt](https://github.com/elastic/integrations/files/8319320/test-audit-gke.log-expected.json.txt)

**Comment by DefSecSentinel** [comment]
Definitely, strongly agree. What are next steps, who will take on those tasks and what does that timeline look like?

**Comment by andrewkroh** [comment]
I have added it to the planning board of the security-external-integrations team for 8.3. But anyone is welcome to pick it up if they are interested.

**Comment by r00tu53r** [comment]
I have addressed these and some refactoring in the PR #3390.

> Preserve data that is not used elsewhere in a [flattened](https://www.elastic.co/guide/en/elasticsearch/reference/current/flattened.html) field.
> Add ECS mappings for the k8s audit log data.

The ECS mappings were available for most of the fields. I have added a few more to ECS.  The contents of `protoPayload.request` and `protoPayload.response` are opaque objects with no spec and those couldn't be added to ECS but are available in the flattened field for query.

**Comment by r00tu53r** [comment]
Changes will be available in `v1.9.0`.
