### ISSUE TITLE
modsecurity integration not working correctly with modsecurity v2 Apache and IIS

### ISSUE THREAD

**Issue by stefanpinter** [elastic/integrations#2859]
Hi!

There is a modsecurity integration available which I am very thankful about. Sadly it doesn't give me all the fields... I see rule.id when trying to create a vizualisation but it seems to be empty. Picking out some messages from "Logs" shows that they DO have some json-fields populated but the other expected fields arent.

What can I contribute to troubleshoot this?

example of modsec_audit.json (not complete though)
...link expired...

thank you!

**Comment by stefanpinter** [comment]
same with modsecurity 2.9.5 on IIS... it doesnt event get the response code (json.response.status) right (says 0 instead of 403)

**Comment by jamiehynds** [comment]
Hi @stefanpinter - the link for the sample event seemed to have expired. Can you post again please? We can take a look and confirm if our Modsecurity pipeline requires an adjustment. @sawwn23 contributed the integration and may have some familiarity with your sample event.

**Comment by stefanpinter** [comment]
Hi!
oh I'd love that :)
https://ourvolaris-my.sharepoint.com/:u:/g/personal/stefan_pinter_motiondata-vector_com/EaskfNUQ8BZEqvIuhaHEcMkBzi_Kk4kHJTwAtQcsZNeueg?e=4wgGXq

**Comment by stefanpinter** [comment]
@sawwn23  hi! sorry, I am unsure if you get a notification when I don't tag you, so I tag you now, sorry to annoy you

**Comment by sawwn23** [comment]
Hi @stefanpinter I will work with your sample on this holiday

**Comment by emnp** [comment]
Hi @stefanpinter We're reviewing Modsecurity issues. Can you pls send the previous sample data again?

**Comment by stefanpinter** [comment]
hi @emnp !
This is good to see! 
of course I can supply the sample data again:
https://ourvolaris-my.sharepoint.com/:u:/g/personal/stefan_pinter_motiondata-vector_com/EaskfNUQ8BZEqvIuhaHEcMkBzi_Kk4kHJTwAtQcsZNeueg?e=F96m7s

on a site note, if anyone in a similar situation wants to work with something different, for now: I created a badly written bash-script that filters out relevant data of concurrent modsecurity v2 logs
https://github.com/stefanpinter/modsecurityhelpers
this has nothing to do with elastic/kibana
