### ISSUE TITLE
[System Integration] Add tags & processors to all system related datastreams

### ISSUE THREAD

**Issue by nimarezainia** [elastic/integrations#2865]
There are use cases where our users would need to enhance data collected from their systems (to either tag it for further processing or in most cases drop). The request here is to add a tag input box and a YAML processor box to the following streams in the systems integration:

System dptime metrics
System diskio metrics
System process metrics
System load metrics
System network metrics
System process_summary metrics
System core metrics
System socket_summary metrics
System cpu metrics
System memory metrics

**Comment by cmacknz** [comment]
Completed in https://github.com/elastic/integrations/pull/3563

**Comment by amolnater-qasource** [comment]
Hi @jlind23 @nimarezainia 
We have revalidated this feature on latest 8.4 Snapshot and had below observations:
`Tags` and `Processor YAML` fields are available for: 
- System uptime metrics
- System diskio metrics
- System process metrics
- System load metrics
- System network metrics
- System process_summary metrics
- System core metrics
- System socket_summary metrics
- System cpu metrics
- System memory metrics

**Screenshot:**
![12](https://user-images.githubusercontent.com/77374876/179707743-486111b9-bc8d-4a0a-b00c-0c8733520fdd.JPG)

**Build details:**
BUILD: 54585
COMMIT: f9e2ed4d9f38424676a558c34b74f0a031746c9e

## Queries

Could you please confirm:
- if any test is required with particular data in the Add tags and processors(yaml) field?
- if we add `test` in the tags field where we can visualize this data?
- Any other test requirements?

Please let us know if we are missing anything here.
Thanks

**Comment by jlind23** [comment]
@amolnater-qasource you can indeed try the "test" tag, then this tag should be available in the data ingested by this particular integration.

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
Thank you for the information.
We have revalidated this on 8.4 Snapshot Kibana cloud environment and we are successfully able to view tags data for various System integration datasets under Discover tab.

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/180164626-14ff1872-6e1c-47ff-b079-26da01dd5653.mp4

![1](https://user-images.githubusercontent.com/77374876/180164666-47521706-a036-48ef-bf32-0b0327f21e09.JPG)

**Build details:**
BUILD: 54585
COMMIT: f9e2ed4d9f38424676a558c34b74f0a031746c9e

Thanks

**Comment by amolnater-qasource** [comment]
Hi @nimarezainia @jlind23 

We have created **02 testcases** for this under our Fleet test suite at links:

- [Validate two fields Add tags and processors(yaml) field is available for system datasets](https://elastic.testrail.io/index.php?/cases/view/167690)
- [Validate if the user add test in the tags field, the data is available under Discover tab with Tags field.](https://elastic.testrail.io/index.php?/cases/view/167691)

Please let us know if we are missing any scenario here.

Thanks

**Comment by nimarezainia** [comment]
@kpollich @joshdover looking at the latest 8.4 looks like what we have in "system" has been overwritten. Could you double check that? 

![image](https://user-images.githubusercontent.com/13442829/187309916-cff346d0-7e42-4a21-8c14-968c7294ab2c.png)

is missing the tag and processor in lieu of custom pipeline work that went in.
