### ISSUE TITLE
[Windows Integration] Add processors to Windows perfmon & service metrics

### ISSUE THREAD

**Issue by nimarezainia** [elastic/integrations#2866]
Windows event logs already have a processor YAML box. This request is to add a similar YAML box on input processors for Windows perfmon and service metrics:

![image](https://user-images.githubusercontent.com/13442829/159535950-63ae529b-1d92-480c-a5e0-7979fdcdd701.png)

**Use Case:**
- user needing to add extra tags to enhance the events data collected.
- user needing to use the drop processor to limit the amount of superfluous data they collect/store

**Comment by nimarezainia** [comment]
https://github.com/elastic/integrations/issues/2359

**Comment by ManojS-shetty** [comment]
We need to change the CODEOWNER to ```obs-service-integrations``` for windows. Also before changing this discussion needed.

@akshay-saraswat will be starting a mail thread regarding the same.

**Comment by ManojS-shetty** [comment]
Please follow the link for Technical Spec documentation:

[Technical_Specification](https://docs.google.com/document/d/1XC7Kw4EJk0A1FKOWi9CjQIEl2M4h3RTDbqBh98dacjM/edit?usp=sharing)
