### ISSUE TITLE
Field formats specified in package not being applied in data view

### ISSUE THREAD

**Issue by ebeahan** [elastic/integrations#2886]
**Kibana version:**

8.1.1

**Describe the bug:**

Data views created by Fleet at package install do not apply the `format` option, if `format` is included on a field definition in the package config.

Example: the `system` package defines the field `system.memory.total`:

https://github.com/elastic/package-storage/blob/production/packages/system/1.6.4/data_stream/memory/fields/fields.yml#L6

The field includes `format: bytes`, but the data view created in Kibana is not setting the `Bytes` format.

<img width="1517" alt="Screen Shot 2022-03-23 at 4 33 02 PM" src="https://user-images.githubusercontent.com/7226265/159799483-08e58776-cfa4-42a0-979f-c6de84afbff2.png">

**Expected behavior:**

The `format` specified in the package's field definitions would be applied in the Kibana data view:

<img width="1253" alt="Screen Shot 2022-03-23 at 4 35 35 PM" src="https://user-images.githubusercontent.com/7226265/159799823-505db22e-f226-4166-a4ef-5c4944840b2b.png">

**Any additional context:**

Many [ECS](https://github.com/elastic/ecs/blob/main/schemas/process.yml#L77) and [non-ECS ](https://github.com/elastic/package-storage/blob/production/packages/system/1.6.4/data_stream/memory/fields/fields.yml#L6) fields index as an Elasticsearch numeric type. However, when viewed in Kibana are better displayed as a String or a Byte value.

Examples:

* Process IDs (pids) and TCP/UDP port numbers. These values should display as `12345` not `12,345`
* Some metric values, like memory totals and usage, can use the `Bytes` format: `5GB` vs. `5,123,456,789`

The Beats docs also discuss the `format` field: https://github.com/elastic/beats/blob/main/docs/devguide/newdashboards.asciidoc#generate-index-pattern

**Comment by ebeahan** [comment]
Thanks for the background, @jen-huang.

Some fields use a numeric type but look unconventional with the Kibana default numeric formatting, like PIDs or port numbers. Users are likely to note the change after migrating from Beats to Agent. Migrating existing fields using the 64-bit `long` to an 8-bit `byte` type isn't likely an easy option.

The past solution was to set the `format`, which would override the index pattern/data view field format. If that's no longer feasible because of the referenced Fleet change, integrations should still have some sort of mechanism to override a field's format.

Related, I did open a separate issue proposing to add `format` to the spec: https://github.com/elastic/package-spec/issues/302.

**Comment by andrewkroh** [comment]
> I will move this to integrations repo for further discussion about cleaning up system field definitions (and maybe other packages too?).

Doing this cleanup would be great. Currently there is no strict validation of the keys used "fields.yml" files. I think this stems from an incomplete definition of the keys in the spec. I noted this in https://github.com/elastic/package-spec/issues/271#issuecomment-1033174805. 

@jen-huang Perhaps we could get some help from your team telling us what fields are actually honored by Fleet and I can update the spec to reflect this. Then we can turn on strict validation and remove invalid keys from packages.
