### ISSUE TITLE
[iis] `event.created` is unmapped

### ISSUE THREAD

**Issue by fdartayre** [elastic/integrations#2889]
**Elastic agent version:** 8.1.1

**Related issues:** https://github.com/elastic/integrations/issues/2286

**Problem Description**:
IIS logs integration maps `event.created` to a `keyword` instead of a [`date`](https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-created).

This causes a mapping conflict with other logs:

![Elastic-Mapping Error](https://user-images.githubusercontent.com/30438455/160128404-b8622dee-f5bf-4432-8b2a-7aabb947e4ad.jpg)

This seems to be missing in https://github.com/elastic/integrations/blob/main/packages/iis/data_stream/access/fields/ecs.yml
```yaml
- external: ecs
  name: event.created
```

**Comment by andrewkroh** [comment]
Relates: https://github.com/elastic/elastic-package/issues/147
