### ISSUE TITLE
[snort] grok parse failure in system test

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#2901]
A system test for the snort integration failed on a grok pattern. 

>Check integrations / snort / snort: check / system test: logfile-full – snort.log1m 3s
>
> Stacktrace
> one or more errors found in documents stored in logs-snort.log-ep data stream: [0] found error.message in event: Provided Grok expressions do not match field value: [[**] [1:1000004:0] Pinging... [**]\n[Classification: Attempted Information Leak] [Priority: 2] \n09/04-21:53:15.299988 10.100.10.190 -> 175.16.199.1\nICMP TTL:64 TOS:0x0 ID:6922 IpLen:20 DgmLen:84 DF]

https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/336/tests/

**Comment by r00tu53r** [comment]
From what I see the last line of the multi line log file is not being sent by filebeat since it doesn't have a new line at the end. And that is breaking the pipeline. I'm looking into filebeat for this.

**Comment by legoguy1000** [comment]
Doesn't look like anything changed since I made it. Anything change with Filebeat since this integration was originally built?
