### ISSUE TITLE
[GCP Container]: Data for all System datasets are not available for Agent running in Docker container.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#2907]
**Kibana version:**  8.2 Snapshot Kibana cloud environment

**Host OS:** GCP Container

**Build details:**
VERSION: 8.2.0 Snapshot
BUILD: 51431
COMMIT: a743498436a863e142592cb535b43f44c448851a
Artifact link: https://artifacts-api.elastic.co/v1/search/8.2-SNAPSHOT

**Preconditions:**
1. 8.2 Snapshot Kibana cloud environment should be available.
2. Agent should be running in Docker container.

**Integrations:**
System

**Install Command:**
```
sudo docker run \
--env FLEET_ENROLL=1 \
--env FLEET_URL=<Kibana URL> \
--env FLEET_ENROLLMENT_TOKEN=<Enrollment Token> \
--rm docker.elastic.co/beats/elastic-agent:8.2.0-dcff22d7-SNAPSHOT
```

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Fleet>Data Streams tab.
3. Observe no logs type datasets for System integration.
4. Observe `system.filesystem` dataset is not available.

**Expected Result:**
Data for all System datasets should be available for Agent running in Docker container.
- metrics- `system.filesystem` should be available.
- logs- `system.syslog` and `system.auth` should be available.

**Screenshot:**
![7](https://user-images.githubusercontent.com/77374876/160566932-4d85cf68-df13-410d-ad36-262178cf39b3.JPG)

![8](https://user-images.githubusercontent.com/77374876/160568272-9b8f27d6-d60c-4ce9-ade8-d3670975ea19.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
@amolnater-qasource thanks for raising it, this is going to be fixed by @fearful-symmetry refactor which is in progress there: https://github.com/elastic/observability-dev/issues/1217

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
Thanks for confirming it an issue.
We will keep track of shared ticket and will retest this once fixed.

Thanks

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

-  01 testcase is updated for this scenario under Fleet test suite at link:
   - [C166100](https://elastic.testrail.io/index.php?/cases/view/166100)

Thanks!
