### ISSUE TITLE
[GCP Container]: Data for all Linux datasets are not available for Agent running in Docker container.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#2909]
**Kibana version:**  8.2 Snapshot Kibana cloud environment

**Host OS:** GCP Container

**Build details:**
VERSION: 8.2.0 Snapshot
BUILD: 51431
COMMIT: a743498436a863e142592cb535b43f44c448851a
Artifact link: https://artifacts-api.elastic.co/v1/search/8.2-SNAPSHOT

**Preconditions:**
1. 8.2 Snapshot Kibana cloud environment should be available.
2. Agent should be running in Docker container.

**Integrations:**
Linux

**Install Command:**
```
sudo docker run \
--env FLEET_ENROLL=1 \
--env FLEET_URL=<Kibana URL> \
--env FLEET_ENROLLMENT_TOKEN=<Enrollment Token> \
--rm docker.elastic.co/beats/elastic-agent:8.2.0-dcff22d7-SNAPSHOT
```

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Fleet>Data Streams tab.
3. Observe `linux.service` and `linux.users` datasets are not available for linux integration.

**Expected Result:**
Data for all Linux datasets should be available for Agent running in Docker container.
- metrics- `linux.service` and `linux.users` should be available.

**Screenshot:**
![10](https://user-images.githubusercontent.com/77374876/160580551-8e2d7016-0793-44f2-95fa-8b14fe1497de.JPG)

![9](https://user-images.githubusercontent.com/77374876/160580865-dcabda8e-f39a-4be6-bea4-b1d6e11d8b6d.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
@fearful-symmetry I know your recently worked on Docker metrics related topic, does it ring a bell on your end?

**Comment by jlind23** [comment]
@amolnater-qasource @manishgupta-qasource when running in container, linux.service and linux.users are meant to be unvailable because there is no systemd at all.
@nimarezainia where would be the best place to update this doc?

**Comment by nimarezainia** [comment]
@jlind23 it should really be in the integrations document for "System". Can't think of anywhere else. Those documents are generated from the packages/system/README file

@dedemorton where do you think is the right place to note this?

**Comment by jlind23** [comment]
@dedemorton they do mention it indeed. Here we talk about mentioning that systemd is not available when running in a docker container. It should probably be a disclaimer in those two places you linked.

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
Thanks for the confirmation on availability of linux datasets in docker container.
Further, please let us know if any doc request ticket is required for updating this expectation for agent running in a docker container.

Thanks

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

-  01 testcase is updated for this scenario under Fleet test suite at link:
   - [C166100](https://elastic.testrail.io/index.php?/cases/view/166100)

Thanks!
