### ISSUE TITLE
[kubernetes] undocumented field detected

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#2974]
The CI job detected an undocumented field:

```
one or more errors found in documents stored in metrics-kubernetes.pod-ep data stream: [0] field "container.network.egress.bytes" is undefined
[1] field "container.network.ingress.bytes" is undefined
```

Please add an appropriate definition for it.

Pipeline [link](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-2969/1/tests)

**Comment by ChrsMark** [comment]
Fixed by https://github.com/elastic/integrations/pull/3054.
