### ISSUE TITLE
Palo Alto Firewalls | Supporting All Log Types

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#2988]
Our current Palo Alto NGFW integration supports the following log types:
- HIP Match
- Global Protect
- Threat
- Traffic
- User ID

However, several other log types are produced by Palo Alto and should be supported by us to ensure users are not left with blind spots across their Palo Alto logs, when using our integrations. Supporting these events, would also enable us to declare full support for PAN-OS 10 (including new fields added in v10). Details on log types can be found [here](https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-admin/monitoring/use-syslog-for-monitoring/configure-syslog-monitoring.html). PAN-OS 10 fields will ned to be added to our current set of supported log types listed above also. The list of types we need to add for support are as follows:
- Authentication
- Config
- Correlated Events
- Decryption
- GTP
- IP Tag
- SCTP
- System
- Tunnel Inspection

**Comment by jamiehynds** [comment]
Example of an PAN-OS 10.2 Threat log that our pipeline will need to support as part of this effort: https://github.com/elastic/integrations/issues/3039#issuecomment-1096755800

**Comment by RazorPC** [comment]
I can also provide examples of Config, Decryption and System logs if needed.

**Comment by jamiehynds** [comment]
If you could, that would be great @RazorPC! Anonimised events are fine, of course. 

I've created a link where you can upload to, valid for 7 days but can re-issue if needed: https://upload.elastic.co/u/c0aa9485-7079-47ca-b89d-3aeb48bf0076

**Comment by LaZyDK** [comment]
Waiting for https://github.com/elastic/integrations/pull/3527 ?

**Comment by jamiehynds** [comment]
Closing this issue as our latest PANW integration now supports PAN-OS 10.x and all the event types generated by PANW firewalls. 

<img width="1213" alt="Screenshot 2022-07-28 at 09 56 39" src="https://user-images.githubusercontent.com/62879768/181466015-cdcaf75c-7a05-49ae-966b-a95d5cae2a85.png">
