### ISSUE TITLE
Populate the repository with initial set of system tests

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#299]
There are Dockerfiles present in Beats repository, we can try to use them to populate the integrations with first system tests.

In the worst case this issue will end up with a set of follow-ups for particular packages (or group of them).

**Comment by ycombinator** [comment]
Resources:
1. HOWTO guide for system tests: https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md
2. System test configuration for the `apache` package: https://github.com/elastic/integrations/pull/263/files?file-filters%5B%5D=.conf&file-filters%5B%5D=.yml&file-filters%5B%5D=No+extension
