### ISSUE TITLE
[okta] validate okta.client.ip as IP address

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#2993]
The `okta.client.ip` value is not validated as an IP address before being copied into `client.ip` and `source.ip`. The `convert` processors `type: ip` can be used. An on_failure handler can be used to remove the field if it is not a valid IP. All three `okta.client.ip`, `source.ip`, and `client.ip` are mapped as IP data types so that data must be valid to prevent mapping exceptions.

https://github.com/elastic/integrations/blob/045ae3b7963310f8dc0e275042a68916e56d1f55/packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml#L199-L203

**Comment by adriansr** [comment]
as a note, the invalid IP address that is received from the Okta API is "null" (as a string).
