### ISSUE TITLE
Cisco ingest pipeline errors

### ISSUE THREAD

**Issue by neptunian** [elastic/integrations#30]
Trying to install the package for cisco returns a Bad Request error.  The messaging isn't very useful but digging a little deeper I found the issue comes from trying to install these 2 pipelines.  Elasticsearch responds:

<img width="2545" alt="Screen Shot 2020-05-27 at 11 28 55 AM" src="https://user-images.githubusercontent.com/1676003/83040654-808d8a00-a00d-11ea-80ad-274f521fa725.png">

Is there something invalid in the pipeline data?

**Comment by andrewkroh** [comment]
The error message from ingest node was not very helpful. To track it down I just started deleting parts of the pipeline until it installed. Here's the broken piece:

https://github.com/elastic/integrations/blob/2da4975f71999880220d0659c39eb5fca8c60dbc/dev/packages/alpha/cisco/0.1.0/dataset/asa/elasticsearch/ingest-pipeline/default.yml#L67-L69

It's missing indentation on `field` and `target_field`.

**Comment by neptunian** [comment]
@andrewkroh thank you.  @ruflin Can we validate for bad indentation?

**Comment by ruflin** [comment]
@neptunian From a package perspective, we only validate if it is valid yaml and I think it is. What I hope we get in the future as part of the integrations repo is that ingest pipelines are test loaded (@mtojek )

@andrewkroh I'm assigning this to @alakahakai to fix, hope that is ok for both of you.

**Comment by alakahakai** [comment]
Addressed in PR #36.
