### ISSUE TITLE
Packages using invalid values for fields according to ECS

### ISSUE THREAD

**Issue by jsoriano** [elastic/integrations#3016]
We want to enable validation of allowed values defined in ECS fields, but there are some packages that are currently using invalid values, find below the list of current related failures.

Would it be ok to migrate these fields to the values expected according to ECS?

Pinging @elastic/obs-cloud-monitoring @elastic/security-external-integrations @elastic/obs-service-integrations @elastic/integrations  as owners of these packages.

Related issues:
* Check being implemented in https://github.com/elastic/elastic-package/pull/771.
* PR to test the change in integrations https://github.com/elastic/integrations/pull/3017.
* Feature request: https://github.com/elastic/elastic-package/issues/615#issuecomment-1021884406).

These are the current failures (once per package), and proposed changes:

- [x] #3043
- [x] #3044
- [x] #3407
- [x] cisco https://github.com/elastic/integrations/pull/3018
- [x] cisco_duo https://github.com/elastic/integrations/issues/3328
- [x] cisco_ftd https://github.com/elastic/integrations/issues/3328
- [x] #3045
- [x] #3053
- [x] https://github.com/elastic/integrations/issues/3406
- [x] #3046
- [x] #3047
- [x] #3329
- [x] #3048
- [x] #3049
- [x] #3050
- [x] #3051
- [x] #3052

**Comment by kaiyan-sheng** [comment]
Just for reference, here are the definitions for different `event.type` in ECS: https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-type.html

**Comment by jsoriano** [comment]
Individual issues created for each package.

**Comment by jsoriano** [comment]
@elastic/security-external-integrations @elastic/obs-service-integrations I have reopened some of the issues because there seems to be still issues.

I am checking this with this PR: https://github.com/elastic/integrations/pull/3017

You can check locally or in your PRs temporarily adding a replace to your go.mod files like the one in the PR above:
```
go mod edit -replace github.com/elastic/elastic-package=github.com/jsoriano/elastic-package@check-allowed-values
go mod tidy
```
To test locally after this change, use `go run github.com/elastic/elastic-package test`.

**Comment by efd6** [comment]
It would be helpful if the tool listed which files the offending terms were found.
