### ISSUE TITLE
[panw] Needs updated to support log formats in PAN-OS 10.x

### ISSUE THREAD

**Issue by RazorPC** [elastic/integrations#3039]
Only traffic and system logs are coming over from the PANW module. I checked for error.message : * and I can't even see any failures from URL/Threat syslog. I've verified that I am sending all log types from the firewall, and a packet capture from the management interface to elastic shows that URL and threat syslogs are getting sent to Elastic. 

Please let me know if/how I can provide more information. 

I've had this issue on PANW module versions 1.5.0 - 1.5.2. I am running PANOS 10.2 but I downgraded to 10.1 and still saw this issue. I can provide syslog examples if necessary.

**Comment by RazorPC** [comment]
[PANW Errors.txt](https://github.com/elastic/integrations/files/8452143/PANW.Errors.txt)
Here are some agent logs that show URL logs getting dropped.

**Comment by LaZyDK** [comment]
Did you set a custom log format in your Palo Alto Firewall/Panorama installation?

**Comment by RazorPC** [comment]
Only for testing. Right now, and in the examples I provided, it was the default log format.

**Comment by andrewkroh** [comment]
The failure is a mapping exception, but the cause looks like an issue with the CSV. There are more columns in 10.2 than what the integration is expecting. From the integration docs, I think this has only been tested with "7.1 to 9.0". So I think it needs updated to handle 10.2 THREAT logs format.

> "reason":"failed to parse field [network.forwarded_ip] of type [ip] in document with id 'H1_oCIABFRie85I1AXLZ'. Preview of field's value: ' Elastic-URL,computer-and-internet-info,low-risk'","caused_by":{"type":"illegal_argument_exception","reason":"' Elastic-URL,computer-and-internet-info,low-risk' is not an IP string literal."}}, dropping event!

> 1,2022/04/08 06:21:03,021201020274,THREAT,url,2562,2022/04/08 06:21:03,10.1.1.2,99.84.248.2,38.129.159.141,99.84.248.2,Ubuntu-ELK URL,,,ssl,vsys1,VLAN 11,WAN,ae2.11,ethernet1/1,SMTP-ELK,2022/04/08 06:21:03,161959,1,41382,443,26191,443,0x40b400,tcp,alert,"otx.alienvault.com/",(9999),Elastic-URL,informational,client-to-server,7083459582974129273,0x0,10.0.0.0-10.255.255.255,United States,,,0,," Elastic-URL,computer-and-internet-info,low-risk",0,,," Elastic-URL,computer-and-internet-info,low-risk"," Elastic-URL,computer-and-internet-info,low-risk"," Elastic-URL,computer-and-internet-info,low-risk"," Elastic-URL,computer-and-internet-info,low-risk"," Elastic-URL,computer-and-internet-info,low-risk",0,0,0,0,0,,palo," Elastic-URL,computer-and-internet-info,low-risk",,,,0,,0,,N/A,unknown,AppThreat-0-0,0x0,0,4294967295," Elastic-URL,computer-and-internet-info,low-risk"," Elastic-URL,computer-and-internet-info,low-risk",02e81f98-b1d6-4af7-aeeb-b9587ef9c4d1,0,,,,,,,,,,,,,,,,,,,,,,,,,,," Elastic-URL,computer-and-internet-info,low-risk"," Elastic-URL,computer-and-internet-info,low-risk",0,2022-04-08T06:21:03.283-05:00,," Elastic-URL,computer-and-internet-info,low-risk",,encrypted-tunnel,networking,browser-based,4,"used-by-malware,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use",,ssl,no,no,


- 10.2 https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/threat-log-fields
- 9.1 https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/threat-log-fields

**Comment by RazorPC** [comment]
Is there any other logs or details that I can provide to help with this?

**Comment by PerkinTahmaz** [comment]
Hello,

Is there a manual workaround for this? If so can you mention which ways to follow in order to approach a fix for something like this? If we can succeed I will update here.

**Comment by LaZyDK** [comment]
Pull https://github.com/elastic/integrations/pull/3527 is almost ready it seems.

**Comment by jamiehynds** [comment]
Closing this issue as our latest PANW integration now supports PAN-OS 10.x and all the event types generated by PANW firewalls. 

<img width="1213" alt="Screenshot 2022-07-28 at 09 56 39" src="https://user-images.githubusercontent.com/62879768/181466015-cdcaf75c-7a05-49ae-966b-a95d5cae2a85.png">

**Comment by devatnull** [comment]
thanks thanks thanks
