### ISSUE TITLE
Network Packet Capture | Oracle DB Support

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#3091]
The NPC integration currently supports capturing of data traffic such as MySQL, PostgreSQL and MongoDB. Adding support for Oracle database is a common request that we should investigate. User supplied PCAP files showing some sample requests and responses are available.

**Comment by efd6** [comment]
I spent some time looking into the packet format used by Oracle — the name of the protocol is TNS (Transparent Network Substrate).

I was initially unable to find any published docs for the format and so started reversing the format based on some captures that we have available, but ran into some complexities that I was unable to resolve from the data I had. More rigorous searching for some docs to help out with resolving this came up with the following series of analyses of the protocol, which agree with the reversing that I did and explain the parts that I was unable to resolve.

- https://developpaper.com/analysis-of-oracle-tns-protocol-1-the-beginning-of-the-series-methodology-and-basic-knowledge/
- https://developpaper.com/oracle-tns-314-protocol-analysis-2-infrastructure-package-structure/
- https://developpaper.com/oracle-tns-314-protocol-analysis-3-connection-authentication-process-and-package-analysis/
- https://developpaper.com/oracle-tns-314-protocol-analysis-4-sql-execution-process-and-package-analysis/
- https://developpaper.com/oracle-tns-314-protocol-analysis-5-error-return/
