### ISSUE TITLE
Do not include cgroups information by default

### ISSUE THREAD

**Issue by andresrc** [elastic/integrations#310]
When the `system` package is running in Linux we do not want to include the `cgroup` information by default.

For Fleet it seems that changing https://github.com/elastic/integrations/blob/master/packages/system/data_stream/process/manifest.yml#L50 would be enough but we should change the default value when running in standalone mode.

However, when running from metricbeat the default value should be the same as today.

**Comment by fearful-symmetry** [comment]
PR here: https://github.com/elastic/integrations/pull/375

So, we still don't have a solution for what we're doing with cgroups metrics at this point. Do we want cgroup metrics to be disabled entirely for 7.10? Do we want to make something processor-side for 7.10?
