### ISSUE TITLE
[system] Add dataset filter per visualisation

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#314]
Each visualisation normally depends on a single `data_stream.dataset`. For example all the CPU visualisations depend on `data_stream.dataset: system.cpu`. At the moment, as far as I can see the queries are made against `metrics-*` and than the aggregation on the fields. 

Adding this filter to each visualisations heavily speeds up the query as only a very small subset of data_streams have to be queried instead of all of them. This is one of the benefits of the new indexing strategy. Especially in cases where many visualisations show up in a single dashboards, this should speed up the dashboard loading and reduce the resource consumption.

The above not only applies to the system visualisations but should be done for all visualisations, it is just that the system has short term the biggest effect.

**Comment by fearful-symmetry** [comment]
Can you elaborate on this a bit? Do you mean a panel filter?

**Comment by ruflin** [comment]
I guess it depends on the visualization type on how it is exactly done. I think in TSVB it is a panel filter. The important part is that this is run as the first part of the query to reduce the number of indices / documents.

**Comment by urso** [comment]
I wonder what would be the impact performance wise if all visualizations are shown and a huge amount of data (last 7 days system metrics) would need to be shown. Doesn't APM UI have some kind of visualization filtering similar to this?

**Comment by fearful-symmetry** [comment]
So, this is going to be a tad problematic. A couple of visualizations already use filters, and as far as I can tell, there's no way to double up filters, and some use different query languages. For now, I'm going to try to add the filter to as many visualizations as I can, but I'm not sure if there's a way to add multiple visualizations.

**Comment by ruflin** [comment]
@urso I assume the impact would be pretty big. We did benchmarks for the indexing strategy and the first part is, that the storage size is reduced by around ~18% overall which also improves query time. I couldn't find the benchmarks on the query side (@jpountz do we have some?) but my math here is as following: 

* Lets assume we have 10 metric indices for system of equal size (not the case in reality)
* If no filters are used, all `metrics-*` indices are checked for data. This happens for each visulization.
* With filters, only the indices with relevant data are queried. This means 1/10th of the indices are checked per visualization.
* If we have 20 visualizations doing the these queries, this sums up quickly. 20*9 data streams checked which don't have any relevant data.
* If we have add other packages with `metrics-*` indices, the impact becomes even lager. With filters, the work almost stays constant no matter how many `metrics-*` data streams exist.

**Comment by urso** [comment]
> With filters, only the indices with relevant data are queried. This means 1/10th of the indices are checked per visualization.

Good point. If this approach indeed has a positive influence on performance, it should be part of our guidelines to always add these filters to all visualizations, no?

**Comment by ruflin** [comment]
Yes!

**Comment by fearful-symmetry** [comment]
The PR is in: https://github.com/elastic/integrations/pull/354

Tried to test as thoroughly as I could, but I didn't think of doing any benchmarking. I'm not even sure how to benchmark dashboards?

**Comment by fearful-symmetry** [comment]
PR is merged, should we close this issue?

**Comment by andresrc** [comment]
closing this, I'll add the topic to the guidelines.
