### ISSUE TITLE
[Windows Integration] Implement ignore_older for Windows event logs

### ISSUE THREAD

**Issue by nimarezainia** [elastic/integrations#3148]
Details are in https://github.com/elastic/integrations/issues/3147

Implement ignore_older for the following event logs:
- Forwarded
- Powershell
- Powershell Operational
- System Operational

**Comment by jlind23** [comment]
@fearful-symmetry did you have a chance to look at it?

**Comment by cmacknz** [comment]
This was done in https://github.com/elastic/integrations/commit/3a6e380db3f0030b82eab11c85185bd19cda8f7f
