### ISSUE TITLE
Github Advanced Security

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#3186]
Based on feedback from Github directly, they recommend that we add support for some additional security events within the Github integration. These events are:

- [Code Scanning](https://docs.github.com/en/rest/code-scanning)
- [Dependabot](https://docs.github.com/en/rest/dependabot)
- [Secret Scanning](https://docs.github.com/en/enterprise-cloud@latest/rest/secret-scanning)

We should aim to support both polling the API via the httpjson input and receiving [webhook callbacks](https://docs.github.com/en/developers/webhooks-and-events/webhooks/creating-webhooks) via the http_endpoint input. They both have their pros and cons. Ideally we can create one data stream for each such that we support audit, code_scanning, dependabot, and secret_scanning. And each of those has two input sources -- webhook or API polling.

**Comment by jamiehynds** [comment]
@kcreddy can this issue be closed, or is there some further work required on the GHAS alerts?

**Comment by kcreddy** [comment]
@jamiehynds We did support all the 3 events using httpjson input. We still need to add support for receiving [webhook callbacks](https://docs.github.com/en/developers/webhooks-and-events/webhooks/creating-webhooks) via the http_endpoint. Maybe we could have another issue to track it separately, or we could keep this open, either is fine.

**Comment by jamiehynds** [comment]
@kcreddy Thanks for the update. I think given that the scope of the webhook is pretty narrow, it's best to close this one out, if you wouldn't mind creating a new issue for the webhooks?
