### ISSUE TITLE
Integrations can have a higher version than the stack

### ISSUE THREAD

**Issue by philippkahr** [elastic/integrations#3247]
I was able to update the Endpoint integration to 8.2.0 whilst my Stack was on 8.1.2.

<img width="1574" alt="Screenshot 2022-04-27 at 22 12 00" src="https://user-images.githubusercontent.com/12175559/166195779-93772b2e-7ea3-4c94-b29a-3a1d27f00d59.png">

**Comment by pzl** [comment]
Hello @philippkahr 

The Endpoint integration at v`8.2.0` was determined to be backwards compatible with the `8.0`, `8.1`, and `8.2` stacks, and was released to 8.0+

We understand the confusion being on a lower stack version and seeing a higher package as you've reported. Starting with `8.3`, the package and stack versions will be aligned with major-and-minor. That was also the intent here, but there was a versioning mistake when transitioning the Endpoint package from series releases (`1.5`, `1.6`, etc) to stack-aligned

**Comment by philippkahr** [comment]
<img width="1158" alt="Screenshot 2022-08-26 at 11 10 32" src="https://user-images.githubusercontent.com/12175559/186870188-268d056d-05a9-4327-812a-59c9eb452034.png">
Reopening this as this happened in 8.4.0 again. @pzl
