### ISSUE TITLE
Leverage mode "time_series" (TSDB) querying capabilities in integration dashboards

### ISSUE THREAD

**Issue by flash1293** [elastic/integrations#3258]
`time_series` indices in Elasticsearch (e.g. discussed here: https://github.com/elastic/ingest-dev/issues/1036) offer a bunch of advantages with regard to disk space usage, but there will also be a few new querying capabilities https://github.com/elastic/elasticsearch-adrs/blob/master/analytics/tsdb/tsdb-design.md#aggregation-apis
* Better handling of rate calculation for counter metrics (automatic reset detection)
* `time_series` agg to split individual series without the need to specify the dimension fields (as these are defined in the mapping)
* Sliding window date histogram (decoupling window size and step width of the date histogram)

The Kibana VisEditors team is currently thinking about how to best support TSDB usage in visualizations. What are common cases of visualizations which are not built / built in a sub-optimal way right now due to limitations of the existing tools?

Right now the following is planned:
* Support for Lens, but not TSVB
* Use Elasticsearch side rate calculation together with `time_series` and `sum_bucket` to do a proper rate calculation summed up for all series without user configuration for counter metric fields 
* Allow to do time_series + sum_bucket for other metrics (average, "last value")
* Later: Allow configuring a window size for metrics which will transparently use the sliding window date histogram instead of regular date histogram

Note: These new features will only function for time_series data, so they won't show any results for indices with historical data indexed as regular data indices.

**Comment by flash1293** [comment]
cc @mtojek @ruflin Who could provide some input on this?

**Comment by mtojek** [comment]
I would ping @ravikesarwani or @akshay-saraswat as they care about the product side of integrations.

**Comment by ruflin** [comment]
@lalit-satapathy It seems most of the things discussed above have been done / are in use? Should this issue be closed?
