### ISSUE TITLE
[kubernetes] field mapping exception while ingesting audit logs

### ISSUE THREAD

**Issue by imays11** [elastic/integrations#3259]
My colleague and I are using the Kubernetes Audit Logs integration to create security detection rules. We have discovered a gap in coverage of [fields](https://github.com/elastic/integrations/blob/main/packages/kubernetes/data_stream/audit_logs/fields/fields.yml) being ingested. The current pipeline has not properly defined a subset of fields grouped under "requestObject" and "responseObject". These are JSON objects with more fields nested within them. However, the integration defines both these fields as "text", instead of "group". 
![image](https://user-images.githubusercontent.com/59296946/166517251-c0d48063-9ad4-4372-9cf8-f7e18ae71a84.png)
![image](https://user-images.githubusercontent.com/59296946/166517288-6ea1eceb-98e4-4dd0-86e1-dc97db0d41ae.png)

This is a problem as we are missing crucial audit log fields needed for detections. For example, "requestObject.spec.container.securityContext.privileged", if 'true', would indicate a request to create a privileged pod. We are unable to detect this at the moment. 

In addition to causing us to miss important data, this issue is causing a parsing error in Kibana and disrupting ingest of all audit log events created at the Request and RequestResponse level. These response levels introduce 1 or both of those fields. All the impacted events are storing data in a large "message" field making the data unusable.
 
![image](https://user-images.githubusercontent.com/59296946/166522931-fb12c7fe-fd32-4a2b-8c92-19ac6ebb3d85.png)

Here are a couple events to reproduce the problem: 

[kubernetes.audit.responseObject_failure.txt](https://github.com/elastic/integrations/files/8612921/kubernetes.audit.responseObject_failure.txt)
[kubernetes.audit.requestObject_failure.txt](https://github.com/elastic/integrations/files/8612925/kubernetes.audit.requestObject_failure.txt)

**Comment by tetianakravchenko** [comment]
Hi @imays11!
Are you interested in the `requestObject.spec.container.securityContext.privileged` field only? Do you maybe have a list fields you are interested in?

**Comment by imays11** [comment]
Hi @tetianakravchenko :)
Here's a list of fields we are interested in for some behavior and anomaly based detections:

requestObject.spec.containers.image
requestObject.spec.containers.securityContext.privileged
requestObject.spec.containers.volumeMounts.mountPath
requestObject.spec.containers.HostNetwork
requestObject.spec.containers.HostIPC
requestObject.spec.containers.HostPID
requestObject.spec.type
requestObject.spec.volumes.hostPath.path
requestObject.rules.resources
requestObject.rules.verbs

responseObject.spec.containers.securityContext.privileged
responseObject.spec.containers.securityContext.allowPrivilegeEscalation
responseObject.spec.containers.volumeMounts.mountPath
responseObject.spec.hostIPC
responseObject.spec.hostNetwork
responseObject.spec.hostPID
responseObject.spec.volumes.hostPath.path
responseObject.spec.restartPolicy
responseObject.rules.resources
responseObject.rules.verbs
responseObject.roleRef.kind

**Comment by tetianakravchenko** [comment]
I've already promoted kubernetes package version [1.20.0 to production](https://github.com/elastic/package-storage/pull/4584) - this version should be available for stack versions `^8.2.0` soon.

**Comment by imays11** [comment]
If it's not too late can I add an additional field?

**Comment by tetianakravchenko** [comment]
@imays11 I've already merged my PR before your comment and version `1.20.0` is already available.
could you please create another issue for the field you mentioned and add there all other needed fields that might be notice after testing 1.20.0?
