### ISSUE TITLE
Remove collect logs from S3 in AWS CloudWatch integration

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#3262]
Current AWS CloudWatch integration includes an option to collect logs from S3, which does not make sense for any users. If logs are already in S3, users can use the s3 integration or custom aws logs instead. We should figure out a proper procedure to remove this option inside CloudWatch integration.

This is what we have in CloudWatch integration right now:
<img width="742" alt="Screen Shot 2022-05-03 at 3 02 13 PM" src="https://user-images.githubusercontent.com/14081635/166565757-8e52eaf9-d656-47a2-85d7-51dd40c52b77.png">

After discussing with @ravikesarwani , we think we should take the steps below:

1. Create a PR asap to mark the `collect logs from S3` option obsolete and promote the package (Done)
2. Create 2.0.0 version with breaking change to remove the `collect logs from S3` option
3. In upgrade process, identify policy where `collect logs from S3` option is configured and add warning on the upgrade page.
4. If the previous step is too difficult, then give a general warning for the 2.0.0 version in the UI and also document the breaking change.

**Comment by tommyers-elastic** [comment]
hey @kaiyan-sheng - step one of this sounds trivial - would you be able to walk me through where this change needs to be made and we can get it done?

**Comment by kaiyan-sheng** [comment]
Sorry I didn't update this issue in time @tommyers-elastic. Actually step one is already done in https://github.com/elastic/integrations/pull/3304.

**Comment by tdancheva** [comment]
Created a [PR](https://github.com/elastic/integrations/pull/6247) to address step 2).

**Comment by tdancheva** [comment]
Finally, to sum up discussions outside of GH, we can use the Changelog modal available in v8.x, backport of the feature could not go through because we are not releasing more minors for 8.7.
