### ISSUE TITLE
Add saved object tags to integrations with Kibana saved objects

### ISSUE THREAD

**Issue by alexfrancoeur** [elastic/integrations#327]
The Kibana team (well, @pgayvallet :wink:) has a PR for saved object tagging targeted for 7.11 that is currently under review (https://github.com/elastic/kibana/pull/79096). This is the MVP and we plan to iterate. That being said, I think there is an opportunity to update any packages with Kibana saved object tags in the same release. I realize the registry is not release based, but it'd be a nice announcement to go along with user generated tags 😄 

Next up that's related to this effort, I plan to start up discussions with the team on https://github.com/elastic/kibana/issues/70461

cc: @ruflin @mostlyjason @tbragin @kobelb @joshdover

**Comment by ruflin** [comment]
Mentioning @andresrc as he will drive the updates of integrations. I assume it means, any visualization / dashboard etc. where we will start using tags, will be only compatible with KB 7.11, means the package itself is probably only compatible with 7.11. No problem with that, just wanted to make sure compatibility is clear.

**Comment by tbragin** [comment]
@alexfrancoeur this is great news! +1 on automatically applying tags for the dashboards we ship with integrations. Thank you for starting this conversation :heart:

cc @sorantis @mukeshelastic from observability integrations
cc @jamiehynds  @hmnichols from security integrations

**Comment by alexfrancoeur** [comment]
As a quick update to this group, @pgayvallet has officially merged tags with out of the box support for dashboards and visualizations. We'll be discussing what additional improvements we can make for 7.11 (https://github.com/elastic/kibana/issues/81980), but the functionality is now available.

**Comment by ruflin** [comment]
@andresrc We should start to create a guideline on how we use the tags inside the packages

**Comment by bradenlpreston** [comment]
@jamiehynds and @epixa in the event we want to update any packages related to security.

**Comment by nreese** [comment]
Tags added to maps with https://github.com/elastic/kibana/pull/83197

**Comment by alexfrancoeur** [comment]
Hey all, I wanted to provide a quick update around tags for 7.11.

There has been some significant (and amazing) progress from @pgayvallet, @ryankeairns and team to support a global experience for tag usage.

Tags are now a suggested filter from our navigational search https://github.com/elastic/kibana/pull/85144
To support this even more, we'll soon surface tags in search results with saved objects that have them https://github.com/elastic/kibana/pull/85084
Users can now manage tags in bulk across supported saved objects https://github.com/elastic/kibana/pull/84177

![ezgif-3-e3c2f122eeb8](https://user-images.githubusercontent.com/25181823/101646458-9260d880-3a05-11eb-9c9b-e10c3c1309f0.gif)

This significantly increases discoverability and streamlines navigation of Kibana assets packaged with integrations. 

Have we come to a consensus on guidelines for integrations? If so, do we think that integrations will add support for tags in 7.11? I also believe that integrations are not bound by release, so maybe it's possible to iterate here.

**Comment by tbragin** [comment]
@mukeshelastic @sorantis @andresrc @mostlyjason @jamiehynds @ruflin @ph I'd love your perspective here. 

As you may recall, we asked the Kibana team to prioritize tags, so we have a mechanism to organize assets we are installing with modules and integrations. Do we already have a plan in place to leverage them? I know it's been discussed, but not sure where we ended up.

**Comment by ruflin** [comment]
My suggestion is we start simple with 2 tags:

* integrations name tag on all assets from an integration
* `managed` tag on all the assets to indicated that they are managed by us. Alternative we could add a `fleet` tag to indicate that they are managed by `fleet`.

**Comment by sorantis** [comment]
We discussed the possibility to use tags as a mechanism to automatically expose integrations' assets in the UI. For example we could automatically add a link to a dashboard based on a tag matching service/integration name on a host's or container's details page. This actually aligns with @ruflin's first suggestion.

**Comment by ph** [comment]
@ruflin what you are proposing is to thave theses tags hardcoded at install time? The second steps would be to allow dev author to define more tags?

**Comment by ruflin** [comment]
Not sure what you mean by hardcoded. EPM would take the package name, create a tag out of it and add it to all assets. In addition, it adds the `managed` tag to all assets.

For your second part about devs adding tags: I'm wondering if a tag references the saved objects or if a tag is part of each saved object. If it part of each object, I guess it could already be used today? @alexfrancoeur might know more here.

**Comment by pgayvallet** [comment]
> For your second part about devs adding tags: I'm wondering if a tag references the saved objects or if a tag is part of each saved object

The reference is from the saved object referencing the tag to the tag SO

**Comment by ph** [comment]
> Not sure what you mean by hardcoded. EPM would take the package name, create a tag out of it and add it to all assets. In addition, it adds the managed tag to all assets.

Yes this exactly what I wanted to hear, this really make it simple.

@pgayvallet so this is a N:N relationship and not denormalized, In that case maybe it's not a good idea to allow integration author to add tags.

**Comment by alexfrancoeur** [comment]
Apologies to keep pinging on this one, but do we have a sense of target release or priority to start supporting tags with integrations? I see this was moved to backlog and do not see any PR's linked. One of the initial drivers to introduce this feature was to organize Kibana assets in packages. It feels like the technical implementation is relatively simple, it's just a matter of defining and agreeing upon a process. With 7.11 pushed a few additional weeks, there is still an opportunity to release tags in the same release.

**Comment by masci** [comment]
@alexfrancoeur this is in the backlog as it still needs to be scheduled, we won't deliver anything in 7.11. As this will be a cross-team effort also on our side, I'll outline the proposed changes (most likely [what ruflin said](https://github.com/elastic/integrations/issues/327#issuecomment-744269122)) along with an action plan during 7.12.

**Comment by alexfrancoeur** [comment]
Awesome, thank you so much for the update @masci !

**Comment by masci** [comment]
We discussed the issue and my team recommendation is to start by letting EPM add the `managed` tag at install time and postpone any manual tagging on the package side until we have a better idea of the integrations developer experience and how those tags could be leveraged throughout the user interface.

**Comment by tbragin** [comment]
@mukeshelastic @alvarolobato FYI ^^

**Comment by alvarolobato** [comment]
@masci does this mean we wouldn't be adding a tag with the package name or some way to identify the integration?
One of the main use cases I thought for this feature is precisely what @sorantis commented [here](https://github.com/elastic/integrations/issues/327#issuecomment-744452272). Right now when you are in Metrics UI you can only see so many details about the services running in a given host and there is no difference if you have a package installed for that service or not, we would like to link to the assets a given module installed and allow the users, for instance, to navigate to MySQL dashboards from a host that is running that service. This would provide a connection between the two worlds, packages with assets and the curated UI.

**Comment by masci** [comment]
@alvarolobato on a second read, the example in my comment might have been misleading.

The idea is to start by letting EPM add tags automatically based on whatever informations the EPM itself has at install time: `managed` is an example but also the name of the package is a good candidate for automatic tagging. 

We are totally on board with the idea you described in the comment but what we propose _not_ to do during this first phase is having developers adding tags before we know exactly how these tags would be used in the UI, a formal naming convention to avoid duplicates or similar variations of the same tag, and ultimately a better idea of how the granularity concept will affect a package containing multiple integrations.

So the plan would be:
- phase one: only automatic tags added at install time
- phase two: integrations developers add tags beforehand, within the package

@exekias please correct me if I'm wrong

**Comment by alvarolobato** [comment]
That makes sense to me, thanks for clarifying Massi.

**Comment by exekias** [comment]
++ let's make sure we get the Integration name automatically in, that will give us a lot already

**Comment by sorantis** [comment]
For packages we're also maintaining a list of categories. Is this something we can also consider in phase one?

**Comment by masci** [comment]
@sorantis that would imply we add the info in the package manually - while that is a good example of a formal label we'll certainly add in the future, I'd wait for the granularity example (specifically, AWS) to be ready before going through the packages we have and add the label.

**Comment by joshdover** [comment]
A few notes about a few things that should be considered when implementing this:
- Tags are their own saved object type, each idenified with a UUID like all other SO types.
	- This means integrations will need to include both a new `tag` object for each tag they want to add (eg. "system" or "managed") as well as adding a new object reference to each object that should have that tag.
- Any tags that are intended to be shared _across_ integrations need to use the same UUID
	- For example, if we want include a "managed" or "fleet" tag on objects from all integrations, we need to make sure the same UUID is used for each integration. If a different UUID is used, then a duplicate tag will be created with the same name. This sounds like something that would confuse users.
	- I'm curious if we have any thing in place for sharing SOs across integrations so that we can be sure the same SO UUID is referenced for integrations that need to make use of it. I imagine we're doing something similar for the `logs-*` and `metrics-*` index patterns that we may be able to reuse here.
- We need to add support for installing SO of the `tag` type on the Fleet side. I've opened an issue to track this here: https://github.com/elastic/kibana/issues/110660

**Comment by alexfrancoeur** [comment]
Hey all, I wanted to follow up on this. Did we end up getting tags as part of the integration specs in 7.last? I couldn't find any linked issues

**Comment by joshdover** [comment]
I've opened an issue to add a standard set of tags to all Saved Objects installed by Fleet: https://github.com/elastic/kibana/issues/123904

**Comment by alexfrancoeur** [comment]
@jen-huang I _think_ this can be closed now. Correct?

**Comment by jen-huang** [comment]
Yep, done with https://github.com/elastic/kibana/issues/123904 in 8.4.
