### ISSUE TITLE
[GCP] Dashboards for Firewall and VPC flow logs

### ISSUE THREAD

**Issue by felix-lessoer** [elastic/integrations#3271]
I've created dashboards for VPC Flow logs and Firewall Logs.
These dashboards are attached as Kibana SO export.

The export includes the index pattern.

## VPC flow dashboard
![GCP  VPC flow dashboard - Elastic](https://user-images.githubusercontent.com/35069463/166647322-98aff273-6411-4bf0-bbee-5479c8705265.png)

## Firewall logs dashboard
![GCP  Firewall logs dashboard - Elastic](https://user-images.githubusercontent.com/35069463/166647359-80a5f72a-e7cc-4cae-8d4b-d5693a545e79.png)

Kibana export
[GCP dashboards.zip](https://github.com/elastic/integrations/files/8618834/GCP.dashboards.zip)

**Comment by jamiehynds** [comment]
Thanks @felix-lessoer - dashboards look great! Are you ok with us adding these to the GCP integration?

**Comment by felix-lessoer** [comment]
Yes thatswhy I am sharing them ;)

**Comment by jamiehynds** [comment]
Thanks, just wanted to make sure. We'll create a PR and get them included with the integration.

**Comment by andrewkroh** [comment]
PR: https://github.com/elastic/integrations/pull/3280
