### ISSUE TITLE
[google_workspace] Add DLP audit log support

### ISSUE THREAD

**Issue by gbanasiak** [elastic/integrations#3277]
**Describe the enhancement:**

Provide support for [DLP audit log](https://support.google.com/a/answer/9656995?hl=en&ref_topic=9646660) ingest through [rules](https://developers.google.com/admin-sdk/reports/v1/appendix/activity/rules) endpoint of Google reporting API.

**Describe a specific use case for the enhancement or feature:**

Track Google Drive user activity for DLP (Data Leak Prevention) purposes.

**Comment by jamiehynds** [comment]
Closing this issue in favour of https://github.com/elastic/integrations/issues/4079
