### ISSUE TITLE
Additional zeek module log files

### ISSUE THREAD

**Issue by 111andre111** [elastic/integrations#3288]
**Describe the enhancement:**
I checked again the existing log types that exist in filebeat because of a test I made with zeek 3.0.
https://docs.zeek.org/en/current/script-reference/log-files.html
These issues
https://github.com/elastic/beats/issues/12724
https://github.com/elastic/beats/pull/12812
https://github.com/elastic/beats/pull/14150
https://github.com/elastic/beats/pull/14404

I did now produce a list of all logs to identify all missing log types:
* [ ] barnyard2.log
* [ ] broker.log
* [ ] cluster.log
* [ ] config.log
* [ ] known_certs.log
* [ ] known_hosts.log
* [ ] known_modbus.log
* [ ] known_services.log
* [ ] loaded_scripts.log
* [ ] modbus_register_change.log
* [ ] netcontrol_catch_release.log
* [ ] netcontrol_drop.log
* [ ] netcontrol_shunt.log
* [ ] netcontrol.log
* [ ] notice_alarm.log
* [x] ntp.log - https://github.com/elastic/beats/pull/24224
* [ ] openflow.log
* [ ] packet_filter.log
* [ ] print.log
* [ ] prof.log
* [ ] reporter.log
* [x] signatures.log - https://github.com/elastic/beats/pull/23772
* [ ] software.log
* [ ] stderr.log
* [ ] stdout.log
* [ ] unified2.log
* [ ] weird_stats.log

One special part is extra
* [x] signatures.log [was already ~~committed~~ contributed but not merged](https://github.com/elastic/beats/tree/8e0e31900da39bf4033039c08478b6a97135b910/x-pack/filebeat/module/zeek/signatures) but never made it into [release](https://github.com/elastic/beats/tree/v7.7.0/x-pack/filebeat/module/zeek) somehow unfortunately.
At the moment because this one using seek module need you to disable the signatures.log logtype:
https://github.com/elastic/beats/blob/v7.7.0/x-pack/filebeat/modules.d/zeek.yml.disabled#L49-L50

[zeek-log-types.xlsx](https://github.com/elastic/beats/files/4706325/zeek-log-types.xlsx)

Additionally documentation doesn't have much information about how to configure seek module:
https://www.elastic.co/guide/en/beats/filebeat/7.7/filebeat-module-zeek.html

**Comment by austinarmbruster-elastic** [comment]
👍 Zeek logs are coming up in a new deal with a customer. Still discovering the details on which specific log types must be supported.
