### ISSUE TITLE
Fortinet | Forti-OS 7.x Support

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#3289]
Our Fortinet firewall integration was originally tested against Forti-OS 6.x, but we need to ensure we support their latest OS, which is currently v7.2 (Release notes [here](https://docs.fortinet.com/document/fortigate/7.2.0/fortios-release-notes/760203/introduction-and-supported-models)). Can we please test against x7.2 and update our pipelines if any parsing errors are discovered. We have an NFR license available from Fortinet. 

Information including updated GROK patterns used by a Fortinet customer, available under ER#15666

**Comment by ebeahan** [comment]
Opened: https://github.com/elastic/integrations/pull/8734

**Comment by ebeahan** [comment]
Docs changes completed in #8734
