### ISSUE TITLE
[Google Workspace Audit] Add support to upload a file or paste the content in the integrations page

### ISSUE THREAD

**Issue by philippkahr** [elastic/integrations#3291]
From an end user perspective I would expect to be able to do everything from the Kibana UI and not go to the host that is running Elastic Agent, paste the file there and then set the path to that.

I would expect to either:
* Upload the file in the integration page
* Paste the content of the file into the integration

<img width="789" alt="image (3)" src="https://user-images.githubusercontent.com/12175559/167151186-33b6e6d7-ed68-460f-b2a4-82f26306744a.png">

**Comment by andrewkroh** [comment]
This is a duplicate of #2834.
