### ISSUE TITLE
[Package: redis] Dashboard issue with constant prefix.

### ISSUE THREAD

**Issue by ph** [elastic/integrations#33]
orignaly reported by @mtojek in https://github.com/elastic/kibana/issues/67598 

I spotted this one while testing the "redis" integration.

<img width="2551" alt="Zrzut ekranu 2020-05-26 o 18 45 12" src="https://user-images.githubusercontent.com/14044910/83131615-683a6f80-a0e0-11ea-9e7d-c4ad4820e63c.png">

solution: https://github.com/elastic/kibana/issues/67598#issuecomment-635328939

**Comment by mtojek** [comment]
Merged, resolving.
