### ISSUE TITLE
[Azure Integration] AzureAD additional sign-in types

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#338]
Our Azure integration currently supports ingestion of sign-in logs to provide visibility into interactive user sign-ins. Microsoft has recently added support for non-interactive sign-ins which are currently dropped by our pipeline. Our integration needs to be updated to include these new sign-in types:

- NonInteractiveUserSignInLogs
- ServicePrincipalSignInLogs
- ManagedIdentitySignInLogs

Community user has confirmed non-interactive logins are parsed just fine by the current pipeline, but needs to modify the drop conditional. Slack thread here: https://elasticstack.slack.com/archives/CNEDGGJQ3/p1603406740279900

Microsoft documentation: https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/concept-all-sign-ins#non-interactive-user-sign-ins

**Comment by andrewkroh** [comment]
These three were added in https://github.com/elastic/integrations/pull/1721.
