### ISSUE TITLE
Migration script should trim `-ecs` suffix from Kibana asset IDs

### ISSUE THREAD

**Issue by ycombinator** [elastic/integrations#339]
Per the discussion starting from https://github.com/elastic/integrations/issues/269#issuecomment-693368174, it was agreed that Kibana asset IDs in Integrations packages should not contain the `-ecs` suffix. We should modify the migration script (that migrates existing Beats modules to Integrations packages) to remove this suffix during the migration.

**Comment by andrewkroh** [comment]
I've noticed a lot of those same dashboards with `-ecs` have titles that are suffixed with "ECS". Maybe it's possible to strip those automatically too.
