### ISSUE TITLE
Update Security Integration Names

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#3400]
Some of our integration names are not consistent with our standard naming, e.g. many of them include 'logs' in the title. 

Can we please adjust the names of the following integrations, to just include the vendor/product name:

- Auth0 Log Streams Integration - `Auth0`
- Cisco Meraki Integration - `Cisco Meraki`
- Azure Active Direction logs - `Azure Active Directory`
- CEF Logs - `Common Event Format (CEF)`
- Cisco Secure Endpoint (AMP) - `Cisco Secure Endpoint`
- Crowdstrike Logs - `CrowdStrike`
- Custom HTTPJSON Input - `Custom REST API Input`?
- CyberArk Privileged Access Security logs - `CyberArk Privileged Access Security`
- Fireeye - `FireEye Network Security `
- Fortinet Logs - `Fortinet`
- Google Santa logs - `Google Santa`
- Google Workspace Audit Reports - `Google Workspace`
- Iptables logs - `Iptables`
- M365 Defender Logs - `Microsoft M365 Defender`
- Office 365 Logs - `Microsoft 365`
- Okta logs - `Okta`
- Palo Alto Cortex XDR logs - `Palo Alto Cortex XDR`
- Palo Alto Network logs - `Palo Alto Next-Gen Firewall`
- pfSense logs - `pfSense`
- Sohos logs - `Sophos`
- Suricata events - `Suricata`
- Zeek logs - `Zeek`

**Comment by andrewkroh** [comment]
The Azure integration is not owned by elastic/security-external-integration. It uses multiple policy_templates to create several tiles on the integration page. If we change `Azure Active Direction logs` to `Azure Active Direction` then this one item in the Azure integration will be inconsistent with the others in the same integration (they all use a "<name> {logs,metrics}" format).
