### ISSUE TITLE
[mySQL Integration]  Add tags & processors to all mySQL related datastreams

### ISSUE THREAD

**Issue by nimarezainia** [elastic/integrations#3431]
**Background:**

As we strive to make Elastic Agent a replacement for the beats, there are some global fields, generally applied on an input datastream, which need to also be available in our integrations. Currently there’s little to no consistency between these integrations, causing a lot of frustration amongst our users.

For more details please refer to: https://github.com/elastic/ingest-dev/issues/995

The following datastreams would need to be modified and have tags and processors enabled:

MySQL error logs
MySQL slowlog logs
MySQL galera_status metrics
MySQL performance metrics
MySQL status metrics

[fyi @akshay-saraswat ]

**Comment by ritalwar** [comment]
There is an ongoing thread i.e https://github.com/elastic/elastic-package/issues/949, which will incorporate these changes.
