### ISSUE TITLE
[Custom Log Integration] Add tags & processors to Custom Log datastreams

### ISSUE THREAD

**Issue by nimarezainia** [elastic/integrations#3432]
**Background:**

As we strive to make Elastic Agent a replacement for the beats, there are some global fields, generally applied on an input datastream, which need to also be available in our integrations. Currently there’s little to no consistency between these integrations, causing a lot of frustration amongst our users.

For more details please refer to: https://github.com/elastic/ingest-dev/issues/995

[fyi @akshay-saraswat ]

**Comment by fearful-symmetry** [comment]
@nimarezainia I'm a tad confused by the scope of this. Is this issue for adding a tags and processors field to all integrations? Just a certain subset of logging integrations?

**Comment by faec** [comment]
[drive-by as I review sprint status] This task looks underspecified -- the design doc linked through the meta issue isn't finalized, and it's unclear what the technical deliverables for this specific issue are, so I don't think "estimation:Day" is a realistic tag.

**Comment by nimarezainia** [comment]
@fearful-symmetry this is just about adding tags and processors to the "Custom Log" integration. this was done for the system integration also: https://github.com/elastic/integrations/issues/2865#issuecomment-1188780415

@kpollich in context of https://github.com/elastic/elastic-package/issues/949   - how should we be pursuing this?

**Comment by kpollich** [comment]
@nimarezainia It would be best to follow suit with https://github.com/elastic/integrations/issues/2865 here and add tags + processors to the Custom Logs integration. 

Regarding https://github.com/elastic/elastic-package/issues/949, let's not let this block any work in the short term. We can discuss a path forward and what the priority looks like for managing these fields in a global way elsewhere.

**Comment by fearful-symmetry** [comment]
@nimarezainia it looks like the main codeowners for that don't work here anymore, so I can probably just add it for this one. In the future if we want to add this to more integrations it should probably be done by the code owners of the given integrations, since the `.yml.hbs` files are so fragile and CI tends to not catch basic errors, so someone with knowledge of a given integration would have an easier time manually testing in-depth.
