### ISSUE TITLE
Migrate packages dashboards to by value visualizations

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#3448]
Kibana visualizations can be added in a dashboard by value or by reference. As historically by value did not exist, most dashboards are still using by reference. Switching to value has the advantage that the dashboards are fully self contained and only need a single request to be installed. Because of this existing dashboards should be moved over to use by value.

The biggest have the most used packages and the ones with many dashboards and visualisations. This meta issue is to track the work on migrating these packages.

* [x] Kubernetes https://github.com/elastic/integrations/pull/3115
* [x] System https://github.com/elastic/integrations/issues/3449
* [x] AWS (multiple) https://github.com/elastic/integrations/issues/3454 and https://github.com/elastic/integrations/issues/3455
* [x] #3719
* [x] Security external integrations https://github.com/elastic/integrations/issues/3463
* [x] Azure https://github.com/elastic/integrations/issues/4922

As soon as this list is migrated, we should expand it to all integrations.

## Migration script

A migration script was created to help with this effort: https://github.com/flash1293/legacy_vis_analyzer

## Documentation

- [x] Update [development guidelines](https://github.com/elastic/integrations/blob/main/docs/generic_guidelines.md) to prescript using by-value visualizations
  - See [dashboards guidelines](https://github.com/elastic/integrations/blob/main/docs/dashboard_guidelines.md#visualizations-by-value-not-by-reference)

**Comment by andrewkroh** [comment]
Meta issue for security-external-integrations: https://github.com/elastic/integrations/issues/3463

**Comment by bradenlpreston** [comment]
@jamiehynds - can you take a look at this?

**Comment by jamiehynds** [comment]
@bradenlpreston - we've made a list of integrations that require conversion [here](https://github.com/elastic/integrations/issues/3463). Assuming there isn't a hard deadline, I've added this work as an 8.5 item as part of our team's planning session later this week.

**Comment by bradenlpreston** [comment]
Great! - thanks Jamie.

**Comment by tommyers-elastic** [comment]
Hey all -For some dashboards that have been migrated to by-value, I still see a bunch of referenced objects for searches, tags, index patterns etc. Are these types of saved objects ok to be still referenced like this, or should these also be inlined? see this dashboard for an example https://github.com/elastic/integrations/blob/5f5ede9bec71adec7b2714097cf019faa20b23b7/packages/gcp/kibana/dashboard/gcp-48e12760-cbe4-11ec-b519-85ccf621cbbf.json#L593 

it seems like unless we do this this can't be true `dashboards are fully self contained and only need a single request to be installed`. 

but at the same time, aren't saved searches sometimes top-level package assets too? in which case it wouldn't make sense to duplicate them.

thanks

**Comment by ruflin** [comment]
As you described, we likely not end up having all assets by value (and shouldn't). But we should have clear guidelines for which these is the case.

**Comment by endorama** [comment]
I opened a PR to update the dashboard guidelines documentation: https://github.com/elastic/integrations/pull/5021

**Comment by milanparmar-crest** [comment]
Team, Is anyone working on Migrating System and Azure dashboards to "by value" visualizations? If not we can take it up and start working on it.

**Comment by ruflin** [comment]
@lalit-satapathy Where did we land here?

**Comment by lalit-satapathy** [comment]
> @lalit-satapathy Where did we land here?

We are addressing this as part of the fixing of the [skipped validations](https://github.com/elastic/integrations/issues/8452) of the package migration work. For the pass-by-value pending the skip was SVR00004. 

Here is one [PR](https://github.com/elastic/integrations/pull/8423) being reviewed, for the initial set of packages.  There was also a [fix](https://github.com/elastic/visualizations_integrations_tools/issues/2) done in the in-liner script. The remaining set of packages will be taken up next [here](https://github.com/elastic/integrations/issues/8938).

**Comment by ruflin** [comment]
@lalit-satapathy Should we keep this issue open or consider it "completed" and all follow up is tracked separately?

**Comment by lalit-satapathy** [comment]
Keeping it open and assigned to me. Will close once all SVR00004 fixes [here](https://github.com/elastic/integrations/issues/8452) are done.
