### ISSUE TITLE
[GCP] Auditlogs producing mapping issues

### ISSUE THREAD

**Issue by felix-lessoer** [elastic/integrations#3452]
The auditlog collection from the GCP integration is running into issues when ingesting data via dataflow due to different data formatting depending on the type of audit log that has been sent.

The error from dataflow: 
`Error message from worker: java.io.IOException: Error writing to Elasticsearch, some elements could not be inserted:
Document id naHxHoEBDj9unoxZGUzK: object mapping for [protoPayload.response.status] tried to parse field [status] as object, but found a concrete value (mapper_parsing_exception)`

The field `protoPayload.response.status` can sometimes be an object and sometimes an concrete value. This leads to mapping issues when putting the data into the same field.

A few examples of the event sent by Google Dataflow with the different kinds of status. I wasn't able to find an event where the status is set like the pipeline is expecting this at the moment. But the two cases below need to work as well.

#### No status
```
{"insertId":"15ciwwfd47gm","logName":"projects/elastic/logs/cloudaudit.googleapis.com%2Fdata_access","protoPayload":{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","authenticationInfo":{"principalEmail":"service-150691754250@container-engine-robot.iam.gserviceaccount.com","principalSubject":"serviceAccount:service-150691754250@container-engine-robot.iam.gserviceaccount.com"},"authorizationInfo":[{"granted":true,"permission":"container.clusters.get","resourceAttributes":{}}],"methodName":"google.container.v1.ClusterManager.GetCluster","policyViolationInfo":{"orgPolicyViolationInfo":{}},"request":{"@type":"type.googleapis.com/google.container.v1alpha1.GetClusterRequest","name":"projects/elastic-product/locations/us-central1-a/clusters/demo-elastic-co"},"requestMetadata":{"callerIp":"111.111.11.111","callerSuppliedUserAgent":"google-api-go-client/0.5 cluster-autoscaler,gzip(gfe)","destinationAttributes":{},"requestAttributes":{"auth":{},"time":"2022-06-01T11:15:10.836131149Z"}},"resourceLocation":{"currentLocations":["us-central1-a"]},"resourceName":"projects/elastic-product/zones/us-central1-a/clusters/demo-elastic-co","serviceName":"container.googleapis.com"},"receiveTimestamp":"2022-06-01T11:15:11.07151757Z","resource":{"labels":{"cluster_name":"demo-elastic-co","location":"us-central1-a","project_id":"elastic-product"},"type":"gke_cluster"},"severity":"INFO","timestamp":"2022-06-01T11:15:10.842495409Z","logging.googleapis.com/timestamp":"2022-06-01T11:15:10.842495409Z"}
```

#### Status is set but empty
```
{"insertId":"4pyr6eegiuw1","logName":"projects/elastic/logs/cloudaudit.googleapis.com%2Fdata_access","protoPayload":{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","authenticationInfo":{"principalEmail":"xxx-compute@developer.gserviceaccount.com","serviceAccountDelegationInfo":[{}]},"authorizationInfo":[{"granted":true,"permission":"storage.objects.get","resource":"projects/_/buckets/dataflow-staging-us-central1-xxx/objects/staging/xxx.jar","resourceAttributes":{}}],"methodName":"storage.objects.get","requestMetadata":{"callerSuppliedUserAgent":"BigstoreFile BigstoreIO (cr/xxx) ","destinationAttributes":{},"requestAttributes":{"auth":{},"time":"2022-06-01T11:19:08.205760711Z"}},"resourceLocation":{"currentLocations":["us-central1"]},"resourceName":"projects/_/buckets/dataflow-staging-us-central1-xxx/objects/staging/jfxrt-xxx.jar","serviceName":"storage.googleapis.com",**"status":{}**},"receiveTimestamp":"2022-06-01T11:19:08.699785539Z","resource":{"labels":{"bucket_name":"dataflow-staging-us-central1-150691754250","location":"us-central1","project_id":"elastic-product"},"type":"gcs_bucket"},"severity":"INFO","timestamp":"2022-06-01T11:19:08.199407722Z","logging.googleapis.com/timestamp":"2022-06-01T11:19:08.199407722Z"}
```

**Comment by andrewkroh** [comment]
What version of the GCP integration is being used?

**Comment by narenswamy** [comment]
Hi @kcreddy @andrewkroh @elastic/security-external-integrations (Team:Security-External Integrations)

I am getting the same error.

exception: "java.io.IOException: Error writing to Elasticsearch, some elements could not be inserted:
Document id 0FnDb4sB82OIuFNhqSsv: [1:2101] object mapping for [protoPayload.response.status] tried to parse field [status] as object, but found a concrete value (document_parsing_exception)

I am using GCP integration version 2.27.0. Anyone please help us.

**Comment by efd6** [comment]
@narenswamy Please file a new issue and link back to this. In the issue it would be very helpful if you can include the document that failed ingest. You should be able to find that in the logs.

**Comment by narenswamy** [comment]
@efd6 

Sure ,I have created the new issue. 
Link: https://github.com/elastic/integrations/issues/8315

Where do i check failed ingest logs? u mean, gcp dataflow log or elastic?

**Comment by efd6** [comment]
They should be in your agent logs.
