### ISSUE TITLE
[Carbon Black Cloud]: Alerts dashboard is broken

### ISSUE THREAD

**Issue by dimple-dave** [elastic/integrations#3462]
Loading "[Logs Carbon Black Cloud] Alerts Logs" fails on 8.x (tested 8.1.0).
Error encountered while loading saved dashboard: Could not find reference for kibanaSavedObjectMeta.searchSourceJSON.index

**Screenshot**: ![image](https://user-images.githubusercontent.com/101388993/171610208-05005218-d552-4c63-9168-cb5263f62250.png)

**Steps to Reproduce**
1. Navigate to the Carbon Black Cloud Integration page and click on Settings.
2. Install assets and click on the Assets tab.
3. Open the Carbon Black Cloud Alerts dashboard
4. Observe the error

**RCA:** On Analysis it was found that the integration was built on the elastic-stack snapshot version which was not the stable which resulted in the dashboard crash. The reason we found is that the reference to the index-pattern saved object is missing in latest update.

**Comment by ITSEC-Hescalona** [comment]
Same problem here
