### ISSUE TITLE
Audit integration ingest pipeline for non-anchored grok pattern

### ISSUE THREAD

**Issue by ph** [elastic/integrations#3477]
I've just noticed something in the system integration, we are using the grok processor to parse the string and transform [them into syslog](https://github.com/elastic/integrations/blob/main/packages/system/data_stream/syslog/elasticsearch/ingest_pipeline/default.yml#L7-L11) event.
```
- '%{SYSLOGTIMESTAMP:system.syslog.timestamp} %{SYSLOGHOST:host.hostname} %{DATA:[process.name](http://process.name/)}(?:\[%{POSINT:process.pid:long}\])?: %{GREEDYMULTILINE:system.syslog.message}'
- '%{SYSLOGTIMESTAMP:system.syslog.timestamp} %{GREEDYMULTILINE:system.syslog.message}'
- '%{TIMESTAMP_ISO8601:system.syslog.timestamp} %{SYSLOGHOST:host.hostname} %{DATA:[process.name](http://process.name/)}(?:\[%{POSINT:process.pid:long}\])?: %{GREEDYMULTILINE:system.syslog.message}'
```
There is a small missing thing in all the above regular expressions, they should be anchored "^" like this "^%{SYSLOGTIMESTAMP:system.syslog.timestamp}".
If you omit anchoring (beginning "^" or "$" if needed) your regular expressions and you receive a badly formatted line that doesn't match any of the pattern, the whole line will be scanned with a high rate of event this is a lot of CPU wasted on string that will never match. We have seen that problem often in Logstash.

I've checked with @jakelandis from the ingest team and the regular expressions aren't anchored by default; it's up to the integration author to ensure they are correctly defined.

**Comment by joshdover** [comment]
Aside from a manual audit, I think this should be prevented with warning-level package-spec validation that can be optionally ignored when needed. elastic-package / package-spec doesn't currently support such a feature, but it's been discussed in: https://github.com/elastic/package-spec/issues/313
