### ISSUE TITLE
Report breakdown of visualization types

### ISSUE THREAD

**Issue by ycombinator** [elastic/integrations#348]
We are aiming to move towards Lens as the primary visualization type to be used by all integrations packages (related: https://github.com/elastic/integrations/issues/265). To track this move it would be useful to report on a periodic basis (weekly? monthly?) a breakdown of visualization types being used across all integrations packages.

For instance, here is the breakdown as it stands right now:

```
find packages -type f -iname *.json | grep visualization | xargs -n1 jq -r .attributes.visState.type - | sort | uniq -c | sort -nr
```
```
 305 metrics
  91 pie
  58 table
  50 metric
  35 histogram
  28 timelion
  18 input_control_vis
  16 markdown
  15 line
  11 tile_map
  11 tagcloud
   7 area
   4 heatmap
   3 horizontal_bar
```

cc: @sorantis

**Comment by sorantis** [comment]
thanks for starting this @ycombinator. Is it safe to assume that `305 metrics` represents TSVB?

**Comment by ycombinator** [comment]
Yes, AFAIK the `metrics` is the internal visualization type for TSVB visualizations. @simianhacker can you confirm?

**Comment by AlonaNadler** [comment]
if it's taken from tleemetry then yes metrics is TSVB. Metric- single metric in visualize

**Comment by ycombinator** [comment]
> if it's taken from tleemetry...

Not taken from telemetry. This is based on a static analysis of Integrations packages, specifically the JSON representations of Kibana visualizations, as exported from Kibana.

But I believe it has the same meaning, regardless.

**Comment by AlonaNadler** [comment]
yes that is correct

**Comment by sorantis** [comment]
@timductive FYI

**Comment by ycombinator** [comment]
Here's the most recent breakdown. I copied the previous breakdown below as well so it's easy to see how things are changing.

| Vis. type | 2021-02-08 | 2020-10-28 |
| --- | --- | --- |
| metrics | 355 | 305 |
| pie | 114 | 91 |
| table | 70 | 58 |
| metric | 61 | 50 |
| histogram | 45 | 35 |
| line | 34 | 15 |
| timelion | 29 | 28 |
| tagcloud | 26 | 11 |
| markdown | 25 | 16 |
| input_control_vis | 25 | 18 |
| tile_map | 22 | 11 |
| area | 11 | 7 |
| heatmap | 8 | 4 |
| horizontal_bar | 6 | 3 |
| gauge | 1 | 0 |

**Comment by flash1293** [comment]
This is tracked via elastic stack now:
https://legacy-vis.kb.europe-west1.gcp.cloud.es.io:9243/app/dashboards#/view/c58a7a60-af64-11ec-a029-d32028b9cf73?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))
https://github.com/flash1293/legacy_vis_analyzer
