### ISSUE TITLE
[Bug][Pfsense Integration]

### ISSUE THREAD

**Issue by crtek** [elastic/integrations#3501]
GROK 
2nd pattern for HAProxy logs have a bug:
%{WORD:haproxy.frontend_name}~
it expects every frontend to end with "~"
as per HAProxy documentation:
['~' is a suffix for SSL frontend](http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#8.2.4)
also WORD -- Matches letters, digits, and underscores "_",
but frontends contains dashes too "-"

please replace it with:
%{NOTSPACE:haproxy.frontend_name}
as [HAProxy integration](https://github.com/elastic/integrations/blob/4993564a0043fdf698b548f2c55ea14572a39ff0/packages/haproxy/data_stream/log/elasticsearch/ingest_pipeline/default.yml) does

I would also suggest to add 2 more patterns like in the HAProxy integration
- error messages
- tcp frontends

and
add a field:
haproxy.connection_total_active_time_ms
as per [HAProxy documentation](http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#8.2.4)
- Ta: total active time for the HTTP request, between the moment the proxy
    received the first byte of the request header and the emission of the last
    byte of the response body.

Diff reference is [here](https://github.com/crtek/integrations/commit/70387af8386ea290dcde1bb5fb39f9e45d238e0d)

**Comment by legoguy1000** [comment]
Can u provide sample logs for the new patterns?

**Comment by crtek** [comment]
hi sure 
you can find them [here](https://github.com/crtek/integrations/commit/08098e055a916f6428a9a003b7c8bcf8c822b794)

I noticed I did not remove double escapes in my previous commit
I fixed that [too](https://github.com/elastic/integrations/commit/315a6f6d66e6bd53b619430af5c29e63f4904beb)
