### ISSUE TITLE
[Cisco][ASA] Syslog priority is stored in the not-ECS-compliant field `syslog.facility`

### ISSUE THREAD

**Issue by herrBez** [elastic/integrations#3507]
I noted that in the Filebeat Cisco-Asa Pipeline the syslog priority is stored in the field `syslog.facility` (which is not ECS-compliant) although it should be stored in the ECS-Field `log.syslog.priority`.

The problem has to do with this line https://github.com/elastic/beats/blob/3cdf704f414f37760a8307c6ad4703cd53c4daef/x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml#L18 and the previous one, where the syslog header is defined.

Further, if we take for instance this test https://github.com/elastic/beats/blob/3cdf704f414f37760a8307c6ad4703cd53c4daef/x-pack/filebeat/module/cisco/asa/test/not-ip.log#L1 (and the expected result https://github.com/elastic/beats/blob/3cdf704f414f37760a8307c6ad4703cd53c4daef/x-pack/filebeat/module/cisco/asa/test/not-ip.log-expected.json#L49) this lead to a `syslog.facility` of value 165, which is invalid (the range of syslog facility is between 0-23).

**Comment by efd6** [comment]
Closed by #3549 and elastic/beats#32025.
