### ISSUE TITLE
[o365] Ingest pipeline error

### ISSUE THREAD

**Issue by cakarlen** [elastic/integrations#3510]
Hi,

I have the O365 Fleet integration configured and enabled for my cluster. Unfortunately, **_all_** the documents present no data due to a bug in the ingest pipeline:

![CleanShot 2022-06-14 at 10 00 35](https://user-images.githubusercontent.com/33635487/173595933-6384d073-c097-40d6-a5e6-e43da8eeba23.png)

I have recently updated the integration to the latest version (1.5.1), thinking that would fix the issue, but no avail.

Thanks!

**Comment by legoguy1000** [comment]
This issue sounds really familiar.  Anything similar to #2550 or #2519?

**Comment by efd6** [comment]
@cakarlen Can you post a suitably sanitised complete event in JSON with `preserve_original_event` set to true?
