### ISSUE TITLE
MYSQL: performance data_stream configs not passed

### ISSUE THREAD

**Issue by lalit-satapathy** [elastic/integrations#3514]
Configs are not passed down in the MYSQL data_stream configs.

Also performance data_stream is disabled by default. It seems to be breaking when enabled.

**Comment by lalit-satapathy** [comment]
https://discuss.elastic.co/t/metricbeat-mysql-8-2-3-fleet-integration-failing/307306

**Comment by hendry-lim** [comment]
Related to #2349.

**Comment by ritalwar** [comment]
Need to resolve: https://github.com/elastic/integrations/issues/4229
