### ISSUE TITLE
Suricata events don't set the host.name field in ingest pipeline

### ISSUE THREAD

**Issue by 111andre111** [elastic/integrations#3521]
With this PR came in to Suricata integration
https://github.com/elastic/integrations/pull/1105
the tag `forwarded` due to the fact that now the ingest pipeline should care about the hostname.
https://github.com/elastic/integrations/blob/main/packages/suricata/data_stream/eve/manifest.yml#L20-L22
The host.name field should not be set by the integration on the agent side any more.

This correction PR still added that this should be true only for forwarded events:
https://github.com/elastic/integrations/pull/1854

In the originating filebeat module this tag has not been set:
https://github.com/elastic/beats/blob/v8.2.0/x-pack/filebeat/module/suricata/eve/manifest.yml#L11-L12

Now as a last step there should be an addition to the ingest pipeline that readds `host.name` field:
https://github.com/elastic/integrations/tree/main/packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline

I am not sure if the suricata integration is considered a `local` integration meaning that agent.name = host.name?

At least suricata events hold a hostname field for http events, would that make sense to add that one in the case as a host.name field?
https://suricata.readthedocs.io/en/latest/output/eve/eve-json-format.html?highlight=hostname#id2
https://github.com/elastic/integrations/blob/main/packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml#L283-L290

Now the host.name field is needed for the Kibana host view for the Events and External Events:
https://www.elastic.co/guide/en/security/current/hosts-overview.html

**Comment by zez3** [comment]
I think we should also add the suricata http hostnames to https://www.elastic.co/guide/en/ecs/current/ecs-related.html#field-related-hosts

**Comment by zez3** [comment]
> I think we should also add the suricata http hostnames to https://www.elastic.co/guide/en/ecs/current/ecs-related.html#field-related-hosts

It seems the current Integration is already populating related hosts

**Comment by andrewkroh** [comment]
> I think we should also add the suricata http hostnames to [ECS related.hosts]

I agree, any hostnames appearing in the event should be appended into the `related.hosts` field.

> It seems the current Integration is already populating related hosts

It is populating it as `related.hosts = [ {{ url.domain }} ]`. But in the case of TLS event I think it could also be appending the `tls.sni` name.

**Comment by andrewkroh** [comment]
> While it can analyze the traffic of the host that it is installed on which the host.name == agent.name, that isn't normally the case so the host that suricata/agent is running on, you don't want host.name set as that gets interpreted as the sensor is making the network traffic when its actually just analyzing it.

Exactly. And in the case where Suricata is monitoring traffic of the host on which it is installed, you can remove the `forwarded` tag from the integration. This will cause the [add_host_metadata processor](https://www.elastic.co/guide/en/beats/filebeat/current/add-host-metadata.html#add-host-metadata) to enrich the event with `host.*` data collected from the machine running Elastic Agent.

<img width="498" alt="suricata-integration-forwarded-tag-removal" src="https://user-images.githubusercontent.com/4565752/176318805-d8b5dc43-501a-45bd-80dd-2431b802bf6d.png">
