### ISSUE TITLE
Common Fields for Service Inventory Schema

### ISSUE THREAD

**Issue by exekias** [elastic/integrations#353]
This is a meta issue to track the work related to defining the common fields for service inventory schema. We want to be able to identify any running service, like a MySQL instance, an Apache webserver or a Go application.

The output should be a set of required and recommended fields to be added to any event related to a service.

**Comment by kaiyan-sheng** [comment]
Add common service fields: https://github.com/elastic/observability-dev/pull/1314

**Comment by kaiyan-sheng** [comment]
I checked in Metricbeat we are using `service.type` already in a lot of modules. @jsoriano Do you know if there's anything else we need to do for service inventory?

**Comment by jsoriano** [comment]
> I checked in Metricbeat we are using `service.type` already in a lot of modules. @jsoriano Do you know if there's anything else we need to do for service inventory?

Yeah, in Metricbeat a lot of modules fill the `service.type` field, and the [`service.name` option](https://www.elastic.co/guide/en/beats/metricbeat/7.10/configuration-metricbeat.html#_service_name) can be used on any module to fill `service.name`. Filebeat also uses to set the `service.type` field, but there is no special setting for `service.name` as in Metricbeat. In any case the `add_fields` processor can also be used to add `service.name`.

In some modules I think that we could also collect the service version for `service.version`, but we are not doing it, this would be something to add.

Regarding `service.node.name`, I think that in some modules we collect something similar, but using service-specific fields (`kafka.broker.id`, `kubernetes.node.name`...), we could consider moving them to this inventory field.

So there would be two things to do, consider adding the `service.version` when possible, and consolidate the use of `service.node.name` to identify individual instances of a service.

**Comment by jsoriano** [comment]
> In some modules I think that we could also collect the service version for `service.version`, but we are not doing it, this would be something to add.

Actually we are doing it in some modules, we could check if we can do it in more of them.

**Comment by kaiyan-sheng** [comment]
TODOs:

- [ ] Change to use `service.version` to collect version information.
- [ ] Change to use `service.node.name` to identify individual instances of a service.
