### ISSUE TITLE
Akamai integration description doesn't follow convention

### ISSUE THREAD

**Issue by joshdover** [elastic/integrations#3538]
We have a convention for the integration descriptions to make them consistent in the integration tile UI in Kibana. This integration doesn't follow it so it looks quite out of place.

<img width="964" alt="image" src="https://user-images.githubusercontent.com/1813008/174602903-5941ca58-51d6-4f92-b01b-04a57b2fa163.png">

I recommend something like: `Collect logs from Akamai SIEM with Elastic Agent.`

**Comment by jamiehynds** [comment]
@kcreddy can you confirm if this was taken care of via https://github.com/elastic/integrations/issues/3400?

**Comment by kcreddy** [comment]
Closed by https://github.com/elastic/integrations/pull/3478
