### ISSUE TITLE
Support AWS postgresql log in postgresql integration

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#3540]
Logs from AWS PostgreSQL is not supported in our existing postgresql integration. When I tried to ingest logs from AWS PostgreSQL using the existing PostgreSQL integration, grok pattern fails. Here are some sample logs:
```
2022-06-16 17:58:41 UTC::@:[7770]:LOG:  checkpoint complete: wrote 8 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.806 s, sync=0.003 s, total=0.822 s; sync files=6, longest=0.003 s, average=0.001 s; distance=65536 kB, estimate=65536 kB
2022-06-16 17:58:40 UTC::@:[7770]:LOG:  checkpoint starting: time
```

The main issue is: AWS PostgreSQL logs are separated with `:` instead of the supported `,` and `<space>` in https://github.com/elastic/integrations/blob/main/packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L24-L29. We will probably have to create a new pipeline called `pipeline-aws.yml` and use `:` as separator instead.

Here is documentation on AWS PostgreSQL log format to check on what are the fields represent for:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.PostgreSQL.html#USER_LogAccess.Concepts.PostgreSQL.overview

**Comment by ravikesarwani** [comment]
@rameshelastic I was wondering if this is something that can be picked up by the services team soonish?
We are working with cloud observability team on Firehose ingestion and this is blocking to get the issue completed for AWS RDS logs. It would be ideal to extend this integration and make it work for AWS RDS PostgreSQL logs as well.

**Comment by kaiyan-sheng** [comment]
@rameshelastic Sorry since the customer is waiting on us to deliver this integration, we decide to jump into it and added the support.
