### ISSUE TITLE
Make CockroachDB GA

### ISSUE THREAD

**Issue by ritalwar** [elastic/integrations#3550]
# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

<!-- Uncomment as many of the following sections as needed
### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists

### Metric dataset changes

_This entry is currently only recommended. It will be mandatory once we provide better support for it._

- [ ] Sample event (`sample_event.json`) exists

**Comment by ritalwar** [comment]
Fix  #25622 before moving to GA.

**Comment by ritalwar** [comment]
Depends on https://github.com/elastic/kibana/issues/129344

**Comment by rameshelastic** [comment]
@ritalwar , could you please post the latest on this?

**Comment by ritalwar** [comment]
Required changes has been done.
https://github.com/elastic/beats/pull/32527 and https://github.com/elastic/integrations/pull/3676 are PRs under review.
