### ISSUE TITLE
Support for generating sample events in metrics datasets

### ISSUE THREAD

**Issue by andresrc** [elastic/integrations#356]
As part of delivering metrics datasets, it's interesting to add a sample document, which can be used to explore the content of the dataset, testing, review, etc.

We have https://github.com/elastic/elastic-package/issues/150 to investigate whether `elastic-package` can provide support in generating it. 

The goal of this issue is, regardless of the outcome of that issue, to document how to generate such a sample, adding it to the [guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines).

**Comment by mtojek** [comment]
I created the issue here: https://github.com/elastic/elastic-package/issues/150

**Comment by andresrc** [comment]
ok, we leave this one for documenting the process in the guideline.

**Comment by mtojek** [comment]
I think we can resolve this one as the work is done here.
