### ISSUE TITLE
Jamf Protect

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#3575]
### Description
Jamf Protect is an endpoint security solution built for macOS. It leverages on-device analysis to proactively block, isolate and remediate Mac security threats. 

### Architecture
Jamf Protect exposes events and alerts via an API endpoint: https://docs.jamf.com/jamf-protect/documentation/Jamf_Protect_API.html

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by andrewkroh** [comment]
Relates (probably blocked by): https://github.com/elastic/beats/issues/31117

**Comment by ebeahan** [comment]
PR: https://github.com/elastic/integrations/pull/9135

**Comment by jamiehynds** [comment]
Closing, as our integration with Jamf Protect is now available: https://docs.elastic.co/integrations/jamf_protect
