### ISSUE TITLE
AWS Logs Custom integration - log_stream_prefix key with a typo

### ISSUE THREAD

**Issue by arielromeo** [elastic/integrations#3608]
Hi All, 

I'm using elastic.co hosted solution, the way to reproduce the error is:
1. Create an Agent policy
2. Add Custom AWS Log package/integration.
3. Enable "Collect Logs from CloudWatch"
4. Enter a "Log group ARN", "Region Name" and "Log Stream Prefix"
5. Save and apply. 

After doing that, you will notice that property "Log Stream Prefix" is not used. The reason seems to be the following one:

There exist a key mismatch between the field manifest for `log_streamS_prefix` (streams in plural) defined in manifest (https://github.com/elastic/integrations/blob/6c883f3664fced60469c63cc0133acc9012ef003/packages/aws_logs/data_stream/generic/manifest.yml#L45) and `log_stream_prefix` (stream in singular) used in the template file: https://github.com/elastic/integrations/blob/6c883f3664fced60469c63cc0133acc9012ef003/packages/aws_logs/data_stream/generic/agent/stream/aws-cloudwatch.yml.hbs#L43

The workaround I'm using right now is to do what was described in steps 2-4 using the API (POST, `api/fleet/package_policies`) and push my package with both keys in `vars` section of the json sent.  

I hope you guys can take this and fix it soon in reward all the hours I spent tracing this bug. :)

**Comment by aspacca** [comment]
hi @arielromeo , thanks for spotting this!

to be fixed in #3610

**Comment by arielromeo** [comment]
Thanks so much @aspacca for the quick fix. Could you please tell me how long will take it to be available a new version of Custom AWS Logs in Elastic.co hosted solution ?

**Comment by aspacca** [comment]
@arielromeo the packages will be promoted today
