### ISSUE TITLE
[docs] List assets included/associated with each integration's README

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/integrations#3625]
In #3433, @jamiehynds suggested that we consider listing assets included/associated with each integration: 

>We could consider a section to cover assets included, or associated with the integration. e.g. describe the dashboards and saved searches that ship with the integration. Possibly even link to detection rules/ML jobs/alerts that may be associated with the integration (but doesn't ship with the integration) 

However, after looking at the dashboards for the top 5 integrations I was updated in https://github.com/elastic/observability-docs/issues/1019, I think we should consider automating this instead of maintaining freeform narrative text about specific dashboards.

As a first step, a writer could help with dashboard descriptions in the JSON files found in `packages/*/kibana/dashboard/`. Then we could generate a list of them from the JSON.

@jamiehynds also suggested adopting a similar approach for detection rules.

cc @approksiu @jamiehynds @elastic/obs-docs

**Comment by dedemorton** [comment]
++ to automating this. Otherwise I guarantee that the text will get out of date over time.

**Comment by bmorelli25** [comment]
Related to https://github.com/elastic/observability-docs/issues/1848. When we automate our integration documentation we should absolutely include relevant package assets.

**Comment by bmorelli25** [comment]
> As a first step, a writer could help with dashboard descriptions in the JSON files found in `packages/*/kibana/dashboard/`. Then we could generate a list of them from the JSON.

If I understand correctly, are you suggesting we edit the `attributes.description` value in each dashboard to be more descriptive? Then use that to automatically add a dashboard description to the docs? For example, this:

https://github.com/elastic/integrations/blob/f1a33c30dc0d92defe9e33996c9ab873708510bc/packages/apache/kibana/dashboard/apache-Logs-Apache-Dashboard.json#L3

I think that could work. The only downside I see with that solution is that the screenshot of each dashboard isn't tied to the updated description.

Another option would be to add a description key to the `screenshots` array in the package.manifest files. Then the screenshot and description are tied together.

https://github.com/elastic/integrations/blob/f1a33c30dc0d92defe9e33996c9ab873708510bc/packages/apache/manifest.yml#L13-L17

A downside to this approach is that we would likely have to duplicate description in the package manifest and dashboard JSON as we probably wouldn't want to keep the dashboard descriptions as-is.
