### ISSUE TITLE
juniper_junos ingest pipeline doesn't contain sufficient parsing

### ISSUE THREAD

**Issue by getkub** [elastic/integrations#3657]
Loading the ingest pipeline from:
https://github.com/elastic/integrations/blob/main/packages/juniper_junos/data_stream/log/elasticsearch/ingest_pipeline/default.yml

does not parse anything. The other modules like infoblox/fortinet/cisco etc are self contained and loading the ingest pipeline makes the fields perfect. But the juniper's one doesn't have grok/parsing logic in the ingest pipeline

**Comment by leweafan** [comment]
As I know juniper junos filebeat module uses js script on host side to parse logs (/usr/share/filebeat/modules/juniper/...). Ingest pipeline only renaming fields.

**Comment by getkub** [comment]
> As I know juniper junos filebeat module uses js script on host side to parse logs (/usr/share/filebeat/modules/juniper/...). Ingest pipeline only renaming fields.
Thanks. Is it possible to move the logic from js script to pipeline, so raw data can be directly sent to ES. cheers
