### ISSUE TITLE
Migrate postgresql integration

### ISSUE THREAD

**Issue by andresrc** [elastic/integrations#366]
# Package / Dataset creation or update checklist

This checklist is intended for Devs which create or update a package to make sure they are consistent.

* [x] Required Kibana version set to target version: 7.11.0

## All Changes

* [ ] Change follows [development guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines)
* [x] Supported versions of the subject being monitored are documented
* [x] Supported operating systems are documented (if applicable)
* [x] [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
* [ ] Documentation
  * [ ] Import https://github.com/elastic/beats/pull/24588 
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] At least a manual test with ES / Kibana / Agent has been performed.
* [x] The required Kibana version is set to the lowest version used in the manual test.

### Dashboards

* [x] Dashboards exists (if applicable)
* [x] Screenshots of added / updated dashboards
* [ ] Datastream filters added to visualizations

## Log datasets

* [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
* [x] Test log files exist for the grok patterns
* [x] Generated output for at least 1 log file exists
* [x] Add changes for logs in CSV format (https://github.com/elastic/integrations/issues/720).
* [ ] Add changes for log_statement (https://github.com/elastic/beats/pull/24607).

## Metric datasets

This entry is currently _recommended_. It will be mandatory once we provide better support for it.

* [x] Sample event (`sample_event.json`) exists

## New Packages

* [x] Screenshot of the Fleet "Add Integration" Page.

**Comment by masci** [comment]
Marking as done after the recent fixes
