### ISSUE TITLE
Migrate apache integration

### ISSUE THREAD

**Issue by andresrc** [elastic/integrations#370]
# Package / Dataset creation or update checklist

This checklist is intended for Devs which create or update a package to make sure they are consistent.

If the change targets a specific ES / Kibana / Agent version, uncomment this line and specify version.

* [ ] ~Required Kibana version set to target version: 7.11.0~ We don't need to require Kibana 7.11.0 for this package.

## All Changes

* [ ] Change follows [development guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines)
* [x] Supported versions of the subject being monitored are documented
* [ ] ~Supported operating systems are documented (if applicable)~
* [x] [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
* [x] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] ~At least a manual test with ES / Kibana / Agent has been performed.~ (covered by system tests)
* [x] The required Kibana version is set to the lowest version used in the manual test.

### Dashboards

* [ ] Dashboards exists (if applicable)
* [ ] Screenshots of added / updated dashboards
* [ ] Datastream filters added to visualizations

## Log datasets

* [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
* [ ] Generated output for at least 1 log file exists

## Metric datasets

This entry is currently _recommended_. It will be mandatory once we provide better support for it.

* [ ] Sample event (`sample_event.json`) exists

## New Packages

* [ ] ~Screenshot of the Fleet "Add Integration" Page.~

**Comment by mtojek** [comment]
@andresrc I'm not sure if I understand these action items:

> Pipeline tests exist (if applicable)
> Test log files exist for the grok patterns
> Generated output for at least 1 log file exists

Pipeline tests use log files as test input. Once they're processed by ingest pipelines, the result is compared with generated output. I mean, pipeline tests require test log files and generated output, there is no way for them to exist without any of them.

Did you think about sth else?

EDIT:

It looks like it was missed in the PR review: https://github.com/elastic/integrations/pull/342#discussion_r514119497

**Comment by mtojek** [comment]
As discussed offline with the team I will try to introduce a condition which will change the Metricbeat's behavior and emit adjusted fields under different names.

**Comment by mtojek** [comment]
Let's write down all action item:

- [ ] Update Docker image to latest version
- [ ] Add information about supported OSes
- [ ] Update period for the `status` dataset
- [ ] Add field defintions in `apache.status` to cover new ECS fields (uptime, hostname)
- [ ] Modify Metricbeat to collect modified fields if running in Fleet mode
(once Docker images for fleet are released, dashboards will stop working)
- [ ] Update dashboards with latest changes in Metricbeat
- [ ] Update the sample event for `status` dataset
- [ ] Save sample events for other dataset
- [ ] Write pipeline tests for Apache
- [ ] Refactor dashboards according to the instructions in the migration assessment
- [ ] Retake new screenshots of dashboards

**Comment by andresrc** [comment]
sorry, I'll remove the grok one, thanks!

**Comment by mtojek** [comment]
Changes partially merged, I will proceed with the next step:

>  Modify Metricbeat to collect modified fields if running in Fleet mode

**Comment by mtojek** [comment]
It looks like there were issues in the unified release, which blocked releasing changes in Metricbeat. It will block:

>  Fix metrics dashboard to properly visualize total_bytes

**Comment by mtojek** [comment]
All action items done. Resolving.
