### ISSUE TITLE
[Feature Request] Cisco NSEL support

### ISSUE THREAD

**Issue by sathevaner** [elastic/integrations#3704]
The out of the box integrations for Netflow are not compatible with Cisco NSEL.

**Comment by andrewkroh** [comment]
@sathevaner Could you please elaborate on this issue and include references to any relevant vendor documentation for the data you would like supported. And any errors you may have encountered with using the netflow integration with NSEL.

We will need a pcap capture of some NSEL traffic to test with if it would be possible to provide that. IIUC NSEL is sending standard Netflow V9 data (RFC 3954) which is supported by the integration. So probably NSEL uses "vendor extensions" to add custom netflow fields and we don't have definitions of those fields in https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/netflow/decoder/fields/cisco.csv.

**Comment by sathevaner** [comment]
I'm going to close the issue, as it was a misunderstanding on my part.
