### ISSUE TITLE
Migrate memcached integration

### ISSUE THREAD

**Issue by andresrc** [elastic/integrations#372]
# Package / Dataset creation or update checklist

This checklist is intended for Devs which create or update a package to make sure they are consistent.

If the change targets a specific ES / Kibana / Agent version, uncomment this line and specify version.

* [x] Required Kibana version set to target version: 8.2

## All Changes

* [x] Change follows [development guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines)
* [x] Supported versions of the subject being monitored are documented
* [x] Supported operating systems are documented (if applicable)
* [x] [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] At least a manual test with ES / Kibana / Agent has been performed.
* [x] The required Kibana version is set to the lowest version used in the manual test.

### Dashboards

* [x] Dashboards exists (if applicable)
* [x] Screenshots of added / updated dashboards
* [ ] Datastream filters added to visualizations

## Log datasets

* [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
* [ ] Test log files exist for the grok patterns
* [ ] Generated output for at least 1 log file exists

## Metric datasets

This entry is currently _recommended_. It will be mandatory once we provide better support for it.

* [x] Sample event (`sample_event.json`) exists

## New Packages

* [ ] Screenshot of the Fleet "Add Integration" Page.

**Comment by ishleenk17** [comment]
Link to the technical Doc for Memcached: 
https://docs.google.com/document/d/1IrRep-geuEyBqYzCxGV0trSz1iHUnOHyqVr-YUdICFo/edit#

**Comment by ishleenk17** [comment]
This issue is being fixed at the Fleet side with https://github.com/elastic/kibana/issues/127268

**Comment by ishleenk17** [comment]
The kibana version used is 8.3 for any new integrations as discussed with Akshay
