### ISSUE TITLE
[GCP] Remove lightweight module in `gcp.billing` data stream

### ISSUE THREAD

**Issue by endorama** [elastic/integrations#3720]
Part of #3188

- [ ] For the migrated data streams (from Beats): we should move the configuration part from Beats into integrations.
- [ ] For all data streams: use ingest pipeline instead of rename processor.

**Comment by legoguy1000** [comment]
IDK if this will be possible since this isn't a lightweight module (at least from my understanding) its custom go code to query BigQuery.

**Comment by kaiyan-sheng** [comment]
Yeah we probably should close this issue @endorama :)

**Comment by endorama** [comment]
Yes, I was to eager and forgot that detail. Closing as not applicable.
