### ISSUE TITLE
Migrate nginx package

### ISSUE THREAD

**Issue by andresrc** [elastic/integrations#373]
# Package / Dataset creation or update checklist

This checklist is intended for Devs which create or update a package to make sure they are consistent.

If the change targets a specific ES / Kibana / Agent version, uncomment this line and specify version.

* [ ] Required Kibana version set to target version: 7.11.0

## All Changes

* [x] Change follows [development guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines)
* [x] Supported versions of the subject being monitored are documented
* [x] Supported operating systems are documented (if applicable)
* [x] [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] At least a manual test with ES / Kibana / Agent has been performed.
* [x] The required Kibana version is set to the lowest version used in the manual test.

### Dashboards

* [x] Dashboards exists (if applicable)
* [x] Screenshots of added / updated dashboards
* [x] Datastream filters added to visualizations

## Log datasets

* [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
* [x] Generated output for at least 1 log file exists

## Metric datasets

This entry is currently _recommended_. It will be mandatory once we provide better support for it.

* [x] Sample event (`sample_event.json`) exists

## New Packages

* [ ] ~Screenshot of the Fleet "Add Integration" Page.~

**Comment by andresrc** [comment]
The nginx ingress controller part goes to a different package.

**Comment by mtojek** [comment]
Let's write down all action item in a convenient order:

- [ ] Update Docker image to latest version
- [ ] Add information about supported OSes
- [ ] Add ECS field definition to replace `nginx.access.user_agent`.
- [ ] Add field definition to collect field `nginx_up`
- [ ] Pull ingest_contoller dashboards if missing
- [ ] Modify Metricbeat to collect modified fields if running in Fleet mode
- [ ] Documentation: write a paragraph on how to prepare Nginx instances to expose metrics (server status)
- [ ] Update dashboards with latest changes in Metricbeat
- [ ] Write system tests
- [ ] Remove duplicated field definitions, use ECS ones
- [ ] Update the sample event for `stubstatus` dataset
- [ ] Save sample events for other dataset
- [ ] Refactor dashboards according to the instructions in the migration assessment
- [ ] Extract the `ingest_controller` to a separate integration
- [ ] Retake new screenshots of dashboards

**Comment by mtojek** [comment]
@andresrc I've comprised the list above based on the migration assessment, but I skipped items that would elongate it like new datasets, fixes requiring investigation (or neverending timeline). There is one exclusion from this rule: `ingest_controller` as a separate integration. Does it sound good?

**Comment by mtojek** [comment]
Resolving this issue in favor of https://github.com/elastic/integrations/issues/467 . Other action items are done.
