### ISSUE TITLE
[BUG] [ProblemChild] Anomaly Detection jobs fail to start due to missing mappings

### ISSUE THREAD

**Issue by ajosh0504** [elastic/integrations#3737]
While testing the ProblemChild integration package in an Elastic Cloud cluster, we found that some of the Anomaly Detection jobs failed to start with the following error:

![image (14)](https://user-images.githubusercontent.com/30438249/179609814-aec6f89a-9edb-4c77-a84d-54886f182b51.png)

Steps to reproduce:
1) Install the ProblemChild integration package in your Elastic Cloud cluster
2) Start the job `problem_child_high_sum_by_host` 
3) Watch the above datafeed error appear

cc: @cojoe01

**Comment by ajosh0504** [comment]
As an aside, we have also received feedback that rules associated with the ProblemChild ML jobs are hard to find. We might want to consider prefixing the rule names with an identifier to make them easier to find.

**Comment by ajosh0504** [comment]
As the error mentions, the `blocklist_label` field not being mapped causes problems as some of the jobs are referencing this field in their detector configurations. It is best practice anyway to explicitly define mappings for non-ECS/custom fields. So we should add mappings for `problemchild.prediction`, `problemchild.probability`, and `blocklist_label` to the index template.

The DGA integration package doesn't explicitly specify mappings either, so we probably want to follow the same procedure there as well.

**Comment by ajosh0504** [comment]
This is currently not possible to do from within the integration packages atm. Users need to edit [Component Templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-component-template.html) from within Kibana to add custom mappings to datastreams that are modified by other datastreams. 

Added steps to do this in the DGA and ProblemChild integration blogs- the update should go out shortly.

**Comment by ajosh0504** [comment]
Still waiting for blog updates to go out.

cc: @jtnk @devonakerr

**Comment by szeitlin** [comment]
> Still waiting for blog updates to go out.
> 
> cc: @jtnk @devonakerr

This feels like it's outside the scope of this ticket? I think you can re-close this ticket?

**Comment by ajosh0504** [comment]
@szeitlin Turns out those updates are what needs to happen to rectify this, not something we can do within the package atm.

**Comment by szeitlin** [comment]
@ajosh0504 ohhhh I see, I thought that was _in addition_ not the whole thing. :P Thanks for clarifying!
