### ISSUE TITLE
[BUG][DGA] Detection rule referencing non-existent ML job

### ISSUE THREAD

**Issue by ajosh0504** [elastic/integrations#3738]
While testing the DGA integration package in an Elastic Cloud cluster, we found that on of the detection rules associated with DGA was referencing a non-existent ML job:

<img width="908" alt="image (15)" src="https://user-images.githubusercontent.com/30438249/179614815-4a6139d4-8f59-4587-ac09-4a6be38da137.png">

Steps to reproduce:
1) Install the DGA integration package in your Elastic Cloud cluster
2) Enable the rule "Potential DGA Activity" 
3) Watch the above error appear

cc: @cojoe01

**Comment by ajosh0504** [comment]
There seems to be a residual reference to an "experimental" ML job in the DGA integration package. This should be a quick one to fix.

**Comment by szeitlin** [comment]
@ajosh0504 this one is being handled along with the ProblemChild one, is that correct?

**Comment by ajosh0504** [comment]
That's right. It's in progress in the PR linked above ^. Currently trying to test the package with the updates.

**Comment by ajosh0504** [comment]
Still waiting to merge the PR- will update the rule tags once we reach a consensus, then merge.
