### ISSUE TITLE
Create package to monitor server workers using Citrix ADC (Netscaler)

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#3746]
Citrix ADC integration(Formally Netscaler) collects metrics from Citrix ADC. Based on the usage analysis, we are integrating the first set of datastreams those are listed below,

- [x] #4322
- [x] #4364
- [ ] #4418
- [ ] #4458
- [ ] #4473

**Comment by rameshelastic** [comment]
@muthu-mps  can this issue be closed?  Are we tracking all the Open PRs separately?

**Comment by muthu-mps** [comment]
@rameshelastic - We are tracking the open PR's here. @kush-elastic - Since we are tracking all the datastreams here better to keep the issue open until we merge all open datastreams.
