### ISSUE TITLE
Migrate Airflow integration

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#3748]
# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

**Comment by ritalwar** [comment]
Updates in - https://github.com/elastic/integrations/issues/4465

**Comment by ritalwar** [comment]
Initial Release PR - https://github.com/elastic/integrations/pull/4630

Next Steps:
1. Reduce the field mapping to avoid any metric explosion in future.
2. Create Dashboards
3. Write System Tests.

**Comment by ritalwar** [comment]
Addressed review comments for PR - https://github.com/elastic/integrations/pull/4630 .
Removed few mapping fields to avoid metric explosion.

Next Steps:
1. Create Dashboards
2. Write System Tests.

**Comment by ritalwar** [comment]
Task for Dashboads: https://github.com/elastic/integrations/issues/5001

**Comment by rameshelastic** [comment]
@ritalwar , can you please update this ticket with the latest?
thanks.

**Comment by ritalwar** [comment]
Dashboards PR in review: https://github.com/elastic/integrations/pull/5185
