### ISSUE TITLE
Improve discoverability of rules associated with the DGA and ProblemChild packages

### ISSUE THREAD

**Issue by ajosh0504** [elastic/integrations#3762]
We have received the following feedback about rules associated with the DGA and ProblemChild integration packages: 

```
Finding the four DGA related detection rules was easy as I just typed in "DGA".  However with LOTL there are eight jobs all named uniquely...and which you often cannot even see the rule name due to the rule management UI collapsing names until you hover over each one  

So to showcase the eight LOTL rules, I actually copied each one individually, and add a [Problem Child] suffix to the name.  This is so I can find the rules easy enough.  I noticed things like ML tagging was not consistent either, and perhaps some other tags like Supervised vs. Unsupervised could be useful?
```

cc: @cojoe01

**Comment by ajosh0504** [comment]
Looking at the way the rules are tagged, the rules associated with ML jobs are tagged `ML`, which is the convention we follow for ML job-based rules. Query-based rules based on the supervised models are tagged `ML-DGA` and `ML-ProblemChild` respectively, which sounds reasonable. 

We could add two additional tags, `DGA` and `LotL` which will help identify all rules associated with each of the models, without violating the general convention followed by other rules i.e. no prefixes.

**Comment by szeitlin** [comment]
@SourinPaul created a separate ticket for @randomuserid re: tracking ML jobs, and there's also a google doc that should be linked there and here. I think it would be simpler if we gather up all the things that need to be tagged and come up with some kind of naming system based off of what we know needs tagging right now, rather than doing these as one-off separate things.

**Comment by ajosh0504** [comment]
If there's an existing convention to be followed, happy to follow it. 

Otherwise, I've tagged all DGA rules with an additional `DGA` tag and living-off-the-land rules with a `LotL` tag. If no system exists, we could expand this to tag all rules related to a particular use case, such as Data Exfil, Malicious Insider etc. with the appropriate use case tag?

Also something to note:
There's two types of rules:
- Rules based on anomaly detection jobs: these are generically tagged `ML` tag in `detection-rules`.
- Rules based on supervised models: these don't have any set convention since such rules don't come up often. We've tagged them `ML-DGA`, `ML-ProblemChild` to indicate which supervised model they are related to.

**Comment by szeitlin** [comment]
This is the ticket I was looking for: https://github.com/elastic/security-team/issues/4535

**Comment by SourinPaul** [comment]
Our ulterior goal is to simplify tags so users (and workflows) can find the dependent assets consistently. 

#4535 covers the need to tag package name, entity type, and general threat category. 

e.g., all `Living Of the Land` assets can be tagged with `LotL` (package name), `Host` (entity type), and `Internal` (threat Category). If we tag all assets with these tags, users will know how to search across all objects.

Also, there may be additional workflow requirements to classify assets (e.g., ML, log source types, etc.). We can introduce additional tags (to accommodate existing workflows) or explore how Investigation Guides metadata can meet these workflow needs.

How about we create a simple EA inventory worksheet to track all assets for an EA package? This will allow us to manage the user-facing tags consistently without proliferating them.

Thoughts?

**Comment by szeitlin** [comment]
> Our ulterior goal is to simplify tags so users (and workflows) can find the dependent assets consistently.
> 
> #4535 covers the need to tag package name, entity type, and general threat category.
> 
> e.g., all `Living Of the Land` assets can be tagged with `LotL` (package name), `Host` (entity type), and `Internal` (threat Category). If we tag all assets with these tags, users will know how to search across all objects.
> 
> Also, there may be additional workflow requirements to classify assets (e.g., ML, log source types, etc.). We can introduce additional tags (to accommodate existing workflows) or explore how Investigation Guides metadata can meet these workflow needs.
> 
> How about we create a simple EA inventory worksheet to track all assets for an EA package? This will allow us to manage the user-facing tags consistently without proliferating them.
> 
> Thoughts?

I think you mean `ultimate` not `ulterior` re: our goals :) 

re: classifying assets, that should be done in code, not in a worksheet, but we can certainly start with a google sheet to decide on the naming conventions we want to use. This is what I was trying to hint at.

**Comment by ajosh0504** [comment]
We should maybe move this conversation elsewhere- this is a public repo so we shouldn't link to internal stuff here? Plus this conversation goes beyond integrations.

**Comment by ajosh0504** [comment]
Closing this issue- will be tracked internally.
