### ISSUE TITLE
Integration page - add documentation for EKS

### ISSUE THREAD

**Issue by ofiriro3** [elastic/integrations#3782]
As part of the CIS k8s integration updates, we need to update the integrations readme and screenshots. This issue will track this work. 

To Do
- [ ] Update Integration readme
- [ ] [Update integration screenshots](https://github.com/elastic/integrations/issues/3827)

**Comment by tinnytintin10** [comment]
First draft of proposed updates to the KSPM integration readme: 

> # Kubernetes Security Posture Management 
> 
> This integration periodically monitors and compares Kubernetes infrastructure against security best practices defined by CIS to help security, DevOps, and DevSecOps personnel to: 
> 
> 1. Identify and remediate misconfigurations 
> 2. Understand the overall security posture of their Kubernetes clusters both- individually and holistically 
> 
> ## Integration Assets 
> 
> After this integration has been installed for the first time, the following assets will get created and made available in the Security solution UI: 
> 
> | Asset             | Description                                                                                                                                         |
> | ----------------- | --------------------------------------------------------------------------------------------------------------------------------------------------- |
> | Posture Dashboard | The posture dashboard provides an overview of the security posture of all Kubernetes clusters monitored                                                |
> | Findings          | Findings communicate the outcome of a specific resource being evaluated with a specific rule. All latest findings are viewable on the findings page |
> | Benchmark Rules   | Benchmark rules are used to assess Kubernetes resources for secure configuration. Benchmark rules are viewable on the Benchmark page                                                                                                                                                   |
> 
> ## Compatibility
> 
> This integration is tested with Kubernetes 1.21.x and currently supports the security posture assessment of:
> 
> 1. [Unmanaged/Vanilla Kubernetes clusters](https://kubernetes.io/)
> 2. [Amazon EKS clusters](https://aws.amazon.com/eks/)
> 
> This integration has not been tested on 
> 
> 1. Amazon EKS on AWS Outposts
> 
> This Integration does not currently support the security posture assessment of:
> 
> 1. Google GKE clusters
> 2. Azure AKS
> 3. Red Hat Openshift 
> 4. Amazon EKS with AWS Fargate nodes
> 
> ## Permissions 
> 
> This integration requires access to node files, node processes, and the Kubernetes api-server therefore it assumes the agent will be installed as a [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) with the proper [Roles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole) and [RoleBindings](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-and-clusterrolebinding) attached.
> 
> If deploying this integration on an [Amazon EKS cluster](https://docs.aws.amazon.com/eks/latest/userguide/what-is-eks.html), specific AWS permissions are required for the IAM user to make specific AWS API calls. To enable the integration to collect configuration metadata from all relevant resources/services, make sure these permissions are given:
> 
> - ecr:GetRegistryPolicy
> - eks:ListTagsForResource
> - elasticloadbalancing:DescribeTags
> - ecr-public:DescribeRegistries
> - ecr:DescribeRegistry
> - elasticloadbalancing:DescribeLoadBalancerPolicyTypes
> - ecr:ListImages
> - ecr-public:GetRepositoryPolicy
> - elasticloadbalancing:DescribeLoadBalancerAttributes
> - elasticloadbalancing:DescribeLoadBalancers
> - ecr-public:DescribeRepositories
> - eks:DescribeNodegroup
> - ecr:DescribeImages
> - elasticloadbalancing:DescribeLoadBalancerPolicies
> - ecr:DescribeRepositories
> - eks:DescribeCluster
> - eks:ListClusters
> - elasticloadbalancing:DescribeInstanceHealth
> - ecr:GetRepositoryPolicy
> 
> ## Leader election
> 
> To collect cluster level data (compared to node level information) the integration makes use of the [leader election](https://www.elastic.co/guide/en/fleet/master/kubernetes_leaderelection-provider.html) mechanism.
> This mechanism assures that the cluster level data is collected by only one of the agents running as a part of the DaemonSet and not by all of them.
> 
> Cluster level data example: List of the running pods.
> Node level data example: kubelet configuration.
> 
> ## Deployment
> 
> #### Deploy the Elastic agent
> 
> Just like every other integration, the KSPM integration requires an Elastic agent to be deployed. 
> 
> See agent [installation instructions](https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html).
> 
> Note, this integration can only be added to Elastic agents with versions 8.4 or higher.
>

**Comment by tinnytintin10** [comment]
@benironside I would love your feedback on the type and content of the readme above. This is what users will see when they first open the integration. You can propose changes directly in this draft PR if you have any: https://github.com/elastic/integrations/pull/3964

**Comment by tinnytintin10** [comment]
@orouz @kfirpeled for the documentation right next to the AWS credentials section, please use the text below:

> To run some of the rules in the benchmark, the integration will need elevated access. Follow [these instructions](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html) to create an IAM user with programmatic access that is associated with a policy with the set of permissions captured in the table below. You can either create a new policy or append these service permissions to an existing one- we recommend creating a new one.
> 
> 
> | Service                           | Permissions |
> | --------------------------------- | ----------- |
> | EKS                               | List, Read  |
> | Elastic Container Registry        | List, Read  |
> | Elastic Container Registry Public | List, Read  |
> | ELB                               | List, Read  |
> | ELB v2                            | Read        | 
>  
> If you choose not to provide credentials, only a subset of the benchmark rules will be evaluated against your cluster(s).

**Comment by DaveSys911** [comment]
@tinnytintin10 Go with the v1, ditch that table. Have the policy as a list so it's easier for the user to copy-paste it, or better in the format below with <click to copy>
<img width="836" alt="image" src="https://user-images.githubusercontent.com/16253938/183748601-8f1cfd65-1d52-4d22-b771-267e52de1ddb.png">

**Comment by tinnytintin10** [comment]
@orouz is it possible for you to implement what @DaveSys911 suggests above? thx

**Comment by orouz** [comment]
@tinnytintin10 - sure, let's open a task for it?

**Comment by ofiriro3** [comment]
Hi,

small update - soon @uri-weisman will merge a breaking change content to the integration repository(content related to 8.5).
Therefore, we will have to make sure we revert his commit before merging our content and reapply it after.

**Comment by eyalkraft** [comment]
@ofiriro3 We are waiting for your change as commented in https://github.com/elastic/security-team/issues/4443#issuecomment-1210444790

Can you please merge today so we won't be blocked?
