### ISSUE TITLE
[CI] Collect artifacts from CI builds

### ISSUE THREAD

**Issue by ycombinator** [elastic/integrations#380]
Artifacts include logs generated from any running containers, essentially anything that might be useful in debugging a CI failure.

**Comment by urso** [comment]
In case of an error let's also collect information stored in Elasticsearch like: index names, index mappings, and snapshots (which I can load into my local ES for investigation)

**Comment by mtojek** [comment]
I've introduced a similar (but simpler change here): https://github.com/elastic/package-storage/pull/759

Let me check what we can do.

**Comment by mtojek** [comment]
Ok, I tried with `filebeat()` in integrations, but I think it will more useful to do it in the `elastic-package`, let's say `elastic-package stack dump`?

There is no way to split logs into multiple files (one per container)?

**Comment by mtojek** [comment]
I guess I can close this one in favor of https://github.com/elastic/elastic-package/pull/534
