### ISSUE TITLE
[osquery] osquery doesn't work when Logstash output is used

### ISSUE THREAD

**Issue by defensivedepth** [elastic/integrations#3807]
Fleet + Elastic Agent 8.3.2, fresh install.

Using W10, macOS & Centos7 systems. Have two different outputs setup: 

![image](https://user-images.githubusercontent.com/954732/180433500-fc054bcd-7da3-45ac-8502-02c2efdc9935.png)

When I select the Elasticsearch output as default, osquery appears to work:

![image](https://user-images.githubusercontent.com/954732/180433577-34646cf0-22cd-4420-9aa4-7764a8dabbc8.png)

When I change the default output to Logstash, I get errors:

![image](https://user-images.githubusercontent.com/954732/180433679-1f10d568-3110-420e-b5e8-c90acb0091e7.png)

Same exact query (`select * from users`), same exact config. I have confirmed that the osquery config does exist both in the Kibana UI & in `elastic-agent inspect`:

![image](https://user-images.githubusercontent.com/954732/180433996-bf82c420-6b3b-461c-a82e-ede4c12f5dba.png)

**Comment by melissaburpo** [comment]
Hi @defensivedepth, thanks for raising this issue, and good find! We actually just released a fix for this, but it's possible it didn't quite make the cutoff to be included in the 8.3.2 release. @aleksmaus or @james-elastic can likely confirm, but I'd expect this to be included in 8.3.3 and 8.4.0.

Here's the PR for the fix: https://github.com/elastic/elastic-agent/pull/674
