### ISSUE TITLE
Create Cassandra Integration

### ISSUE THREAD

**Issue by andresrc** [elastic/integrations#381]
## Metrics
The integration should collect performance characteristics of a Cassandra cluster for the following:
- **System metrics**
Disk usage, CPU usage, Memory usage (JVM heap, non-heap, and total memory used by Cassandra).
- **GC metrics**
Total number of collections that have occurred (since JVM start), estimated cumulative collection elapsed time (since JVM start), last collection duration.
- **[Compaction](https://docs.datastax.com/en/cassandra-oss/3.x/cassandra/operations/opsCompactionMetrics.html)**
Compaction metrics for knowing when to add capacity to your cluster.
- **[Thread pool and read/write latency statistics](https://docs.datastax.com/en/cassandra-oss/3.x/cassandra/operations/opsThreadPoolStats.html)**
Increases in pending tasks on thread pool statistics can indicate when to add additional capacity.
- **[Table statistics](https://docs.datastax.com/en/cassandra-oss/3.x/cassandra/operations/opsTableStatistics.html)**
Provides a number of metrics that are important for monitoring performance trends.

More information can be found in [Cassandra monitoring docs](https://docs.datastax.com/en/cassandra-oss/3.x/cassandra/operations/opsMonitoring.html).
## Logs

Parse Cassandra system logs and ensure that the extracted fields are ECS compatible. See the example grok patterns [here](https://gist.github.com/ibspoof/917a888adb08a819eab7163b97e018cb).

# Package / Dataset creation or update checklist

This checklist is intended for Devs which create or update a package to make sure they are consistent.

## All Changes

* [ ] Change follows [development guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines)
* [ ] Supported versions of the subject being monitored are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
* [ ] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] At least a manual test with ES / Kibana / Agent has been performed.
* [ ] The required Kibana version is set to the lowest version used in the manual test.

### Dashboards

* [ ] Dashboards exists (if applicable)
* [ ] Screenshots of added / updated dashboards
* [ ] Datastream filters added to visualizations

## Log datasets

* [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
* [ ] Test log files exist for the grok patterns
* [ ] Generated output for at least 1 log file exists

## Metric datasets

This entry is currently _recommended_. It will be mandatory once we provide better support for it.

* [ ] Sample event (`sample_event.json`) exists

## New Packages

* [ ] Screenshot of the Fleet "Add Integration" Page.

**Comment by mtojek** [comment]
Referring to our conversation today about Jolokia endpoint.

I did a quick investigation on the Beats side and we have ActiveMQ, Tomcat and Kafka modules using Jolokia endpoint to scrap metrics. In all cases we don't differentiate level keys, but just assume the flat model:

See:

[Tomcat requests](https://github.com/elastic/beats/blob/23e4403ae093fcc8f7905345cad2c7ad256976d8/x-pack/metricbeat/module/tomcat/requests/manifest.yml)
[Tomcat threading](https://github.com/elastic/beats/blob/23e4403ae093fcc8f7905345cad2c7ad256976d8/x-pack/metricbeat/module/tomcat/threading/manifest.yml)
[Tomcat memory](https://github.com/elastic/beats/blob/23e4403ae093fcc8f7905345cad2c7ad256976d8/x-pack/metricbeat/module/tomcat/memory/manifest.yml)
[ActiveMQ broker](https://github.com/elastic/beats/blob/23e4403ae093fcc8f7905345cad2c7ad256976d8/x-pack/metricbeat/module/activemq/broker/manifest.yml)
[Kafka consumer](https://github.com/elastic/beats/blob/23e4403ae093fcc8f7905345cad2c7ad256976d8/metricbeat/module/kafka/consumer/manifest.yml)

In terms of Cassandra integration (`org.apache.cassandra.metrics:type=Table,keyspace=*,scope=*,name=*`) I guess it would be valuable to let the user define these levels using UI (default: verbose ones disabled), and consider keyspace, scope and name as standard fields (I hope they can be scraped using Jolokia input).

**Comment by masci** [comment]
Package is on `production` EPR, closing
