### ISSUE TITLE
Update CIS Kubernetes Benchmark integration screenshots 

### ISSUE THREAD

**Issue by ofiriro3** [elastic/integrations#3827]
We have recently added the EKS benchmark to the CIS Kubernetes Benchmark integration.

As a result of adding the new benchmark, we would like to update our integration screenshots with new screenshots displaying the new EKS integration as well as changes in our UI.

DOD:
- Adding screenshot to the integration
- Ask for a review from the product team.

**Comment by ofiriro3** [comment]
@tinnytintin10 Can you please elaborate on what screenshots we want to add here?

**Comment by tehilashn** [comment]
after talking to @tinnytintin10 - he said he will also do that part

**Comment by ofiriro3** [comment]
Hi,

small update - soon @uri-weisman will merge a breaking change content to the integration repository(content related to 8.5).
Therefore, we will have to make sure we revert his commit before merging our content and reapply it after.

**Comment by eyalkraft** [comment]
@ofiriro3 
I think it's closed by https://github.com/elastic/integrations/pull/3964

**Comment by ofiriro3** [comment]
@tinnytintin10 Can we close this issue?

**Comment by tinnytintin10** [comment]
completed as part of https://github.com/elastic/integrations/issues/3782
