### ISSUE TITLE
Google Workspace Audit Reports Integration - Support new data sources

### ISSUE THREAD

**Issue by rediasec** [elastic/integrations#3836]
At the moment, Google Workspace Audit Reports integration v1.4.0 supports the following data sources:
- Admin logs
- Drive logs
- Groups logs
- Login
- SAML
- User accounts _(here, check the following note from the link below: `The old Login and User accounts audit logs are now combined into User log events.`)_

But there are other data sources that could prove useful in the security detection & response processes. An example would be `Takeout log events` which can be a sign of unauthorized data access or even data exfiltration: https://support.google.com/a/answer/11339435?hl=en&ref_topic=7563358#zippy=%2Cdata-sources

**Comment by jamiehynds** [comment]
Closing in favour of https://github.com/elastic/integrations/issues/4722
