### ISSUE TITLE
infoblox: ECS mapping not perfect

### ISSUE THREAD

**Issue by WildDogOne** [elastic/integrations#3858]
I have noticed in [fields.yml](https://github.com/elastic/integrations/blob/d90c6db09fc52fbee91f986cc5b6e0c01661c751/packages/infoblox_nios/data_stream/log/fields/fields.yml) that the ECS field mapping for source.ip and destionation.ip are missing, hence the mapping in our environment defaulted to keyword.

I have also found a non ecs compliant field log.source.ip which is populated but also missing in the mapping

**Comment by WildDogOne** [comment]
@andrewkroh Example from the named module of nios:
```
<142>Jul 28 09:47:13 192.168.1.1 named[7172]: infoblox-responses: 28-Jul-2022 09:47:13.997 client 192.168.1.2#59062: UDP: query: 25.22.28.192.in-addr.arpa IN PTR response: NOERROR +A 25.22.28.192.in-addr.arpa. 68400 IN PTR contoso.com.;
```

I can deliver more of course, for example also of the dhcpd module

**Comment by andrewkroh** [comment]
I tested that event through the `logs-infoblox_nios.log-0.2.0` ingest pipeline and it did not produce `source.ip` or `destination.ip`. This is what was produced.

```json
{
  "@timestamp": "2022-07-28T09:47:13.997Z",
  "client": {
    "ip": "192.168.1.2",
    "port": 59062
  },
  "dns": {
    "answers": {
      "class": [
        "IN"
      ],
      "data": [
        "contoso.com."
      ],
      "name": [
        "25.22.28.192.in-addr.arpa."
      ],
      "ttl": [
        68400
      ],
      "type": [
        "PTR"
      ]
    },
    "header_flags": "+A",
    "question": {
      "class": "IN",
      "name": "25.22.28.192.in-addr.arpa",
      "type": "PTR"
    },
    "response_code": "NOERROR"
  },
  "ecs": {
    "version": "8.3.0"
  },
  "event": {
    "created": "2022-07-28T09:47:13.000Z",
    "original": "<142>Jul 28 09:47:13 192.168.1.1 named[7172]: infoblox-responses: 28-Jul-2022 09:47:13.997 client 192.168.1.2#59062: UDP: query: 25.22.28.192.in-addr.arpa IN PTR response: NOERROR +A 25.22.28.192.in-addr.arpa. 68400 IN PTR contoso.com.;"
  },
  "host": {
    "ip": "192.168.1.1"
  },
  "infoblox_nios": {
    "log": {
      "dns": {
        "category": "infoblox-responses"
      },
      "service_name": "named",
      "type": "DNS"
    }
  },
  "log": {
    "syslog": {
      "priority": 142
    }
  },
  "message": "infoblox-responses: 28-Jul-2022 09:47:13.997 client 192.168.1.2#59062: UDP: query: 25.22.28.192.in-addr.arpa IN PTR response: NOERROR +A 25.22.28.192.in-addr.arpa. 68400 IN PTR contoso.com.;",
  "network": {
    "transport": "udp"
  },
  "process": {
    "pid": 7172
  },
  "related": {
    "hosts": [
      "contoso.com.",
      "25.22.28.192.in-addr.arpa.",
      "25.22.28.192.in-addr.arpa"
    ],
    "ip": [
      "192.168.1.2",
      "192.168.1.1"
    ]
  },
  "tags": [
    "preserve_original_event"
  ]
}
```

-----

- What version of the infoblow_nios integration are you running?
- Did you add any custom processing to the integration configuration?
- Can you share the event JSON as seen in Kibana Discover?

**Comment by andrewkroh** [comment]
> I have also found a non ecs compliant field log.source.ip which is populated but also missing in the mapping

I see that the integration produces `log.source.address` but not `log.source.ip`. And `log.source.address` is in the mapping as `keyword`. https://github.com/elastic/integrations/blob/abf777f4b874d59d64dd4ca4178fa5fa8ff1c00b/packages/infoblox_nios/data_stream/log/fields/agent.yml#L187-L189

**Comment by WildDogOne** [comment]
Ahh yes! I can see this now, we are doing some post processing which copies client.ip to source.ip because the ECS shema is a bit confusing when it comes to that.
In this case I suppose we can just close this incident and I will patch local

**Comment by andrewkroh** [comment]
The recommended approach to handling customization is to add your own mappings into the "`@custom`" component template associated with this data stream. Fleet creates an empty component template like `logs-infoblox_nios.log@custom` for each integration. Anything you add there will persist across upgrade to the infoblox_nios package. Changes here won't affect existing indices, but the new ones going forward will get the correct mapping.

<img width="1413" alt="Screen Shot 2022-07-29 at 07 40 00" src="https://user-images.githubusercontent.com/4565752/181751385-dc019b49-a402-4060-acae-6ac78f9ce9ac.png">

**Comment by andrewkroh** [comment]
Relates: https://github.com/elastic/elasticsearch/issues/85692
