### ISSUE TITLE
[Fleet] ECS fields in packages are not included in `index.query.default_field` setting

### ISSUE THREAD

**Issue by joshdover** [elastic/integrations#3926]
**Kibana version**: 8.3.x

**Elasticsearch version**:

**Server OS version**:

**Browser version**:

**Browser OS version**:

**Original install method (e.g. download page, yum, from source, etc.)**:

**Description of the problem including expected versus actual behavior**:

The `message` field is missing from the `default_field` setting in the `logs-elastic_agent.cloudbeat` component template.

I noticed that it's present in the `logs-elastic_agent.filebeat` template, but not the cloudbeat one. They define this field is defined slightly differently in the package. The cloudbeat one uses an external reference to ECS whereas the filebeat one does not.

https://github.com/elastic/integrations/blob/cc68f3efc0f26d9fdbcf570dd03eac089f9f1e75/packages/elastic_agent/data_stream/filebeat_logs/fields/fields.yml#L1-L3

https://github.com/elastic/integrations/blob/cc68f3efc0f26d9fdbcf570dd03eac089f9f1e75/packages/elastic_agent/data_stream/cloudbeat_logs/fields/ecs.yml#L5

**Steps to reproduce**:
 1. Install elastic_agent package
 2. Check out the `index.query.default_field` setting on the `logs-elastic_agent.cloudbeat@package` component template
 3. See that `message` is missing

**Errors in browser console (if relevant)**:

**Provide logs and/or server output (if relevant)**:

**Describe the feature**:

**Comment by jen-huang** [comment]
@elastic/ecosystem Can you assist in finding out why the ECS fields are not expanded?
https://github.com/elastic/package-storage/blob/41b60270e74187fcd0e7c9ee4680083ec9eaa1f7/packages/elastic_agent/1.3.3/data_stream/cloudbeat_logs/fields/ecs.yml
https://github.com/elastic/package-storage/blob/41b60270e74187fcd0e7c9ee4680083ec9eaa1f7/packages/elastic_agent/1.3.3/data_stream/cloudbeat_metrics/fields/ecs.yml

The other ecs.yml files in elastic_agent package seem to have the same issue.

**Comment by mtojek** [comment]
The root cause is relatively simple. Whenever you're using [external definitions](https://github.com/elastic/package-storage/blob/41b60270e74187fcd0e7c9ee4680083ec9eaa1f7/packages/elastic_agent/1.3.3/data_stream/cloudbeat_logs/fields/ecs.yml), you need to declare the [dependency mapping](https://github.com/elastic/integrations/blob/main/packages/activemq/_dev/build/build.yml).
The `elastic_agent` package misses that one hence `external` property hasn't been resolved.

Passing the issue to the @elastic/elastic-agent-control-plane to fix it.

**Comment by andrewkroh** [comment]
@mtojek Should we make some part of `elastic-package check` require specifying the external dependency whenever `external` fields are referenced? Is there any reason we wouldn't want to add that check?

**Comment by mtojek** [comment]
Yes, we could add a new [semantic validation rule](https://github.com/elastic/package-spec/tree/main/code/go/internal/validator/semantic) to verify external fields.

**Comment by jen-huang** [comment]
cc @pierrehilbert
