### ISSUE TITLE
[TI_MISP] Issue with .cursor.timestamp

### ISSUE THREAD

**Issue by remynicol** [elastic/integrations#3937]
**Issue 1**
- The integration loads the first page composed of the first 10 misp events
- Then it sets the cursor timestamp at `.last_event.Event.timestamp`
- And when it requests the second page, it sets `body.timestamp` with the new `.cursor.timestamp` instead to keep the old one (or `now (parseDuration "-{{ .first_interval }}")` for the very first execution)

In consequence, misp returns no result in the second page and many of events will never be ingested (page 2, page 3, ...).

**Issue 2**
The value gives to `cursor.timestamp` : `'[[.last_event.Event.timestamp]]'` does not return the timestamp of the more recent event but the timestamp of the last injected event.

In consequence, if the last injected event is not the more recent event, the integration always asks to misp to send again the more recent ones and cannot inject them in elastic because they already exist. The cursor timestamp is not changed and it will be reproduced at each updates.

**Combination of issue 1 and 2**
As the cursor timestamp is not setted on the last event but on a random event of page 1, the integration sometimes achieves to load an non empty page 2, page 3, ...
It depends on the random event picked on each page (the last injected) and the gap in time between events in the misp database.

**Comment by drizzthacker** [comment]
Hi, Is there any workaround to fix it in the meanwhile? we're facing the same problem and randomly ingesting events

**Comment by remynicol** [comment]
Anything new for me

**Comment by drizzthacker** [comment]
Hi!, any news? Thanks!

**Comment by remynicol** [comment]
> @remynicol I verified the issues you described by observing the raw requests and responses with the request tracer feature and created issues for each finding:
> 
> * [[ti_misp] Incorrect initial timestamp format #6474](https://github.com/elastic/integrations/issues/6474)
> * [[ti_misp] Incorrect cursor timestamp because response not sorted #6477](https://github.com/elastic/integrations/issues/6477)
> * [[ti_misp] timestamp should not change while paginating #6479](https://github.com/elastic/integrations/issues/6479)

Great job of analysis, thanks !
