### ISSUE TITLE
Record missing units in _meta

### ISSUE THREAD

**Issue by exekias** [elastic/integrations#394]
We recently [added support for meta](https://github.com/elastic/package-spec/issues/42) information in `fields.yml`. This issue is minded to collect the missing unit values that we lack. Every time we have a metric with no matching value in the spec we should track it here.

Supported units are: `percent`, `byte`, `d`, `h`, `m`, `s`, `ms`, `micros`, `nanos`

Missing units:
- kilobytes
  - https://github.com/elastic/integrations/blob/9b939747c04ff6eb10c83b3b02acc2fc0da3a50a/packages/apache/data_stream/status/fields/fields.yml#L12
- bytes/s
  - https://github.com/elastic/integrations/blob/9b939747c04ff6eb10c83b3b02acc2fc0da3a50a/packages/system/data_stream/diskio/fields/fields.yml#L58

**Comment by costin** [comment]
A nit, any reason why `micros` is not `us` and nanos `ns`?

**Comment by exekias** [comment]
Hi @costin, we are following [Elasticsearch time units](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#time-units). Original discussion happened here: https://github.com/elastic/dev/issues/1350

**Comment by costin** [comment]
Thanks - the linked ticket was useful. I see @jpountz noticed the same issue with time units. I've raised a ticket for discussion within the Elasticsearch team (https://github.com/elastic/elasticsearch/issues/65432).

**Comment by exekias** [comment]
Thanks! I think that makes total sense, happy to update our meta if this goes in!

**Comment by jpountz** [comment]
> kilobytes

How many fields are storing kilobytes across our integrations, is it the only one? If yes my preference would go for keeping it without a unit for now, or converting it to a number of bytes on the agent side before shipping data to Elasticsearch.

> bytes/s

Is there a risk of an explosion of the number of units if we start tracking all possible combinations?

**Comment by exekias** [comment]
> How many fields are storing kilobytes across our integrations, is it the only one? If yes my preference would go for keeping it without a unit for now, or converting it to a number of bytes on the agent side before shipping data to Elasticsearch.

This is not the only one, just the first time we encountered it. We will keep adding meta to more integrations and updating this list. From a quick search I see that at least `redis`, `ceph`,  `apache`, `elasticsearch`, `tomcat`, `sophos` modules have fields reported in kilobytes.

I agree with waiting and see what to do about them, another option would be to update these integrations to report in bytes.

> Is there a risk of an explosion of the number of units if we start tracking all possible combinations?

Definitely yes, that's why I wanted to go for tracking the missing units first, then add support for the outstanding ones only. For this particular unit, it seems clear we will need support for metrics reporting instant rates like this one, as they are very commonly reported.
