### ISSUE TITLE
[Fleet]: `Elastic Synthetics` integration is installed by default on 8.4

### ISSUE THREAD

**Issue by simranvaseer-qasource** [elastic/integrations#3952]
**Kibana version**: 8.4.0 BC2 Kibana Cloud Environment.

**Host OS and Browser version**: All, All

**Build details:**
VERSION: 8.4.0 BC2.
BUILD: 55166
COMMIT: 9e9e0d6a685cbc2858a85a357f93dcb76259fdee

**Preconditions:**
- 8.4.0 BC2 Kibana Cloud Environment should be available.

**Steps to reproduce:**
1. Login to 8.4 BC2 Kibana environment.
2. Navigate to Installed integrations.
3. Observe `Elastic Synthetics` integration is installed by default.

**Expected Result:**
- `Elastic Synthetics` integration should not installed by default on 8.4

**Screenshot:**
![image](https://user-images.githubusercontent.com/102019374/182774183-6bbc262f-1e71-459e-9ea9-2512df7d073d.png)

**Comment by simranvaseer-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by juliaElastic** [comment]
I traced where the synthetics install is coming from, and found that it comes from `synthetics` plugin setup code.
I found that it was added likely in this change in 8.4: https://github.com/elastic/kibana/pull/135782
I suppose it is expected then? @joshdover @dominiqueclarke @kpollich

**Comment by kpollich** [comment]
Seems like this is indeed intentional, but let's wait for some confirmation from @elastic/uptime to close this out

**Comment by andrewvc** [comment]
Yes, this is intentional. I'm not sure why it was reported as a bug, it's a requirement for our product.

**Comment by kpollich** [comment]
Closing per above clarification from the Synthetics folks. Thanks all.

**Comment by simranvaseer-qasource** [comment]
Hi Team
Thank you for the confirmation. 
As per feedback we have updated below test cases .

- [C165601](https://elastic.testrail.io/index.php?/cases/view/165601&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=34918)
- [C76942](https://elastic.testrail.io/index.php?/cases/view/76942&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=30797)

Thanks

**Comment by joshdover** [comment]
@andrewvc We've had user complaints about having assets installed that aren't in use by the customer. Is this package installed on every cluster or only when the user has started using synthetics?

**Comment by andrewvc** [comment]
CC @dominiqueclarke , I believe that's the case, but I don't understand the concern. The assets involved are just the package / mappings. What is the practical concern here?

**Comment by andrewvc** [comment]
I'll also add that heartbeat, even when run as a standalone instance, expects the synthetics mappings / streams to be in place as of 8.4.0, so removing it would be tricky.
