### ISSUE TITLE
Migrate MySQL Enterprise Audit log

### ISSUE THREAD

**Issue by P1llus** [elastic/integrations#397]
This issue has been created to ensure that the merge of the OSS and the X-Pack mysql module happens.
OSS:
https://github.com/elastic/beats/tree/master/filebeat/module/mysql
X-Pack:
https://github.com/elastic/beats/pull/22273

## All Changes

* [ ] Change follows [development guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines)
* [ ] Supported versions of the subject being monitored are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
* [ ] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] At least a manual test with ES / Kibana / Agent has been performed.
* [ ] The required Kibana version is set to the lowest version used in the manual test.

## Log datasets

* [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
* [ ] Test log files exist for the grok patterns
* [ ] Generated output for at least 1 log file exists

**Comment by andresrc** [comment]
This should be coordinated with #365

**Comment by andrewkroh** [comment]
The [myqsl package](https://github.com/elastic/integrations/tree/master/packages/mysql/data_stream) has been created so for this we need to migrate the Filebeat audit log data stream.
