### ISSUE TITLE
[ti_abusech] Remove event.original from "query.default_fields"

### ISSUE THREAD

**Issue by smnschneider** [elastic/integrations#3976]
Remove field `event.original` from index setting `index.query.default_field` as this field is by design not searchable. (https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-original)
This results into errors when using the search bar in Kibana.
This should also be checked for other integrations as this could be a general issue.

The following line has to be added:

`default_field: false`

To the following field configurations:

url:
https://github.com/elastic/integrations/blob/9fc4428cf23520a7255da0c3cc541556e1e5f2f3/packages/ti_abusech/data_stream/url/fields/ecs.yml#L19

malwarebazaar:
https://github.com/elastic/integrations/blob/9fc4428cf23520a7255da0c3cc541556e1e5f2f3/packages/ti_abusech/data_stream/malwarebazaar/fields/ecs.yml#L19

malware:
https://github.com/elastic/integrations/blob/9fc4428cf23520a7255da0c3cc541556e1e5f2f3/packages/ti_abusech/data_stream/malware/fields/ecs.yml#L21

**Comment by smnschneider** [comment]
Additional information: This lets also fail the detection rule `Threat Intel Indicator Match`

**Comment by joshdover** [comment]
@jsoriano could the `default_field: false` be the default behavior for `event.original`? Is that possible to do from the spec / definition of external fields?

**Comment by jsoriano** [comment]
> @jsoriano could the `default_field: false` be the default behavior for `event.original`? Is that possible to do from the spec / definition of external fields?

We can add a note about this behaviour in the spec, but this would need to be implemented in Fleet for fields that don't have `default_field` on its definitions.

I guess it could make sense if Fleet removes from the default fields any field that has `index: false` and `doc_values: false`. We could do this instead of adding an exception for the `event.original` field.

**Comment by rsdrakh** [comment]
I have found this issue actually in a lot of other integrations on customer site:
system.system
system.application 
system.security
cisco_*
auditd.log
iis.access|error
sophos.utm
system.auth
microsoft_dhcp

This seems to be a general issue.

**Comment by jsoriano** [comment]
> I guess it could make sense if Fleet removes from the default fields any field that has `index: false` and `doc_values: false`. We could do this instead of adding an exception for the `event.original` field.

> This seems to be a general issue. So I think the "remove all fields with index:false and doc_values:false from default_fields" is the best approach.

@kpollich should we put this in our plate?

**Comment by kpollich** [comment]
@jsoriano Yes I think this makes sense. Could you file a Fleet issue for this?

**Comment by jsoriano** [comment]
Closing this in favor of https://github.com/elastic/kibana/issues/143936, thanks!
