### ISSUE TITLE
Promote EKS integration to version 0.25

### ISSUE THREAD

**Issue by ofiriro3** [elastic/integrations#3981]
**Motivation**
As we merged our EKS integration to the integration repository, we would like to promote the integration, making it available for users of the Elastic 8.4+ stack.
We now want to make it available for both our staging/dev environments.

**Definition of done**
- [ ] Promote our integration package to SNAPSHOT
- [x] Promote our integration package to staging
- [x] Promote our integration package to production

**Useful links**
- https://github.com/elastic/security-team/blob/main/docs/cloud-security-posture-team/publish-package.mdx

**Related tasks**
- https://github.com/elastic/integrations/issues/3698

**Comment by oren-zohar** [comment]
Done - https://beats-ci.elastic.co/job/Ingest-manager/job/release-distribution/663/
