### ISSUE TITLE
[Nginx]:  `Ignore events older than` field not available for Nginx logs dataset.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#3991]
**Kibana version:**  8.4.0 BC3 Kibana cloud environment

**Host OS:**  All

**Build details:**
VERSION: 8.4.0 BC3
BUILD: 55281
COMMIT: e42c547d7ab545472fd978383c2c43fa203a5b06

**Preconditions:**
1. 8.4.0 BC3 Kibana cloud environment should be available.
2. Policy should be created using Nginx integration.

**Integration Version:**
Nginx v1.4.1
(Same version is available on latest 8.4 Snapshot)

**Steps to reproduce:**
1. Navigate to Fleet>Agents Policies tab.
2. Click Edit Nginx integration and observe Nginx logs dataset>Advanced.
3. Observe ` Ignore events older than` field not available for Nginx datasets.

**Related Feature:**
https://github.com/elastic/integrations/pull/3691

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/184329773-74eafc4c-b971-421c-8bb9-7ffabea5aed6.mp4

**Expected Result:**
`Ignore events older than` field should be available for Nginx logs dataset.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by amolnater-qasource** [comment]
FYI @fearful-symmetry

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by fearful-symmetry** [comment]
Not sure why I'm being pinged here?

**Comment by amolnater-qasource** [comment]
Hi @fearful-symmetry 

As we have seen that you been working on the similar PR at https://github.com/elastic/integrations/pull/3691

So while going through that ticket, we did some testing on 8.4 BC3 and found the issue reported above.

Considering the above fact we have mentioned you in this ticket.

Please let us know in case we need to assign different person or team.

Thanks

**Comment by fearful-symmetry** [comment]
So, I only made one change to nginx because I had time, but generally it's not my area. However, it looks like the the change with `ignore_older` is still in snapshot, so I have a promotion PR here: https://github.com/elastic/package-storage/pull/5344

**Comment by amolnater-qasource** [comment]
Hi @fearful-symmetry 

Thank you for the update.
We will revalidate this issue once the attached PR is merged.

Thanks!

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated testing `Ignore events older than` feature on latest 8.4.1 BC2 and observed Nginx version is still `v1.4.1`.
- `v1.5.0` Nginx version is still not available.

**Build details:**
BUILD: 55434
COMMIT: 415cecc1c67ed775c4d9f6592fe5acc35dc9dce5

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/187377310-5cff2670-7390-4d5a-953b-cf45757fb492.JPG)

Thanks

**Comment by jlind23** [comment]
@amolnater-qasource because @fearful-symmetry promoted it from snapshot to staging but i am sure it needs to be promoted to production in order to be available on BC.

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this on latest 8.4.1 released kibana cloud build and observed latest version Nginx integration `v1.5.0` still not available.

**Build details:**
BUILD: 55434
COMMIT: 415cecc1c67ed775c4d9f6592fe5acc35dc9dce5

**Screenshot:**
![7](https://user-images.githubusercontent.com/77374876/188813197-cca86ce1-5641-42a3-ba77-2fc252950bc0.JPG)

Thanks

**Comment by jlind23** [comment]
@amolnater-qasource this was promoted from snapshot to staging only: https://github.com/elastic/package-storage/pull/5344

@fearful-symmetry can you promote it to production please?
