### ISSUE TITLE
Issue in Grok processor for Message ID 113039 logs-cisco_asa.log-2.5.2

### ISSUE THREAD

**Issue by WildDogOne** [elastic/integrations#3992]
Hello Everyone,
I don't know if this is the proper way to open issues for small adjustments like this.
Is there an easier or faster way to do this?
I would like to help remediate things quickly,  I could also make pull requests if that is OK

I have noticed that the Grok Filter for Message [ID 113039 in Cisco ASA Logs](https://github.com/elastic/integrations/blob/d812de3cbac085e39a1828c49a5cd81ebd6be369/packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L364) doesn't seem to work always.

We get the following log linese:
`Group <staff-policy> User <user@domain.com> IP <192.168.1.1> AnyConnect parent session started`

So I would propose to add this Grok:
```
Group %{NOTSPACE:source.user.group.name} User <%{USER:source.user.name}@%{USER:source.user.domain}> IP <%{IP:source.address}>
```

**Comment by efd6** [comment]
As of v2.7.1 this parses as
```
{
    "@timestamp": "2022-07-15T12:18:51.000Z",
    "cisco": {
        "asa": {}
    },
    "ecs": {
        "version": "8.4.0"
    },
    "event": {
        "action": "client-vpn-connected",
        "category": [
            "network",
            "session"
        ],
        "code": "113039",
        "kind": "event",
        "original": "Jul 15 12:18:51 81.2.69.192 %ASA-6-113039: Group \u003cstaff-policy\u003e User \u003cuser@domain.com\u003e IP \u003c192.168.1.1\u003e AnyConnect parent session started",
        "severity": 6,
        "type": [
            "connection",
            "start"
        ]
    },
    "host": {
        "hostname": "81.2.69.192"
    },
    "log": {
        "level": "informational"
    },
    "observer": {
        "hostname": "81.2.69.192",
        "product": "asa",
        "type": "firewall",
        "vendor": "Cisco"
    },
    "related": {
        "hosts": [
            "81.2.69.192",
            "domain.com"
        ],
        "ip": [
            "192.168.1.1"
        ],
        "user": [
            "user"
        ]
    },
    "source": {
        "address": "192.168.1.1",
        "ip": "192.168.1.1",
        "user": {
            "domain": "domain.com",
            "group": {
                "name": "staff-policy"
            },
            "name": "user"
        }
    },
    "tags": [
        "preserve_original_event"
    ]
}
```
What version are you currently using?

**Comment by WildDogOne** [comment]
We are on V2.5.2 and I also don't get an update prompt.
I did however see that there is a new grok rule in the repository, tried using that and it did not fix the issue for me, hence I made a pull request.

But what interests me more right now is the fact that we are lagging behind in integration versions even though we are on ELK 8.3.3

**Comment by efd6** [comment]
@WildDogOne v2.7.1 is not in production yet, it is [still in snapshot](https://github.com/elastic/package-storage/tree/snapshot/packages/cisco_asa).

The log line that you have in the issue description it correctly processed by the v2.7.1 grok processor, so if you are still having issues, would you please post some more examples, or check that what is there reflects the lines you are having issues with.

**Comment by WildDogOne** [comment]
@efd6 OK perfect, in that case I will just wait till it goes GA, test again and open a new issue / pull request if necessary.
Thanks for your assistance.
