### ISSUE TITLE
dev tool: update package-storage with integrations 

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#40]
The `dev/update-package-storage` will simplify pushing next changes to the `package-storage`. 

Requirements:
1. Fork the `package-storage` repository.
2. Set the upstream to the https://github.com/elastic/package-storage.

Here are the next steps:
1. Fetch upstream.
2. Checkout the Git master branch.
3. Rebase with upstream.
4. Create a branch from master: `sync-integrations-<timestamp>`
5. Copy integrations files to right folders (preserve versions).
6. Commit all changes.
7. Push to the `package-storage` repository.
8. Open a pull-request with the `package-storage` for every single package.

**Comment by ruflin** [comment]
Looking forward to this tool. It would be nice to have 1 PR per package on the package-storage side.

**Comment by exekias** [comment]
At some point before packages are sent to the package-storage it would be interesting to bump versions and tag the package on this repo. This adds traceability and allows us to go back to a released package.

**Comment by jonathan-buttner** [comment]
I think it would also be useful to have some hash of the contents of the package that is released. The hash could be checked in the PR to the package-storage repo. This would guarantee that the package that is tagged/versioned in this repo matches with the package that is released in the package-storage repo.

**Comment by mtojek** [comment]
The current implementation (PR soon) compares changes in the version control system and if there are any updates that should be released. This model covers requirements of integrations, IMHO no need to introduce tags.
I'm happy to discuss the endpoint team use-case, let's first see how much does the tool satisfy your needs.

**Comment by ph** [comment]
> I think it would also be useful to have some hash of the contents of the package that is released. The hash could be checked in the PR to the package-storage repo. This would guarantee that the package that is tagged/versioned in this repo matches with the package that is released in the package-storage repo.

Would adding commit hash do the trick?

**Comment by mtojek** [comment]
Next followups:

https://github.com/elastic/integrations/issues/46
https://github.com/elastic/integrations/issues/45

**Comment by jonathan-buttner** [comment]
> > I think it would also be useful to have some hash of the contents of the package that is released. The hash could be checked in the PR to the package-storage repo. This would guarantee that the package that is tagged/versioned in this repo matches with the package that is released in the package-storage repo.
> 
> Would adding commit hash do the trick?

hmm I don't think a commit hash would work. The hash would ideally protect against an unlikely edge case where if say the copy command or however the PR is being created against the package storage repo failed halfway through the CI for the package storage repo could calculate some hash across the entire contents of the files in the PR and verify it against a file with a hash or something to make sure the contents of the PR lines up with what it's supposed to have. I think the commit hash is going to be different in the PR.

**Comment by mtojek** [comment]
@jonathan-buttner 

Once the PR https://github.com/elastic/integrations/pull/59 is merged, you can try to adopt the tool and see if you can release the endpoint. I'm happy to adjust the CLI to meet your expectations.

**Comment by jonathan-buttner** [comment]
Thanks @mtojek we're currently using https://github.com/github/hub to open the pull request against package-storage. I'll take a look at the CLI tool.

**Comment by mtojek** [comment]
Resolving
