### ISSUE TITLE
[Fleet]: All added integrations didn't upgrade to latest version when checkbox is enabled-'Upgrade Integration policies' while upgrading integration

### ISSUE THREAD

**Issue by simranvaseer-qasource** [elastic/integrations#4003]
**Kibana version:**  8.4 BC4 Kibana cloud environment 

**Host OS and Browser version:** All, All 

**Build details:** 

``` 
VERSION: 8.4.0 BC4
BUILD: 55323
COMMIT: 0011c16d2b4b19b169bd801766cb4db8792a2adc
ARTIFACT LINK : https://staging.elastic.co/8.4.0-61dcfeb1/summary-8.4.0.html
```

**Preconditions:**
1. 8.4 BC4 Kibana cloud environment should be available.
2. Lower version integration should be added to the policy.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Integration tab.
3. Add lower version integration to 3 or 4 policies.
4. `Upgrade integration policies` checkbox should be enabled
5. Click on 'Upgrade to latest version'.
6. Observe all added integration didn't upgrade to latest version.

**Expected Result:**
-  All added integrations should be upgrade to latest version when checkbox is enabled-'Upgrade Integration policies' while upgrading integration

**Screen Recording:**

https://user-images.githubusercontent.com/102019374/184844241-604003be-d606-4d3a-8a84-f0e497185a82.mp4

**Note:**
Integration didn't upgrade on policies details page also.

**Screenshots:**
![image](https://user-images.githubusercontent.com/102019374/184845887-85359290-f42b-43ef-b5b3-ef9545a2f12e.png)

![image](https://user-images.githubusercontent.com/102019374/184845750-1f2c45ab-fcee-497e-a7a4-0a70e40b1ad9.png)

**Comment by dikshachauhan-qasource** [comment]
Secondary review is done

**Comment by simranvaseer-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.5 BC6 kibana cloud environment and found it **fixed** now.

- All added integrations are upgraded to latest version when checkbox is enabled-'Upgrade Integration policies' while upgrading integration.

```
Build Details:
Build: 57022
Commit: 0b06c1437f38a9eb9a4273003d8d2ce2c8905189
**Screen Recording:**

https://user-images.githubusercontent.com/102019374/196391566-776470ac-2cd1-42ae-8c6c-4df451983093.mp4

Hence, marking this issue as QA:Validated.
Thanks
