### ISSUE TITLE
[Hashicorp Vault] Support for Vault v1.11

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#4035]
Our integration currently supports up to Vault v1.8 (as that's what we test against). Vault is now up to v1.11 and after some discussions with Hashicorp and Vault users, we should aim to support up to v1.11

There are no significant changes to Vault logging between 1.8 and 1.11, so it will likely just require a smoke test. Assuming the test with our integration is successful, we'll need to ensure [our documentation](https://docs.elastic.co/integrations/hashicorp_vault) is updated to reflect support for versions up to 1.11.

**Comment by andrewkroh** [comment]
PR: https://github.com/elastic/integrations/pull/4036
