### ISSUE TITLE
[Sysmon] Full Event Coverage

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#4038]
Our Sysmon integration does not include mappings for some event types introduced since Sysmon v13.10. The current list of events we map to `event.category` and `event.type` can be viewed within the pipeline [here](https://github.com/elastic/integrations/blob/main/packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml). Useful blog with sample use cases for each event available [here](https://www.blackhillsinfosec.com/a-sysmon-event-id-breakdown/). 

In order to fully support all Sysmon events, the following events should be supported:

- EventID 8: [CreateRemoteThread](https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-8-createremotethread) | [Sample Event](https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventid=90008)
- EventID 9: [RawAccessRead](https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-9-rawaccessread) | [Sample Event](https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventid=90009)
- EventID 19: [WmiEventFilter activity detected](https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-19-wmievent-wmieventfilter-activity-detected) | [Sample Event](https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventid=90019)
- EventID 20: [WmiEventConsumer activity detected](https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-20-wmievent-wmieventconsumer-activity-detected) | [Sample Event](https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventid=90020)
- EventID 27: [FileBlockExecutable](https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-27-fileblockexecutable)
- EventID 28: [FileBlockShredding](https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-28-fileblockshredding)
- EventID 255: [Error](https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-28-fileblockshredding)

This issue will track our progress on adding support for this new event type to our Sysmon integration.

**Comment by jamiehynds** [comment]
When adding support for Sysmon v14, we need to look at supporting v13.3 too: https://github.com/elastic/integrations/issues/2043

**Comment by narph** [comment]
https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon
