### ISSUE TITLE
Crowdstrike FDR Mapping Enhancement

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#4040]
**related.ip**
Our FDR pipeline currently adds `observer.ip`, `source.ip` and `destination.ip` to `related.hosts` but customer feedback suggests, it should be added be added to [`related.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-related.html#field-related-ip) field instead of `related.hosts`.
https://github.com/elastic/integrations/blob/main/packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml#L1342
https://github.com/elastic/integrations/blob/main/packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml#L1834
https://github.com/elastic/integrations/blob/main/packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml#L1839

**crowdstrike.FirstSeen**
Customer has suggested this field is mapped to `@timestamp`. What field do we currently rely on to generate the timestamp? We do have a `threat.indicator.first_seen` but not a good fit here, as it relates more to IOC's.

**Comment by jamiehynds** [comment]
Currently blocked by https://github.com/elastic/kibana/issues/134321

**Comment by efd6** [comment]
Regarding the timestamp, the logic is to take the first available value from the FDR data in the following list:

1. UTCTimestamp
2. timestamp
3. CreationTimeStamp
4. AgentLocalTime
5. _time

This seems fairly sensible to me, and there will always be an argument that it should be different, no matter what we have, so I'm not sure it should be changed.
