### ISSUE TITLE
AWS Security Hub #3589: SecurityHub Dashboard Overview and other dashboard improvements

### ISSUE THREAD

**Issue by Udayel** [elastic/integrations#4041]
As we discussed in the demo call please consider adding the following resources to the AWS Security Hub overview dashboard:

- Findings by resource type
- Findings by Types
- Top 10 security hub findings
- Top 10 critical findings by severity
- Critical findings count comparison in last week
- Counts records by Severity
- Counts of records by service name

**Comment by felix-lessoer** [comment]
Started to improve the Security Hub Dashboard. Any things you like to add? 
Working on fixing the last issues.

![SecurityHub Summary - Elastic](https://user-images.githubusercontent.com/35069463/197767104-59d75422-f93b-4afe-bda4-01421b63da49.png)

**Comment by jamiehynds** [comment]
Thanks @felix-lessoer - once you finalised the dashboards would you minding submitting a PR and we can work through the review process? @Udayel any other suggestions you'd suggest?

**Comment by felix-lessoer** [comment]
Sure @jamiehynds 

I have updates for many of the AWS dashboards in place

**Comment by Udayel** [comment]
Thank you @felix-lessoer. @jamiehynds Looks good to me. But some of the security findings raw events and geo map data still not showing in the default dashboard.I really appreciate if someone can look into that asap.

**Comment by felix-lessoer** [comment]
The data that I am able to produce does not include geo information. 
Any ideas how to trigger it?

Also: Any doc that is of type `aws.securityhub_insights` does not include any information. The event.original field is always `{"Insights":[]}` . The Security Hub Console in AWS shows data. I think thats a bug in the Beat / Agent Integration.

**Comment by jamiehynds** [comment]
@vinit-elastic can you confirm if the lack of data within `Insights` is an issue on our side or on Security Hub?

**Comment by vinit-elastic** [comment]
Hey @felix-lessoer - can you please increase the time range ( initial_interval ) of the connector and re-run it? I suspect the reason you are getting `Insights: []` could be that there are no new insights.

**Comment by felix-lessoer** [comment]
@vinit-elastic The **insights** integration only has `interval `but not `initial interval`. 
`Initial interval` is only available for **findings**.

**Comment by vinit-elastic** [comment]
Ahh, my bad. You are right. For insights you'll have to generate the logs on the fly, with connector running.

**Comment by felix-lessoer** [comment]
Is it enough to click on "Create insight" in the AWS console?

**Comment by vinit-elastic** [comment]
Hey @felix-lessoer @Udayel - I have updated the dashboard on one of Felix's instances. Let me know if anything else is required. 

![e9ebabfd-52e0-4489-8c1f-4fdef58bf05e](https://user-images.githubusercontent.com/89848047/200040459-67cc227a-d262-4f9f-8395-826195760a6c.png)
