### ISSUE TITLE
[zscaler_zia] Regenerating sample event files yields invalid sample events

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/integrations#4044]
I discovered this while working on a separate issue, but when regenerating sample event files, the events are filled with invalid/nonsense data. Regenerating files is done by running the system tests with the generate flag.

Here are some examples. This was performed on `main` and on a fresh stack.

```diff
# packages/zscaler_zia/data_stream/dns/sample_event.json
@@ -13,43 +13,25 @@
         "type": "logs"
     },
     "destination": {
-        "as": {
-            "number": 29518,
-            "organization": {
-                "name": "Bredband2 AB"
-            }
-        },
-        "geo": {
-            "city_name": "Linköping",
-            "continent_name": "Europe",
-            "country_iso_code": "SE",
-            "country_name": "Sweden",
-            "location": {
-                "lat": 58.4167,
-                "lon": 15.6167
-            },
-            "region_iso_code": "SE-E",
-            "region_name": "Östergötland County"
-        },
-        "ip": "89.160.20.156",
-        "port": 8080
+        "ip": "0.0.0.0",
+        "port": 0
     },
     "dns": {
         "answers": {
-            "name": "Some response string"
+            "name": "NotFound"
         },
         "question": {
-            "name": "example.com",
-            "type": "Some type"
+            "name": "Unknown",
+            "type": "NotFound"
         }
     },
     "zscaler_zia": {
         "dns": {
             "department": "Unknown",
             "dom": {
-                "category": "Professional Services"
+                "category": "Other"
             },
             "duration": {
-                "milliseconds": 123456
+                "milliseconds": 34000
             },
-            "hostname": "Machine9000",
-            "location": "TestLoc DB",
+            "hostname": "NA",
+            "location": "Unknown",
             "request": {
-                "action": "REQ_ALLOW",
+                "action": "None",
                 "rule": {
-                    "label": "Access Blocked"
+                    "label": "None"
                 }
             },
             "response": {
-                "action": "Some Response Action",
+                "action": "None",
                 "rule": {
                     "label": "None"
                 }
```

To me, this seems like the test files were handcrafted with data. This only works for integrations that lack system tests. For those that do,  and for long-term maintainability, we really should be populating the sample event automatically. This also raises the question of the quality of these tests. If we are getting a bunch of `unknown` and `not found` values out of the test case, that to me implies that the test case itself is faulty, or there's a problem in the integration itself.

**Comment by jamiehynds** [comment]
@vinit-elastic do you know if these events were handcrafted? Do you still have live data from the Zscaler instance we used during development?

**Comment by vinit-elastic** [comment]
Hey, 
In the Zscaler ZIA integration, there are 2 input types (TCP and HTTP-Endpoint). And we have used the actual events that we received from the Zscaler instance for the system test. Moreover, one of the reasons why it's generating new file could be because it is running system tests for HTTP-Endpoint input type for this particular test. When we ran the test to generate the sample-event.json it ran for TCP input.

**Comment by narph** [comment]
@vinit-chauhan , it's been a while, can we close this issue?

**Comment by vinit-chauhan** [comment]
Hey @narph - As far as I remember, this issue was resolved. 

However, I'd suggest getting it confirmed by @piyush-elastic once, before closing it. 

Thanks!

**Comment by piyush-elastic** [comment]
Hey @narph - feel free to close this issue. Thanks @vinit-chauhan.
