### ISSUE TITLE
[kibana] Verify logs mappings and pipelines

### ISSUE THREAD

**Issue by klacabane** [elastic/integrations#4047]
### Summary

Let's verify that every kibana log types is properly ingested when running the kibana package. The package should only support log formats from versions >= 8.0.

#### Note
- if a log type is failing to ingest, we should look at the corresponding [filebeat implementation](https://github.com/elastic/beats/tree/main/filebeat/module/kibana) and verify both pipelines and mappings are aligned.
- if the logs are generated with an ecs format, we should look at simplifying the pipeline like the [platform-observability package](https://github.com/elastic/integrations/blob/main/packages/platform_observability/data_stream/kibana_audit/elasticsearch/ingest_pipeline/ecs-logs-pipeline.yml)

**Comment by crespocarlos** [comment]
Both [Audit](https://www.elastic.co/guide/en/kibana/current/xpack-security-audit-logging.html#xpack-security-ecs-audit-schema) and [Kibana Server](https://www.elastic.co/guide/en/kibana/master/kibana-troubleshooting-kibana-server-logs.html) logs are in ECS format. I'll simplify the pipeline
