### ISSUE TITLE
cisco_ise tacacs pipeline missing error handling

### ISSUE THREAD

**Issue by Bernhard-Fluehmann** [elastic/integrations#4076]
I am investigating a problem of processing cisco_ise logs. Some of the logs are rejected with the following message:

`"error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [AVPair] of type [keyword] in document with id 'YWm404IBFzFBE6qKgb3x'. Preview of field's value: '{elapsed_time=0, task_id=4f4ad6}'", "caused_by"=>{"type"=>"illegal_state_exception", "reason"=>"Can't get text on a START_OBJECT at 1:3163"}}}}}`

From what I see, the AVPair field should be removed at the end of the pipeline (remove processor). One way this could happen is when a previous processor fails. This may be the case, since not all processors have the igonre_failure flag set and there are no on_failure processors set in the pipeline. I have fixed this temporarily on my cluster by adding a on_failure processor to remove the temporary stuff and it seems to help. Another solution would be to  set ignore_failure flags on all of the previous processors, but I don't know the integration well enough to evaluate the side effects. Overall, rejecting logs in case of parsing errors should be avoided if ever possible, since in case of UDP they will just get lost in this case.

**Comment by efd6** [comment]
@Bernhard-Fluehmann Are you able to provide a failing example or two to see exactly how this is failing?

**Comment by efd6** [comment]
@Bernhard-Fluehmann gentle ping.

**Comment by Bernhard-Fluehmann** [comment]
@efd6 I will try to find an example.
