### ISSUE TITLE
Cisco Umbrella Proxylogs integration fields order is different from Cisco documentation.

### ISSUE THREAD

**Issue by leandrojmp** [elastic/integrations#4078]
Hello,

We are starting to migrate our Logstash pipelines to use the Elastic Agent integrations and the first step is to adapt our Logstash pipelines to emit the same fields that the Elastic Agent integration emits in the output event.

Looking into the integration for the Cisco Umbrella Proxylogs, we saw that the order of the fields in the `csv` processor is different from the one in the documentation and the one we have in our logs.

The order of the fields is described in the [cisco documentation](https://docs.umbrella.com/deployment-umbrella/docs/log-formats-and-versioning#section-proxy-logs) page, considering just the first 6 fields, we have this order:

```
<timestamp>,<policy identity label>,<internal client ip>,<external client ip>,<destination ip>,<content type>
```
Those fields are:
> Timestamp—The timestamp of the request transaction in UTC (2015-01-16 17:48:41). 
 Policy Identity Label—The identity that made the request.
 Internal Client IP—The internal IP address of the computer making the request.
 External Client IP—The egress IP address of the network where the request originated.
 Destination IP—The destination IP address of the request.
 Content Type—The type of web content, typically text/html.

Our logs match this order:

```
2022-08-26 13:59:46","redacted","redacted-ip-address","redacted-ip-address","redacted-ip-address","image/webp"
```

The integration parses this csv log using this [csv processor](https://github.com/elastic/integrations/blob/1fbdbd141fb164861b6246a868302bea9d77516f/packages/cisco_umbrella/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L70-L105), where the first 6 fields are:

```
cisco.umbrella._tmp.time, cisco.umbrella.computer_name, cisco.umbrella.identities, source.address, source.nat.ip, destination.address
```

The parser in the integration does not match the order of the documentation from Cisco, for example the 5th field in the csv document is the `destination.ip`, but the Integration would save it as the `source.nat.ip`.

Are we missing something?

**Comment by legoguy1000** [comment]
Something must have changed on their end as I built this off their docs and the sample events are directly from that same page.

**Comment by leandrojmp** [comment]
@legoguy1000 I would say that it is very likely, when I was building our logstash parser the documentation does not even had the order of the fields, just the names.

I think that every time Cisco changes the log version to add a new field it could break the integration since they can add the field anywhere in the CSV document.

If it helps, this is the fields names and order that we are using in our  `csv` filter in the logstash pipeline:

```
"timestamp"
"[source][user][name]"
"[source][ip]"
"[source][nat][ip]"
"[destination][ip]"
"[cisco][umbrella][content_type]"
"[cisco][umbrella][verdict]"
"[url][full]"
"[http][request][referrer]"
"[user_agent][original]"
"[http][response][status_code]"
"[http][request][bytes]"
"[http][response][bytes]"
"[http][response][body][bytes]"
"[cisco][umbrella][sha_sha256]"
"[cisco][umbrella][categories]"
"[cisco][umbrella][av_detections]"
"[cisco][umbrella][puas]"
"[cisco][umbrella][amp][disposition]"
"[cisco][umbrella][amp][malware_name]"
"[cisco][umbrella][amp][score]"
"[cisco][umbrella][identity_type]"
"[cisco][umbrella][blocked_categories]"
"[cisco][umbrella][identities]"
"[cisco][umbrella][identity_types]"
"[http][request][method]"
"[cisco][umbrella][dlp_status]"
"[cisco][umbrella][certificate_errors]"
"[cisco][umbrella][destination_lists_ids]"
"[cisco][umbrella][file_name]"
"[cisco][umbrella][rule_id]"
"[cisco][umbrella][ruleset_id]"
```

**Comment by legoguy1000** [comment]
Ya, i'm looking at what I originally copied from the Filebeat module last year and whats there now and I think there was a misinterpretation or I misread something as the source username and "identities" field should be all one and not 2 separate fields.
