### ISSUE TITLE
GCP CloudSQL integration

### ISSUE THREAD

**Issue by ravikesarwani** [elastic/integrations#4086]
[Google Cloud SQL](https://cloud.google.com/sql/) is a fully managed relational database service for MySQL, PostgreSQL, and SQL Server databases. It's one of the most popular service in the GCP ecosystem and developing an OOTB integration will help provide better time to value for our GCP customers on fulfilling observability needs on their key infrastructure services they rely on.

- Focus is on metrics.
- Metrics collection focuses on: Connections, CPU, Memory, Disk, Network In/Out, Read/Write operations, Queries, Failover, Replication
- Priority order is MySQL->PostgreSQL->SQL Server in that order

**User experience suggestion:**
- From the integration configuration/setup perspective “Google Cloud SQL” is a single integration and the users can select MySQL, PostgreSQL & SQL server as individual check marks to collect data. All 3 are checked by default. They should also have a filter to exclude one or more instances by “instance ID” (we can keep this as a stretch goal if its too complex).
- We need a "Google Cloud SQL overview" dashboard. This provides data points on all the DB instances available (MySQL, PostgreSQL & SQL server), counts/types and key top 10 instance metrics (Connections, CPU, Memory, Network). Then we need a separate dashboards for Google Cloud MySQL, PostgreSQL & SQL server, linked from the main overview one. These will cover the detailed metrics (Connections, CPU, Memory, Disk, Network In/Out, Read/Write operations, Queries, Failover, Replication) focusing on top 10-15 instances by default and allowing filtering by Instance(s).

**Comment by gpop63** [comment]
Would this require multiple data streams in the GCP integration: `cloudsql_mysql`, `cloudsql_postgresql`, `cloudsql_sql_server`, or 1 data stream `cloudsql` would be better since there are shared metrics?

**Comment by ravikesarwani** [comment]
I will let the technical decision be driven by the engg. team but would like to help define the user experience so that it can help us make the right technical decision.

If I work backwards from customers perspective the hypothesis is that we need a "Google Cloud SQL overview" dashboard. This provides data points on all the DB instances available (MySQL, PostgreSQL & SQL server), counts/types and key top 10 instance metrics (Connections, CPU, Memory, Network).

Then we need a separate dashboards for Google Cloud MySQL, PostgreSQL & SQL server, linked from the main overview one. These will cover the detailed metrics (Connections, CPU, Memory, Disk, Network In/Out, Read/Write operations, Queries, Failover, Replication) focusing on top 10-15 instances by default and allowing filtering by Instance(s).

From the integration configuration/setup perspective “Google Cloud SQL” is a single integration and the users can select MySQL, PostgreSQL & SQL server as individual check marks to collect data. All 3 are checked by default. They should also have a filter for each DB type to exclude one or more instances by “instance ID” (we can keep this as a stretch goal if its too complex).

**Comment by endorama** [comment]
> They should also have a filter for each DB type to exclude one or more instances by “instance ID” (we can keep this as a stretch goal if its too complex).

I think this deserves its own issue, as it is not supported at the moment by the underlying input.

**Comment by gpop63** [comment]
There is a problem we encounter if we implement this integration without additional logic that collects CloudSQL metadata in `metricbeat`. If CloudSQL is enabled in the GCP integration, for example the metric `database.up` is collected by all 3 `cloudsql` datastreams (`mysql`, `postgresql`, `sqlserver`), even if maybe a single PostgreSQL instance sent it. There is no way to know which database type sent that event.
