### ISSUE TITLE
System version `v1.19.3` not available on 8.4.1 BC2.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#4094]
**Kibana version:**  8.4.1 BC2 Kibana cloud environment

**Host OS:**  All

**Build details:**
BUILD: 55434
COMMIT: 415cecc1c67ed775c4d9f6592fe5acc35dc9dce5

**Preconditions:**
1. 8.4.1 BC2 Kibana cloud environment should be available.
2. Policy should be created having System integration.

**Integration Version:**
`System v1.16.2`

**Steps to reproduce:**
1. Navigate to Fleet>Agents Policies tab.
2. Observe System integration v1.16.2.
3. Navigate to Edit System integration and observe Events older than field not available for System datasets.

**Related Feature:**
https://github.com/elastic/integrations/pull/3691

**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/187378693-1e3d6997-fe81-41d4-831e-c507d377e45e.JPG)

**Expected Result:**
System version `v1.19.3` should be available on 8.4.1 BC2.

**Impacted Testcase:**
[C35556](https://elastic.testrail.io/index.php?/cases/view/167687&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=35556&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=35556)

**Comment by amolnater-qasource** [comment]
FYI @jlind23

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
@amolnater-qasource it is only because system integrations versions were not promoted to production.
@fearful-symmetry do you think we can promote the latest system integration which is 1.19.3?

**Comment by fearful-symmetry** [comment]
As of last week, everything _should_ be promoted properly.

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this on latest 8.4.1 released kibana cloud build and observed latest version System integration `v1.19.3` available.

**Build details:**
BUILD: 55434
COMMIT: 415cecc1c67ed775c4d9f6592fe5acc35dc9dce5

**Screenshot:**
![7](https://user-images.githubusercontent.com/77374876/188813197-cca86ce1-5641-42a3-ba77-2fc252950bc0.JPG)

Hence we are closing this issue and marking as QA:Validated.
Thanks
