### ISSUE TITLE
Ensure all integrations fields have `unit`, `metric_type` and `dimension`

### ISSUE THREAD

**Issue by endorama** [elastic/integrations#4099]
[Per our development guidelines](https://github.com/elastic/integrations/blob/main/docs/generic_guidelines.md#specify-metric-types-and-units) all fields should have 2 specific settings: `unit` and `metric_type`.

From an internal discussion and observation of this repository is not the case and a lot of data streams are missing the `metric_type` and/or `unit` field settings.

Example of documentation page for an integration with `metric_type` metadata: https://docs.elastic.co/integrations/apache#status-metrics

## Data stream missing `metric_type`

From my investigation there are `556` data streams and `444` of them **are missing** this setting. 

A data stream is missing if either _all_ required field don't have it or _some_ required field doesn't.

<details>
<summary>List of data streams with correct and complete <code>metric_type</code></summary>
<pre>
data stream signin_attempts in package 1password has metric_type
data stream status in package apache has metric_type
data stream cloudtrail in package aws has metric_type
data stream cloudwatch_logs in package aws has metric_type
data stream cloudwatch_metrics in package aws has metric_type
data stream ec2_logs in package aws has metric_type
data stream route53_public_logs in package aws has metric_type
data stream route53_resolver_logs in package aws has metric_type
data stream vpcflow in package aws has metric_type
data stream waf in package aws has metric_type
data stream app_insights in package azure_application_insights has metric_type
data stream platformlogs in package azure has metric_type
data stream springcloudlogs in package azure has metric_type
data stream compute_vm in package azure_metrics has metric_type
data stream compute_vm_scaleset in package azure_metrics has metric_type
data stream container_instance in package azure_metrics has metric_type
data stream container_registry in package azure_metrics has metric_type
data stream container_service in package azure_metrics has metric_type
data stream database_account in package azure_metrics has metric_type
data stream monitor in package azure_metrics has metric_type
data stream storage_account in package azure_metrics has metric_type
data stream log in package cisco_umbrella has metric_type
data stream findings in package cloud_security_posture has metric_type
data stream status in package cockroachdb has metric_type
data stream blkio in package containerd has metric_type
data stream cpu in package containerd has metric_type
data stream memory in package containerd has metric_type
data stream bucket in package couchbase has metric_type
data stream container in package docker has metric_type
data stream cpu in package docker has metric_type
data stream event in package docker has metric_type
data stream image in package docker has metric_type
data stream info in package docker has metric_type
data stream memory in package docker has metric_type
data stream network in package docker has metric_type
data stream apm_server_logs in package elastic_agent has metric_type
data stream auditbeat_logs in package elastic_agent has metric_type
data stream cloudbeat_logs in package elastic_agent has metric_type
data stream elastic_agent_logs in package elastic_agent has metric_type
data stream endpoint_sercurity_logs in package elastic_agent has metric_type
data stream filebeat_logs in package elastic_agent has metric_type
data stream fleet_server_logs in package elastic_agent has metric_type
data stream heartbeat_logs in package elastic_agent has metric_type
data stream metricbeat_logs in package elastic_agent has metric_type
data stream osquerybeat_logs in package elastic_agent has metric_type
data stream packetbeat_logs in package elastic_agent has metric_type
data stream audit in package elasticsearch has metric_type
data stream deprecation in package elasticsearch has metric_type
data stream slowlog in package elasticsearch has metric_type
data stream generic in package filestream has metric_type
data stream audit in package github has metric_type
data stream metrics in package hashicorp_vault has metric_type
data stream generic in package http_endpoint has metric_type
data stream generic in package httpjson has metric_type
data stream error in package iis has metric_type
data stream log in package kafka has metric_type
data stream audit in package kibana has metric_type
data stream log in package kibana has metric_type
data stream apiserver in package kubernetes has metric_type
data stream container in package kubernetes has metric_type
data stream controllermanager in package kubernetes has metric_type
data stream event in package kubernetes has metric_type
data stream pod in package kubernetes has metric_type
data stream proxy in package kubernetes has metric_type
data stream state_container in package kubernetes has metric_type
data stream state_cronjob in package kubernetes has metric_type
data stream state_daemonset in package kubernetes has metric_type
data stream state_deployment in package kubernetes has metric_type
data stream state_job in package kubernetes has metric_type
data stream state_node in package kubernetes has metric_type
data stream state_persistentvolume in package kubernetes has metric_type
data stream state_persistentvolumeclaim in package kubernetes has metric_type
data stream state_pod in package kubernetes has metric_type
data stream state_replicaset in package kubernetes has metric_type
data stream state_resourcequota in package kubernetes has metric_type
data stream state_service in package kubernetes has metric_type
data stream state_statefulset in package kubernetes has metric_type
data stream state_storageclass in package kubernetes has metric_type
data stream system in package kubernetes has metric_type
data stream volume in package kubernetes has metric_type
data stream network_summary in package linux has metric_type
data stream log in package log has metric_type
data stream log in package logstash has metric_type
data stream performance in package oracle has metric_type
data stream sysmetric in package oracle has metric_type
data stream result in package osquery_manager has metric_type
data stream kibana_audit in package platform_observability has metric_type
data stream kibana_log in package platform_observability has metric_type
data stream collector in package prometheus has metric_type
data stream query in package prometheus has metric_type
data stream remote_write in package prometheus has metric_type
data stream log in package rabbitmq has metric_type
data stream log in package redis has metric_type
data stream audit_events in package spring_boot has metric_type
data stream http_trace in package spring_boot has metric_type
data stream auth in package system has metric_type
data stream core in package system has metric_type
data stream filesystem in package system has metric_type
data stream fsstat in package system has metric_type
data stream load in package system has metric_type
data stream process_summary in package system has metric_type
data stream socket_summary in package system has metric_type
data stream syslog in package system has metric_type
data stream uptime in package system has metric_type
data stream generic in package tcp has metric_type
data stream threat in package ti_cybersixgill has metric_type
data stream generic in package udp has metric_type
data stream datastore in package vsphere has metric_type
data stream host in package vsphere has metric_type
data stream log in package vsphere has metric_type
data stream virtualmachine in package vsphere has metric_type
data stream perfmon in package windows has metric_type
</pre>
</details>

## Data stream missing `unit`

From my investigation there are `556` data streams and `0` of them **have** this setting.

**Comment by jsoriano** [comment]
When filling this metadata, please select also the dimension fields. This was missing from integration docs, adding it in https://github.com/elastic/integrations/pull/4113.

**Comment by tommyers-elastic** [comment]
this ticket is being worked on to improve docs around these fields: https://github.com/elastic/integrations/issues/4124
