### ISSUE TITLE
Empty Code block under Endpoint Integration

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/integrations#4110]
**Describe the bug**
Empty Code block under Endpoint Integration

**Build Details:**
```
VERSION: 8.5.0 SNAPSHOT
build:55925
commit:dc43193d73c5869335a239c7012528bb1fffd509
```

**Steps**
- Login to kibana deployment
- Go to integrations
- Click on Endpoint and Cloud Security Integration
- Observe the logs blocks have not details inside code block, scroll down and will notice many instance of blank code block

**Expected result**
- Details should be seen under the different code block of integration details page 

![image](https://user-images.githubusercontent.com/59917825/187852086-00d38ea1-143c-4d03-99fa-d604c07bda8b.png)

**Screen-Shoot:**

![image](https://user-images.githubusercontent.com/59917825/187835823-a0cb4148-c92c-4407-b17d-9b8206b077d6.png)

![image](https://user-images.githubusercontent.com/59917825/187835840-c89be786-80ea-4368-be2f-c29636692792.png)

**Comment by simranvaseer-qasource** [comment]
Hi Team
We have revalidated this issue with many other integrations and found it **reproducible** there.

Some integrations like:
- Linux
- Redis
- System
- Windows
- Nginx
- Kafka
- Fleet Server
- MongoDB

**Screenshots:**
![1](https://user-images.githubusercontent.com/102019374/187846975-06b55b7f-133f-443b-8215-ce64c5fc9cf9.png)
![2](https://user-images.githubusercontent.com/102019374/187847169-b8393cdd-0082-4d1f-87dd-f1d3da50bb8b.png)

Thanks

**Comment by karanbirsingh-qasource** [comment]
Hi Team,

we have validated this issue on 8.5.0 BC6 and found the issue to be fixed now. ✔️ 

**Build Details:**
```
Version:8.5.0 BC6
Commit:0b06c1437f38a9eb9a4273003d8d2ce2c8905189
Build:57022
```

**Screen-Shot**

![image](https://user-images.githubusercontent.com/59917825/196402242-02a3078d-058d-4cb9-8ed8-05e235740b12.png)


![image](https://user-images.githubusercontent.com/59917825/196402304-233db886-a6d2-4e7b-8c62-bcad4ee966ea.png)

![image](https://user-images.githubusercontent.com/59917825/196402480-6537ce54-6ecd-45e0-9d01-a14b10ec563e.png)


Hence we are closing this issue and adding "QA:Validated" tag to it.

thanks !!

**Comment by simranvaseer-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in exploratory testing.

 Thanks!
