### ISSUE TITLE
Request integrations for the Google cloud metrics metricset for Elastic Agent

### ISSUE THREAD

**Issue by cplow** [elastic/integrations#4119]
# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

**Comment by chrisservian** [comment]
I'm looking for CloudSQL, REDIS metrics from the Google Cloud. Something like what metricbeat gcp module offers - [Google Cloud Platform metrics metricset | Metricbeat Reference [7.17] | Elastic](https://www.elastic.co/guide/en/beats/metricbeat/7.17/metricbeat-metricset-gcp-metrics.html)

**Comment by endorama** [comment]
Hello @cplow, I'm going to close this as is partially a duplicate.

You can track your requests following these issues:
- cloudsql #4086 - there is a PR #4126
- metrics #4292 
- redis #4293
