### ISSUE TITLE
[Cisco Umbrella] The authorization header is malformed

### ISSUE THREAD

**Issue by MichalMarchewka** [elastic/integrations#4139]
Hello

Since yesterday when I updated and reinstalled Cisco Umbrella integration in my DEV environment I am receiving error 400 with below message:

[elastic_agent.filebeat][error] Input 'aws-s3' failed with: failed to initialize s3 poller: failed to get AWS region for bucket: operation error S3: GetBucketLocation, https response error StatusCode: 400, RequestID: 36CWBXAHG8A4GJP9, HostID: xaeeeQuY7i1txrGEtdRHbqiw29ir29umtxQeiFDk8lobh6PQcMKsa8pwltXgvC74NzFnnEX1HuM=, api error AuthorizationHeaderMalformed: The authorization header is malformed; a non-empty region must be provided in the credential.

Current integration settings are exactly the same as before integration reinstall. Even in my PRD environment settings are the same and integration is working as expected.

Elastic Cloud, version 8.4.1
Cisco Umbrella integration, version 1.3.0
Customer managed S3 bucket (not Cisco managed)

In PRD I am using Cisco Umbrella integration version 1.0.1.

**Comment by P1llus** [comment]
Ref: https://github.com/elastic/package-storage/pull/5470
