### ISSUE TITLE
Elastic-Agent "Windows" integration: asking for equivalent of linux iostats  (diskio.iostats more precisely)

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#4141]
Please 

Could you add some iostats figures (diskio stats per device name more precisely) to "Windows" integration ?
The goal is to supervise disk io stats on windows servers, particularly, those having critical applications using high number of iops such as DBs 

Thank you, Dan

**Comment by Danouchka** [comment]
cc @pmeresanu85 @pierrehilbert

**Comment by pierrehilbert** [comment]
cc @nimarezainia

**Comment by nimarezainia** [comment]
@Danouchka we will place this on the backlog however are not in a position to deliver it soon due to other high priorities.
