### ISSUE TITLE
Linux or Windows or System Integrations: periodically monitor network connections using "netstat -tupo" command

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#4143]
Hello 

By retrieving periodically the output of "netstat -tupo" command, sys and network admins can detect applications that are blocked due to a network issue (close wait ..., fin wait). 
Example of netstat -tupo commmand output :
```
tcp        0      0 localhost:smc-https     localhost:42770         ESTABLISHED 11043/elastic-agent  keepalive (3,20/0/0)
tcp        0      0 sa-da-ingest-02.c:40320 253.130.195.35.bc:https ESTABLISHED 25259/filebeat       keepalive (0,18/0/0)
tcp        0      0 sa-da-ingest-02.c:35698 253.130.195.35.bc:https ESTABLISHED 29514/filebeat       keepalive (11,13/0/0)
tcp        0      0 sa-da-ingest-02.c:35670 253.130.195.35.bc:https ESTABLISHED 29497/metricbeat     keepalive (1,88/0/0)
tcp        0      0 sa-da-ingest-02.c:35666 253.130.195.35.bc:https ESTABLISHED 11241/elastic-endpo  off (0.00/0/0)
tcp        0      0 localhost:42740         localhost:smc-https     ESTABLISHED 29497/metricbeat     keepalive (0,12/0/0)


```

The fields that would be parsed out of the results and then indexed would be:
- network proto type (tcp or udp)
- the local hostname address
- the local monitored port 
- the remote address
- the remote port 
- the connection state 
- the PID 
- the application name 
- the timer 

Thank you, Dan

**Comment by Danouchka** [comment]
cc @pmeresanu85 @pierrehilbert

**Comment by pmeresanu85** [comment]
@mukeshelastic @nimarezainia this request could be interesting for you to look into

**Comment by zez3** [comment]
@Danouchka Will this work on windows? as the command is different, also the output

**Comment by Danouchka** [comment]
I guess we should adapt to all environments

**Comment by pmeresanu85** [comment]
@SubhrataK @lalit-satapathy could you please check if this is something our team can address?

**Comment by Danouchka** [comment]
Any news @SubhrataK ?

**Comment by SubhrataK** [comment]
@nimarezainia please suggest, as this looks more of a systems related integration
