### ISSUE TITLE
elastic.agent fields missing from mappings

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#415]
I noticed that the three `elastic.agent.*` fields are not declared in `fields/*.yml` for data streams. Is this intentional? Or an oversight? 

```
- name: elastic.agent.id
  type: keyword
- name: elastic.agent.snapshot
  type: boolean
- name: elastic.agent.version
  type: keyword
```

**Comment by mtojek** [comment]
I haven't noticed `elastic.agent` fields and I suppose they should fail testing. I saw only `elastic_agent` fields: https://github.com/elastic/elastic-package/blob/master/internal/fields/validate.go#L150 . I believe we need to come up with a generic solution for common fields.
