### ISSUE TITLE
[GCP] host.hostname in metricset compute is set to the agents hostname

### ISSUE THREAD

**Issue by felix-lessoer** [elastic/integrations#4172]
Within the GCP integration the host.hostname is set with the hostname where the agent is installed.
While the host.name is set to the compute host we got the metrics from.

![image](https://user-images.githubusercontent.com/35069463/189162956-195a6e33-fd68-4d3b-a346-c967509f44ab.png)

**Comment by legoguy1000** [comment]
This probably needs to be updated https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/gcp/metrics/metricset.go#L349 or use an ingest pipeline to change it.
