### ISSUE TITLE
AWS and Azure integrations doc fixes

### ISSUE THREAD

**Issue by alaudazzi** [elastic/integrations#4183]
This issue tracks the feedback received during a UX session.
The customer reported specific pain points that need to be addressed in the AWS and Azure documentation. 

### Notes from the meeting Sep 9, 2022:

[Recording](https://elastic.slack.com/files/U01TTG7DHL4/F041VJE3M8C/video1011281524.mp4)
Participants: 
Elastic = Kaarina, Arianna, Angela

- We shared the recent doc fixes on AWS docs: https://docs.elastic.co/integrations/aws

- Most problematic integrations:
Azure Logs integration seems to encompass all the other Azure integrations, but you still have to install each separate Azure integration.
- For each Azure integration, Azure logs integration only works for one. For all other integrations, Azure Logs integration doesn’t work. 
- To get the proper pipeline and categorization, you have to install each separate Azure integration. 
- Azure Logs is used to just ingest Azure logs. This is confusing because the settings are misleading. 
- The Integrations Settings: There needs to be more information about connection strings and what you’re looking for. The event hub can contain other event hubs. The settings are looking for the main event hub, not the sub event hubs. 
These settings need help:
- These integrations are 1:1, not 1 for many. You can’t use this one agent to pull all logs.
- The following settings need more information:
   - **Eventhub** setting needs to specify that this is the main eventhub name. Do we need to add an error message when they don’t specify the main eventhub name? In Azure, this appears as Event Hubs Namespace. “Event hubs where logs are saved”
   - **Consumer Group** = Used if you dump all Azure logs into one event hub, then broken out into subgroups. Need more information on this. How does Azure actually use this?
   - **Connection String** = Connection string for the event hub where the data is actually being stored. 
All other settings make sense to the user.

- This does not apply to AWS. The AWS docs are accurate. 
- Other than integrations, anything else about the docs?
	The biggest issue is being able to find the content. 
	Integrations needs to be it’s own section. 
- This content would have been more useful directly in the UI.

CC @KOTungseth @dedemorton @bmorelli25 @ollyhowell 

Relates to https://github.com/elastic/integrations/pull/3907

**Comment by dedemorton** [comment]
cc'ing @zmoog as an FYI.

**Comment by zmoog** [comment]
Hey @dedemorton, thanks for cc'ing me! 

This report matches my experience with cases from customer support. I discussed this topic with the team during the last few weekly meetings, and we plan to work on the integration docs.

**Comment by alaudazzi** [comment]
@zmoog 

Integration docs are massive, there's lots to do, and your support is definitely precious!

A $150k+ customer, who is currently month-to-month but would like to convert to annual, found gaps in the Azure docs and took the time to report them to us. The required doc fixes might be easier than we expect. Updating one doc page will make a customer happier.
I'm happy to make those changes, if you can assist with the technical details.
We should update the section [Settings](https://docs.elastic.co/integrations/azure/activitylogs#settings) where we need to be more explicit on how to use these three settings:

**Eventhub** = Needs to specify that this is the main eventhub name. Do we need to add an error message when they don’t specify the main eventhub name? In Azure, this appears as Event Hubs Namespace. “Event hubs where logs are saved”
**Consumer Group** = Used if you dump all Azure logs into one event hub, then broken out into subgroups. Need more information on this. How does Azure actually use this?
**Connection String** = Connection string for the event hub where the data is actually being stored.
