### ISSUE TITLE
[system] Auth logs default config: remove 'hashicorp-vault-logs' tag

### ISSUE THREAD

**Issue by rsdrakh** [elastic/integrations#4188]
https://github.com/elastic/integrations/blob/57a42bf793fab71d4d0096138e2aa46c10d7fb3a/packages/system/data_stream/auth/manifest.yml#L39

The manifest.yml contains a default tag "hashicorp-vault-logs" in the auth logs config.
I think that probably got there by mistake?

Best
Robert

**Comment by andrewkroh** [comment]
Yeah, that's probably a copy / paste issue from reusing a config snippet from another integration.
