### ISSUE TITLE
[Cloudflare] Deprecate Logpull and rename Log Push

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#4217]
We recently shipped our Cloudflare Log Push integration, which is intended to replace the current Cloudflare Logpull based integration. Based on guidance from Cloudflare they recommend that we deprecate our Logpull integration, as Logpull is a legacy product and they are pushing their customers to switch over to using Logpush as well.

Can the current Logpull integration be deprecated and removed from future releases, while ensuring existing users of the integration can continue to use it for a period of time? A deprecation notice should be added to the integration for those users, with a recommendation to switch to Logpush. 

In parallel, can the new 'Cloudflare Log Push' integration be renamed to 'Cloudflare' as no other integration includes the method of ingestion in the name. This may involve having to rename the current 'Cloudflare' integration to 'Cloudflare Logpull' before we deprecate.

**Comment by legoguy1000** [comment]
My only thought is that the API (httpjson) input for the audit data stream should be migrated as logpush is only available to enterprise customers and anyone can use the API polling to ingest their audit logs.

**Comment by jamiehynds** [comment]
Closing, as'll keep Logpull for the foreseeable. Although Cloudflare recommend Logpush for most logging use cases, Logpul remains fully support and we'll continue to do the same.
