### ISSUE TITLE
Citrix ADC(NetScaler) Package Evaluation

### ISSUE THREAD

**Issue by muthu-mps** [elastic/integrations#4221]
### Evaluation Checklist

- [x] Create the PRD/TDD spec
- [x] Document supported version, platforms
- [x] Evaluate and mention dependencies, roadblocks and configuration options and testing methodologies and the support platform.
- [x] Perform a dry run with the Citrix ADC installation and configuring with the integrations
- [x] Collect the sample monitoring metrics data.

**Comment by muthu-mps** [comment]
[Citrix ADC PRD](https://docs.google.com/document/d/1iJ5WYV0vGHhVpWBM0-vKjYAS_ooMo4ltxRfkBIcSr7k/edit#)

**Comment by jamiehynds** [comment]
@muthu-mps  - @LaZyDK shared a sample pipeline that he is using in production, which may of interest if you are working on an ADC integration: https://github.com/elastic/integrations/issues/470#issuecomment-1064106801

**Comment by LaZyDK** [comment]
> @muthu-mps  - @LaZyDK shared a sample pipeline that he is using in production, which may of interest if you are working on an ADC integration: https://github.com/elastic/integrations/issues/470#issuecomment-1064106801

It's not perfect but it does the job for now :)

**Comment by muthu-mps** [comment]
> @muthu-mps - @LaZyDK shared a sample pipeline that he is using in production, which may of interest if you are working on an ADC integration: [#470 (comment)](https://github.com/elastic/integrations/issues/470#issuecomment-1064106801)

Thanks @jamiehynds for providing the details. Let me go through the details.

**Comment by muthu-mps** [comment]
> > @muthu-mps  - @LaZyDK shared a sample pipeline that he is using in production, which may of interest if you are working on an ADC integration: [#470 (comment)](https://github.com/elastic/integrations/issues/470#issuecomment-1064106801)
> 
> It's not perfect but it does the job for now :)

@LaZyDK - Let me have a look at the pipeline which is used currently.
