### ISSUE TITLE
Feature request: Cisco IOS hostname

### ISSUE THREAD

**Issue by makkaroni8** [elastic/integrations#4222]
Hi

Is it possible to implement the hostname of the Cisco IOS devices?

There is already a hostname attribute (log.syslog.hostname) but it returns strange numbers. and the numbers are different for the same host.

**Comment by andrewkroh** [comment]
@makkaroni8 Do you have a sample of the log that is producing the "strange numbers"? This may have already been fixed. There were several changes the Cisco IOS integrations to improve it's handling of the various log formats. Can you please try the latest version and let us know by reopening.
