### ISSUE TITLE
Airflow Package Migration Evaluation

### ISSUE THREAD

**Issue by ritalwar** [elastic/integrations#4228]
### Evaluation Checklist

- [x] Create the PRD/TDD spec
- [x] Document supported version, platforms
- [x] Evaluate and mention dependencies, roadblocks and configuration options and testing methodologies and the support platform.
- [x] Perform a dry run with the Airflow installation and configuring with the integrations
- [x] Collect the sample monitoring metrics data.

##Relates To:
- https://github.com/elastic/integrations/issues/3748

**Comment by ritalwar** [comment]
[Airflow Analysis Doc](https://docs.google.com/document/d/12b9IygbYXrykVEk-H76tb7MhaJFcTeaSVG38XQFkUeI/edit)

**Comment by rameshelastic** [comment]
@ritalwar ..is this done? If so can we close this sub task.

**Comment by ritalwar** [comment]
Yes Ramesh.
