### ISSUE TITLE
ES failed to parse date field with format : yyyy-MM-dd HH:mm:ss.SSSSSS

### ISSUE THREAD

**Issue by ritalwar** [elastic/integrations#4229]
while working on https://github.com/elastic/integrations/pull/4167, getting a date_time_parse_exception for the field last_seen which is of type date i.e 
"caused_by":{"type":"illegal_argument_exception","reason":"failed to parse date field [2022-09-07 09:55:51.911456] with format [strict_date_optional_time_nanos||epoch_millis]","caused_by":{"type":"date_time_parse_exception","reason":"Failed to parse with all enclosed parsers"}}}, dropping event!

Tried specifying different date and format combinations(also format: yyyy-MM-dd HH:mm:ss.SSSSSS) in fields.yml but the issue persists.

Need further analysis.

**Comment by lalit-satapathy** [comment]
@ritalwar Please change the **format** to a matching [format](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html). How about date_hour_minute_second_millis?

**Comment by ritalwar** [comment]
@lalit-satapathy Hi Lalit, tried that, but no luck. 

Also, my observation is whatever format I am specifying in fields.yml, it is not getting applied somehow because in error message the format am always getting for type date is:
reason":"failed to parse date field [2022-09-20 12:02:32.042203] with format [**strict_date_optional_time||epoch_millis**]","caused_by":{"type":"date_time_parse_exception","reason":"Failed to parse with all enclosed parsers"}}}, dropping event!

Ideally shouldn't it state the format am providing in fields.yml ?

OR if I specify field type as date_nanos in fields.yml then in that case getting similar error but with changed format like
 reason":"failed to parse date field [2022-09-20 12:02:32.042203] with format [**strict_date_optional_time_nanos||epoch_millis**]","caused_by":{"type":"date_time_parse_exception","reason":"Failed to parse with all enclosed parsers"}}}, dropping event!

In Both the cases their default format is getting applied and whatever format we are specfying explicitly is getting ignored somehow.
 i.e 
for **type: date** default format is **strict_date_optional_time||epoch_millis** and 
for **type: date_nanos** default format is **strict_date_optional_time_nanos||epoch_millis** which we get in error message of agent  logs.
