### ISSUE TITLE
SQL Server Integration Update needed (1.4.0)

### ISSUE THREAD

**Issue by muralidharanvenkataraman** [elastic/integrations#4244]
SQL Server Integration.

1.  Is there a possibility to use domain account instead of local account for gathering performance metrics?
2.  When a connection fails, it logs the id & password in clear text
3.  Integration should accept special characters.
4.  PORT field should support environment variable and it should allow multiple ports (assuming there are multiple sql instances running on a server).
5. SQL Server ERROR logs - Combines two log file entries into a single line and parser fails to parse those messages.  If I extract a single line from event.original field, the parser parses the message correctly.
6. field [event.original] already exists - error message shows in up in all microsoft_sqlserver.log dataset. 

Thanks
Murali

**Comment by muralidharanvenkataraman** [comment]
Any updates on this request ?

**Comment by lalit-satapathy** [comment]
In #3 are you referring to passwords?

**Comment by muralidharanvenkataraman** [comment]
Thank you :).
