### ISSUE TITLE
Elastic agent system.process.cpu mapping ms consistency 

### ISSUE THREAD

**Issue by nchaulet** [elastic/integrations#4245]
Some field in the elastic agent are not consistent we should use the same mapping for all the agent datastream

[system.process.cpu.system.time.ms](https://system.process.cpu.system.time.ms/) | date, long | Conflict
[system.process.cpu.total.time.ms](https://system.process.cpu.total.time.ms/) | date, long | Conflict
[system.process.cpu.user.time.ms](https://system.process.cpu.user.time.ms/) | date, long | Conflict

**type: long**
metrics-elastic_agent.elastic_agent-default

**type: date**
metrics-elastic_agent.apm_server-default
metrics-elastic_agent.filebeat-default
metrics-elastic_agent.fleet_server-default
metrics-elastic_agent.metricbeat-default
metrics-elastic_agent.osquerybeat-default

**Comment by andrewkroh** [comment]
This issue is still present as of 74e55abc934ea82ba69e96cf005793b35f876444.

**Comment by andrewkroh** [comment]
To add to this, these fields are inconsistent with the `beat` integration:

- beat.stats.libbeat.config.running - ([beat.stats](https://github.com/elastic/integrations/blob/74e55abc934ea82ba69e96cf005793b35f876444/packages/beat/data_stream/stats/fields/fields.yml#L783) |[elastic_agent_metrics](https://github.com/elastic/integrations/blob/74e55abc934ea82ba69e96cf005793b35f876444/packages/elastic_agent/data_stream/elastic_agent_metrics/fields/beat-stats-fields.yml#L162)) - let's standardize on  `long`
- beat.stats.libbeat.config.starts
- beat.stats.libbeat.config.stops
