### ISSUE TITLE
Elastic-Agent: Microsoft SQL Server Integration - configuration of named instances 

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#4257]
Many SQL Server named instances can be deployed on a single machine, listening on different ports 

**Currently** 
You can define many hosts but all should have same instance port, Username, Password 

**Enhancement Request**
Possibility to have connection settings per Host and add several hosts is required  
if for each Host, enter its own Instance Port, Username, Password.
Each will be then mapped to a named instance. 

Having several microsoft sql server integrations on same machine, 1 for each named instance,  is not ok because it means enabling (Windows Event Logs, SQL error logs) only on 1 of them and disabling log collection on the others.   

Moreover, 2 named instance may not have the same password, port, username

Thanks 

**Definitions of SQL server instances  / Databases** 
https://pediaa.com/what-is-the-difference-between-instance-and-database-in-sql-server/#:~:text=Conclusion-,The%20main%20difference%20between%20instance%20and%20database%20in%20SQL%20server,that%20stores%20data%20in%20tables.

**Comment by Danouchka** [comment]
cc @pmeresanu85 @lalit-satapathy @ManojS-shetty

**Comment by Danouchka** [comment]
This is actual config that is not ok 
<img width="1123" alt="Capture d’écran 2022-09-29 à 12 15 02" src="https://user-images.githubusercontent.com/48563314/193005621-6877b57a-b8c0-48c2-baa6-c4da4c011f14.png">

**Comment by lalit-satapathy** [comment]
Draft [PR](https://github.com/elastic/integrations/pull/4501) out, which will address some of the critical named instance gaps.

<img width="1465" alt="Screenshot 2022-11-02 at 8 01 49 PM" src="https://user-images.githubusercontent.com/69236064/199517359-ba1f81f1-c48d-4529-bd58-20633365e1f6.png">

**Comment by muthu-mps** [comment]
Fixed in #4501

**Comment by Danouchka** [comment]
Hi @lalit-satapathy @muthu-mps  what if the username & password are different for each host:port ? 
cc @pmeresanu85

**Comment by lalit-satapathy** [comment]
> Hi @lalit-satapathy @muthu-mps what if the username & password are different for each host:port ? cc @pmeresanu85

That is not an issue, since each host is taken separately. Please go through the host configuration section in latest [doc](https://github.com/muthu-mps/integrations/blob/67005688debf21c0f19a00d2614c97e7495847e5/packages/microsoft_sqlserver/_dev/build/docs/README.md).
