### ISSUE TITLE
Elastic-Agent: Microsoft SQL Server Integration - missing metrics for user defined databases 

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#4258]
Hello

**Currently**
metricbeat retrieves transaction log metrics for user defined databases and system databases 

**Issue** 
At equivalent configuration, elastic-Agent Microsoft SQL Server Integration does retrieve Transaction Logs metrics only for system databases. 
Transaction Logs metrics for user-defined databases should be also retrieved by Elastic Agent SQL Server integration 

Thanks 

**Microsoft SQL Server description**
https://pediaa.com/what-is-the-difference-between-instance-and-database-in-sql-server/#:~:text=Conclusion-,The%20main%20difference%20between%20instance%20and%20database%20in%20SQL%20server,that%20stores%20data%20in%20tables.

**Comment by Danouchka** [comment]
cc @pmeresanu85 @lalit-satapathy @ManojS-shetty

**Comment by muthu-mps** [comment]
@Danouchka - The user defined database will be passed as a user input from the integrations UI and the metrics collected for those database.

**Comment by pmeresanu85** [comment]
Hi @muthu-mps,

I must say I agree with @Danouchka perspective.
We should aim at providing the same functionality with the Elastic agent based MS SQL Server Integration; maybe even improving the experience.

Furthermore the scenario where a customer has 100DBs/ 1000 DBs is not that uncommon in a customer setting. 

Can you please work with @SubhrataK and make sure we at least match the Beats functionality?

Thank you!

**Comment by muthu-mps** [comment]
@pmeresanu85 - Sure, We are currently working on this. FYI - This issue is also tracked [here](https://github.com/elastic/integrations/issues/4108).

**Comment by lalit-satapathy** [comment]
Closing per https://github.com/elastic/integrations/issues/4108
