### ISSUE TITLE
AWS integration UX enhancements

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#427]
This issue is to track several enhancements we would like to make for `aws` integration:

- [x] Change from `Collect from AWS instances` to `Collect from AWS services`: fixed by https://github.com/elastic/integrations/pull/426
- [x] Make `type: bool` a toggle `true/false` instead of a text box: tracking by https://github.com/elastic/kibana/issues/84699
![boolean](https://user-images.githubusercontent.com/14081635/100787262-9cb12000-33d0-11eb-9070-0ddc3ff49060.png)

- [x] Move common config options for both metrics and logs under `Integration settings`: This can be done after https://github.com/elastic/package-spec/issues/51 is resolved.
![aws-integration-screenshot](https://user-images.githubusercontent.com/14081635/100787251-96bb3f00-33d0-11eb-8b1e-3167b87c9788.png)

cc @sorantis @mostlyjason

**Comment by mostlyjason** [comment]
Thanks @kaiyan-sheng

**Comment by kaiyan-sheng** [comment]
`bool` type is fixed as shown below:
<img width="736" alt="Screen Shot 2021-01-12 at 2 32 27 PM" src="https://user-images.githubusercontent.com/14081635/104377063-1f0a2500-54e3-11eb-8d5e-0728f850ff8c.png">

**Comment by kaiyan-sheng** [comment]
For the third task, we already have credential configuration options all under Integration settings for all data streams.
