### ISSUE TITLE
Add `processor` optional input for the Kubernetes integration

### ISSUE THREAD

**Issue by ChrsMark** [elastic/integrations#4288]
At the moment we cannot add a processor in the Kubernetes integration when it is managed by Fleet UI. It would be helpful to add a `processor` optional input so as to cover cases like when orchestrator fields are not populated in specific environments.

**Comment by gizas** [comment]
Long term solution would be: https://github.com/elastic/kibana/issues/140276

**Comment by vnirocha** [comment]
Any updates on this? The issue is closed but it seems like the new version is not available to download on kibana.

**Comment by gizas** [comment]
@vnirocha is included in kubernetes integration v1.26.0 (cc https://github.com/elastic/integrations/pull/4363/files#diff-f5cad472c8987c44a5ae13aa50b43dd7f3ddbdc5709dded2519ba851aa43d8daR2 )
