### ISSUE TITLE
Elastic-Agent: Oracle Database Audit Logs Parser

### ISSUE THREAD

**Issue by muralidharanvenkataraman** [elastic/integrations#4299]
Hi There,

Finding an issue with Oracle Database Audit Logs parser.  The parser fails with the following error message

`field [audit] does not contain value_split [:\\S\\d+\\S(?= ')]`

Upon researching, the original message has `\n` in multiple locations within the ACTION field.  This causes the ACTION field to be populated with the message up to the first occurence of `\n`.

Example of EVENT.ORIGINAL field
`Tue May 25 16:31:54 2021 -04:00\nLENGTH : '2080'\nACTION :[1810] 'CREATE OR REPLACE TYPE MY_Collection_T FORCE\nOID '00000000000000000000000000020017'\nauthid current_user\nAS OPAQUE VARYING (*)\nUSING library DBMS_MYCOLL_LIB\n(\n -- Methods\n MEMBER FUNCTION create_Index (specification VARCHAR2)\n RETURN NUMBER,\n\n MEMBER FUNCTION create_View_From_DG (view_Name VARCHAR2,\n data_Guide CLOB)\n RETURN NUMBER,\n\n MEMBER FUNCTION drop_Index (index_Name VARCHAR2,\n force BOOLEAN DEFAULT FALSE)\n RETURN NUMBER,\n\n MEMBER FUNCTION find\n RETURN SODA_Operation_T,\n\n MEMBER FUNCTION find_One (key VARCHAR2)\n RETURN SODA_Document_T,\n\n MEMBER FUNCTION get_Data_Guide\n RETURN CLOB,\n\n MEMBER FUNCTION get_Metadata\n RETURN VARCHAR2,\n\n MEMBER FUNCTION get_Name\n RETURN NVARCHAR2,\n\n MEMBER FUNCTION insert_Many (document_List SODA_Document_List_T)\n RETURN NUMBER,\n\n MEMBER FUNCTION insert_One (document SODA_Document_T)\n RETURN NUMBER,\n\n MEMBER FUNCTION insert_One_And_Get (document SODA_Document_T,\n hint VARCHAR2 DEFAULT NULL)\n RETURN SODA_Document_T,\n\n MEMBER FUNCTION remove_One (key VARCHAR2)\n RETURN NUMBER,\n\n MEMBER FUNCTION replace_One (key VARCHAR2,\n document SODA_Document_T)\n RETURN NUMBER,\n\n MEMBER FUNCTION replace_One_And_Get (key VARCHAR2,\n document SODA_Document_T)\n RETURN SODA_Document_T,\n\n MEMBER FUNCTION save (document SODA_Document_T)\n RETURN NUMBER,\n\n MEMBER FUNCTION save_And_Get (document SODA_Document_T,\n hint VARCHAR2 DEFAULT NULL)\n RETURN SODA_Document_T,\n\n MEMBER FUNCTION truncate\n RETURN NUMBER\n\n) FINAL NOT PERSISTABLE;'\nDATABASE USER:[1] '/'\nPRIVILEGE :[6] 'SYSDBA'\nCLIENT USER:[6] 'oracle'\nCLIENT TERMINAL:[5] 'pts/0'\nSTATUS:[1] '0'\nDBID:[10] '2290978012'\nSESSIONID:[10] '4294967295'\nUSERHOST:[24] 'server.my.domain'\nCLIENT ADDRESS:[0] ''\nACTION NUMBER:[2] '77'\n`

Example of AUDIT field (To prove my theory, I replaced \n with ~~~~~)

`ACTION :[1810] 'CREATE OR REPLACE TYPE SODA_Collection_T FORCE\nOID '00000000000000000000000000020017'~~~~~authid current_user\nAS OPAQUE VARYING (*)\nUSING library DBMS_SODACOLL_LIB\n(\n -- Methods\n MEMBER FUNCTION create_Index (specification VARCHAR2)\n RETURN NUMBER,\n\n MEMBER FUNCTION create_View_From_DG (view_Name VARCHAR2,\n data_Guide CLOB)\n RETURN NUMBER,\n\n MEMBER FUNCTION drop_Index (index_Name VARCHAR2,\n force BOOLEAN DEFAULT FALSE)\n RETURN NUMBER,\n\n MEMBER FUNCTION find\n RETURN SODA_Operation_T,\n\n MEMBER FUNCTION find_One (key VARCHAR2)\n RETURN SODA_Document_T,\n\n MEMBER FUNCTION get_Data_Guide\n RETURN CLOB,\n\n MEMBER FUNCTION get_Metadata\n RETURN VARCHAR2,\n\n MEMBER FUNCTION get_Name\n RETURN NVARCHAR2,\n\n MEMBER FUNCTION insert_Many (document_List SODA_Document_List_T)\n RETURN NUMBER,\n\n MEMBER FUNCTION insert_One (document SODA_Document_T)\n RETURN NUMBER,\n\n MEMBER FUNCTION insert_One_And_Get (document SODA_Document_T,\n hint VARCHAR2 DEFAULT NULL)\n RETURN SODA_Document_T,\n\n MEMBER FUNCTION remove_One (key VARCHAR2)\n RETURN NUMBER,\n\n MEMBER FUNCTION replace_One (key VARCHAR2,\n document SODA_Document_T)\n RETURN NUMBER,\n\n MEMBER FUNCTION replace_One_And_Get (key VARCHAR2,\n document SODA_Document_T)\n RETURN SODA_Document_T,\n\n MEMBER FUNCTION save (document SODA_Document_T)\n RETURN NUMBER,\n\n MEMBER FUNCTION save_And_Get (document SODA_Document_T,\n hint VARCHAR2 DEFAULT NULL)\n RETURN SODA_Document_T,\n\n MEMBER FUNCTION truncate\n RETURN NUMBER\n\n) FINAL NOT PERSISTABLE;'~~~~~DATABASE USER:[1] '/'~~~~~PRIVILEGE :[6] 'SYSDBA'~~~~~CLIENT USER:[6] 'oracle'~~~~~CLIENT TERMINAL:[5] 'pts/0'~~~~~STATUS:[1] '0'~~~~~DBID:[10] '2290978012'~~~~~SESSIONID:[10] '4294967295'~~~~~USERHOST:[24] 'server.my.domain'~~~~~CLIENT ADDRESS:[0] ''~~~~~ACTION NUMBER:[2] '77'~~~~~`

Example of oracle.database_audit.ACTION field
`CREATE OR REPLACE TYPE SODA_Collection_T FORCE\nOID '00000000000000000000000000020017`

Thanks
Murali

**Comment by muralidharanvenkataraman** [comment]
I have another scenario where the logs without ACTION word, fails with a GROK matching,  Here is a sample message

Sample Message

`- @timestamp, column 3, row 1
Mon Aug 17 05:25:25 2020 -04:00\nLENGTH: \"361\"\nSESSIONID:[9] \"475841391\" ENTRYID:[1] \"1\" STATEMENT:[1] \"1\" USERID:[14] \"LMS_QUARTZ_USR\" USERHOST:[26] \"plweblogic10.wil.csc.local\" TERMINAL:[7] \"unknown\" ACTION:[3] \"100\" RETURNCODE:[1] \"0\" COMMENT$TEXT:[99] \"Authenticated by: DATABASE; Client address: (ADDRESS=(PROTOCOL=tcp)(HOST=10.10.10.0)(PORT=41679))\" OS$USERID:[8] \"weblogic\" DBID:[10] \"3055782571\" \n]`


Thanks
Murali

**Comment by muralidharanvenkataraman** [comment]
If I remove the `\"` with `'`, and also define a new GROK pattern, then I'm able to go past the GROK parser failure.

`%{GREEDYDATA:tmp_timestamp}\nLENGTH: '%{GREEDYDATA:LENGTH}'\n(?m)%{GREEDYDATA:audit}`

It looks like I need to have a separate pipeline to process this type of message.

Thanks
Murali

**Comment by jamiehynds** [comment]
@P1llus would you mind having a look at these samples and confirm if they match our expected format or if adjustments are required to our pipeline?

**Comment by muralidharanvenkataraman** [comment]
@P1llus - Please let me know if you need any additional information.

**Comment by P1llus** [comment]
@muralidharanvenkataraman I think we have all the test messages we need. Will push something out this week (looking at it today)

**Comment by muralidharanvenkataraman** [comment]
@P1llus -  Can I expect an update today ?

**Comment by muralidharanvenkataraman** [comment]
@P1llus - Can we expect an update today ?

**Comment by P1llus** [comment]
@muralidharanvenkataraman I have applied the changes locally, I was just looking for some test data to add to our tests, the issue with the examples you have provided is the format, this is how our test data looks: https://github.com/elastic/integrations/blob/main/packages/oracle/data_stream/database_audit/_dev/test/pipeline/test-oracle-database-audit.log

Would you happen to have any examples in that format? Worst case we can try to build one by hand, but I feel it might miss certain important aspects.

After we have the test data we can push out the hotfix you have provided once it pass our tests.

**Comment by muralidharanvenkataraman** [comment]
@P1llus - I will attach the sample logs to this case - 01034607 or I can email them to you.

Please let me know if you are able to access the internal case.

**Comment by P1llus** [comment]
@muralidharanvenkataraman Let me see if I can access them, should be possible :)

**Comment by muralidharanvenkataraman** [comment]
awesome, I just attached the logs to the case.

**Comment by P1llus** [comment]
@muralidharanvenkataraman I am working on anonymizing it so I can use it as test data, since I am only interested in the format of the actual log data.

Hopefully I can push out the fix once the tests finishes sometime today. Once I have pushed it I will link the PR here.

**Comment by muralidharanvenkataraman** [comment]
@P1llus - thank you :)
