### ISSUE TITLE
Description for "Collective Intelligence Framework v3" integration is broken

### ISSUE THREAD

**Issue by maxcold** [elastic/integrations#4305]
The description for "Collective Intelligence Framework v3" integration on the Integrations page in Kibana is broken, seems like it has malformed markdown or smth. Here is the screenshot 
<img width="1720" alt="Screenshot 2022-09-26 at 14 53 48" src="https://user-images.githubusercontent.com/478762/192282096-fd35b19f-581b-4b3f-b7e9-e7eca05ae0c0.png">

**Comment by efd6** [comment]
The fix for this is in #4295.
