### ISSUE TITLE
Support conditions algongside parser config with kubernetes integration

### ISSUE THREAD

**Issue by paul-mesnilgrente** [elastic/integrations#4306]
I noted that https://github.com/elastic/integrations/issues/2313 had a related PR to add parser configs in the advanced section.

Although this line: https://github.com/elastic/integrations/pull/2345/files#diff-0357f29b430528695df420c2917a9cb06b6ade346ee0b1d71603e50befa1dcc2R10 is a bit troublesome.

Because of this line, I can have something like this to only get production logs: 
![image](https://user-images.githubusercontent.com/4416830/192319376-379b007b-2d7b-44a8-8848-71df024e87e3.png)

But I can't add parser configs like because it's not valid YAML:
![image](https://user-images.githubusercontent.com/4416830/192319778-283f16de-3a0e-4bd7-b31e-016f2db37b94.png)

Is there any possibility to add support (or maybe there is?) for both "condition" and parser configs?

**Comment by legoguy1000** [comment]
That's because the config ur using isn't a parser config. It's part of the input. Really there should be 2 config options. One for parsers and another for the condition.

**Comment by paul-mesnilgrente** [comment]
Yeah, that sounds right. Do you think there is any chance to see this in a future release? I'm not familiar with all this so I'm afraid I can't create a PR for it without spending days and days.

**Comment by legoguy1000** [comment]
@paul-mesnilgrente PR created
