### ISSUE TITLE
[AWS] Unable to add Amazon DynamoDB integration, billing agent template is invalid

### ISSUE THREAD

**Issue by prachigupta-qasource** [elastic/integrations#4307]
**Kibana version:** 8.5 Kibana Staging environment

**Host OS and Browser version:** All, All

**Build Details:**

```
Version: 8.5.0 BC1
Build: 56595
Commit: 0d8de4df69f8084a94cdd9638d7de510813cb5ce
```

**Preconditions:**

- 8.5 Kibana cloud environment should be available.

**Steps to reproduce:**

1. Navigate to Integrations page.
2. Search `Amazon DynamoDB` integration.
3. Navigate to `Amazon DynamoDB` integration details page.
4. Click `+Amazon DynamoDB` button.
5. Fill the details and click on 'Save and continue' button.
6. Observe that the error is shown.

**Expected Result:**

-  `Amazon DynamoDB` integration should be added.

**Screenshots:**

![image](https://user-images.githubusercontent.com/97870262/192265715-7ec17852-1fba-498c-b153-7f247ea4f78b.png)

![image](https://user-images.githubusercontent.com/97870262/192265734-8b911783-fe7c-4b97-a83e-35411b31a799.png)

**Comment by legoguy1000** [comment]
Damn, looks like that was my fault when I added the default region option

**Comment by legoguy1000** [comment]
PR submitted

**Comment by prachigupta-qasource** [comment]
Hi  @jen-huang  @legoguy1000  @zmoog,

We have re-validated this issue on the latest **8.5.0 BC3** Kibana Cloud environment and found that the issue is **fixed**.

**Build details:**

```
Version: 8.5.0 BC3
Build: 56932
Commit: 1bb0d052c8d6842b88665c8c489f3a2d4cf4b46a
```
**Below are the observations:**

**Scenario 1:**  Through `Fleet > Agent Policies`  page

- Amazon DynamoDB integration is added.

https://user-images.githubusercontent.com/97870262/194469923-e679d012-354d-4975-90b5-3211b0d7b1ec.mp4

**Scenario 2:**  Through `Integrations` page 

- Amazon DynamoDB integration is added.

https://user-images.githubusercontent.com/97870262/194469968-99eb89ee-bc6b-42f7-abdb-572450f5e536.mp4


Hence, marking this issue as QA: Validated.

Thanks!
