### ISSUE TITLE
System Test not present for galera_status datastream of mysql package.

### ISSUE THREAD

**Issue by ishleenk17** [elastic/integrations#4313]
System Test not present for galera_status datastream of mysql package.
Its important to have one for testing basic working of the datastream

**Comment by ritalwar** [comment]
Trying to set-up a Galera cluster to get some sample data.
Draft PR: https://github.com/elastic/integrations/pull/5194

**Comment by ritalwar** [comment]
Update sample data, [PR](https://github.com/elastic/integrations/pull/5194) ready for reviw.
