### ISSUE TITLE
[System][auth] Erroneous definition of default tags makes tags mandatory in Kibana UI

### ISSUE THREAD

**Issue by herrBez** [elastic/integrations#4333]
The auth dataset in the system integration defines a tag named `hashicorp-vault-log`. This makes Kibana consider the tag mandatory. The cause seems related to this line in the manifest definition https://github.com/elastic/integrations/blob/d3fe0f6470ed9cbed9472e1bf42e8cf99ae37db8/packages/system/data_stream/auth/manifest.yml#L39 

I post two images to let you better understand the impact on the Fleet UI. Without modifying the system auth dataset, we see that the tag  `hashicorp-vault-log` is defined.
<img width="380" alt="integration-issue-tag" src="https://user-images.githubusercontent.com/6976484/192774960-dc10f6ea-79d8-4ef9-a951-a336ad61e072.png">

Moreover, if we try to remove the tag, Kibana complains that the tag is mandatory
<img width="388" alt="integration-issue-tag-missing" src="https://user-images.githubusercontent.com/6976484/192796089-4e7cefe7-2e88-4ab1-85cb-ba8b50ef1b18.png">

**Comment by legoguy1000** [comment]
I created #4248 to resolve that.

**Comment by herrBez** [comment]
I think we can consider this issue closed?

**Comment by herrBez** [comment]
Closing, because of https://github.com/elastic/integrations/pull/4248.
