### ISSUE TITLE
Elastic Agent's integration package

### ISSUE THREAD

**Issue by ph** [elastic/integrations#434]
Since 7.9 we are sending the Elastic Agent is sending log and metric to Elasticsearch agent. We should create an Elastic Agent packages to define the exposed data stream.

**AC:**
- [ ] The integrations package should support Elastic Agent's log.
- [ ] The integrations package should support Elastic Agent's metric.
- [ ] The integrations package should contains a dashboard to expose Elastic Agent's metric. (Need issues to formalize the graph based on https://github.com/elastic/beats/issues/22394 )
- [ ] The integration package should support Filebeat and Metricbeat logs
- [ ] The integrations pacakge should support Filebeat and Metricbeat log.

# Open questions

@ravikesarwani  Can we clarify the plan for observability and the dashboard, I believe we wanted to have a custom UI for displaying the relevent metrics but in the meantime to have a dashboard that display the metrics. Is that correct?

@ruflin I assuming our intention is to have this integration installed by default like system and endpoint? We should probably have a concept of **internal or system integration** so users cannot mess with them.

**Comment by ravikesarwani** [comment]
Current thinking is for dashboard only. The dashboard should allow filtering by "All, Agent, Filebeat & Metricbeat". The fleet UI will link to this dashboard.

**Comment by ruflin** [comment]
@ph Agree this should be a preinstalled integration as we do with system and endpoint. These are hardcoded in KB and I would follow the same logic here.

**Comment by nchaulet** [comment]
@ravikesarwani I am starting on building a dashboard for the metric is there any mock up that I can use as reference on what we want to have?

**Comment by ravikesarwani** [comment]
Beats monitoring overview (from SM UI) is what we have for mock up. Its curated vs. dashboard so the look and feel will be different and that is okay.

**Comment by ravikesarwani** [comment]
You should be able to browse that in the [observability clusters](https://release-oblt.elastic.dev/app/monitoring#/beats/beats?_g=(cluster_uuid:'5c_yX2zTS02b1v09iVUv6Q',refreshInterval:(pause:!f,value:10000),time:(from:now-1h,to:now))).

**Comment by mtojek** [comment]
@nchaulet do you plan to release it to prod?

**Comment by nchaulet** [comment]
@mtojek yes what is the next step do it?

**Comment by mtojek** [comment]
You can use `elastic-package promote` (snapshot -> production if you're confident that it will work) to open PRs in package-storage.
