### ISSUE TITLE
[Stack Monitoring] Support field overrides in package inputs

### ISSUE THREAD

**Issue by matschaffer** [elastic/integrations#4351]
https://github.com/elastic/beats/issues/32665 includes an example of adding fields to a log input

```
        fields:
          service.name: 'kibana'
          cloud.availability_zone: 'danger-zone'
```

We should ensure these are still supported when using packages to ingest stack component logs. The original issue is kibana-specific, but I think we can use this issue to test and ensure support for all stack monitoring packages.

**Comment by smith** [comment]
This looks like a missing feature in integrations/fleet in general. Keeping in backlog for now.
