### ISSUE TITLE
[microsoft_dhcp] Non-standard "MAC Addresses" stored in host.mac

### ISSUE THREAD

**Issue by nicpenning** [elastic/integrations#4360]
After testing this integration, I found that some devices are not passing along a MAC address but instead a machine identifier which does not conform with the standard MAC address of 12 characters. Instead I have a unique identifier that is 40 characters long. This seems to be the phenomenon with some Linux systems as noted here: https://superuser.com/questions/1552917/36-chars-mac-addresses-on-windows-server-2012-dhcp-server?rq=1

https://github.com/elastic/integrations/blob/0cf02514c9851726fa0277822c899c953042e96b/packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/dhcp.yml#L337-L341

So I was wondering if we should add a check and limit this host.mac extraction to 12 characters and anything longer be set in a new field and a tag added to the event stating that this is not a standard MAC address. Perhaps it should live in microsoft.dhcp.invalid_mac or something of that sort.

An example original event looks like this (with some slight alterations):
`10,10/02/22,00:00:33,Assign,192.168.10.40,,653445372C132434342A381337302B566C616D31,,3327778676,0,,,,0x4850452E20485045204F6666696312336F6D6E65637420313825302A31325847542D345346502B20537769746368,COM. COM OfficeTele 2002-11ABC-4SFP+ Switch,,,0x0106766C323E3580,0`

**Comment by efd6** [comment]
From the discussion at the SU post, perhaps what is currently being mapped as `host.mac` should actually be being mapped as `host.id`. We could retain the current mapping of 6-octet identifiers as `host.mac` in addition.

**Comment by nicpenning** [comment]
Makes sense to me. Thanks!
