### ISSUE TITLE
[infoblox_nios] Add a grok pattern for the new type of log

### ISSUE THREAD

**Issue by vinit-elastic** [elastic/integrations#4365]
Infoblox Nios produces a new log pattern as mentioned below:
`<30>Feb 15 01:14:25 infoblox_localdomain dhcpd[2132]: DHCPACK on 81.2.69.142 to 00:00:5E:00:53:00 via eth3 relay 81.2.69.142 lease-duration 2100 uid 00:00:5E:00:53:00`

There is an additional `uid` field in this new log. To address this log, a new grok pattern needs to be added.

**Comment by vinit-elastic** [comment]
Infoblox NIOS produces a new log patterns as mentioned below:

**DHCP Release**
`<30>Sep 30 11:27:26 anudhcp.anu.edu.au 130.56.15.81 dhcpd[11411]: RELEASE on 10.20.142.129 to ce:93:30:8e:db:ac`
`<30>Sep 30 11:28:01 anudhcp.anu.edu.au 130.56.15.81 dhcpd[11411]: DHCPRELEASE of 10.28.39.37 from 50:eb:71:32:26:16 (ITS-053016) via 10.28.32.2 (found) TransID a030e930 uid 01:50:eb:71:32:26:16`

**DHCP ACK**
`<30>Sep 30 11:30:55 anudhcp.anu.edu.au 130.56.15.81 dhcpd[11411]: DHCPACK to 10.28.8.151 (9c:ad:97:7a:fd:33) via eth2`
`<30>Sep 30 11:33:03 anudhcp.anu.edu.au 130.56.15.81 dhcpd[11411]: DHCPACK on 130.56.53.143 to 4a:34:bf:d2:78:24 via eth2 relay 130.56.52.7 lease-duration 900 uid 01:4a:34:bf:d2:78:24`
`<30>Sep 30 11:33:03 anudhcp.anu.edu.au 130.56.15.81 dhcpd[11411]: DHCPACK on 130.56.53.143 to 4a:34:bf:d2:78:24 (my-iPhone) via eth2 relay 130.56.52.7 lease-duration 900 offered-duration 3600 (RENEW) uid 01:4a:34:bf:d2:78:24`
`<30>Sep 30 11:33:03 anudhcp.anu.edu.au 130.56.15.81 dhcpd[11411]: DHCPACK on 130.56.53.143 to 4a:34:bf:d2:78:24 via eth2 relay 130.56.52.7 lease-duration 900 offered-duration 3600 (RENEW) uid 01:4a:34:bf:d2:78:24`
`<30>Sep 30 11:33:03 anudhcp.anu.edu.au 130.56.15.81 dhcpd[11411]: DHCPACK on 130.56.53.143 to 4a:34:bf:d2:78:24 (my-iPhone) via eth2 relay 130.56.52.7 lease-duration 900 offered-duration 3600 (RENEW)`

There are some additional fields in the new logs. So for that, new Grok patterns need to be added in order to handle these logs.

**Comment by ulab** [comment]
Just for reference and if people search for it, is this was causes `error.message` to have messages similar to `For input string: "5884 offered-duration 5900 (RENEW) uid 01:01:01:01:01:01:01"`?

**Comment by vinit-elastic** [comment]
> Just for reference and if people search for it, is this was causes `error.message` to have messages similar to `For input string: "5884 offered-duration 5900 (RENEW) uid 01:01:01:01:01:01:01"`?

Hey @ulab Sorry for the late reply, There is additional fields in the new log `5884 offered-duration 5900 (RENEW) uid 01:01:01:01:01:01:01`. So for that, new grok pattern need to be added in order to handle these. That's why the `error.message` field is generated.

**Comment by ulab** [comment]
No worries.

I thought so. Just wanted to leave a search term in case someone is looking for it like me.

I hope your pull request gets through soon. My coworkers are eager to use the integration. ;)

**Comment by vinit-elastic** [comment]
Hey @ulab - sorry to keep you waiting. We will push the team from our side to get this PR merged, as soon as possible. Happy to see you excited about the integration. :)
