### ISSUE TITLE
[meta] Upgrade integrations to ECS 8.6

### ISSUE THREAD

**Issue by marc-gr** [elastic/integrations#4366]
This is a meta issue to track ECS 8.6 updates to Fleet integrations maintained by the `elastic/security-external-integrations` team.

### ECS 8.6 Changes

This is a summary of the changes in ECS 8.6. You can view the official changelog [here](https://github.com/elastic/ecs/blob/8.6/CHANGELOG.next.md#860-soft-feature-freeze).

This issue will be updated once the necessary work to be done is evaluated.

**Comment by ebeahan** [comment]
Completed in #4576
