### ISSUE TITLE
File Integrity Monitoring - Wildcard support in Paths to be monitored

### ISSUE THREAD

**Issue by rediasec** [elastic/integrations#4367]
The configuration page states that _wildcards are accepted_, but they do not work when used. 
Though, this behavior matches the statement from Auditbeat File Integrity Modules [docs](https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-module-file_integrity.html):
![image](https://user-images.githubusercontent.com/61625853/193595660-6dba95b9-ab67-4b70-9ac9-e39ea8cb8ef6.png)

![image](https://user-images.githubusercontent.com/61625853/193596024-dd84f806-898e-49a3-8d87-4e27e377f7c7.png)

**Comment by efd6** [comment]
Related issue: elastic/beats#31060
