### ISSUE TITLE
Write system test cases for performance data stream of Mysql

### ISSUE THREAD

**Issue by ritalwar** [elastic/integrations#4372]
Add system test cases for performance data stream of Mysql as a standard practice.

**Comment by rameshelastic** [comment]
@ritalwar , can you please outline the impact of the issue in the description.

**Comment by ishleenk17** [comment]
@ritalwar : What is the blocker for this one ?

**Comment by ritalwar** [comment]
Hi @ishleenk17 , there was a bug fix in performance data stream and there exists no system test cases.
At that time fix was done but a separate issue was created to handle system test cases due to time constraint.
It is in our backlog as of now, can plan for some iteration.

**Comment by aliabbas-elastic** [comment]
Hi @ritalwar, I was trying to perform the data collection of `performance`  data stream before moving forward to the system tests.

Currently in the MySQL beats module, there is a blocker related to the data collection of the `performance` data stream. I am facing the following error `Error 1054: Unknown column 'quantile_95' in 'field list'`. 
![image](https://github.com/elastic/integrations/assets/124054599/aae03fbf-9f47-4471-a646-2350a0bca3bb)

Also, there is also an open [issue](https://github.com/elastic/beats/issues/25069) related to this.

The query used for the data collection is 

```
SELECT digest_text, count_star, avg_timer_wait, max_timer_wait, last_seen, quantile_95
  FROM performance_schema.events_statements_summary_by_digest
  ORDER BY avg_timer_wait DESC
  LIMIT 10
```

I tried to dig more into this issue and found that by adding the quote around `'quantile_95'` in the query (in the `metricbeat/module/mysql/performance/manifest.yml` file of MySQL metricbeat module), I am able to collect the data for performance metrics.

So the system tests will be dependent on the data collection. Let me know if you want to check anything else. 

Also, I found a weird thing related to the MySQL integration. Despite of there are no system tests , the `sample_event.json` file is generated for the `performance` metrics.

**Comment by ritalwar** [comment]
> Also, I found a weird thing related to the MySQL integration. Despite of there are no system tests , the sample_event.json file is generated for the performance metrics.

The sample_event.json files can be generated manually or extracted from the Discover page in Kibana.


@lalit-satapathy Should we prioritize looking into this open [issue](https://github.com/elastic/beats/issues/25069) first?

**Comment by lalit-satapathy** [comment]
> @lalit-satapathy Should we prioritize looking into this open [issue](https://github.com/elastic/beats/issues/25069) first?
Added to backlog, we need testing to confirm which versions are correctly supported first?

**Comment by ritalwar** [comment]
@aliabbas-elastic Could you please confirm when quantile_95 was introduced, the correct query to fetch the data, and also  in which version you encountered the error?  
Also, Does the existing code work properly with the MySQL version in which quantile_95 was introduced?

**Comment by aliabbas-elastic** [comment]
@ritalwar 
- I was trying to run the system tests on MariaDB and Percona images. The tests seem to use the hard-coded version specified in the `Dockerfile`. So system test will run for all the variants specified in variants.yml, but it will only use the hardcoded image in `Dockerfile` (which as mentioned in the screenshot is `mysql:8.0.13`), which seems to be some kind of mistake.

![image](https://github.com/elastic/integrations/assets/124054599/4125c287-1357-454b-946a-39e5cba73115)

While digging deep into this issue, I tried to run the system tests on all variants by some modification in the `Dockerfile` but it seems that tests are only compatible with MySQL images and not with Percona and MariaDB images. We are not sure why there is any need for Peracona and MariaDB images here. Could you provide more context on the same?

- Also regarding the `quantile_95` column, here is the [description](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-statement-summary-tables.html#:~:text=QUANTILE_95%3A%20The%2095th%20percentile%20of%20the%20statement%20latency%2C%20in%20picoseconds.%20This%20percentile%20is%20a%20high%20estimate%2C%20computed%20from%20the%20histogram%20data%20collected.%20In%20other%20words%2C%20for%20a%20given%20digest%2C%2095%25%20of%20the%20statements%20measured%20have%20a%20latency%20lower%20than%20QUANTILE_95). I am not sure whether to keep this field as it is not used in any visualizations as well. Please let me know what you think about this.

- Also FYI, I am able to query the `quantile_95` column in Percona version `8.0` by adding a tag. But with the latest tag(`5.7.35`) it is not available. For the Maria DB, it is not supported at all and I have checked in the latest version as well.

**Comment by ritalwar** [comment]
> but it will only use the hardcoded image in Dockerfile (which as mentioned in the screenshot is mysql:8.0.13), which seems to be some kind of mistake.

I think we should fix this.

> We are not sure why there is any need for Peracona and MariaDB images here. Could you provide more context on the same?

As per this [doc](https://github.com/elastic/integrations/tree/main/packages/mysql#compatibility), the mysql module is compatible with MySQL-based databases such as MariaDB and Percona, so it would be good to run system tests for these images as well.

> I am not sure whether to keep this field as it is not used in any visualizations as well. Please let me know what you think about this.

Sure, I will update you.

**Comment by ritalwar** [comment]
@aliabbas-elastic Let's focus on writing system test cases for the variants that are compatible with the existing code as part of this issue.

**Comment by aliabbas-elastic** [comment]
As discussed with @ritalwar, we can proceed with the system tests in two variants i.e., `mysql:8.0.13` and `percona:8.0.13-4`.
The rest of the variants don't support the `quantile_95` column in the query hence we won't be able to run the tests on the same.
