### ISSUE TITLE
Update packages to support Azure Blob Storage

### ISSUE THREAD

**Issue by ShourieG** [elastic/integrations#4376]
Certain packages require to be updated with support for azure-blob-storage. 

- [Auth0](https://auth0.com/docs/customize/extensions/export-log-events-with-extensions/export-logs-to-azure-blob-storage)
- Azure - research required which services support log streaming to blob storage (if any)
- Cloudflare Log Push - supports Azure Blob, but SAS tokens are required and needs to be added our input
- [Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/raw-data-export-storage?view=o365-worldwide)

**Comment by narph** [comment]
need to check if the azure input supports SAS tokens and implement this functionality

**Comment by jamiehynds** [comment]
Closing this one until we see stronger demand for Azure Blob support for these integrations.
