### ISSUE TITLE
[cisco_ise] TLS encrypted syslog inputs

### ISSUE THREAD

**Issue by jlim0930** [elastic/integrations#4378]
Currently integration only supports TCP & UDP inputs only for Cisco ISE integration.  This is not secure.  Need to be able to send the logs to a TLS encrypted endpoint.

**Comment by andrewkroh** [comment]
Is this a request to enhance the `cisco_ise` integration to allow the configuration of TLS options on the TCP input?

**Comment by legoguy1000** [comment]
It already does https://github.com/elastic/integrations/blob/main/packages/cisco_ise/manifest.yml#L48

**Comment by andrewkroh** [comment]
Assuming the answer the question is yes and closing since it is supported as demonstrated in #4422.
