### ISSUE TITLE
the Agent host.mac field does not respect ECS RFC 7042 format 

### ISSUE THREAD

**Issue by zez3** [elastic/integrations#4385]
Hello Elastics,

all of my mac address fields are formatted according to https://www.elastic.co/guide/en/ecs/current/ecs-client.html#field-client-mac 
respecting the ECS and RFC 7042
but the Agent is delivering host.mac in a different colon separated format

Can someone please have a look and fix this

Thank you

**Comment by leehinman** [comment]
elastic/beats#32265 should fix the issue and be released in 8.5

**Comment by zez3** [comment]
indeed, this has been fixed
