### ISSUE TITLE
[Network Packet Capture] Upgrade is broken

### ISSUE THREAD

**Issue by philippkahr** [elastic/integrations#4406]
Hi

When I try to upgrade the Network packet capture integration, it deletes all the values out of the `ports` list. I didn't do any customisation. Just wanted to upgrade to a newer version. 

https://user-images.githubusercontent.com/12175559/194277998-6605c344-f003-4209-9ba4-3ca77d29a8d1.mov

**Comment by efd6** [comment]
@philippkahr The upgrade in the video is from v0.9.0 to v1.4.1 which goes from tech preview to GA and includes major changes in how configuration is handled by the integration including the type that the ports field maps as, so I'm not completely surprised that this would not work. Do you see the same behaviour if you upgrade from a GA version to a later GA version?
