### ISSUE TITLE
Common fields for Orchestrators

### ISSUE THREAD

**Issue by masci** [elastic/integrations#442]
This is a meta issue to track the work related to defining the common fields for the `orchestrator` schema. 

The output should be a set of required and recommended fields to be added to any event related to containers orchestrators.

**Comment by kaiyan-sheng** [comment]
kubernetes common fields: https://github.com/elastic/beats/issues/23725

**Comment by masci** [comment]
Orchestrators RFC https://github.com/elastic/ecs/pull/1230
