### ISSUE TITLE
MSSQL enhancements: Named Instance support and separation of databases/instance metrics

### ISSUE THREAD

**Issue by lalit-satapathy** [elastic/integrations#4431]
- Named Instance support
  - Refer https://github.com/elastic/integrations/issues/4257
- metrics mapping to instance or database
  - Refer https://github.com/elastic/integrations/issues/4259

**Comment by muthu-mps** [comment]
The named instance connection is working fine. The SQL Server browser service listens for incoming connections to a named instance. This uses the UDP port 1434 and it should be open in the Inbound rule.

Connection String: `"sqlserver://user:pass@host/MSSQLSERVER01"`

**Comment by muthu-mps** [comment]
The support for named instance is enabled with #4257. The connection can be established either for default (no-name) instance and named instance by providing the host details of the instance.

**Comment by muthu-mps** [comment]
#4259 - Picking this as a part of 8.7 release.
