### ISSUE TITLE
MSSQL enhancements: support a list of "Dynamic Counter Name"

### ISSUE THREAD

**Issue by lalit-satapathy** [elastic/integrations#4432]
Explore support a list of "Dynamic Counter Name" can be passed instead of just one

**Comment by lalit-satapathy** [comment]
Meta issue: https://github.com/elastic/integrations/issues/4238

**Comment by Danouchka** [comment]
Hello 

I have listed the performance counters below, that does not seem to be instance related. 
I have added %pool%,%block%,%buffer%,%locks% in the integration dynamic counter field

If those counters below are 0, are they reported as 0 or not reported at all ? 

Many thanks for your answers, Dan 


[root@sa-da-webserver ~]# sqlcmd -S localhost -U SA -P sqlMS200675# -Q "SELECT object_name, counter_name, instance_name, cntr_value, cntr_type FROM sys.dm_os_performance_counters where counter_name like '%locks%'"
object_name                                                                                                                      counter_name                                                                                                                     instance_name                                                                                                                    cntr_value           cntr_type
-------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- -------------------- -----------
SQLServer:General Statistics                                                                                                     Mars Deadlocks                                                                                                                                                                                                                                                                       0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          Xact                                                                                                                                                0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          RowGroup                                                                                                                                            0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          OIB                                                                                                                                                 0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          AllocUnit                                                                                                                                           0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          HoBT                                                                                                                                                0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          Metadata                                                                                                                                            0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          Application                                                                                                                                         0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          RID                                                                                                                                                 0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          Extent                                                                                                                                              0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          Key                                                                                                                                                 0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          Page                                                                                                                                                0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          Object                                                                                                                                              0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          File                                                                                                                                                0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          Database                                                                                                                                            0   272696576
SQLServer:Locks                                                                                                                  Number of Deadlocks/sec                                                                                                          _Total                                                                                                                                              0   272696576
SQLServer:Memory Manager                                                                                                         Lock Blocks Allocated                                                                                                                                                                                                                                                             3550       65792
SQLServer:Memory Manager                                                                                                         Lock Owner Blocks Allocated                                                                                                                                                                                                                                                       5550       65792
SQLServer:Memory Manager                                                                                                         Lock Blocks                                                                                                                                                                                                                                                                          0       65792
SQLServer:Memory Manager                                                                                                         Lock Owner Blocks                                                                                                                                                                                                                                                                    0       65792
SQL Server 2017 XTP IO Governor                                                                                                  Log Blocks/sec                                                                                                                   MSSQLSERVER                                                                                                                                         0   272696320

**Comment by ritalwar** [comment]
If I understand your question correctly, I can see that they are reported as 0.
![image](https://github.com/elastic/integrations/assets/102972658/813af50e-97e6-48b3-848b-76faac477212)
<img width="622" alt="Screenshot 2023-05-16 at 3 35 34 PM" src="https://github.com/elastic/integrations/assets/102972658/5f23f3a3-b796-49ce-99f4-8dcaf2eb4116">
![image](https://github.com/elastic/integrations/assets/102972658/388ee66f-7b85-4e2a-9c38-8edd0294a7e0)

**Comment by Danouchka** [comment]
Hi @ritalwar 
this is exactly what I want but I dont see those metrics 
I have put in my integration **%pool%,%block%,%buffer%,%lock%**
Is this the right configuration or did I make a mistake here ?

**Comment by ritalwar** [comment]
Hi @Danouchka, In MSSQL, the LIKE operator does not support multiple pattern matching using comma-separated values. We need to explore alternatives using regular expressions, to match all these patterns in a single query.
https://learn.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-ver15

**Comment by Danouchka** [comment]
Thank you very much for the answer, I added a 2nd integration

**Comment by lalit-satapathy** [comment]
> Hi @Danouchka, In MSSQL, the LIKE operator does not support multiple pattern matching using comma-separated values. We need to explore alternatives using regular expressions, to match all these patterns in a single query. https://learn.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-ver15

Can we update document for the same, Please create an issue backlog.

**Comment by Danouchka** [comment]
Hi @lalit-satapathy , as I have said,
for now I am adding a 2nd sql integrations to cover another dynamic counter pattern. 
if  **%pool%,%block%,%buffer%,%lock%** does not work, maybe we could have several row fields instead in the same integration. This way we could add %pool% , %block% etc ...separately

**Comment by lalit-satapathy** [comment]
@Danouchka, 

How many counters you have in total? 

- If you want all you, can always pass `"%"`
- If you want to restrict to a smaller subset (%pool%,%block%,%buffer%,%lock%) try syntax supported by MS-SQL like [pattern](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-ver15). This below should roughly match yo what you need but few extras, which you should not care.
    - `%[pbl][olu][ofc][lcfk]%`
