### ISSUE TITLE
[application_insights] app state overview dashboard does not work OOTB 

### ISSUE THREAD

**Issue by tommyers-elastic** [elastic/integrations#4446]
There are some issues in the app_state and app_insights datastreams which are causing empty visualizations in the OOTB dashboard. 

As part of the changes here we should also ensure that the app_state datastream is using the base app_insights metricset, not the app_state lightweight module. 

If an ingest pipeline is required to map the metric names, pipeline tests are required.

**Comment by gpop63** [comment]
There are 2 fields used in the dashboard: `azure.dimensions.exception_type` and `azure.dimensions.browser_timing_url_path` which I've never seen present in the events.
