### ISSUE TITLE
LastPass Dashboard Spelling and Grammar Errors

### ISSUE THREAD

**Issue by iamhowardtheduck** [elastic/integrations#4460]
Spelling and grammar errors with LastPass Dashboard from version 8.4.3, please see below in the Dashboard Changes section:

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations
Spelling error with User Dashboard, should be "weak" not "week"
![image](https://user-images.githubusercontent.com/11168913/195623288-94e7e3b7-4dc2-4d6d-85b7-49c9c1c7d5c8.png)

Grammar error with Deleted Shared Folder dashboard, should be "Number of Shared Folders" not "Number of Shared Folder"
![image](https://user-images.githubusercontent.com/11168913/195623594-619dad11-130b-4227-94f8-2daeba04d4c7.png)

**Comment by jamiehynds** [comment]
Hi @iamhowardtheduck - the 'Dashboard Changes' section seems to be missing, so we can't see the spelling/grammar errors. Would you mind adding?
