### ISSUE TITLE
Tag few integrations under the new `infrastructure` category

### ISSUE THREAD

**Issue by ManojS-shetty** [elastic/integrations#4469]
Please tag the below list of integration under the new category `infrastructure`.

| Packages | 
| ---------  |
| activemq  | 
| apache |
| couchbase| 
| couchdb| 
| etcd| 
| hadoop |  
| haproxy | 
| http_endpoint | 
|ibmmq|
| websphere_application_server |
| iis |
| kafka |
| memcached |
| mongodb |
| microsoft_sqlserver |
| mysql |
| nagios_xi |
| nginx |
| oracle |
| postgresql |
| rabbitmq |
| redis |
| redisenterprise |
| traefik |
| vsphere |
| zookeeper |

References: https://docs.google.com/document/d/1Ha-rqDbMAYIt8KIU-E6dZqU4WyQ0AjbeiY3lKxeP7nc/edit

Github issue associated: https://github.com/elastic/package-spec/issues/381

**Comment by ManojS-shetty** [comment]
CC: @SubhrataK

**Comment by LL6688** [comment]
@ManojS-shetty  is this merged?

**Comment by LL6688** [comment]
@rameshelastic , fyi
