### ISSUE TITLE
[Meta] [Security External Integrations] Update package format version to `2.0.0` 

### ISSUE THREAD

**Issue by narph** [elastic/integrations#4518]
New package format version is available (2.0.0) and introduces additional validations.

Initial code change requires updating `format_version` to `2.0.0` in the security package manifests.

This could trigger validation issues and contains breaking changes, more on troubleshooting here https://github.com/elastic/elastic-package/blob/main/docs/howto/update_major_package_spec.md

Potentially automate the update process if the number of changes turns out to be too big.

@jsoriano any restrictions here?

**Comment by efd6** [comment]
@andrewkroh's [ecs-update](https://github.com/andrewkroh/go-examples/tree/main/ecs-update) could easily be bent to do this since it already {de,re}-serialises the packages' manifests.

**Comment by andrewkroh** [comment]
Closing. Package are on to 3.0.0 now. #7810
