### ISSUE TITLE
end of the stream or a document separator is expected at line 13, column 1: 

### ISSUE THREAD

**Issue by zez3** [elastic/integrations#4525]
syslog enable in policy UI not working with custom processors 

Steps to reproduce:

Use a custom UDP integration, enble syslog in UI and a add a simple processor in advanced options
Try to save this policy.
An error will occur

```
end of the stream or a document separator is expected at line 13, column 1:
 ```

Workaround:
Disable the UI option and use the syslog processor directly in the advanced option section together with other processors there.

For confirmed bugs, please report:
- Version: Elastic stack 8.4.3
- Operating System: Ubuntu
- Discuss Forum URL: n/a

**Comment by leehinman** [comment]
This looks like an issue with the YAML that is produced when processors are defined.  Specifically in the udp.yml.hbs file:

```
{{#if processors}}
processors:
{{#if syslog}}
  - syslog:
      {{syslog_options}}
{{/if}}
{{processors}}
{{else if syslog}}
processors:
  - syslog:
      {{syslog_options}}
{{/if}}
```

If {{processors}} exists it won't get added with the same indentation as the `  - syslog` processor.

**Comment by taylor-swanson** [comment]
This also affects the custom TCP integration as well. I do a sweep over the rest of the hbs files to see if any other processor blocks are affected.
