### ISSUE TITLE
[Kubernetes][Dashboards] Nodes Panel does not completely work for cloud providers

### ISSUE THREAD

**Issue by ChrsMark** [elastic/integrations#4537]
The following dashboard does on work on cloud providers:

<img width="2556" alt="190446028-cb33fdd2-4a01-4bcd-b059-011b38ae1419" src="https://user-images.githubusercontent.com/11754898/199498190-9f82194d-3cff-4a4f-9539-8aaea8f3337c.png">

It seems that the labels the broken visualization relies on do not exist in all cases.

Issue valid on:

- [GKE](https://github.com/elastic/observability-dev/issues/2408)
- ...

**Comment by tetianakravchenko** [comment]
for AWS - `Node Informations by Labels` chart is empty as well

**Comment by ChrsMark** [comment]
Thanks for the feedback here. I will have a look to see how we can tackle this or even remove the breaking field.
