### ISSUE TITLE
MSSQL Integration (for Audit Logs)

### ISSUE THREAD

**Issue by muralidharanvenkataraman** [elastic/integrations#4538]
Hi there,

We have installed MSSQL Server Integration version 1.4.0.  When we enable the log integration (new feature with 1.4.0) to collect SQL Server error logs, we found that two lines were merged into a single line.   We figured out that it was due to the encoding and by adding this line to the config.yml file, the logs were parsed correctly.

encoding: utf-16le

a) Is there a possibility to add this as option within the integration UI
b) Support the ability to ignore files older than a certain time frame

Thanks
Murali

**Comment by efd6** [comment]
@muralidharanvenkataraman I don't see "utf-16le" in the list of valid encodings. Did you use "utf-16le-bom"?

**Comment by muralidharanvenkataraman** [comment]
@efd6 - I looked at the file encoding using notepad and it is set as UTF-16 LE BOM. 

I also found this in the elastic forum -> https://discuss.elastic.co/t/found-encoding-issue-with-filebeat-ms-sql-module/315351

Thanks
Murali

**Comment by wbaker23** [comment]
> Hello,
> 
> Don't know if this is the right place to post or if I should open a new issue but while using the MSSQL integration if I try to set the encoding as "utf-16le-bom" the logs are no longer ingested. I have to clear the encoding field to get the log back into elastic. But, with all the double lines and weird chars all over the place. I'm using v2.1.1 of the integration and elastic 8.8.2.
> 
> Any idea on what I am obviously doing wrong ?
> 
> Thanks -jeff.

@jeffest I'm resurrecting a very old thread but did you ever figure this out? I'm seeing the same behavior.
