### ISSUE TITLE
[Custom Logs Integration] Change default dataset name to `log.log`

### ISSUE THREAD

**Issue by kesslerm** [elastic/integrations#4539]
The default dataset name for the Custom Logs Integration is currently `generic`. This should be changed to `log.log`, to synchronise the generated index names with the fleet managed index templates and ingest pipeline.

Based on the package name `log`, and the package datastream name `log` fleet generates the `logs-log.log` index template, the `logs-log.log@package` and `logs-log.log@custom` component templates, and the `logs-log.log-1.0.0` ingest pipeline. The template applies to the `logs-log.log-*` index pattern.

In its default configuration, the [dataset name is `generic`](https://github.com/elastic/integrations/blob/dd312c59870e41849c07e2ce89d809e0d9e4b621/packages/log/data_stream/log/manifest.yml#L16). This leads to the default data stream being called `logs-generic`. The index templates installed by the integration do not apply to this data stream.

As a workaround, the user can currently change `generic` to `log.log` and benefit from the index templates and ingest pipeline.

The current behaviour may be intentional (if a bit confusing). There is an open case (https://github.com/elastic/package-spec/issues/26) to allow for packages that don't install their own templates, as it doesn't make sense to have a single template / ingest pipeline preinstalled if the user can and will have multiple instances of the log integration for a variety of non-overlapping use cases. This requires some more discussion, IMO.

**Comment by hop-dev** [comment]
I agree this was broken before.

From kibana 8.8 the custom logs package has moved to an "input only" package. This means that no index templates will be created on package install, then when the user selects a dataset we will create the index templates etc at package policy creation time so they will always match up. So the default value will no longer be an issue. 

I will close this issue now if you don't mind. Thanks!
