### ISSUE TITLE
Enable Kube-state Metrics dataset in kubernetes Integration by default

### ISSUE THREAD

**Issue by gizas** [elastic/integrations#4548]
Goal:
----
We want to enable kube-state metrics dataset in Kubernetes Integration. 

Requirements:
---
- Update relevant kubernetes package
- Test behaviour of integration when kube-state dataset is enabled and we have not installed the kube-state metrics library in the kubernetes cluster we monitor
- Identify any log entries that mark that kube-state metrics endpoint is missing
- Update documentation for any findings

**Comment by formgeist** [comment]
@gizas I found this issue through the onboarding initiative, but I was wondering if this new default setting is supposed to be showing in the package configuration already within the integrations UI for the latest Kibana snapshot? I don't see it being enabled by default yet. cc @mlunadia 

<img width="779" alt="image" src="https://user-images.githubusercontent.com/4104278/203732078-e952084e-dbe6-4f86-844c-494282d05256.png">

**Comment by gizas** [comment]
Hello @formgeist,

See [here](https://github.com/elastic/integrations/pull/4646/files#diff-d20d8086b58468701d8a944fc3ead31ddcc098054affdcc335b69464b4c16c54R4) that the enablement has been introduced in version >=1.28.0 

Screenshot from version 1.27.1

![1 27 0](https://user-images.githubusercontent.com/1685415/203764876-7f1071b6-5a9e-4af3-a64d-3d150d02f2a9.png)


Screenshot from version 1.29.1

![1 29 1](https://user-images.githubusercontent.com/1685415/203764903-9eb77a48-7eec-4ee1-aabf-6dedd24f8dc7.png)

Please make sure that you go to Integrations>Kubernetes>Settings and upgrade to latest version

**Comment by formgeist** [comment]
@gizas Thanks for confirming the version for me. I found that the Kibana snapshots are not using the latest package versions, so I'm investigating why that is.
