### ISSUE TITLE
[Kubernetes][Dashboards] Nodes > Memory usage by Node - Not correct data

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#4577]
Memory usage by Nodecan should usage > 100%
<img width="2550" alt="Screenshot 2022-11-04 at 17 43 43" src="https://user-images.githubusercontent.com/28299531/200340337-443e7dd6-56e8-418d-9cc1-aa00951466f6.png">

**Comment by gsantoro** [comment]
Same issue in AKS

**Comment by iamjosh007** [comment]
what about CPU usage by nodes, it has similar formula, this should be capacity instead of allocatable cores? 

average(kubernetes.node.cpu.usage.nanocores)/(max(kubernetes.node.cpu.allocatable.cores)*1000000000)
