### ISSUE TITLE
Testing for the Jolokia Input package

### ISSUE THREAD

**Issue by ishleenk17** [elastic/integrations#4583]
Add testing for the Jolokia input. 
Currently, system testing is not supported in the elastic-package. Once this [dependency](https://github.com/elastic/package-spec/issues/361) is resolved, we can take this up.

**Comment by lalit-satapathy** [comment]
Assuming this can be done now?

**Comment by ishleenk17** [comment]
Duplicate of : https://github.com/elastic/integrations/issues/5341
