### ISSUE TITLE
GCP Audit Logs Integration v2.14.0 - Ingest Pipeline fails 

### ISSUE THREAD

**Issue by anrsec** [elastic/integrations#4589]
Due to an error in a "Convert" processor, the ingest pipeline fails to properly parse and map the log fields:

![image](https://user-images.githubusercontent.com/61625853/200588871-8d8c276d-1d6e-45cf-8107-68134ef02df8.png)

For example, `json.protoPayload.methodName` should have been mapped to `event.action` but didn't happen when the following field was present:
`error.message: 'private' is not an IP string literal.`

This can be fixed by changing an existing `Convert` Processor from `logs-gcp.audit-2.14.0` managed ingest pipeline to the following:

![image](https://user-images.githubusercontent.com/61625853/200589655-31550d80-475d-4ede-9dac-644191476e18.png)

**Comment by efd6** [comment]
@rediasec Can you provide a sanitised `event.original` from a failing event so that this can be investigated.

**Comment by rediasec** [comment]
```
{"insertId":"7dc9850e-a52e-4ef2-930b-c5db435cdcb0","labels":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"system:redacted\" of ClusterRole \"system:redacted\" to User \"system:redacted\""},"logName":"projects/redacted/logs/cloudaudit.googleapis.com%2Factivity","operation":{"first":true,"id":"7dc9850e-a52e-4ef2-930b-c5db435cdcb0","last":true,"producer":"k8s.io"},"protoPayload":{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","authenticationInfo":{"principalEmail":"system:redacted"},"authorizationInfo":[{"granted":true,"permission":"io.k8s.coordination.v1.leases.update","resource":"coordination.k8s.io/v1/namespaces/redacted/leases/redacted","resourceAttributes":{}}],"methodName":"io.k8s.coordination.v1.leases.update","requestMetadata":{"callerIp":"private","callerSuppliedUserAgent":"redacted/v0.0.0 (linux/amd64) kubernetes/$Format","destinationAttributes":{},"requestAttributes":{}},"resourceName":"coordination.k8s.io/v1/namespaces/redacted/leases/redacted","serviceName":"k8s.io","status":{}},"receiveTimestamp":"2022-11-08T05:59:58.298462161Z","resource":{"labels":{"cluster_name":"redacted","location":"redacted","project_id":"redacted"},"type":"k8s_cluster"},"timestamp":"2022-11-08T05:59:57.114227Z"}
```

**Comment by oliver-creed** [comment]
Any news on this one i see the same thing?

**Comment by rediasec** [comment]
I confirm that I'm seeing the same issue in 2.16.0

**Comment by leandrojmp** [comment]
Just got the same issue and following @anrsec suggestion I edited the `convert` processor.

The only difference is that I'm using this conditional:

```
ctx.json?.protoPayload?.requestMetadata?.callerIp != null && !['gce-internal-ip', 'private'].contains(ctx.json?.protoPayload?.requestMetadata?.callerIp)
```

From [google documentation](https://cloud.google.com/logging/docs/reference/audit/auditlog/rest/Shared.Types/AuditLog), it seems that the `callerIp` field can have, besides an IP address, the values `gce-internal-ip` or `private`.

> The IP address of the caller. For a caller from the internet, this will be the public IPv4 or IPv6 address. For calls made from inside Google's internal production network from one GCP service to another, callerIp will be redacted to "private". For a caller from a Compute Engine VM with a external IP address, callerIp will be the VM's external IP address. For a caller from a Compute Engine VM without a external IP address, if the VM is in the same organization (or project) as the accessed resource, callerIp will be the VM's internal IPv4 address, otherwise callerIp will be redacted to "gce-internal-ip"

I can make a PR with this fix.

**Comment by leandrojmp** [comment]
Added the PR with the suggested change by @anrsec 

```
ctx.json?.protoPayload?.requestMetadata?.callerIp != null && ctx.json?.protoPayload?.requestMetadata?.callerIp != "gce-internal-ip"  && ctx.json?.protoPayload?.requestMetadata?.callerIp != "private"
```
