### ISSUE TITLE
Look for replacement for kibana-vis-editors codeowners

### ISSUE THREAD

**Issue by jsoriano** [elastic/integrations#4600]
It seems that @elastic/kibana-vis-editors team doesn't exist anymore, but they are the codeowners of some files in this repo. Look for a replacement and replace references to this team.

@flash1293 do you know what team can take care of these files now?

**Comment by flash1293** [comment]
Should be changed already by https://github.com/elastic/integrations/pull/4550 - where is it still saying vis-editors?

**Comment by jsoriano** [comment]
Ah sorry, I saw it in an open PR (https://github.com/elastic/integrations/pull/4543/files), but it must be outdated. Thanks!
