### ISSUE TITLE
[Kubernetes][Dashboards] Proxy - Fixing empty visualisations

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#4607]
1. Is it expected that Proxy dashboard is missing from the list of linked dashboards?
<img width="1772" alt="Screenshot 2022-11-09 at 16 16 04" src="https://user-images.githubusercontent.com/28299531/200868488-dc560d4c-adc6-4fff-8439-a8f15e7570f2.png">

2. Proxy > `Proxy HTTP request duration [Metrics Kubernetes]` - no data on EKS

<img width="2552" alt="Screenshot 2022-11-08 at 10 13 42" src="https://user-images.githubusercontent.com/28299531/200868688-baa44eef-8353-48ae-9e04-ca728f75bda9.png">

<img width="1767" alt="Screenshot 2022-11-09 at 16 18 12" src="https://user-images.githubusercontent.com/28299531/200869016-c6244341-89fc-49f3-a00c-968a777c59f1.png">

**Comment by MichaelKatsoulis** [comment]
@tetianakravchenko, @gizas currently kubernetes proxy metricset is a bit broken as it collects some deprecated metrics and does not collect some other ones that are present in newer kubernetes versions. 
We need to fix it similar to apiserver and controller manager (https://github.com/elastic/integrations/pull/3825)
So until it is fixed it would be better to keep the link out.

**Comment by tetianakravchenko** [comment]
we already have issue to fix broken metrics - https://github.com/elastic/integrations/issues/4580.
