### ISSUE TITLE
[Kubernetes][Dashboards] API server - Fixing empty visualisations

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#4608]
API server > Apiserver Requests per Resource and SubResource [Metrics Kubernetes] - no data
<img width="1773" alt="Screenshot 2022-11-09 at 17 22 49" src="https://user-images.githubusercontent.com/28299531/200886399-4b95b095-d9a7-44ac-8e49-31ee1e1c7240.png">

reason: missing `kubernetes.apiserver.request.subresource` metric (strange thing that on 8.4 stack it provides data)

reproduced on EKS

**Comment by gsantoro** [comment]
On AKS with Kubernetes integration 1.29.0 and Elastic stack 8.5.0 everything seems to work

![Screenshot 2022-11-23 at 16 28 02](https://user-images.githubusercontent.com/2378291/203598583-6b9ea973-f4db-4663-968b-6f0495cfa6e6.png)

**Comment by gsantoro** [comment]
It is still a problem with Kubernetes integration 1.21.2 and Elastic 8.5. I am not sure if this is still relevant given the integration dashboards has been updated

![Screenshot 2022-11-23 at 16 35 15](https://user-images.githubusercontent.com/2378291/203600148-932b38ee-e60c-4c08-b47b-6ecfa55afece.png)

**Comment by tetianakravchenko** [comment]
I will check the latest version of the dashboard for EKS

**Comment by tetianakravchenko** [comment]
On AWS with the latest versions of kubernetes integration (1.29.2) and stack version 8.5.x, API Server dashboard works:
<img width="2554" alt="Screenshot 2022-12-27 at 11 10 41" src="https://user-images.githubusercontent.com/28299531/209651009-903941bc-dcc5-4b37-b5d4-cb2974009d2b.png">

I am going to close this issue.
