### ISSUE TITLE
Create new Prometheus Input package

### ISSUE THREAD

**Issue by gizas** [elastic/integrations#4615]
Input package specification is defined [here](https://github.com/elastic/package-spec/tree/main/spec/input)

The new input package tries to address flexible implementation for custom Ingest configurations for our customers based on preexisting modules . Basic advantages until now is the a) specification of custom dataset per input b) custom mappings 

Continuing discussion of https://github.com/elastic/integrations/issues/4271, Cloudnative plans to create a new Prometheus Input package based on the existing Prometheus Collector Module.  

Goal:
- Understand inner details of the new Input Specification
- Define custom mappings in the new input package
- Define custom dataset name per input and verify functionality
- Define custom ingest pipelines and verify functionality
- Promote beta version to production

**Comment by gizas** [comment]
@tetianakravchenko https://github.com/elastic/integrations/pull/4517

**Comment by StephanErb** [comment]
Has there been a discussion on how the Prometheus input can leverage TSDB? 

We would need to do something like this below, but I am not sure how the dynamic and unbounded number of labels will play together with `index.mapping.dimension_fields.limit`

```yaml
- name: prometheus
  type: group
  fields:
    - name: labels.*
      type: object
      object_type: keyword
      dimension: true 

```

I am curious what your thoughts are on this.
