### ISSUE TITLE
Validate Kubernetes Integration with TSDB

### ISSUE THREAD

**Issue by gizas** [elastic/integrations#4618]
TSDB feature has been introduced since 8.5.  Goal is to enable TSDB with latest Kubernetes Integration package and validate functionality of collection, ingestion and visualisation of Kubernetes resources. 

Relevant information can be found [here](https://github.com/elastic/kibana/issues/132818).

## Goal*
Validate Kubernetes Integration functionality and UX with TSDB feature enabled 

## TSDB very simple example

<details>

<summary>Steps to reproduce the example</summary>

1. Create TSDB index:
```console
PUT /testing-timeseries-mode
{
  "settings": {
    "index": {
        "routing_path": [
          "dimension-1",
          "dimension-2"
        ],
        "mode": "time_series"
    }
  },
  "mappings": {
    "properties": {
      "counter-field": { 
        "type": "integer",
        "time_series_metric": "counter"
      },
      "dimension-1": { 
        "type": "keyword",
        "time_series_dimension": true
      },
      "dimension-2": { 
        "type": "keyword",
        "time_series_dimension": true
      }
    }
  }
}
```
2. Try to add a document without any dimension (this is, no fields in the `routing_path`:
```console
POST testing-timeseries-mode/_doc/
{
  "@timestamp": "2099-11-15T13:12:00",
  "counter-field": 123
}
```
It should fail:
![image](https://user-images.githubusercontent.com/113898685/223703440-cec2f91b-17d3-4b95-923e-dcc8b4d770ef.png)
3. Adding a document with a unique combination between timestamp and dimension should work:
```console
POST testing-timeseries-mode/_doc/
{
  "@timestamp": "2099-11-15T13:12:00",
  "counter-field": 123,
  "dimension-1": "AA"
}
```
4. If we try to POST a document with the same dimension and timestamp, but with a different `counter-field` value, then it will fail because the combination already exists:
```console
POST testing-timeseries-mode/_doc/
{
  "@timestamp": "2099-11-15T13:12:00",
  "counter-field": 321,
  "dimension-1": "AA"
}
```
6. If we still use the same dimension and timestamp, but use a new dimension, the new combination will be (timestamp, dimension1, dimension2) and that means it is still unique. It should work without any problems.
```console
POST testing-timeseries-mode/_doc/
{
  "@timestamp": "2099-11-15T13:12:00",
  "counter-field": 321,
  "dimension-1": "AA",
  "dimension-2": "BB"
}
```
</details>

## Outcomes:
- Configure a TSDB Elastic Stack with our Kubernetes Integration. We will need to update 
- Verify functionality of Kubernetes Integration
  - Indexing Functionality
  - Kubernetes Dashboard functionality
- Validate our current `Dimension` fields, if they are accurate for TSDb configuration
- Validate any performance (storage savings, number of documents, performance of Dashboards/ queries). (This goal can be done in combination with the **K8s Scaling Performance story** - Link to TBD 
- For evaluation of performance we can use rally tool: 
    https://github.com/elastic/rally-tracks/tree/master/tsdb : Specific Track for TSDB
    https://github.com/elastic/k8s-integration-infra/tree/cloudnative/cloudnative : Track with data focused on K8s integration

Breaking the steps of the Story:
- [x] Understanding TSDB Design
- [TSDB design](https://github.com/elastic/elasticsearch-adrs/blob/master/analytics/tsdb/tsdb-design.md)
- [Time series datastream](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html#time-series-mode)
- [TSDB - Kibana behavior](https://docs.google.com/document/d/1ZLbabj0fKHai-d7MpA8dqnmGMe0_2Qb9hZFqfos0CNw/edit) 
- [TSDB migration](https://github.com/elastic/integrations/blob/main/docs/developer_tsdb_migration_guidelines.md)
- [x] Checking relevant Prototyping work: [1](https://github.com/elastic/observability-dev/issues/2541), [2](https://github.com/elastic/obs-infraobs-team/issues/904), [3](https://github.com/elastic/integrations/pull/2829), [4](https://github.com/jsoriano/package-spec/blob/59f38f7012af8fcae29e02277b5926313fc50af7/test/packages/time_series/data_stream/example/manifest.yml)
- [x] All metrics datastreams (https://github.com/elastic/integrations/pull/5464 and https://github.com/elastic/integrations/pull/5621):
   - [x] Set dimension fields in all Kubernetes metrics datastreams
   - [x] Toggle Option to enable TSDB in Integration UI (relevant [link](https://github.com/elastic/observability-dev/issues/2541#issuecomment-1397044131))
   - [x]  Validate UX when Kubernetes data already have been ingested inside Elastic Search and user enables TSDB feature. Searching in Discovery should be with no problems
  - [x] Retrieve basic metrics for storage, indexing time etc. with TSDB enabled
- [ ] Check that each pre defined dashboard works as expected
   - [x] Proxy: https://github.com/elastic/integrations/pull/5992
   - [x] Scheduler: https://github.com/elastic/integrations/pull/5992
   - [x] Controller manager: https://github.com/elastic/integrations/pull/5992
   - [ ] API Server
   - [x] Cronjob
   - [x] StatefulSet
   - [x] Volume
   - [ ] Pods
   - [x] Deployments
   - [x] Daemonset
   - [x] Job
   - [x] Nodes
   - [x] PV/PVC
   - [x] Cluster Overview
   - [x] Services

For the future:
- [ ] If TSDB mode is the default, then update all Kubernetes Datastreams with `index_mode: "time_series"`

**Comment by constanca-m** [comment]
I updated the description to include which data streams have the dashboards working @lalit-satapathy. I already open a PR to fix 3 of the 5 that were broken. I will start working on trying to fix the other 2.
