### ISSUE TITLE
Elastic Agent for Autopilot GKE clusters to support kubernetes observability

### ISSUE THREAD

**Issue by rameshelastic** [elastic/integrations#4620]
Since 8.5.0 we started a combined effort with Google to verify the dependencies needed to install Elastic Agent with Kubernetes Integration in order to monitor an Autopilot GKE cluster.

**Autopilot for GKE:**
https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview

Autopilot feature provisions and manages the GKE cluster's underlying infrastructure, including nodes and node pools, giving you an optimised cluster with a hands-off experience.

**Current challenge:**
Autopilot offers a secure protected environment to end users, meaning that it does not provide user access to specific resources (eg access to Cloud Control Plane is not allowed) and namespaces (eg creation of new pods under kube-system namespace) comparing to normal unmanaged Kubernetes clusters. Additional admission webhooks protect unauthorised creation of resources with configurations like mounting hostpaths, or editing existing namespaces.

That said, Elastic agent can not be installed in an Autopilot GKE cluster with our https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml manifest. 

**Goal**
We have started defining the requirements that we define in our manifests to install Agent in standalone deployment scenario

Current [doc](https://docs.google.com/document/d/16fVp6fzvVy-KA0gR_6xo5BRbLISNSimCmtd7jEl5pag/edit) captures combined effort and tests

An ECS cluster created and shared with Google team to assist them to their tests

**Outcomes**:
- Install Standalone Agent in the Autopilot GKE cluster 👍 done
- Validate monitoring of GKE cluster with our solution 👍 done
- Expand support to managed Agent scenarios 👍 done
- **[Future tbd]** Possibly integrate the Agent Installation with given Kubernetes Policy enabled in the UI steps of Autopilot installation. A new option to be available in the users choices when it tries to install an autopilot cluster ---- Still Marketplace does not support Autopilot clusters. to be considered when it is done

**Comment by gizas** [comment]
Status until 10 Nov: 

- We have defined modifiable/non modifiable parts of our manifest and shared with GCP 
- Validated mountpaths needed. Informations shared
- Shared modified manifests for standalone scenario
- Testing with Autopilot Rapid Channel version - Still GCP to verify that latest code is propagated and in which GKE version. We need to retest

**Comment by gizas** [comment]
Important note is that mountpoints of etc/*, hostfs/*, /var/lib/docker/containers have not been whitelisted from Google.

At the moment we agreed that we support only Kubernetes metrics and kubernetes container logs observability.

That said, google users will use Google's tools to observe system status.

**Comment by gizas** [comment]
Relevant documentation for redused manifests: https://github.com/elastic/elastic-agent/blob/autopilotdocumentaton/docs/elastic-agent-gke-autopilot.md

**Comment by gizas** [comment]
We can close this one for now as all actions of story were completed.
If more work is needed for the upcoming webinar of Google+Elastic, then we will track this work in a separate story inside 8.8
