### ISSUE TITLE
[CEF] Add TCP Support to the Common Event Format (CEF) Integration

### ISSUE THREAD

**Issue by Scriptception** [elastic/integrations#4643]
**Describe the enhancement:**
The CEF integration currently only supports listening on UDP. Can we get support for this integration to listen on TCP as well?

**Describe a specific use case for the enhancement or feature:**
Ingested CEF messages will be truncated if the length exceeds the UDP maximum. This is a severe roadblock to integrating logs via CEF into Elastic.

![Screenshot 2022-11-15 132810](https://user-images.githubusercontent.com/118245755/201837638-70f63fc4-7b57-4a1f-8e0b-51e17ab558b8.png)

**Comment by andrewkroh** [comment]
Closed by #5955
