### ISSUE TITLE
Integration has duplicate reference to @custom ingest pipeline 

### ISSUE THREAD

**Issue by jorsmatthys** [elastic/integrations#4650]
Integration name: Azure logs  (though might apply to others)
Version: 1.5.4

We are using the latest version of the Azure Logs integration and I see something which seems incorrect to me. 
Since recently the integrations now have support for custom ingest pipelines. We want to use the custom ingest pipeline 
for the azure spring cloud part of Azure Logs integration (to map certain non-ECS fields on ECS field).

The integration creates two managed ingest pipelines for Azure Spring Cloud (Azure Spring Apps).
A default pipeline and a pipeline that gets called within. 
![image](https://user-images.githubusercontent.com/67681021/201933688-80a573bb-c027-485f-b579-d3895f54ddd8.png)

If I look inside both pipelines, they both seem to be calling the `@custom` pipelines. Am I overlooking something here ? Or might this be undesirable/breaking in some cases ? 

At the end of the `logs-azure.springcloudlogs-1.5.4` pipeline: 
``` json
  {
    "pipeline": {
      "name": "logs-azure.springcloudlogs-1.5.4-azure-shared-pipeline"
    }
  },
  {
    "remove": {
      "field": "event.original",
      "if": "ctx?.tags == null || !(ctx.tags.contains('preserve_original_event'))",
      "ignore_failure": true,
      "ignore_missing": true
    }
  },
  {
    "pipeline": {
      "name": "logs-azure.springcloudlogs@custom",
      "ignore_missing_pipeline": true
    }
  }
```

At the end of the `logs-azure.springcloudlogs-1.5.4-azure-shared-pipeline` pipeline
``` json
  {
    "lowercase": {
      "field": "event.outcome",
      "ignore_missing": true
    }
  },
  {
    "pipeline": {
      "name": "logs-azure.springcloudlogs@custom",
      "ignore_missing_pipeline": true
    }
  }
```

Since the processors calling this pipeline do not appear to be present in the code (https://github.com/elastic/integrations/tree/main/packages/azure/data_stream/springcloudlogs/elasticsearch/ingest_pipeline).
I assume they are added dynamically, and that this behaviour might occur in other integrations as well ?

I tried searching the already existing issues and did not immediately see one covering this.

**Comment by zmoog** [comment]
Hey @jorsmatthys, thank you for submitting this report and for your patience! 

It's totally fine to mention me if you think you found something I can help with.  Reading through your comments 👀

**Comment by zmoog** [comment]
@jorsmatthys, I confirm the call for the custom pipeline is not in the source code. 

For the Azure Spring Cloud (Azure Spring Apps) logs, the pipeline source code is:
- [default.yml](https://github.com/elastic/integrations/blob/848f2991ffb3126fbd24407afaa6ebb2dd22bc3f/packages/azure/data_stream/springcloudlogs/elasticsearch/ingest_pipeline/default.yml) 
- [azure-shared-pipeline.yml](https://github.com/elastic/integrations/blob/848f2991ffb3126fbd24407afaa6ebb2dd22bc3f/packages/azure/data_stream/springcloudlogs/elasticsearch/ingest_pipeline/azure-shared-pipeline.yml)

**Comment by zmoog** [comment]
I ran some checks on my testing 8.6.2 cluster using the Azure Logs integration 1.5.13. 

Here's the default pipeline, from the data stream settings:

```
GET logs-azure.springcloudlogs-default/_settings
{
  ".ds-logs-azure.springcloudlogs-default-2023.04.17-000001": {
    "settings": {
      "index": {
        ...
        "default_pipeline": "logs-azure.springcloudlogs-1.5.13"
      }
    }
  }
}
```

After getting the default pipeline (`logs-azure.springcloudlogs-1.5.13`) content, I can see there is the call to the `logs-azure.springcloudlogs@custom` pipeline:

```
GET _ingest/pipeline/logs-azure.springcloudlogs-1.5.13
      ...
      {
        "pipeline": {
          "name": "logs-azure.springcloudlogs@custom",
          "ignore_missing_pipeline": true
        }
      }
```

I also checked the content of the shared pipeline:

```
GET _ingest/pipeline/logs-azure.springcloudlogs-1.5.13-azure-shared-pipeline
```

But in this pipeline, there are no calls to the custom pipeline.

***

I don't know what component adds the custom pipeline call in the default pipeline, but it is probably not the integration. 

What version of the Elastic stack are you using?

**Comment by jorsmatthys** [comment]
@zmoog 
Hi, thanks for having a look at this ! I am not sure if it has to be in the code of the pipeline itself to be honest, because I also do not see it in code for Azure platformlogs, but I can confirm that for platformlogs it works perfectly. And if you at the platformlogs pipeline in elastic, you can see that the call to the custom pipeline is there  (it perhaps gets appended by something ?).
* [default.yml](https://github.com/elastic/integrations/blob/848f2991ffb3126fbd24407afaa6ebb2dd22bc3f/packages/azure/data_stream/platformlogs/elasticsearch/ingest_pipeline/default.yml)

Our custom pipelines:
![image](https://user-images.githubusercontent.com/67681021/232478446-94e17a1c-af9d-4aaa-b8e5-2da158979edb.png)

Spring cloud/apps pipeline:
![image](https://user-images.githubusercontent.com/67681021/232478669-b8d881b2-49dc-451e-8eae-4499ad66d5dc.png)

Platform pipeline:
![image](https://user-images.githubusercontent.com/67681021/232478818-770cbdef-70ea-4a38-8cd4-ffa02d929885.png)

The platform pipeline custom pipeline is working for us, the Spring Apps one is not  :/.

**Comment by jorsmatthys** [comment]
@zmoog Ah my answer crossed your answer :) Ok I upgraded our test environment from 5.11 to 5.13 and I don't see it being called from the shared pipeline anymore there, as you say, this appear to have been corrected. 

I will verify if the custom pipeline is working as expected now and if it is I will bump our production version from 5.4 to 5.13 for the integration. 

Thanks a lot.

**Comment by zmoog** [comment]
After a quick check, I learned this problem was also reported as https://github.com/elastic/integrations/issues/4510 and fixed in Kibana with elastic/kibana#144150

**Comment by jorsmatthys** [comment]
@zmoog  Ah we did also recently upgrade the elk stack so I guess that would explain why it was now ok after installing a new version of the integration (because just upgrading the elk stack doesn't reload the pipelines of the integration I guess). 
My custom pipeline still is not working as expected for spring cloud, but since my assumption of the cause was wrong I will close this for now. I use the test data from the repo here to see if I can pinpoint where it goes wrong. Thanks again.

**Comment by zmoog** [comment]
> Ah we did also recently upgrade the elk stack so I guess that would explain why it was now ok after installing a new version of the integration (because just upgrading the elk stack doesn't reload the pipelines of the integration I guess).

Yeah, we need the stack version with the fix and a new integration upgrade to reload the pipeline to solve this issue. 

> I use the test data from the repo here to see if I can pinpoint where it goes wrong.

You can open a new issue to track your investigation and ping me, and I'll try to help.
