### ISSUE TITLE
[carbon_black_cloud] Support of encrypted AWS S3 bucket and KMS keys

### ISSUE THREAD

**Issue by RivianRascal** [elastic/integrations#4654]
There is currently no support for the usage of encrypted AWS S3 buckets with the Carbon Black Cloud Integration. I would like to request the possibility to work with encrypted AWS S3 buckets and AWS KMS keys. The feature would enable me/us to encrypt data at rest.

**Comment by mindl355** [comment]
Dear Elastic Team, @jamiehynds 

Could someone please assist me on how I can make use of encrypted S3 Buckets and the Carbon Black Integration?

AWS has made some changes where it is not possible anymore to use unencrypted S3 Buckets. I have created a case as well (#01177884) stating the issue I have.

Thank you very much.

**Comment by mindl355** [comment]
Dear team, @jamiehynds 

Do you have an estimate on when the Carbon Black integration will support encrypted buckets in AWS?

We are getting more and more customers and have to work with the workaround we have at the moment. But we would like to use the Carbon Black integration.

Thank you very much.

**Comment by mindl355** [comment]
@jamiehynds Thank you for your swift and detailed reply. I would have to investigate on this matter once more since it has been a few months I looked into it. I will plan to redo the steps in order to integrate encrypted buckets.

We have used SSE-KSM for our integration and yes your assumption is correct. We create a role, grant permission and specify the ARN as part of the role. However, what is missing from our point is to paste somewhat the key within the integration so that the Carbon Black Integration is aware of the encryption to decrypt the data.

I will plan to look into this hopefully soon and I will update you once I've done the setup. Currently we are using a self written script that calls the Carbon Black API and posts the alert data directly.

**Comment by mindl355** [comment]
hi @jamiehynds, I was able to get the API part running. that helps me a lot, thanks for your suggestion.

for the S3 buckets part I was able to perform the test once more. I followed all the instructions and using SSE-KSM, but I was not lucky to get it running. The data is flowing into the S3 bucket, but I'm not able to pull the data via the Elastic integration. could this be solved if I open a support ticket?

**Comment by taylor-swanson** [comment]
@jamiehynds, just as a heads up, it doesn't look like the AWS S3 beats input supports KMS keys currently. I'm checking to get a rough estimate on much effort is involved here.

**Comment by ebeahan** [comment]
I came across [this Knowledge article](https://repost.aws/knowledge-center/decrypt-kms-encrypted-objects-s3) from AWS that indicates:

> You don't need to specify the AWS Key Management Service (AWS KMS) key ID when you download an SSE-KMS-encrypted object from an S3 bucket. Instead, you need the permission to decrypt the AWS KMS key.

I did some testing and found that with the right IAM policies/permissions, the existing AWS S3 input does appear to decrypt the objects from S3.

<details>
<summary>Expand to see notes from testing</summary>

To test, I created simple scenario with an S3 bucket, enabled SSE-KMS, created the necessary IAM policy (`"kms:Decrypt"` ), and granting that IAM policy to creds used by the `type: aws-s3` input I defined:

Create the object in S3 bucket:

`$ aws s3api put-object --bucket s3-testing-kms --key dir1/tacocat2.txt --body tacocat.txt`

Response back from the PUT with the KMS key id:

```
{
    "ETag": "\"c23e945383f83fc64de2760a364c7ebe\"",
    "ServerSideEncryption": "aws:kms",
    "SSEKMSKeyId": "arn:aws:kms:us-east-2:528962165841:key/5155f83e-c2e2-4d73-87ac-f9ce31425fa3",
    "BucketKeyEnabled": true
}
```

The existing S3 input retrieved the new object:

```
{
  "@timestamp": [
    "2023-11-15T20:15:33.375Z"
  ],
  "agent.version": [
    "8.11.1"
  ],
  "aws.s3.bucket.arn": [
    "arn:aws:s3:::s3-testing-kms"
  ],
  "aws.s3.bucket.name": [
    "s3-testing-kms"
  ],
  "aws.s3.object.key": [
    "dir1/tacocat2.txt"
  ],
  "cloud.provider": [
    "aws"
  ],
  "cloud.region": [
    "us-east-2"
  ],
  "ecs.version": [
    "8.0.0"
  ],
# Removed host details for brevity #
  "input.type": [
    "aws-s3"
  ],
  "log.file.path": [
    "https://s3-testing-kms.s3.us-east-2.amazonaws.com/dir1/tacocat2.txt"
  ],
  "log.offset": [
    0
  ],
  "message": [
    "TACOCAT"
  ],
  "_id": "1122547a98-000000000000",
  "_index": ".ds-filebeat-8.11.1-2023.11.15-000001",
  "_score": null
}
```

If I remove the IAM permissions, the S3 poller on the input sees a 403 response from S3:

```
{"log.level":"warn","@timestamp":"2023-11-15T14:55:52.449-0600","log.logger":"input.aws-s3.s3_poller","log.origin":{"file.name":"awss3/s3.go","file.line":390},"message":"Failed processing S3 listing.","service.name":"filebeat","id":" 40D724C71621FD6","bucket":"arn:aws:s3:::s3-testing-kms","error":{"message":"failed processing S3 event for object key \"dir1/tacocat9.txt\" in bucket \"s3-testing-kms\": failed to get s3 object (elapsed_time_ns=76395542): s3 GetObject failed: operation error S3: GetObject, https response error StatusCode: 403, RequestID: NHX9H2939GPE5AXW, HostID: IIXJWTiZWcpdcPhOqnZplC06j5NhTLPzDYelyNYuJ9muGuf0pUeA6L8TgXYXh905fufL4SpAXxA=, api error AccessDenied: User: arn:aws:iam::528962165841:user/tacocat is not authorized to perform: kms:Decrypt on resource: arn:aws:kms:us-east-2:528962165841:key/5155f83e-c2e2-4d73-87ac-f9ce31425fa3 because no identity-based policy allows the kms:Decrypt action"},"ecs.version":"1.6.0"}
```

</details>

> for the S3 buckets part I was able to perform the test once more. I followed all the instructions and using SSE-KSM, but I was not lucky to get it running. The data is flowing into the S3 bucket, but I'm not able to pull the data via the Elastic integration. could this be solved if I open a support ticket?

@mindl355 Do you recall what errors you saw when you've testing in your environment? Perhaps we need to troubleshoot the IAM permissions assigned to the Carbon Black Cloud integration?

**Comment by mindl355** [comment]
@ebeahan Thanks for your testing.

Errors I wasn't able to see. I've tested a few configuration and following guidelines provided by Carbon Black to get it working with encrypted buckets. I just assume that it's not working if I don't see any data being ingested for endpoint events for example.

I've looked at the IAM permissions once more and checked that the assigned access key for the Carbon Black integration has the sufficient privileges such as kms:decrypt and that's how it has been set for a longer time.

Would you be available to set up a call where we could go through the settings?

**Comment by ebeahan** [comment]
Met with @mindl355 to review Carbon Black Cloud config and to troubleshoot. After testing and a bit of troubleshooting, discovered there were missing IAM permissions.

Filed https://github.com/elastic/integrations/issues/8693 to track adding better guidance specifically for `carbon_black_cloud` and also https://github.com/elastic/beats/issues/37387 to improve SSE-KMS guidance in the AWS S3 input docs: https://github.com/elastic/beats/issues/37387. Will close this issue and continue to track the documentation improvements in these separate, distinct issues.

**Comment by taylor-swanson** [comment]
@ebeahan, do we still need elastic/beats#37071 since this seems to be more of a documentation issue?
