### ISSUE TITLE
[oracle] Integration documentation for metrics is incorrect

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/integrations#4656]
The section on configuring metrics for the Oracle integration was copied almost directly from the `oracle` metricbeat module. It's important to note that the Oracle integration uses the `sql` metricbeat module and NOT the `oracle` module underneath. I'm not a subject-matter expect in Oracle databases, so I don't know how much of that information can carry over. At the very least, the section in the documentation on what host format to use is incorrect. It does appear that the `Old style host configuration` works, but the `DSN host configuration` does not. This has been an issue in at least one SDH.

```
# Old style host configuration:
hosts: ["user/pass@0.0.0.0:1521/ORCLPDB1.localdomain"]
hosts: ["user/password@0.0.0.0:1521/ORCLPDB1.localdomain as sysdba"]

# DSN host configuration. (does not work with sql metricbeat module):
user="user" password="pass" connectString="0.0.0.0:1521/ORCLPDB1.localdomain"
user="user" password="password" connectString="host:port/service_name" sysdba=true

# Oracle DSN (used by sql metricbeat module):
oracle://sys:Oradoc_db1@0.0.0.0:1521/ORCLCDB.localdomain?sysdba=1
```

Integration docs: https://github.com/elastic/integrations/tree/main/packages/oracle
SQL metricbeat module docs: https://www.elastic.co/guide/en/beats/metricbeat/8.5/metricbeat-module-sql.html
Oracle metricbeat module docs: https://www.elastic.co/guide/en/beats/metricbeat/8.5/metricbeat-module-oracle.html

**UPDATE**: The DSN issue mentioned above is caused by a bug within the sql module. It was fixed for the oracle module, but hasn't been fixed for the sql module, yet. Regardless, I still think it's a good idea to verify the information in the documentation is still valid.

# Related Issues
- elastic/sdh-beats#2742

**Comment by agithomas** [comment]
Until the https://github.com/elastic/beats/pull/32293 is rolled out, the DSN support for Oracle Integration must not be displayed. Working on to update the documentation

**Comment by agithomas** [comment]
PR Link : https://github.com/elastic/integrations/pull/4697

**Comment by lalit-satapathy** [comment]
@agithomas, Can this be closed now?

**Comment by chrisberkhout** [comment]
Closing now as it looks like this issue was indeed resolved a year ago in https://github.com/elastic/integrations/pull/4697.
