### ISSUE TITLE
[Stack Monitoring] Add missing metricbeat configuration to integrations

### ISSUE THREAD

**Issue by klacabane** [elastic/integrations#4666]
### Summary
The metricbeat modules ([elasticsearch](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-elasticsearch.html), [kibana](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-kibana.html),..) allows one to specify ssl configuration (`certificate_authorities`, `verification_mode`..) and other parameters like `period` or `scope`.

Since the [elastic integration](https://github.com/elastic/integrations/tree/main/packages/elasticsearch) spawns the metricbeat module under the hood, one should be able to set any accepted metricbeat parameters from the integration.

### Implementation hints
- The parameters are defined under the integration's manifest [vars block](https://github.com/elastic/integrations/blob/main/packages/elasticsearch/manifest.yml#L27)
- The parameters are then transformed into a metricbeat configuration in the data streams [stream.yml.hbs file](https://github.com/elastic/integrations/blob/main/packages/elasticsearch/data_stream/ccr/agent/stream/stream.yml.hbs)

See relevant PR that added the `scope` parameter: https://github.com/elastic/integrations/pull/3275

- [x] https://github.com/elastic/integrations/pull/4946
- [x] https://github.com/elastic/integrations/pull/4912
- [x] https://github.com/elastic/integrations/pull/4914
- [x] https://github.com/elastic/integrations/pull/4916

### AC
- All metricbeat parameters can be set from the integration form

**Comment by miltonhultgren** [comment]
We should also add support for API keys.

**Comment by klacabane** [comment]
Updated the issue to account for the other Stack Monitoring packages

**Comment by joshdover** [comment]
> We should also add support for API keys.

Did we end up doing this? I'm not seeing in my latest pull of `main`

**Comment by mohamedhamed-ahmed** [comment]
> > We should also add support for API keys.
> 
> Did we end up doing this? I'm not seeing in my latest pull of `main`

Hi @joshdover 
We have a [ticket](https://github.com/elastic/integrations/issues/4949) opened for this, but not picked up yet
