### ISSUE TITLE
Kubernetes integration with empty charts with kube-state-metrics in different namespace

### ISSUE THREAD

**Issue by endorama** [elastic/integrations#4667]
Hello, I've recently worked on a demo for [GCP Kubernetes App for Elastic Agent](https://github.com/elastic/elastic-agent-gcp-kubernetes-app) and had some troubles around configuring correct collection for the Kubernetes integration.

My setup: 
- GKE cluster v1.24.5-gke.600 with 7 nodes
- a dummy microservice app deployment
- Kubernetes integration v1.28.0
- `kube-state-metrics` v2.6.0 in `kube-system` (deployed straigth from `examples/standard` folder from `kube-state-metrics` repo)
- Elastic Agent 8.5.0 installed through the GCP Marketplace in `default` namespace

The initial investigation started from this dashboard:
![Screenshot from 2022-11-16 14-48-36](https://user-images.githubusercontent.com/526307/202198116-38de03f8-fc31-4e35-a584-bc920d7ae23d.png)

As you can see there are some empty charts, even if the deployment seemed to be working properly. I've been helped in this investigation by @gsantoro.

**Solution**

Deploy `kube-state-metrics` in the same namespace as Elastic Agent **or** configure Hosts setting in the integration policy.

I think this has to be clearly mentioned in the docs, as without deeper knowledge on our collection process this was unexpected and felt contradictory with the instruction of installing `kube-state-metrics`.

## Documents ingested with `error.message` but no error shown

The first thing that we discovered is that documents related to those graphs were being ingested but without the data we needed.
We discovered that ingested document had a `error.message` field reporting a collection error:
```
error.message | error getting families: error making http request: Get "http://kube-state-metrics:8080/metrics": lookup kube-state-metrics on 10.100.16.10:53: no such host
```
Full document for further inspection: [document-with-errormessage.json.txt](https://github.com/elastic/integrations/files/10022324/document-with-errormessage.json.txt) (as .txt due to GitHub upload limitations)

**No other visible error was being triggered for these errors**.

The Elastic Agent pods were not able to reach `kube-state-metrics`, even if the service was correctly deployed.
We identified the culprit in the Agent pods being deployed in `default` namespace while `kube-state-metrics` was deployed in `kube-system`. This difference from our usual deploy settings is due to GCP (probably, further investigation is being done here) preventing deployment of apps to `kube-system`.
In any case this feels a sensible limitation that cluster operators may want to enforce.

A sidenote here is that there is a block stating the need for `kube-state-metrics` but this possible issue about the namespace is has been deployed in is not mentioned:
![Screenshot from 2022-11-16 15-00-20](https://user-images.githubusercontent.com/526307/202200508-bdd76baa-5ab6-4df6-b401-065a77811f15.png)

## Reaching `kube-state-metrics` in a different namespace

We tested DNS resolution from Agent pods with `nslookup kube-state-metrics`, which gave a missing record.

Based on how DNS discovery works in K8s, this is expected, as per K8s docs ([Debugging DNS resolution - Are you in the right namespace for the service?](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#are-you-in-the-right-namespace-for-the-service)):
```
DNS queries that don't specify a namespace are limited to the pod's namespace.
```

This was confirmed by running `nslookup kube-state-metrics.kube-system` in the same pod, which correctly resolved the DNS.

Given this and that is possible to configure the Host to collect data from in the integration, we tried using `kube-state-metrics.kube-system:8080` as configuration value:
![Screenshot from 2022-11-16 15-08-15](https://user-images.githubusercontent.com/526307/202202198-2bbd574c-7f42-48b0-989e-d4455c8c9b7a.png)

Unfortunately this configuration did not work (but please continue reading) and we have not been able to troubleshoot why. The pod is correctly reaching the service (confirmed by `curl http://kube-state-metrics.kube-system:8080/metrics`, which is showing correct data) but **no data is ingested**.

Looking at logs on the leader pod we found a security exception:
```
{\"type\":\"security_exception\",\"reason\":\"action [indices:data/write/bulk[s]] is unauthorized for API key id [fugFgIQBC
uunaIEmGl7M] of user [elastic/fleet-server] on indices [metrics-system.process-default,.ds-metrics-system.process-default-2022.11.16-000001], this action is granted by the index privileges [create_doc,create,delete,index,write,all]\"}, dropping event!","service.n
ame":"metricbeat","ecs.version":"1.6.0"}
```

<details>
<summary>Full log line</summary>
<pre>
{"log.level":"warn","@timestamp":"2022-11-16T14:04:23.154Z","log.logger":"elasticsearch","log.origin":{"file.name":"elasticsearch/client.go","file.line":429},"message":"Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Date(2022, time.November,
 16, 14, 4, 22, 493931598, time.Local), Meta:{\"input_id\":\"system/metrics-system-fb89b9be-9992-4719-9528-bf400aa5ce72\",\"raw_index\":\"metrics-system.process-default\",\"stream_id\":\"system/metrics-system.process-fb89b9be-9992-4719-9528-bf400aa5ce72\"}, Field
s:{\"agent\":{\"ephemeral_id\":\"3bb053bc-89f0-4e43-9cc9-f1f2d66e7f54\",\"id\":\"e9b97c4a-894e-4804-9ffd-fe0fd0617a3a\",\"name\":\"gke-edoardo-gke-app-demo-default-pool-7e445b8b-g65s\",\"type\":\"metricbeat\",\"version\":\"8.5.0\"},\"cloud\":{\"account\":{\"id\":
\"elastic-observability\"},\"availability_zone\":\"europe-west8-a\",\"instance\":{\"id\":\"7442225956810265453\",\"name\":\"gke-edoardo-gke-app-demo-default-pool-7e445b8b-g65s\"},\"machine\":{\"type\":\"e2-medium\"},\"project\":{\"id\":\"elastic-observability\"},
\"provider\":\"gcp\",\"service\":{\"name\":\"GCE\"}},\"data_stream\":{\"dataset\":\"system.process\",\"namespace\":\"default\",\"type\":\"metrics\"},\"ecs\":{\"version\":\"8.0.0\"},\"elastic_agent\":{\"id\":\"e9b97c4a-894e-4804-9ffd-fe0fd0617a3a\",\"snapshot\":fa
lse,\"version\":\"8.5.0\"},\"event\":{\"dataset\":\"system.process\",\"duration\":33854917,\"module\":\"system\"},\"host\":{\"architecture\":\"x86_64\",\"containerized\":false,\"hostname\":\"gke-edoardo-gke-app-demo-default-pool-7e445b8b-g65s\",\"id\":\"54aaa636a
35031f5f1a110a785d8b579\",\"ip\":[\"10.198.0.17\",\"fe80::4001:aff:fec6:11\",\"169.254.123.1\",\"10.112.0.1\",\"fe80::a456:33ff:feb3:1311\",\"10.112.0.1\",\"fe80::9488:33ff:fe4a:2c7c\",\"10.112.0.1\",\"fe80::f8f7:e3ff:feff:a1a6\",\"10.112.0.1\",\"fe80::e493:a8ff:
fea2:4289\"],\"mac\":[\"02-42-65-3C-4B-C3\",\"42-01-0A-C6-00-11\",\"96-88-33-4A-2C-7C\",\"A6-56-33-B3-13-11\",\"E6-93-A8-A2-42-89\",\"FA-F7-E3-FF-A1-A6\"],\"name\":\"gke-edoardo-gke-app-demo-default-pool-7e445b8b-g65s\",\"os\":{\"codename\":\"focal\",\"family\":\
"debian\",\"kernel\":\"5.10.133+\",\"name\":\"Ubuntu\",\"platform\":\"ubuntu\",\"type\":\"linux\",\"version\":\"20.04.5 LTS (Focal Fossa)\"}},\"metricset\":{\"name\":\"process\",\"period\":10000},\"orchestrator\":{\"cluster\":{\"name\":\"edoardo-gke-app-demo\",\"
url\":\"https://10.198.0.6\"}},\"process\":{\"args\":[\"/app/cartservice\"],\"command_line\":\"/app/cartservice\",\"cpu\":{\"pct\":0.009,\"start_time\":\"2022-11-15T15:18:16.000Z\"},\"executable\":\"/app/cartservice\",\"memory\":{\"pct\":0.0106},\"name\":\"cartse
rvice\",\"parent\":{\"pid\":3100},\"pgid\":3633,\"pid\":3633,\"state\":\"sleeping\",\"working_directory\":\"/app\"},\"service\":{\"type\":\"system\"},\"system\":{\"process\":{\"cmdline\":\"/app/cartservice\",\"cpu\":{\"start_time\":\"2022-11-15T15:18:16.000Z\",\"
total\":{\"norm\":{\"pct\":0.009},\"pct\":0.0181,\"value\":1307920}},\"fd\":{\"limit\":{\"hard\":1048576,\"soft\":1048576},\"open\":224},\"memory\":{\"rss\":{\"bytes\":43819008,\"pct\":0.0106},\"share\":7376896,\"size\":2795155456},\"state\":\"sleeping\"}},\"user
\":{\"name\":\"root\"}}, Private:interface {}(nil), TimeSeries:true}, Flags:0x0, Cache:publisher.EventCache{m:mapstr.M(nil)}} (status=403): {\"type\":\"security_exception\",\"reason\":\"action [indices:data/write/bulk[s]] is unauthorized for API key id [fugFgIQBC
uunaIEmGl7M] of user [elastic/fleet-server] on indices [metrics-system.process-default,.ds-metrics-system.process-default-2022.11.16-000001], this action is granted by the index privileges [create_doc,create,delete,index,write,all]\"}, dropping event!","service.n
ame":"metricbeat","ecs.version":"1.6.0"}
</pre>
</details>

We were not sure how this error came to be, but our further investigation didn't bring up any other detail.

## Missing indices

To test if the previous error was due to out debugging efforts or some other inconsistency we created, I spun up a new Elastic Cloud cluster (same version), deleted the previous deployment of the GCP Kubernetes App and deployed a new one, configuring `kube-state-metrics.kube-system:8080` as Host for data collection.

This time it worked better. Documents were collected, but some indices were not created, as shown from this screenshot of the Cluster overview dashboard:
![Screenshot from 2022-11-16 15-36-28](https://user-images.githubusercontent.com/526307/202210014-d3fb19b4-5282-4d3d-9525-ca80ea9d6f88.png)

The same happens when deploying `kube-state-metrics` in the same namespace.
Is this due to not having any StatefulSet or CronJob in the cluster?

## `kube-state-metrics` configuration

There are 14 `Hosts` fields where I had to copy paste the new `kube-state-metrics` value. 

I don't know if it's possible to reduce them, but in this case having a single set of configuration used by all data streams would have helped and be less error prone.

**Comment by gsantoro** [comment]
@endorama  We are fully aware of those errors in the "Missing indices" section. It shouldn't be a error to don't have data about cronjob, stateful_set, and so on. The Kibana team is going to remove that error banner in favour of "No Data" in the dashboard instead. In the meantime we are working on a temporary fix. Stay tuned.
