### ISSUE TITLE
Update AWS integration documentation with risk in using the GetMetricData API calls

### ISSUE THREAD

**Issue by brenwie** [elastic/integrations#4674]
Hello Team

Could we get more clarity on the [AWS Integration guide](https://docs.elastic.co/integrations/aws), especially from a cost point of view that could be incurred on the AWS cloud account when using our Elastic Agent with this integration?  When the integration makes use of something like the [GetMetricData API](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_billing.html#:~:text=embedded%20custom%20metrics-,GetMetricData,-GetMetricData%20can%20also), this will incur charges on the AWS cloud account because AWS charges per API call made. 

Looking at the [Metricbeat AWS module documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-aws.html#:~:text=Extra%20AWS%20charges%20on%20CloudWatch%20API%20requests%20will%20be%20generated%20by%20this%20module), it is stated that using the GetMetricsData API would incur extra costs, where this is not so clear on the Elastic Agent AWS Integration guide.  On the Metricbeat AWS Module documentation, there is also a section on the [AWS API request count](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-aws.html#aws-api-requests) which could also be included on the AWS Integration guide which would give a good understanding as to how the API calls are utilized to retrieve data from AWS. 

Thank you

**Comment by bmorelli25** [comment]
@elastic/obs-cloud-monitoring can we copy the AWS API request count section into the integration docs? Does that content apply to the integration as-is, or are changes required?

**Comment by zmoog** [comment]
Hey @bmorelli25, as of today, the Elastic Agent leverages Filebeat and Metricbeat behind the scenes, so most, if not all, is valid for Metricbeat holds for the Agent.

Since Agent and Metricbeat share the same code, the cost depends on the configuration options. The collection period or the number of metrics influences are influential factors.
