### ISSUE TITLE
aws: cloudtrail data stream is missing field definition for event.ingested

### ISSUE THREAD

**Issue by skh** [elastic/integrations#473]
The ingest pipeline contained in the `cloudtrail` datastream of the `aws` integration uses the field `event.ingested`, but this field is not defined in any of the fields definition files.

Hence the corresponding index template does not contain a mapping for that field, so it defaults to `keyword`, which breaks searching.

This has been reported in https://discuss.elastic.co/t/fleet-aws-integration-error-cloudtrail-logs-not-searchable/258987

**Comment by andrewkroh** [comment]
User's version is 0.3.12.

**Comment by andrewkroh** [comment]
It's missing in the main branch too. The pipeline tests missed this which seems like a bug in the test. Despite ignoring the value of event.ingested while testing it should still be checked that the field is part of the fields.yml.

**Comment by kaiyan-sheng** [comment]
@andrewkroh I created a PR to simply adding the field into ecs.yml but I didn't fix the test. I will look into it later 🙂
