### ISSUE TITLE
[Synthetics] Monitors created with Synthetics Integration (directly or via private locations) do not contain location name

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/integrations#4735]
Integrations version: 0.11.3

When running Synthetics via the integrations, either directly or via private locations in Uptime, the location name is missing. 

<img width="1324" alt="Screen Shot 2022-11-29 at 5 27 22 PM" src="https://user-images.githubusercontent.com/11356435/204662249-7cdd8693-e9a9-4eea-ac4d-da72835db72c.png">

The location name for direct Synthetics integrations should be `Fleet managed`, and the location name for public locations should be the user-specified location name. 

In 0.11.3, we recently introduced the[ `run_from`](https://github.com/elastic/integrations/pull/4673/files) key. Heartbeat uses this key to determine what location a monitor is run from and index the data to `observer`. Previously, the integration exclusively relied on `fields_under_root` to define `observer.name`.

**Comment by b2ronn** [comment]
as a temporary workaround, created Ingest Pipelines
synthetics-browser.network@custom
synthetics-browser.screenshot@custom
synthetics-browser@custom
synthetics-http@custom
synthetics-icmp@custom
synthetics-tcp@custom

```
{
  "processors": [
    {
      "set": {
        "field": "observer.geo.name",
        "override": false,
        "ignore_failure": true,
        "copy_from": "observer.name"
      }
    }
  ]
}
```

**Comment by dominiqueclarke** [comment]
The fix has been deployed to our production package registry. The latest version of the Synthetics Integration package, which manages the `synthetics-*` data streams, is 0.11.4.

 Unfortunately, this fix will not be able to be applied for customers in **_airgapped environments_** upgrading to 8.5.3. 

Customers in **_airgapped environments_** upgrading to 8.5.3
--
To restore location information, you'll create a custom ingest pipeline.

Navigate to `app/dev_tools#/console` and run the following commands

```
PUT _ingest/pipeline/synthetics-browser.screenshot@custom
{
  "description": "Applies location name (observe.geo.name) to Synthetics documents",
  "processors": [
    {
      "set": {
        "field": "observer.geo.name",
        "override": false,
        "ignore_failure": true,
        "copy_from": "observer.name"
      }
    }
  ]
}

PUT _ingest/pipeline/synthetics-browser.network@custom
{
  "description": "Applies location name (observe.geo.name) to Synthetics documents",
  "processors": [
    {
      "set": {
        "field": "observer.geo.name",
        "override": false,
        "ignore_failure": true,
        "copy_from": "observer.name"
      }
    }
  ]
}

PUT _ingest/pipeline/synthetics-browser@custom
{
  "description": "Applies location name (observe.geo.name) to Synthetics documents",
  "processors": [
    {
      "set": {
        "field": "observer.geo.name",
        "override": false,
        "ignore_failure": true,
        "copy_from": "observer.name"
      }
    }
  ]
}

PUT _ingest/pipeline/synthetics-http@custom
{
  "description": "Applies location name (observe.geo.name) to Synthetics documents",
  "processors": [
    {
      "set": {
        "field": "observer.geo.name",
        "override": false,
        "ignore_failure": true,
        "copy_from": "observer.name"
      }
    }
  ]
}


PUT _ingest/pipeline/synthetics-tcp@custom
{
  "description": "Applies location name (observe.geo.name) to Synthetics documents",
  "processors": [
    {
      "set": {
        "field": "observer.geo.name",
        "override": false,
        "ignore_failure": true,
        "copy_from": "observer.name"
      }
    }
  ]
}

PUT _ingest/pipeline/synthetics-icmp@custom
{
  "description": "Applies location name (observe.geo.name) to Synthetics documents",
  "processors": [
    {
      "set": {
        "field": "observer.geo.name",
        "override": false,
        "ignore_failure": true,
        "copy_from": "observer.name"
      }
    }
  ]
}
```
`synthetics-*@custom` ingest pipelines are already applied by default to `synthetics-*` component templates. So you won't need to take any further steps to apply the newly created ingest pipelines.

All other customers on 8.5.x
--
Monitors created via Uptime Monitor Management
---
Navigate to `app/uptime/manage-monitors/all`. Toggle each one of your monitors on and off. This will apply the latest fix to the data stream settings.

Monitors created via the Synthetics Integration
---
Navigate to `app/fleet/agents`. That's it. Integration policies are designed to auto-upgrade when visiting the Fleet page, on version upgrades, or when Kibana is restarted. Once you navigate back to Uptime, you should see the fix applied shortly.
