### ISSUE TITLE
[Fleet]:  Not all Metrics dataset are available on Data Streams page for Linux integration.

### ISSUE THREAD

**Issue by simranvaseer-qasource** [elastic/integrations#4736]
**Kibana version:**  8.6 BC4 Kibana cloud environment 

**Host OS and Browser version:** **Ubuntu22**

**Build details:** 

``` 
VERSION: 8.6.0 BC4
BUILD: 58612
COMMIT: 218162f282314db5b3833c84752dd24395949b3f
Artifacts: https://staging.elastic.co/8.6.0-0f9567fc/summary-8.6.0.html
```

**Preconditions:**
1. 8.6 BC4 Kibana cloud environment should be available.
2. Linux Agent should be install with Linux integration.

**Steps to reproduce:**

1. Navigate to Kibana cloud environments
2. Edit Linux integration.
3. Enable all toggles at `Collect linux metrics from Linux instances` and 
`Collect low-level linux metrics from Linux instance`
4. Observe Not all Metrics dataset are available on Data Streams page for Linux integration.

**Expected Result:**
-  All Metrics dataset should be available on Data Streams page for Linux integration.

**Dataset not available:**
- **linux.users**

**Screenshot:**
What is not working fine.
![Untitled](https://user-images.githubusercontent.com/102019374/204764021-88f22747-709f-47ac-aa63-eebd9fe5d6e5.png)

![image](https://user-images.githubusercontent.com/102019374/204767945-fd9f8406-4e51-4e0c-9f4a-78b74b97bed0.png)

**Comment by dikshachauhan-qasource** [comment]
Secondary Review is done

**Comment by jen-huang** [comment]
See comment: https://github.com/elastic/elastic-agent/issues/1840#issuecomment-1332916011

**Comment by simranvaseer-qasource** [comment]
Hi @jen-huang 

We have revalidated this issue on latest 8.6 BC10 kibana Cloud environment and and found it is **working fine.**

Below Observations:
All Metrics dataset are available on Data Streams page for Linux integration. 

**Build Details:**
```
Version: 8.6.0 BC10
BUILD: 58852
COMMIT: d3a625ef4a6e611a5b3233a1ce5cbe8ef429eb47
Artifacts: https://staging.elastic.co/8.6.0-b6c773f9/summary-8.6.0.html
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/102019374/211485833-333b1c29-af8c-4408-ab36-73fe495c660c.png)

Hence, marking it as QA:Validated.
Thanks
