### ISSUE TITLE
[Fleet]: Logs dataset are not available on Data Streams page for Windows integration.

### ISSUE THREAD

**Issue by simranvaseer-qasource** [elastic/integrations#4737]
**Kibana version:**  8.6 BC4 Kibana cloud environment 

**Host OS and Browser version:** All, All 

**Build details:** 

``` 
VERSION: 8.6.0 BC4
BUILD: 58612
COMMIT: 218162f282314db5b3833c84752dd24395949b3f
Artifacts: https://staging.elastic.co/8.6.0-0f9567fc/summary-8.6.0.html
```

**Preconditions:**
1. 8.6 BC4 Kibana cloud environment should be available.
2. Agent should be added with Windows integration.

**Steps to reproduce:**

1. Navigate to Kibana cloud environments
2. Add Windows Integration 
3. Enable toggles at `Collect events from the following Windows event log channels`
4. Observe Logs dataset are not available on Data Streams page for Widows integration.

**Expected Result:**
-   Logs dataset should be available on Data Streams page for Widows integration.

**Dataset not available:**
- **windows.powershell_operational**
- **windows.powershell**

**Screenshot:**
What is not working fine.

![Untitled](https://user-images.githubusercontent.com/102019374/204761753-fd3d2085-cb9d-442c-a275-0ce076078aae.png)
![Untitled](https://user-images.githubusercontent.com/102019374/204762178-fb6518e4-4ba0-44e0-8749-d5d8c4461a52.png)

**Comment by dikshachauhan-qasource** [comment]
Secondary Review is done

**Comment by jen-huang** [comment]
See comment: https://github.com/elastic/elastic-agent/issues/1840#issuecomment-1332916011

**Comment by simranvaseer-qasource** [comment]
Hi @jen-huang 

We have revalidated this issue on latest 8.6 BC10 kibana Cloud environment and and found it is **working fine.**

Below Observations:
- Logs dataset are available on Data Streams page for Windows integration. 

**Build Details:**
```
Version: 8.6.0 BC10
BUILD: 58852
COMMIT: d3a625ef4a6e611a5b3233a1ce5cbe8ef429eb47
Artifacts: https://staging.elastic.co/8.6.0-b6c773f9/summary-8.6.0.html
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/102019374/211485646-df5b0088-efba-47bd-b148-e404875a7b83.png)

Hence, marking it as QA:Validated.
Thanks
