### ISSUE TITLE
[Okta] Integration can throw the error `field [event.original] already exists`

### ISSUE THREAD

**Issue by BenB196** [elastic/integrations#4782]
The okta Integration pipeline tries to rename `message` to `event.original`

https://github.com/elastic/integrations/blob/f9afcc0958180d8eb970a375d87de8d8fdf90864/packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml#L7-L9

This can cause issues with `event.original` is already set. Instead the integration should use something like a Set processor which has the ability to override the value

```json
{
  "set": {
    "field": "event.original",
    "ignore_empty_value": true,
    "copy_from": "message"
  }
}
```

**Comment by efd6** [comment]
@BenB196 Can you describe the set-up you have that sets `event.original` before the integration sees the document? We see this in filebeat when logstash is used, but I'd like to understand how you are seeing it with an integration.

**Comment by BenB196** [comment]
Hi @efd6 the setup for this is relatively similar to what you describe with Filebeat/Logstash: 

Elastic Agent Okta Integration -> Logstash Pre-processing Pipeline -> Elasticsearch Okta Integration Pipeline -> Elasticsearch Okta Integration `@custom` pipeline

**Comment by efd6** [comment]
@BenB196 OK, thanks. The PR above will fix that while leaving an error.message in the document letting you know that you should change the ECS compatibily setting.

**Comment by BenB196** [comment]
Thank for looking at this @efd6. Quick question about this statement:

> leaving an error.message in the document letting you know that you should change the ECS compatibily setting

My Logstash pipeline sets this at the input layer:

```
input {
    elastic_agent {
        # Input Specific Settings
        client_inactivity_timeout => 300 # 5 minutes
        ecs_compatibility => "v8"
        host => "0.0.0.0"
        port => 20001
        # SSL
        ssl => true
        ssl_certificate_authorities => ["/usr/share/logstash/config/ca.crt"]
        ssl_certificate => "/usr/share/logstash/config/elastic-agent-mtls/logstash.crt"
        ssl_key => "/usr/share/logstash/config/elastic-agent-mtls/logstash.pkcs8.key"
        ssl_verify_mode => "force_peer"
        # Generic Settings
        id => "elastic_agent_input"
        enable_metric => true
    }
}
```

My understanding is that this is the "correct" way of setting compatibility. Is this incorrect? There aren't really any mentions of the "correct" way to set compatibility in the Elastic Agent Logstash [docs](https://www.elastic.co/guide/en/fleet/8.5/secure-logstash-connections.html).

**Comment by efd6** [comment]
> My understanding is that this is the "correct" way of setting compatibility. Is this incorrect?

We would rather not have that happen. We are tracking an internal issue to address this.

**Comment by BenB196** [comment]
Just as a reference to anyone who comes across this (or similar) issue.

The issue appears to be that Logstash ECS compatibility automatically added `event.original` to all events, [source](https://discuss.elastic.co/t/logstash-8-0-is-adding-extra-field/297594).

Solution I did (don't know if it is the best, but it works from what I can tell)

The first item in the Logstash pipeline filter section is to drop the `event.original` field.

```ruby
# Remove the event.original field that Logstash adds when ECS Compatability v8 is enabled
mutate {
    remove_field => ["[event][original]"]
    id => "remove_logstash_added_event_original_ecs_compatability"
}
```
