### ISSUE TITLE
Update README.md to rename process.ppid to process.parent.pid (Applies to ECS >=8.0)

### ISSUE THREAD

**Issue by muthu-mps** [elastic/integrations#4786]
In the ECS version 8.0.0 the field `process.ppid` is migrated to `process.parent.pid`. This is based on the [ecs 8.0](https://github.com/elastic/ecs/releases/tag/v8.0.0) release notes. The field names are updated but the field names in the documentation is still showing the `process.ppid`. I have captured quite a few integrations here,
```
ZScalar 
Barracuda
Bluecoat
Cyberark
F5
etc...
```

Similarly the `log.original `field  in `F5` integration is migrated to `event.original.` This also needs documentation update.

**Comment by muthu-mps** [comment]
@elastic/security-external-integrations - Could you please have a look. I was able to capture few integrations here which is referencing the `process.ppid` field.

**Comment by efd6** [comment]
There are some deprecated packages in the affected set, but the rest are rsa2elk. These are experimental, but it's trivial to fix these.
