### ISSUE TITLE
Darktrace integration does not apply the correct ingestion pipeline

### ISSUE THREAD

**Issue by craiglawson** [elastic/integrations#4799]
The default configuration of the Darktrace integration does not apply the ingestion pipeline to parse the `message` field, this results in a large field which cannot be searched.

I have this working now, but I was only able to do so by setting a custom ingestion pipeline for AI Analyst and model breach alerts as follows:

- `logs-darktrace.model_breach_alert@custom` with a processor to run the `logs-darktrace.model_breach_alert-0.2.0-default` pipeline
- `logs-darktrace.ai_analyst_alert@custom` with a processor to run the `logs-darktrace.ai_analyst_alert-0.2.0-default` pipeline

I would have expected this pipeline to be running in the first instance

**Comment by vinit-elastic** [comment]
Hi @craiglawson,
We checked collecting data with default configuration from the live instance. We observed that it is working fine, data is parsing through default pipeline and fields are getting extracted. We checked in Elastic stack v8.4.0 and v8.5.3. In both versions, it is working as expected.

Could you please confirm the versions of the Elastic-Agent and Integrations package for the staters? For the best understanding, we have to check elastic-agent logs.

For downloading the diagnostics elastic-agent logs, follow this link: https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html#_collect_elastic_agent_diagnostics_bundle

For collecting fresh debug logs, please remove the existing integration policy, create a new policy, and assign it to the integration package.

**Comment by craiglawson** [comment]
Hi @vinit-elastic, we are using EA v8.5.3, from memory (currently on annual leave) the integration version was 0.2.0?

To reconfigure and collect logs, I will have to wait until the new year to collect this information for you unless I get a bit of slack time to have a play

**Comment by jamiehynds** [comment]
@craiglawson just following up here to see if you've managed to test the Darktrace integration again? If you're still having issues, I can provide an upload link for you to upload fresh debug logs, as suggested by Vinit.

**Comment by craiglawson** [comment]
Hi @jamiehynds yes, this continues to be an issue, and an additional issue has been found since but that is beyond the scope of this issue.

If you could provide an upload link, I will obtain some debug logs

Thanks

**Comment by jamiehynds** [comment]
Thanks @craiglawson - here's the link: https://upload.elastic.co/u/4adcb3cf-f945-4ef3-b69f-be468be3d4cf

**Comment by jamiehynds** [comment]
@craiglawson I'm going to close out this issue for now, but if you continue to run into issues, feel free to pull the debug logs and reopen the issue.
