### ISSUE TITLE
Move cockroachdb module to GA

### ISSUE THREAD

**Issue by andresrc** [elastic/integrations#480]
- Ensure the [requirements](https://github.com/elastic/beats/blob/master/.github/ISSUE_TEMPLATE/module-checklist.md) are met.
- Move the module to GA

**Comment by masci** [comment]
Currently blocked on https://github.com/elastic/beats/pull/17736

**Comment by ritalwar** [comment]
Requirement Document -> https://docs.google.com/document/d/1yjQdEAIjhxTSJzwyCEiutum14sp1VgtzJiIEPi7KGwA/edit#heading=h.drk5bek2a52h

**Comment by ritalwar** [comment]
Dependency on https://github.com/elastic/kibana/issues/129344
