### ISSUE TITLE
[AWS] Splitting AWS ELB integration into 3 separate data streams

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#4800]
The current ELB integration, we are collecting metrics from 3 different kinds of load balancers: Classic Load Balancer, Application Load Balancer, and Network Load Balancer. The metric collection for these three load balancers can be found [here](https://github.com/elastic/integrations/blob/main/packages/aws/data_stream/elb_metrics/agent/stream/stream.yml.hbs#L39). They are from 3 different namespaces from CloudWatch. 

This issue is to consider/discuss if we should split elb data stream into 3 different data streams: application_elb, network_elb, and classic_elb. Users will get the flexibility to enable the kind of load balancers they have. Note: Even with the separation, these 3 data streams should still show up under the same ELB integration tile in Kibana.

**Comment by aspacca** [comment]
> This issue is to consider/discuss if we should split elb data stream into 3 different data streams: application_elb, network_elb, and classic_elb. Users will get the flexibility to enable the kind of load balancers they have.

what about existing dashboards/migration path?
