### ISSUE TITLE
Proofpoint Tap integration issue

### ISSUE THREAD

**Issue by FredericAWills** [elastic/integrations#4801]
_A lot of fields are being ignored in the logs  and placed in the message field as *ignored** . Like the sender IP , email , threatID ....... This causes the dashboards to be incomplete.  Any assistance is appreciated_

<html>
<body>

Ignored value{"GUID":"976b5JXQlRrOtGO2J-zfkyYjn9oMypXs","QID":"3mcm8507u4-1","ccAddresses":[],"cluster":xxxxxxxxxxxxx","completelyRewritten":false,"fromAddress":["cabi@cabiclio.com"],"headerFrom":"Alexandra Pell Kuhel \u003ccabi@cabiclio.com\u003e","headerReplyTo":"apkuhel1@gmail.com","id":"92f4f821-5085-208e-bd75-659f4894bf22","impostorScore":100,"malwareScore":0,"messageID":"\u003c1791647953.2231421670692049038.JavaMail.ofbiz@ofbiz-jobs\u003e","messageParts":[{"contentType":"text/html","disposition":"inline","filename":"text.html","md5":"dc2e0b0af9882a8cdebbb2bec3594e7b","oContentType":"text/html","sandboxStatus":null,"sha256":"708f4fe2df0745b007d95a9228f400c243d866df42bc535f54ba53aeae88231b"}],"messageSize":68585,"messageTime":"2022-12-10T17:07:32.000Z","modulesRun":["av","zerohour","dkimv","spf","spam","dmarc","urldefense"],"phishScore":0,"policyRoutes":["default_inbound","allow_relay"],"quarantineFolder":"Impostor","quarantineRule":"impostor","recipient":["bxxxxxxxxxxxxxxxxx@xxxxxxx.org"],"replyToAddress":["apkuhel1@gmail.com"],"sender":"1826.82.9c7a000649563e.666366ecc336a25be20dc3fa6f3890a7@email-od.com","senderIP":"142.0.176.15","spamScore":0,"subject":"Want more cabi at 50%? Share the #cabilove.","threatsInfoMap":[{"campaign":null,"classification":"impostor","threat":"apkuhel1@gmail.com:976b5JXQlRrOtGO2J-zfkyYjn9oMypXs","threatID":"9d9d08989cfca6af80f31d9b74b90fa56933efa0412ab7f253d5e52a978b8301","threatStatus":"active","threatTime":"2022-12-10T17:07:34.000Z","threatType":"messageText","threatUrl":"https://threatinsight.proofpoint.com/xxxxxxxxxxxxxxx"}],"toAddresses":["bxxxxxxxxxx@xxxxxx.org"],"xmailer":"Apache OFBiz, The Apache Open For Business Project"}
--
  | tags | [forwarded, proofpoint_tap-message_blocked]

</body>
</html>

**Comment by jamiehynds** [comment]
@vinit-elastic would you mind taking a look?

**Comment by vinit-elastic** [comment]
Looking into it.

**Comment by vinit-elastic** [comment]
Hey @FredericAWills, 
Could you please confirm the versions of the Elastic-Agent and Integrations package for the staters? Moreover, could you please send the original log ( redacted ) received from the Proofpoint instance?

**Comment by FredericAWills** [comment]
Thank you Vinit, agent version is Agent version 8.4.2 and the Proofpoint TAP integration version is Version
1.3.1

I am a newbie when it comes to elastic :) We are presently exploring it as a replacement SIEM in our company. When you say log, do you mean documents or filebeat log on that agent ? 

[document.txt](https://github.com/elastic/integrations/files/10218504/document.txt)

**Comment by vinit-elastic** [comment]
Hey @FredericAWills,
Thank You for sanding the log file, We were going through the log file, and we tested the package with the log that you shared, and it seems that all fields populated successfully with the current pipeline. So for the best understanding, we have to check elastic-agent logs.

For downloading the diagnostics elastic-agent logs, follow this link: https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html#_collect_elastic_agent_diagnostics_bundle

For collecting fresh debug logs, please remove the existing integration policy, create a new policy, and assign it to the integration package.

**Comment by FredericAWills** [comment]
is there a secure method to share with you?

**Comment by jamiehynds** [comment]
@FredericAWills if you don't mind, you can upload the logs to our secure upload service via this link: https://upload.elastic.co/u/b9c6110f-cb04-4312-a21b-d3192945f4a8

**Comment by FredericAWills** [comment]
Thank you @jamiehynds . Uploaded
added files for b9c6110f-cb04-4312-a21b-d3192945f4a8 
1 elastic-agent-diagnostics-2022-12-15T14-53-34Z-00 (2) - Copy.zip 0.3MB

**Comment by jamiehynds** [comment]
@FredericAWills - we've taken a look at the debug logs provided, and it looks like the issue is related to Filebeat/Agent rather than the Proofpoint integration itself. Would you mind creating a ticket with our Support team and sending me the Case ID in order to resolve the issue?

**Comment by FredericAWills** [comment]
@jamiehynds @vinit-elastic I think I was able to fix it. I changed the pipeline that is used in the settings to *-default 
![default](https://user-images.githubusercontent.com/4839022/209687940-22bb7aed-84db-4b22-b6dc-bdc6f4967b49.png)

**Comment by vinit-elastic** [comment]
Hey @FredericAWills - That's great that you are able to resolve it. 
However, I'd like to know if the package's vanilla install threw an error or if there were some configuration changes made.

**Comment by FredericAWills** [comment]
@vinit-elastic sure no problem. How can I assist ?

**Comment by vinit-elastic** [comment]
@FredericAWills - Would you mind sharing the series of steps that you executed in order to install the integration and were there any other steps that you performed? Furthermore, what was the value in the settings before you changed it to *-default?
