### ISSUE TITLE
Why I can install assets if the integration is not configured?

### ISSUE THREAD

**Issue by markov00** [elastic/integrations#4825]
We are discussing an issue in dashboard that should [limit a bit the number of errors on a dashboard,](https://github.com/elastic/kibana/issues/143673) in particular with dashboards that are configured without having indices for their data views.

In some case I see it legit to reduce such volume of errors but in someothers I'm wondering if we can fix that behaviour at the root level. In particular I'm considering the case exposed [here](https://github.com/elastic/kibana/issues/143673#issuecomment-1316685490)  where an integration dashboard is probably installed before installing the Elastic Agent and related integration.
If I open an integration page, I can start by adding/configuring the integration or, from the `Settings` tab I can go on and install directly the assets without configuring the integration.
<img width="937" alt="Screenshot 2022-12-14 at 11 16 05" src="https://user-images.githubusercontent.com/1421091/207569450-a3347263-9969-4f30-88b5-a579522a5a3e.png">
There is a small message that says to install the integration first, but nothing blocks me from clicking that `Install assets` button.

I'm wondering why we allow this behaviour, knowing that:
- if you don't have the Agent configured the index is probably not available and opening a related dashboard will generate errors, some charts will not be shown, some other will error out and others will be just empty.
- a dashboard or saved search without an index (without data) doesn't make much sense (even with a nice/clean chart skeleton when no data is available), IMHO doesn't tempt the user to proceed with the integration, but at contrary it makes it run away because it "seems" to not working properly.

Have we considered the possibility to disable that `Install assets` button if the data is not available and/or if the integration is not installed/configured correctly? A preview, with some screenshots of the dashboards with nice data and the saved searches tables, can probably replace the need of installing the assets before the integration is configured and can temp way more the user to keep going with that.
WDYT?

cc @andrewctate

**Comment by aspacca** [comment]
> Have we considered the possibility to disable that Install assets button if the dataviews are not available and/or if the integration is not installed/configured correctly? A preview, with some screenshots of the dashboards with nice data and the saved searches tables, can probably replace the need of installing the assets before the integration is configured and can temp way more the user to keep going with that.
> WDYT?

Beware that the Elastic Serverless Forwarder relies on the fact that assets are installed, for native AWS services (or in general any source of logs we have an integration for) without having Elastic Agent installed: https://www.elastic.co/guide/en/observability/current/aws-deploy-elastic-serverless-forwarder.html

The same will be probably true for the AWS Firehose input.

Andrea Spacca
Principal Software Engineer I
Elastic – Search. Observe. Protect.

**Comment by markov00** [comment]
Thank you @aspacca, I think I probably misunderstood what an asset is and how adding an  integration should work, but in my mind I have the following concepts:
1) the process of installing/adding an integration means: the tool (Kibana in our case) gives you all the advice/steps/configurations needed to start working right away, the installation process could have branches depending on your current "state" (you already have used this integration before and some config are already there, or you start from scratch)
2) an asset instead is an additional set of examples, tutorials, optional configs, like in our case dashboards, saved searches, that is useful to get start working quicker on what you have just installed.

From what you are saying instead, the assets can contain both mandatory configurations and/or optional objects with no particular order.
When I think about adding an a plugin/an integration/an additional feature I always imagine the following flow:
1) install the integration first by checking and confirming the **mandatory steps*** (ES configs, indices, mappings, ingest nodes config). This could branch a bit if some of those steps are already configured (the "installation wizard" should tell me whenever I have already something similar installed and skips some of the steps. 
2) now, that I have all the config in place, and the only last bits are sending data, I can add optional assets, like Kibana Dasboards or Saved Searches, so that I can start looking at my data as soon as the first document is ingested.

Instead, what I see today is that, the process of installing the assets doesn't validate all the requirements for the installed assets, in particular, doesn't validate if all the indices are there, if the mappings are valid and in line with the expectations. 
It just install everything and let's the user figure our that there is a problem by throwing errors. Dashboard/Lens can alleviate this a bit by making it more "comprehensible" but the problem persists, we just pushed the problem more toward the user.
