### ISSUE TITLE
Move the ibmmq metricbeat module to GA

### ISSUE THREAD

**Issue by andresrc** [elastic/integrations#484]
# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows [development guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines)
- [x] Supported versions of the monitoring target are documented
- [ ] ~Supported operating systems are documented (if applicable)~
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to: 

### Metric dataset changes

_This entry is currently only recommended. It will be mandatory once we provide better support for it._

- [ ] Sample event (`sample_event.json`) exists

### Metricbeat module changes

- [x] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
- [x] Test environment in Docker exist for integration tests

**Comment by chidspark** [comment]
Hi, One of my customer is looking for IBM MQ module for metricbeat integration and would like to know the tentative dates for IBM MQ module GA.  As per this documentation, it is currently showing as beta --> https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-ibmmq.html#_compatibility_23.  Any update on this would be helpful! Thank you
