### ISSUE TITLE
[MISP] Document created with error.message field when there is and empty response.

### ISSUE THREAD

**Issue by leandrojmp** [elastic/integrations#4892]
Hello,

I've just installed the MISP integration and noticed that when the response from MISP is empty, it creates a document with a the following message in the `error.message` field.

> cannot access method/field [size] from a null def reference

When this happens, the value of the `event.original` field is the following:

> {"response":[]}

I configured it to check our MISP server every 5 minutes, and every 5 minutes I got this error when there is nothing published in the MISP server, if there are published IOCs, it can get the events without any problem.

![Screenshot from 2022-12-22 19-50-52](https://user-images.githubusercontent.com/322886/209238649-04ff31b7-ea76-46ad-a14a-9073723d946b.png)

I can easily configure a custom ingest pipeline to drop those messages, but shouldn't the integration already do that?

**Comment by LaZyDK** [comment]
I agree. These events should be dropped.
