### ISSUE TITLE
[System] Dashboards do not prefilter on dataset values

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#4936]
Looking at the system dashboards, it seems most visualisations do not prefilter on the `data_stream.dataset` value but instead query all of the `metrics-*` indices.

This is an issue as it is much less performant!

**Comment by ruflin** [comment]
@elastic/ecosystem It would be great to have some checks in place for the above. Also, is this somewhere documented in our guidelines? Tried to find it in https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md but without success.

**Comment by mrodm** [comment]
> @elastic/ecosystem It would be great to have some checks in place for the above. Also, is this somewhere documented in our guidelines? Tried to find it in https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md but without success.

@ruflin I've created a PR to include a new section about adding this filters in the Dashboard guidelines doc https://github.com/elastic/integrations/pull/5026

**Comment by mrodm** [comment]
@ruflin One doubt about how to set these filters in the system package.
Visualizations like the below one with this search would be considered ok ? This visualization comes from the ` [System Windows Security] Group Management Events - Simple Metrics` dashboard

![visualization_search](https://user-images.githubusercontent.com/5330827/213160475-b02beaff-aceb-42b3-baed-1a1efa6abc9f.png)

**Comment by ruflin** [comment]
Having 2 (or more) dataset filter are ok. The part I'm surprised is that it is in search and not a filter? @andrewkroh Is this by design or accident? 

My general recommendation, lets leave the search bar to our users and have all "half hardcoded" filters below.

**Comment by andrewkroh** [comment]
I would also prefer to have those as a filter to keep the search bar open. There are two filters for backward compatibility with earlier data. Originally these data streams were contained in the Windows package so we wanted to accept that data.

**Comment by mrodm** [comment]
To be on the same page, I've created a new PR to update the docs about adding these filters in visualizations https://github.com/elastic/integrations/pull/5043.

Would that be the preferred way (best practice) for this ?
