### ISSUE TITLE
Allow Prometheus integration in Fleet to leverage the standard HTTP module options in Metricbeat

### ISSUE THREAD

**Issue by maximhan** [elastic/integrations#496]
**Describe the feature:**
The current Prometheus integration only seems to support the module specific configuration, but does not allow you to feed in the standard configuration options that are available across all the Metricbeat modules.

Something along these lines would thus be very helpful:
![image](https://user-images.githubusercontent.com/264774/101969915-82284380-3c27-11eb-99ca-4bd1be557b98.png)

**Describe a specific use case for the feature:**
This is needed for the exact same reason as is outlined in https://github.com/elastic/beats/issues/12954, where we're trying to scrape data from HashiCorp Vault's metrics/telemetry API, but are unable to do so using Fleet.

**Comment by jen-huang** [comment]
If I'm understanding correctly, this would require changes to the prometheus package, not Kibana, so I moved it to the Integrations repo here.
