### ISSUE TITLE
Make sure that our Integrations mapping adhere to ECS best practices

### ISSUE THREAD

**Issue by philippkahr** [elastic/integrations#4960]
Are there any plans to make sure that all integrations adhere to [ECS best practices](https://www.elastic.co/guide/en/ecs/current/ecs-guidelines.html)?

`Field names must be lower case`

e.g. the windows integration does not adhere to this.[Windows mapping]
(https://github.com/elastic/integrations/blob/968a3f133bc6f09172b5111bdd1988dfd75293fd/packages/windows/data_stream/forwarded/fields/winlog.yml#L45)

I think there are plenty of integrations that do not follow our own best practices.

**Comment by ruflin** [comment]
@elastic/ecosystem Should we do some linting around this?

**Comment by andrewkroh** [comment]
I had never considered these ECS best practices to apply to non-ECS fields. The `winlog.*` namespace is not governed by ECS. At least for the example given of `winlog.trustAttribute`, I don't think there is a issue with ECS.

From [ECS | Custom Fields](https://www.elastic.co/guide/en/ecs/current/ecs-custom-fields-in-ecs.html#ecs-custom-fields-in-ecs):

> However, ECS does not define anything about custom fields. By definition, they are additional fields, exactly as the user or the integration defines them, independently of ECS.

**Comment by ruflin** [comment]
I kind of assume that that fields (if possible) should still follow the [general naming convention](https://www.elastic.co/guide/en/beats/devguide/current/event-conventions.html). Unfortunately it is not part of ECS but Beats.
