### ISSUE TITLE
[Beats] Integration does not map agent.name

### ISSUE THREAD

**Issue by philippkahr** [elastic/integrations#4961]
I have a policy with collect system metrics enabled, and I wondered why I couldn't filter in Kibana when using agent.name: "bla". Appears that we don't map agent.name. I believe this is related to this integration [beats](https://github.com/elastic/integrations/tree/main/packages/beat) and quickly checking in the repo, I cannot find any agent mapping.

I suspect there are more integrations that do not adhere to the entire ECS catalog, yet index data that contains ECS fields.

This brings me back to one issue, where I mentioned that ES should be aware of all ECS fields and autodetect them, making sure that we would not need to have complex checks in place to ensure that the integration does not do stuff like this. https://github.com/elastic/elasticsearch/issues/85146

<img width="605" alt="image (2)" src="https://user-images.githubusercontent.com/12175559/211538036-07cd2b81-5511-46ae-88b0-bc584b458506.png">

**Comment by ruflin** [comment]
There is quite a list of related issues here:

* https://github.com/elastic/elasticsearch/issues/85692
* https://github.com/elastic/ecs/issues/1869

But the most important short term one is this one here: https://github.com/elastic/elastic-package/issues/1018 As soon as dynamic mappings for the basic fields exist in packages, this "accidental" errors should not show up anymore.
