### ISSUE TITLE
Summary solution/dashboard for all azure related dashboards

### ISSUE THREAD

**Issue by narph** [elastic/integrations#497]
Provide a solution or dashboard that will  include all azure related dashboards.

**Comment by narph** [comment]
@sorantis , @masci , the following url format should work in filtering only the `azure` related dashboards:
`http://localhost:5601/app/dashboards#/list?filter=azure`


![image](https://user-images.githubusercontent.com/1900090/103645668-49db0300-4f50-11eb-9547-e1adb96ec94c.png)


Let me know if that is enough for the issue.

**Comment by sorantis** [comment]
Thanks, looks good. Closing the issue for now, will reopen should there be any addition requirements for dashboard consolidation
