### ISSUE TITLE
Need to update links to Elastic Agent processor docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/integrations#4989]
For integrations that support processors, we currently provide links that send users to the Filebeat documentation:

![image](https://user-images.githubusercontent.com/14206422/212209373-9fcca5e8-de94-41a2-ae2e-07c255bc6631.png)

Starting in 8.6.0, the processor documentation is available in the Fleet and Elastic Agent Guide. We need to update all Elastic Agent integrations to use the new URL for processor docs:

https://www.elastic.co/guide/en/fleet/current/elastic-agent-processor-configuration.html

**Comment by dedemorton** [comment]
@joshdover @nimarezainia  I've created this issue to track the updates that are required to integrations. Can you make sure the correct labels get applied and that this gets into someone's workflow? I'm also wondering if we need a similar issue in Kibana (I'm not quite sure how the UI for integrations is built, but I do see the Filebeat URL in a Kibana search).

**Comment by joshdover** [comment]
These are defined in integrations right now.

> but I do see the Filebeat URL in a Kibana search

The only things I'm finding in the code base are for tests (not important) or for the Beats tutorials we still host in Kibana. I think those are fine.

**Comment by dedemorton** [comment]
@joshdover Do I need to apply more labels to make sure this gets picked up? I want to make sure users can find the correct docs.

**Comment by joshdover** [comment]
Put up a PR for this 👍
