### ISSUE TITLE
[Ingest Manager]: Datasets generated with future timestamps for "system.syslog" and "system.auth" events for linux .tar agent under Data Streams in Fleet UI.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#501]
Kibana version:
Kibana:7.11.0 Cloud environment

Elasticsearch version:
Elasticsearch: 7.11.0 Cloud environment 

Build Details:
Build number: 37399
Commit: f3abc08ac648f8b302733c5c22a39048314a027c

Host OS and Browser version:
linux centos 7.3, All

Original install method (e.g. download page, yum, from source, etc.):
7.11.0 Cloud environment

Preconditions
1. Artifacts for 7.11.0 Agent should be available.
Link used: https://staging.elastic.co/7.11.0-710164a0/downloads/beats/elastic-agent/elastic-agent-7.11.0-linux-x86_64.tar.gz
2. 7.11.0 Cloud environment should be available.

Steps to reproduce:

1. Login to Kibana cloud environment.
2. RDP to endpoint. Install Linux .tar Agent using default policy having system integration.
3. Navigate to Data Streams tab. Observe, System data is generated successfully for elastic agent.
4. Notice that "system.syslog" and "system.auth" data is generated with future timestamps.
5. Navigate to Discover tab. Set Timeline filter to "Next 1 year".
6. Observed logs for future timestamps.

Reference ticket Id:

Actual Result:
- Data for "system.syslog" and "system.auth" is generated with future timestamps under Data Streams Tab and Discover tab.

Expected Result:
- Data for "system.syslog" and "system.auth" should not be generated with future timestamps under Data Streams Tab and Discover tab.

What's working
Same observation has been made at 7.10.1 BC build with Linux .rpm and .tar agent.Build details are as: 
```
BUILD 36063
COMMIT 608c5e5dd32659e8afadd520d0cdc58766ba505b
Artifact link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.10.1-linux-x86_64.tar.gz
```
![bug_observation](https://user-images.githubusercontent.com/72375798/103766569-0b734000-5045-11eb-94a9-e0f7e3cfbf71.png)

What's not working
N/A

Screenshots:
![bug](https://user-images.githubusercontent.com/72375798/103766114-46c13f00-5044-11eb-838a-8c140943e039.png)

**Comment by fearful-symmetry** [comment]
@ph That's...really odd. Nothing in those two data streams changed for 7.11. Could this be a filebeat issue?

**Comment by EricDavisX** [comment]
@masci Hi - I'm tagging you on this and assigning you just to confirm we agree if it is urgent, or not.  I tagged it as 'impact:high' although I agree it is arguable, I don't know how serious we want to take this particular 'wrong data' problem.  Please do comment and update.  Let us know if the test team can help provide any more info to help decide, or push this on.

**Comment by masci** [comment]
This looks pretty bad to me, @exekias how should we proceed?

**Comment by andrewkroh** [comment]
Do we have an example of the logs that are being parsed when this occurs? My wild guess is that they contain syslog dates without years in them. When this happens the current year is assumed by the date processor IIRC.

**Comment by exekias** [comment]
Just tested this and couldn't reproduce:

![image](https://user-images.githubusercontent.com/299804/110297337-a8296e00-7ff3-11eb-8030-6fe81f242f42.png)

I also suspect about year missing in some old logs, from my ubuntu syslog:

```
Mar  8 08:50:06 ubuntu-focal multipathd[471]: sdb: failed to get sgio uid: No data available
```

Could you please confirm how old is the machine containing these logs? If it has been up since November in some past year this would be expected. As an example, this is the syslog in my machine (no year present):

```
Mar  8 08:50:06 ubuntu-focal multipathd[471]: sdb: failed to get sgio uid: No data available
```

Could you please run this command in the machine where you installed the agent and paste the output?

```
ls -la /var/log/syslog
```

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have attempted to reproduce above and below are our observations:

on Centos 7.6:

- Issue is reproducible.
- Syslog file was not generated on endpoint.
- Other log files are:
[elasticagent_yml.txt](https://github.com/elastic/integrations/files/6101392/elasticagent_yml.txt)

[elastic-agent.log](https://github.com/elastic/integrations/files/6101440/elastic-agent.log)


Screenshot:
![image](https://user-images.githubusercontent.com/72375798/110323739-07f73780-803b-11eb-923c-5cd2dc883a49.png)

On Ubuntu 20:
- issue is reproducible
- Output for this ls -la /var/log/syslog command is as follows:

![image](https://user-images.githubusercontent.com/72375798/110323870-38d76c80-803b-11eb-9623-753c89318cb1.png)

- Output for date command: 
zeus@mainqa-atlcolo-10-0-7-238:/var/log$ date
Mon 08 Mar 2021 07:54:42 AM EST

Logs file are as follows:


[syslog.txt](https://github.com/elastic/integrations/files/6101477/syslog.txt)
[syslog.1.txt](https://github.com/elastic/integrations/files/6101478/syslog.1.txt)


Screenshot:
![image](https://user-images.githubusercontent.com/72375798/110324530-1d209600-803c-11eb-9cf7-d82e34d65636.png)


Please let us know if anything else is required.

Thanks
QAS

**Comment by EricDavisX** [comment]
Thought I would post a similar issue seen in recent 7.12 / Integration on Windows package:
https://github.com/elastic/integrations/issues/768

**Comment by exekias** [comment]
Thank you! It would be good to actually check the data. Would it be possible to get the result of this query?

```
GET logs-system.syslog-default/_search
{
   "sort" : [
      {"@timestamp" : {"order" : "desc"}}
   ]
}
```

It can be run under `Dev Tools` menu

**Comment by dikshachauhan-qasource** [comment]
Hi @exekias 

As per above feedback, we have run the mentioned api request in dev tools on 7.12 BC4 having linux centos agent and below is the response:

![image](https://user-images.githubusercontent.com/72375798/110782261-ebead480-828c-11eb-8e6a-c6cc9988bea6.png)

Response details: 
[API_response.txt](https://github.com/elastic/integrations/files/6122700/API_response.txt)

Please let us know if anything else is required.

Thanks
QAS

**Comment by exekias** [comment]
Thank you! From the first document I can confirm that timestamps are in the future 🤔 

```
          "@timestamp" : "2021-11-14T10:24:19.000-05:00",
```

I tried to reproduce this by ingesting the logs from the syslog files shared in this comment https://github.com/elastic/integrations/issues/501#issuecomment-792766935, but I had no luck, all lines seem to be generated in the expected dates.

@EricDavisX I'll try to use the same centos image being used here. Where can I find information about it? `qa-centos 7.3x64-endpoint-clone-base-template`

**Comment by EricDavisX** [comment]
@exekias we can certainly get you more details on the image, and we can use a cloud-based image to help make shared access the same.  Or we can get you Endgame VPN access, Michal and a few non-Endgamer former team folk have it.  Or me / Diksha could also do a zoom session to help debug it live on that environment - she is based in IST timezone I think you should have some easy overlap.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

While performing testing today on Linux aws arm 64 machine, we observed that, no future timestamps for "system.syslog" and "system.auth" events were observed for linux  agent under Data Streams in Fleet UI. 

Build : 7.13 snapshot
BUILD 39998
COMMIT 5443379a381211da2872be856417bdbfa656a7dd
Artifact link: https://snapshots.elastic.co/7.13.0-ad409673/downloads/beats/elastic-agent/elastic-agent-7.13.0-SNAPSHOT-linux-arm64.tar.gz

Screenshot:
![image](https://user-images.githubusercontent.com/72375798/113412427-da9d6f80-93d5-11eb-8087-e7f8dfef19d0.png)

Further, on deeper check, we observed that it is reproducible only on VM machines, as per our understanding. Please let us know if any further information isrequired from our side.

Thanks
QAS

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

While performing testing on 7.13 BC3 kibana builds, we are observing this issue as **still reproducible.**

Build details:
```
BUILD 40647
COMMIT ac09c73a4a7998c770b50d39177c22036ae14375
Artifact page: https://staging.elastic.co/7.13.0-100107e6/summary-7.13.0.html
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/72375798/116525539-3df7c000-a8f6-11eb-9b3a-e6436040c5bf.png)


Thanks
QAs

**Comment by dikshachauhan-qasource** [comment]
Hi @jen-huang 

cc @EricDavisX 

We have validated this issue on 8.0 snapshot build and found it working fine. Build details:

```
BUILD 49040
COMMIT 155e06787e48de9a8de4345d86a826e95edf32ec
```

**Observations:** Datasets generated for "system.syslog" and "system.auth" events are now shown up with current timestamps for linux .tar agent under Data Streams in Fleet UI.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/149757834-68a29ede-c785-4c6d-849f-88c485e368b5.png)

Hence, we are closing this.
 
Thanks
QAS
