### ISSUE TITLE
[GCP] Ensure compute metrics dashboard can be filtered by resource location

### ISSUE THREAD

**Issue by endorama** [elastic/integrations#5020]
#5006 highlighted that the GCP Compute dashboard has a missing visualisation. When it was present, it was a filtering widget that could be used to filter data by `cloud.provider`, `cloud.account.id` and `gcp.billing.invoice_month`.

The fix is in progress, this issue wants to track the addition of filtering by resource location to the dashboard controls.

**Comment by tommyers-elastic** [comment]
@endorama resource location == `cloud.region`? or `cloud.availability_zone` ? what do you think?

**Comment by endorama** [comment]
That's interesting. In most dashboard we are using `gcp.*.labels.resource.<location | region | zone>`

The correct label depends on the service. I'm not sure we duplicate the data to `cloud.*` fields, but if that's the case for all we should still use either:
- the one the service is using
- both

What do you think?

**Comment by tommyers-elastic** [comment]
interesting - the compute metrics don't have any `labels.resource` fields for me. but the aforementioned `cloud.` fields are populated [here](https://github.com/elastic/beats/blob/3bcefabb28dbb78ea78cc442bdf4bb9a89953ca5/x-pack/metricbeat/module/gcp/timeseries_metadata_collector.go#L64).

**Comment by endorama** [comment]
Could it be you are collecting metrics with `exclude_labels: true`? ([docs](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-gcp.html))

> exclude_labels: (true/false default false) Do not extract extra labels and metadata information from metricsets and fetch metrics only. At the moment, labels and metadata extraction is only supported in compute metricset.
