### ISSUE TITLE
[System] Dashboard clean-up for Windows event logs

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#5022]
The windows event log dashboards contained in the system package require some attention to clean them up. They were migrated from Beats and have a few issues as pointed out in https://github.com/elastic/integrations/issues/3449.

- [x] Remove duplicate dashboards.
- [x] Fix navigation between dashboards. The navigation visualization can be shared.
- [x] Embed all other non-shared visualizations in the dashboards (aka "by value").
- [ ] Replace TSVB visualizations in favor of Lens.
- [x] Check if the same dashboards are contained in the Windows package (for use with Forwarded event logs). Ideally we should only ship the dashboards in one package (like system) and they could still be able to view data from the `system`, `winlog`, and `windows` data streams.
- [ ] Ensure that the dashboard aligns with the latest dashboard UX guidelines.

Related

- https://github.com/elastic/integrations/issues/3449#issuecomment-1385052609
- https://github.com/elastic/beats/pull/18775 (see how the dashboards looked originally)
- https://github.com/elastic/beats/pull/15236 (the very first instance of the dashboards)

**Comment by andrewkroh** [comment]
Also any queries should be created as filters to free up the search bar for users. For example:

BAD:
<img width="1544" alt="Screen Shot 2023-01-18 at 10 50 06" src="https://user-images.githubusercontent.com/4565752/213221211-6c182a3e-de3d-444f-9dcb-45296aa04e36.png">

GOOD:
<img width="869" alt="Screen Shot 2023-01-18 at 10 51 13" src="https://user-images.githubusercontent.com/4565752/213221245-a8c6c495-1990-44a5-862b-16e957a663c5.png">

**Comment by efd6** [comment]
The Windows integration does not have any dashboards that show the information shown in the System Windows dashboards. Winlog has no assets since it's a custom integration.

So marking that item as done.
