### ISSUE TITLE
Security Integrations GA

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#5033]
We have a number of integrations under Tech Preview/Beta which need to be moved to GA for 8.7. These integrations have been tested against the relevant data sources and have seen users adopt them without issues. 

- Barracuda CloudGen
- Box Events
- Cisco Aironet*
- Cisco Umbrella (Datastream is tech preview)
- Cloudflare Logpush
- Cyberark PTA
- Darktrace
- F5 BIG-IP
- Github (Datatreams are beta/tech preview. Leave Issues datastream in Beta)
- Infoblox BloxOne DDI
- Jamf Compliance Reporter
- LastPass
- Microsoft Exchange Message Trace
- PingOne
- Rapid7 Threat Command
- Slack Logs*
- Sophos Central
- Trend Micro Vision One
- Journald Input

*Community developed

**Comment by kcreddy** [comment]
@jamiehynds Sysmon for Linux requires more system tests before we can GA. Here's the tracking issue: https://github.com/elastic/integrations/issues/4784
- Sysmon for Linux
  - [ ] System tests
  - [x] Dashboard
  - [x] Documentation

**Comment by ShourieG** [comment]
@jamiehynds these were my findings for all the inputs listed : 

- Barracuda CloudGen Firewall
  - [x] System tests
  - [ ] Dashboard
  - [x] Documentation (Could be improved)
  - [x] Current Version  - 0.3.1
  
- Box Events
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.4.1 (beta)

- Cisco Aironet*
  - [x] System tests
  - [ ] Dashboard
  - [x] Documentation (Very minimal, needs to be improved)
  - [x] Current Version  - 0.3.1

- Cisco Umbrella (Datastream is tech preview)
  - [ ] System tests (no system tests)
  - [ ] Dashboard
  - [x] Documentation (Very minimal, needs to be improved)
  - [x] Current Version  - "1.6.2"

- Cloudflare Logpush (needs a bit of UI overhaul for the SQS queues)
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.6.0

- Cyberark PTA
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.4.1

- Darktrace
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.3.1

- F5 BIG-IP
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.1.0

- Github (Datatreams are beta/tech preview. Leave Issues datastream in Beta)
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 1.8.2

- Infoblox BloxOne DDI
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.3.1

- Jamf Compliance Reporter
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.5.0

- LastPass
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.3.1

- Microsoft Exchange Online Message Trace
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.4.1

- PingOne
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.3.1

- Ti Rapid7 Threat Command
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.1.0

- Slack Logs*
  - [x] System tests
  - [ ] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.3.0

- Sophos Central
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.1.0

- Trend Micro Vision One
  - [x] System tests
  - [x] Dashboard
  - [x] Documentation
  - [x] Current Version  - 0.3.1

- Journald Input
  - [x] System tests - but no pipeline tests
  - [ ] Dashboard
  - [x] Documentation (minimal)
  - [x] Current Version  - 0.0.5

Do we want to continue will all the integrations or remove ones without dashboards/system tests ?

**Comment by jamiehynds** [comment]
Thanks for digging into this one @ShourieG. My preference is to proceed to GA as these integrations have been around for several releases and should be supported. We'll add any missing dashboards as part of wider task of adding/updating Lens dashboards to our integrations. Can create separate issues to add any missing system tests, documentation, etc.
