### ISSUE TITLE
System winlogbeat event dashboards not populated

### ISSUE THREAD

**Issue by narph** [elastic/integrations#505]
Windows eventlogs dashboards are not populated:

This is an example:
![image](https://user-images.githubusercontent.com/1900090/104178364-18f04780-5402-11eb-80d7-d20272f5cdaa.png)

although there are events going in.

Also the name  of the dashboards are still containing `Windows` as they would be part of the `windows` package:

![image](https://user-images.githubusercontent.com/1900090/104178460-463cf580-5402-11eb-9c13-3c807a271ca5.png)

Can we also rename the dashboards to `System Windows Security` for example, it looks like there is no  naming pattern for the metrics and logs dashboards in the system package, I think we should create one.

cc @fearful-symmetry

**Comment by fearful-symmetry** [comment]
I'm fighting with the Dashboard issue here. @narph is that the _only_ dashboard that isn't populating? Can you post one of the events that should be showing up in the visualization?

**Comment by fearful-symmetry** [comment]
So there's a PR in, #522, that should fix some of this. However, I'm still not sure what's up with this:
```
Saved field "event.code" of index pattern "logs-*" is invalid for use with the "Terms" aggregation. Please select a new field.
```

**Comment by narph** [comment]
@fearful-symmetry , looks like either the type for this field has changed, or the vis is not supporting that type anymore, have you tried `event.code.keyword` instead? is this fixed in the #522 PR now?

**Comment by fearful-symmetry** [comment]
Yep, fixed the `event.code` issue.

**Comment by narph** [comment]
The added filters are letting events in, dashboards are being populated.

Few issues:

 - naming has been changed with the exception of one dashboard (the last one):

![image](https://user-images.githubusercontent.com/1900090/105070597-6e1fff00-5a7b-11eb-82c4-16aadbc86ca6.png)

-  the naming of the visualizations should be also updated for example here:
![image](https://user-images.githubusercontent.com/1900090/105070907-d7077700-5a7b-11eb-8648-fb5711333f7f.png)

we usually remove the [Windows Security] text al together .

- also, once we get to Windows General Dashboard dashboard (which should be renamed) it does not contain any navigation links to the other dashboards.
