### ISSUE TITLE
Feature Request of GCP Cloud Functions Logs 

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#5058]
Hello 

Would it be possible to have a dedicated  integration for GCP Cloud Functions Logs as per the work described below and attached files ? Of course, that would need more checks, some rewriting and more testing. 

Thank you very much 
  
**Context**
GCP supports Cloud functions of generation 1 and generation 2 
For generation 2, there are a few more triggers than http/https compared to generation 1. 
I have tested gcp cloud functions of gen1 and gen2 but only for http/https trigger

**Procédure on GCP**
After you create some GCP cloud functions in your project. 
You must create a sink , a topic and subscription that the gcp_pubsub generic integration call pull.  
I have used that one in the mean time. 

The sink (GCP log router) must be configured as follow 

> (resource.type="cloud_function" AND  log_name ="projects/carbon-minutia-308710/logs/cloudfunctions.googleapis.com%2Fcloud-functions") OR (resource.type="cloud_run_revision" AND log_name="projects/carbon-minutia-308710/logs/run.googleapis.com%2Frequests") OR labels."goog-managed-by"="cloudfunctions"

The 1st part is where gcp cloud functions of generation1 logs their activity 
The 2nd part is where gcp cloud functions of generation 2 logs their activity because they are run by GCP Cloud Run

**Procedure on Elastic: Add ingest pipelines, dashbaords**
Unzip attached gcp_cf_logs.zip
In Elastic Cloud Dev Console,  please upload content of the file _gcp_cf_logs_ingest_pipelines.json_ (ingest pipelines + mappings) 
In Kibana saved objects, import gcp_cf_logs_export.ndjson (a Suggested Dashboard) 

**Procedure on Elastic: use current gcp_pubsub generic integration**
Add the gcp_pubsub generic integration for Elastic-Agent
Enter the GCP Project ID, the topic, the subscription, your credentials ...

But most important, rename the event.dataset to **gcp.cloudfunctions** , otherwise it wont work 
[gcp_cf_logs.zip](https://github.com/elastic/integrations/files/10611894/gcp_cf_logs.zip)

**Comment by Danouchka** [comment]
cc @P1llus

**Comment by P1llus** [comment]
Quick question @Danouchka , since I have not used GCP Cloud Functions that much:

1. Is the logs from Cloud Functions different for every user, like a custom log created by a custom function, or is this simply a standardized format, that logs activity from cloud functions?
2. Do you have some example data that could be shared?

**Comment by Danouchka** [comment]
Hi @P1llus , it's a standartized format.. directly available in log router of GCP like gcp audit logs, vpcflow logs etc..

**Comment by Danouchka** [comment]
But formats are very different from gen1 and gen2 cloud functions

**Comment by Danouchka** [comment]
Hi, I have updated the attached zip with a few corrections...as well as the gcp log router sink definition according customer wishes
