### ISSUE TITLE
System package: process count is low when running agent on windows

### ISSUE THREAD

**Issue by narph** [elastic/integrations#506]
We've noticed this issue in previous tests, number of processes is too low when running the system package on windows.
Previous tests here https://github.com/elastic/observability-test-plans/issues/160#issuecomment-714387915

![image](https://user-images.githubusercontent.com/1900090/104177869-615b3580-5401-11eb-8a33-004f72ce455e.png)

There are a lot more than 31 processes, there should be 250-300. We do not encounter this issue with the system module.

**Comment by fearful-symmetry** [comment]
This is a known issue, correct? I could have sworn that somewhere we narrowed this down to a precise API issue, but I can't find it.

**Comment by narph** [comment]
> This is a known issue, correct? I could have sworn that somewhere we narrowed this down to a precise API issue, but I can't find it.

I don't think this is a known issue, at least I have not been in any conversation regarding this, this is an issue I am able to reproduce using the system package and we were able to reproduce in the last tests but we have not done anything about it (as far as I know).
The system module works fine, I only see this in the system package.

**Comment by fearful-symmetry** [comment]
> The system module works fine, I only see this in the system package.

So the abnormally low process count is only happening on _fleet_ and not on metricbeat system?

Stupid question: Are you sure that you're testing the integration against the same stack release as metricbeat? I ask, as there's been some upstream confusion with testing a given stack release against a given integration release.

**Comment by fearful-symmetry** [comment]
@narph can you get the agent metricbeat logs? You might have to get from the log files on the host, still not sure what agent is forwarding.

**Comment by fearful-symmetry** [comment]
Sorry, one last thing. Can you post the integration config for the `process` data stream?

**Comment by narph** [comment]
![image](https://user-images.githubusercontent.com/1900090/105067079-46c73300-5a77-11eb-86bb-2087a0f3bbc9.png)

The issue was that only top n processes where monitored, soon as I increased the number all went fine. Will close the issue.
