### ISSUE TITLE
[Mimecast] the removal of the pagination from the SIEM endpoint

### ISSUE THREAD

**Issue by oliver-creed** [elastic/integrations#5060]
the removal of pagination from the SIEM endpoint in #4929 causes the integration not to keep up-to-date with the latest logs

**Comment by jamiehynds** [comment]
@kcreddy possibly knock on effect of the recent Mimecast PR mentioned above.

**Comment by kcreddy** [comment]
Hi @oliver-creed,

Could you please give more details on this issue, i.e., current result vs expected result?

**Comment by kcreddy** [comment]
Also FYI, the pagination is not removed in https://github.com/elastic/integrations/pull/4929 . The `token` present inside request `body.data` should take care of the pagination. We confirmed this with Mimecast vendor.

CC @marc-gr
