### ISSUE TITLE
[O365] Audit Integration - Missing ecs fields file.name and file.extension

### ISSUE THREAD

**Issue by janniten** [elastic/integrations#5064]
Hi, 
I've notice that file.name and file.extension is only populated when the event code is SharePointFileOperation.
From the ingestion pipeline:
```
      {
        "rename": {
          "field": "o365audit.SourceFileName",
          "target_field": "file.name",
          "ignore_missing": true,
          "if": "ctx.event?.code == \"SharePointFileOperation\""
        }
      },
      {
        "rename": {
          "field": "o365audit.SourceFileExtension",
          "target_field": "file.extension",
          "ignore_missing": true,
          "if": "ctx.event?.code == \"SharePointFileOperation\""
        }
      }
```
In the` event.code: "SharePointSharingOperation"` there exists also this information
I'm solving the issue in the custom pipeline,but I believe that those fields should be populated in the main pipeline

Thanks a lot

**Comment by efd6** [comment]
@janniten Are you able to provide a test event.original?

**Comment by janniten** [comment]
@efd6 Here it is
`
  "AppAccessContext": {
    "AADSessionId": "xxxxxx-4224-4250-b040-yyyyyyy",
    "CorrelationId": "wwwwww-e021-6000-1d2d-zzzzzzzz",
    "UniqueTokenId": "xxxxxyyyyyyzzzzz"
  },
  "CreationTime": "2023-01-30T07:39:56",
  "Id": "xxxxxxxxx-832d-4e6a-868b-yyyyyyyyyyyyy",
  "Operation": "SecureLinkUsed",
  "OrganizationId": "xxxxxxxxxxx-9e16-4286-9a69-yyyyyyyyyy",
  "RecordType": 14,
  "UserKey": "i:0h.f|membership|xxxxxxxxxc@live.com",
  "UserType": 0,
  "Version": 1,
  "Workload": "SharePoint",
  "ClientIP": "1.1.1.1",
  "ObjectId": "https://dummydomain.sharepoint.com/sites/msteams_067dce/Shared Documents/General/Trainings/Train The Trainer (TTT)/Day 1 - CSRDesktop/HL Agenda.pdf",
  "UserId": "user@dummydomain.com",
  "CorrelationId": "xxxxxxx-e021-6000-1d2d-yyyyyyyy",
  "EventSource": "SharePoint",
  "ItemType": "File",
  "ListId": "xxxxxxxxxx-e1db-4a04-ab81-zzzzzzzzzzz",
  "ListItemUniqueId": "zzzzzzzz-1872-4e5c-8db1-yyyyyyyyyyyy",
  "Site": "xxxxxxxxxxx-6723-456f-994c-yyyyyyyyyyy",
  "UserAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.70",
  "WebId": "xxxxxxxxxxxxx-d881-418c-89dd-yyyyyyyy",
  "SourceFileExtension": "pdf",
  "SiteUrl": "https://dummydomain.sharepoint.com/sites/msteams_067dce",
  "SourceFileName": "HL Agenda.pdf",
  "SourceRelativeUrl": "Shared Documents/General/Trainings/Train The Trainer (TTT)/Day 1 - CSRDesktop/HL Agenda.pdf"
}`
