### ISSUE TITLE
[Microsoft Exchange Online Message Trace] Set `source.user.email` and `destination.user.email`

### ISSUE THREAD

**Issue by BenB196** [elastic/integrations#5081]
The Microsoft Exchange Online Message Trace currently only sets some of the `source` and `destination` fields. One of the missing fields is the `user.email` field for both of them. This information can easily be gotten from the `email` object via a Set/Copy processor

**Comment by gonzalosand** [comment]
Sorry I know it is not the subject but what url do you put for the integration I have tried several ways and currently I have this https://reports.office365.com/ecp/reportingwebservice/reporting.svc/MessageTrace

help

**Comment by BenB196** [comment]
Closed by #5159
