### ISSUE TITLE
[O365] incorrect ECS schema

### ISSUE THREAD

**Issue by mbrancato** [elastic/integrations#5090]
Looking at the expected O365 output, I noticed somethings that may need improvement.

First `event.category` is being implemented as a string, but the ECS schema says this field is an array.
https://github.com/elastic/beats/blob/c01dfe680e8d4d810e014c6caa6b0e543c56df57/x-pack/filebeat/module/o365/audit/test/01-exchange-admin.log-expected.json#L5

The following might be limited to the Exchange logs...

Second, two fields seem to be copied but not parsed, and I'm curious is this is the expected ECS result (to leave the content as is)? The `server.name` field and `user.id` field contain more than just those values, but they are not being parsed.
https://github.com/elastic/beats/blob/c01dfe680e8d4d810e014c6caa6b0e543c56df57/x-pack/filebeat/module/o365/audit/test/01-exchange-admin.log-expected.json#L39-L44

Third, the `server.address` field is supposed to be copied to either `server.ip` or `server.domain` depending on what type of value it is, but it is not. Should this be updated?

**Comment by jamiehynds** [comment]
Closing as we've recently reviewed and updated our O365 ECS mappings.

**Comment by chrisberkhout** [comment]
These issues do seem to remain in the beats module that was linked to, but not in the o365 integration (in this repo).

For the integration:
1. [`event.category` is an array](https://github.com/elastic/integrations/blob/4c91ffccc36bd7be2586ee57eca1a5ea61b7560f/packages/o365/data_stream/audit/sample_event.json#L30-L32)
2. The information from the `OriginatingServer` field [is split up into address, domain and IP](https://github.com/elastic/integrations/blob/4c91ffccc36bd7be2586ee57eca1a5ea61b7560f/packages/o365/data_stream/audit/_dev/test/pipeline/test-exchange-admin-events.json-expected.json#L58-L62). `UserID` values such as `NT AUTHORITY\\SYSTEM (Microsoft.Exchange.ServiceHost)` are [simply copied to `user.id`](https://github.com/elastic/integrations/blob/4c91ffccc36bd7be2586ee57eca1a5ea61b7560f/packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml#L66-L70) and appear [without further parsing](https://github.com/elastic/integrations/blob/4c91ffccc36bd7be2586ee57eca1a5ea61b7560f/packages/o365/data_stream/audit/_dev/test/pipeline/test-exchange-admin-events.json-expected.json#L66-L68), but that seems like a good choice. Values in the `user@domain` format do have [further parsing](https://github.com/elastic/integrations/blob/4c91ffccc36bd7be2586ee57eca1a5ea61b7560f/packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml#L970-L980).
3. As mentioned in point 2, [server address, domain and IP are set correctly](https://github.com/elastic/integrations/blob/4c91ffccc36bd7be2586ee57eca1a5ea61b7560f/packages/o365/data_stream/audit/_dev/test/pipeline/test-exchange-admin-events.json-expected.json#L58-L62).
