### ISSUE TITLE
[ Cisco Secure Email Gateway ] Parse of cisco_secure_email_gateway.log.message not working because of extra space.

### ISSUE THREAD

**Issue by leandrojmp** [elastic/integrations#5095]
Hello,

For some unknown reason my Cisco Secure Email Gateway is sending an extra space on the beginning of each message, this breaks the parse of the `cisco_secure_email_gateway.log.message` field because the pipelines that parse this fields uses an anchored grok.

For example, after the `default` pipeline the field `cisco_secure_email_gateway.log.message` the message will be sent to one of the other pipelines in the integration, in my case I'm using only the AMP pipeline at the moment.

The field `cisco_secure_email_gateway.log.message` will have the following message:

```
 File reputation query initiating. File Name = fileName, MID = 55780405, File Size = 3598 bytes, File Type = image/png
```
Notice the extra space in the beginning.

But the amp pipeline expects this message:
```
File reputation query initiating. File Name = atl-generated-b7e35071-ef20-42b9-a4ca-6ad62165ee7a, MID = 55780405, File Size = 3598 bytes, File Type = image/png
```

That will be parsed with the following processor:
```
  - grok:
      field: cisco_secure_email_gateway.log.message
      patterns:
        - "^File reputation query initiating. %{GREEDYDATA:_tmp.new_message}$"
```

Since the grok patterns are all anchored, the messages with an extra space won't get parsed.

The fix is pretty simple, just adding a `trim` processor after the main `grok` processor in the `default` ingest pipeline solves this issue.

I will try to make a PR fixing this later.

**Comment by dhruvil-elastic** [comment]
Hi @leandrojmp, we have started looking into it and will raise PR soon.

**Comment by leandrojmp** [comment]
Hello @dhruvil-elastic, I didn't had time to raise a PR, but this is what I've changed:

```
  {
    "trim": {
      "field": "cisco_secure_email_gateway.log.message",
      "ignore_missing": true,
      "ignore_failure": true
    }
  }
```

Just added this `trim` processor after the `grok` processor in the default ingest pipeline.
