### ISSUE TITLE
Migrate AWS integration

### ISSUE THREAD

**Issue by masci** [elastic/integrations#512]
# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows [development guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines)
- [x] Supported versions of the monitoring target are documented
- [x] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

**Comment by kaiyan-sheng** [comment]
Things to fix:
- [ ]  Remove aws_partition config
- [ ]  Add cost_explorer_config options into billing dataset
- [ ]  Bump aws package version
- [ ]  Fix regions to accept a list of strings
- [ ]  Fix credential_profile_name
- [ ]  Change s3 input to aws-s3 input for logs
