### ISSUE TITLE
Integration Update Release Notes

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#5142]
Across our various integrations teams, we ship updates to integrations on a very regular cadence (weekly, at least). These updates typically includes bug fixes, new data streams, dashboard updates, improved ECS mappings and more. While having the ability to address bugs and ship enhancements out of band is amazing, users have a hard time deciphering that's included in integration updates, forcing them to blindly applying updates. 

As an example, the AWS integration has an update available. When a user clicks into the package, they are offered no information whatsoever as to what enhancements are included in the update. You can drill into settings to see the update available, but again, no information as to what's included. A user also has to manually go to the settings tab, they should be directed here by default when accessing via the 'Updates Available' page. They are currently directed to the Overview section of the integration. 

<img width="931" alt="Screenshot 2023-01-30 at 10 38 05" src="https://user-images.githubusercontent.com/62879768/215468512-f99d2712-a665-4008-aaaa-36018bc30c5b.png">

<img width="918" alt="Screenshot 2023-01-30 at 11 55 01" src="https://user-images.githubusercontent.com/62879768/215470377-11ff98f5-16c1-4349-8dfe-ab527b6bfd19.png">

Valuable information is included in the Changelog of each integration (e.g. [AWS Changelog](https://github.com/elastic/integrations/blob/main/packages/aws/changelog.yml)), but it resides on Github and we can't expect users to dig into Github just to understand what's included in an integration update. 

Proposal: Expose a 'description' field within Fleet, whereby integration developers can add what's included in the update, enabling users to have a clear understanding of the update. Could the current 'New Version Available' section, be an option for this?

Add a 'Changelog' section under Overview->Details of each integration, similar to our docs, e.g. [AWS Changelog in docs](https://docs.elastic.co/integrations/aws#changelog).

**Comment by jamiehynds** [comment]
@serenachou @danajuratoni @SubhrataK several users I've spoken to have reported this lack of visibility as an issue. Feel free to chime in if you've seen similar requests or have ideas on how to tackle it.

**Comment by serenachou** [comment]
cc @chriscressman  @DianaJourdan @danajuratoni  I agree that discoverability is an issue that we would share with our connector clients. It'd be good to have a similar consistent strategy on reporting deltas per release once we get to GA

**Comment by bmorelli25** [comment]
>  I think docs are only updated once a week so there could be a significant lag, resulting in users not having up to date release notes for integration updates.

That's unfortunately correct. With the pace of integration development, our docs on docs.elastic.co go out of date quite quickly. We're working towards a plan to automate documentation publishing, but that's a long ways away at this point.

**Comment by amitkanfer** [comment]
>> We're working towards a plan to automate documentation publishing

What does this mean? Is it a manual process today?
Anyway... if this is the case, perhaps we should link to [github]?(https://github.com/elastic/integrations/blob/main/packages/aws/changelog.yml).
I really *really* want to avoid adding product features that are not really necessary.

**Comment by bmorelli25** [comment]
Yes, it's manual. You can learn more about the problems with our documentation build process in https://github.com/elastic/observability-docs/issues/1848. Our proposal to change from .md to .mdx readme files is outlined in https://github.com/elastic/integrations/issues/4988.

**Comment by amitkanfer** [comment]
@jamiehynds 
> Valuable information is included in the Changelog of each integration (e.g. [AWS Changelog](https://github.com/elastic/integrations/blob/main/packages/aws/changelog.yml)), but it resides on Github and we can't expect users to dig into Github just to understand what's included in an integration update.

Not sure I agree. If there was a better option - yes, ofcourse.. but in light of not having up-to-date docs, I would just add something like "Github changelog is available [here](https://github.com/elastic/integrations/blob/main/packages/aws/changelog.yml)" at the end of what we have there today. It's not great, but it does solve the problem of not providing the information to the user.

> Proposal: Expose a 'description' field within Fleet, whereby integration developers can add what's included in the update, enabling users to have a clear understanding of the update. Could the current 'New Version Available' section, be an option for this?

What if the user is upgrading 5 versions as example? Now we need to build a logic to aggregate all the descriptions from all the versions in between? 

I really think that a simple link to the github changelog is 1000 times better compared to what we have today, and we should just do it. Whenever we'll have up-to-date docs, we'll just replace the link to there.

**Comment by joshdover** [comment]
> What if the user is upgrading 5 versions as example? Now we need to build a logic to aggregate all the descriptions from all the versions in between?

Ideally, we'd implement this as a registry which could display all of the changelogs between two version numbers. Agreed it's non-trivial and would take some effort.

+1 on linking to GitHub if feasible and low effort. Note that we'll need some special logic for any integrations not hosted in the integrations repo (Endpoint, APM, maybe others) and this could even change in the future and break links from older versions of Kibana.

**Comment by kpollich** [comment]
+1 on using GitHub changelog links as an interim fix while we sort out the automation around integrations docs @bmorelli25 has proposed in https://github.com/elastic/integrations/issues/4988 (@nimarezainia @mukeshelastic we should consider prioritizing this as it's a means to an end for the private changelog issue Nima linked above)

> Note that we'll need some special logic for any integrations not hosted in the integrations repo (Endpoint, APM, maybe others)

We'll probably need to hardcode "base URL's" for the individual repos in which these special cases live. I think this is certainly feasible.

**Comment by jen-huang** [comment]
> We'll probably need to hardcode "base URL's" for the individual repos in which these special cases live. I think this is certainly feasible.

Do we really need to link to Github? Can we just link to the `changelog.yml` file served up in package storage? For example: https://epr.elastic.co/package/1password/1.8.0/changelog.yml
It's the exact same content as what lives in Github but will let us avoid the risk of hardcoding Github paths.

**Comment by amitkanfer** [comment]
github is "prettier" vs. the raw yaml file viewer browsers provide. However, if it's a simpler implementation that will be less "fragile", I vote for the EPR option as you suggested @jen-huang .

**Comment by joshdover** [comment]
I don't love that it downloads a file instead of allowing me to easily see the content, but agree it allows us to avoid the GH linking problem. It also may work better for any air-gapped installs that have an on-prem EPR.

What I didn't realize is that we contain the entire changelog in every package release. This should make showing the correct changelog entries in the UI easier whenever we prioritize this.

**Comment by kpollich** [comment]
> I don't love that it downloads a file instead of allowing me to easily see the content

This might be a browser-specific detail. In Chrome and Safari, I see the raw YML as text. Firefox downloads the file, though. 

The `content-type` header returned from https://epr.elastic.co/package/1password/1.8.0/changelog.yml is `text/yaml; charset=UTF-8`. 

In Chrome, the request has an `accept` header of:

```
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9`
```

Firefox: 

```
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8`

Not sure what the actual difference is, but maybe a corner case we can reasonably accept for now. We could provide something like `?raw=true` query param to file URL's that forces a `content-type: text/html` header similar to what GitHub does.

**Comment by amitkanfer** [comment]
>  It also may work better for any air-gapped installs that have an on-prem EPR

I think this takes priority... doesn't it?

> We could provide something like ?raw=true query param to file URL's that forces a content-type: text/html header similar to what GitHub does?

sounds easy

**Comment by kpollich** [comment]
Example raw URL: https://raw.githubusercontent.com/elastic/kibana/main/config/kibana.yml

Specifies `content-type: text/plain` in response headers. Would probably be a quick implementation on https://github.com/elastic/package-registry to support `?raw` to force the content type and just link to EPR changelogs here.

**Comment by nimarezainia** [comment]
> Example raw URL: https://raw.githubusercontent.com/elastic/kibana/main/config/kibana.yml
> 
> Specifies `content-type: text/plain` in response headers. Would probably be a quick implementation on https://github.com/elastic/package-registry to support `?raw` to force the content type and just link to EPR changelogs here.

could we not then just go one step further and grep the descriptions field? or is that more than one line of code?

**Comment by kpollich** [comment]
@nimarezainia - We certainly have the data to parse the changelog and display it in some compelling way in the UI (probabl with hyperlinks and such as well), but I think the intent here is to ship something that surfaces the raw changelog without need for design input or further planning. 

If we create the `?raw` parameter in the package registry service and render a link to it in the integrations UI, we could get a quick win over a day or two and buy us time to think about how changelogs should be represented in a more formal way, including whether it's a priority for us or not.

**Comment by jen-huang** [comment]
I agree w/ Kyle. It will be more than "one line of code" to retrieve the file, parse updates from version X to Y, and display in the UI.

I created an internal implementation issue for the link work and have added it to Sprint 9 to target 8.8. I will leave this one in the backlog as a placeholder for the "full" version where the changelog is directly in the UI.

**Comment by joshdover** [comment]
> If we create the `?raw` parameter in the package registry service and render a link to it in the integrations UI, we could get a quick win over a day or two and buy us time to think about how changelogs should be represented in a more formal way, including whether it's a priority for us or not.

One thing to consider is that registries hosted on-prem may not be exposed to the end user's browser, only to the Kibana server. It also might actually be easier to add this flag to the existing Kibana API that allows fetching a single file from a package instead of the registry anyways, example: `/api/fleet/epm/packages/elasticsearch/1.2.0/changelog.yml`

**Comment by kpollich** [comment]
That's a good point, @joshdover - we can handle this entirely in Kibana then.

**Comment by jen-huang** [comment]
I am starting to think it might be a negligible difference in amount of work if we just show the contents in the UI right away 😅 We trade off the work for fetch single file as raw text for parsing yaml and returning the difference between the two versions. The link can instead open a modal similar to how LICENSE.txt and NOTICE.txt are shown today. @kpollich WDYT?

**Comment by kpollich** [comment]
@jen-huang Yeah thinking about this again you're probably right. I forgot about the "get file" API that already exists and satisfies a lot of our needs here. It should be fairly trivial to render changeling contents in a modal here.

**Comment by jen-huang** [comment]
https://github.com/elastic/kibana/issues/150754 updated with the new implementation details.

**Comment by kpollich** [comment]
Closing in favor of https://github.com/elastic/kibana/issues/150754
