### ISSUE TITLE
Publicising New Integrations

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#5143]
Across our various integration teams, we are consistency releasing new integrations across Security, Search and Observability, often in between stack releases. However, we have a discoverability problem. We are relying on users (and our internal SA, support and services teams) to randomly stumble across new integrations as they browse the Integrations section of Kibana. In [this case](https://github.com/elastic/integrations/issues/2333) we even ask a user to run a `curl` command against the Elastic Package Registry. 

The [integrations page](https://www.elastic.co/integrations/data-integrations) of our website is updated with each stack release, but it's just in alphabetical order with no indication of 'new' or 'recently added' integrations. 

Our [integration docs](https://docs.elastic.co/integrations) are updated weekly, but again, alphabetical and no indication of 'new' integrations. 

Our release blogs generally include a mention of new integrations, but these posts are generally made available several weeks after an integration has shipped and include a lot of content outside of integrations. 

I've spoken to several security users who keep a close eye on our integrations Github repo to monitor issues I create and open pull requests, but there has to be a better way to improve discoverability. 

**Proposal**
- Improve discoverability of new integrations in-product, on our website and on our docs site through a 'Recently Added' section, category, label or filter. 
- Leverage the Security News Feed and other in-product feeds to raise awareness of new integrations.

**Comment by jamiehynds** [comment]
@serenachou @danajuratoni @SubhrataK incase you are seeing similar requests. 

@jamesspi for any ideas on the PMM side. 

@mukeshelastic @dborodyansky incase this has been discussed on the Fleet side?

**Comment by serenachou** [comment]
I thought there were some improvements being discussed with the work that was designed for better search and category mapping on the integration page that could help showcase -> https://docs.google.com/spreadsheets/d/1NUR2ypKSjtHvrAq1MVK31SkVnzh7vQN8TptnwsayQmI/edit#gid=0 and from the Enterprise Search side, we were looking to harden up our guided onboarding experience to help too. 

cc @JessicaOTaylor & @kathleen-walker  for our PMM side

**Comment by andrewkroh** [comment]
From a package registry perspective, having a "publish date" available in API would enable some workflows that could produce lists of newly published integrations or integration versions. You could answer the question of "what's new since I last looked on <Month Day, Year>?"

Relates: https://github.com/elastic/package-registry/issues/886

**Comment by jamesspi** [comment]
@jamiehynds, we could potentially use the in-product news feeds for improved visibility. We could also think about a similar workflow that is used when new prebuilt rules are available for users (a banner is displayed).
