### ISSUE TITLE
Remove `Custom Filestream Logs` from public documentation

### ISSUE THREAD

**Issue by rdner** [elastic/integrations#5158]
`Custom Filestream Logs` was mistakenly promoted to production in Nov 2022, it was soon removed but the public documentation remained available to the public here https://docs.elastic.co/integrations/filestream

We need to remove this integration from the public documentation.

**Comment by rdner** [comment]
@elastic/obs-docs  and @elastic/security-docs please have a look.

**Comment by joepeeples** [comment]
Hi @rdner, thanks for the notice! The next scheduled weekly update of the integration docs is next Monday, Feb 6 — does this need to be removed more urgently, or is it OK to include in the scheduled update?

**Comment by rdner** [comment]
@joepeeples well, it's been there since November, I think it can wait for another week :)
