### ISSUE TITLE
Move `custom_logs` to `type: input`

### ISSUE THREAD

**Issue by hop-dev** [elastic/integrations#5162]
Move custom logs to be an input only package. 

We already have a test package version of custom logs which is an input package:

https://github.com/elastic/package-spec/tree/main/test/packages/custom_logs

We just need to port over the changes and run some tests to ensure the upgrade works smoothly.

**Comment by hop-dev** [comment]
CC @joshdover not a very exciting issue but just wanted to track the work :)

**Comment by jlind23** [comment]
@hop-dev @kpollich pulling it in the current sprint as Mark already started.
cc @cmacknz @pierrehilbert as Elastic Agent team owns this integration.

**Comment by hop-dev** [comment]
Currently blocked by https://github.com/elastic/package-spec/issues/480

**Comment by jlind23** [comment]
@kpollich @jen-huang This is blocked and the package spec related issue has not been prioritized yet. What should be the path forward? Should we replace one of the current ecosystem items with this in order to work on it for the current sprint?

**Comment by kpollich** [comment]
@jlind23 Yes it'd be good to prioritize the blocker on the ecosystem side and look to allocate some time to it in this sprint in order to unblock. Unless @hop-dev is able to work on it? Not sure how involved the spec changes will be.

**Comment by jlind23** [comment]
I will pull the other items in the current sprint and assign it to you @hop-dev

**Comment by hop-dev** [comment]
@jlind23  coincidentally I've just made the PR ready for review :)

**Comment by kpollich** [comment]
@amolnater-qasource - For QA here, we should test the following behavior

- Upgrading from `log-1.1.2` -> `log-2.0.0` version should preserve user settings, continue to function and ingest data as expected from a custom log file
- Selecting either an existing dataset or creating a new data set in the Fleet policy editor UI should route the custom log data properly
- Index template + ingest pipeline should be generated based on the dataset value selected when creating a custom logs policy

Let me or  @hop-dev know if anything needs additional clarity here.
