### ISSUE TITLE
Tenable.io integration fails after initial data pulls

### ISSUE THREAD

**Issue by eric-ooi** [elastic/integrations#5165]
The initial pull of Tenable.io data seems to work but then eventually fails with these types of errors in /opt/Elastic/Agent/data/elastic-agent-b8553c/logs:

```
{"log.level":"error","@timestamp":"2023-02-01T11:24:24.177Z","message":"Error while processing http request: failed to execute rf.collectResponse: failed to execute chain http client.Do: server responded with status code 404: {\"status\":404,\"message\":\"Export expired or not found\"}","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"httpjson-default","type":"httpjson"},"log":{"source":"httpjson-default"},"input_url":"https://cloud.tenable.com/assets/export","ecs.version":"1.6.0","log.logger":"input.httpjson-cursor","log.origin":{"file.line":135,"file.name":"httpjson/input.go"},"service.name":"filebeat","id":"httpjson-tenable_io.asset-2dfb7920-bbc5-498d-b04f-a3fa8a98eb10","input_source":"https://cloud.tenable.com/assets/export","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-02-01T11:24:50.040Z","message":"Error while processing http request: failed to execute rf.collectResponse: failed to execute chain http client.Do: server responded with status code 404: {\"error\":\"Chunk does not exist\"}","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"httpjson-default","type":"httpjson"},"log":{"source":"httpjson-default"},"service.name":"filebeat","ecs.version":"1.6.0","input_url":"https://cloud.tenable.com/vulns/export","log.logger":"input.httpjson-cursor","log.origin":{"file.line":135,"file.name":"httpjson/input.go"},"id":"httpjson-tenable_io.vulnerability-2dfb7920-bbc5-498d-b04f-a3fa8a98eb10","input_source":"https://cloud.tenable.com/vulns/export","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-02-01T20:51:21.565Z","message":"Error while processing http request: failed to execute rf.collectResponse: failed to execute http client.Do: server responded with status code 429: {\"values\":[\"19700f9e-4a62-4319-a8ea-fefb127cd8c9\",\"af9a1f1a-7837-4cfb-a514-181dd22df8f3\"],\"strings\":[\"Duplicate export (job_uuid=\",\" container_uuid=\",\"). not allowed. Please modify request or wait until existing export is complete.\"],\"empty\":false,\"bytes\":\"RHVwbGljYXRlIGV4cG9ydCAoam9iX3V1aWQ9MTk3MDBmOWUtNGE2Mi00MzE5LWE4ZWEtZmVmYjEyN2NkOGM5IGNvbnRhaW5lcl91dWlkPWFmOWExZjFhLTc4MzctNGNmYi1hNTE0LTE4MWRkMjJkZjhmMykuIG5vdCBhbGxvd2VkLiBQbGVhc2UgbW9kaWZ5IHJlcXVlc3Qgb3Igd2FpdCB1bnRpbCBleGlzdGluZyBleHBvcnQgaXMgY29tcGxldGUu\",\"value_count\":2}","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"httpjson-default","type":"httpjson"},"log":{"source":"httpjson-default"},"log.origin":{"file.line":135,"file.name":"httpjson/input.go"},"input_url":"https://cloud.tenable.com/vulns/export","ecs.version":"1.6.0","service.name":"filebeat","id":"httpjson-tenable_io.vulnerability-2dfb7920-bbc5-498d-b04f-a3fa8a98eb10","input_source":"https://cloud.tenable.com/vulns/export","log.logger":"input.httpjson-cursor","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-02-01T20:34:06.119Z","message":"Error while processing http request: failed to execute rf.collectResponse: failed to execute chain http client.Do: failed to execute http client.Do: failed to read http.response.body: Get \"https://cloud.tenable.com/vulns/export/19700f9e-4a62-4319-a8ea-fefb127cd8c9/status\": GET https://cloud.tenable.com/vulns/export/19700f9e-4a62-4319-a8ea-fefb127cd8c9/status giving up after 11 attempts","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"httpjson-default","type":"httpjson"},"log":{"source":"httpjson-default"},"ecs.version":"1.6.0","log.logger":"input.httpjson-cursor","service.name":"filebeat","id":"httpjson-tenable_io.vulnerability-2dfb7920-bbc5-498d-b04f-a3fa8a98eb10","input_source":"https://cloud.tenable.com/vulns/export","input_url":"https://cloud.tenable.com/vulns/export","log.origin":{"file.line":135,"file.name":"httpjson/input.go"},"ecs.version":"1.6.0"}
```

I tried restarting the agent and modifying the initial pull time and timeout durations but it would eventually fail each time. 

Using Elastic Agent 8.6.1 on Ubuntu 20.04 with Tenable.io integration 0.1.0.

**Comment by jamiehynds** [comment]
@vinit-elastic could you assign someone to investigate please?

**Comment by vinit-elastic** [comment]
Hey @eric-ooi,

Can you please share agent debug logs for tanable.io integration package as well as the whole configuration for this connector?
So, it will be easy to debug the error for us.

**Comment by eric-ooi** [comment]
Sure. How do I get the debug logs?

**Comment by Meet191100** [comment]
> Sure. How do I get the debug logs?

For downloading the diagnostics elastic-agent logs, follow this link: https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html#_collect_elastic_agent_diagnostics_bundle

For collecting fresh debug logs, please remove the existing integration policy, create a new policy, and assign it to the integration package.

**Comment by vinit-elastic** [comment]
> Sure. How do I get the debug logs?

For downloading the diagnostics elastic-agent logs, follow this link: https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html#_collect_elastic_agent_diagnostics_bundle

For collecting fresh debug logs, please remove the existing integration policy, create a new policy, and assign it to the integration package.

**Comment by vinit-elastic** [comment]
You can upload your logs in the following link, 

https://upload.elastic.co/u/ea6564fc-894a-4cc8-aa26-50995c2f395f

**Comment by eric-ooi** [comment]
I ran the debug log collection twice, once before making any changes and another after removing and creating a newly assigned policy.  They're suffixed with "BEFORE" and "AFTER" accordingly.

I also uploaded a screen shot of the current config.

Let me know if you need anything else.

**Comment by vinit-elastic** [comment]
> I ran the debug log collection twice, once before making any changes and another after removing and creating a newly assigned policy. They're suffixed with "BEFORE" and "AFTER" accordingly.
> 
> I also uploaded a screen shot of the current config.
> 
> Let me know if you need anything else.

Hey @eric-ooi  - Thanks for the logs. We have analyzed the logs and we observed a couple of things,

In many logs we saw, the server responded with staus code 429. Which represents we are making too many requests in a short period of time. One possiblity could be when the export job is in "processing" state and we make another export. And Tenable supports only two to three concurrent export jobs per account. [As mentioned Here](https://developer.tenable.com/docs/concurrency-limiting). 

We suspect that in this case we suspect that on the initial run where there might be a lot of data on the first run and as the value of "interval" is set to "5m", There's a possibility that we are still processing the initial request after 5 minutes, and we send another request which is causeing the API server to throw 429. 

Moreover, We would need the debug logs to investigate it further. I'd be great if you could send us those as well. For the elastic-agent debug logs, follow this link: 
Stand alone Elsatic Agent: https://www.elastic.co/guide/en/fleet/current/debug-standalone-agents.html#debug-standalone-agents
Fleet Managed Elastic Agent: https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html#change-logging-level

In the mean time can you try and increase the value of "interval".

**Comment by eric-ooi** [comment]
Thanks @vinit-elastic.  So I should change the logging level to debug and then run the same diagnostic command to collect the logs again?

**Comment by vinit-elastic** [comment]
Yes, please. Additionally, you can increase the value of the "interval" parameter as well. 

Moreover, I'm on PTO this week, @janvi-elastic would be assisting you in the meantime. :)

**Comment by eric-ooi** [comment]
Cool, enjoy your PTO!  I just uploaded a new set of debug logs after increasing interval to 30m.  Still seeing the same errors, so maybe a larger interval is needed.

**Comment by vinit-elastic** [comment]
Thanks @eric-ooi!
I'll forward the logs to Janvi she'll be able to take it up from here. Let us know if you still face the same issue even with the larger interval. 
Just one more thing I wanted to know is, can you confirm if there's only one integration of tenable io running or more? The Tenable API only supports 2-3 export jobs in parallel/account. So if you have any other services doing the export in the background it might cause issues as well.

**Comment by janvi-elastic** [comment]
Hey @eric-ooi , Thanks for the debug logs!!
We have gone through the debug logs, but we have found that they contain different package (Azure) logs. So it would be a great help for us if you could make a new integration policy and assign it solely to Tenable.io. For better understanding, could you please share all of the elastic agent's debug logs?

**Comment by eric-ooi** [comment]
Ok, I assigned it a policy with only the Tenable integration and uploaded a new debug log file.

**Comment by janvi-elastic** [comment]
Hey @eric-ooi - Thanks for the logs.

We have observed that when the export job is in the `Processing` state,  we won't be able to get the logs unless and until last call doesn't get  `Finished`. Could you please check whether your vulnerability export status is `Finished` or not?

Link for reference:
First call for export_uuid - https://developer.tenable.com/reference/exports-vulns-request-export
Second call for export status  - https://developer.tenable.com/reference/exports-vulns-export-status

If required we can schedule call and debug. Kindly update us once you verify.

**Comment by eric-ooi** [comment]
Ok, trying to run this and it does show "Processing."

**Comment by janvi-elastic** [comment]
Hey @eric-ooi,

We found that your vulnerability export status is taking more time in `PROCESSING` state, where as our integration waits for only 50s to get `FINISHED` state. So we are planning an enhancement that will allow users to increase the wait time.

**Comment by eric-ooi** [comment]
Great! Looking forward to trying it out.

**Comment by janvi-elastic** [comment]
Hey @eric-ooi,

We have raised a [PR](https://github.com/elastic/integrations/pull/5302) to address your issue. You will be able to update the package once PR has been merged.

**Comment by eric-ooi** [comment]
When will this update be available?  I saw that this issue was "closed" but I haven't yet seen the integration update nor been able to test to confirm.
