### ISSUE TITLE
MISP Integration v1.9.0 fails to pull attribute data from MISP

### ISSUE THREAD

**Issue by ar3diu** [elastic/integrations#5173]
I used this integration since it was released but I'm afraid that since the last update, it stopped working.

Elastic Version: 8.6.1
Elastic Agent Version: 8.6.1
MISP Integration: 1.9.0
Error Message:
```
Error while processing http request: failed to execute rf.collectResponse: failed to execute http client.Do: failed to execute http client.Do: failed to read http.response.body: Post "https://misp01/events/restSearch": POST https://misp01/events/restSearch giving up after 6 attempts
```

![image](https://user-images.githubusercontent.com/61625853/216329117-31090ca7-bb74-49b4-a939-79c970c7d436.png)

Fleet Policy configuration:
```
{
  "package": {
    "name": "ti_misp",
    "version": "1.9.0"
  },
  "name": "MISP Collector",
  "namespace": "bss",
  "description": "",
  "policy_id": "REDACTED",
  "inputs": {
    "ti_misp-httpjson": {
      "enabled": true,
      "streams": {
        "ti_misp.threat": {
          "enabled": true,
          "vars": {
            "api_token": "REDACTED",
            "initial_interval": "120h",
            "interval": "10m",
            "filters": "excludeDecayed: 1\nincludeDecayScore: 1\n",
            "ssl": "verification_mode: none",
            "url": "https://misp01",
            "preserve_original_event": false,
            "http_client_timeout": "30s",
            "tags": [
              "misp-threat"
            ]
          }
        }
      }
    }
  }
}
```

**Comment by rediasec** [comment]
Another error related to the same issue:

![image](https://user-images.githubusercontent.com/61625853/216342371-7da2e377-6d10-4e61-bddd-e905abd49a0a.png)

**Comment by rediasec** [comment]
All this while Filebeat with the Threat Intel module works perfectly.

**Comment by efd6** [comment]
@rediasec In 1.10.0 I added null deref checks that stopped this behaviour in testing. It's not clear to me why it didn't fail prior to 1.9.0 since that change should not affect this, but would you please try upgrading to 1.10.0 to see if that has resolved your issue?

**Comment by rediasec** [comment]
Did the update, rechecked the URL endpoint but still getting these errors:
![image](https://user-images.githubusercontent.com/61625853/217469242-e94fc5b8-0c3f-4900-b5f4-8ae2aea673dd.png)

```
Error while processing http request: failed to execute rf.collectResponse: failed to execute http client.Do: failed to execute http client.Do: failed to read http.response.body: Post "https://misp01:443/events/restSearch": context canceled
```
```
read token request for getting IMDSv2 token returns empty: Put "http://169.254.169.254/latest/api/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers). No token in the metadata request will be used.
```

**Comment by anrsec** [comment]
I just tried the latest version of the integration (1.10.1), but the same errors show up:

![image](https://user-images.githubusercontent.com/61625853/227258446-0192f713-288a-40ef-b0d0-4882ce76195a.png)

**Comment by chrisberkhout** [comment]
Hi @ar3diu,

we've recently made quite a few changes to the MISP integration, so I suggest trying with the latest version: 1.31.0.

From the information you provide it looks like there may be a network issue.

I suggest enabling request tracing (under "Advanced options") when adding the policy, then after running for a bit, get the agent diagnostics bundle as described [here](https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html#trb-collect-agent-diagnostics). In that bundle you should find information about requests and responses (note that large responses may be dropped from the log), and you can see if there is error information in the responses, and try replicating the requests with curl. The bundle may include sensitive information, so don't share any part of it without carefully reviewing it first.

**Comment by ar3diu** [comment]
Yes, I have used the newer versions since posting this and do not remember to have encountered these issues again. Thanks for this answer anyway!🙌
