### ISSUE TITLE
Add ability to specify custom Windows event Provider at elastic agents Integration 

### ISSUE THREAD

**Issue by Skoetting** [elastic/integrations#521]
With the elastic agent Windows Integration we can easily add the basic windows logs to our elastic cluster. In our use case we have some additional event provider we want to collect in addition to system, application, powershell, etc. (The predefined one)
With winlogbeat we can easily add these logs like winlogon or Group Policy. Would be nice to have this possibility also in the windows integration for the elastic agents.
For my use case this would be the reason why I still need to use the classic winlogbeat.

**Comment by jamiehynds** [comment]
Thanks for raising this @Skoetting, this is certainly on our radar. Our plan is to add a 'Custom Windows Events' section to the existing Windows integration whereby you can add channels outside of Security, System, PowerShell, etc.

**Comment by jamiehynds** [comment]
Closing this ticket in favor of https://github.com/elastic/integrations/issues/317
