### ISSUE TITLE
[beat] update stats fields including the new apm_server fields

### ISSUE THREAD

**Issue by crespocarlos** [elastic/integrations#5225]
## Summary

APM server [added new metric fields ](https://github.com/elastic/apm-server/commit/2e58ae3ad343b6520a5aef047b50e2bc019ddab1#diff-20f700df6ec50fcbecb398cba4104ea382244cc68006978dcde3a107b5e12b7cR254), and the beat integration package started to [fail in CI](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-5130/7/tests/), complaining about these fields

### AC
- Test should pass with latest apm_server:8.7.0-snapshot image

**Comment by crespocarlos** [comment]
@klacabane we might need to put together a process, to make sure new fields are also mapped in the integration package and beats.

**Comment by klacabane** [comment]
How did we find about the failure, does the team get a notification ?
