### ISSUE TITLE
[Custom TCP/UDP Logs] Add ability to apply custom configurtion to Custom TCP & UDP logs

### ISSUE THREAD

**Issue by nimarezainia** [elastic/integrations#5229]
The Custom logs integration has yaml box where additional configuration not yet supported via UI can be applied:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/13442829/217963011-2037af67-9dd1-475b-9bb5-0af8d4c11506.png">

This requirement to have the same custom configuration YAML box applied to the TCP and UDP custom log integrations

**Comment by jen-huang** [comment]
@elastic/security-external-integrations Can you take a look at this for the TCP and UDP packages?

**Comment by nimarezainia** [comment]
fyi @jamiehynds
