### ISSUE TITLE
[Cisco ASA] Add support for additional Cisco log types

### ISSUE THREAD

**Issue by narph** [elastic/integrations#5256]
Add support for additional Cisco ASA and SSL VPN authentication messages

| ID  | Type | Message | 
| ------------- | ------------- |------------- |
| `106006` |
| `106012` |
| `113008` |
| `113009` |
| `113015` |
| `113039` |
| `302010` |
| `315011` |
| `716002` |
| `716058` |
| `716059` |
| `721016` |
| `721018` |
| `722022` |
| `722023` |
| `722028` |
| `722032` |
| `722033` |
| `722034` |
| `722055` |
| `725001` |
| `725002` |
| `725007` |
| `725016` |
| `737003` |
| `737006` |
| `737016` |
| `737026` |
| `737034` |
| `113019` | disconnect | `Group = Development, Username = some.user, IP = 123.123.123.123, Session disconnected.` |
| `737016` | system  | `Freeing local pool some-named-client01 address 123.123.123.123` |
| `113005` | failure | `AAA user authentication Rejected : reason = AAA failure : server = 123.123.123.123 : user = some.user : user IP = 123.123.123.123` |
| `716039` | failure | `Group <DfltGrpPolicy> User <some.user> IP <123.123.123.123> Authentication: rejected, Session Type: WebVPN.` |
| `113004` | success | `AAA user authentication Successful : server =  123.123.123.123 : user = some.user` |
| `113009` | success | `AAA retrieved default group policy (ProductionGP) for user = some.user` |
| `113008` | success | `AAA transaction status ACCEPT : user = some.user` |
| `722055` | success | `%ASA-svc-6-722055: Group <some-client> User <some.user> IP <123.123.123.123> Client Type: Cisco AnyConnect VPN Agent for Mac OS X 4.8.01090` |
| `716003` | success | `WebVPN access GRANTED: https://123.123.123.123//api/languages?token=REDACTED4F7859A219B61DB0A3E546A586C173A6B5BBFDBB73D08490070855526` |

**Comment by richardleeps** [comment]
Can we add 722055

%ASA-6-722055: Group <GROUP-POLICY> User <user.name@domain.com> IP <external IP> Client Type: Cisco AnyConnect VPN Agent for Windows 4.10.08025

We would like to extract 
- Group Policy
- Username
- External IP
- Anyconnect version (Windows 4.10.08025)

Solution

Group <%{NOTSPACE:cisco.asa.webvpn.group_name}> User <%{NOTSPACE:source.user.name}> IP <%{IP:source.address}> Client Type: Cisco AnyConnect VPN Agent for %{NOTSPACE:client.type}
