### ISSUE TITLE
Airflow TSDB Enablement

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#5275]
## Test Environment Setup
- [x] Creation of Airflow Test Environment.

## Datastream : StatsD 
  - [x] Add dimension fields 
         https://github.com/elastic/integrations/pull/5847
- [x] #6729
        https://github.com/elastic/integrations/pull/7469
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.

## Issues
  - https://github.com/elastic/kibana/issues/155004. [Blocker for metric_type]
  - https://github.com/elastic/integrations/issues/7504

Enable TSDB by default: https://github.com/elastic/integrations/pull/6776

## Screenshots

<img width="1635" alt="Screenshot 2023-07-03 at 12 35 59 PM" src="https://github.com/elastic/integrations/assets/102972658/b6dc0c9b-7567-4bcd-a4a7-af36ef47f262">
<img width="1694" alt="Screenshot 2023-07-03 at 12 36 17 PM" src="https://github.com/elastic/integrations/assets/102972658/acee2ba2-e401-4777-be50-2b5a8abc75e9">
<img width="823" alt="Screenshot 2023-07-03 at 12 36 35 PM" src="https://github.com/elastic/integrations/assets/102972658/7705c983-db1b-4398-a491-f64600b22558">
<img width="765" alt="Screenshot 2023-07-03 at 12 36 50 PM" src="https://github.com/elastic/integrations/assets/102972658/a0a4c3f8-a4de-49ea-a7ac-8f3b09207d3b">

**Comment by agithomas** [comment]
@ritalwar , please update the issue with the current status and please link the issue related to the metric_type mapping here. Also, add the details of the issue under Meta.

**Comment by ritalwar** [comment]
Closing this issue for now.

I'll create a metric_type PR once metric_type mapping for dynamic templates is available.

**Comment by lalit-satapathy** [comment]
@ritalwar, Can the metric_type mapping be added now since https://github.com/elastic/kibana/issues/155004 is fixed. Also, keeping this meta open for now.
