### ISSUE TITLE
MSSQL TSDB Enablement

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#5278]
## Test Environment Setup
- [x] Creation of MSSQL Test Environment

## Datastream : Performance 
  - [x] Add dimension fields
          https://github.com/elastic/integrations/pull/5519
  - [x] Adding metric_type mapping
         https://github.com/elastic/integrations/pull/5532
    
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if dimension field mapping is correct in the data stream template.

## Datastream : Transaction Log 
  - [x] Add dimension fields 
          https://github.com/elastic/integrations/pull/5540
  - [x] Adding metric_type mapping - Already available
    
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.

**Comment by ritalwar** [comment]
Verified data loading, count and dimensions after enabling : Time-series indexing (TSDB) flag in kibana.
