### ISSUE TITLE
MongoDB TSDB Enablement

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#5281]
## Test Environment Setup
- [x] Creation of MongoDB Test Environment

## Datastream : collstats 
  - [x] Add dimension fields
          https://github.com/elastic/integrations/pull/5945
  - [x] Adding metric_type mapping
          https://github.com/elastic/integrations/pull/5986
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if dimension field mapping is correct in the data stream template.

## Datastream : dbstats
  - [x] Add dimension fields 
          https://github.com/elastic/integrations/pull/5987
  - [x] Adding metric_type mapping
          https://github.com/elastic/integrations/pull/5998
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.
 
## Datastream : metrics
  - [x] Add dimension fields 
          https://github.com/elastic/integrations/pull/6027
  - [x] Adding metric_type mapping
         https://github.com/elastic/integrations/pull/6042
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.

## Datastream : replstatus
  - [x] Add dimension fields 
          https://github.com/elastic/integrations/pull/6234
  - [x] Adding metric_type mapping
          https://github.com/elastic/integrations/pull/6235
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.

## Datastream : status
  - [x] Add dimension fields 
           https://github.com/elastic/integrations/pull/6100
  - [x] Adding metric_type mapping
          https://github.com/elastic/integrations/pull/6103
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.

**Comment by ritalwar** [comment]
I'm currently debugging the replStatus data stream to collect metrics, but I'm running into an error when trying to retrieve data from the oplog.rs collection.

**Comment by ritalwar** [comment]
Managed to run a new instance using docker and obtained the required data. PRs for the replstatus datastream have also been raised.

**Comment by lalit-satapathy** [comment]
@ritalwar, Can we also link to the TSDB-mode dashboard images in these meta issues? That will be a good reference in the review.

**Comment by ritalwar** [comment]
MongoDB metrics  Dashboard verified after enabling TSDB:

<img width="1694" alt="Screenshot 2023-06-28 at 11 00 20 AM" src="https://github.com/elastic/integrations/assets/102972658/b871b1a2-ff30-4a11-80cf-052dfc9f3e64">
<img width="1697" alt="Screenshot 2023-06-28 at 11 00 30 AM" src="https://github.com/elastic/integrations/assets/102972658/eca8c517-d5e5-4c89-ac66-d1b64deda12d">
