### ISSUE TITLE
AWS Security Lake

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#5286]
### Description
Amazon Security Lake automatically centralizes security data from cloud, on-premises, and custom sources into a purpose-built data lake stored in your account. Security Lake makes it easier to analyze security data so that you can get a more complete understanding of your security across the entire organization. Security Lake automatically gathers and manages all your security data across accounts and Regions. You can use your preferred analytics tools while retaining control and ownership of your security data. Security Lake has adopted the Open Cybersecurity Schema Framework (OCSF), an open standard. It helps normalize and combine security data from AWS and a broad range of enterprise security data sources. Now, your analysts and engineers can get broad visibility to investigate and respond to security events and improve your security across the cloud and on premises.

Security Lake supports events from AWS services such as Cloudtrail, VPC Flow, Security Hub, GuardDuty, etc, but also supports events from cybersecurity vendors including CrowdStrike, Zscaler, Tanium and others. For a full list of 'source partners' see [here](https://aws.amazon.com/security-lake/partners/). 

Our focus is towards becoming a '[Subscriber Partner](https://aws.amazon.com/security-lake/partners/)' whereby we can ingest data from AWS Services and Source Partners via Security Data lake. 

### Architecture
Security Lake is based on S3 storage and the data is stored in [Parquet files](https://parquet.apache.org/). As mentioned above, events are mapped to the Open Cybersecurity Schema Framework. Mappings will be have to be implemented to transform this data to ECS, to ensure data ingested via Security Lake can be leveraged by our Security app. 

### Related Issues

- Depends on: https://github.com/elastic/beats/issues/34662

### Additional Resources
Getting Started Guide - https://docs.aws.amazon.com/security-lake/latest/userguide/getting-started.html
[Security Lake Product Page](https://aws.amazon.com/security-lake/)
[Security Lake Product Integrations](https://docs.aws.amazon.com/security-lake/latest/userguide/integrations-overview.html)
[OCSF announcement blog](https://aws.amazon.com/blogs/security/aws-co-announces-release-of-the-open-cybersecurity-schema-framework-ocsf-project/)
[Security Lake Pricing](https://aws.amazon.com/security-lake/pricing/)

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by andrewkroh** [comment]
One open question from me is whether there will be any reason to reuse existing pipelines for processing data like Cloudtrail and VPC flow. And do we want to route data to the data streams like `logs-aws.cloudtrail-*` or have it in its own Security Lake data stream?

**Comment by andrewkroh** [comment]
Related: https://github.com/elastic/beats/issues/36321
