### ISSUE TITLE
[Mimecast] Duplicate events

### ISSUE THREAD

**Issue by jmyns** [elastic/integrations#5293]
The mimecast integration creates duplicate events if no new events are present.  ttp_url_logs seem to be particularly noisy.  If a suitable id does not exist, can you set the _id based on the hash of the event? 

For ttp_url_logs specifically, a hash of the messageId and date might be suitable.

Similar to  #5010.

**Comment by efd6** [comment]
@jmyns Can you confirm that the `event.original` in the duplicate documents looks something like `{..., "data":[]}`?

**Comment by jmyns** [comment]
Hi @efd6 , The empty data issue may have been a separate issue...  I noticed that problem with DLP logs where we'd continuously receive empty results.  But we were on mimecast 0.0.12 at the time and recently switched to 1.6.0 

The issue I am referring to may be a problem with the cursor not updating or because the events are not using a unique id.  For example here is a recent example of 4 duplicate events generated at 8:50:25.  The interval for this dataset is 5m, so we see 4 instances of the event in kibana. (The events all contain the same event.original data).

![image](https://user-images.githubusercontent.com/10801754/220662903-068978e4-8a48-4895-a7ea-b892171bddc6.png)

Here are the raw API response from that approximate time.         
```
{
    "meta": {
        "pagination": {
            "pageSize": 2,
            "totalCount": 2
        },
        "status": 200
    },
    "data": [
        {
            "clickLogs": [
                {
                    "userEmailAddress": "<redacted>",
                    "fromUserEmailAddress": "<redacted>"",
                    "url": "<redacted>",
                    "ttpDefinition": "Default Inbound URL Protect Definition",
                    "subject": "RE: Question!",
                    "action": "allow",
                    "adminOverride": "N/A",
                    "userOverride": "None",
                    "scanResult": "clean",
                    "category": "Health & Medicine",
                    "sendingIp": "<redacted>"",
                    "userAwarenessAction": "N/A",
                    "date": "2023-02-22T14:07:47+0000",
                    "actions": "Allow",
                    "route": "inbound",
                    "creationMethod": "User Click",
                    "emailPartsDescription": [
                        "Body"
                    ],
                    "messageId": "2"
                },
                {
                    "userEmailAddress": "<redacted>"",
                    "fromUserEmailAddress": "<redacted>"",
                    "url": "<redacted>",
                    "ttpDefinition": "Default Inbound URL Protect Definition",
                    "subject": "Welcome",
                    "action": "allow",
                    "adminOverride": "N/A",
                    "userOverride": "None",
                    "scanResult": "clean",
                    "category": "Entertainment",
                    "sendingIp": "<redacted>",
                    "userAwarenessAction": "N/A",
                    "date": "2023-02-22T13:50:25+0000",
                    "actions": "Allow",
                    "route": "inbound",
                    "creationMethod": "User Click",
                    "emailPartsDescription": [
                        "Body"
                    ],
                    "messageId": "1"
                }
            ]
        }
    ],
    "fail": []
}
```

When the problem happens, note that it sends the "old" event every 5 minutes according to the interval.  When a new event is detected (ie messageId = 2), then the problem begins for the new latest event. We continue to receive event 2 until a new event is detected.

**Comment by efd6** [comment]
@jmyns Are you able to provide
- [ ] The document above but with the redactions to be consistent across log events (i.e. if the same value appears in two places it is replaced with the same readaction string, but unique between different redactions).
- [ ] The ingested JSON document corresponding to the events with the same redactions made.

**Comment by jmyns** [comment]
Here are the raw ingested events and mimecast responses with redactions removed. (Both files are json but I could only upload as txt files). The raw ingested file contains all of the events as outlined in the screenshot.
[mimecast.ttp_url.raw-api-response.txt](https://github.com/elastic/integrations/files/10814451/mimecast.ttp_url.raw-api-response.txt)
[mimecast.ttp_url.raw-ingested.txt](https://github.com/elastic/integrations/files/10814452/mimecast.ttp_url.raw-ingested.txt)

![image](https://user-images.githubusercontent.com/10801754/220933127-827cf8cc-c4a4-4adb-a048-c44c28f3f8bf.png)

**Comment by efd6** [comment]
@jmyns Thanks. That was helpful.

**Comment by jmyns** [comment]
Thank you @efd6 and elastic team for responding to this so quickly!

**Comment by jmyns** [comment]
I don't believe this is fixed.  I haven't debugged it yet, but the agent is still sending us duplicate events based on whatever interval is set on the dataset. I'm noticing it on ttp_url_logs and ttp_ip_logs but perhaps others as well.

**Comment by efd6** [comment]
@jmyns Is this still working for you?
