### ISSUE TITLE
[Zscaler Private Access] Issue mapping `event.created` in audit logs

### ISSUE THREAD

**Issue by srilumpa** [elastic/integrations#5346]
Hello,

I have noticed a mapping issue for the `event.created` field set [here](https://github.com/elastic/integrations/blob/main/packages/zscaler_zpa/data_stream/audit/elasticsearch/ingest_pipeline/default.yml#L37) and introduced in 71c5255ef7c411a56b9b34ba8ec07b9cd66187d0. This change made the `event.created` field mapped to a `keyword` type instead of a date, either because the `set` processor copies it as a string or because the mapping of this specific field is not set for the data stream.

If needed, I can prepare a PR to try to fix this issue.

**Comment by vinit-elastic** [comment]
Hey @srilumpa - Thanks for bringing it to our attention.  
As you mentioned, it seems like there is some issue with the ECS mappings, and I really appreciate your willingness to raise a PR. However, we are already working on an enhancement in the package, where we are planning to leverage the newly introduced dynamic ECS, which would resolve this issue. 
I will keep you posted on any updates. 😄
