### ISSUE TITLE
[Cisco Secure Endpoint] Parse additional fields to ECS

### ISSUE THREAD

**Issue by MakoWish** [elastic/integrations#5352]
There are additional fields in the Cisco Secure Endpoint events that can be parsed into ECS fields. Some examples are:

*  `cisco.secure_endpoint.computer.network_addresses` --> `host.ip` and `host.mac`
* `cisco.secure_endpoint.computer.connector_guid` --> `host.id`
* `cisco.secure_endpoint.error.description` --> `error.message`
* `cisco.secure_endpoint.error.error_code` --> `error.code`
* `cisco.secure_endpoint.group_guids` --> `group.id`

Thank you,
Eric

**Comment by MakoWish** [comment]
ping @elasticmachine

**Comment by MakoWish** [comment]
@jamiehynds,

I think quite a few changes need to be done to this integration. 

## Parse out `host.ip` and `host.mac` fields:

```
    {
      "script": {
        "description": "Parse out host.ip from array of network_addresses.",
        "if": "ctx?.cisco?.secure_endpoint?.computer?.network_addresses != null",
        "lang": "painless",
        "source": """if (ctx?.host?.ip == null) {
  ctx.host.ip = new ArrayList();
}
for (addr in ctx?.cisco?.secure_endpoint?.computer?.network_addresses) {
  if (addr.ip != null && !addr.ip.isEmpty()) {
        ctx.host.ip.add(addr.ip);
  }
}"""
      }
    },
    {
      "script": {
        "description": "Parse out host.mac from array of network_addresses.",
        "if": "ctx?.cisco?.secure_endpoint?.computer?.network_addresses != null",
        "lang": "painless",
        "source": """if (ctx?.host?.mac == null) {
  ctx.host.mac = new ArrayList();
}
for (addr in ctx?.cisco?.secure_endpoint?.computer?.network_addresses) {
  if (addr.mac != null && !addr.mac.isEmpty()) {
        ctx.host.mac.add(addr.mac);
  }
}"""
      }
    }
```

## Utilize `vulnerability.*` fields

## Utilize `error.*` fields

## Utilize `rule.*` fields

## Utilize `group.*` fields

## Parse out `cisco.secure_endpoint.bp_data` to explicit fields instead of a "flattened" field that cannot be aggregated

Thoughts?

Eric

**Comment by LaZyDK** [comment]
@MakoWish do you need anything for this to be ready for review? We would like it in production, and it looks great :)

**Comment by MakoWish** [comment]
Hi @LaZyDK ,

I am [having an issue](https://github.com/elastic/integrations/pull/6258/#issuecomment-1569066252) with setting the `error.message` field, so I decided to just leave that out for now. I had to resolve some conflicts with another recent merge, but I marked the PR as ready for review.

**Comment by LaZyDK** [comment]
I just created another pull request for this integration for cleaner data #6419.
