### ISSUE TITLE
PANW value in labels.decrytped_traffic does not match Palo management console

### ISSUE THREAD

**Issue by NateUT99** [elastic/integrations#5358]
While reviewing logs ingested using the panw.panos integration, I noticed that the "labels.decrypted_traffic" value is opposite of what is shown in the Panorama management console. I have provided two examples below, with screenshots from both Elastic and Panorama as well as the event.original for both logs. I can certainly provide additional examples of this as needed (only modified to redact some potentially sensitive information).

**Palo Says Not Decrypted, Elastic Says Decrypted**
> Kibana Screenshot:
> <img width="1774" alt="Screenshot 2023-02-22 at 12 34 04 PM" src="https://user-images.githubusercontent.com/48816468/220712018-3eeb12e9-5fe4-4d79-80ea-942bfb6a40d5.png">

> Panorama (Palo) Screenshot:
> <img width="1420" alt="Screenshot 2023-02-22 at 12 32 37 PM" src="https://user-images.githubusercontent.com/48816468/220712753-46e38dde-4c4e-4054-aede-0c4952386857.png">

> event.original: 
`<14>1 2023-02-22T17:12:06.344Z stream-logfwd20-ad3f08db--01090836-h2je-harness-1f5n logforwarder - panwlogs - 1,2023-02-22T17:12:05.000000Z,no-serial,THREAT,url,10.0,2023-02-22T17:11:58.000000Z,10.176.0.17,10.1.8.138,,,Allow-Data-Center-Default,user.name@company.com,,ssl,vsys1,trust,inter-fw,tunnel.1,tunnel.2001,prisma-access-logging,,487561,1,55637,443,0,0,0xb400,tcp,alert,hostname.company.com/,,motor-vehicles,Informational,client to server,24388748,0xa800000000000000,10.0.0.0-10.255.255.255,10.0.0.0-10.255.255.255,,,0,,,0,,,,,,,,,1071,1101,0,0,,GP cloud service,,,,unknown,0,,0,1970-01-01T00:00:00.000000Z,N/A,unknown,0,0,,,,"motor-vehicles,low-risk",b391a50d-8807-4e45-839a-dc24d7aa1509,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,2023-02-22T17:11:58.398000Z,,,`

**Palo Says Decrypted, Elastic Says Not Decrypted**
> Kibana Screenshot:
> <img width="1749" alt="Screenshot 2023-02-22 at 12 36 07 PM" src="https://user-images.githubusercontent.com/48816468/220713412-aabbbfeb-4140-42e1-b1e6-a26eb99b4b67.png">

> Panorama (Palo) Screenshot:
> <img width="1400" alt="Screenshot 2023-02-22 at 12 36 56 PM" src="https://user-images.githubusercontent.com/48816468/220713569-68d0d0b3-f0bd-4242-b11e-7d979782da5a.png">

>event.original:
`<14>1 2023-02-22T17:10:26.725Z stream-logfwd20-ad3f08db--01090836-h2je-harness-1f5n logforwarder - panwlogs - 1,2023-02-22T17:10:25.000000Z,no-serial,THREAT,url,10.0,2023-02-22T17:10:07.000000Z,10.176.0.17,52.96.163.34,208.127.241.85,52.96.163.34,B-Important-URL-Allow,user.name@company.com,,office365-enterprise-access,vsys1,trust,untrust,tunnel.1,ethernet1/1,prisma-access-logging,,381894,1,50910,443,21316,443,0x140b000,tcp,alert,outlook.office365.com/autodiscover/autodiscover.json/v1.0/mailbox@company.com?Protocol=Autodiscoverv1,,low-risk,Informational,client to server,24388572,0xa800000000000000,10.0.0.0-10.255.255.255,US,,text/xml,0,,,152,Microsoft Office/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.15928; Pro),,,,,,,,1071,1101,0,0,,GP cloud service,,,,get,0,,0,1970-01-01T00:00:00.000000Z,N/A,unknown,0,0,,,,"computer-and-internet-info,low-risk",b1c5e8a3-6adb-4e5e-b90b-bf2cbe6bd724,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,2023-02-22T17:10:07.773000Z,,,`

**Comment by efd6** [comment]
The [PANW docs](https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/decryption-log-fields) say the following in the **Flags (flags)** section:

> 32-bit field that provides details on session; this field can be decoded by AND-ing the values with the logged value:
>
> - 0x00000400—decrypted traffic is being sent out clear text through a mirror port

In the events above we get the following:

- first event (`"@timestamp": "2023-02-22T17:12:06.344Z"`) has flags 0xb400 (& 0x00000400 == TRUE)

- second event (`"@timestamp": "2023-02-22T17:10:26.725Z"`) has flags 0x140b000 (& 0x00000400 == FALSE)

So the script is doing the correct thing if the word "decrypted" in the docs' sentence means the same thing as it does in the Panorama screen shot. Perhaps the meaning is inverted? Or alternatively the Panorama implementation is incorrect.

**Comment by NateUT99** [comment]
The logs that I provided are [URL](https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/url-filtering-log-fields) (which I believe are sent as THREAT), and not DECRYPTION as noted in the document link you provided. That said, I believe the flag values are the same. 

The description for 0x00000400 does not match what is occurring in this transaction. The "decrypted" checkbox in Panorama simply indicates (at least in this case) that SSL decryption/inspection was enabled for the outbound traffic to the Internet, so the communication was decrypted, inspected, and then re-encrypted on its way to its final destination. If I had to guess, I would think the correct value would be 0x01000000—SSL session is decrypted (SSL Proxy). Admittedly I am not super familiar with this dataset; if you believe the script is working correctly, I can open a support case with Palo.

**Comment by efd6** [comment]
@NateUT99 thanks for following this up.

**Comment by dhruvil-elastic** [comment]
Hi @NateUT99 ,

We did extensive digging into the problem and script. And we discovered this [document](https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000Cm1JCAS) on the Paloalto support site that describes how to decode the flag field value (hex value).

And this is exactly what the script that decodes flag value does.

As a result, we believe there has been some modification from the Paloalto side.

**Comment by NateUT99** [comment]
Thanks @dhruvil-elastic! From my own observations, I think you may be correct. I hope to hear something back from them today and will pass along.

**Comment by efd6** [comment]
I didn't notice that there are two flags for decrypted. I think this probably explains the situation. The example posted by @dhruvil-elastic handles 0x01000000 — "SSL session is decrypted (SSL Proxy)" which we map as `labels.ssl_decrypted` while the field in the OP (and the one addressed in my post) is `labels.decrypted_traffic`.

@NateUT99 Please check that `labels.ssl_decrypted` matches the Panorama rendering.

**Comment by NateUT99** [comment]
@efd6 I took a look at the logs and this does appear to match what I see in both Kibana and Elastic. labels.ssl_decrypted is appearing as "true" in the correct instances. It looks like a simple misunderstanding between the two similiar labels (labels.decrypted_traffic and labels.ssl_decrypted). Thanks to both yourself and @dhruvil-elastic; I'll go ahead and close this issue.
