### ISSUE TITLE
Add IOC expiration support to all TI providers

### ISSUE THREAD

**Issue by narph** [elastic/integrations#5369]
Meta issue https://github.com/elastic/security-team/issues/5868 for detailed info.

Once support for IOC expiration has been implemented in https://github.com/elastic/security-team/issues/6114 then this should be applied (if necessary) in all the `ti_*` packages. The following list of packages are in priority order:

- [x] [ti_abusech](https://github.com/elastic/integrations/tree/main/packages/ti_abusech) (Free)
- [x] [ti_otx](https://github.com/elastic/integrations/tree/main/packages/ti_otx) (Free)
- [x] [ti_misp](https://github.com/elastic/integrations/tree/main/packages/ti_misp) (Free)
- [x] [ti_cybersixgill](https://github.com/elastic/integrations/tree/main/packages/ti_cybersixgill) (Commercial)
- [x] [ti_threatq](https://github.com/elastic/integrations/tree/main/packages/ti_threatq) (Commercial)
- [x] [ti_cif3](https://github.com/elastic/integrations/tree/main/packages/ti_cif3) (Free)
- [x] [ti_rapid7_threat_command](https://github.com/elastic/integrations/tree/main/packages/ti_rapid7_threat_command) (Commercial)
- [x] [ti_anomali](https://github.com/elastic/integrations/tree/main/packages/ti_anomali) (Commercial)
- [x] [ti_recordedfuture](https://github.com/elastic/integrations/tree/main/packages/ti_recordedfuture) (Commercial)
- [x] [ti_opencti](https://github.com/elastic/integrations/tree/main/packages/ti_opencti) (Free)

**Comment by P1llus** [comment]
Not all of these packages are applicable, and the "solution" is different for each TI package, for example Recorded Future does not have any expiry dates, and the issue there is much different than with Anomali.

While maybe one or two more of the TI packages might be applicable, the focus should really be on the ones that customers have been asking for (Anomali and RF), and we should take a look at some of the others individually once the first 2 are done.

**Comment by LaZyDK** [comment]
And MISP.

**Comment by P1llus** [comment]
> And MISP.

The issue with MISP is going to be the fact that every source would be different, there is no specific format we can follow

**Comment by kcreddy** [comment]
PR for RecordedFuture https://github.com/elastic/integrations/pull/5460
PR for Anomali https://github.com/elastic/integrations/pull/5582

**Comment by kcreddy** [comment]
`ti_abusech`: I couldn't find documentation about indicator expiration in AbuseCH docs. Since they didn't have any communication channel, I filled up the form requesting information on the same: https://www.spamhaus.com/contact-us-abuse-ch/

`ti_otx`: The API thats currently being used is no longer supported as per API documentation: https://otx.alienvault.com/assets/static/external_api.html#Home. Created an issue: https://github.com/AlienVault-OTX/OTX-Python-SDK/issues/70 for get more info.

**Comment by chrisberkhout** [comment]
@kcreddy I've got most a solution for OpenCTI done. I just have some field type issues and dashboard filtering to adjust and then I'll open a PR.
