### ISSUE TITLE
Enable backward compatibility tests

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#537]
Currently, integrations are tested only against the newest version of the stack. The goal of this issue is to enable tests against older supported stacks to make sure that there haven't been introduced any incompatible changes.

**Comment by andresrc** [comment]
I understand we would only test against older versions if they are supported by the minimum version metadata, wouldn't we?

**Comment by mtojek** [comment]
Yes, you're right.

The procedure would be as follows:
1. Run older version of stack.
2. Go over local packages, check if the Kibana version is within the constraints range (it means: the package should be valid in the Kibana).
3. Try to install the package.

I assume that we should do it for the latest (3?) supported stack releases.

**Comment by mtojek** [comment]
Action items:

- [ ] Extract `install` step as CLI action https://github.com/elastic/elastic-package/issues/87 
- [ ] Extend Jenkinsfile to start older stacks

**Comment by mtojek** [comment]
I'm going to start adjusting the Jenkinsfile for Integrations.
