### ISSUE TITLE
[Linux Metrics Integration] some linux host service metrics are not reported for Centos7  

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#5374]
Hello 

Regarding Linux integration > Linux Host Service metrics, version 0.6.9, and ran by elastic-agent 8.5.3, some metrics are reported for Debian and Ubuntu distributions but not for Centos7  
More specifically:
system.service.resources.memory.usage.bytes  
system.service.resources.tasks.count 

Below some illustrations 
Linux metrics are reported for all distributions below 
<img width="1984" alt="Capture d’écran 2023-02-23 à 16 22 43" src="https://user-images.githubusercontent.com/48563314/220952151-c47e060d-0830-4a11-80c6-bb7a9608948c.png">

Except system.service.resources.memory.usage.bytes  for instance
<img width="2006" alt="Capture d’écran 2023-02-23 à 16 22 52" src="https://user-images.githubusercontent.com/48563314/220952326-adf049c3-090c-4a15-ae34-89b34b5d7695.png">

**Comment by fearful-symmetry** [comment]
So, the availability of that metric depends on the config of systemd, and of the individual unit. We'll only get this metric if either the systemd unit in question has `MemoryAccounting=yes` set in the unit config, or if `DefaultMemoryAccounting=yes` is set globally on the systemd config. On centos7, memory accounting appears disabled by default.

**Comment by Danouchka** [comment]
Hi @fearful-symmetry  many thanks for your explanations !
