### ISSUE TITLE
CockroachDb TSDB Enablement

### ISSUE THREAD

**Issue by ritalwar** [elastic/integrations#5410]
## Test Environment Setup
- [x] Creation of CockroachDb Test Environment.

## Datastream : Status 
  - [x] Add dimension fields
       - https://github.com/elastic/integrations/pull/5479
  - [x] #6728
       - https://github.com/elastic/integrations/pull/7429
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.
## Issues
  - https://github.com/elastic/kibana/issues/155004. [Blocker for metric_type]

Enable TSDB by default: https://github.com/elastic/integrations/pull/6774

**Comment by ritalwar** [comment]
Draft PR for dimension fields: [PR]https://github.com/elastic/integrations/pull/5479

**Comment by ritalwar** [comment]
Blocked on CI issues due to tests getting failed.

**Comment by ritalwar** [comment]
Verified data loading, count and dimensions after enabling TSDB flag in kibana.

**Comment by ritalwar** [comment]
I'll create a metric_type PR once metric_type mapping for dynamic templates is available.

**Comment by lalit-satapathy** [comment]
@ritalwar, Can the metric_type mapping be added now since https://github.com/elastic/kibana/issues/155004 is fixed. Also, keeping this meta open for npw.

**Comment by lalit-satapathy** [comment]
@ritalwar, Do we have the TSDB dashboard images with the latest metric types and dimension added?

**Comment by ritalwar** [comment]
> @ritalwar, Do we have the TSDB dashboard images with the latest metric types and dimension added?
Yes Lalit, let me attach them here.

**Comment by ritalwar** [comment]
##Screenshots
![image](https://github.com/elastic/integrations/assets/102972658/af4be56c-d47c-4668-be66-b9a176cb59f0)
![image](https://github.com/elastic/integrations/assets/102972658/56cec5b2-b34f-44e1-93cb-7150c4ba8fed)
![image](https://github.com/elastic/integrations/assets/102972658/aa02a42e-66f7-46f6-b209-fd8906380a4c)
<img width="1720" alt="Screenshot 2023-06-29 at 7 13 54 PM" src="https://github.com/elastic/integrations/assets/102972658/772d54a5-d45f-417c-973f-bb4b7b1cf2f7">
