### ISSUE TITLE
[Postgresql] TSDB Enablement

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#5429]
## Test Environment Setup
- [x] Creation of Postgresql Test Environment

## Datastream : `activity` 
  - [x] Add dimension fields 
    - https://github.com/elastic/integrations/pull/5457
  - [x] Adding metric_type mapping  
    - Not applicable. There exist no metric fields that falls in the category of becoming a metric_type (gauge / counter) 

    
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.

## Datastream : `bgwriter` 
  - [x] Add dimension fields 
    - https://github.com/elastic/integrations/pull/5544
  - [x] Adding metric_type mapping  
    - https://github.com/elastic/integrations/pull/5544

    
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.

## Datastream : `database` 
  - [x] Add dimension fields 
    - https://github.com/elastic/integrations/pull/5601
  - [x] Adding metric_type mapping 
    - https://github.com/elastic/integrations/pull/5585
    
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.

## Datastream : `statement` 
  - [x] Add dimension fields 
    - https://github.com/elastic/integrations/pull/5534
  - [x] Adding metric_type mapping
    - Already exist  
    
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.

## TSDB Enablement :
  - [x] https://github.com/elastic/integrations/pull/6973
   
## Issues Identified
  - https://github.com/elastic/elastic-package/issues/1174
  - https://github.com/elastic/kibana/issues/153220

**Comment by agithomas** [comment]
Only one dashboard for metrics. 

<img width="1667" alt="image" src="https://user-images.githubusercontent.com/101976829/223804987-a19d8247-8baf-4390-b4bb-e4d7dbef3272.png">

**Comment by lalit-satapathy** [comment]
@agithomas, Anything still gating PostgeSQL for 8.8 stack version?

**Comment by agithomas** [comment]
> @agithomas, Anything still gating PostgeSQL for 8.8 stack version?

No. The TSDB enablement of this package has resumed.

**Comment by agithomas** [comment]
Dashboard verification after the fix

![image](https://github.com/elastic/integrations/assets/101976829/960896a9-7157-4203-8f59-dcf185721d8c)
