### ISSUE TITLE
PulseSecure parser needs to accept users with @domain if SAML is used

### ISSUE THREAD

**Issue by zez3** [elastic/integrations#5439]
Orig event:

```
<134>1 2023-03-03T17:21:09+01:00 1.1.1.1 PulseSecure: - - - 2023-03-03 17:21:09 - sslvpn02 - [1.1.1.1] user.name@students.mydom.com(MembersSAML)[MemberRole] - WebRequest completed, GET to https://some.web.ch:443//sss/sessionPing?unique=0.10846163950738053 from 1.1.2.22 result=200 sent=60 received=4 in 1 seconds
```

will output:

```
Provided
 Grok expressions do not match field value:
``

The grok pattern needs to changes by trying to add the `(@%{USERNAME:user.domain})`, if existing

```
^(<%{NONNEGINT:log.syslog.priority:long}>%{NUMBER}?|%{SYSLOGTIMESTAMP} %{SYSLOGHOST:host.hostname} %{INT}) %{TIMESTAMP_ISO8601:_tmp.timestamp} (%{IP:observer.ip}|%{HOSTNAME:observer.hostname}) PulseSecure: - - - %{DATE2} - %{SYSLOGHOST:observer.name} - \[%{IPORHOST:client.address}\] (%{DATA}::)?(%{HOSTNAME:user.domain}\\)?%{USERNAME:user.name}?(@%{USERNAME:user.domain})?\(%{DATA:pulse_secure.realm}?\)\[%{DATA:pulse_secure.role}\] - %{GREEDYDATA:message}
```

I've also added in my custom pipeline the url domain,path  and http method and version

```
WebRequest ok : Host: %{GREEDYDATA:url.domain}, Request: %{WORD:http.request.method} %{URIPATHPARAM:url.path} HTTP/%{NUMBER:http.version:double}
```

**Comment by efd6** [comment]
@zez3 It does not look like the WebResquest message format is consistent enough to reliably extract that information (the pattern that you have added does not match the event that you have posted for example).
