### ISSUE TITLE
Linux Integration - Docs issue: System Integration headings is displayed for Linux integration on detail page.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#546]
**Kibana version:**
8.0 Snapshot Kibana Cloud environment 

**Elasticsearch version:**
8.0 Snapshot Kibana Cloud environment 

**Host OS and Browser version:**
Linux centos, All

**Original install method (e.g. download page, yum, from source, etc.):**
8.0 Snapshot Kibana Cloud environment  

**Preconditions**
1.  8.0 Snapshot Kibana Cloud environment  should be available.
```
BUILD 39668
COMMIT a43d609b094763a61969a00c764d015d3454923f
Artifact link: https://snapshots.elastic.co/8.0.0-c6c1882a/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-linux-x86_64.tar.gz
```
2. Default policy having system integration should exist.[No change in namespace].

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Integrations>all integrations. 
3. Go to 'Linux' integration.
4. Observe, System Integration headings is displayed for Linux integration on Linux integration detail page.

**Reference ticket Id:**
N/A

**Actual Result**
System Integration headings is displayed for Linux integration on Linux integration detail page.

**Expected Result**
Linux Integration heading should be displayed for Linux integration on Linux integration detail page.

**What's working**
N/A

**What's not working**
N/A

**Screenshots:** 
![linux_heading](https://user-images.githubusercontent.com/72375798/105160084-d206fe00-5b35-11eb-838a-3f56a9006774.png)

**Comment by jen-huang** [comment]
Moved this to Integrations repo as it's an issue with documentation for the Linux integration.

**Comment by fearful-symmetry** [comment]
Fix has been merged, closing.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX
We have re-validated this issue on 8.0.0 Snapshot Kibana Cloud environment and found it **Fixed**. Build details are as follows:
```
Build: 39872
Commit: 0fe7b9e080c67c43aefdb7ea25d5e90a80cb4ade
```
**Observations:**
- Integration heading is updated on Linux integration detail page.

**Screenshots:**
![17](https://user-images.githubusercontent.com/77374876/105987839-d77bbf80-60c4-11eb-8867-75fc4bd59367.JPG)

Please let us know if anything else is required.

Thanks
QAS
