### ISSUE TITLE
Linux Integration - Docs bug: No information is present for low-level metrics on linux Overview page.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#547]
**Kibana version:**
8.0 Snapshot Kibana Cloud environment 

**Elasticsearch version:**
8.0 Snapshot Kibana Cloud environment 

**Host OS and Browser version:**
Linux centos, All

**Original install method (e.g. download page, yum, from source, etc.):**
8.0 Snapshot Kibana Cloud environment  

[Ingest Manager]: No information is present for low-level metrics on linux integration Overview page.

**Preconditions**
1.  8.0 Snapshot Kibana Cloud environment  should be available.
```
BUILD 39668
COMMIT a43d609b094763a61969a00c764d015d3454923f
Artifact link: https://snapshots.elastic.co/8.0.0-c6c1882a/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-linux-x86_64.tar.gz
```
2. Default policy having system integration should exist.[No change in namespace].

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Integrations>installed integrations. 
3. Goto 'Linux' integration.
4. Click on 'Read More' under Overview section.
5. Observe, No information is present for low-level metrics on linux Overview page.

**Reference ticket Id:**
N/A

**Actual Result**
No information is present for low-level metrics on linux Overview page.

**Expected Result**
Brief information should be available for low-level metrics on linux Overview page.

**What's working**
N/A

**What's not working**
N/A

**Screenshots:** 
![Linux_detail_page_info_missing](https://user-images.githubusercontent.com/72375798/105162302-71c58b80-5b38-11eb-9d7a-f0101631d26a.png)

**Comment by jen-huang** [comment]
Moved this to Integrations repo as it's an issue with documentation for the Linux integration.

**Comment by fearful-symmetry** [comment]
Fix has been merged, closing.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX
We have re-validated this issue on 8.0.0 Snapshot Kibana Cloud environment found it **Fixed**. Build details are as follows:
```
Build: 39872
Commit: 0fe7b9e080c67c43aefdb7ea25d5e90a80cb4ade
```
**Observations:**
-Information is present for low-level metrics under Linux Integration details page.

**Screenshots:**
![14](https://user-images.githubusercontent.com/77374876/105988466-aa7bdc80-60c5-11eb-92bc-b687433ea776.JPG)

Please let us know if anything else is required.

Thanks
QAS
