### ISSUE TITLE
[O11y][CoreDNS] Visualizations are showing error

### ISSUE THREAD

**Issue by rajvi-elastic** [elastic/integrations#5518]
The CoreDNS integration contains one dashboard (**[Filebeat CoreDNS] Overview**) with 4 visualizations. However, 2 out of 4 visualizations are showing below error in Kibana v8.0.0.

> Could not find reference for kibanaSavedObjectMeta.searchSourceJSON.index

Below is the screenshot of the dashboard:
![screencapture-dev-4-kb-us-central1-gcp-cloud-es-io-9243-app-dashboards-2023-03-13-17_01_19](https://user-images.githubusercontent.com/124889398/224694817-b2a42a51-150c-4dbf-a749-9bc70c9d8b00.png)

**Steps to Reproduce**
1. Navigate to the CoreDNS integration page.
2. Click on install assets.
3. Click on the Assets tab.
4. Open the dashboards.

**Comment by agithomas** [comment]
@rajvi-elastic , were you able to figure out the reason for this issue? Is it something because of typo and can be fixed quickly?

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic , were you able to figure out the reason for this issue? Is it something because of typo and can be fixed quickly?

@agithomas, We have looked into the issue and found that removing below property from visualizations file will resolve the issue:

`"indexRefName": "kibanaSavedObjectMeta.searchSourceJSON.index"`

The wrong index was referenced for these two panels and after removing the above reference from json files, the panel won't throw any error. 

Below are the two lines that will might need to be removed in order to resolve this issue:

1. [packages/coredns/kibana/visualization/coredns-75743f70-443c-11e9-8548-ab7fbe04f038.json](https://github.com/elastic/integrations/blob/main/packages/coredns/kibana/visualization/coredns-3ad75810-4429-11e9-8548-ab7fbe04f038.json#L7)
2.  [packages/coredns/kibana/visualization/coredns-75743f70-443c-11e9-8548-ab7fbe04f038.json](https://github.com/elastic/integrations/blob/main/packages/coredns/kibana/visualization/coredns-75743f70-443c-11e9-8548-ab7fbe04f038.json#L7)

Please let me know how should we proceed ahead? As this integration is not developed by us should we first confirm this probable solution with the service owner first to ensure the functionality of the panels won't be changed with this fix?

**Comment by rajvi-elastic** [comment]
PR is approved and merged, hence closing this issue: https://github.com/elastic/integrations/pull/5814
