### ISSUE TITLE
'linux.users' dataset metrics not available under datastreams page for agent deployed on linux centos 7 (update docs for lack of support)

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#552]
**Kibana version:**
8.0 Snapshot Kibana Cloud environment 

**Elasticsearch version:**
8.0 Snapshot Kibana Cloud environment 

**Host OS and Browser version:**
Linux centos 7, All

**Original install method (e.g. download page, yum, from source, etc.):**
8.0 Snapshot Kibana Cloud environment  

[Ingest Manager]: 'linux.users' dataset metrics not available under datastreams page for agent deployed on linux centos 7.

**Preconditions**
1.  8.0 Snapshot Kibana Cloud environment  should be available.
```
BUILD 39668
COMMIT a43d609b094763a61969a00c764d015d3454923f
Artifact link: https://snapshots.elastic.co/8.0.0-c6c1882a/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-linux-x86_64.tar.gz
```
2. Default policy having **linux** integration should exist.[No change in namespace].
3. Agent should be deployed using above policy. 
4. Datastreamimg is available for the above agent.

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Datastreams Tab. 
3. Goto integration dropdowm.
4. Select 'linux' as option.
5. Observe, 'linux.users' dataset metrics not available.

**Reference ticket Id:**
N/A

**Actual Result**
'linux.users' dataset metrics not available  under datastreams page for agent deployed on **linux centos 7**.

**Expected Result**
'linux.users' dataset metrics not available  under datastreams page for agent deployed on linux centos 7.

**What's working**
'linux.users' dataset metrics is available under datastreams page for agent deployed on **ubuntu 20**.

_**Note: We have also looked at location /var/run/dbus/ in both OSs ubuntu20 and centos 7 and found file 'system_bus_socket' with 0kb in size. Referrred using information provided at Users heading on linux integration Overview page. please refer below screenshot:**_
![linux_detail_page](https://user-images.githubusercontent.com/72375798/105171893-cec73e80-5b44-11eb-84dd-1e3832165b81.png)

**What's not working**
N/A

**Screenshots:** 
![liux_7_error](https://user-images.githubusercontent.com/72375798/105167620-f3b8b300-5b3e-11eb-9004-2db3fa05152f.png)

**Comment by fearful-symmetry** [comment]
I need the actual logs from metricbeat under agent. Where they are depends on the install method, but it's usually somewhere like `data/elastic-agent-37bea7/logs/default/`.

**Comment by EricDavisX** [comment]
@fearful-symmetry we can also do a check to see if systemd is on the given system.  We know that some of the systems are quite old and use systemctl. if systemd is a requirement for beats, if we can document that (if it isn't) then we have a different choice to make regarding Beats support vs what we cite for Agent, etc.  https://www.elastic.co/support/matrix  I think we have _mostly_ the same support, but with Linux the older systems it does get tricky. :S @ph thoughts?

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have validated this issue on other Linux machines referred from [ https://www.elastic.co/support/matrix](https://www.elastic.co/support/matrix) on 8.0.0 Kibana Cloud build. Build details are as follows:
```
Kibana commit: 25f16db4d9791a8943b386cccb8680d70bc6bf54
BUILD: 39743
Agent : https://snapshots.elastic.co/8.0.0-2e77272e/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-linux-x86_64.tar.gz
https://snapshots.elastic.co/8.0.0-2e77272e/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-amd64.deb
```
Please find metrics generated for linux integration on different OSs as follows:


Data sets | Type | Integration | Linux Centos 7 | Linux CentOS 8 | Linux RHEL 7 | Linux RHEL 8 | Ubuntu 16 | Ubuntu 18 | Ubuntu 20 | Deb 9 | Deb 10
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
linux.service | metrics | linux | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
linux.raid | metrics | linux | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
linux.ksm | metrics | linux | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
linux.users | metrics | linux | No | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
linux.conntrack | metrics | linux | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
linux.network_summary | metrics | linux | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
linux.iostat | metrics | linux | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
linux.entropy | metrics | linux | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
linux.pageinfo | metrics | linux | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
linux.memory | metrics | linux | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
linux.socket | metrics | linux | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
Observation | N/A | N/A | Not Working Fine | Working Fine | Working Fine | Working Fine | Working Fine | Working Fine | Working Fine | Working Fine | Working Fine



We have observed that, above reported issue is occurring only on Linux centos 7. Please find required logs as follows:
[CentOS7_metricbeat_logs.zip](https://github.com/elastic/integrations/files/5848936/CentOS7_metricbeat_logs.zip)

cc @fearful-symmetry 

Further, let us know if anything else is required.

Thanks
QAS

**Comment by fearful-symmetry** [comment]
Okay, so there's no actual errors related to `system.users` that I can see. I don't have a CentOS box in front of me, but what I suspect is happening is that CentOS isn't actually using systemd to manager user sessions, which would explain why there's no data.

**Comment by EricDavisX** [comment]
Thank you all, I feel comfortable closing this as 'will not fix' - since it is with the older OS and only for the one dataset.  If you agree, please comment back and we can close it out.  Thanks much.

**Comment by fearful-symmetry** [comment]
This would be _nice_ to fix, but as of now, the `users` metricset is all systemd, so any OSes that don't use systemd for session management aren't supported. We'll probably want to add some documentation somewhere if we don't have it already.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

Considering the bug reported here wont be able to fix for reported OS. We would like to close the issue.

Further, if you would like us to log separate issue for docs here to be updated, we can raise the required.

Please let us know your views over this.

Thanks
QAS

**Comment by EricDavisX** [comment]
Thanks @dikshachauhan-qasource .  @fearful-symmetry @masci where would you prefer to add relating docs for support on this, in the package itself in a separate file, or in the package code or elsewhere?  I figure we can use this ticket for the docs need, unless you want a separate one.  Your call.  Thanks.

**Comment by fearful-symmetry** [comment]
So, it's mentioned in the metricbeat doc:

> The system/users metricset reports logged in users and associated sessions via dbus and logind, which is a systemd component. By default, the metricset will look in `/var/run/dbus/` for a system socket, although a new path can be selected with `DBUS_SYSTEM_BUS_ADDRESS`.

We might want to clarify that, but I'm also not sure that shows up in the Integrations docs anywhere....
