### ISSUE TITLE
[Cassandra] Visualizations with multiple breakdowns could not be migrated to lens

### ISSUE THREAD

**Issue by rajvi-elastic** [elastic/integrations#5531]
**Description**

The Cassandra integration contains two dashboards, **[Logs Cassandra] System Logs** and **[Metrics Cassandra] Overview**. While migrating visualizations to lens, most of the visualizations from **[Metrics Cassandra] Overview** dashboard could not be migrated to the lens. These visualizations contains multiple split series buckets which is not supported in lens yet.

![Screenshot 2023-03-14 145730](https://user-images.githubusercontent.com/124889398/224957618-46deba7b-63cb-4129-b84a-2a7951b2bab2.png)

List of panels that contains multiple split series buckets:

1. Disk Usage [Metrics Cassandra]
2. Cache [Metrics Cassandra]
3. Heap Memory [Metrics Cassandra] 
4. Read Latency [Metrics Cassandra] 
5. Write Latency [Metrics Cassandra]  
6. Range Slice Latency [Metrics Cassandra] 
7. Tasks [Metrics Cassandra]  
8. CAS Read/Write Latency [Metrics Cassandra]  
9. Read/Write Failures [Metrics Cassandra]  
10. Dropped Message [Metrics Cassandra]  
11. Read/Write Count [Metrics Cassandra]  
12. Storage Exception [Metrics Cassandra]  
13. Unavailable Requests [Metrics Cassandra]  
14. Request Timeouts [Metrics Cassandra]  

## Related Issue

- https://github.com/elastic/kibana/issues/82208

**Comment by agithomas** [comment]
@rajvi-elastic , going with the [comment](https://github.com/elastic/kibana/issues/82208#issuecomment-1110624373) doesn't the problem get solved with the approach mentioned as per the comment?

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic , going with the [comment](https://github.com/elastic/kibana/issues/82208#issuecomment-1110624373) doesn't the problem get solved with the approach mentioned as per the comment?

@agithomas According to the [comment](https://github.com/elastic/kibana/issues/82208#issuecomment-1110624373), multiple breakdowns supports in lens but the behavior is different from the breakdown functionality in visualizations. 

The below screenshot compares the behavior of breakdown functionality in both lens and visualizations.
![image](https://user-images.githubusercontent.com/124889398/225833265-5d2cfca0-0631-44b7-b304-ee7e65b4edb1.png)

Suppose, the series is grouped by two fields, top 5 values of field1 and top 5 values of field2.

In visualizations, it will first identify top 5 values of field1 and then identifies top 5 values of field2 for those top 5 values of field1.

On the other hand, in lens, first it will group field 1 and field 2 then shows top 5 values from those entire group (field1 + field2).

**Comment by agithomas** [comment]
> In visualizations, it will first identify top 5 values of field1 and then identifies top 5 values of field2 for those top 5 values of field1.
> 
> On the other hand, in lens, first it will group field 1 and field 2 then shows top 5 values from those entire group (field1 + field2).

To me, the results / behaviour offered by Lens makes more sense. @SubhrataK , what do you think as the right approach ? 

cc @lalit-satapathy , @rameshelastic

**Comment by SubhrataK** [comment]
@rajvi-elastic Looks like the approach taken by Lens is correct and hence, we should proceed with making the changes.

**Comment by rajvi-elastic** [comment]
PR is approved and merged, hence closing this issue:
https://github.com/elastic/integrations/pull/5714
https://github.com/elastic/integrations/pull/5715
