### ISSUE TITLE
[ZScaler ZPA] UserStatus -  Processing errors for PostureHits and PostureMiss fields

### ISSUE THREAD

**Issue by srilumpa** [elastic/integrations#5537]
Hello,

We noticed the `PosturesHit` and  `PosturesMiss` fields from our ZScaler ZPA User status logs were not parsed and didn't appeared into our data streams. Zscaler ZPA is configured to send us its logs the way described into the [integration documentation](https://docs.elastic.co/integrations/zscaler_zpa#user-status-logs). Version of the integration is the current one (1.5.0)

After some quick tests, I was able to reproduce the issue by simulating the pipeline execution on a raw log in verbose mode. The two `split` processors dealing with those fields were failing with the following output:

```json
{
  "processor_type": "split",
  "status": "error_ignored",
  "ignored_error": {
    "error": {
      "root_cause": [
        {
          "type": "illegal_argument_exception",
          "reason": "field [json.PosturesHit] of type [java.util.ArrayList] cannot be cast to [java.lang.String]"
        }
      ],
      "type": "illegal_argument_exception",
      "reason": "field [json.PosturesHit] of type [java.util.ArrayList] cannot be cast to [java.lang.String]"
    }
  },
  "doc": {...}
}
```

I changed the two `split` processors into `rename` processors and documents started to show with `zscaler_zpa.user_status.postures.hit` and `zscaler_zpa.user_status.postures.miss` stored as arrays.

I think the `split` processors should remain but with a condition checking if the original fields are `String` and they should be doubled with their `rename` counterparts if the original fields are of type `ArrayList`. That way, compatibility with the current logic will remain and the pipeline would support data that are already into a JSON array. If needed, I can try to submit a PR to fix this issue.

Thank you

**Comment by ShourieG** [comment]
@srilumpa Awesome, thanks a lot for the PR. This will definitely improve our integration for the better. I will review it and merge asap
