### ISSUE TITLE
[O11y][Oracle WebLogic] Lens Migration

### ISSUE THREAD

**Issue by harnish-elastic** [elastic/integrations#5547]
Manually migrate Oracle WebLogic visualizations to lens in kibana version `8.4.0`. 

## Preparation of data for testing
- [x] Use sample_event.json / setup live instance using docker / mock data using mock server to populate dashboards 

## Migration stats

<html>
<body>
<google-sheets-html-origin>

Oracle WebLogic dashboards  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics Oracle WebLogic] Deployed Application | 5 | 2 | 7 | 0
[Logs Oracle WebLogic] Logs Overview | 3 | 8 | 7 | 4
[Metrics Oracle WebLogic] ThreadPool | 8 | 1 | 9 | 0
  | 16 | 11 | 23 | 4

</body>
</html>

## Data stream :  Deployed Application 
  - [x] Migrate 2 visualizations to the lens
    - https://github.com/elastic/integrations/pull/5548

## Data stream :  ThreadPool 
  - [x] Migrate 1 visualizations to the lens
    - https://github.com/elastic/integrations/pull/5548

## Data stream :  Admin Server
  - [x] Migrate 1 visualizations to the lens
    - https://github.com/elastic/integrations/pull/5548

## Data stream :  Managed Server
  - [x] Migrate 1 visualizations to the lens
    - https://github.com/elastic/integrations/pull/5548

## Data stream :  Access
  - [x] Migrate 1 visualizations to the lens
    - https://github.com/elastic/integrations/pull/5548

## Data stream :  Domain
  - [x] Migrate 1 visualizations to the lens
    - https://github.com/elastic/integrations/pull/5548

## Verification and Validation
  - [x] Verification of functionality remains the same after migration in kibana
  - [x] Verification of data count of after-migrated visualization with before-migrated visualization in kibana
  - [x] Verification of Dashboard are not distorted in supported kibana version (8.4.0)

**Comment by agithomas** [comment]
What is the reason why 4 viz are not migrated to Lens?

**Comment by harnish-elastic** [comment]
> What is the reason why 4 viz are not migrated to Lens?

Those 4 are markdown visualizations.

**Comment by agithomas** [comment]
@harnish-elastic , i recommend you to create smaller PRs going forward - preferably one or two (max) PR / datastream.

**Comment by kush-elastic** [comment]
PR is approved and merged, hence closing this issue: https://github.com/elastic/integrations/pull/5548
