### ISSUE TITLE
Integrations using (deprecated)log input

### ISSUE THREAD

**Issue by muthu-mps** [elastic/integrations#5578]
There are couple of integrations using the deprecated `log` input. 
The log input has been deprecated since `7.16.0`. Capturing the list of integrations which should be upgraded to use `filestream` input instead.

```[tasklist]
### Integrations
- [ ] apache
- [ ] activemq
- [ ] cassandra
- [ ] iis
- [ ] nginx
- [ ] haproxy
- [ ] kafka
- [ ] mongodb
- [ ] mysql
- [ ] postgresql
- [ ] rabbitmq
- [ ] redis
- [ ] tomcat
- [ ] traefik
```

**Comment by muthu-mps** [comment]
@jamiehynds - Currently we have captured the list of integrations. The next step is to try applying the changes with single integration and verify the events before and after upgrade. I don't think so we need to enable `filestream` input manually.

**Comment by BenB196** [comment]
I mentioned this in a PR which is currently in draft (https://github.com/elastic/integrations/pull/5347#discussion_r1137618187), but if you bump the minimum version to to 8.7, I believe you can in theory switch to filestream input, add a toggle to enable [`take_over`](https://github.com/elastic/beats/pull/34292), with it being on by default. That would in theory allow for an in-place replacement of `log` -> `filestream` without a breaking change (provided that `take_over` works as expected)
