### ISSUE TITLE
[O11y][HAProxy] Lens Migration

### ISSUE THREAD

**Issue by rajvi-patel-22** [elastic/integrations#5584]
Manually migrate HAProxy visualizations to lens in current Kibana version `8.4.0` itself. 

## Preparation of data for testing
- [x] Use sample_event.json / setup live instance using docker / mock data using mock server to populate dashboards 

## Migration stats
<html>
<body>

HAProxy Dashboards  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics HAProxy] HTTP backend | 0 | 8 | 5 | 3
[Metrics HAProxy] Overview | 0 | 4 | 1 | 3
[Metrics HAProxy] Frontend | 0 | 2 | 2 | 0
[Logs HAProxy] Overview | 0 | 3 | 3 | 0
[Metrics HAProxy] HTTP frontend | 0 | 3 | 3 | 0
[Metrics HAProxy] HTTP server | 0 | 6 | 5 | 1
[Metrics HAProxy] Backend | 0 | 6 | 3 | 3
  | 0 | 32 | 22 | 10

</body>
</html>

## Data stream : Log 
  - [x] Migrate 3 visualizations to the lens.
    - https://github.com/elastic/integrations/pull/5610

## Data stream : Stat 
  - [x] Migrate 19 visualization to the lens.
    - ~~https://github.com/elastic/integrations/pull/5611~~
    - https://github.com/elastic/integrations/pull/8375

## Verification and Validation
  - [x] Verification of functionality remains the same after migration in Kibana
  - [x] Verification of data count of after-migrated visualization with before-migrated visualization in Kibana
  - [x] Verification of Dashboard are not distorted in supported Kibana version (8.4.0)

**Comment by rameshelastic** [comment]
Can we close this? What is pending here?

**Comment by rajvi-elastic** [comment]
> Can we close this? What is pending here?

@rameshelastic, We are waiting for the confirmation as these integration has large version changes. [[Reference](https://github.com/elastic/integrations/pull/5818#issuecomment-1504537291)]

**Comment by kush-elastic** [comment]
Closing this as all the PRs are merged.
