### ISSUE TITLE
need to fix / backport cisco package fix from #36 so it can be released

### ISSUE THREAD

**Issue by EricDavisX** [elastic/integrations#56]
Hi, I'm testing in 7.8 BC5 deployed on June 3 and find that the Cisco package is still erroring when I try to install.

I see Ruflin commented in closed pr below as:
@alakahakai Could you open a PR to the package-storage repo with this change as a new version so we can release it?
https://github.com/elastic/integrations/pull/36

I'm opening this issue to track it since the issue is closed as is the pr above

**Comment by EricDavisX** [comment]
@ruflin fyi

**Comment by mtojek** [comment]
> @alakahakai Could you open a PR to the package-storage repo with this change as a new version so we can release it?
#36

Speaking about `cisco`, everything is released at the moment (version: 0.1.1) . Could you please describe the issue you're facing?

**Comment by ruflin** [comment]
@mtojek It is not yet in the experimental branch: https://github.com/elastic/package-storage/tree/experimental/packages/cisco/0.1.0 To have it in 7.8, it needs to be there too.

**Comment by mtojek** [comment]
> @mtojek It is not yet in the experimental branch: https://github.com/elastic/package-storage/tree/experimental/packages/cisco/0.1.0 To have it in 7.8, it needs to be there too.

I'm not releasing anything to experimental branches at the moment according to your message in https://github.com/elastic/package-storage/pull/46#issuecomment-638713502 .

**Comment by ruflin** [comment]
@mtojek Got it. I also hoped that packages are pretty final in experimental. Seems like we need to push 1-2 of the releases over there to have it in 7.8. I hope we don't need any code changes.

**Comment by EricDavisX** [comment]
@ruflin has pushed all of the packages files into experimental - so we can test in 7.8.  He's built and deployed, and I've recreated my cloud deploy and Cisco seems to install now.  So I'm closing this as fied

**Comment by EricDavisX** [comment]
Ruflin's pr is here: https://github.com/elastic/package-storage/pull/51
