### ISSUE TITLE
[O11y][Couchbase] Lens Migration

### ISSUE THREAD

**Issue by kush-elastic** [elastic/integrations#5609]
Manually migrate Couchbase visualizations to lens in kibana version `8.4.0`. 

## Preparation of data for testing
- [x] Use sample_event.json / setup live instance using docker / mock data using mock server to populate dashboards 

## Migration stats

<html>
<body>
<google-sheets-html-origin>

Couchbase dashboards  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics Couchbase] Sync Gateway Overview | 18 | 0 | 18 | 0
[Metrics Couchbase] Node Overview | 0 | 4 | 4 | 0
[Metrics Couchbase] Metrics Overview | 0 | 7 | 7 | 0
[Metrics Couchbase] XDCR Overview | 7 | 0 | 7 | 0
  | 25 | 11 | 36 | 0

</body>
</html>

## Dashboard : [Metrics Couchbase] Node Overview
  - [x] Migrate 4 visualizations to the lens
    - https://github.com/elastic/integrations/pull/5612

## Dashboard : [Metrics Couchbase] Metrics Overview
  - [x] Migrate 7 visualizations to the lens
    - https://github.com/elastic/integrations/pull/5612

## Verification and Validation
  - [x] Verification of functionality remains the same after migration in kibana
  - [x] Verification of data count of after-migrated visualization with before-migrated visualization in kibana
  - [x] Verification of Dashboard are not distorted in supported kibana version (8.3.0)

**Comment by agithomas** [comment]
@kush-elastic , i do not see a PR link . Can you please add the PR link to the issue?

**Comment by kush-elastic** [comment]
PR is approved and merged, hence closing this issue: https://github.com/elastic/integrations/pull/5612
