### ISSUE TITLE
Version mapping/compatibility list between the integration vs stack versions

### ISSUE THREAD

**Issue by hp0620** [elastic/integrations#5619]
**Describe the enhancement:**
Currently, it looks like Integrations declare the minimum version of the stack required in the manifest https://github.com/elastic/integrations/blob/main/packages/kubernetes/manifest.yml#L13

However, it does not seem to be versioned, so it's quite tricky to know integration version <> min stack requirement.

So, when circumstances arise that you will need to revert to the previous versions of integration or install a specific versions of integration to bypass a bug, by leveraging the API call 
```
POST api/fleet/epm/packages/[package name]/[package version]
{ "force": true }
```
, https://www.elastic.co/guide/en/fleet/8.6/fleet-faq.html#how-do-i-reinstall-a-missing-dashboard-asset -  it's difficult to guess which version would be the supported/compatible version. 

For this reason, it will be helpful to have some kind of version mapping summary available between the integration versions and the stack versions for each release and list the min/max versions of the stack vs the integration packages.  

Thanks for the consideration!

**Comment by andrewkroh** [comment]
The [Elastic Package Registry API](https://github.com/elastic/package-registry#search) holds every package that has been released. You can query data from it to answer the question of what are the kibana version requirements for a given package release. For example, https://epr.elastic.co/search?package=kubernetes&all=true returns all GA versions of the kubernetes integration and its metadata.

`curl "https://epr.elastic.co/search?package=kubernetes&all=true" | jq '.[] | {package_version: .version, kibana_requirement: .conditions.kibana.version}`

```json
...
{
  "package_version": "1.8.1",
  "kibana_requirement": "^7.16.0 || ^8.0.0"
}
{
  "package_version": "1.9.0",
  "kibana_requirement": "^7.16.0 || ^8.0.0"
}
```
