### ISSUE TITLE
[IBM MQ] Migrate `Top 5 Errors [Logs IBM MQ]` panel to the lens

### ISSUE THREAD

**Issue by rajvi-patel-22** [elastic/integrations#5662]
**Description**

The text type field is not supported in table chart of Lens (current Kibana version `v8.6.0`).  Hence, `Top 5 Errors [Logs IBM MQ]` panel from **[Logs IBM MQ] Overview of error log**  dashboard has not been migrated to the lens as a part of the [IBM MQ lens migration task](https://github.com/elastic/integrations/issues/5494).

**Related Issue**
Lens only shows keyword fields, not text fields: https://github.com/elastic/kibana/issues/96576

**Comment by lalit-satapathy** [comment]
@milan-elastic, Please update this issue as needed.

**Comment by harnish-elastic** [comment]
Closing as completed #9997
