### ISSUE TITLE
Cloudflare Zero Trust logs support

### ISSUE THREAD

**Issue by aywrite** [elastic/integrations#5667]
Request to add a new integration or update the Cloudflare logpush integration to support the ingest of logs from the Cloudflare zero trust product suite.

The Cloudflare side of the zero trust logs works in the same way as other Cloudflare logging - you can configure one or more logpush jobs to storage such as S3. The schemas for zero trust logs are described here https://developers.cloudflare.com/cloudflare-one/analytics/logs/logpush/ 

The zero trust product is described at a high level here https://www.cloudflare.com/products/zero-trust/

I would be fine with this being part of the existing logpush integration but given the different meaning of the data and possible need to use a separate S3 bucket a new integration might be better in the long run.

**Comment by aywrite** [comment]
Possibly superseded by https://github.com/elastic/integrations/issues/5867 if gets actioned

**Comment by jamiehynds** [comment]
@aywrite this PR we're working on will add various zero trust logs. Curious if the log types listed in the PR will give you enough coverage or are there more event types you are look to ingest too?

https://github.com/elastic/integrations/pull/6132

**Comment by aywrite** [comment]
> @aywrite this PR we're working on will add various zero trust logs. Curious if the log types listed in the PR will give you enough coverage or are there more event types you are look to ingest too?
> 
> #6132

Hi @jamiehynds - yeah that MR covers all the use cases we were after - thanks!

**Comment by jamiehynds** [comment]
@aywrite we've shipped an update to the Logpush integration (v1.5.0) which includes support for several Zero Trust event types. Additional dashboards were also added as part of the update. Would you be willing to update your integration and let us know if the logs you wanted to ingest are now covered? 

cc @chemamartinez

**Comment by aywrite** [comment]
@jamiehynds - yes I've updated and tested the different logs types. Haven't done anything advanced but it all looks to be in order and working as expected. Thanks!
