### ISSUE TITLE
crowdstrike: add event fingerprint processor

### ISSUE THREAD

**Issue by efd6** [elastic/integrations#5668]
A user has reported that their cluster is ingesting Crowdstrike documents with duplicated event IDs. We do not currently fingerprint events in this package and we should.

**Comment by andrewkroh** [comment]
It should be noted that if the aws-s3 input is used to ingest the data that the input will set a document `_id` based on the bucket ARN, object key, and offset into the file. This will prevent duplicates so long as the documents are written to the same backing index. If the same S3 object is indexed at different times when the data stream has rolled over the backing index then it will not be deduplicated.

**Comment by efd6** [comment]
So what would be the preferred option? The user was using multiple agents to pull records and apparently saw duplicated events IDs.

**Comment by andrewkroh** [comment]
The fingerprint processor will give us more uniform behavior if there are different inputs in the integration. And it will be more robust if the same content were duplicated within a file or across files (the built-in aws-s3 _id won't catch that since its based on offsets).
