### ISSUE TITLE
[O11y][Redis Enterprise] Lens Migration 

### ISSUE THREAD

**Issue by rajvi-elastic** [elastic/integrations#5674]
Manually migrate Redis Enterprise visualizations to lens in current Kibana version `8.3.0` itself. 

## Preparation of data for testing
- [x] Use sample_event.json / setup live instance using docker / mock data using mock server to populate dashboards 

## Migration stats
<html>
<body>

Redis Enterprise dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metricbeat Redis Enterprise] Overview | 0 | 12 | 11 | 0
  | 0 | 12 | 11 | 0

</body>
</html>

Note: One visualization is migrated to the new control panel.

## Dashboard : [Metricbeat Redis Enterprise] Overview
  - [x] Migrate 11 visualizations to the lens and 1 control to new control type.
    - https://github.com/elastic/integrations/pull/5678
 - [x] Add descriptions for the lens migrated panels:
   -  https://github.com/elastic/integrations/pull/5737

## Verification and Validation
  - [x] Verification of functionality remains the same after migration in Kibana
  - [x] Verification of data count of after-migrated visualization with before-migrated visualization in Kibana
  - [x] Verification of Dashboard are not distorted in supported Kibana version (8.3.0)

## Issues Identified
-  Gauge chart (arc) type is not available in lens. In Lens, only horizontal and vertical gauge chart are supported.
https://github.com/elastic/kibana/issues/89859
Impact : [ Severity : Critical, Workaround : Yes (Convert the panel into either horizontal/vertical gauge chart or metric visualization)]

**Comment by rajvi-elastic** [comment]
As discussed with @SubhrataK, We will migrate gauge chart into **horizontal/vertical gauge chart** or **metric type** based on the below two scenario.

**Scenario 1:**
If the panel represents just the metric/count then it will be migrated to the metric visualization.

Before Migration:
![image](https://user-images.githubusercontent.com/124889398/227493012-d9e67cfa-1852-4721-9535-6e279dc96327.png)

After Migration:
![image](https://user-images.githubusercontent.com/124889398/227493095-1efcd7d6-4b52-4fde-9ede-aff39c851b07.png)

**Scenario 2:** 
If the panel represents the CPU Usage or Memory usage which can be represented **as a part of whole** then we will convert the panel to horizontal/vertical gauge chart.

Before migration:
![image](https://user-images.githubusercontent.com/124889398/227492192-b213fb3e-cc9b-4831-becd-7940c591822e.png)

After migration:
![image (7)](https://user-images.githubusercontent.com/124889398/227497020-171a9a8f-cff6-4e9d-a197-fa860443b0f5.png)

**Comment by agithomas** [comment]
As the workaround suggested is meeting the objective, no concerns in making the proposed changes.

**Comment by rajvi-elastic** [comment]
PR is approved and merged, hence closing this issue: https://github.com/elastic/integrations/pull/5678

**Comment by lalit-satapathy** [comment]
In the Lens version is the info for each of the panel description now gone?

Before:

<img width="367" alt="Screenshot 2023-03-28 at 2 39 50 PM" src="https://user-images.githubusercontent.com/69236064/228188025-ae619524-45c7-45c5-92d1-ae7bde82a735.png">

**Comment by lalit-satapathy** [comment]
> > In the Lens version is the info for each of the panel description now gone?
> 
> Yes @lalit-satapathy, **By value** lens panel doesn't show panel description. [[GitHub issue](https://github.com/elastic/kibana/issues/140637)]

The description seems empty for now and I am able to add them by editing as below.
<img width="316" alt="Screenshot 2023-03-28 at 3 00 41 PM" src="https://user-images.githubusercontent.com/69236064/228193513-f2dfa2a5-7e29-45d0-944e-32e04e859506.png">

**Comment by rajvi-elastic** [comment]
> The description seems empty for now and I am able to add them by editing as below. <img alt="Screenshot 2023-03-28 at 3 00 41 PM" width="316" src="https://user-images.githubusercontent.com/69236064/228193513-f2dfa2a5-7e29-45d0-944e-32e04e859506.png">

@lalit-satapathy, I don't see any option to add description in lens and Kibana issue is also open for the same. Can you please provide steps to add the description so that I can verify it from my end.

**Comment by lalit-satapathy** [comment]
> Can you also specify the Kibana version that you have?

It lets you update in _8.7.0-SNAPSHOT_, May be its newly added.

**Comment by rajvi-elastic** [comment]
> It lets you update in _8.7.0-SNAPSHOT_, May be its newly added.

Yes @lalit-satapathy. It could be the case. Because I tried to add description in `8.3.0` and `8.6.1` but I didn't get the option.

**Comment by agithomas** [comment]
@rajvi-elastic , as the PR is already merged, we have two options here considering the description is no longer available in the kibana dashboard

Option 1: Do a rollback 
Option 2: Create a PR with say 8.7  as the version having the panel description.

The decision will soon be shared here. However, please work on the option 2 and share the issue & PR link here.

**Comment by agithomas** [comment]
We also need to find out how much dashboards under various integration has description in panels. 

a. Identify the json block in vis that holds the description info of the panels. 

b. Grep the visualisation json of all integrations having the block.

c. Do the dashboard screenshot validation additionally.

We need to have the names of dashboards with integration impacted by the above mentioned problem.  How many among in this list had a lens migration completed. Please take this up at the highest priority.

cc @lalit-satapathy , @harnish-elastic , @kush-elastic

**Comment by rajvi-elastic** [comment]
> The decision will soon be shared here. However, please work on the option 2 and share the issue & PR link here.

@agithomas Please find the below Issue and PR for adding panel description in migrated lens visualizations.

Issue: https://github.com/elastic/integrations/issues/5723
PR Link: https://github.com/elastic/integrations/pull/5737

**Comment by rajvi-elastic** [comment]
> We need to have the names of dashboards with integration impacted by the above mentioned problem. How many among in this list had a lens migration completed. Please take this up at the highest priority.

@agithomas, We have looked into the other integrations but no any other integrations are having the panel description apart from the Redis Enterprise.

**Comment by rajvi-elastic** [comment]
PR is approved and merged, hence closing this issue: https://github.com/elastic/integrations/pull/5737
