### ISSUE TITLE
[Docker] `message` field is mapped as `keyword`

### ISSUE THREAD

**Issue by n0othing** [elastic/integrations#5679]
The Docker integration's `container_logs` data stream maps `message` as a `keyword` [1]. This makes the field difficult to search + clashes with ECS [2], which maps `message` as `match_only_text`

[1] https://docs.elastic.co/en/integrations/docker#container_logs
[2] https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-ecs.html

**Comment by thecatontheflat** [comment]
As a novice to the stack, I had just spent hours trying to figure it out. This was especially confusing since both Docker and Kubernetes integrations match the same "logs" pattern, so I expected them to have similar configuration :D
