### ISSUE TITLE
Unmapped fields in Fleet Server Logs

### ISSUE THREAD

**Issue by christophercutajar** [elastic/integrations#5680]
`logs-elastic_agent.fleet_server-$workspace*` has a number of useful fields which aren't mapped. The below screenshot highlights a number of these fields that would be useful during an investigation. It would be helpful if such fields get mapped to be leverage during searching and aggregations.

<img width="438" alt="Screenshot 2023-03-24 at 17 54 27" src="https://user-images.githubusercontent.com/60098546/227591147-69051ea1-149b-4842-952e-62e714f7f674.png">

**Comment by michel-laterman** [comment]
It's strange that some of these fields are unmapped, `error.message` should be defined as part of the ecs common schema. and I think the `component.*` are [defined as part of the elastic-agent logs](https://github.com/elastic/integrations/blob/main/packages/elastic_agent/data_stream/elastic_agent_logs/fields/fields.yml#L29) I think these need to be copied into the fleet-server specific mappings
