### ISSUE TITLE
[Synthetics] Configure DLM policy for Synthetics in Serverless

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/integrations#5681]
Serverless will not support ILM policies in favor of DLM (Data Lifecycle Management) policies. This is a new concept that will provide similar functionality, but with guaranteed compatibility in serverless deployments.

It is not yet clear what will need to be done to support DLM for serverless. This issue serves as a placeholder.

**Comment by justinkambic** [comment]
We may need to follow this up with some modification to the way we are displaying info in our data retention screen. See the screenshots below:

### Synthetics data retention view

![Image](https://github.com/elastic/integrations/assets/18429259/dd13ac12-ddf6-4783-a954-5de0c2f08b0c)

### Data streams view

![Image](https://github.com/elastic/integrations/assets/18429259/5cc78e02-d470-4bc7-bba7-138358f158d5)

**Comment by justinkambic** [comment]
DSL is now configured via the Synthetics package via https://github.com/elastic/integrations/pull/9058. Closing this.

I have created https://github.com/elastic/kibana/issues/176540 to address the issues with the retention tab that are noted in comments on this issue.
