### ISSUE TITLE
[O11y][Microsoft SQL Server] Lens Migration 

### ISSUE THREAD

**Issue by rajvi-elastic** [elastic/integrations#5710]
Manually migrate Microsoft SQL Server visualizations to lens in current Kibana version `8.3.0` itself. 

## Preparation of data for testing
- [x] Use sample_event.json / setup live instance using docker / mock data using mock server to populate dashboards 

## Migration stats
<html>
<body>

  | Before Migration |   | After Migration   |  |  
-- | -- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization | New control panel
[Metrics Microsoft SQL Server] Transaction log | 0 | 8 | 7 | 0 | 1
[Logs Microsoft SQL Server Audit Events] Overview | 7 | 0 | 7 | 0 | 0
[Logs Microsoft SQL Server]  Error Log Overview | 1 | 0 | 1 | 0 | 0
[Metrics Microsoft SQL Server] Performance | 5 | 0 | 5 | 0 | 0
  | 13 | 8 | 20| 0 | 1
</body>
</html>

## Dashboard : [Metrics Microsoft SQL Server] Transaction log
  - [x] Migrate 7 visualization to the lens and one visualization to new control panels.
    - https://github.com/elastic/integrations/pull/5734

## Dashboard : [Logs Microsoft SQL Server Audit Events] Overview
  - [x] Migrate 0 visualization to the lens.
    - https://github.com/elastic/integrations/pull/5733

## Dashboard : [Logs Microsoft SQL Server]  Error Log Overview
  - [x] Migrate 0 visualization to the lens.
    - https://github.com/elastic/integrations/pull/5733
    
## Dashboard : [Metrics Microsoft SQL Server] Performance
  - [x] Migrate 0 visualization to the lens.
    - https://github.com/elastic/integrations/pull/5733

## Verification and Validation
  - [x] Verification of functionality remains the same after migration in Kibana
  - [x] Verification of data count of after-migrated visualization with before-migrated visualization in Kibana
  - [x] Verification of Dashboard are not distorted in supported Kibana version (8.3.0)

**Comment by muthu-mps** [comment]
@rajvi-elastic - Can you please revisit the total values shown in the above table ?

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic - Can you please revisit the total values shown in the above table ?

@muthu-mps, Updated! Thank you.

**Comment by rajvi-elastic** [comment]
PR is approved and merged, hence closing this issue: 
https://github.com/elastic/integrations/pull/5733
https://github.com/elastic/integrations/pull/5734
