### ISSUE TITLE
Mark cloud security integration var credentials as secrets

### ISSUE THREAD

**Issue by eyalkraft** [elastic/integrations#5719]
Following this [doc](https://docs.google.com/document/d/15DHwXy8bw1p1T5AutrU_vgLtlTJihrpxnE2i59hKKio/edit#) and [spec change](https://github.com/elastic/package-spec/pull/339). 

**DOD**
- [ ] Check what are the implications when using secrets - does that effect how cloudbeat consumes sensitive information?
- [ ] Mark sensitive data that we use in cloud_security_posture as secrets
- [ ] Check what happens after an upgrade, does it automatically migrate that into a secret or not?

**Comment by kfirpeled** [comment]
no longer blocked - moved to todo

**Comment by mitodrummer** [comment]
This might still be blocked. I've compiled the latest elastic-package binary from main branch, and it shows "secret" as an invalid field, perhaps the spec change is not released yet? 
<img width="914" alt="image" src="https://github.com/elastic/integrations/assets/16198204/b9e23341-1e84-486e-a8b7-194a6694591c">

**Comment by maxcold** [comment]
@mitodrummer  Looking at https://github.com/elastic/package-spec/pull/339/files# it seems like the validation failed. DId you use the format version `2.9.0` where `secret` was introduced as far as I understand?
For more context: I found this PR from this issue https://github.com/elastic/kibana/issues/154715 linked in this thread https://elastic.slack.com/archives/C0348SPA1RN/p1692605636646459

**Comment by mitodrummer** [comment]
You are correct. Updating the format version to 2.9.0 allows the secret field to be compiled. Not blocked!

**Comment by oren-zohar** [comment]
Closing as a [duplicate](https://github.com/elastic/security-team/issues/7380)
