### ISSUE TITLE
[Network Packet Capture] Flow Metrics not reported properly 

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#5771]
Hello

I have issued a wget free.fr command , ie to destination.ip: "212.27.48.10"  from a VM
on that VM, i have installed elastic-agent 8.6.2 with **network packet capture integration** and flows should be reported once (-1 and -1s were tested)  after a tcp timeout of 30s . 

On terminal, I have the following output

```
root@machine~# wget free.fr

--2023-04-02 15:59:58--  http://free.fr/
Resolving free.fr (free.fr)... 212.27.48.10, 2a01:e0c:1::1
Connecting to free.fr (free.fr)|212.27.48.10|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.free.fr/ [following]
--2023-04-02 15:59:58--  https://www.free.fr/
Resolving www.free.fr (www.free.fr)... 212.27.48.10, 2a01:e0c:1::1
Connecting to www.free.fr (www.free.fr)|212.27.48.10|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.free.fr/freebox/ [following]
--2023-04-02 15:59:58--  https://www.free.fr/freebox/
Reusing existing connection to www.free.fr:443.
HTTP request sent, awaiting response... 200 OK
Length: 68173 (67K) [text/html]
Saving to: ‘index.html.1’

index.html.1                                    100%[====================================================================================================>]  66.58K  --.-KB/s    in 0.006s

2023-04-02 15:59:58 (11.4 MB/s) - ‘index.html.1’ saved [68173/68173]
```
So this command issued 2 flows but all lasting less than 6ms. 

Now in my Discovery, I have this
<img width="2015" alt="Capture d’écran 2023-04-02 à 18 12 01" src="https://user-images.githubusercontent.com/48563314/229365441-68c9f9bc-1b03-4242-8e08-a703139a1b3f.png">

**Questions**

1. Why my 2 flows are not reported once at 18:00:30 ?  each of the 2 flows are reported 5 times , ie every 10 seconds , for 40 seconds 
2. Why the source bytes/packets and destination bytes/packets are repeated to the same in every record for each flow resp ? This means a total of exchanged bytes that is 5 times higher than the reality 

Please could you fix asap ? 

cc @pierrehilbert

**Comment by Danouchka** [comment]
-1 or -1s in flow settings is not taken into account

**Comment by Danouchka** [comment]
Periodic reporting seems not working neither

**Comment by pierrehilbert** [comment]
@narph: keep me honest here but seems to be in your team. Could you have someone to have a look please?

**Comment by efd6** [comment]
@Danouchka 

Can you clarify some things please:

1. What do you mean by "-1 or -1s in flow settings is not taken into account"? Can you provide a reproducer?
2. What do you mean by "Periodic reporting seems not working neither"? Can you provide a reproducer?
3. Are you able provide a pcap of the session?

**Comment by efd6** [comment]
Despite what the documentation says, a value of "-1" will not work. The [code that is parsing this](https://github.com/elastic/beats/blob/25acf60399e2c56f544f4f76cb76611a28847cdf/packetbeat/flows/flows.go#L49-L66) uses `time.ParseDuration` which [requires a unit](https://play.golang.com/p/Z7Si8WEzDAL). A fix to the beats code will be release cycle-bound, so it would be better to fix the documentation. The same documentation error exists in the packetbeat.yml file, so this should also be fixed.

**Comment by Danouchka** [comment]
Hi @efd6 
- On packetbeat "-1s" setting works . One flow record for each network connection will be sent once 
- On network packet capture integration, "-1s" will not work..I have more than 1 flow record for each network connection. 
It's not only a matter of documentation.  

Best, Dan

**Comment by efd6** [comment]
Thanks. The fact that packetbeat is working as expected is a useful data point.

The [comment](https://github.com/elastic/integrations/issues/5771#issuecomment-1495194362) above is not suggesting a fix for this, but for the misleading documentation that exacerbates the confusion.

**Comment by Danouchka** [comment]
Please find attached here agent policy 
[agent_policy.txt](https://github.com/elastic/integrations/files/11145483/agent_policy.txt)

**Comment by Danouchka** [comment]
Another test
<img width="1960" alt="Capture d’écran 2023-04-04 à 09 30 18" src="https://user-images.githubusercontent.com/48563314/229720082-bc26ffcf-2fcd-41df-8fb9-ff98f5c0e538.png">

Corresponding pcap 
[free2.pcap.txt](https://github.com/elastic/integrations/files/11145804/free2.pcap.txt)

According the pcap trace: we have  77472 bytes 
According the image : we have 1993+75537 = 77530 , soit +58 bytes of difference

**Comment by Danouchka** [comment]
Elastic Agent Diagnostics provided in MP

**Comment by Danouchka** [comment]
@morashwan 
Many thanks for your input.  

a) The issue is that the [Network Packet Capture] Dashboards  dont take into account the flow.final flag 
They aggregate on all occurrences which leads to incorrect metrics. 
Dashboards should be corrected as well

b) As I have asked only to be reported once at timeout (-1s) , I should not have all those occurences anyway. but rather the one with flow.final flag set to true

**Comment by efd6** [comment]
@morashwan Thanks for pointing that out.

@Danouchka I've added a filter to the flow dashboard which should cover you for now. I'll look into what is going wrong with the publish logic for the report-on-kill case.

**Comment by efd6** [comment]
@Danouchka From the logs and looking at the logic extracted into an experimental set-up, this looks like it is doing the right thing, modulo the configuration of -1s.

In the logs what I see is essentially the following
```
{"log.level":"debug","@timestamp":"2023-04-04T07:37:40.001Z","message":"worker tick, nTimeout=2, nPeriod=0","component":{"binary":"packetbeat","dataset":"elastic_agent.packetbeat","id":"packet-default","type":"packet"},"log":{"sourc
e":"packet-default"},"log.logger":"flows","log.origin":{"file.line":206,"file.name":"flows/worker.go"},"service.name":"packetbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
flows/worker.go:206
        worker tick, nTimeout=2, nPeriod=0

{"log.level":"debug","@timestamp":"2023-04-04T07:37:40.001Z","message":"exec tick, timeout=false, report=true","component":{"binary":"packetbeat","dataset":"elastic_agent.packetbeat","id":"packet-default","type":"packet"},"log":{"so
urce":"packet-default"},"log.logger":"flows","log.origin":{"file.line":236,"file.name":"flows/worker.go"},"service.name":"packetbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
flows/worker.go:236
        exec tick, timeout=false, report=true

{"log.level":"debug","@timestamp":"2023-04-04T07:37:40.001Z","message":"report flow","component":{"binary":"packetbeat","dataset":"elastic_agent.packetbeat","id":"packet-default","type":"packet"},"log":{"source":"packet-default"},"l
og.logger":"flows","log.origin":{"file.line":274,"file.name":"flows/worker.go"},"service.name":"packetbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
flows/worker.go:274
        report flow
```
with subsequent flow reports. The logged value of `nTimeout` cycles from 2 down to 0 as expected for a 30 second timeout with a 10 second period and `nPeriod` is always 0 as expected for a configured period >0. This is consistent with the [experimental simulation](https://play.golang.com/p/OjyaZa6cPma) using the same logic as packetbeat, but extracted.
```
new flows worker. timeout=30s, period=10s, tick=10s, ticksTO=3, ticksP=1
worker wait start(2009-11-10 23:00:00 +0000 UTC): 0s
start flows worker loop: tick=10s, nTimeout=3, nPeriod=1
worker tick, nTimeout=2, nPeriod=0
exec tick, timeout=false, report=true
handle flow
report flow

worker tick, nTimeout=1, nPeriod=0
exec tick, timeout=false, report=true
handle flow
report flow

worker tick, nTimeout=0, nPeriod=0
exec tick, timeout=true, report=true
handle flow
kill flow 2009-11-10 23:00:30 +0000 UTC m=+30.000000001
report flow

worker tick, nTimeout=2, nPeriod=0
exec tick, timeout=false, report=true
handle flow
report flow

worker tick, nTimeout=1, nPeriod=0
exec tick, timeout=false, report=true
handle flow
report flow

worker tick, nTimeout=0, nPeriod=0
exec tick, timeout=true, report=true
handle flow
kill flow 2009-11-10 23:01:00 +0000 UTC m=+60.000000001
report flow
```

The report=true state can only happen if the period is positive or `nTimeout` is zero. This leaves us in the position of trying to understand how the configuration which has `flows.period: -1s` is resulting in a positive period.

For [comparison](https://play.golang.com/p/EfL-A9jJjbH), this is what a negative period looks like.
```
new flows worker. timeout=5s, period=-1s, tick=5s, ticksTO=1, ticksP=-1
worker wait start(2009-11-10 23:00:00 +0000 UTC): 0s
start flows worker loop: tick=5s, nTimeout=1, nPeriod=-1
worker tick, nTimeout=0, nPeriod=-2
exec tick, timeout=true, report=false
handle flow
kill flow 2009-11-10 23:00:05 +0000 UTC m=+5.000000001
report flow

worker tick, nTimeout=0, nPeriod=-2
exec tick, timeout=true, report=false
handle flow
kill flow 2009-11-10 23:00:10 +0000 UTC m=+10.000000001
report flow

worker tick, nTimeout=0, nPeriod=-2
exec tick, timeout=true, report=false
handle flow
kill flow 2009-11-10 23:00:15 +0000 UTC m=+15.000000001
report flow
```

To rule out all confusion, would you please set up a new instance configured from the outset with timeout='30s' and period='-1s', perform your network operation and then shortly after get a diagnostic bundle. What I'm looking for here is the logging that is written on start up, which is missing in the logs I have, these [explicitly detail](https://github.com/elastic/beats/blob/30171898d8e49f57f423d5d22872f939e4466e00/packetbeat/flows/worker.go#L159-L160) the period and timeout values.

**Comment by Danouchka** [comment]
Hi @efd6 , I have sent you in MP  , 2 other diagnostics !
