### ISSUE TITLE
Microsoft Exchange Online Message Trace integration Basic auth deprecated.

### ISSUE THREAD

**Issue by asiridiaz** [elastic/integrations#5772]
Hi There,

as per [This Article](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-time-s-up/ba-p/3695312) The basic auth has been desabled permamantly and the integration has stopped working. we need to change this with the modern auth according to [this article](https://www.michev.info/blog/post/4067/modern-authentication-oauth-support-for-the-reporting-web-service-in-office-365#content) where we can use the OAuth with below params

```
auth.oauth2.client.id: {{client_id}}
auth.oauth2.client.secret: {{client_secret}}
auth.oauth2.token_url: https://login.microsoftonline.com/{{tenant_id}}/oauth2/v2.0/token
auth.oauth2.scopes: https://outlook.office365.com/.default
request.url: https://reports.office365.com/ecp/reportingwebservice/reporting.svc/MessageTrace?$format=json
```

instead of teh currecnt params

```
request.url: https://reports.office365.com/ecp/reportingwebservice/reporting.svc/MessageTrace
auth.basic.user: {{username}}
auth.basic.password: {{password}}
```

**Comment by romain-chanu** [comment]
Linking https://github.com/elastic/integrations/pull/5775

**Comment by BenB196** [comment]
It looks like a new version was published. Has anyone tested it out to see if it works? (I tried to test it, but I'm getting an error)

**Comment by BenB196** [comment]
I was able to get it to work.

I'm not sure if this integration was actually tested before release, but some of the default values are just bad:

https://github.com/elastic/integrations/blob/8bb1537a5f470b6d3d003caa87ef3b8ecefbe5f3/packages/microsoft_exchange_online_message_trace/manifest.yml#L62-L73

The default scope should really be: `https://outlook.office365.com/.default`

https://github.com/elastic/integrations/blob/8bb1537a5f470b6d3d003caa87ef3b8ecefbe5f3/packages/microsoft_exchange_online_message_trace/manifest.yml#L82-L89

Should most likely default to `oauth2/v2.0/token`, as that appears to be the recommended value (per: https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow)

Also:

https://github.com/elastic/integrations/blob/8a3df8b8cbeeceb341690f33c841e7c44744f403/packages/microsoft_exchange_online_message_trace/docs/README.md?plain=1#L29-L31

Should really include the actual permissions needed.

**Comment by ebeahan** [comment]
Resolved in https://github.com/elastic/integrations/pull/5775
