### ISSUE TITLE
Prometheus TSDB enablement

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#5800]
## Test Environment Setup
- [x] Creation of Prometheus Test Environment

## Datastream : Collector 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/5974
  - [x] Adding metric_type mapping
    
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface

## Datastream : Query 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/5974
  - [x] Adding metric_type mapping
    
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface

## Datastream : Remote Write 
  > ⚠️ after migrating to TSDB (labels_id is added) I can see dropped documents - reason: metrics are not correctly grouped by the labels, seems like a bug in metricbeat

related issue - https://github.com/elastic/integrations/issues/7533
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/7565
  - [x] Adding metric_type mapping - https://github.com/elastic/integrations/pull/7565
    
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface

**Comment by tetianakravchenko** [comment]
some limitation on dimensions fields - https://github.com/elastic/elasticsearch-adrs/blob/master/analytics/tsdb/tsdb-design.md#constraints-on-dimension-fields

**Comment by tetianakravchenko** [comment]
1.  For the prometheus integration `labels` should be used as an dimensions, since `labels` field is of type `object` and can exceed the existing limit of 16 fields on `_tsid` (7 ecs fields are marked as dimension, left only 9), I think it makes sense to introduce the fingerprint processor as mentioned in [doc](https://github.com/elastic/integrations/blob/main/docs/developer_tsdb_migration_guidelines.md)

For example, one of documents that I found has 10 label - together with ecs fields it is already 17 fields - that exceeds the default limit
<img width="527" alt="Screenshot 2023-04-12 at 16 05 36" src="https://user-images.githubusercontent.com/28299531/231483334-1a13bce3-8b82-4400-a352-e5d5fdcf60e8.png">

it is still possible to rewrite the default limit, but since the number of labels is dynamic I think it is better to use fingerprint processor

2. Metric_type for fields with dynamic mapping does not work

3. Histograms are not supported

**Comment by tetianakravchenko** [comment]
## Query

One of 2 use case: using query that returns a single value - in this case no labels will be returned, but labels_id will be still calculated:
<img width="767" alt="Screenshot 2023-04-24 at 16 24 48" src="https://user-images.githubusercontent.com/28299531/234026429-f19e2bdf-509f-4c85-97fa-a413242805e3.png">

1. is it fine to calculate labels_id on missing field?

2. For such cases should be used query name as a dimension, need to extract if from an object - https://github.com/elastic/integrations/blob/main/packages/prometheus/data_stream/query/fields/fields.yml#L9-L14
3. In configuration it is possible to define query with the same name multiple times. For now I would assume that unique names are provided.

## Remote_write

**Comment by lalit-satapathy** [comment]
@tetianakravchenko, Can metric_type be now added since https://github.com/elastic/kibana/issues/155004 is fixed?

**Comment by lalit-satapathy** [comment]
@tetianakravchenko, Can we update this issue/description, where we are wrt. prometheus TSDB migration and testing status?

**Comment by tetianakravchenko** [comment]
> @tetianakravchenko, Can we update this issue/description, where we are wrt. prometheus TSDB migration and testing status?


@lalit-satapathy I've updated description. going to run local tests for collector/query today
