### ISSUE TITLE
Upgrade ECS version for Integrations [Service Integrations]

### ISSUE THREAD

**Issue by muthu-mps** [elastic/integrations#5803]
Every major release of Elastic stack is aligned with the ECS release. It is recommended to upgrade the ECS version used in Integrations for every release.

Currently this step is partially automated. There should be a process to streamline the upgrade for every release. The upgrade should be done by going through the release highlights and making the necessary changes to the fields if applicable and update the version.

**Comment by ishleenk17** [comment]
Now that we are following ecs@mapping template. This doesn't hold true as always the latest ECS mappings will be used
