### ISSUE TITLE
[meta] Upgrade integrations to ECS 8.8

### ISSUE THREAD

**Issue by ebeahan** [elastic/integrations#5816]
Track ECS 8.8 updates to integration packages maintained by the `elastic/security-external-integrations` team.

## ECS 8.8 Changes

This is a summary of the changes in ECS 8.8. You can view the official changelog [here](https://github.com/elastic/ecs/blob/8.8/CHANGELOG.md) (invalid link for now - will update).

#### Added

- Add access as an allowed type for event.type: file. elastic/ecs#2174
- Add orchestrator.resource.annotation and orchestrator.resource.label. elastic/ecs#2181
- Add event.kind: asset as a beta category. elastic/ecs#2191

#### Added

- Add parameters property for field definitions, to provide any mapping parameter. elastic/ecs#2084

This issue will be updated once the necessary work to be done is evaluated.

**Comment by taylor-swanson** [comment]
Updated all SEI packages to reference ECS 8.8.

The two packages SEI has (`gcp` and `sentinel_one`) that reference orchestrator fields don't appear to have anything actionable at the moment regarding: https://github.com/elastic/integrations/issues/5816. @ebeahan, would you agree?
