### ISSUE TITLE
Enable TSDB for System integration

### ISSUE THREAD

**Issue by joshdover** [elastic/integrations#5848]
We need to enable TSDB indexing for the system integration's metric streams to reduce storage costs. This should be done in 3 broad phases:
- Update mappings to specify dimensions
- Update mappings to specify metric types
- Flip the toggle to enable TSDB indexing mode, update `constraint.kibana.version` to 8.8

You can find related issues and examples for other integrations in https://github.com/elastic/integrations/issues/5233

### Current PRs:
- [x] beta release PR - https://github.com/elastic/integrations/pull/6427
- [x] metric_type - add missing metadata - https://github.com/elastic/integrations/pull/6395
- [x] dimensions network data_stream: https://github.com/elastic/integrations/pull/6405
- [x] dimensions for add data_sreams, except core, network, process - https://github.com/elastic/integrations/pull/6118
- [x] dimensions process data_stream: https://github.com/elastic/integrations/pull/6407
- [x] core dimensions - https://github.com/elastic/integrations/pull/6454
- [x] enable tsdb on network - https://github.com/elastic/integrations/pull/6469
- [x] process metric_type https://github.com/elastic/integrations/pull/6493
- [x] process add missing metric_types https://github.com/elastic/integrations/pull/7660
- [x] enable TSDB on process - https://github.com/elastic/integrations/pull/7672
- [ ] enable TSDB on core - https://github.com/elastic/integrations/pull/8637

### Found issues:
- missing time_series_metric https://github.com/elastic/kibana/issues/160403
- https://github.com/elastic/elasticsearch/issues/96552

**Comment by jlind23** [comment]
cc @andresrc for awareness / prio

**Comment by lalit-satapathy** [comment]
@tetianakravchenko will help do the TSDB enablement on system package.

Based on the analysis, the scope of the TSDB enablement on system package would be:
- dimensions present only in 3 out of 17 data_streams: memory, cpu and load. See any missing dimensions. Dimension need to be added to all remaining data_streams and testing.
Prior [work](https://github.com/elastic/integrations/pull/5160 ) by @ruflin. 
- metic_type present in diskio, core, memory, socket_summary, cpu, network,filesystem, load, fsstat, process_summary, uptime and process. We need to see if this work before is complete or anything pending here.
Prior [work](https://github.com/elastic/integrations/pull/402).

As usual, we we separate the dimension work from new metric type work(if any) and track in separate PRs.

**Comment by tetianakravchenko** [comment]
Relevant for TSDB datastreams: 

### Datastream: core (metrics)

### Datastream: cpu (metrics)

### Datastream: diskio (metrics)

### Datastream: filesystem (metrics)

### Datastream: fsstat (metrics)

### Datastream: load (metrics)

### Datastream: memory (metrics)

### Datastream: network (metrics)

### Datastream: process (metrics)

### Datastream: process_summary (metrics)

### Datastream: socket_summary (metrics)

### Datastream: uptime (metrics)

next datastream are skipped:
- `application` (input log: winlog)
- `auth` (input type: logfile)
- `security` (input type: winlog)
- `syslog` (input type: logfile)
- `system` (input type: winlog)

**Comment by lalit-satapathy** [comment]
Hi @joshdover, @jlind23,

We have the initial [PR](https://github.com/elastic/integrations/pull/6118) ready (with dimension work) as part of the TSDB enablement. Can someone help review the changes from the package owner perspective and also need help answering one query [here](https://github.com/elastic/integrations/pull/6118#discussion_r1196332959). Thanks!

**Comment by lalit-satapathy** [comment]
@tetianakravchenko, Anything pending on this issue or it can be closed?
