### ISSUE TITLE
[Cloudflare Logpush] url.path mapped to referrer path

### ISSUE THREAD

**Issue by 0xC0FFEEEE** [elastic/integrations#5849]
The url.path ECS field in the Cloudflare Logpush integration appears to be populated from the ClientRequestReferer (original)/cloudflare_logpush.http_request.client.request.referer (parsed) field. See the following example:

![image](https://user-images.githubusercontent.com/119874251/231123025-9ebbdb6d-14ca-45fc-969c-7c4a077e6ef2.png)

This also appears to be the case for cloudflare_logpush.firewall_event.

Shouldn't this be mapped from the ClientRequestPath/cloudflare_logpush.http_request.client.request.path field instead? Currently we're unable to construct reliable EQL queries that use the url.path field for this data source.

I'm struggling to find where this particular mapping takes place.

**Comment by 0xC0FFEEEE** [comment]
Looking through the less favorable Cloudflare Logpull integrations ingest pipeline (`logs-cloudflare.logpull-2.4.1-http`) in Kibana I can see the following processors snippet which does map the appropriate fields correctly.

```
  {
    "uri_parts": {
      "field": "json.ClientRequestURI",
      "ignore_failure": true,
      "if": "ctx?.json?.ClientRequestURI != null"
    }
  },
  {
    "set": {
      "field": "url.domain",
      "copy_from": "json.ClientRequestHost",
      "ignore_empty_value": true,
      "if": "ctx?.url?.domain == null"
    }
  },
  {
    "set": {
      "field": "url.path",
      "copy_from": "json.ClientRequestPath",
      "ignore_empty_value": true,
      "if": "ctx?.url?.path == null"
    }
  },
  {
    "set": {
      "field": "url.scheme",
      "copy_from": "json.ClientRequestScheme",
      "ignore_empty_value": true,
      "if": "ctx?.url?.scheme == null"
    }
  },
  {
    "set": {
      "field": "url.scheme",
      "value": "https",
      "ignore_empty_value": true,
      "if": "ctx?.url?.scheme == null && ctx?.cloudflare?.client?.ssl?.protocol != null"
    }
  },
  {
    "set": {
      "field": "url.scheme",
      "value": "http",
      "ignore_empty_value": true,
      "if": "ctx?.url?.scheme == null"
    }
  }
```

**Comment by efd6** [comment]
@0xC0FFEEEE I'm not convinced by the `uri_parts` processor there to populate the `url.*` fields given the sample events we have since the `ClientRequestURI` is not a URL in the examples we have. Are any of the `ClientRequestURI` fields in your logs actually URLs?
