### ISSUE TITLE
TSDB for Input Packages

### ISSUE THREAD

**Issue by ishleenk17** [elastic/integrations#5863]
We have been adding TSDB fields to OOTB Integrations where the developer defines all the field mappings beforehand.
Opening up this ticket to curate information/brainstorm on how do we deal with TSDB for Input Packages.

There is no default field mappings in Input Packages.
Are we going to provide the user with the option to add the dimension while doing his custom mappings? 
Or is the stand to not support TSDB for Input Packages for now?

cc: @lalit-satapathy @rameshelastic

**Comment by lalit-satapathy** [comment]
We had a brief chat among the TSDB team for input package, we would need further discussion.  Let me summarise the initial thoughts here:

- Decide which input packages will have TSDB enabled.
   - This is would be simple decision. The input packages are of [type](https://github.com/elastic/integrations/blob/main/packages/sql_input/manifest.yml#L22) metrics, can be choose to have TSDB enabled.

- How to enable TSDB for input package
   - Can input packages follow the same principle as integrations and come pre TSDB enabled in the [manifest](https://github.com/elastic/integrations/blob/main/packages/nginx/data_stream/stubstatus/manifest.yml#LL2) file?
   - Note: input packages do not have any data streams, will enablement like this supported at a package [manifest](https://github.com/elastic/integrations/blob/main/packages/sql_input/manifest.yml) file?
   - Whether the user should have an option to toggle TSDB for input package
      - Initial thoughts: follow same mechanism as integrations. This should not be an user option.     
-  How mappings are provided for the input package?
   - Input packages by definition expects user to provide the mapping. So can we expect fleet to provide a mechanism for the users to provide these additional mappings in the run time?
   - What is the process to define dimensions for metrics ingested by input packages?
   - What is the process to define metric_types for for input packages? 
   - Can we have any package level pre-fined mappings for the above or these are defined runtime? 

CC: @ruflin

**Comment by ishleenk17** [comment]
> * Note: input packages do not have any data streams, will enablement like this supported at a package [manifest](https://github.com/elastic/integrations/blob/main/packages/sql_input/manifest.yml) file?

Yes, we will have to add it in the package manifest file

> * What is the process to define dimensions for metrics ingested by input packages?

Currently in the custom mappings I don't see any option to add dimension, metric_types during custom mappings.

> * Can we have any package level pre-fined mappings for the above or these are defined runtime?

There will be some default mapping( for fields which we know are always going to be mapped a certain way). And there will be user mapped fields as well., The way we add dimension for both will vary.
