### ISSUE TITLE
[Cloudflare] Expanded Event Coverage

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#5867]
Our Cloudflare Logpush integration currently supports Audit, DNS, Firewall Event, HTTP Request, NEL Report, Network Analytics and Spectrum Event Logs. However, Logpush provides additional event types that our integration needs to support, in order to provide users with full coverage of Cloudflare events. 

We need to add support for the following sources:

- [Gateway DNS](https://developers.cloudflare.com/logs/reference/log-fields/account/gateway_dns/)
- [Gateway HTTP](https://developers.cloudflare.com/logs/reference/log-fields/account/gateway_http/)
- [Gateway Network](https://developers.cloudflare.com/logs/reference/log-fields/account/gateway_network/)
- [Audit Logs](https://developers.cloudflare.com/logs/reference/log-fields/account/audit_logs/)
- [Access Requests](https://developers.cloudflare.com/logs/reference/log-fields/account/access_requests/)
- [CASB Findings](https://developers.cloudflare.com/logs/reference/log-fields/account/casb_findings/)
- [Device posture status](https://developers.cloudflare.com/cloudflare-one/analytics/logs/posture-logs)

**Comment by 0xC0FFEEEE** [comment]
+ [Worker Trace Events](https://developers.cloudflare.com/workers/platform/logpush/) please

**Comment by chemamartinez** [comment]
I have opened a new issue to cover the non Zero Trust events https://github.com/elastic/integrations/issues/6345

**Comment by jamiehynds** [comment]
@0xC0FFEEEE while Worker Trace events are still on our to-do list, we've now added support for several Zero Trust log types. If you're interested in testing and providing some feedback to us, you can update to the latest version of our Logpush integration (v1.5.0).

**Comment by jamiehynds** [comment]
@0xC0FFEEEE Worker trace events coming via this PR: https://github.com/elastic/integrations/pull/7136 :)
