### ISSUE TITLE
[O11y][SpringBoot] Update `_id` field in SpringBoot dashboard

### ISSUE THREAD

**Issue by rajvi-elastic** [elastic/integrations#5871]
# Description

Below two SpringBoot dashboards contains `Audit Events [Logs Spring Boot]` panel which uses [_id](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html) field:

1. [Spring Boot] Audit Events
2. [Spring Boot] Overview Dashboard

These visualizaions are working as expected in 8.4.0 and 8.5.0. But in Kibana 8.6.0 and later versions it shows below error.

![image-2023-04-12-16-55-50-562](https://user-images.githubusercontent.com/124889398/231449143-af2af0b5-07e2-42fc-9fc9-59f9c2cd450e.png)

According to [documention](https://www.elastic.co/guide/en/elasticsearch/reference/8.7/mapping-id-field.html#:~:text=The%20_id%20field%20is%20restricted%20from%20use%20in%20aggregations%2C%20sorting%2C%20and%20scripting.%20In%20case%20sorting%20or%20aggregating%20on%20the%20_id%20field%20is%20required%2C%20it%20is%20advised%20to%20duplicate%20the%20content%20of%20the%20_id%20field%20into%20another%20field%20that%20has%20doc_values%20enabled.) _id fields are not supported in aggregations:
> The _id field is restricted from use in aggregations, sorting, and scripting. In case sorting or aggregating on the _id field is required, it is advised to duplicate the content of the _id field into another field that has doc_values enabled.

## Related Issues
- https://github.com/elastic/kibana/issues/155344

**Comment by rajvi-elastic** [comment]
### There are two possible solutions to resolve this issue:

### Solution 1:
As mentioned in the documentation of [_id](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html), the content of _id field can be copied in another field using ingest pipeline and the new field can be used in visualizations.

> The _id field is restricted from use in aggregations, sorting, and scripting. In case sorting or aggregating on the _id field is required, it is advised to duplicate the content of the _id field into another field that has doc_values enabled.

### Solution 2: 
The panels are showing list of audit events. Hence, the saved search can be used to display all the events. The only drawback in creating search visualization is column name. In search panels, column names are not configurable. 

Please find below screenshots of originial visualization and suggested panel:

Original visualization:
![image](https://user-images.githubusercontent.com/124889398/231719523-b7574083-c1e8-455e-9721-cb97b400c82b.png)
Suggested search panel:
![image](https://user-images.githubusercontent.com/124889398/231719717-39940b0d-0af9-4126-81e2-1fa2d8778257.png)

**Comment by rajvi-elastic** [comment]
@agithomas, The possible solutions of meta data field (_id) issue are mentioned in the above comment. Please let us know how we should proceed ahead.

**Comment by agithomas** [comment]
@rajvi-elastic , i think unable to retain the column name might impact the customer experience and as well add to the confusion. 

So, my recommendation is to go with the Solution 1, considering it is less disruptive. 
Are there any specific reasons because of which Solution 1 might not be ideal?

**Comment by rajvi-elastic** [comment]
Yes @agithomas. There are some drawbacks of solution 1:

1. The panel will show limited events. [[Reference](https://discuss.elastic.co/t/lens-table-increase-limit-on-number-of-values/306268)]
   - 1000 events till v8.3.0 (As SpringBoot is migrated to 8.1.0, it could only show 1000 events)
   - 10000 events from v8.4.0 to v8.7.0
3.  Search visualization (Solution 2) has better performance than lens table visualization. [[Reference](https://www.elastic.co/guide/en/kibana/current/save-open-search.html)]

**Comment by agithomas** [comment]
> The panel will show limited events. [[Reference](https://discuss.elastic.co/t/lens-table-increase-limit-on-number-of-values/306268)]
> * 1000 events till v8.3.0 (As SpringBoot is migrated to 8.1.0, it could only show 1000 events)
> * 10000 events from v8.4.0 to v8.7.0

I am not sure, if the usecase is practical enough when a user will go through more than 1000 records in a dashboard panel . 

@SubhrataK , thoughts?

**Comment by SubhrataK** [comment]
@rajvi-elastic I agree with Agi, does not seem like a valid use case to me. You can proceed with Solution 1.

**Comment by rajvi-elastic** [comment]
@SubhrataK Okay! We will create one ecs field [event.id](https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-id) and copy the value of `_id` field into `event.id` which can be used in visualization.

**Note**: When user will upgrade to the newer version, `event.id` field will be added only to the new incoming documents. The data that is already present in indices will not get updated. Hence, the `Audit Events [Logs Spring Boot]` visualization will show documents which have `event.id` field present (documents that have been ingested after upgrading to the latest version).

**Comment by agithomas** [comment]
> @SubhrataK Okay! We will create one custom field `spring_boot.audit_events.document_id` and copy the value of `_id` field into `spring_boot.audit_events.document_id` which can be used in visualization.
> 
> **Note**: When user will upgrade to the newer version, `spring_boot.audit_events.document_id` field will be added only to the new incoming documents. The data that is already present in indices will not get updated. Hence, the `Audit Events [Logs Spring Boot]` visualization will show documents which have `spring_boot.audit_events.document_id` field present (documents that have been ingested after upgrading to the latest version).

cc @lalit-satapathy .

**Comment by rajvi-elastic** [comment]
PR is approved and merged, hence closing this issue: https://github.com/elastic/integrations/pull/5935
