### ISSUE TITLE
[O11y][Salesforce] Update _id field in Salesforce dashboard

### ISSUE THREAD

**Issue by rajvi-elastic** [elastic/integrations#5876]
# Description

Below two Salesforce dashboards panels uses [_id](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html) field:
<html>
<body>

 Dashboard | Panel | Data stream
-- | --  | --
 [Logs Salesforce] Setup Audit Trail Dashboard | Changes made in the setup | Setup audit trail
[Logs Salesforce] Login Dashboard | Login events table | Login rest

</body>
</html>

These visualizaions are working as expected till 8.4.0 and 8.5.0. But in Kibana 8.6.0 and later versions it shows below error.

![image-2023-04-13-12-01-59-431](https://user-images.githubusercontent.com/124889398/231688366-d79b0b25-e055-4ce7-91f5-9119d5a1ce05.png)
![image-2023-04-13-12-01-30-894](https://user-images.githubusercontent.com/124889398/231688377-93d963d5-2a23-46af-ab9a-03a4291b9858.png)

According to [documention](https://www.elastic.co/guide/en/elasticsearch/reference/8.7/mapping-id-field.html#:~:text=The%20_id%20field%20is%20restricted%20from%20use%20in%20aggregations%2C%20sorting%2C%20and%20scripting.%20In%20case%20sorting%20or%20aggregating%20on%20the%20_id%20field%20is%20required%2C%20it%20is%20advised%20to%20duplicate%20the%20content%20of%20the%20_id%20field%20into%20another%20field%20that%20has%20doc_values%20enabled.) _id fields are not supported in aggregations:
> The _id field is restricted from use in aggregations, sorting, and scripting. In case sorting or aggregating on the _id field is required, it is advised to duplicate the content of the _id field into another field that has doc_values enabled.

## Related Issues
- https://github.com/elastic/kibana/issues/155344

**Comment by rajvi-elastic** [comment]
### There are two possible solutions to resolve this issue:

### Solution 1:
As mentioned in the documentation of [_id](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html), the content of _id field can be copied in another field using ingest pipeline and the new field can be used in visualizations.

> The _id field is restricted from use in aggregations, sorting, and scripting. In case sorting or aggregating on the _id field is required, it is advised to duplicate the content of the _id field into another field that has doc_values enabled.

### Solution 2: 
The panels are showing list of events. Hence, the saved search can be used to display all the events. The only drawback in creating search visualization is column name. In search panels, column names are not configurable. 

Please find below screenshots of originial visualization and suggested panel:

Original visualization:
![image](https://user-images.githubusercontent.com/124889398/231768418-81dc3a97-fb5b-458d-9a13-6c06d3d12a3b.png)
Suggested search panel:
![image](https://user-images.githubusercontent.com/124889398/231768914-cbb6fcac-23ed-43e5-bf03-efebbcaf7f29.png)

**Comment by rajvi-elastic** [comment]
@agithomas, The possible solutions of meta data field (_id) issue are mentioned in the above comment. Please let us know how we should proceed ahead.

**Comment by rajvi-elastic** [comment]
Two panels that use **_id** meta field belongs to two different data streams:
<html>
<body>


 Dashboard | Panel | Data stream
-- | -- | --
 [Logs Salesforce] Setup Audit Trail Dashboard | Changes made in the setup | Setup audit trail
[Logs Salesforce] Login Dashboard | Login events table | Login rest


</body>
</html>

The _id generation happens after the ingest pipeline is applied.  **Login Rest** data stream has the fingerprint processor which assigns value to the _id field in pipeline itself [[Reference](https://github.com/elastic/integrations/blob/main/packages/salesforce/data_stream/login_rest/elasticsearch/ingest_pipeline/default.yml#L13-L20)]. So we can copy the value of _id field to custom field in ingest pipeline.
```
- fingerprint:
    fields:
    - json.REQUEST_ID
    - json.SESSION_KEY
    - json.TIMESTAMP_DERIVED
    - json.USER_ID
    target_field: _id
    ignore_missing: true
```
But in **Setup audit trail** data stream, the fingerprint processor is not used. So _id field will be generated automatically once the document has been parsed from the ingest pipeline and because of that we can not copy the value from _id field to the custom field in ingest pipeline (because _id field will be empty at that moment ). However, there is a `event.id` field in **Setup audit trail** data stream which represents the unique id extracted from the incoming events [[Reference](https://github.com/elastic/integrations/blob/main/packages/salesforce/data_stream/setupaudittrail/elasticsearch/ingest_pipeline/default.yml#L64-L68)]. The `event.id` field can be used in the panel instead of _id as per the analysis.

@agithomas, @SubhrataK  Can you please provide your suggestions?

**Comment by agithomas** [comment]
> **Setup audit trail** data stream which represents the unique id extracted from the incoming events [[Reference](https://github.com/elastic/integrations/blob/main/packages/salesforce/data_stream/setupaudittrail/elasticsearch/ingest_pipeline/default.yml#L64-L68)]. The `event.id` field can be used in the panel instead of _id as per the analysis.

It is not uncommon to have _id and event.id depending on same json field value . [Reference](github/data_stream/audit/elasticsearch/)

If `json.Id` (stored as `event.id`) is unique enough, why `_id` was computed using `fingerprint` processor originally?

**Comment by rajvi-elastic** [comment]
> If `json.Id` (stored as `event.id`) is unique enough, why `_id` was computed using `fingerprint` processor originally using other fields?

@agithomas, In **Login Rest** data stream, It was required to create fingerprint hence `_id` was computed using 4 fields ( `json.REQUEST_ID`, `json.SESSION_KEY`, `json.TIMESTAMP_DERIVED`, `json.USER_ID`). But in **Setup audit trail** data stream, we didn't require fingerprint that creates `_id` field. So, fingerprint processor was not used over there. Hence `_id` is not accessible from the pipeline. 

However, we can add fingerprint processor on `json.Id` field and store the value in `_id` field which can be copied into `salesforce.login.document_id` field. In this case we will need to add two more processors but in our proposed solution we won't need to add any extra processors.

**Comment by rajvi-elastic** [comment]
PR is approved and merged, hence closing this issue: https://github.com/elastic/integrations/pull/6041
