### ISSUE TITLE
[Cisco ASA] parsing issues

### ISSUE THREAD

**Issue by daixque** [elastic/integrations#5946]
# Overview

We found that couple of type of messages are not able to be parsed properly.

I'm an Elastic consultant in APJ, and my customer said they're verifying the Cisco ASA integration but almost half of the logs are parsed insufficiently. So we should improve those parsing processors.

# Message types

Below are the examples of the logs which is not parsed properly.

| messege id | message |
|---|---|
| 313005 | No matching connection for ICMP error message: icmp src inside:192.168.2.2(LOCAL\xxx\yyy) dst inside:192.168.2.3 (type 3, code 3) on inside interface.  Original IP payload: udp src 192.168.2.2/53 dst 192.168.2.3/10872. |
| 722037 | Group <GroupPolicy_Employee> User <foo.bar@example.com> IP <192.168.0.1> SVC closing connection: DPD failure. |
| 722011 | Group <GroupPolicy_Employee> User <464_0273> IP <1192.168.0.1> SVC Message: 17/WARNING: Reconnecting the VPN tunnel.. |
| 722033 | Group <GroupPolicy_Employee> User <464_0273> IP <192.168.0.1> First UDP SVC connection established for SVC session. |
| 722034 | Group <GroupPolicy_Employee> User <464_0273> IP <192.168.0.1> New TCP SVC connection, no existing connection. |

I will update above list if we find further issues.

Related to https://github.com/elastic/integrations/issues/5256

**Comment by efd6** [comment]
@daixque Can we close this now?
