### ISSUE TITLE
[aws] AWS ELB metrics integration should contain OOTB dashboards for each of the 3 load balancer types 

### ISSUE THREAD

**Issue by tommyers-elastic** [elastic/integrations#5953]
Currently there is only a single dashboard for ELB metrics, which charts metrics for 'classic elb' (`aws.elb.metrics.*` metrics). 

We also collect metrics for application load balancers and network load balancers (`aws.applicationelb.metrics.*` and `aws.networkelb.metrics.*` respectively).

It's confusing for users who are collecting ALB or NLB metrics as to why they don't see any data in the ELB metrics dashboard, which doesn't specify which type of load balancer (it's just called "ELB Overview").

**Comment by agithomas** [comment]
The requirements are addressed through the [PR](https://github.com/elastic/integrations/pull/10444/). Closing the issue.
