### ISSUE TITLE
Tenable.io integration missing some fixed vulnerabilities

### ISSUE THREAD

**Issue by meganlear** [elastic/integrations#5979]
The Tenable.io integration recently started including fixed vulnerabilities but I can see a lot of fixed vulnerabilities in Tenable that aren't showing up in Elastic. This seems to be because the export request is based on the "last_found" time, which for fixed vulnerabilities could be a few days in the past depending on the scan schedule. A possible fix could be to export fixed vulnerabilities separately from open and reopened vulnerabilities, with an export request using the "last_fixed" parameter instead of "last_found".

**Comment by jamiehynds** [comment]
Hey @meganlear - we discussed with Tenable directly and they advised that we should use `since` also. 

We've raised a PR to address your feedback and are addressing some other bugs/enhancements too: https://github.com/elastic/integrations/pull/6281

Thanks for all the feedback so far!

**Comment by meganlear** [comment]
We updated the integration earlier and we're definitely seeing more fixed vulnerabilities. Thank you!
