### ISSUE TITLE
Add default routing rules to sink-type integrations

### ISSUE THREAD

**Issue by felixbarny** [elastic/integrations#5988]
- should redict k8s.container_logs (as an example integration datastream) to `logs-*-*` so that we can do the routing?
- what to use for the routing rules for example for k8s.container_logs??

1. use container.image.name? distinguish the application from another. it contains also the repository name and the tag of the container image. you need to remove those parts if you want to use it. It would be great to be able to override this in case the same application is used for multiple purposes (eg. nginx ingress controller vs nginx web server. Hopefully in this case as well the output should look the same). You might want to split stdout from stderr and distinguish different stream to separate access_logs from error logs
2. you can't use pod.name since it is unique per namespace. For example within a daemont set, the pod name will have a k8s generated hash to make each instance unique.
3. you might allow the user to provide a well defined container label to do the routing

**Comment by gsantoro** [comment]
Closing this issue in favour of https://github.com/elastic/integrations/issues/6845 since we don't want to add default routing rules to an integration
