### ISSUE TITLE
Github Dependabot - GraphQL schema change 

### ISSUE THREAD

**Issue by CyberTaoFlow** [elastic/integrations#5993]
Hello, 

While troubleshooting a failure to obtain results from the dependabot stream of the github integration I decided to use curl to replicate the request.  Doing this returned more useful error output than the agent was giving me:

`"2023-04-25T10:35:44.862-0500"
"error processing response: template: :1:48: executing \"\" at <.last_response.body.data.organization.repositories.pageInfo.endCursor>: map has no entry for key \"data\""
"2023-04-25T10:35:44.862-0500"
"request finished: 0 events published"
`
Using elastic-agent inspect to get the query used then swapping out variables ($org) with their values using curl I was able to obtain the output below indicating an issue with the query field selection:

 `
 { "errors": [
    {
      "path": [
        "query fetchRepoAlerts",
        "organization",
        "repositories",
        "nodes",
        "vulnerabilityAlerts",
        "nodes",
        "fixReason"
      ],
      "extensions": {
        "code": "undefinedField",
        "typeName": "RepositoryVulnerabilityAlert",
        "fieldName": "fixReason"
      },
      "locations": [
        {
          "line": 1,
          "column": 339
        }
      ],
      "message": "Field 'fixReason' doesn't exist on type 'RepositoryVulnerabilityAlert'"
    }
  ]
}
`
Removing the field "fixReason" from the query resulted in obtaining the desired results.  Investigation uncovered this : 

https://docs.github.com/en/graphql/overview/changelog#schema-changes-for-2023-04-07

where the removal of fixReason is documented.

**Comment by kcreddy** [comment]
Fixed in https://github.com/elastic/integrations/pull/6015
