### ISSUE TITLE
Trigger "UpdatePackageStorage" on repository update 

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#60]
`mage UpdatePackageStorage` should be executed on git push to the integrations repository, to make sure we do not skip any package updates.

The script already reacts to integration versions that haven't been pushed yet. It lacks support for assignees and labels.

**Comment by mtojek** [comment]
Will this issue be resolved in favor of https://github.com/elastic/package-storage/pull/110 ?

**Comment by mtojek** [comment]
I want to trigger `mage UpdatePackageStorage` as additional step of the master job. I can adjust Jenkinsfile to execute it, but the script requires a Github token.

`mage UpdatePackageStorage` opens a PR against package-storage once it detects that there are changes that should be pushed. To push a PR it need a github token in file in `~/.elastic/github.token`, but the path can be adjusted. I suppose it should be stored in a secret.

As @kuisathaverat  is OOTO, can I ask for any guidance from the team? @cachedout @mdelapenya

**Comment by cachedout** [comment]
>  To push a PR it need a github token in file in ~/.elastic/github.token, but the path can be adjusted. I suppose it should be stored in a secret.

Can it use an environment variable or is it required that `~/.elastic/github.token` be written out?

**Comment by mtojek** [comment]
I can modify the code to fetch from two places. This is not a problem at all.

I see an issue in preparing the sandbox for the user, I assume Elasticmachine? The user needs to have forked a repository, https://github.com/elastic/package-storage , then while executing the script, it will update the fork, checkout new branch with changes and open a PR. I understand I need to open an issue with infra team to fork the public repo? I hope it's not the problem... 

BTW I don't need the Elasticmachine user. I can use any available one.

**Comment by cachedout** [comment]
@mtojek Which pipeline is this? If you have access to the [APM Pipeline Library](https://github.com/elastic/apm-pipeline-library), could you just use `githubCreatePullRequest()`

Example: https://github.com/elastic/apm/blob/master/.ci/Jenkinsfile#L113

**Comment by mtojek** [comment]
Pipeline: https://beats-ci.elastic.co/job/Beats/job/integrations/job/master/

The UpdatePackageStorage script doesn't only open a PR, but it executes also some logic to determine whether the PR should be created, hence it's hard to simply replace it with bunch of groovy's functions (like `githubCreatePullRequest()`).

Docs for UpdatePackageStorage: https://github.com/elastic/integrations/tree/master/dev/update-package-storage#principle-of-operation

As you see the script belongs to the https://github.com/elastic/integrations , but it access and commits to the https://github.com/elastic/package-storage .

**Comment by mtojek** [comment]
Actually with GITHUB_TOKEN, this would be relatively easy. I believe the missing link is where and how can I configure the forked package-storage, and which Github user can own this. In all cases I saw Elastic Machine, but I don't see it has any public repos available (and fork of package-storage must be public).

**Comment by cachedout** [comment]
> ..how can I configure the forked package-storage, and which Github user can own this. 

Hmm, this is an interesting question. We might need to bring in infra here to help advise us on the right course of action here. I will cc: @jonahbull as a starting point and see if we can figure this out.

**Comment by cachedout** [comment]
@mtojek In thinking about this a bit more, is there a specific reason that a fork even needs to exist? Could you just submit a PR to the main `package-storage` repo?

**Comment by mtojek** [comment]
Here is a sample PR: https://github.com/elastic/package-storage/pull/206

We used to review changes in the PR and also involved some CI checks around. Actually it's not main, but snapshot branch.

Later on, the package travels through different branches (snapshot->staging->production). I would keep this path aside from the context of the PR. Let's focus on the push from integrations to the package-storage.

**Comment by mtojek** [comment]
> Could you just submit a PR to the main package-storage repo?

Sorry I misread your comment, though you propose to directly push to the branch without repo. Actually, my above response is valid, but I will ask a followup them: is it possible to submit a PR without a fork to a different repo (integrations vs package-storage)?

**Comment by cachedout** [comment]
>  is it possible to submit a PR without a fork to a different repo (integrations vs package-storage)? or any repo?

I believe you'll need write permissions to push to a temporary branch on the repo but then after that, nothing special is required to create a PR from that newly created branch.

**Comment by mtojek** [comment]
Hmm.. this is good argument and it may work! I will try this way :)

**Comment by ruflin** [comment]
@mtojek This sounds very promising. If we are already on CI opening a PR, could this CI potentially just run the tests for the specific branch + the changes in addition and if they pass push a commit directly? :-D BTW, should not block your progress on this one, happy to have the PR.

**Comment by mtojek** [comment]
@cachedout 

In the PR draft https://github.com/elastic/integrations/pull/224 I'm trying to store credentials in variable GITHUB_TOKEN (https://github.com/mtojek/integrations/commit/7a018f97ac52c05a24160b0d6651f8a0f912bfa5#diff-8db37e8fcea0f1a8f2f39667e94ebcc4), but unfortunately it fails the CI without any hints: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations/detail/PR-224/7/pipeline/122

I assume that it's a security mechanism and I need some permissions?

**Comment by mtojek** [comment]
I found different credentials used by Kibana (`2a9602aa-ab9f-4e52-baf3-b71ca88469c7`) and managed to open a PR: https://github.com/elastic/package-storage/pull/302. I have no idea how to force Elasticmachine to sign CLA :)
