### ISSUE TITLE
[GCP Audit Integration] Dashboard not displaying the proper field 

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#6023]
Hello

The default **[Logs GCP] Audit** dashboard is not displaying the right the top audit user email because it's using user.email field that is no more populated. 
Should be using client.user.email instead 

Please can you fix this ?

**Comment by Danouchka** [comment]
cc @valerioarvizzigno  cc @endorama

**Comment by jamiehynds** [comment]
@P1llus would you mind looking at this one when you get to the GCP dashboard updates?

**Comment by Danouchka** [comment]
Fixed
