### ISSUE TITLE
Make ActiveMQ GA

### ISSUE THREAD

**Issue by muthu-mps** [elastic/integrations#6048]
The ActiveMQ integration is currently in BETA.

To make this integrations GA we need to validate the below use-case.

- [x] #8718
- [x] Can both Artemis and Classic supported.
- [x] Deprecation strategy if both cannot be supported together.

### Issues:

- [x] https://github.com/elastic/beats/issues/35113
- [ ] https://github.com/elastic/beats/issues/37543

```[tasklist]
### Issues and Enhancements
- [ ] https://github.com/elastic/integrations/issues/8861
- [ ] https://github.com/elastic/integrations/issues/8862
- [ ] https://github.com/elastic/integrations/issues/8863
- [ ] https://github.com/elastic/integrations/issues/8864
- [ ] https://github.com/elastic/integrations/issues/8865
- [ ] https://github.com/elastic/integrations/issues/8866
- [ ] https://github.com/elastic/integrations/issues/8867
```

### Enhancement Request:
https://github.com/elastic/enhancements/issues/11568
ActiveMQ released two flavours classic and Artemis with 5.18 release. Currently we support ActiveMQ classic version. As per the release highlights they mentioned that once the feature parity happens between classic and Artemis then the next major will be on Artemis.
@SubhrataK to provide updates on do we need to make ActiveMQ GA with or without supporting Artemis version.

**Comment by SubhrataK** [comment]
@muthu-mps Lets re-evaluate it in 8.9 release. Lets not make it GA in 8.8

**Comment by muthu-mps** [comment]
Based on the analysis the ActiveMQ integrations will be upgraded to GA. For more information please refer https://github.com/elastic/integrations/issues/8718

**Comment by muthu-mps** [comment]
@harnish-elastic - We need to fix this issue https://github.com/elastic/beats/issues/37543.

**Comment by alaudazzi** [comment]
@muthu-mps 
Please make sure that the Integrations [doc template](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md#overview) is applied.
