### ISSUE TITLE
Make IBMMQ GA

### ISSUE THREAD

**Issue by muthu-mps** [elastic/integrations#6050]
### Integration release checklist
This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

- [x] Change follows [development guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines)
- [x]  Supported versions of the monitoring target are documented
- [x]  Supported operating systems are documented (if applicable)
- [x]  Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x]  Documentation exists
- [x]  Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x]  At least a manual test with ES / Kibana / Agent has been performed.

### Checklist
| Integration  | Alpha / Beta Release Duration | Documentation | Move To GA |
|---------------|-----------------|-----------------|-------------|
| IBM MQ | 10M | Verified | :green_heart:

| Data streams | Alpha / Beta Release | Automated Tests | Simulated / Live | Manual Testing | Move To GA |
|---------------|-----------------|----------------------|-----------------|-----------------|-------------|
| errorlog| 10M | Yes | Live | done | :green_heart:
| qmgr| 9M | Yes | Live | done | :green_heart:

### Discussions:

- `Metricbeat of IBMMQ` is in beta and we are not considering metricbeat to be moved to GA as the metrics collected from integrations uses `Prometheus`.
- The enhancement requests on metricbeat is not considered when making IBMMQ GA.

### Enhancement Requests:

https://github.com/elastic/enhancements/issues/18669 - Currently we collect metrics using Prometheus HTTP endpoints. The request is to collect metrics using other option using Go Clients.

**Comment by muthu-mps** [comment]
### Test Execution:
Verified the metrics collection by setting up the latest version of Couchbase server.
Data is getting loaded in the dashboards.
System test execution is successful.
Pipeline test execution is successful.

**Comment by agithomas** [comment]
Adding a recommendation for future consideration

If the package is going through a bigger multi-pr enhacement, it would be best to keep the GA promotion on-hold until the enhancement is complete. 

Reference PRs : 

https://github.com/elastic/integrations/pull/6466
https://github.com/elastic/integrations/pull/6468
