### ISSUE TITLE
Make MemCached GA

### ISSUE THREAD

**Issue by muthu-mps** [elastic/integrations#6055]
### Checklist

| Integration  | Time Duration | Documentation | Move To GA |
|---------------|-----------------|-----------------|-------------|
| MemCached | 11 Months | Verified | :green_heart:

Data streams | Time Duration | Automated Tests | Simulated / Live | Manual Testing | Move To GA
-- | -- | -- | -- | -- | --
stats | 11 Months | Yes | Live | done | 💚

### Issues:
- [x] https://github.com/elastic/integrations/issues/5997

**Comment by ishleenk17** [comment]
@muthu-mps : You might want to check if doing this backlog task is importnat befre moving it to GA. 
https://github.com/elastic/observability-dev/issues/2313
