### ISSUE TITLE
Apache TSDB Enablement

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#6075]
## Test Environment Setup
- [x] Creation of Test Environment

## Datastream : `status` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/6077

    
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.

**Comment by lalit-satapathy** [comment]
@agithomas, I see missing metric types PR but see them already added. Please confirm it is accurate?

**Comment by agithomas** [comment]
> @agithomas, I see missing metric types PR but see them already added. Please confirm it is accurate?

Yes, it is already present
