### ISSUE TITLE
[Meta] Azure Functions Integration

### ISSUE THREAD

**Issue by SubhrataK** [elastic/integrations#6086]
Azure Functions is a serverless computing service provided by Microsoft Azure that enables developers to build and deploy event-driven, scalable, and pay-per-execution functions or small pieces of code without the need to manage and provision infrastructure. These functions can be triggered by various events like HTTP requests, database changes, or messages in a queue. 

The scope of this issue is to deliver an OOTB integration for Azure Functions that collects logs and metrics both.

The following type of logs are generated by Azure Functions:
**FunctionAppLogs**

The following metrics are available for Azure Functions:

- **FunctionExecutionCount** - Function execution count indicates the number of times your function app has executed. This value correlates to the number of times a function runs in your app.
- **FunctionExecutionUnits** - Function execution units are a combination of execution time and your memory usage. 

- **Response Time** - The time taken for the app to serve requests, in seconds.
- **Average memory working set** - The average amount of memory used by the app.
- **Connections** - The number of bound sockets existing in the sandbox (w3wp.exe and its child processes).
- **CPU Time** - The amount of CPU consumed by the app, in seconds.
- **Current Assemblies** - The current number of Assemblies loaded across all AppDomains in this application.
- **Data In** - The amount of incoming bandwidth consumed by the app.
- **Data Out** - The amount of outgoing bandwidth consumed by the app.
- **File System Usage** - The amount of usage in bytes by storage share.
- **Gen 0 Garbage Collections** - The number of times the generation 0 objects are garbage collected since the start of the app process. Higher generation GCs include all lower generation GCs.
- **Gen 1 Garbage Collections** - The number of times the generation 1 objects are garbage collected since the start of the app process. Higher generation GCs include all lower generation GCs.
- **Gen 2 Garbage Collections** - The number of times the generation 2 objects are garbage collected since the start of the app process.
- **Handle Count** - The total number of handles currently open by the app process.
- **Health Check Status** - The average health status across the application's instances in the App Service Plan.
- **Http 2xx** - The count of requests resulting in an HTTP status code ≥ 200 but < 300.
- **Http 3xx** - The count of requests resulting in an HTTP status code ≥ 300 but < 400.
- **Http 4xx** - The count of requests resulting in an HTTP status code ≥ 400 but < 500.
- **Http Server Errors** - The count of requests resulting in an HTTP status code ≥ 500 but < 600.
- **IO Other Bytes Per Second** - The rate at which the app process is issuing bytes to I/O operations that don't involve data, such as control operations.
- **IO Other Operations Per Second** - The rate at which the app process is issuing I/O operations that aren't read or write operations.
- **IO Read Bytes Per Second** - The rate at which the app process is reading bytes from I/O operations.
- **IO Read Operations Per Second** - The rate at which the app process is issuing read I/O operations.
- **IO Write Bytes Per Second** - The rate at which the app process is writing bytes to I/O operations.
- **IO Write Operations Per Second** - The rate at which the app process is issuing write I/O operations.
- **Memory working set** - The current amount of memory used by the app.
- **Private Bytes** - Private Bytes is the current size, in bytes, of memory that the app process has allocated that can't be shared with other processes.
- **Requests** - The total number of requests regardless of their resulting HTTP status code.
- **Requests In Application Queue** - The number of requests in the application request queue.
- **Thread Count** - The number of threads currently active in the app process.
- **Total App Domains** - The current number of AppDomains loaded in this application.
- **Total App Domains Unloaded** - The total number of AppDomains unloaded since the start of the application.

### The subtasks for adding a new integration are divided into: 
- [x] #6704  
- [x] #6723

**Comment by zmoog** [comment]
@rameshelastic, @lalit-satapathy the Azure Function service is currently producing logs documents containing invalid JSON. It's something Microsoft is [aware](https://learn.microsoft.com/en-us/answers/questions/1001797/invalid-json-logs-produced-for-function-apps) of, have some plan to address it [^1], but no ETA.

We are working on a [workaround](https://github.com/elastic/beats/pull/34874) at the input level.

[^1]: we created a support ticket to raise the issue, and they redirected us to this issue: https://github.com/Azure/azure-functions-host/issues/7864

**Comment by zmoog** [comment]
We can use the `azure-eventhub` input for collecting logs.  We may need to use the Azure Monitor metricset to collect the metrics; we need to double-check if these metrics are stored in Azure Monitor or App Insights. 

@SubhrataK, this should be an independent integration with two data streams: one for the logs and another for the metrics.

**Comment by devamanv** [comment]
@rameshelastic @SubhrataK Do we intend to create a separate integration pertaining to Azure functions or have two separate datastreams one each for function logs and metrics inside the already existing Azure logs integration? 

cc: @zmoog

**Comment by SubhrataK** [comment]
@devamanv Discussed this with Lalit also, we will add two new datastreams in the already existing Azure package.

**Comment by zmoog** [comment]
@SubhrataK, which package? 

We currently have several Azure-focused packages:

| Package | Logs | Metrics |
|------|----|----|
| Azure Logs | x | |
| Azure Metrics | | x |
| Azure Application Insights | | x |
| Azure Billing | | x |
| Azure Blob Storage | x | |
| Azure Frontdoor | x | |

**Comment by zmoog** [comment]
When I joined Elastic on Feb 2022 there were only the Azure Logs, Metrics, Billing, and Application Insights packages.

during the last 12 months, our team and others added new data streams to the Azure Logs package, and SEI added the Frontdoor and Blob Storage packages.

We have both type-oriented packages (Azure Logs and Metrics) and product oriented packages (Azure Frontdoor).

**Comment by devamanv** [comment]
Done with the initial setup as in #6271 and #6272. The next step will be to analyze the logs and create a new data stream inside the [azure](https://github.com/elastic/integrations/tree/main/packages/azure/data_stream) package

**Comment by lalit-satapathy** [comment]
>@lalit-satapathy, which package do you have in mind?

@zmoog Is this fine being a data_stream in the main [azure](https://github.com/elastic/integrations/tree/main/packages/azure/data_stream) package?

**Comment by zmoog** [comment]
@lalit-satapathy, we picked the [Azure Logs](https://github.com/elastic/integrations/tree/main/packages/azure) package, so @devamanv was able to start working on the logs part of this task. 

However, since this integration requires logs and metrics data streams, we should evaluate a dedicated package. The [Azure Logs](https://github.com/elastic/integrations/tree/main/packages/azure) is a collection of Azure services that we support only with logs.

So what about creating a `packages/azure_functions` package with one data stream for logs and one (or more) for the metrics?

We already have product-oriented packages in the Azure area, for example:

- Azure Frontdoor
- Azure Application Insights
- Azure Blob Storage

**Comment by devamanv** [comment]
### Some additional details about Azure Functions(metrics collection):
- `FunctionExecutionCount` and `FunctionExecutionUnits` are the only Azure Functions specific metrics. These are specifically used for estimating consumption costs
- All the other metrics are General App Service metrics which can also be used to monitor function apps. 
- All these metrics are automatically collected platform metrics by the Azure monitor. These metrics are routed the from the Azure monitor pipeline using a Diagnostic Setting under the `AllMetrics` category to a destination like Event hub. 
- Platform metrics are collected from Azure resources at one-minute
- You can analyze metrics for Azure Functions using metrics explorer by opening Metrics from the Azure Monitor menu in the Azure Portal.
- https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftwebsites
- All  metrics currently available with the consolidated metric pipeline in Azure Monitor are organized by resource provider and a resource type e.g. the service apps are provided under the `Microsoft.Web/sites` , [docs](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftwebsites)
- Use [diagnostic settings](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings) to route platform metrics to
-

**Comment by zmoog** [comment]
> All these platform metrics are sent automatically to [Azure Monitor Metrics](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/data-platform-metrics) by default. These metrics can then be routed from the Azure monitor pipeline using a Diagnostic Setting under the AllMetrics category to a destination like Event Hub.

I see more Azure services adding the option of exporting metrics using the diagnostic settings. However, up until now, we have used the Event Hub for logs only with the [azure-eventhub](https://github.com/elastic/beats/tree/main/x-pack/filebeat/input/azureeventhub) input. If this trend continues, we should evaluate this opportunity for the metrics. 

AFAIK, we can bring metrics from Azure using the [Azure Monitor](https://github.com/elastic/beats/tree/main/x-pack/metricbeat/module/azure/monitor) and [Application Insights](https://github.com/elastic/beats/tree/main/x-pack/metricbeat/module/azure/app_insights) metricsets only. 

> All these metrics are stored in Azure Monitor Metrics and may not require Application Insights at all unless the intent is to optimize the memory usage of a function app. At this point, we can use the performance counter data collected by Application Insights. Refer [docs](https://learn.microsoft.com/en-us/azure/azure-functions/monitor-functions-reference#azure-functions-specific-metrics)

If we ship Azure Functions as a new independent integration package, we could use:
- one data stream for logs 
- one data stream for metrics using Azure Monitor 
- (optional?) one data stream for metrics using Azure Application Insights 

Azure Monitor and App Insights require two different meticsets. 

***

Choosing between adding Azure Functions to existing integration packages or creating a new one requires product and technical considerations. @SubhrataK @lalit-satapathy, what's your perspective on this topic?

When @devamanv completes the logs, we must choose whether to add a new integration package or use existing ones.

**Comment by devamanv** [comment]
### Conclusion on the approach
It was decided to create a separate integration package for Azure functions and have two data streams, each for logs and metrics respectively. 

Completed #6273, the changes so far are [here](https://github.com/elastic/integrations/pull/6417/files). Added more tasks(#6413, #6414, and #6415) in the meta issue description that are required to complete the integration.

**Comment by devamanv** [comment]
Added a few more changes as part of #6415 to the PR. The following changes are in place:
- Ingest pipeline for Azure function logs
- Fields mappings as mentioned in the official [schema](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/functionapplogs) from Microsoft Azure
-  Documentation wherever needed

Next steps:
- End-to-end testing of the pipelines and that logs show up in Elasticsearch
- Add the required assets like Dashboards, images, icons etc.

**Comment by devamanv** [comment]
Added the Azure Functions integration as a separate package(tile) as seen below:
![image](https://github.com/elastic/integrations/assets/38116245/4d677489-0d44-4120-868b-d3acc22d39ae) 
<img width="1909" alt="image" src="https://github.com/elastic/integrations/assets/38116245/22929a83-ee06-4d9c-a679-6a2de2050edb">

**Note: This is on a local package registry**

**The expected document to be ingested into Elasticsearch is as follows:**
```json
{
    "expected": [
        {
            "@timestamp": "2023-05-23T20:11:59.000Z",
            "azure": {
                "category": "FunctionAppLogs",
                "functions": {
                    "app_name": "test-function",
                    "function_invocation_id": "d878e365-b3d6-4796-9292-7500acd0c677",
                    "function_name": "Functions.hello",
                    "host_instance_id": "bb84c437-4c26-4d0b-a06d-7fc2f16976e3",
                    "host_version": "4.19.2.2",
                    "process_id": 67,
                    "role_instance": "54108609-638204200593759681"
                },
                "level": "Information",
                "level_id": 2,
                "operation_name": "Microsoft.Web/sites/functions/log"
            },
            "cloud": {
                "provider": "azure"
            },
            "ecs": {
                "version": "8.7.0"
            },
            "event": {
                "action": "FunctionStarted",
                "category": [
                    "network"
                ],
                "kind": "event",
                "original": "{\"time\":\"2023-05-23T20:11:59Z\",\"resourceId\":\"/SUBSCRIPTIONS/12CABCB4-86E8-404F-A3D2-1DC9982F45CA/RESOURCEGROUPS/TEST-RG/PROVIDERS/MICROSOFT.WEB/SITES/TEST-FUNCTION\",\"category\":\"FunctionAppLogs\",\"operationName\":\"Microsoft.Web/sites/functions/log\",\"level\":\"Informational\",\"location\":\"East US\",\"properties\":{\"appName\":\"test-function\",\"roleInstance\":\"54108609-638204200593759681\",\"message\":\"Executing Functions.hello (Reason=This function was programmatically called via the host APIs., Id=d878e365-b3d6-4796-9292-7500acd0c677)\",\"category\":\"Function.hello\",\"hostVersion\":\"4.19.2.2\",\"functionInvocationId\":\"d878e365-b3d6-4796-9292-7500acd0c677\",\"functionName\":\"Functions.hello\",\"hostInstanceId\":\"bb84c437-4c26-4d0b-a06d-7fc2f16976e3\",\"level\":\"Information\",\"levelId\":2,\"processId\":67,\"eventId\":1,\"eventName\":\"FunctionStarted\"}}",
                "type": [
                    "connection"
                ]
            },
            "message": "Executing Functions.hello (Reason=This function was programmatically called via the host APIs., Id=d878e365-b3d6-4796-9292-7500acd0c677)",
            "observer": {
                "product": "Azure Functions",
                "type": "functions",
                "vendor": "Azure"
            },
            "tags": [
                "preserve_original_event"
            ]
        }
    ]
}
```

@zmoog @lalit-satapathy @SubhrataK is the expected document good enough to proceed ahead? Please suggest.

**Comment by zmoog** [comment]
Hey @devamanv, this looks good!

Here are a few things I noticed in your sample document:

## 1 — `azure.category` vs. `azure.functions.category`

 Most[^1] Azure Logs place the `category` field in the `azure.<type>` path. In your case, it's `azure.category`, but I would keep it as `azure.functions.category` field. 

## 2 — the `message` field

I would keep the `message` field containing the function message inside the `azure.functions` field to avoid confusion and abiguity. In Azure Logs, the `message` field at the root level has special semantics.  

The Agent [sends](https://github.com/elastic/beats/blob/4af3e606c68403b8beafe5f4e0906be3ddcfdf87/x-pack/filebeat/input/azureeventhub/input.go#L152-L155) the whole JSON document it received from the event hub in a field called `message`. Then the pipeline processes it and renames it as `event.original` at the end.

I would generally keep the event data from the `properties` field together unless they have a specific destination per ECS semantics.

[^1]: For example, Firewall, Audit, and Provisioning logs.

**Comment by devamanv** [comment]
Pushed some new changes to the [PR](https://github.com/elastic/integrations/pull/6417) for Azure Functions logs to mask the sensitive fields. Waiting for reviews.

**Comment by devamanv** [comment]
> CPU Time - The amount of CPU consumed by the app, in seconds.

This metric is App services specific [[source](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-web-sites-metrics)], and should not be a part of the list of metrics. I have dropped this metric from the PR currently, please let me know if we should keep it this way. 

cc: @SubhrataK @rameshelastic

**Comment by devamanv** [comment]
The Azure Functions integration is complete and this issue can be closed.
