### ISSUE TITLE
Error message is displayed to user, when user is trying to add AWS integrations to agent policies.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#6088]
**Kibana version:** 8.8.0 BC2 staging Kibana cloud environment

**Host OS:** Windows
**Browser:** Chrome

**Build details:**
VERSION: 8.8.0 BC2
BUILD: 62857
COMMIT: 33efd47ee6927b54b328e901fe31d31eae875325
Artifact: https://staging.elastic.co/8.8.0-118443e6/summary-8.8.0.html

**Preconditions:**

- 8.8.0 BC2 staging Kibana cloud environment should be available.

**Steps to reproduce:**

- Navigate to Fleet > Policies Tab.
- Using "Add integration" button on Policy detail page attempt to add "AWS DynamoDB" integration.
- Observe Error message is displayed.

**Screenshots:**
![image](https://user-images.githubusercontent.com/72375798/236193248-4918fae4-766f-424a-802d-3a15f45d33fa.png)
![image](https://user-images.githubusercontent.com/72375798/236193523-cd758937-854b-42fe-8a45-eb4a7eded8f9.png)

**Expected Result:**
- No error message should be displayed to user, when user is trying to add AWS integrations.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @kpollich

**Comment by jen-huang** [comment]
@efd6 I think your PR https://github.com/elastic/integrations/pull/5740 introduced [Fleet-created tags](https://github.com/elastic/integrations/tree/e59f29f159f215010cf676b7f2718d3fe1760f27/packages/system/kibana/tag) to the System integration.

Could you please make sure the version of `elastic-package` you are using includes the fix we made to strip these tags out when exporting dashboards?: https://github.com/elastic/elastic-package/pull/1206

Thanks!

**Comment by jen-huang** [comment]
Full error:
```json
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Error installing aws 1.34.3: Encountered 1 errors creating saved objects: [{\"type\":\"search\",\"id\":\"aws-30ccde50-7397-11ea-a345-f985c61fe654\",\"error\":{\"isBoom\":true,\"isServer\":false,\"data\":null,\"output\":{\"statusCode\":400,\"payload\":{\"message\":\"[attributes.sort]: types that failed validation:\\n- [attributes.sort.0.0]: array size is [0], but cannot be smaller than [2]\\n- [attributes.sort.1.0]: expected value of type [string] but got [Array]: Bad Request\",\"statusCode\":400,\"error\":\"Bad Request\"},\"headers\":{}},\"type\":\"unknown\"}}]"
}
```

It is failing to install [this saved search asset](https://github.com/elastic/integrations/blob/5176089e30cf2932d6e5ca7c90caa2ab9a237bee/packages/aws/kibana/search/aws-30ccde50-7397-11ea-a345-f985c61fe654.json) which hasn't been touched in a few years.

Investigating to see if changes in https://github.com/elastic/kibana/pull/154016, which added stricter [schema validation for `sort` field](https://github.com/elastic/kibana/blob/25b8f92753eb2936e9079e8a349f2913acd65a54/src/plugins/saved_search/server/saved_objects/search.ts#L52) may be the culprit...

**Comment by jen-huang** [comment]
@davismcphee I believe the change above is causing the saved objects importer to reject [`sort: []` on this saved search object](https://github.com/elastic/integrations/blob/5176089e30cf2932d6e5ca7c90caa2ab9a237bee/packages/aws/kibana/search/aws-30ccde50-7397-11ea-a345-f985c61fe654.json#L48). Would it be possible to adjust the schema to allow an empty array here for BWC?

**Comment by davismcphee** [comment]
@jen-huang This was definitely caused by https://github.com/elastic/kibana/pull/154016 and was an oversight on my part -- empty sort arrays are a valid scenario for saved searches. I've opened https://github.com/elastic/kibana/issues/156724 to track the bug in the Kibana repo and will publish a PR asap to get the schema fixed.

**Comment by jen-huang** [comment]
Thanks @davismcphee!

@dikshachauhan-qasource please validate the fix on the next BC. Thanks!

**Comment by dikshachauhan-qasource** [comment]
Hi @jen-huang  & @davismcphee 

We have revalidated this issue on the latest 8.8.0 BC2 Kibana staging cloud build and found it **not fixed**.

**Observations:**
- Error message is still displayed to user, when user is trying to add AWS integrations to agent policies. 

**Build details:**
```
VERSION: 8.8.0 BC2
BUILD: 62857
COMMIT: 33efd47ee6927b54b328e901fe31d31eae875325
Artifact: https://staging.elastic.co/8.8.0-118443e6/summary-8.8.0.html

```

*Screenshots:**
![image](https://user-images.githubusercontent.com/72375798/236753058-7da91472-7f29-448d-943b-0fb29d5f7e22.png)
![image](https://user-images.githubusercontent.com/72375798/236753141-adc2b387-d650-41e3-9cd2-62501cf63b1f.png)


**Full error:**
`Error installing aws 1.34.3: Encountered 1 errors creating saved objects: [{"type":"search","id":"aws-30ccde50-7397-11ea-a345-f985c61fe654","error":{"isBoom":true,"isServer":false,"data":null,"output":{"statusCode":400,"payload":{"message":"[attributes.sort]: types that failed validation:\n- [attributes.sort.0.0]: array size is [0], but cannot be smaller than [2]\n- [attributes.sort.1.0]: expected value of type [string] but got [Array]: Bad Request","statusCode":400,"error":"Bad Request"},"headers":{}},"type":"unknown"}}]
`

Hence, we are **reopening** this ticket.

Thanks!!

**Comment by dikshachauhan-qasource** [comment]
Hi @jen-huang 

Thanks for the update, we will revalidate this issue on BC3.

Thanks.

**Comment by dikshachauhan-qasource** [comment]
Hi @jen-huang 

We have revalidated this issue on latest 8.8.0 BC3 Kibana staging cloud build and found it **working fine.**

**Observation:**
- User is now able to add the AWS integrations successfully to the agent policies.

**Build details:**
```
VERSION: 8.8.0
BUILD: 62994
COMMIT: 85b22d307ab93fca95c1698ede4cb61d85f3d314

```
**Screenshot:**
![image](https://github.com/elastic/integrations/assets/72375798/62452637-a58d-40ef-bcd5-ff332875724a)


Hence, we are marking it as "QA:Validated".

Thanks!!

**Comment by harshitgupta-qasource** [comment]
### `Bug Conversion:`

We have updated **01 testcase** for this scenario in our fleet test suite at:
  - https://elastic.testrail.io/index.php?/cases/view/15415

Thanks
