### ISSUE TITLE
Duplicate tags entries are created on Stack Management> Tags page, when user creates a new policy in Fleet.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#6096]
**Kibana version:** 8.8.0 BC2 staging Kibana cloud environment

**Host OS:** Windows
**Browser:** Chrome

**Build details:**
VERSION: 8.8.0 BC2
BUILD: 62857
COMMIT: 33efd47ee6927b54b328e901fe31d31eae875325
Artifact: https://staging.elastic.co/8.8.0-118443e6/summary-8.8.0.html

**Preconditions:**

- Fresh 8.8.0 BC2 staging Kibana cloud environment should be available.

**Steps to reproduce:**

- Navigate to Stack Management> Tags page.
- Observe, no entries are available on Fresh Kibana instance.
- Navigate to Fleet > Policies Tab.
- Using "Create Policy" button on Policy tab, attempt to create a new policy.
- Navigate back to Stack Management> Tags page.
- Observe, Duplicate tags entries for System and Managed tag is displayed on the page.

**NOTE:** Issue is reproducible on 8.7.1 patch as well.

**Screenshots:**
![image](https://user-images.githubusercontent.com/72375798/236204280-9b3d6ace-86e2-4579-9e7d-c59f95d76694.png)
![image](https://user-images.githubusercontent.com/72375798/236204402-6685010b-446e-4a6d-9e87-fde60e01475d.png)

**Expected Result:**
- Duplicate tags entries should not be created on Stack Management> Tags page, when user creates a new policy in Fleet.

**Comment by efd6** [comment]
@jen-huang To clarify, are you asking me to remove these tags, or are you asking me to be aware of this in the future? The tags were not explicitly added by me, and when I tried removing them manually, the build broke.

**Comment by efd6** [comment]
It seems I cannot use the re-export to strip these tags, since the version will not install. I am not sure what the pathway is to move this forward given that my previous manual attempts in working on #5740 broke the build.

It would be nice to understand why these tags were added?

**Comment by dikshachauhan-qasource** [comment]
Hi @jen-huang & @efd6 

We have revalidated this issue on the latest 8.8.0 BC2 Kibana staging cloud build and found it **fixed now.**

**Observartions:**
- No Duplicate tags entries are created now on Stack Management> Tags page, when user creates a new policy in Fleet.

**Build details:**
```
VERSION: 8.8.0 BC2
BUILD: 62857
COMMIT: 33efd47ee6927b54b328e901fe31d31eae875325
Artifact: https://staging.elastic.co/8.8.0-118443e6/summary-8.8.0.html
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/72375798/236751519-e4049dfb-c06a-4475-8db1-39acd35f6715.png)


Hence, we are marking it as "QA:VAlidated".

Thanks!!
