### ISSUE TITLE
[Mimecast] Audit Events for `Logon Authentication Failed` not Parsing Properly

### ISSUE THREAD

**Issue by MakoWish** [elastic/integrations#6097]
The provided dissect patterns are unfortunately splitting the `eventInfo` in the wrong place, and this is causing the rest of the ingest pipeline to be skipped over. We ultimately end up without the client IP, date, time, etc. fields. 

Here is a sample message that is not being parsed correctly:

```
{"auditType":"Logon Authentication Failed","category":"authentication_logs","eventInfo":"Failed authentication for john.doe@contoso.com \u003cDoe, John\u003e, Date: 2023-05-01, Time: 13:50:07 GMT-04:00, IP: 103.87.232.7, Application: MfO, Method: SP-initiated SAML, Reason: Account disabled","eventTime":"2023-05-01T17:50:07+0000","id":"eNoVzlETgTAAwPHvstfcaRHWnYdZpUiElQcvWVPdlbnVSM53xwf43-__Bg1nSvIyAxZIaEb8fKEF9Bq4wito7LxeW676y5oUU3QMt1XCcD9ZxPazOg-JUyxpXt9Jl-Sa0ft1tFyHqh-Fpm3vVoXusg32ZOS1rrPvrs-DPCFH19IAy9nKn4MBSFVWtpXI__h4bExHBoJoAJhqWlFzyUTGf1eEHjCEOobI_DUPLptS3IAFP1_HBjvt","user":"john.doe@contoso.com"}
```

It seems the dissect pattern `%{mimecast.info}, %{mimecast.rest_of_event_info}` is the one that is parsing the `mimecast.eventInfo` field in this case, but since there is a comma in `\u003cDoe, John\u003e`, it is splitting the field there instead of after the closing `>` (\u003e) where I believe it is intended to be split. 

Eric

**Comment by MakoWish** [comment]
Verified the comma in the event is the issue. For kicks, I removed the comma, giving `\u003cDoe John\u003e`, and it parsed properly. 

I also noticed `user.email` is being added to `related.users`. I think that should be removed.

**Comment by chemamartinez** [comment]
Hi @MakoWish,

I already opened a PR to fix the parsing error.

Regarding the comment about the `user.email` field. Based on the [description](https://www.elastic.co/guide/en/ecs/8.7/ecs-related.html#field-related-user) of the `related.users` field I would let the email included along with the user name since it is also an identifier.
```
All the user names or other user identifiers seen on the event.
```
However, I don't really know what the standard is here because I see some integrations include it and others doesn't.

**Comment by MakoWish** [comment]
This is the first time I have seen email addresses in `user.email`, but if the standard allows for it, that's cool.
