### ISSUE TITLE
[SQL Input Package] Period Configuration  in SQL Input Package

### ISSUE THREAD

**Issue by ishleenk17** [elastic/integrations#6122]
The period configuration in SQL Input package is 10 seconds by default. 
It's been reported that the period configuration is not picked up even if we change it. It always takes 10 seconds. 
This issue will verify this and fix if the issue exists

**Comment by rameshelastic** [comment]
The description is empty. can we add some more details to this?

**Comment by ishleenk17** [comment]
Checked out the period functionality. It is working as expected. 
When the period is changed to 60s, the change can be seen in the events coming in. 
<img width="1507" alt="Screenshot 2023-07-19 at 1 21 41 PM" src="https://github.com/elastic/integrations/assets/102962586/647fc35b-9fa6-4d96-80f5-ebd043835449">


When the period was changed to 20s, it gets depicted in the events
<img width="1535" alt="Screenshot 2023-07-19 at 1 25 26 PM" src="https://github.com/elastic/integrations/assets/102962586/446f6bf6-b198-4683-b0ad-991631c868b9">
