### ISSUE TITLE
[Meta][TSDB] TSDB Release for multiple packages

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#6152]
As part of TSDB enablement, integration packages will be having a beta version available for testing. This issue captures the information of all the related PRs 

- Redis - https://github.com/elastic/integrations/pull/6153
- Nginx - https://github.com/elastic/integrations/pull/6129
- CouchDB - https://github.com/elastic/integrations/pull/6166
- MSSQL - https://github.com/elastic/integrations/pull/6181
- Oracle - https://github.com/elastic/integrations/pull/6195
- InfluxDB - https://github.com/elastic/integrations/pull/6223
- RabbitMQ - https://github.com/elastic/integrations/pull/6229
- Kafka - https://github.com/elastic/integrations/pull/6277
- Apache - https://github.com/elastic/integrations/pull/6330
- AWS Redshift - https://github.com/elastic/integrations/pull/6359
- IBM MQ - https://github.com/elastic/integrations/pull/6471
- Active MQ - https://github.com/elastic/integrations/pull/6689
- MongoDb: https://github.com/elastic/integrations/pull/6692
- Vsphere: https://github.com/elastic/integrations/pull/6693
- IIS: https://github.com/elastic/integrations/pull/6694

**Comment by agithomas** [comment]
The issue is related to https://github.com/elastic/integrations/issues/5233

**Comment by lalit-satapathy** [comment]
Closing this.
