### ISSUE TITLE
[Palo Alto] Next-Gen Firewall integration pipeline fails on machine account usernames (machine$@domain.org)

### ISSUE THREAD

**Issue by dustintennill** [elastic/integrations#6172]
Versions: 
Elastic Agent 8.7.1
Elastic/Kibana 8.7.1 

Problem: 
The Palo Alto Next Gen integration drops incoming logs from Palo when the source username is in this format: 
MachineName$@somedomain.org.  

This issue is essentially the same as https://github.com/elastic/integrations/issues/5598 - I wasn't sure if I should add to that or create a new issue. It impacts the _temp_.srcuser and the _temp_.dstuser fields. 

Here is sample data to test in the ingest pipeline "logs-panw.panos-3.7.1"  (scrubbed of relevant company data): 
```
[
{
"_index": "fakeindex",
"_id": "fakeid",
"_version": 1,
"_score": 0,
"_source": {
"message": "1,2023/04/24 11:18:35,013101012679,USERID,login,2561,2023/04/24 11:18:35,vsys1,192.168.1.43,testmachine$@fakedomain.org,localpasvc,0,1,36000,0,0,agent,,7210135588942986414,0x0,0,0,0,0,,PA5000,1,,2023/04/24 11:18:35,1,0x0,testmachine$@fakedomain.org,,2023-04-24T11:18:36.548-04:00"
}
}
]
```

Screenshot of ingest pipeline testing: 
![Screenshot from 2023-05-11 14-15-22](https://github.com/elastic/integrations/assets/9064880/d0247bb4-c01a-47a4-9b8d-a899849253bb)

A potential fix is to add this pattern to the list of grok patterns: 
^%{USERNAMEM:source.user.name}@%{HOSTNAME:source.user.domain}$

Pic of fixed pattern: 
![Screenshot from 2023-05-11 14-21-23](https://github.com/elastic/integrations/assets/9064880/869ef5da-e883-4481-ae50-068be38ef75f)

This is the first time I've posted an issue for an Elastic issue here - please let me know if I've missed something that's required.

**Comment by efd6** [comment]
@jamiehynds Sorry, this got missed. I expect that to fix the title issue (@dustintennill Can you please try with a version of the package at or after 3.7.2?). I will not fix the issue with spaces in hostnames. We are using a derivative of the elasticsearch HOSTNAME grok pattern:
```
HOSTNAME \b(?:[0-9A-Za-z][0-9A-Za-z-]{0,62})(?:\.(?:[0-9A-Za-z][0-9A-Za-z-]{0,62}))*(\.?|\b)
```
@dustintennill For the space issue, do you see that commonly? I wish we could just tell people not to do that, but I can see nothing which makes it invalid, and have seen some indication that it is allowed, though (correctly) frowned upon. I'll send a change to handle this.
