### ISSUE TITLE
OpenCTI

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#6186]
### Description
OpenCTI is an open source platform allowing organizations to manage their cyber threat intelligence knowledge and observables. It enabled security analysts to structure, store, organize and visualize technical and non-technical information about cyber threats.

For an overview of OpenCTI please see more information on their [Github](https://github.com/OpenCTI-Platform/opencti) and [website](https://www.filigran.io/en/solutions/products/opencti/). 

### Architecture
OpenCTI includes a GraphQL API which should enable to ingest indicators and associated metadata (such as labels) into Elastic. 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [x] Supported versions of the monitoring target are documented
- [x] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to: 8.9.0

### New Package

- [x] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [x] Dashboards exists
- [x] Screenshots added or updated
- [x] Datastream filters added to visualizations

### Log dataset changes

- [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [x] Generated output for at least 1 log file exists
- [x] Sample event (`sample_event.json`) exists

**Comment by chrisberkhout** [comment]
Some background info and design choices are described in this document: [OpenCTI integration development notes](https://docs.google.com/document/d/1Brp_DjGhp5t_a70qmNDY5b-jeW-lKhlRhCxZbvV5PzY/edit?usp=sharing).

**Comment by chrisberkhout** [comment]
The [OpenCTI Mappings](https://docs.google.com/spreadsheets/d/1w5y_2XVWBZCFaMFPiFQ_jehjsH9Nntfwa8a3nKuxZCs/edit?usp=sharing) spreadsheet is complete.

Next I'll finish translating that into field definitions and an ingest pipeline.
