### ISSUE TITLE
Integrations to be Migrated from TSVB to Lens

### ISSUE THREAD

**Issue by SubhrataK** [elastic/integrations#6194]
This issue lists all the integrations with visualisations that need migration to Lens. This list is a WIP.

**AWS**

AWS Transit Gateway
AWS ELB
AWS Lambda
AWS CloudTrail
Amazon VPN
Amazon DynamoDB
Amazon S3 Storage Lens
Amazon SQS
AWS Usage
Amazon RDS
Amazon S3
Amazon Inspector
Amazon VPC
Amazon NAT Gateway
AWS Security Hub
AWS EC2
AMAZON SNS
AWS ELB
AWS Billing 

**Azure**

Azure Application Gateway
Azure Firewall logs
Azure Spring Cloud logs
Azure activity logs
Azure platform logs
Azure Active Directory
Azure Event Hub Input
Azure Metrics
Azure Application insights
Azure Billing

**GCP**

GCP Metrics

**Comment by milan-elastic** [comment]
Following issues are used for lens migration work, these issues are completed hence closing this issue

- #6141 
- #6907
