### ISSUE TITLE
[O11y][AWS ELB] Lens Migration

### ISSUE THREAD

**Issue by milan-elastic** [elastic/integrations#6201]
Manually migrate AWS `ELB` visualizations to the lens in the current Kibana version `8.7.1` itself. 

## Preparation of data for testing
- [x] Use sample_event.json / setup live instance using docker / mock data using a mock server to populate dashboards 

## Migration stats
<html>
<body>

AWS ELB Dashboards | Before Migration |   |   |   | After Migration |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
  | Maps | Search | Lens | Visualization | Maps | Search | Lens | Visualization
[Metrics AWS] ELB Overview | 0 | 0 | 0 | 9 | 0 | 0 | 9 | 0
[Logs AWS] ELB Access Log Overview | 1 | 0 | 0 | 8 | 1 | 0 | 8 | 0

</body>
</html>

### Dashboard : [Logs AWS] ELB Access Log Overview
  - [x] Migrate 8 visualization to the lens.
    - https://github.com/elastic/integrations/pull/6521

## Verification and Validation
  - [x] Verification of functionality remains the same after migration in Kibana
  - [x] Verification of data count of after-migrated visualization with before-migrated visualization in Kibana
  - [x] Verification of Dashboards is not distorted in the supported Kibana version 8.7.1

**Comment by zmoog** [comment]
@rajvi-elastic, using `user_agent.original` creates this problem, and I'm not sure we are extracting all the value from these data points. We could combine the other fields (device name, name, os name, and version) in one or more visualizations.

For a piece of advice on the visualizing of such data, I believe @drewdaemon can probably help us. Andrew, I read your reviews on similar dashboards: do you have ideas? 😇

**Comment by drewdaemon** [comment]
Thanks for the ping. We have an open issue describing this: https://github.com/elastic/kibana/issues/100231. It's a more complicated problem than it appears, but we have added it to our next team meeting agenda to discuss a good approach.

I'm assuming there isn't a shorter version of the field in the data you could use instead?

If not, a couple of tactical workarounds come to mind:
- Move that particular visualization to its own row in the layout. Pros—quick, easy, probably fixes the problem. Cons—interrupts your nice grid
- Create add a runtime field to truncate the field name to a specific number of characters. You could do this in a by-value data view for just that visualization. Pros—guarantees a nice layout. Cons—user won't be able to see full data, possibly a small performance hit

Let me know if I can be of further help!

**Comment by rajvi-elastic** [comment]
@drewdaemon, We don't have the shorter version of field that we can use instead of `user_agent.original `. 

### Solution-1
However, as @zmoog suggested we could combine the other fields (name, os name, and version) and use that field instead of `user_agent.original `.

I have combined `user_agent.name`, `user_agent.os.name` and `user_agent.version` and used that in top values.

![image](https://github.com/elastic/integrations/assets/124889398/e1495a35-258a-4bda-ba92-f064408c110f)

Pros: 

1. We won't need to create runtime field!
2. Dashboard layout will remain intact!

Cons:

1. If either of field is missing then count will be incorrect.

### Solution-2

Below is the screenshot of entire dashboard after extending panel.
![screencapture-localhost-5601-app-dashboards-2023-06-02-11_15_19](https://github.com/elastic/integrations/assets/124889398/6eb9c7a7-c5df-4d08-a572-68331e05640b)


Let me know what are your thoughts?

**Comment by drewdaemon** [comment]
Thanks for the screenshots! Sounds like we have three options on the table
- adjusting layout
- use runtime field to truncate terms
- multi-term dimension

I would personally prioritize correct counts over aesthetics (so avoid the multi-term strategy).

But, I'm just here to advise on our current visualization capabilities. This decision belongs to @zmoog .

**Comment by drewdaemon** [comment]
FWIW, I also just noticed that if you go the runtime field route (not advocating for this, just adding an insight), you don't actually have to perform the truncation serverside. Instead, you can just apply a truncation field formatter.

<img width="1136" alt="Screenshot 2023-06-02 at 2 12 51 PM" src="https://github.com/elastic/integrations/assets/315764/4b169f5c-fbe6-498b-bc0c-a002a1fb4659">

**Comment by drewdaemon** [comment]
My colleague pointed out yet one more option: convert the bar chart to a table. Pro—the user can always see the complete user agent string _and_ the layout is preserved. Con—different aesthetic.

**Comment by rajvi-elastic** [comment]
I tried the runtime field solution but it is not showing expected results when the beginning of string is same and field length for truncated string is small (In my case 50):

_**Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)**_ HeadlessChrome/112.0.5615.29 Safari/537.36 Elastic/Synthetics
**_Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)_** Chrome/81.0.4044.129 Safari/537.36

Here, beginning of both the string is same till some length hence it is grouping it in one bar after truncation!

![image](https://github.com/elastic/integrations/assets/124889398/f82aa7c0-a939-46ba-9d07-0dead6db037d)

I think creating table chart would be better option here. What do you think @zmoog?

**Comment by zmoog** [comment]
I tried some experiments truncating the user agent, but the results were usually weird.

I am starting to think that the user agent is such a particular field (a very long string composed of many sub-elements) that a table chart may better serve it.

If there are outliers, you can spot them immediately, with full details at hand.

**Comment by zmoog** [comment]
I'm gravitating towards a +1 on the table chart; @drewdaemon, do you think changing the aesthetic is acceptable in this scenario?

**Comment by drewdaemon** [comment]
I agree that user agent is a really particular field. I don't think it looks bad to have a table in there. I would go with it!

**Comment by rajvi-elastic** [comment]
As Y-axis labels were not getting truncated in lens bar chart, the `ELB Top User Agents` has been represented using the table chart as best alternative.

PR for AWS ELB Access log lens migration: https://github.com/elastic/integrations/pull/6521
