### ISSUE TITLE
[O11y][AWS Cloudtrail] Lens Migration

### ISSUE THREAD

**Issue by milan-elastic** [elastic/integrations#6206]
Manually migrate AWS `CloudTrail` visualizations to the lens in the current Kibana version `8.7.1` itself. 

## Preparation of data for testing
- [x] Use sample_event.json / setup live instance using docker / mock data using a mock server to populate dashboards 

## Migration stats
<html>
<body>
<google-sheets-html-origin>

AWS Cloudtrail Dashboards | Before Migration |   |   |   | After Migration |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
  | Maps | Search | Lens | Visualization | Maps | Search | Lens | Visualization
[Logs AWS] CloudTrail | 1 | 1 | 0 | 6 | 1 | 1 | 6 | 0

</body>
</html>

## Dashboard : [AWS Cloudtrail] Dashboards 
  - [x] Migrate 6 visualizations to the lens.
    - https://github.com/elastic/integrations/pull/6374

## Verification and Validation
  - [x] Verification of functionality remains the same after migration in Kibana
  - [x] Verification of data count of after-migrated visualization with before-migrated visualization in Kibana
  - [x] Verification of Dashboards is not distorted in the supported Kibana version (TBD)

**Comment by lalit-satapathy** [comment]
> Hey @SubhrataK, for the CloudTrail Event Outcome over time [Logs AWS], in the before migrated visualization, we have Show missing values toggle on

Any conclusion and next step on this?

**Comment by harnish-elastic** [comment]
> event.outcome

@lalit-satapathy, Debugging more into this issue, I found that for `event.outcome` field, there are only three possibilities (success, failure, and unknown) based on the official [document](https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-outcome.html#:~:text=make%20logical%20sense.-,Allowed%20Values,-failure). And the visualization breakdown size (five) is more than the possible values. Hence it won't create the other bucket which is the same behavior that the before-migrated visualization has. Therefore we are good with the visualization.
