### ISSUE TITLE
[Kubernetes][event]  illegal_argument_exception when enabling TSDB

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#6208]
Error when enabling TSDB using the toggle:
```
illegal_argument_exception Caused by: illegal_argument_exception: invalid composite mappings for [metrics-kubernetes.event] Root causes: illegal_argument_exception: composable template [metrics-kubernetes.event] template after composition with component templates [metrics-kubernetes.event@package, metrics-kubernetes.event@custom, .fleet_globals-1, .fleet_agent_id_verification-1] is invalid
```

Also when using on the event data_stream level:
```
elasticsearch:
  index_mode: "time_series"
```

Updating the package is failing, because of the event data_stream:
<img width="345" alt="Screenshot 2023-05-10 at 10 45 56" src="https://github.com/elastic/integrations/assets/28299531/504bfb80-03b2-4379-8e3d-a3b8207266e3">

**Comment by constanca-m** [comment]
Cause of this issue seems to be the field of type text. Opened a new one for it: https://github.com/elastic/elasticsearch/issues/96254
