### ISSUE TITLE
[O11y][AWS Metrics] Lens Migration

### ISSUE THREAD

**Issue by milan-elastic** [elastic/integrations#6222]
Manually migrate AWS `Metrics (EC2, SQS, ELB, Lambda)` visualizations to the lens in the current Kibana version `8.7.1` itself. 

## Preparation of data for testing
- [ ] Use sample_event.json / setup live instance using docker / mock data using a mock server to populate dashboards 

## Migration stats
<html>
<body>

AWS Metrics Dashboard  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
Dashboards | 0 | 15 |  | 

</body>
</html>

## Dashboard : [Metrics AWS] Overview
  - [ ] Migrate x visualization to the lens.
    - PR link

## Verification and Validation
  - [ ] Verification of functionality remains the same after migration in Kibana
  - [ ] Verification of data count of after-migrated visualization with before-migrated visualization in Kibana
  - [ ] Verification of Dashboards is not distorted in the supported Kibana version 8.7.1

**Comment by rajvi-elastic** [comment]
@SubhrataK, **[Metrics AWS] Overview** dashboard contains incorrect fields due to which we are not able to migrate those panels. Previously this issue (https://github.com/elastic/integrations/issues/3703) was identified and AWS dashboards were updated but it seems like this dashboard was miss out. First, we will have to update these panels with correct field names and then and only we would be able to migrate this dashboard to lens.

![image](https://github.com/elastic/integrations/assets/124889398/0ebdff6b-b317-49f7-a24c-4b6a782edfd5)

CC: @lalit-satapathy

**Comment by lalit-satapathy** [comment]
> [Metrics AWS] Overview dashboard contains incorrect fields due to which we are not able to migrate those panels. Previously this issue (https://github.com/elastic/integrations/issues/3703) was identified and AWS dashboards

CC @zmoog @kaiyan-sheng for comments

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic You are right! The field name is wrong here. Thanks for catching it! Would you like our team to fix the old dashboard first or this can be done as a part of the migration process?

@kaiyan-sheng, We will fix these fields and raise a separate PR. And we will also add you as a reviewer to review the changes and verify new field names.

**Comment by rajvi-elastic** [comment]
@kaiyan-sheng, In **AWS Metrics Dashboard** most of the panel uses last value function which shows value of last bucket only.

For example, below chart represents **Total # of HTTP 4xx Errors** over time.
**Total errors for entire time range** = 9
 **Total errors in last bucket** = 1 
![image](https://github.com/elastic/integrations/assets/124889398/e51d3621-e031-4539-a2c6-c0ca1255b36e)

The current TSVB visualization shows **Total errors in last bucket** for `S3 Total Error 4xx` panel.
![image](https://github.com/elastic/integrations/assets/124889398/db5d5360-f364-4c41-9417-20a4709afcef)

Migrated lens visualization shows **Total errors for entire time range** for `S3 Total Error 4xx` panel.
![image](https://github.com/elastic/integrations/assets/124889398/e4ef0d77-9ae8-4550-8722-290dd775a4e6)
 
What is the actual use case of AWS metrics panels? Does it represents the value of last bucket only or value of the entire timerange?

Below panels that falls under red square use last bucket function:
![screencapture-localhost-5601-app-dashboards-2023-06-01-12_12_13](https://github.com/elastic/integrations/assets/124889398/69ea8152-4c7f-4508-a4b9-3600b3467e90)

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic Good catch, it should be the value of the entire time range I believe!

@kaiyan-sheng Thanks for confirming. We will use entire timerange in migrated panels instead of last value.

**Comment by kaiyan-sheng** [comment]
@rajvi-elastic Sorry I just looked a bit more into this. Since we are using `average` [statistic](https://github.com/elastic/integrations/blob/main/packages/aws/data_stream/s3_request/agent/stream/stream.yml.hbs#L47) for 4xxErrors and 5xxErrors, it's actually representing the error rate. But instead of showing the rate, it's showing 0s or 1s? 

If it's indeed representing the error rate, then it should not be summed by the entire time range, it should be only showing the last value.

**Comment by rajvi-elastic** [comment]
@kaiyan-sheng, It won't show only 0's or 1's but it will show value of last bucket. If there are 3 **4xx** errors then it will display 3.

And you are right, it's representing error rate and hence we will keep the functionality same (last value).

**Comment by kaiyan-sheng** [comment]
@rajvi-elastic I would present an average error rate here across all s3 buckets. If `auto` is not supported it, I'd prefer calculating the average for all 4xx error data points across the global time range. Do you know if `auto` will be added later into Lens?

**Comment by rajvi-elastic** [comment]
@kaiyan-sheng, As per the discussion that we had with Kibana team, they might not provide support for `auto` in lens. (https://github.com/elastic/kibana/issues/153326)

**Comment by rajvi-elastic** [comment]
As per the discussion with @kaiyan-sheng, aggregations for below panels have been modified:
<html>
<body>

Visualization | Field | Aggregation [Before]  | Aggregation [After]
-- | -- | -- | --
Total # of HTTP 4xx Errors | aws.s3_request.errors.4xx | Sum | Average
Total # of HTTP 5xx Errors | aws.s3_request.errors.5xx | Sum | Average
SQS Empty Receives Top5 | aws.sqs.empty_receives | Average | Last Value
SQS Messages Delayed Top5 | aws.sqs.messages.delayed | Average | Last Value
Cloudwatch ELB Request Count Top5 | aws.elb.metrics.RequestCount.sum | Sum | Sum
Cloudwatch ELB Unhealthy Host Count | aws.elb.metrics.UnHealthyHostCount.max | Sum | Last Value
Cloudwatch Lambda Errors Top5 | aws.lambda.metrics.Errors.avg | Average | Average
Cloudwatch Lambda Invocations Top5 | aws.lambda.metrics.Invocations.avg | Average | Average
Cloudwatch Lambda Throttles Top5 | aws.lambda.metrics.Throttles.avg | Average | Average

</body>
</html>

CC: @SubhrataK
