### ISSUE TITLE
[Kubernetes] Visualizations with adhoc dataviews do not work for cross cluster search

### ISSUE THREAD

**Issue by MichaelKatsoulis** [elastic/integrations#6240]
Visualizations that make use of adhoc data views in order to create runtime fields cannot work always.
In cases like when CCS is used there are different metrics index patterns created that include data from multiple elasticsearch clusters.

As seen in an [example](https://github.com/elastic/integrations/blob/dc0584634af8f3443a4fb0a5920e235b3be8e961/packages/kubernetes/kibana/dashboard/kubernetes-f4dc26db-1b53-4ea2-a78b-1bfab8ea267c.json#L106) where adhoc data view is used to list Pods per phase(last value of their phase only) there is a [title](https://github.com/elastic/integrations/blob/dc0584634af8f3443a4fb0a5920e235b3be8e961/packages/kubernetes/kibana/dashboard/kubernetes-f4dc26db-1b53-4ea2-a78b-1bfab8ea267c.json#L1193) attribute  where an index-pattern is specified.

So the adhoc dataview relies on an index pattern rather than on a another data stream:
<img width="655" alt="dataview-index-pattern" src="https://github.com/elastic/integrations/assets/26270880/2a15fa1c-d491-4497-a39a-9e9787c511f2">
So if someone wants to update their metrics-* data view to match more index-patterns (defaults to metrics-*) and then use that as their dashboards source, the viz that use the adhoc data view will not show all the data. The reason is that the index-pattern is hardcoded in the dashboard's json itself.

Possible solutions could be :
1. Not use adhoc data views for runtime fields, rather put them in the main metrics-* data view
2. Update the adhoc data view index pattern to `*metrics*` to include other metrics sources
3. Make it possible for a dataview to be based on other data view. This means to expand the supported types of [title](https://www.elastic.co/guide/en/kibana/master/data-views-api-create.html#data-views-api-properties) to also include dataviews. (could end up to a chicken egg problem)

cc @mlunadia , @neiljbrookes

**Comment by MichaelKatsoulis** [comment]
I would like hear from @elastic/kibana-visualizations if they have any suggestion on this matter.

**Comment by stratoula** [comment]
I personally find 1 and 2 ok, about the 3rd one is not supported atm. I am pinging the @elastic/kibana-data-discovery which actually owns dataviews in general

**Comment by davismcphee** [comment]
++ to what @stratoula commented about using 1 or 2 as the solution. This is more in @mattkime's area of expertise than mine, but I can't imagine we'd want to modify the data view class as suggested in 3. And even if we did, I'm not sure there'd be a benefit then to using ad hoc data views over a persisted `metrics-*` data view.
