### ISSUE TITLE
Create MS SQL package

### ISSUE THREAD

**Issue by masci** [elastic/integrations#626]
# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [x] Supported versions of the monitoring target are documented
- [x] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to:

**Comment by weltenwort** [comment]
related: elastic/integrations#2009

**Comment by jamiehynds** [comment]
MSSQL Audit Event integration is now available - https://github.com/elastic/integrations/tree/master/packages/microsoft_sqlserver/docs

**Comment by mholttech** [comment]
Great to see Audit Event Integration but is there any work being done for SQL Performance Monitoring?

**Comment by jamiehynds** [comment]
@akshay-saraswat can you confirm if SQL Performance Monitoring is on your radar?

**Comment by akshay-saraswat** [comment]
@jamiehynds yes, it's listed in [this meta issue](https://github.com/elastic/integrations/issues/2337). As soon as we have engineering bandwidth available to be invested into Integrations migration, we will work on it.

**Comment by mholttech** [comment]
Any update on when SQL Performance Monitoring will be released? We've been asking this question of our customer success team since Fleet was originally released. We're a heavy MSSQL Shop and this is Critical for moving forward with adopting Elastic for monitoring our MSSQL Clusters.

**Comment by akshay-saraswat** [comment]
@mholttech we are actively developing it and will publish it soon if everything goes as planned.

**Comment by willemdh** [comment]
:+1

**Comment by lalit-satapathy** [comment]
This old issue can be closed. Recent data streams made GA - https://github.com/elastic/integrations/issues/6056
