### ISSUE TITLE
[IIS] TSDB Enablement

### ISSUE THREAD

**Issue by ritalwar** [elastic/integrations#6267]
## Test Environment Setup
- [x] Creation of IIS Test Environment

## Datastream : application_pool 
  - [x] Add dimension fields
         https://github.com/elastic/integrations/pull/6460
  - [x] Adding metric_type mapping - Already exists
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if dimension field mapping is correct in the data stream template.

## Datastream : webserver
  - [x] Add dimension fields 
         https://github.com/elastic/integrations/pull/6461
  - [x] Adding metric_type mapping - Already exists.
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.
 
## Datastream : website
  - [x] Add dimension fields 
          https://github.com/elastic/integrations/pull/6462
  - [x] Adding metric_type mapping - Already exists
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.

Enable TSDB by default: https://github.com/elastic/integrations/pull/6694

**Comment by ritalwar** [comment]
Testing took longer than expected due to issues with the available VMs. Troubleshooting the problems with the VMs consumed a significant amount of time, but unfortunately did not resolve the issues. 

As a workaround, I created a new VM specifically for testing the IIS integration. I have also created an [issue](https://github.com/elastic/integrations/issues/6453) to propose enhancements to the IIS integration, which would also make testing easier by eliminating the need for complex environment setup and reducing the time required to run IIS services. 

I have successfully tested all metrics datastreams on the new VM.

**Comment by lalit-satapathy** [comment]
Hi @ritalwar,

Can we link to the TSDB-mode dashboard images here for future reference?

**Comment by ritalwar** [comment]
Screenshots
## Screenshots
![image](https://github.com/elastic/integrations/assets/102972658/f8514625-cecf-4160-bac5-9c47ab47745a)
![image](https://github.com/elastic/integrations/assets/102972658/cdff1fed-e0e6-48e8-b2b1-6bffb3643d76)
![image](https://github.com/elastic/integrations/assets/102972658/ce3b6733-7c5b-472c-8c49-6c42a8aecc15)
![image](https://github.com/elastic/integrations/assets/102972658/ac83ba9a-b14f-4bbd-8da3-d026fac05dcc)
