### ISSUE TITLE
[Redis Enterprise] TSDB Enablement

### ISSUE THREAD

**Issue by ritalwar** [elastic/integrations#6268]
## Test Environment Setup
- [x] Creation of Redis Enterprise Test Environment

## Datastream : node 
  - [x] Add dimension fields
         https://github.com/elastic/integrations/pull/8091
  - [x] Adding metric_type mapping
          https://github.com/elastic/integrations/pull/8133
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if dimension field mapping is correct in the data stream template.

## Datastream : proxy
  - [x] Add dimension fields 
         https://github.com/elastic/integrations/pull/8148
  - [x] Adding metric_type mapping
         https://github.com/elastic/integrations/pull/8539
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.

Tsdb Enablement PR: https://github.com/elastic/integrations/pull/8584

**Comment by ritalwar** [comment]
Since this package is in beta, its priority is considered low. 
Therefore postponing its progress for now and migrating other packages with higher priority first.

**Comment by lalit-satapathy** [comment]
Hi @ritalwar, 

These are prometheus based metrics and summarising below the current approach

- **Metric type mapping:**

   [In this case](https://github.com/elastic/integrations/blob/48b1b082181a18ae051f89e42b04b70fc955a8a5/packages/redisenterprise/data_stream/node/fields/fields.yml#L10), we have a single dynamic mapping for all the `node.metrics.*` fields. How do we cover different metric types from this? Assuming there can be both a mix of _gauges_ and _counters_ inside the data stream? Sample [example](https://github.com/elastic/integrations/blob/main/packages/redisenterprise/data_stream/node/sample_event.json#L50). May be no counters in node data stream now, but what if it gets added in future?

- **Dimension/Label mapping:**

   We are mapping [each of the labels](https://github.com/elastic/integrations/blob/6f397ff47fdf35172e7f759b8d508ed8aefb1910/packages/redisenterprise/data_stream/node/fields/fields.yml#L9) individually as dimension. There are seems to be couple of solutions currently:  

  - Map individual labels to dimensions explicitly (done here)
  - Use fingerprint processor

   What is the long term approach here?
   
   CC: @tommyers-elastic @felixbarny
