### ISSUE TITLE
[docs] Broken `prometheus_input` docs

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/integrations#6324]
[Placeholders (`fields`, `event`, `url`)](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md) should never be used outside an integration's `_dev/build/docs/` directory. (I think) the values only get replaced when you [build the package](https://github.com/elastic/integrations/blob/main/docs/developer_workflow_design_build_test_integration.md#build).

The [`prometheus_input`](https://github.com/elastic/integrations/tree/main/packages/prometheus_input) integration (https://github.com/elastic/integrations/pull/6170) uses the `url` placeholder in [`docs/README.md`](https://github.com/elastic/integrations/blob/main/packages/prometheus_input/docs/README.md?plain=1#L19-L20) so the placeholder value is not being replaced. It looks like there is no `_dev/build/docs/` directory at all for this integration.

This unresolved `url` placeholder is breaking the docs build. No integration docs updates will be published until this is resolved here and the changes are available on EPR.

For more details on using placeholders, see the [Documentation guidelines](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md).

cc @jamiehynds @bmorelli25 @ishleenk17

**Comment by ishleenk17** [comment]
I am looking into it. Thanks for pointing it out.
