### ISSUE TITLE
[ITF] Enable config persistence in the Integrations Test Framework (ITF)

### ISSUE THREAD

**Issue by ishleenk17** [elastic/integrations#6354]
As a part of[ ITF (Integrations Test Framework)](https://github.com/elastic/integrations/issues/5338), we had a requirement of config persistence as stated below

While working with integrations, we need a way we can test with any type of customized config for any integration and a way to persist these configs for any future use. 
This ticket focuses on providing a way to persist these configs.

Eg: MSSQL service integration needs to be tested with 2 different configurations:

Config1: Bring up MSSQL DB and pre-populate user database udb1
Config2: Bring up MSSQL DB and pre-populate user database udb2

Relates: https://github.com/elastic/integrations/issues/5338

**Comment by ishleenk17** [comment]
### Proposed Solution
ITF uses the dockerfiles present under _dev/deploy/docker for each integrations to deploy the services.
The dockerfiles under this brings up the service with default config. 

We can enable the handling of different configs for these integrations by making changes to these dockerfiles and pushing them to the oblt-cluster which would restart the service. But if we do changes to the existing dockerifiles, persistency will not be maintained.

We can follow the below structure for handling different configs: 
<img width="515" alt="Screenshot 2023-05-29 at 2 53 35 PM" src="https://github.com/elastic/integrations/assets/102962586/4536900e-3f80-403b-a39b-a3b6bdec725b">



### How to use these configs

`oblt-cli package cluster service update <clustername> <servicename> -config=<foldername under test_configs> `
     Eg: config=config_1, config=config_2
If you want the default docker_compose (under deploy) to be picked up, config=default.
If you don’t specify any config, default config will be considered while bringing up the container.

**Comment by lalit-satapathy** [comment]
Can we have a draft PR (as reference) where integration has multiple test configs?

**Comment by ishleenk17** [comment]
There is a better solution which we can have for this: 
We can add another service under the docker-compose file and bring up just a particular service container.
The example can be seen in the dummy PR which will be linked to this issue. 

I have taken example of salesforce. Currently we bring up 1 container with a particular config. This is used for system test as well. 
During an SDH we wanted to have it tested with another config (bulk response salesforce).
We will add [profiles] to service containers which we don't want to be executed in system test

**Comment by ishleenk17** [comment]
> Can we have a draft PR (as reference) where integration has multiple test configs?

@lalit-satapathy : I have shared a dummy PR of how we can manage the configs, while taking an actual example of salesforce which we handled currently.
