### ISSUE TITLE
File Integrity Integration - Can't save .SLDASM file from Solidworks to a monitored path

### ISSUE THREAD

**Issue by GuyPodolsky** [elastic/integrations#6371]
### Info:
Elastic Agent Version: 8.7.1
Integration Version: 1.6.0
OS: Windows Server 2019

### The Issue:
When trying to save a  .SLDASM file from Solidworks to a monitored path by the policy with SHA1 hashing
it creates an error event log in the file monitoring logs and causes the saving process of the file to fail.

### Notes: 
- Doesn't happen when I copy the final file to the monitored directory.
- Doesn't happen when I create a text file with the same file extension.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#0563C1" vlink="#954F72">

@timestamp | @version | _id | _index | _score | agent.ephemeral_id | agent.id | agent.name | agent.type | agent.version | data_stream.dataset | data_stream.namespace | data_stream.type | ecs.version | elastic_agent.id | elastic_agent.snapshot | elastic_agent.version | error.message | event.action | event.agent_id_status | event.category | event.dataset | event.ingested | event.kind | event.module | event.type | file.ctime | file.drive_letter | file.extension | file.inode | file.mtime | file.owner | file.path | file.path.text | file.size | file.type | file.uid | host.architecture | host.hostname | host.id | host.ip | host.mac | host.name | host.os.build | host.os.family | host.os.kernel | host.os.name | host.os.name.text | host.os.platform | host.os.type | host.os.version | service.type | tags
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
May 29, 2023 @ 11:59:53.441 | 1 | Dqa8ZogBARPLMBrkRW9S | .ds-logs-fim.event-default-2023.05.22-000001 | - | 82a7b97a-7fd3-46f2-80b5-76cd2284b443 | ba927f19-7f30-4902-8467-e50465c875a2 | XXXFilesrv | auditbeat | 8.7.1 | fim.event | default | logs | 8.7.0 | ba927f19-7f30-4902-8467-e50465c875a2 | FALSE | 8.7.1 | failed to open file for hashing: Error creating file 'D:\XXXX.SLDASM':   The process cannot access the file because it is being used by another   process. | attributes_modified | auth_metadata_missing | file | fim.event | May 29, 2023 @ 11:59:54.000 | event | file_integrity | change | May 29, 2023 @ 11:32:39.939 | D | SLDASM | 8.44425E+14 | May 29, 2023 @ 11:59:53.439 | XXX | D:\XXX.SLDASM | D:\XXXXX.SLDASM | 2,720,457 | file | XXXXX | x86_64 | XXXFilesrv | XXXX | xxx.xxx.xxx | XXXX | XXXFilesrv | 17763.1577 | windows | 10.0.17763.1577 (WinBuild.160101.0800) | Windows Server 2019 Standard | Windows Server 2019 Standard | windows | windows | 10 | file_integrity | fim-event, beats_input_raw_event

</body>

</html>

### A possible reason:
Solidworks first creates a temporary file from which it creates the final file.
The integration tries to hash the temporary file and it causes the file to be locked for the Solidworks

### Steps to reproduce:
1. Deploy Elastic Agent version 8.7.1 (Might happen on other versions too) on Windows Server 2019 (Might happen on other versions too)
2. Add to the Agent's policy the File Integrity integration version 1.6.0 (Might happen on other versions too) 
3. Configure the integration to monitor a directory with SHA1 hashing (Might happen with other Hashes too)
4. Try to save from Solidworks a .SLDASM file to the monitored directory (Might happen with other file extensions of Solidworks too)

**Comment by andrewkroh** [comment]
I think what probably happens is

1. File is created.
2. FIM opens it to hash the contents.
3. App tries to [move](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefileexa?redirectedfrom=MSDN) the file while it is being read and gets an ERROR_SHARING_VIOLATION.

FIM takes the most liberal approach it can on Windows when opening the file. It allows all [share modes](https://github.com/elastic/beats/blob/8ff6894cab0591cc3a898d7abd6a9103e535efdd/libbeat/common/file/file_windows.go#L103) meaning another app can read/write/delete the file when FIM is reading it. But the move operation is not something that can be "allowed" so the move call fails if FIM is still reading it.

The only way I can think of to prevent this would be to use the `exclude_files` config option to ignore the naming convention used for the Solidworks temporary files.

**Comment by GuyPodolsky** [comment]
@andrewkroh , Thank you for your comment.
Your explanation makes much more sense than mine.

The workaround might work, but it's not ideal, since we do want to monitor and hash those files
Is there will be any fix for it (if it's even possible)?

**Comment by andrewkroh** [comment]
I think the first step is to confirm what is happening. I think that if you ran [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) and captured a .PML file, then you would be able to see what operation fails within Solidworks.

- Is is a move operation that is failing?
- What is the source file name?
- What is the destination file name?

If Solidworks names the temporary files differently than the final file then Agent could ignore only the temp side and it would still hash the final files.
