### ISSUE TITLE
[AWS] [EMR Metrics] Dashboard

### ISSUE THREAD

**Issue by gpop63** [elastic/integrations#6438]
## Summary

The current monitoring capabilities for AWS EMR metrics lack a dedicated dashboard to visualize EMR metrics data stream. Create a concise and user-friendly EMR metrics dashboard for Kibana. This will provide customers with valuable insights to optimize their EMR clusters.

## Tasks/Steps

- Identify Relevant Metrics
  - Determine the most meaningful and valuable metrics for customers. This will involve understanding the specific needs and pain points of EMR users.
- Dashboard Creation
  - Develop a concise and intuitive dashboard using Kibana to display the identified metrics. The dashboard should be visually appealing and easy to navigate, allowing customers to quickly gain insights into the performance of their EMR clusters.

## Docs
- https://docs.aws.amazon.com/emr/latest/ManagementGuide/UsingEMR_ViewingMetrics.html

**Comment by lalit-satapathy** [comment]
Marked done in project.
