### ISSUE TITLE
Amol & Diksha need write access for Integration GitHub Repo

### ISSUE THREAD

**Issue by manishgupta-qasource** [elastic/integrations#644]
As per Discussion in today's call with @EricDavisX 

Below 2 members of Castor team need Write access for Integration GitHub Repo to add labels and other details
1. amolnater-qasource
2. dikshachauhan-qasource

Please let me know if any other details are required

CC @MindyRS

**Comment by EricDavisX** [comment]
I have added @amolnater-qasource and @dikshachauhan-qasource as 'triage' level contributors.  @andresrc If we need to update it further let me know. 

Diksha and Amol, if you have need for more access let me know and we'll look into it.  I'm not 100% certain what this role entails.  : /

**Comment by andresrc** [comment]
Thanks @EricDavisX , `triage` should be enough to manage issues and pull requests (adding labels, etc.), if not please let know and we'll move to `write`.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX cc @andresrc

Thanks for providing the required access to Integration repo. We are now able to add label and assignee to tickets.

Hence, closing this out.

Thanks
QAS
