### ISSUE TITLE
ActiveMQ TSDB Enablement

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#6473]
## Test Environment Setup
- [x] Creation of Test Environment

## Datastream : `broker` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/6484
  - [x] Add metric type mapping - https://github.com/elastic/integrations/pull/6532

## Datastream : `queue` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/6491
  - [x] Add metric type mapping - https://github.com/elastic/integrations/pull/6532

## Datastream : `topic` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/6498
  - [x] Add metric type mapping -https://github.com/elastic/integrations/pull/6532

Enable TSDB by default 
 - 
    
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Perform Enable-Disable-Enable testing using Package update, API call, Package Update

**Comment by lalit-satapathy** [comment]
Can we link the TSDB enable PR - https://github.com/elastic/integrations/pull/6689 in the meta tasks?
