### ISSUE TITLE
[ti_misp] Incorrect cursor timestamp because response not sorted

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#6477]
The timestamp stored in the cursor is not correct because it assumes the [last event](https://github.com/elastic/integrations/blob/9c9f1f346f53f042f4a48c9835027006909ec120/packages/ti_misp/data_stream/threat/agent/stream/httpjson.yml.hbs#L63) is the latest event. But the events in the response from MISP are not sorted by time so that last event is not necessarily the most recent event.

The [/events/restSearch API](https://www.misp-project.org/openapi/#tag/Events/operation/restSearchEvents) does not offer a sort parameter.

**Request tracer logs from v1.14.1**: [ti_misp.threat.ndjson.log.gz](https://github.com/elastic/integrations/files/11654021/ti_misp.threat.ndjson.log.gz)

Version: MISP 2.4.124 (ran from https://github.com/MISP/docker-misp#how-to-run-it-in-3-steps)

**Comment by andrewkroh** [comment]
I don't know that this one can be solved by using HTTPJSON because there isn't a way to select and sort the timestamps AFAIK. Perhaps this can be changed over to [CEL](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-cel.html) and which should be capable of this.

**Comment by efd6** [comment]
Yes, CEL can do this. We can use the `.min()` and `.max()` on timestamps (the mito README shows how to do this). For anything more complex than this, we would need a sort function, which we don't have, but from the HTTPJSON config, `.max()` looks like it will do what we want.

**Comment by efd6** [comment]
I'm wondering if it's not possible to do in HTTPJSON with
```
cursor:
  timestamp:
    value: '[[if gt .last_event.Event.timestamp.Unix .cursor.timestamp.Unix]][[.last_event.Event.timestamp]][[else]][[.cursor.timestamp]][[end]]'
```

**Comment by andrewkroh** [comment]
The more I look at data from MISP, I think the Event.timestamp value is sorted. So maybe this isn't actually a problem after all.

Based on the data I captured with the tracer (attached above), this test indicates it is sorted.

`jq -c -r '.["http.response.body.content"]' ti_misp.threat.ndjson | grep -v ^null | jq -r '.response[].Event.timestamp' | sort -c`

I was confused, because I thought the timestamp being reference in the cursor was the result of the "split" operation and could be from the `.Event.Attribute[].timestamp` value which does not appear to be sorted and is often less than the overall `.Event.timestamp`.
