### ISSUE TITLE
[AWS] VPC flow log integration missing config parameters and field definitions

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#6481]
By looking at the VPC flow integration, we are missing `bucket_arn` and `number_of_workers` in the configuration list:
<img width="695" alt="Screenshot 2023-06-05 at 5 43 24 PM" src="https://github.com/elastic/integrations/assets/14081635/b648dccd-4e8a-4712-abfb-fdd40b820176">

Also when choosing to collect VPC flow logs from S3, s3 bucket information should also be stored into each document. These fields are collected in [Filebeat](https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/s3_objects.go#L343-L353) but not registered in the integration.

**Comment by tdancheva** [comment]
So these are all the integrations that miss this option. I have marked in red the one that does implement the logic for both SQS/S3 and S3. @kaiyan-sheng, can you just confirm please if I should go ahead and implement a similar one everywhere that it is missing? 

![SQS_S3](https://github.com/elastic/integrations/assets/122360116/b9f1a8c8-0adb-47ba-b3c2-1a897e8231e5)

**Comment by kaiyan-sheng** [comment]
@tdancheva Yes thank you!! 

For the missing field like `aws.s3.bucket.name`, we can add them in a separate PR so it's easier to review. Thanks!!

**Comment by tdancheva** [comment]
I am on it, thinking also about bumping the aws package spec to 2.6.0 and using a select component, we are on 1.0.0

**Comment by tdancheva** [comment]
Here is how it would look otherwise, for ex. for CloudTrail, without the select, with a toggle switch. 
![Add-integration-AWS-CloudTrail-Integrations-Elastic](https://github.com/elastic/integrations/assets/122360116/a9604368-e7a1-474e-97ac-2ccdb88e7818)

**Comment by tdancheva** [comment]
I am adding them one by one:

- First to remove the blocker on vpcflow logs, https://github.com/elastic/integrations/pull/6916 and https://github.com/elastic/integrations/pull/6936
- Cloudtrail https://github.com/elastic/integrations/pull/6915
