### ISSUE TITLE
[symantec_endpoint] Timezone issues when ingesting message with "Event time:"

### ISSUE THREAD

**Issue by rkerr** [elastic/integrations#6499]
When ingesting logs from symantec endpoint there appear to be issues with the handling of timestamps in some messages that result in events with an incorrect timestamp. Symantec appears to use local time for all logs, but the integration appears to treat some of the timestamps as UTC and others as local. For messages with a single timestamp at the beginning the integration will correctly determine the timezone and ingest with the correct timestamp, eg:

Jun  7 09:15:54 SERVER SymantecServer: Site: Site SERVER,Server Name: SERVER,Domain Name: Default,The management server received the client log successfully,DESKTOP,USER,DOMAIN

But for messages with a separate "Event time" it appears this is treated as GMT and used to overwrite the timestamp, eg:

Jun  7 09:16:10 SERVER SymantecServer: DESKTOP,Category: 0,Smc,Event Description: Received a new policy with serial number AB13-05/30/2023 23:01:52 031 from Symantec Endpoint Protection Manager.,Event time: 2023-06-07 09:09:54,Group Name: My Group

Which results in the timezone effectively being added twice to the timestamp, once by symantec and once by elastic.

Looking at the integration pipelines I suspect this may also happen for some other timestamps - eg begin and end times in firewall logs.

**Comment by andrewkroh** [comment]
> Symantec appears to use local time for all logs

That wasn't clear from the documentation in https://knowledge.broadcom.com/external/article?legacyId=TECH171741 so I think we assumed UTC for the times that were not part of the syslog header or log export header. I have opened https://github.com/elastic/integrations/pull/6509 to change that. Please take a look.

What version of Symantec Endpoint are you running?

**Comment by andrewkroh** [comment]
> Jun 7 09:16:10 SERVER SymantecServer: DESKTOP,Category: 0,Smc,Event Description: Received a new policy with serial number AB13-05/30/2023 23:01:52 031 from Symantec Endpoint Protection Manager.,Event time: 2023-06-07 09:09:54,Group Name: My Group

@rkerr  Can you tell me a bit more about this log. I want to create a test case for it, but need to know a bit more about its provenance. 

- SEP version.
- Was it exported over syslog or to a log [file](https://techdocs.broadcom.com/us/en/symantec-security-software/endpoint-security-and-management/endpoint-protection/all/Monitoring-Reporting-and-Enforcing-Compliance/viewing-logs-v7522439-d37e464/exporting-log-data-to-a-text-file-v8440135-d15e1197.html)?
- If it was via syslog, did it go direct to the Elastic Agent? I'm curious if it originally had the normal syslog priority (e.g. `<51>`).
- Do you know what [type](https://knowledge.broadcom.com/external/article?legacyId=tech171741) of log this would be classified as (e.g. Agent System Log)?

**Comment by rkerr** [comment]
This is from SEP 14.3RU7. The logs were exported over syslog from the management server direct to the elastic agent - the priority was `<54> - LPR.INFO`

I'm not entirely sure the types listed in the broadcom document map to anything visible in SEP itself. This message appears in the "Client Management Logs" section of the SEP client - judging by the fields present in the message and the log types available in the list I'd assume it is an Agent System Log, but I can't promise that is the case.

One other thing here - I suspect the Agent logs are just collected directly from the client and passed on unaltered. That likely means they are actually using the local time of the client and not the local time of the server. In the majority of cases this will probably be the same thing, but I guess in the worse case there may be a single server handling clients in multiple timezones. Not sure there's really any solution for that without elastic somehow knowing the timezone of every client, but it might at least be worth documenting.
