### ISSUE TITLE
[Okta] Ingest Pipeline Failing on Some Documents

### ISSUE THREAD

**Issue by SpencerLN** [elastic/integrations#6506]
While reviewing ingest pipeline performance metrics, I noticed that ~25% of our Okta documents are failing to run the ingest pipeline fully. It seems that when the pipeline fails, this isn't logged anywhere.

![image](https://github.com/elastic/integrations/assets/6659148/706d1393-2f5a-4b71-8d8c-c07ba64dcd67)

```
{
  "root_cause": [
    {
      "type": "concurrent_modification_exception",
      "reason": "concurrent_modification_exception: null"
    }
  ],
  "type": "script_exception",
  "reason": "runtime error",
  "script_stack": [
    "java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)",
    "java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1638)",
    "java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1636)",
    "for (def e: de.entrySet()) {\n        ",
    "              ^---- HERE"
  ],
  "script": "def arr = ctx.okta?.target; ...",
  "lang": "painless",
  "position": {
    "offset": 342,
    "start": 328,
    "end": 365
  },
  "caused_by": {
    "type": "concurrent_modification_exception",
    "reason": "concurrent_modification_exception: null"
  }
}
```

the `error.message` field on the documents is empty instead of containing an error indicating that there is a problem:
![image](https://github.com/elastic/integrations/assets/6659148/4062ce15-5ca1-4bd5-a9b5-0edee7ae3c26)

Sample event where this occurs: 
```

```

**Comment by andrewkroh** [comment]
https://github.com/elastic/integrations/blob/0fed43548edc02c2d54d43851065d76843ab47d5/packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml#L567-L571

That's definitely a recipe for concurrent modification exceptions.

**Comment by andrewkroh** [comment]
@joegallo It seems like this `concurrent_modification_exception` should have generated a non-empty `_ingest.on_failure_message` that the pipeline could use? Is this expected? Thanks.

**Comment by joegallo** [comment]
> @joegallo It seems like this concurrent_modification_exception should have generated a non-empty _ingest.on_failure_message that the pipeline could use. Is this expected? Thanks.

> `"concurrent_modification_exception: null"`

The exception in question doesn't have a message -- it's just an exception (hence the null). I'd say it's expected, albeit unfortunate. +1 to your addition of more debugging information in the `on_failure` over on https://github.com/elastic/integrations/pull/6507.
