### ISSUE TITLE
[iptables] journald input system tests failing

### ISSUE THREAD

**Issue by ebeahan** [elastic/integrations#6547]
`iptables.log` system integration tests failing to find expected data against stack 8.8 (and all stack versions since 8.1 from testing):

```
2023/06/12 15:48:10 DEBUG checking for expected data in data stream...
2023/06/12 15:48:10 DEBUG found 0 hits in logs-iptables.log-ep data stream: index_not_found_exception: no such index [logs-iptables.log-ep] Status=404
2023/06/12 15:48:11 DEBUG found 0 hits in logs-iptables.log-ep data stream: index_not_found_exception: no such index [logs-iptables.log-ep] Status=404
2023/06/12 15:48:12 DEBUG found 0 hits in logs-iptables.log-ep data stream: index_not_found_exception: no such index [logs-iptables.log-ep] Status=404
2023/06/12 15:48:13 DEBUG found 0 hits in logs-iptables.log-ep data stream: index_not_found_exception: no such index [logs-iptables.log-ep] Status=404
```

Suspect whatever underlying problem here also impacts the `journald` integration package. Past discussion of similar issue #2602 that was resolved by a workaround in #5984.

**Comment by andrewkroh** [comment]
I recommend checking the logs of Filebeat to see if there are any errors or panics. (although elastic-package's new error checks should be picking up that sort of issue).

The workaround mentioned was applied to both iptables and the journald input package.

**Comment by andrewkroh** [comment]
The journal is generated on the latest `debian:stable-slim` container image,  meanwhile it is being read from an container based on `ubuntu:20.04`. So the jouranld versions are different. The debian version is probably newer and the file format may not be backward compatible.

We could probably move the generation to `ubuntu:20.04` and it would fix the test.
