### ISSUE TITLE
[docs] Broken image in `aws` docs

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/integrations#6559]
In https://github.com/elastic/integrations/pull/6231, an image was added to the [`aws` `README.md` file](https://github.com/elastic/integrations/blob/main/packages/aws/_dev/build/docs/README.md?plain=1#L209) using invalid Markdown. The syntax should be updated to:

```diff 
- ![alt text](../img/metricbeat-aws-cloudwatch-latency.png "CloudWatch Last Data Point Timestamp")
+ ![CloudWatch Last Data Point Timestamp](../img/metricbeat-aws-cloudwatch-latency.png) 
```

This error is breaking the docs build. No integration docs updates will be published until this is resolved here and the changes are available on EPR.

cc @kaiyan-sheng @zmoog @bmorelli25

**Comment by kaiyan-sheng** [comment]
oh no sorry my bad! I will create a PR to fix it right away!

**Comment by kaiyan-sheng** [comment]
PR for fixing the link is merged. Sorry for breaking the doc!!

**Comment by bmorelli25** [comment]
Thank you so much!
