### ISSUE TITLE
Airflow integration is not generating events

### ISSUE THREAD

**Issue by HansHatElastic** [elastic/integrations#6595]
Summary
Customer is interested in the Airflow integration, installed the beta, but it not getting any events. There are no errors either in Metricbeat,Logstash or Elasticsearch

Architecture and versions
Elastic Cloud , release 8.5.3
Logstash and Metricbeat 8,7.1 deployed on AKS. Metricbeat sends events to Logstash, and Logstash to Elastic

**Comment by SubhrataK** [comment]
@HansHatElastic Request you to kindly involve @elastic/support for an initial analysis/debugging of the issue.

**Comment by jakommo** [comment]
Just a friendly reminder that @\elastic/support is a wide handle with > 200 members, that are all subscribed to this issue now :sweat_smile:

**Comment by lucabelluccini** [comment]
I've reached out @HansHatElastic to guide the customer to open a support ticket this morning - with few info which can help our investigation.

**Comment by PritamToshniwal** [comment]
@lucabelluccini Hello, 01392525,  I have a customer whose env is exactly the same, [Deployment](https://admin.found.no/deployments/6f5dc64c6a3a4963bd295960f3e34916) ( I believe it's the same customer )
