### ISSUE TITLE
Convert Windows's edge processing to Ingest Node pipeline

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#663]
# Convert edge processing to Ingest Node pipeline

This package uses Beats processors for some of its data processing. We want to
move that processing into the ingest node pipeline that is part of the package
to make reuse easier (e.g. data from Kafka could be routed through the pipeline).

### Data Streams
- sysmon (inputs: winlog)
  - [ ] All beats processors are removed
  - [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- forwarded (inputs: winlog)
  - [ ] All beats processors are removed
  - [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added

**Comment by andrewkroh** [comment]
Sysmon's DNS event processing depends on  https://github.com/elastic/elasticsearch/issues/57476.

**Comment by jamiehynds** [comment]
@leehinman are we ok to close this one?

**Comment by leehinman** [comment]
Yep, following were converted:

- system/security
- system/system
- system/application
- windows/sysmon_operation
- windows/powershell_operational
- windows/powershell
- windows/forwarded
