### ISSUE TITLE
Hadoop TSDB Enablement

### ISSUE THREAD

**Issue by ritalwar** [elastic/integrations#6707]
## Test Environment Setup
- [x] Creation of Hadoop Test Environment

## Datastream : Cluster 
  - [x] Add dimension fields
         https://github.com/elastic/integrations/pull/7631
  - [x] Adding metric_type mapping
         https://github.com/elastic/integrations/pull/7632
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if dimension field mapping is correct in the data stream template.

## Datastream : Datanode
  - [x] Add dimension fields 
         https://github.com/elastic/integrations/pull/7676
  - [x] Adding metric_type mapping
         https://github.com/elastic/integrations/pull/7717
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.
 
## Datastream : NameNode
  - [x] Add dimension fields 
         https://github.com/elastic/integrations/pull/7720
  - [x] Adding metric_type mapping
         https://github.com/elastic/integrations/pull/7722
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.

## Datastream : NodeManager
  - [x] Add dimension fields 
          https://github.com/elastic/integrations/pull/7642 
  - [x] Adding metric_type mapping
         https://github.com/elastic/integrations/pull/7644

#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.

Enable TSDB by default - https://github.com/elastic/integrations/pull/7769

**Comment by ritalwar** [comment]
Since this package is in beta, its priority is considered low. 
Need to migrate packages with P0 and P1 priority first.

**Comment by lalit-satapathy** [comment]
@harnish-elastic @milan-elastic can you review all the hadoop TSDB PRs?
