### ISSUE TITLE
[Fleet] Package version error

### ISSUE THREAD

**Issue by mostlyjason** [elastic/integrations#671]
**Kibana version:**
7.10.1

**Elasticsearch version:**
7.10.1

**Original install method (e.g. download page, yum, from source, etc.):**
docker

**Describe the bug:**
When I load the integrations page I see an error message saying:

```Unable to initialize Fleet

Document "apache-Logs-Apache-Dashboard" has property "dashboard" which belongs to a more recent version of Kibana [7.11.0]. The last known version is [7.9.3]
```

Its not clear why it is trying to load the package version for 7.11, since I am running a 7.10.1 version of Kibana. Are we not limiting the package version by the kibana version?

This also appears to be an intermittent issue. I switched to the discover app and back, and the issue remained. Then I did it again and the page loaded successfully. I did a hard refresh and the error came back.

**Steps to reproduce:**
1. Install ES/Kibana 7.10.1
2. Install Apache package 7.10.1 or below (not the latest)
3. Load integrations page a few times until the error shows (its intermittent)

**Expected behavior:**
It should load the integrations page and show the list of integrations.

**Provide logs and/or server output (if relevant):**
I see a network call to http://kibana:5601/api/fleet/setup that turns 422 with the error:
```
{
	"statusCode": 422,
	"error": "Unprocessable Entity",
	"message": "Document \"apache-Logs-Apache-Dashboard\" has property \"dashboard\" which belongs to a more recent version of Kibana [7.11.0]. The last known version is [7.9.3]"
}
```

The kibana log shows an error message:
```
{"type":"log","@timestamp":"2021-02-02T11:01:06Z","tags":["warning","plugins","ingestManager"],"pid":6,"message":"{ Error: Saved object [dashboard/apache-Metrics-Apache-HTTPD-server-status] not found\n    at Function.createGenericNotFoundError (/usr/share/kibana/src/core/server/saved_objects/service/lib/errors.js:136:37)\n    at SavedObjectsRepository.delete (/usr/share/kibana/src/core/server/saved_objects/service/lib/repository.js:574:46)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n  data: null,\n  isBoom: true,\n  isServer: false,\n  output:\n   { statusCode: 404,\n     payload:\n      { statusCode: 404,\n        error: 'Not Found',\n        message:\n         'Saved object [dashboard/apache-Metrics-Apache-HTTPD-server-status] not found' },\n     headers: {} },\n  reformat: [Function],\n  typeof: [Function: notFound],\n  [Symbol(SavedObjectsClientErrorCode)]: 'SavedObjectsClient/notFound' }"}
{"type":"log","@timestamp":"2021-02-02T11:01:10Z","tags":["error","plugins","ingestManager"],"pid":6,"message":"Document \"apache-Logs-Apache-Dashboard\" has property \"dashboard\" which belongs to a more recent version of Kibana [7.11.0]. The last known version is [7.9.3]"}
```

I do some hard refreshes and the page loads. Right after the call to `/api/fleet/epm/packages?experimental=true` my kibana log shows:
```
{"type":"log","@timestamp":"2021-02-02T11:08:38Z","tags":["error","plugins","ingestManager"],"pid":6,"message":"Saved object [dashboard/apache-Logs-Apache-Dashboard] not found"}
```

**Any additional context:**

**Comment by mtojek** [comment]
It was fixed in https://github.com/elastic/package-storage/pull/790 , deployed to prod and concerned exactly that package. Not sure how did you get the faulty package. Is it a long running cluster?
