### ISSUE TITLE
Adding metric_type mapping for CockroachDB TSDB Enablement.

### ISSUE THREAD

**Issue by ritalwar** [elastic/integrations#6728]
Metric_type mapping PR was left as part of TSDB enablement of CockroachDB [task](https://github.com/elastic/integrations/issues/5410).

As metric_type mapping for dynamic template was blocked on [issue](https://github.com/elastic/kibana/issues/155004), which is now resolved and also verified, so now we are good to create the metric_type PR for CockroachDB.

PR -> https://github.com/elastic/integrations/pull/6753

**Comment by lalit-satapathy** [comment]
Let's link to the PR in description.

**Comment by ritalwar** [comment]
Revert metrics field definition to the original format: [PR](https://github.com/elastic/integrations/pull/7429)
