### ISSUE TITLE
Jolokia Integration release I do not see it in epr package repository

### ISSUE THREAD

**Issue by cmendez92** [elastic/integrations#6752]
In the release notes I see the Jolokia integration is being updated in epr, but when I search in repository I didn't see Jolokia Integration.

¿Is that normal behaviour?

Greetings.

**Comment by ishleenk17** [comment]
Hello @cmendez92 : It's in Beta currently. I hope you have enabled the `Display Beta Integrations` toggle

<img width="282" alt="Screenshot 2023-06-30 at 1 28 17 PM" src="https://github.com/elastic/integrations/assets/102962586/ae875d1d-de8a-47cf-8f68-5a3626b49be3">
