### ISSUE TITLE
[network_traffic] tls.detailed.server_certificate_chain mapping error

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#6842]
`tls.detailed.server_certificate_chain` is mapped as a `keyword`, but it appears that the contents are an object under v8.6.2.

`Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Date(2023, time.June, 30, 16, 23, 9, 96963000, time.Local), Meta:{"input_id":"packet-network-07d59c7a-0a33-46b2-a336-fda9e792ec80","raw_index":"logs-network_traffic.tls-default","stream_id":"packet-network_traffic.tls-07d59c7a-0a33-46b2-a336-fda9e792ec80"},`

```
{
  "type": "mapper_parsing_exception",
  "reason": "failed to parse field [tls.detailed.server_certificate_chain] of type [keyword] in document with id 'V-gwDokBS9-8Co-dO9Mt'. Preview of field's value: '{not_after=2030-08-23T22:21:28.000Z, subject={country=US, organization=Amazon, distinguished_name=CN=Amazon RSA 2048 M01,O=Amazon,C=US, common_name=Amazon RSA 2048 M01}, not_before=2022-08-23T22:21:28.000Z, public_key_algorithm=RSA, signature_algorithm=SHA256-RSA, serial_number=166129328851546858514271303855646110030630415, version_number=3, public_key_size=2048, issuer={country=US, organization=Amazon, distinguished_name=CN=Amazon Root CA 1,O=Amazon,C=US, common_name=Amazon Root CA 1}}'",
  "caused_by": {
    "type": "illegal_state_exception",
    "reason": "Can't get text on a START_OBJECT at 1:5167"
  }
}
```

### References

- Original report: https://elasticstack.slack.com/archives/C02J2JBS0FP/p1688179249534349?thread_ts=1688163504.403769&cid=C02J2JBS0FP
- https://github.com/elastic/integrations/blob/058b5e1909ab39c5fc76fe7121c7d944233ad931/packages/network_traffic/data_stream/tls/fields/protocol.yml#L163-L165

**Comment by PoppaShell** [comment]
The same issue is present with `tls.detailed.client_certificate_chain` also being mapped as a `keyword` but contents appear to be an object.

`Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Date(2023, time.July, 6, 9, 34, 22, 359166000, time.Local), Meta:{"input_id":"packet-network-07d59c7a-0a33-46b2-a336-fda9e792ec80","raw_index":"logs-network_traffic.tls-default","stream_id":"packet-network_traffic.tls-07d59c7a-0a33-46b2-a336-fda9e792ec80"}`

```{"type":"document_parsing_exception","reason":"[1:3926] failed to parse field [tls.detailed.client_certificate_chain] of type [keyword] in document with id 'gFOgK4kBoCeVF04oKmWg'. Preview of field's value: '{not_after=2026-07-18T14:39:18.000Z, subject={organization=<REDACTED>, distinguished_name=CN=<REDACTED>,O=<REDACTED>, common_name=<REDACTED>}, not_before=2016-07-18T00:00:00.000Z, public_key_algorithm=ECDSA, signature_algorithm=ECDSA-SHA256, version_number=3, public_key_size=256, serial_number=<REDACTED>, issuer={organization=<REDACTED>, distinguished_name=CN=<REDACTED>,OU=<REDACTED>, common_name=<REDACTED>, organizational_unit=<REDACTED>}}'","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:3251"}}```

**Comment by PoppaShell** [comment]
And also similar issue with `system.process.cpu.total.time.ms` being mapped as `data`, but it appears to just be a milliseconds value, which I would assume needs to be mapped as a `float`.

`Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Date(2023, time.July, 6, 9, 42, 53, 643916600, time.Local), Meta:{"input_id":"metrics-monitoring-agent","raw_index":"metrics-elastic_agent.elastic_agent-default","stream_id":"metrics-monitoring-filebeat-1"}`

```
{
  "type":"document_parsing_exception",
  "reason":"[1:311] failed to parse field [system.process.cpu.total.time.ms] of type [date] in document with id 'bqKnK4kBDcIblIdM9Jqx'. Preview of field's value: '1.2172796E7'",
  "caused_by":{
    "type":"illegal_argument_exception",
    "reason":"failed to parse date field [1.2172796E7] with format [strict_date_optional_time||epoch_millis]",
    "caused_by":{
      "type":"date_time_parse_exception",
      "reason":"Failed to parse with all enclosed parsers"}
  }
}
```

**Comment by andrewkroh** [comment]
@PoppaShell That last comment appears to be related to https://github.com/elastic/integrations/issues/4208. I would suggest commenting on that issue instead so that we can keep this one focused on the `network_traffic` integration.

**Comment by PoppaShell** [comment]
@andrewkroh I can do that.

In regards to the `network_traffic` integration fields, someone mentioned the following in the Community Slack, for what it's worth.

```
The field type is correct. Packetbeat is sending a slice of PEM-encoded certificates; these should not be interpreted as objects.
```

**Comment by efd6** [comment]
The defined type in network traffic is correct, the value is a slice of PEM encoded certificates. The values are coming from [here](https://github.com/elastic/beats/blob/f75a2ed898bc883c451d6aab35cc60d17158f788/packetbeat/protos/tls/tls.go#L453-L461) and constructed [here](https://github.com/elastic/beats/blob/f75a2ed898bc883c451d6aab35cc60d17158f788/packetbeat/protos/tls/tls.go#L315-L318). These come from [here](https://github.com/elastic/beats/blob/f75a2ed898bc883c451d6aab35cc60d17158f788/packetbeat/protos/tls/tls.go#L472).

**Comment by andrewkroh** [comment]
@efd6 I think the code you pointed at is for a different field. It's missing the `.detailed.` part. It looks like the `tls.detailed.{server,client}_certificate_chain` are arrays of objects.

https://github.com/elastic/beats/blob/f0215ff5cfdbcb0db8ebc1f07af1b4885081389b/packetbeat/protos/tls/tls_test.go#L299-L304

https://github.com/elastic/beats/blob/37ddd1e4daa5c5679cf49a846b3f80d315966a24/packetbeat/protos/tls/tls.go#L308-L312

https://github.com/elastic/beats/blob/37ddd1e4daa5c5679cf49a846b3f80d315966a24/packetbeat/protos/tls/parse.go#L637-L639

**Comment by efd6** [comment]
Yes, you are correct. Will change the mapping to flattened.

**Comment by efd6** [comment]
Query: Why does ES render the field as invalid JSON?
