### ISSUE TITLE
[azure_frontdoor] waf ingest pipeline does not preserve event.original when preserve toggle selected

### ISSUE THREAD

**Issue by bvader** [elastic/integrations#6847]
Issue: azure frontdoor waf does not preserve `event.original` when we toggle selected
Expected Result: `event.orginal` should be preserved, there is no condition in the ingest pipeline 

See Code: 
https://github.com/elastic/integrations/blob/main/packages/azure_frontdoor/data_stream/waf/elasticsearch/ingest_pipeline/default.yml

**Comment by nicpenning** [comment]
I stumbled across this problem when trying to use this integration. This should fix it: https://github.com/elastic/integrations/pull/7463
