### ISSUE TITLE
DGA Integration - Documentation

### ISSUE THREAD

**Issue by tammytorbert** [elastic/integrations#6873]
The DGA integration has a blog link to provide guidance to setup this integration.  However, this is an old link.  It should point to this new blog - https://www.elastic.co/security-labs/detect-domain-generation-algorithm-activity-with-new-kibana-integration or should incorporate this instruction into the integration details page.

**Comment by susan-shu-c** [comment]
Thank you for the suggestion - now closing this issue as the blogs are now in the DGA package [README](https://github.com/elastic/integrations/tree/main/packages/dga). Thanks @jmcarlock for surfacing this!
