### ISSUE TITLE
[Arista NG Firewall] Parse `log.syslog.hostname` from `log.source.address` to allow filtering by firewall

### ISSUE THREAD

**Issue by MakoWish** [elastic/integrations#6874]
The Arista NG Firewall logs do not include a hostname in the syslog header, so we are left with Elastic Agent populating the source address as `log.source.address`. Unfortunately, this includes the port number that changes quite frequently, so there is no easy way to filter by which firewall you want to view data from. 

I will be creating a PR to add a `gsub` processor that removes the port from the `log.source.address` and puts the result to [`log.syslog.hostname`](https://www.elastic.co/guide/en/ecs/current/ecs-log.html#field-log-syslog-hostname). Having this field as either a keyword hostname or FQDN, or an IP address without the port, will allow filtering by source firewall.

**Comment by gogochan** [comment]
Based on this comment, https://github.com/elastic/integrations/pull/6875#issuecomment-1636267963, this seems to be completed already. Please re-open if that's not the case.
