### ISSUE TITLE
[SQL Input Package] Support merge_results in SQL Input Package

### ISSUE THREAD

**Issue by ishleenk17** [elastic/integrations#6896]
Merge results is one of the features supported in the SQL beats module. It's currently used by MSSQL Integration.
We would like to add it's support to the SQL Input Package as well. 

It helps to merge the results of 2 queries. Details of this feature can be seen [here](https://github.com/elastic/beats/issues/31806). 

Related Issues: 
[Enhancement Request](https://github.com/elastic/integrations/issues/6243) for merge_result

**Comment by ishleenk17** [comment]
@lalit-satapathy : I see that this will get enabled at the module level.
But, what if the requirement is for merging say 2 out of the 5 queries? 
I don't think that is supported yet. 

It's either all merge or none.

**Comment by lalit-satapathy** [comment]
> But, what if the requirement is for merging say 2 out of the 5 queries? I don't think that is supported yet.

That is not supported. We dont want to provide SQL merge_results as a flag, which is blindly enabled. It is an advanced feature, only for specific usages of document optimisation.
