### ISSUE TITLE
logs-zeek.http-2.11.0 uri-parts

### ISSUE THREAD

**Issue by charliek17** [elastic/integrations#6913]
logs-zeek.http pipeline seems to error on rename zeek.http.host to url.domain as it already contains a value derived from the uri-parts processor. the remove "url.domain" is set to only run when its empty so if already filled it will error.

Why is it there as url-parts can generate it?

**Comment by ebeahan** [comment]
Looking at how the pipeline's [implemented](https://github.com/elastic/integrations/blob/main/packages/zeek/data_stream/http/elasticsearch/ingest_pipeline/default.yml#L120), the `uri_parts` processor runs to extract different fields for the `uri` field in the original Zeek log. In the Zeek HTTP log (at least in the [samples](https://github.com/elastic/integrations/blob/main/packages/zeek/data_stream/http/_dev/test/pipeline/test-http.log) included in the integration for pipeline testing), the `uri` field doesn't actually contain the host name. Under normal circumstances, the `url.domain` field created by `uri_parts` will be null and then deleted by the [`remove` processor](https://github.com/elastic/integrations/blob/main/packages/zeek/data_stream/http/elasticsearch/ingest_pipeline/default.yml#L134) that follows. The `zeek.http.host` field is then [renamed](https://github.com/elastic/integrations/blob/main/packages/zeek/data_stream/http/elasticsearch/ingest_pipeline/default.yml#L142) to `url.domain`.

@charliek17 are you seeing specific pipeline errors when ingesting Zeek HTTP events?

**Comment by efd6** [comment]
@charliek17 I have a fix based on assumptions of what your event looks like. Can you provide a complete sanitized event.original that would fail?

**Comment by charliek17** [comment]
I can't issue a customer log but here's the example log from our own repo with the failing log added in.
`{"ts":1547687130.172944,"uid":"CCNp8v1SNzY7v9d1Ih","id.orig_h":"10.178.98.102","id.orig_p":62995,"id.resp_h":"89.160.20.156","username":"user","id.resp_p":80,"trans_depth":1,"method":"GET","host":"ocsp.apple.com","uri":"http://msedge.b.tlu. di.delivery.mp.microsoft.com/filestreamingservice/ocsp04-aaica02/ME4wTKADAgEAMEUwQzBBMAkGBSsOAwIaBQAEFNqvF+Za6oA4ceFRLsAWwEInjUhJBBQx6napI3Sl39T97qDBpp7GEQ4R7AIIUP1IOZZ86ns=","version":"1.1","user_agent":"com.apple.trustd/2.0","request_body_len":0,"response_body_len":3735,"status_code":200,"status_msg":"OK","tags":[],"resp_fuids":["F5zuip1tSwASjNAHy7"],"resp_mime_types":["application/ocsp-response"]}`
