### ISSUE TITLE
[docs] Broken `google_scc` docs

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/integrations#6918]
In the Google Security Command Center integration (added in https://github.com/elastic/integrations/pull/6645), the description of the `google_scc.finding.access.service_account.delegation_info.principal.subject` field has an unclosed `{`, which is breaking the docs build. **No integration docs updates will be published until this is resolved here and the changes are available on EPR.**

https://github.com/elastic/integrations/blob/b845b1d97b61502716437f4de2556a988f309f89/packages/google_scc/data_stream/finding/fields/fields.yml#L45

To fix this, this part of the description needs to be updated:

```diff
- principal://iam.googleapis.com/{identity pool name}/subject/{subject)
+ principal://iam.googleapis.com/{identity pool name}/subject/{subject}
```

cc @bmorelli25 @janvi-elastic @elastic/security-external-integrations

**Comment by jamiehynds** [comment]
@piyush-elastic @janvi-elastic can we get this addressed ASAP as it's blocking all new integration docs for being published.
