### ISSUE TITLE
[ Memcached ] TSDB enablement

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#6925]
## Test Environment Setup
- [x] Creation of Test Environment

## Datastream : `stats` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/6926
  - [x] Add metric_type mappings -Already exists

#### Verification and validation
  - [x] Verification of data in visualisation after enabling the TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Verify if the TSDB can be disabled using the API method
  - [x] Verify if the TSDB can be re-enabled after 4 hours, following disablement using API method, making use of package upgrade. 
  - [x] Add screenshots of dashboards (Recommended), if applicable. 
 
## TSDB Release PR
 - [x] PR to enable TSDB - https://github.com/elastic/integrations/pull/6983
 - [x] Update the tracking sheet (GA release version, github link, status)

**Comment by agithomas** [comment]
After enabling TSDB, metric_type mapping

<img width="2553" alt="image" src="https://github.com/elastic/integrations/assets/101976829/658b8685-e433-4450-a109-67ff516ee2a3">

**Comment by lalit-satapathy** [comment]
@agithomas,

Are the metric_types defined [here](https://github.com/elastic/integrations/blob/main/packages/memcached/data_stream/stats/fields/fields.yml  ) correct and complete?

**Comment by agithomas** [comment]
> Are the metric_types defined [here](https://github.com/elastic/integrations/blob/main/packages/memcached/data_stream/stats/fields/fields.yml) correct and complete?

I looked at the completeness (already existing). The one that does not have the mapping is `pid` and it is not expected to have any `metric_type` mapping.

**Comment by lalit-satapathy** [comment]
> > Are the metric_types defined [here](https://github.com/elastic/integrations/blob/main/packages/memcached/data_stream/stats/fields/fields.yml) correct and complete?
> 
> I looked at the completeness (already existing). The one that does not have the mapping is `pid` and it is not expected to have any `metric_type` mapping.

@ishleenk17, Can you cross-check and confirm if the existing metric types  metric_types defined [here](https://github.com/elastic/integrations/blob/main/packages/memcached/data_stream/stats/fields/fields.yml) correct and complete? They were added before TSDB.

**Comment by ishleenk17** [comment]
> > > Are the metric_types defined [here](https://github.com/elastic/integrations/blob/main/packages/memcached/data_stream/stats/fields/fields.yml) correct and complete?
> > 
> > 
> > I looked at the completeness (already existing). The one that does not have the mapping is `pid` and it is not expected to have any `metric_type` mapping.
> 
> @ishleenk17, Can you cross-check and confirm if the existing metric types metric_types defined [here](https://github.com/elastic/integrations/blob/main/packages/memcached/data_stream/stats/fields/fields.yml) correct and complete? They were added before TSDB.

The metric_types look fine for memcached
