### ISSUE TITLE
[azure_billing] Fix Azure Dashboard to use a dataset filter as per guidelines.

### ISSUE THREAD

**Issue by ash-darin** [elastic/integrations#6946]
**Description:**

The Azure Billing Integration provides a dashboard "[Azure Billing] Billing overview" with corresponding visualizations. The dashboard and visualizations are slow to the point that Kibana suggests changing autocomplete.

![autocomplete](https://github.com/elastic/integrations/assets/126493657/3a583a94-a0b5-49e5-876b-69d272f9fc74)

The reason for this is that the visualizations use the "metrics-*" data view without a filter on data_stream.dataset as suggested in the [Contributing Guide](https://github.com/elastic/integrations/blob/43d3ba0422800bfe416bd4a1ef00b78ef2a9f9d0/docs/dashboard_guidelines.md#visualizations-should-contain-a-filter)

![2023-07-13 09_42_11-](https://github.com/elastic/integrations/assets/126493657/2f79e7ae-89ca-472a-ae35-c3b0c1a8c27f)

**Suggestion:**

Set a filter for "data_stream.dataset: azure.billing". This is suggested in the [dashboard guidelines](https://github.com/elastic/integrations/blob/43d3ba0422800bfe416bd4a1ef00b78ef2a9f9d0/docs/dashboard_guidelines.md#visualizations-should-contain-a-filter).

> It is recommended to set a filter in each visualization at least by the required data_stream.dataset.

Alternatively provide a "metrics-azure.billing-\*" or "metrics-azure.\*" data view with the integration and make the visualizations use it to fix the performance issues.

**Comment by zmoog** [comment]
Hey @ash-darin, thank you for taking the time to investigate this problem and proposing solutions!

@cgi-gerlando-caldara, I agree it is a good and welcome change. We reviewed and merged the PR from @smnschneider, and version 1.3.1 will be available within the hour.
