### ISSUE TITLE
[meta] Upgrade integrations to ECS 8.9

### ISSUE THREAD

**Issue by narph** [elastic/integrations#6949]
Track ECS 8.9 updates to integration packages maintained by the `elastic/security-external-integrations` team.

## ECS 8.9 Changes

This is a summary of the changes in ECS 8.9. You can view the official changelog [here](https://github.com/elastic/ecs/blob/8.9/CHANGELOG.md) (invalid link for now - will update).

#### Added
 

This issue will be updated once the necessary work to be done is evaluated.

**Comment by kcreddy** [comment]
Draft PRs generated as placeholders. 
Once the ECS changes for `8.9` is released, the PRs will be opened for review.

**Comment by kcreddy** [comment]
Among the packages that are owned by SEI team as per CODEOWNERS, the following packages are being skipped by the `ecs-update` tool because of the reasons stated:

- bluecoat:
    - Deprecated
- f5:
    - Deprecated
- gcp:
    - Ownership changed, and hence skipped.
- juniper_junos:
    - Deprecated
- juniper_netscreen:
    - Deprecated
