### ISSUE TITLE
Radware integration needs sample logs for system test

### ISSUE THREAD

**Issue by adriansr** [elastic/integrations#698]
Currently system tests are disabled.

**Comment by jamiehynds** [comment]
@adriansr I've been in touch with the vendor, they are in the process of gathering sample events for us. In the meantime, they provided an integration guide. Attaching incase it's of use. 
[DefensePro-v8-x-SIEM_Integration-Guide.pdf](https://github.com/elastic/integrations/files/6076308/DefensePro-v8-x-SIEM_Integration-Guide.pdf)
