### ISSUE TITLE
Windows TSDB Enablement

### ISSUE THREAD

**Issue by ritalwar** [elastic/integrations#6993]
## Test Environment Setup
- [x] Creation of Windows Test Environment

## Datastream : perfmon 

Note: According to Andres, when examining the expected usage of the metrics dataset "perfmon," it appears more suitable to treat it as an input package, where users can query specific metrics. Based on this observation, he recommends postponing its migration for the time being. As a result, we will only migrate the service dataset as part of this migration task.

~- [ ]Add dimension fields~
  ~- [ ] Adding metric_type mapping~
#### Verification and validation
  ~- [ ] Verification of data in visualisation after enabling TSDB flag in kibana~
  ~- [ ] Verification of the count of documents (before & after TSDB enablement) in Discover Interface~
  ~- [ ] Verify if dimension field mapping is correct in the data stream template.~

## Datastream : service
  - [x] Add dimension fields 
          https://github.com/elastic/integrations/pull/7172
  - [x] Adding metric_type mapping
         https://github.com/elastic/integrations/pull/7200
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.

Enable TSDB by default - https://github.com/elastic/integrations/pull/7206

## Screenshots

![image](https://github.com/elastic/integrations/assets/102972658/92c72470-3402-46f8-8978-a81687923864)
![image](https://github.com/elastic/integrations/assets/102972658/f7457a7f-2059-459a-865f-08184006331f)
![image](https://github.com/elastic/integrations/assets/102972658/cc62d8a5-275e-4ad5-a050-6e568483e0f0)
![image](https://github.com/elastic/integrations/assets/102972658/55f23d4f-3762-43bc-8c9e-49ca4717ae14)
![image](https://github.com/elastic/integrations/assets/102972658/5f667376-0246-42d4-903d-c003eb539ef1)

**Comment by lalit-satapathy** [comment]
@ritalwar, Please update the overall plan for windows TSDB enablement here.

**Comment by ritalwar** [comment]
> @ritalwar, Please update the overall plan for windows TSDB enablement here.

Updated in description.

**Comment by ritalwar** [comment]
Also here is the summary of testing conducted on Windows VM:

- Verified the number of datasets in the discover view.
- Checked data collection and the count of event documents before and after enabling TSDB.
- Verified the count of fields.
- Checked the index mode, which was set to "time_series" in the Index Template after enabling TSDB.
- Verified the count of dimension fields and their limits.
- Confirmed the "time_series_metric" for the fields with metric_type mapping.
- Checked visualisations and Dashboards after enabling TSDB.
