### ISSUE TITLE
[MongoDB Atlas] Explore OpenTelemetry to collect logs and metrics in elasticsearch 

### ISSUE THREAD

**Issue by milan-elastic** [elastic/integrations#6994]
Goal of this issue is to check feasibility of collecting MongoDB Atlas metrics and logs with help of **Opentelemetry** and ingesting it into elasticsearch so it can be monitored using kibana. 

**What is [OpenTelemetry](https://opentelemetry.io/) ?**
OpenTelemetry is an Observability framework and toolkit designed to create and manage telemetry data such as traces, metrics, and logs. Crucially, OpenTelemetry is vendor- and tool-agnostic, meaning that it can be used with a broad variety of Observability backends, including open source tools like Jaeger and Prometheus, as well as commercial offerings. OpenTelemetry is a Cloud Native Computing Foundation (CNCF) project.

Opentelemetry has [MongoDB atlas receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/mongodbatlasreceiver) already build for fetching data from MongoDB Atlas instances. Users can install Opentelemetry and use this receiver to collect data from MongoDB Atlas.

**Comment by milan-elastic** [comment]
**Steps to Install Opentelemetry:**

1. Check this [link](https://github.com/open-telemetry/opentelemetry-collector-releases/releases) for latest version of otel and download rpm version with following common
      - wget https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v<version>/otelcol-contrib_<version>_linux_386.rpm
2. Run the following command to install the downloaded file
      - rpm -i <file_name>
3. After the above step config file for OTEL will be generated at the following location :- /etc/otelcol-contrib/config.yaml
4. Restart otel after changing config file according to requirement with following command
      - systemctl restart otelcol-contrib
5. Run following command to display logs 
      - journalctl -u otelcol-contrib -f

Opentelemetry has [MongoDB atlas receiver ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/mongodbatlasreceiver)already build for fetching data from MongoDB Atlas instances. Users can install Opentelemetry and use this receiver to collect data from MongoDB Atlas. Minimum configuration to enable MongoDB Atlas receiver is as follows.

> receivers:
  mongodbatlas:
      public_key: ${env:MONGODB_ATLAS_PUBLIC_KEY}
      private_key: ${env:MONGODB_ATLAS_PRIVATE_KEY}

To get output on logs we can use following exporter.

> exporters:
  logging:
    verbosity: detailed


To send data from OTEL to elastic search we need to add otlp/elastic:exporter as shown in this [link](https://www.elastic.co/guide/en/apm/guide/current/open-telemetry-direct.html#connect-open-telemetry-collector). ELASTIC_APM_SERVER_ENDPOINT and ELASTIC_APM_SECRET_TOKEN can be found from default APM integration in cloud instance of kibana. We need to use following exporterl to send data from OTEL to elasticsearch.

> exporters: 
  otlp/elastic: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "${ELASTIC_APM_SERVER_ENDPOINT}"  
    headers:
      # Elastic APM Server secret token
      Authorization: "Bearer ${ELASTIC_APM_SECRET_TOKEN}"

Limitation of this approach:
1. Currently, no OTEL integration available and users will have to set up APM server to configure OTEL with elastic search.
2. Metrics collected through MongoDB atlas receiver are very limited compared to Prometheus end point
3. Based on the documents currently only Activity log data is being collected.

**Comment by ishleenk17** [comment]
@milan-elastic : How are we getting data from APM fields mapped to Elastic Observability fields?
Is it a direct 1:1 mapping? Do we have to do processing on the fields to have them on Kibana?

**Comment by milan-elastic** [comment]
> @milan-elastic : How are we getting data from APM fields mapped to Elastic Observability fields? Is it a direct 1:1 mapping? Do we have to do processing on the fields to have them on Kibana?

What do you mean by APM field mapping? Are you referring to [this](https://www.elastic.co/guide/en/apm/guide/current/data-model.html)? Currently, We are running the OTEL config.yml which sends the MongoDB Atlas data to the APM server and will ingest them into Elastic and we can search it from Kibana. For further field mapping and processing, we are not sure how it can be done, there should be some configuration file for it but currently, we haven't come across any. To get more details about it we need to check the APM integration backend which currently I am not finding in the integration Repo. I assume there should be some docs and guidelines for OTEL integrations that can help us to answer this.

@rameshelastic @lalit-satapathy Do we have any internal docs around OTEL that can help us to understand how we can process the data after getting collected using OTEL and give some idea about how OTEL integrations work as a bundle?

**Comment by milan-elastic** [comment]
Please find the details of the latest OTEL logs approaches and findings [here](https://github.com/elastic/obs-infraobs-team/issues/1250#issuecomment-1913959653)
