### ISSUE TITLE
Elasticsearch Metrics integration dashboard error: Field [elasticsearch.ingest_pipeline.total.count] of type [long] is not supported for aggregation [sum].

### ISSUE THREAD

**Issue by bczifra** [elastic/integrations#6996]
The `[Elasticsearch] Ingest Pipelines` dashboard in the Elasticsearch integration is throwing an error that: `Field [elasticsearch.ingest_pipeline.total.count] of type [long] is not supported for aggregation [sum].`

* `index_mode` is set to `time_series`: https://github.com/elastic/integrations/blob/3ce066e4b81169ad068909313e4cc6336c261dd8/packages/elasticsearch/data_stream/ingest_pipeline/manifest.yml#L10
* `elasticsearch.ingest_pipeline.total.count` is a counter field: https://github.com/elastic/integrations/blob/3ce066e4b81169ad068909313e4cc6336c261dd8/packages/elasticsearch/data_stream/ingest_pipeline/fields/fields.yml#L18C17-L18C17
* the dashboard defines a `sum` aggregation on that field: https://github.com/elastic/integrations/blob/3ce066e4b81169ad068909313e4cc6336c261dd8/packages/elasticsearch/kibana/dashboard/elasticsearch-metrics-ingest-pipelines.json#L584C93-L584C93
* Sum aggregations aren’t available on counter fields: https://github.com/elastic/elasticsearch/issues/96170
* The `release` is marked `experimental`: https://github.com/elastic/integrations/blob/3ce066e4b81169ad068909313e4cc6336c261dd8/packages/elasticsearch/data_stream/ingest_pipeline/manifest.yml#L4

As a workaround, it's possible to [disable the use of TSDS on the data stream]https://www.elastic.co/guide/en/fleet/current/data-streams-advanced-features.html#data-streams-advanced-tsds-disable).

**Comment by joshdover** [comment]
Note that to reproduce this, you have to be using Elastic Agent to monitor Elasticsearch. We do not use TSDS when monitoring with just Beats.

**Comment by lalit-satapathy** [comment]
The aggregation restrictions on counter fields are being removed and recent fixes has gone from elasticsearch on the same- https://github.com/elastic/elasticsearch/pull/97974

**Comment by joshdover** [comment]
I can confirm this is fixed on 8.9.1
