### ISSUE TITLE
[CrowdStrike] Update docs with supported event types

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#7013]
Our CrowdStrike Falcon integration lists supported event types. It need to be updated to add event types we've recently added to the integration. https://github.com/elastic/integrations/tree/main/packages/crowdstrike#logs

List of additional event types to be added:

- CSPM Streaming events
- CSPM Search events
- IDP Incidents
- IDP Summary events
- Mobile Detection events
- Recon Notification events
- XDR Detection events

**Comment by alaudazzi** [comment]
Additional events added to https://docs.elastic.co/integrations/crowdstrike. Closing.
