### ISSUE TITLE
proposal: system,windows: make code ownership more fine grained

### ISSUE THREAD

**Issue by efd6** [elastic/integrations#7023]
The system and windows packages contain data streams that are maintained by @elastic/security-external-integrations, for example system/auth, system/security, windows/powershell_operational and so on. Due to the current approach to code ownership, SEI needs to get approval from @elastic/obs-infraobs-integrations for changes to the security data streams in system. In other cases, it is possible to @elastic/elastic-agent-data-plane to approve changes in security data streams in the windows package.

```
/packages/system @elastic/obs-infraobs-integrations
/packages/system/kibana @elastic/elastic-agent-data-plane @elastic/kibana-visualizations
```

```
/packages/windows @elastic/elastic-agent-data-plane @elastic/security-external-integrations
```

It would be good if we could make finer grained ownership rules to allow independent review of security data streams by SEI. AFAIU this would essentially just need to be a change to the CODEOWNERS file, but the teams would need to agree on the breakdown.

/cc @jsoriano

**Comment by jsoriano** [comment]
Yes, I think that this could be achieved with a change in the CODEOWNERS file. @efd6 would you like to open a PR with the proposed change?

**Comment by lalit-satapathy** [comment]
> It would be good if we could make finer grained ownership rules to allow independent review of security data streams by SEI

This is a good idea. We could have CODEONWER at a data stream level, where a specific data stream is owned by a separate team, which is different from the package owner. This will avoid, certain PRs criss-crossing different teams and waiting for CODEOWNER review. We could possibly extend this outside of system/windows packages. Let's start from these two packages first and extend the same idea to other packages as applicable.

In an earlier discussion with @ruflin, we discussed a possibility to generate CODEOWNER file automatically, than maintaining it manually. The code-owner can be defined at a data-stream manifest level and CODEOWNER file getting auto-compiled. @jsoriano, Is this something, which can  be explored long-term?

**Comment by jsoriano** [comment]
> The code-owner can be defined at a data-stream manifest level and CODEOWNER file getting auto-compiled. @jsoriano, Is this something, which can be explored long-term?

This has been discussed some times before. In principle we want to have a single point of contact for each package, so support engineers or users don't need to look for the owner of each specific part of the package. They can contact with the single owner, and this owner can forward the request to the maintainer of each specific part if needed.

Also, packages are released as a single piece, and I think it is good to have a single responsible for this.

Having owners mapped per data stream doesn't solve some use cases that we already have for packages maintained by multiple teams, such as the packages whose dashboards are maintained by the kibana visualizations team.

So generally speaking, I would say that the owner in the manifest and the owners in the CODEOWNER file have different purpouses and we cannot map them one to one. The owner in the manifest is like the "main" owner and the external point of contact, while the owners in the CODEOWNER file are the maintainers of the package or any of their parts.

**Comment by efd6** [comment]
@jsoriano I've sent #7028 as a first change for this. It is the more important of the two and the more complex.

Please comment on the approach at the PR for refinement. Once we've stabilised, I'll send PRs for other relevant packages; I mentioned Windows, but GCP has also been mentioned.

**Comment by jsoriano** [comment]
> The second aspect, has been an issue recently and we need to address that.

I see, but current CODEOWNER seems to be enough, right?

**Comment by leehinman** [comment]
One point of confusion I see is the fact that the top level `manifest.yml` has an owners field, and that doesn't necessarily reflect what is in the `CODEOWNERS` file.

Could we change the package-spec to allow `owner` in the data_stream `manifest.yml` ?  Or at least add the multiple teams to the `owner` field in the top level `manifest.yml`. 

Or I suppose we could drop the `owner` field all together from `manifest.yml` and just use the `CODEOWNERS` file.

But no matter what, the data should be in sync (or one copy).

**Comment by efd6** [comment]
@leehinman The issue here is that the term 'owner' is overloaded. Our 'owner' in the manifest means owner, while GitHub's 'owner' means caretaker for the purposes of approvals; they refer to different concepts in different domains. This doesn't necessarily bring a conflict, though I agree, having them more concordant would be nice and having it possible to specify the owner in the data stream's manifest would help that at the cost of having the concept spread into more locations (I'm not sure this cost is worth it).

**Comment by lalit-satapathy** [comment]
>I'm mostly coming at this from a support perspective. If there is a problem with a data_stream, what is the algorithm (for a person that is external to the development process) to figuring out who to ask for help? In the past we have pointed at the 'owner' in the manifest.yml as a way to find a team to ask for help. But now people should probably parse the CODEOWNERS file? 

I agree, we should desire long-term support cases going to the right team based on an up-to-date CODEOWNERS for each data stream. It will be ideal, if CODEOWNERS is made auto-generated also.

**Comment by jsoriano** [comment]
> I'm mostly coming at this from a support perspective. If there is a problem with a data_stream, what is the algorithm (for a person that is external to the development process) to figuring out who to ask for help? In the past we have pointed at the 'owner' in the manifest.yml as a way to find a team to ask for help. But now people should probably parse the CODEOWNERS file?

I think that after this change the algorithm should still be to contact the owner in the manifest file. This owner would take care of redirecting the request to other people or teams if needed. Thinking on supportability I think it is valuable to have a single point of contact for each package.

> Could we change the package-spec to allow `owner` in the data_stream `manifest.yml` ?

> I agree, we should desire long-term support cases going to the right team based on an up-to-date CODEOWNERS for each data stream. It will be ideal, if CODEOWNERS is made auto-generated also.

As mentioned in other comment, take into account that this is not only about data streams. We already have packages where the dashboards are maintained by a team that is not the owner of the package. We would also need to add something for these directories.

> Or I suppose we could drop the `owner` field all together from `manifest.yml` and just use the `CODEOWNERS` file.

If we end up finding that the owner in the manifest doesn't provide any value on its own then I agree with this, I would rather have a single file than multiple of them that need to be synchronized.

**Comment by jsoriano** [comment]
> > > I'm mostly coming at this from a support perspective. If there is a problem with a data_stream, what is the algorithm (for a person that is external to the development process) to figuring out who to ask for help? In the past we have pointed at the 'owner' in the manifest.yml as a way to find a team to ask for help. But now people should probably parse the CODEOWNERS file?
> > 
> > 
> > I think that after this change the algorithm should still be to contact the owner in the manifest file. This owner would take care of redirecting the request to other people or teams if needed. Thinking on supportability I think it is valuable to have a single point of contact for each package.
> 
> I'm not in favor of this. Making a team a "support case router" adds latency to finding the right team and reduces capacity for the router team because of interrupts. While I _really_ love the idea of 'single point of contact', once you move development to multiple teams, that can independently approve their own work, you have lost the 'single point of contact'. I'd rather we move to making it more obvious what team is doing the development and thus is responsible for support.

Well, the "case router" would be the owner of the package, that is probably the most knowledgeable team about the package, and probably can quickly route to the most adequate person. When having an issue with a package, it may not be obvious what part of the package has the issue. Packages are seen as a single entity when installed and used.
If we have multiple ownership areas, with different points of contact, this is something users and support need to know, and they need to know how to identify the areas, look for the owners of each area and so on.

But well, if we have packages where this latency routing the issue is being a problem, we can definitely try to find a solution.

> > As mentioned in other comment, take into account that this is not only about data streams. We already have packages where the dashboards are maintained by a team that is not the owner of the package. We would also need to add something for these directories.
> 
> Awesome point. I think this means listing files in `kibana/dashboard` individually in CODEOWNERS. Right?

We could also list individual files, but currently we list the dashboard directories, like here: https://github.com/elastic/integrations/blob/41b6a7b45b994c49dc3d32baea4b29321f38897b/.github/CODEOWNERS#L25

**Comment by efd6** [comment]
> Awesome point. I think this means listing files in `kibana/dashboard` individually in CODEOWNERS. Right?

The issue with this is that dashboard files are almost always given opaque names, so knowing that a file ownership assignment is correct is not trivial.

**Comment by andrewkroh** [comment]
These a few more datasets that where I think SEI has mostly been the maintainer.

- aws.guardduty
- aws.securityhub_*
- gcp.audit
- gcp.dns
- gcp.firewall
- gcp.vpcflow
