### ISSUE TITLE
[Azure] [container_service] Review list of dimensions

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#7161]
Current configuration:
https://github.com/elastic/integrations/blob/main/packages/azure_metrics/data_stream/container_service/agent/stream/stream.yml.hbs#L91-L114

1. For pod specific metrics (like `kube_pod_status_ready`) the only used dimension is `pod`, that could be not enough in case the pod name is used in different namespaces.

Available [dimensions](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-containerservice-managedclusters-metrics) for those metrics (second last column):
<img width="892" alt="Screenshot 2023-07-27 at 10 43 35" src="https://github.com/elastic/integrations/assets/28299531/942b3b16-5fc0-4d17-aa0c-511d45dc72e2">

Both has `namespace`, not sure regarding `phase` and `condition` if they are needed

2.  `kube_node_status_condition` has as a dimension `status2` - not sure if it provides useful info

**Comment by tommyers-elastic** [comment]
the second to last column are all listed as dimensions in the azure docs, i think we should add them as such in our mappings.

**Comment by zmoog** [comment]
Yep, adding the missing dimensions would do.

**Comment by tetianakravchenko** [comment]
> can we close this one out @tetianakravchenko ?

@tommyers-elastic no, in the mentioned PR I've used only existing in configuration dimensions, but not extended current configuration with more dimensions
