### ISSUE TITLE
[Azure][compute_vm][compute_vm_scaleset] metrics `Azure.VM.Windows.GuestMetrics` and `Azure.VM.Linux.GuestMetrics` seems to be not available

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#7167]
`compute_vm` - current configuration - https://github.com/elastic/integrations/blob/main/packages/azure_metrics/data_stream/compute_vm/agent/stream/stream.yml.hbs#L100-L150 that includes `namespace: "Azure.VM.Linux.GuestMetrics"` and `namespace: "Azure.VM.Windows.GuestMetrics"`

Note: I've configured diagnostic settings on all monitored nodes as described in https://docs.elastic.co/integrations/azure_metrics/compute_vm#guest-metrics:
<img width="1148" alt="Screenshot 2023-07-27 at 17 10 49" src="https://github.com/elastic/integrations/assets/28299531/9ba3ee05-2dc1-41a5-b140-6db1e548bc72">

But I am not getting any metrics and also I see those elastic-agent errors:
```
no metric definitions were found for resource /subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Compute/virtualMachines/XXX and namespace Azure.VM.Windows.GuestMetrics. Verify if the namespace is spelled correctly or if it is supported by the resource in case.
```

the same for linux:
```
no metric definitions were found for resource /subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Compute/virtualMachines/XXXX and namespace Azure.VM.Linux.GuestMetrics. Verify if the namespace is spelled correctly or if it is supported by the resource in case.
```

For the `compute_vm_scaleset` I see the same behavior - error:
```
no metric definitions were found for resource /subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Compute/virtualMachineScaleSets/XXX and namespace Azure.VM.Windows.GuestMetrics. Verify if the namespace is spelled correctly or if it is supported by the resource in case.
```

I am missing a guidance how to get those metrics

**Comment by tetianakravchenko** [comment]
@zmoog @TomLawler could you help me with this?

**Comment by tetianakravchenko** [comment]
was fixed for the `compute_vm_scaleset` by: `Diagnostic settings` >  under `Sinks` > `Enable Azure Monitor`

**Comment by tommyers-elastic** [comment]
thanks tania! do you think the docs need improving here?

**Comment by tetianakravchenko** [comment]
@tommyers-elastic yes, the only documentation I found is this - https://docs.elastic.co/integrations/azure_metrics/compute_vm#guest-metrics

**Comment by zmoog** [comment]
@tetianakravchenko so the issue is resolved with these extra settings?

The docs are there, but it would be great if they were more precise and actionable.

**Comment by tetianakravchenko** [comment]
@zmoog 
> @tetianakravchenko so the issue is resolved with these extra settings?

yes, actually to be more precise required steps are:
- on vm resource under `Monitoring` > Install Diagnostics Extension
  - select `storage account` - you might need to create a `Diagnostics storage account` if does not exist already
  - enable guest-level monitoring
- `Diagnostic settings` > `Sinks` > `Enable Azure Monitor`
  note: to do so should be configured managed identity:
<img width="786" alt="Screenshot 2023-07-28 at 17 26 01" src="https://github.com/elastic/integrations/assets/28299531/510a22cb-848e-49e4-9f2f-5380143ed9f7">
