### ISSUE TITLE
Windows Integrations Different For the Same Log 100+ Differences

### ISSUE THREAD

**Issue by neu5ron** [elastic/integrations#7174]
1. Regex for Powershell Channel(s):

From Powershell Channel
https://github.com/elastic/integrations/blob/163fd962931aedd34cda8857df28d74a79ff1511/packages/windows/data_stream/powershell/elasticsearch/ingest_pipeline/default.yml#L264

From Forwarded Powershell Channel
https://github.com/elastic/integrations/blob/163fd962931aedd34cda8857df28d74a79ff1511/packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/powershell.yml#L240

)

I would imagine the first one is the correct one per commit: https://github.com/elastic/integrations/commit/75c6fada34f9c4f5b3b4fd81fceb574b8462dc54
Also winlogbeat uses this one as well.

Same is also true for Powershell_Operational Regex

2. 40 Differences for Security Channel
There are over 40 differences between the Security Channel log and the same log within the Forwarded Channel despite them being the same log.

3. 70 Differences for Sysmon Channel
There are over 70 differences between the Sysmon Channel log and the same log within the Forwarded Channel despite them being the same log.

**Comment by efd6** [comment]
@neu5ron Can you provide examples for 2. and 3.?

**Comment by neu5ron** [comment]
2. sysmon
just compare these two files
[non forwarded](https://github.com/elastic/integrations/blob/main/packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml)
[forwarded](https://github.com/elastic/integrations/blob/main/packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml)



3. sysmon
just compare these two files
[non forwarded](https://github.com/elastic/integrations/tree/main/packages/windows/data_stream/sysmon_operational)
[forwarded](https://github.com/elastic/integrations/blob/main/packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/sysmon_operational.yml)

**Comment by efd6** [comment]
@neu5ron I have made changes to handle the cases in powershell, powershell_operational, and sysmon_operational. The case of security is between the system package and the windows package, so it's not so clear that they need to be reconciled. I will take a look.

**Comment by neu5ron** [comment]
awesome! thank you!
so the system security is the windows security channel - it's definitely confusing given the pipeline names - but in the details, they are both the same

**Comment by efd6** [comment]
This is done.
