### ISSUE TITLE
[FortiMail] Add parsing for "authserver" system/kevent logs

### ISSUE THREAD

**Issue by eriroley** [elastic/integrations#7180]
This is a feature request for the FortiMail integration - there is currently no parsing done on events that match "type: kevent" and "sub_type:system", specifically for 'authserver' events
This includes messages where the fortimail is applying a timed block because of failed login attempts.

examples include (privacy modified versions of event.original - serial number has been obfuscated x=alpha n=numeric, IP addresses have been replaced with RFC5737 IP addresses):

```
<191>date=2023-07-28,time=04:48:36.567,device_id=FEVM02xxnnnnnn,log_id=0702001939,type=kevent,subtype=system,pri=debug, user=,ui=,action=none,status=none,msg="authserver: removed block rule for 192.0.2.57"

<191>date=2023-07-28,time=05:07:20.426,device_id=FEVM02xxnnnnnn,log_id=0702001941,type=kevent,subtype=system,pri=debug, user=,ui=,action=none,status=none,msg="authserver: added block rule for 192.0.2.94 until 2023-07-28 05:57 -0400"

<191>date=2023-07-28,time=03:58:41.726,device_id=FEVM02xxnnnnnn,log_id=0702001941,type=kevent,subtype=system,pri=debug, user=,ui=,action=none,status=none,msg="authserver: added block rule for 192.0.2.155 until 2023-07-28 04:48 -0400"
```

I note that log_id is parsed as event.code, and for these exampled, the event.code does indicate what type of action is being taken (0702001941 indicates a new timed block is applied, 0702001939 indicates that it is being removed)

Ideally I would like to have a minimum of the action and the IP address parsed (this will allow me to better search my logs for failed login attempts, and correlate with SIEM, and submit automatically to threat feeds)

Thank You

**Comment by efd6** [comment]
@eriroley Please take a look at #7191 to check whether that satisfies the requirements.

**Comment by eriroley** [comment]
That looks wonderful!

Thank You
