### ISSUE TITLE
[Azure] [Docs] Expand Azure VM Guest Metrics documentation

### ISSUE THREAD

**Issue by zmoog** [elastic/integrations#7181]
The Azure Virtual Machines Metrics documentation contains a section about the [Guest Metrics](https://docs.elastic.co/integrations/azure_metrics/compute_vm#guest-metrics). 

It is great it's here, but I believe we should expand it a little and make it more actionable for the users, like:

- Which section of the Azure Portal to visit
- Step by step instructions of what to enable
- Link to pages with additional information

Relates:

- #7167

**Comment by alaudazzi** [comment]
@zmoog 
As discussed on Friday Dec 1, here is a [draft with the doc fix](https://docs.google.com/document/d/1ZxnbuLORPOb8R1GHyl8dCSvhsJiOFuWCmoRVHLsCBUM/edit). As soon as you give me your 👍I'll push a doc PR.
