### ISSUE TITLE
Defend for Containers — is it beta or GA?

### ISSUE THREAD

**Issue by bmorelli25** [elastic/integrations#7197]
### Summary

Our documentation build determines the release status of an integration from the `release` field in `manifest.yml`. An example can be seen here: 

https://github.com/elastic/integrations/blob/f659da9bcafdbedc80dffd8a52bc33d359c35ffa/packages/linux/manifest.yml#L10

Defend for Containers does not currently specify a release status, and our doc build therefore assumes it is "Generally Available." The description however states that the integration is in beta:

https://github.com/elastic/integrations/blob/f659da9bcafdbedc80dffd8a52bc33d359c35ffa/packages/cloud_defend/manifest.yml#L7

This will likely lead to confusion when users look at our documentation on docs.elastic.co.

### Recommended resolution

Can the dev team either:

- **A**. Add `release: beta` to the `manifest.yml` file, or
- **B.** Remove `beta` from the description string

Thank you!

cc @norrietaylor

**Comment by norrietaylor** [comment]
Hi @bmorelli25,

I agree that the current state is confusing for users; however, the integration is in a beta state, **and** we cannot mark it as such in the release field. 

Although we only intend to support this as a beta offering, the product requirements included a requirement to link to the integration from the Security -> Management page in Kibana. Integrations marked as beta can not fulfill this requirement. @mitodrummer can elaborate more on the technical details of this limitation. 

During development of the integration, we discussed this limitation with the Cloud Security product manager leading this effort and placing "(BETA)" in the descriptions was the agreed-upon compromise. 

This should be a temporary state, as we have intentions of making this a GA integration in an upcoming release. cc/ @nick-alayil for further information.

**Comment by bmorelli25** [comment]
Thanks for the information. I assumed this was just an oversight, but it sounds like considerable thought has gone into this already. I'll close this issue.
