### ISSUE TITLE
[Azure] [container_service] Handle boolean values

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#7220]
<img width="562" alt="Screenshot 2023-08-02 at 15 12 38" src="https://github.com/elastic/integrations/assets/28299531/d3a04b0e-70c4-4f9f-b390-f7d743ea0455">

It seems that Azure API return either `false` or `False` and we send it to elasticsearch without modification.

cc @tommyers-elastic @zmoog fyi

**Comment by zmoog** [comment]
We should add a processor and pick just one of the two formats. 

A few questions:

1. Any idea about which format to use (upper- or lowercase)?
2. During your tests, did you see value other than these boolean-ish values?
3. Are you [planning](https://github.com/elastic/integrations/pull/7139/files#r1281896354) to drop this field from the TSDB dimensions?

**Comment by tetianakravchenko** [comment]
> We should add a processor and pick just one of the two formats.

I was thinking on processing it on the beats side to lower/upper case instead

> Any idea about which format to use (upper- or lowercase)?

I would use lowercase

> During your tests, did you see value other than these boolean-ish values?

no, only `True`/`true`/`False`/`false`

> Are you [planning](https://github.com/elastic/integrations/pull/7139/files#r1281896354) to drop this field from the TSDB dimensions?

yes, I did it in this commit - https://github.com/elastic/integrations/pull/7139/commits/2ce9f5cc6739d69dae1f3ec2022cc48d78ef0f7d

**Comment by zmoog** [comment]
> I was thinking on processing it on the beats side to lower/upper case instead

You mean using a beats processor or change the metricset code?

**Comment by tetianakravchenko** [comment]
> > I was thinking on processing it on the beats side to lower/upper case instead
> 
>You mean using a beats processor or change the metricset code?

metricset code, at the place where the metrics are actually fetched

**Comment by zmoog** [comment]
> > > I was thinking on processing it on the beats side to lower/upper case instead
> > 
> > 
> > You mean using a beats processor or change the metricset code?
> 
> metricset code, at the place where the metrics are actually fetched

What are the pros of this approach vs. normalising this field value in a pipeline or beat processor?

**Comment by zmoog** [comment]
@tetianakravchenko, I added a pipeline processor to avoid mixed cases values True/true/False/false. With the previous PR, we'll only have `true` or `false` values.
