### ISSUE TITLE
Elastic Agent Integration - we can add more clarity to the overview notes section on what this is and how it relates to Elastic Agent overall

### ISSUE THREAD

**Issue by EricDavisX** [elastic/integrations#723]
we got feedback from a CSM that it wasn't clear.  So I'm putting a ticket in so we can review and improve it.

The note that caught their attention was that... the Integration says it is "only to monitor itself" and the implication was taken to apply that to all of the Elastic Agent functionality.  It is confusing because we have Elastic Agent and then an Elastic Agent integration.

However it is best to impart this, we probably want to inform that this specific integration is in fact for monitoring the Elastic Agent, but that note is not meant to imply that monitoring the Agent process is all that Elastic Agent can do.  

![elastic-agent-integration](https://user-images.githubusercontent.com/12970373/108235531-e5e15800-7113-11eb-80aa-f65c14d862e4.png)

**Comment by ph** [comment]
@mostlyjason Can you work with @nchaulet to improve the description of this integration?

**Comment by mostlyjason** [comment]
@nchaulet did you follow the guidelines for creating this package and dashboards? https://github.com/elastic/obs-dc-team/blob/master/development/generic_guidelines.md https://github.com/elastic/integrations/issues/269. For example, I don't see a screenshot of the dashboards. The process table also looks like it has a markdown error.

CC @sorantis in case there are other guidelines we should follow

Also, does this integration add any inputs or is it just assets? Is it a default package?

**Comment by ph** [comment]
It currently just add assets.

@mostlyjason in 7.13 we want to make it a default package like system.

**Comment by ph** [comment]
@mostlyjason Currently It only contains dashboard, Maybe we could write something like this.

```
The Elastic Agent integration is a default integration that contains the dashboards required to visualize the monitoring information of a running Elastic Agent and the running processes. The integration will be automatically updated on every new release of the stack.

**Comment by mostlyjason** [comment]
How about this?

`The Elastic Agent integration is a default integration that contains the dashboards required to visualize the monitoring information of a running Elastic Agent and the running processes. It does not need to be added to agent policies. The integration will be automatically updated on every new release of the stack.`

This is another good example for this use case https://github.com/elastic/kibana/issues/96525
