### ISSUE TITLE
[O11y] [Azure Application Insights] Lens Migration

### ISSUE THREAD

**Issue by milan-elastic** [elastic/integrations#7231]
Manually migrate `Azure Application Insights` visualizations to the lens in the current Kibana version <TBD> itself. 

## Preparation of data for testing
- [x] Use sample_event.json / setup live instance using docker / mock data using a mock server to populate dashboards 

## Migration stats
<html>
<body>
<p data-renderer-start-pos="1" style="margin: 0px; padding: 0px; font-size: 14px; line-height: 1.714; font-weight: 400; letter-spacing: -0.005em; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-wrap; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Migration Stats:</p><div class="pm-table-container " data-layout="default" style="margin: 0px auto 16px; padding: 0px; position: relative; box-sizing: border-box; clear: both; z-index: 0; transition: all 0.1s linear 0s; display: flex; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-wrap; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: inherit;"><div class="pm-table-wrapper" style="margin: 0px; padding: 0px; overflow-x: auto;">

  | Before Migration |  | After Migration |  | 
-- | -- | -- | -- | -- 
Dashboad Name | Lens | Visualization | Lens | Visualization
[Logs Azure] App State Overview | 10 | 1 | 11 | 0

</div></div>
</body>
</html>

## Dashboard : [Azure Metrics] App State Overview
  - [x] Migrate  visualization to the lens.
    - https://github.com/elastic/integrations/pull/8379

## Verification and Validation
  - [x] Verification of functionality remains the same after migration in Kibana
  - [x] Verification of data count of after-migrated visualization with before-migrated visualization in Kibana
  - [x] Verification of Dashboards is not distorted in the supported Kibana version (TBD)

**Comment by rajvi-elastic** [comment]
Application insights Lens migration task is blocked due to this issue: https://github.com/elastic/integrations/issues/7259

**Comment by rajvi-elastic** [comment]
Changing type from flattened to object resolves the dashboard issue. 
![image](https://github.com/elastic/integrations/assets/124889398/2636acf5-ac5f-4814-9c5a-56a1a8c3f777)

Dashboards are not showing any error after updating data type!
![image](https://github.com/elastic/integrations/assets/124889398/f8db0432-6947-4f66-8cec-69e87d448248)
