### ISSUE TITLE
[docs] Change the details surrounding the Logs configuration to not use LocalHost in the vSphere Integration docs

### ISSUE THREAD

**Issue by brenwie** [elastic/integrations#7244]
In the 'Logs` section of the  [vSphere Integration](https://docs.elastic.co/integrations/vsphere#logs) we specify

> To access the logs, host address (localhost) and host port (9525) needs to be passed in Kibana UI.

This is a bit confusing as using `localhost` will not work when the Elastic Agent acts as a remote syslog server. Using `localhost` will bind port `9525` to the `127.0.0.1` IP address which is a loopback address used for internal communication and not accessible remotely.

By simply changing this value to `0.0.0.0` in the vSphere integration, meaning that port `9525` will be bound to all network interfaces available on that host, you will be able to remotely access port `9525` on the host where you have the Elastic Agent deployed with the vSphere Integration which will allow VMware to successfully connect and forward logs to the Elastic Agent for ingestion into Elasticsearch. 

Furthermore, to improved security, you should **rather specify the host's network-accessible IP address** instead of using the `0.0.0.0` option. Bear in mind, if the IP address of the Elastic Agent host changes, the configuration of the vSphere Integration would need to be updated accordingly. 

Therefore the use of `localhost` should not be an option.  Rather specify the network-accessible IP address of the host where the Elastic Agent will be deployed

**Comment by alaudazzi** [comment]
@brenwie I'll fix the docs as we discussed over Slack. A doc PR will follow.
