### ISSUE TITLE
[GCP Billing] Update Legacy metrics in GCP Billing overview dashboard

### ISSUE THREAD

**Issue by rajvi-patel-22** [elastic/integrations#7252]
## Description

Update Legacy metric visualization to new metric visualization according to best practice.

## Screenshot
![image](https://github.com/elastic/integrations/assets/124889398/715927b1-6ebc-4719-b3a4-2ff98dd5cda1)

**Comment by harnish-elastic** [comment]
Closing issue as completed in this PR https://github.com/elastic/integrations/pull/8404
