### ISSUE TITLE
[O11y][GCP VPC Flow] Lens Migration

### ISSUE THREAD

**Issue by rajvi-elastic** [elastic/integrations#7258]
Manually migrate GCP `VPC Flow` visualizations to the lens in the current Kibana version `8.7.1` itself. 

## Preparation of data for testing
- [x] Use sample_event.json / setup live instance using docker / mock data using a mock server to populate dashboards 

## Migration stats
<html>
<body>

  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Vizualization | Lens | Vizualization
[Logs GCP] VPC Flow | 9 | 6 | 9 | 6

</body>
</html>

## Dashboard : [Logs GCP] VPC Flow
  - [ ] Migrate 6  visualization to lens
    - PR Link

## Verification and Validation
  - [x] Verification of functionality remains the same after migration in Kibana
  - [x] Verification of data count of after-migrated visualization with before-migrated visualization in Kibana
  - [x] Verification of Dashboards is not distorted in the supported Kibana version (TBD)

**Comment by kush-elastic** [comment]
VPC Flow dashboard contains 6 Vega visualization which can not be migrated to lens:

![image](https://github.com/elastic/integrations/assets/124889398/782c3f5b-06b4-4e90-a46b-91f165419d99)

**Comment by rajvi-elastic** [comment]
The Vega visualizations uses Vega library which enables user to create custom visualizations. Hence, these visualizations can not be migrated to lens.
