### ISSUE TITLE
[Azure] Azure app state overview dashboard contains flattened data type

### ISSUE THREAD

**Issue by rajvi-elastic** [elastic/integrations#7259]
## Description

The `App State Overview` dashboard is using `azure.dimensions.*` field which have flattened data type. Flattened data type can not be used in dashboards hence it showing **field not found error**.
![screencapture-localhost-59173-app-dashboards-2023-08-04-17_12_59](https://github.com/elastic/integrations/assets/124889398/525f42bb-8476-4412-8402-81407e167da8)

**Comment by rajvi-elastic** [comment]
Runtime field with painless script can be used to visualize data of a flattened type in lens. But runtime fields degrades the performance and doesn't provide best user experience https://github.com/elastic/kibana/issues/25820#issuecomment-1588266181.

**Comment by agithomas** [comment]
@rajvi-elastic , please check if the issue is resolved with this PR : https://github.com/elastic/integrations/pull/7550?

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic , please check if the issue is resolved with this PR : #7550?

Yes @agithomas, Dashboard is not showing any error:
![image (6)](https://github.com/elastic/integrations/assets/124889398/1ab2ae96-efed-4785-839e-3dd6cf5a0aeb)

**Comment by agithomas** [comment]
Great, hope you can close the issue and soon complete the migration.

**Comment by rajvi-elastic** [comment]
> Great, hope you can close the issue and soon complete the migration.

I will close the issue and start working on lens migration once [PR](https://github.com/elastic/integrations/pull/7550) gets merged.

**Comment by agithomas** [comment]
> I will close the issue and start working on lens migration once [PR](https://github.com/elastic/integrations/pull/7550) gets merged.

The PR is merged.

**Comment by rajvi-elastic** [comment]
This issue has been resolved by [PR](https://github.com/elastic/integrations/pull/7550)
