### ISSUE TITLE
perform and service metrics not generated for windows agent when having Linux and windows integration in agent policy 

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#726]
**Build:** 7.11.1 snapshot staging build
**OS:** windows 10 pro

Integration details:
"Linux" integration Version 0.3.7
"windows" Version 0.3.1

On installing agent using a policy having on windows and Linux integration only on Windows x64 bit, we observed that:
- perform and service metrics not generated on data stream page for windows 10x64 bit agent.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/108356581-52db1780-7212-11eb-8221-0930335528e7.png)

**Build details:**
```
BUILD 37947
COMMIT b8ce8c202dff437413cdd01d5ba956bfa41bb8af
artifact link: https://snapshots.elastic.co/7.11.1-16d3597f/downloads/beats/elastic-agent/elastic-agent-7.11.1-SNAPSHOT-windows-x86_64.zip
```

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by dikshachauhan-qasource** [comment]
@EricDavisX , When we reported defects, at that time, metricbeat error was logged in AGgnts logs. Later after more than an hour of time span, metricbeat service resumes it state to running on continuous hitting in backend[as per logs] and agent comes back to healthy state. Thus further, generating Windows.perform and service metrics data events on data set page.
 
We have same observations yesterday with Mac agent that metricbeat comes to running state after almost an hour and shared it under https://github.com/elastic/beats/issues/23996 .MAC OS used was Apple Mac OS X 10.12 (64-bit)

We have observed that this behavior is ON and OFF. Sharing a screenshot below:

**Screenshot:**

![image](https://user-images.githubusercontent.com/72375798/108377096-b0c72980-7229-11eb-9c38-b25661599807.png)


**Window Agent Logs from Endpoint to trace exact timelines:**
[elastic-agent-json.log](https://github.com/elastic/integrations/files/6003824/elastic-agent-json.log)


**Integration details:**
"Linux" integration Version 0.3.7
"windows" Version 0.3.1

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource can you confirm explicitly the intent of the bug... I believe you are reporting that the functionality works when NOT combined together and only fails when the 2 Integrations are in use in the same Agent policy. Just confirming if this is the case, thank you

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

It is working fine when we are using just windows or [System+Windows] package in Agent policy. This issue is only occurring when Linux combinations are used in Agent policy like:
- Windows + Linux
- Windows + Linux + System

Thanks
QAS

**Comment by fearful-symmetry** [comment]
`0.3.8` should be available in staging. Can we re-test with that version?

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX cc @fearful-symmetry 

We have revalidated this issue on 7.11.1 snapshot Kibana cloud build having Linux package version 3.8 and found issue as **Fixed**.

- perform and service metrics are generated for windows agent when having Linux and windows integration in agent policy
- No error in metricbeat logs under Agents tab when 'linux' Integration is used in agent policy. 
- Agent is in healthy state.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/108810509-4a4b5e00-75d1-11eb-9135-afaba187837e.png)


**Build details:**
```
BUILD 37947
COMMIT b8ce8c202dff437413cdd01d5ba956bfa41bb8af
Artifact link: https://snapshots.elastic.co/7.11.1-16d3597f/downloads/beats/elastic-agent/elastic-agent-7.11.1-SNAPSHOT-windows-x86_64.zip
```

Hence, closing this issue.

Thanks
QAS
