### ISSUE TITLE
[Docs]: improve clarity when adding/editing windows integration.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#727]
**Build**: 7.11.1 Snapshot staging cloud build

**Steps to reproduce:**
1. login to Kibana fleet UI.
2. Go to Integrations. Search for 'windows' integration.
3. Click on 'add windows' button.
4. Scroll down the page to 'Collect Windows perfmon and service metrics'

**Actual result:** 
- Perform spelling mistakes in heading 'Collect Windows perfmon and service metrics'
- expand the section again observe spell error for word 'perform'
- On data stream page, windows.perfmom' is getting displayed.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/108358222-77d08a00-7214-11eb-9464-fa87c1abf5bf.png)

**Build details:**
```
BUILD 37947
COMMIT b8ce8c202dff437413cdd01d5ba956bfa41bb8af
artifact link: https://artifacts-api.elastic.co/v1/search/7.11.1-SNAPSHOT
```

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by EricDavisX** [comment]
Thanks Diksha, I think perfmon is a shortened windows terminology for 'performance monitor' - see the reference in this windows doc page: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/set-up-performance-counters-performance-monitor

I don't think it is a mistake here - if it says it differently somewhere like 'perform' then that *may be a bug.

**Comment by mtojek** [comment]
Actually I would consider this as a bug as the official name is "Windows Performance Monitor", "perfmon" seems to be more like a slang.

**Comment by dikshachauhan-qasource** [comment]
HI @EricDavisX 

Thanks for the confirmation. As per above feedback, we are closing this out. And will report new bug if found 'perform' instead of 'perfmon'  at any place in the application.

Thanks
QAS

**Comment by EricDavisX** [comment]
I know that some of the content in the display comes directly from the field names and if they are released already it requires more work / decisions to correct them.  I will let the Integration owner review and comment.  Thanks

**Comment by masci** [comment]
@narph @sorantis can you chime in?

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

Thanks for the update.

We will be waiting for further updates on reported issue.

Thanks
QAS

**Comment by narph** [comment]
`perfmon` is the name of the metricset (in Metricbeat)/data stream (in the windows integration), comes from `Performance Monitor` tool in Windows. We could replace it to `performance monitor` .. metrics instead for more clarity.
