### ISSUE TITLE
Enhance Windows Integration: Save winlog.event_data.Details to ECS Field

### ISSUE THREAD

**Issue by Harmlos** [elastic/integrations#7310]
"Within the Windows integration in the ingest pipeline, we have several processors, and one of them deletes certain non-ECS fields from the event. One of these deleted fields is actually useful.

In our installations, we modify the ingest pipeline 'logs-windows.sysmon_operational-XX.YY.ZZ' after each update. We only need to add a single SET processor before the Delete processor. Here's the required addition to the following file:

/packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml

``` json
{
    "set": {
      "field": "winlog.event_data.Detail",
      "copy_from": "winlog.event_data.Details",
      "ignore_failure": true
    }
}
```
Before processor:
``` json
  {
    "remove": {
      "field": [
        "_temp",
        "winlog.event_data.ProcessId",
        "winlog.event_data.ParentProcessId",
        "winlog.event_data.SourceProcessId",
        "winlog.event_data.SourceThreadId",
        "winlog.event_data.SourceIp",
        "winlog.event_data.SourcePort",
        "winlog.event_data.SourcePortName",
        "winlog.event_data.DestinationIp",
        "winlog.event_data.DestinationPort",
        "winlog.event_data.DestinationPortName",
        "winlog.event_data.RuleName",
        "winlog.event_data.User",
        "winlog.event_data.Initiated",
        "winlog.event_data.SourceIsIpv6",
        "winlog.event_data.DestinationIsIpv6",
        "winlog.event_data.QueryStatus",
        "winlog.event_data.Archived",
        "winlog.event_data.IsExecutable",
        "winlog.event_data.QueryResults",
        "winlog.event_data.UtcTime",
        "winlog.event_data.Hash",
        "winlog.event_data.Hashes",
        "winlog.event_data.TargetObject",
        "winlog.event_data.Details",
        "winlog.time_created",
        "winlog.level"
      ],
      "ignore_failure": true,
      "ignore_missing": true
    }
  },

```

Unfortunately, we cannot use a custom ingest pipeline, as the data is completely removed within the managed ingest pipeline."

**Comment by efd6** [comment]
@Harmlos Is there a reason not to just remove that field from the `remove` processor? ISTM that leaving the field as the name used by Windows, i.e. `Details`, would be preferable.

**Comment by Harmlos** [comment]
@efd6  Using the field from the ECS schema offers advantages, such as an existing mapping that aligns with its intended meaning. This approach eliminates the need to modify the Index Template.

Furthermore, this particular field is solely mapped from sysmon messages. Consolidating both 'Detail' fields into one enhances clarity and reduces redundancy.

**Comment by efd6** [comment]
@Harmlos That's not what I was asking. The change above does not move the field to an ECS field, it effectively renames it from `winlog.event_data.Details` to `winlog.event_data.Detail` via a copy/delete. If the `winlog.event_data.Details` line were removed from the the `remove` processor then the field would still be available, and would be under a name that is consistent with how it is named by Microsoft in the event.
