### ISSUE TITLE
Use integration to monitor the elastic cluster?

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/integrations#733]
Hi all,
first of all: WOW! I was out of elastic for a time and what happened since then, is just amazing. The elastic agent and fleet stuff is just awesome! I just started to try it out and I can't stop smiling. You are making an Admin very happy!!!

So I just built up a new cluster based on 7.11.1. On the monitoring page, I get the notice, that I am using internal detection monitoring. That's true, as I did not install any beat yet. I installed the agent on every node and then wanted to create a policy for Elastic/Kibana Integrations. But I couldn't find any. Are there no elasticsearch-xpack / kibana-xpack for the "internal" monitoring yet? 

Cheers!
Marcus

**Comment by andresrc** [comment]
Thanks @MarcusCaepio , integrations for ES / Kibana are planned, I cannot provide a specific timeline yet.

**Comment by masci** [comment]
Hi @MarcusCaepio 

the work to port cluster monitoring for kibana and es to the new ingestion experience based on agent and integrations is tracked here:

- https://github.com/elastic/integrations/issues/368
- https://github.com/elastic/integrations/issues/367

I'm going ahead closing this but feel free to subscribe to those issues and contribute with comments or questions.
