### ISSUE TITLE
[TI_CIF3] Add support for IOC expiration

### ISSUE THREAD

**Issue by kcreddy** [elastic/integrations#7358]
Individual tracking issue for `ti_cif3` package for adding IOC expiration support.
Meta Issue - https://github.com/elastic/integrations/issues/5369

**Comment by kcreddy** [comment]
We currently have 1 datastream `feed` which use the CIFv3 API `/feed` documented [here](https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/REST-API#parameters:~:text=%22GET%20/feed%22%3A%20%22filter%20for%20a%20data%2Dset%2C%20aggregate%20and%20apply%20respective%20whitelist%22%2C) with parameters such as `itype`, `confidence`, `tags`, `hours`, `reporttime` to fetch only relevant filtered indicators since last reported time. 

This repository which supports the v3 API is now archived. There is also a CIFv5 that is available at https://github.com/csirtgadgets/cif-v5
None of the [v3 API](https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/REST-API#parameters) or [v5 API](https://github.com/csirtgadgets/cif-v5/wiki/REST-API) have documentation which provides information on indicator expiration. I created an issue on their reposiroty to confirm it.

Issue - https://github.com/csirtgadgets/cif-v5/issues/43

**Comment by jamiehynds** [comment]
@mdavis332 I know it's been awhile since you built the integration, but do you have any familiarity with the CIFv5 API and how it handles IoC expiration?

**Comment by mdavis332** [comment]
> @mdavis332 I know it's been awhile since you built the integration, but do you have any familiarity with the CIFv5 API and how it handles IoC expiration?

Hi @jamiehynds, I see that Wes already replied to @kcreddy's issue at https://github.com/csirtgadgets/cif-v5/issues/43. Although his answer his for CIFv5, it's mostly the same for CIFv3. The `/feed` endpoint handles [looking back a certain number of days automatically based on itype](https://github.com/csirtgadgets/bearded-avenger/blob/master/cif/httpd/views/feed/__init__.py#L43-L59) if a `reporttime` field isn't specified during the indicator feed pull. Therefore, each pull will only ever yield indicators from that `reporttime` or forward and there's no explicit expiry field in the schema (the clients get to handle how far back they want to pull indicators for).

Hope that helps!

**Comment by kcreddy** [comment]
Thanks @mdavis332 for the info.
Yes we are using `reporttime` in the url parameter and fetching the latest indicators since previous `reporttime`.
Since there is no explicit expiry field here, we will go with Wes suggestion on the defaults provided: https://github.com/csirtgadgets/cif-v5/issues/43#issuecomment-1674988424
