### ISSUE TITLE
Wrong mappings in Apache Integration "apache.error" (7.11.1)

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/integrations#736]
Hi all,
It seems, there is a wrong mapping of the fields source.ip and source.port for the apache error logs integrations.
I just enabled the intgeration for 2 hosts and getting Mapping Conflicts:
![image](https://user-images.githubusercontent.com/7324088/108636782-d3567e00-7487-11eb-86ff-4854caf3b1d4.png)
![image](https://user-images.githubusercontent.com/7324088/108636792-e79a7b00-7487-11eb-8414-c854538a7864.png)

Cheers,
Marcus

**Comment by mtojek** [comment]
I think we can change the field type to "long" in `apache.error` and release new package revisio.

BTW I'm not sure how will Kibana behave when the user decides to upgrade the package and mappings. @ruflin?

**Comment by MarcusCaepio** [comment]
Please note, it is not only source.port. It is source.port and source.ip, which has wrong mappings.

**Comment by ruflin** [comment]
As soon as the package is updated and assuming the type is not compatible, fleet will roll over the data streams. So this should work.

**Comment by MarcusCaepio** [comment]
One question to this: Will the fix be automatically available in my cluster via auto update of the integrations or do I have to do anything, to get it (e.g. updating the cluster) ?
Thanks for the fast fix!
