### ISSUE TITLE
[TI_Rapid7_Threat_Command] Add support for IOC expiration

### ISSUE THREAD

**Issue by kcreddy** [elastic/integrations#7360]
Individual tracking issue for `ti_rapid7_threat_command` package for adding IOC expiration support.
Meta Issue - https://github.com/elastic/integrations/issues/5369

**Comment by kcreddy** [comment]
No publicly available documentation is found on how `rapid7_threat_command` handles expiration. Below analysis is assumed looking at the sample logs (which must be confirmed with Rapid7).

Currently, we only have 3 datastreams `ioc`, `alert`, and `vulnerability` that we support. 
Among them, only the datastream `ioc` contains the indicator data which uses the API `https://api.intsights.com/public/v2/app/elastic/iocs`. Looking at the sample logs for this API, the indicator response contains the field `status`. The possible values are `Active` and `Retired`.

**Approach:**

- Whenever the document comes in with `status` as `Retired`, we can add a new field `retired_at` with value `now()`. **Must be confirmed with Rapid7 if indicator being updated to `Retired` status is available via the API or not.**
- Use this `retired_at` field inside transform for retention policy with `max_age` as `1m` so the expired indicator is immediately deleted in the destination index.

**Comment by kcreddy** [comment]
@P1llus Its been a long time since this integration shipped its own rules and provided documentation to users on how to setup transforms. I would like to conform this integration with other TI integrations and added below analysis. Let me know WDYT.

------

This Rapid7 integration is different from the rest of Threat Intel integrations in the sense that it ships custom rules for Threat Indicator Matches and also CVE matches. It also provides documentation on API calls to add transforms and make use of the the custom rules to create correlation indices which are later used by the dashboards.

The following changes can be applied to the integration to make it more streamlined and conform with other Threat Intel integrations. 
Each numbered item indicates what currently exist and the _subsequent point_ highlights the change to be made.

#### `ioc` datastream:
1. [A latest transform `ti_rapid7_threat_command_unique_ioc_transform`](https://github.com/elastic/integrations/tree/main/packages/ti_rapid7_threat_command/docs#:~:text=Create%20a%20transform%20for%20unique%20IOCs) from source `ioc` datastream into `rapid7-tc-unique-iocs` indices. This is provided in the README. There is no retention period specified in the transform.
    - _This latest transform can be shipped inside the package. The retention can be based on [above approach](https://github.com/elastic/integrations/issues/7360#issuecomment-1674613902) or defaulted to user-configurable value._
2. [Shipped dedicated rule](https://github.com/elastic/integrations/blob/main/packages/ti_rapid7_threat_command/kibana/security_rule/af814670-3279-11ed-93fa-d354b323cd1b.json) for indicator matches from `rapid7-tc-unique-iocs` indices.
    - _This rule can be deleted. Instead the 4 prebuilt Indicator Match Rules should suffice._
3. [Another latest transform `ti_rapid7_threat_command_ioc_rule_transform`](https://github.com/elastic/integrations/tree/main/packages/ti_rapid7_threat_command/docs#:~:text=Create%20a%20transform%20for%20IOC%20detection%20rule) for storing indicator correlations (based on above rule matches). Runs on source `.internal.alerts-security.alerts*` indices into `rapid7-tc-ioc-correlations` indices.
    - _This transform is only for dashboards usage in below step. This can be deleted_
4. Dashboards for IOC correlations using `rapid7-tc-ioc-correlations` indices.
    - _These dashboards can be deleted. [`Security Alerts`](https://www.elastic.co/guide/en/security/current/visualize-alerts.html) view should give a decent picture of these IOC correlations i.e., matches found by the prebuilt  Indicator Match rules._

#### `alert` datastream:
1. A latest transform from source `alert` datastream into `rapid7-tc-unique-alerts` indices to keep only the latest alerts.
   - _This latest transform can be shipped inside the package. The retention can be based on a user-configurable value._

#### `vulnerability` datastream:
1. [A latest transform `ti_rapid7_threat_command_unique_cve_transform`](https://github.com/elastic/integrations/tree/main/packages/ti_rapid7_threat_command/docs#:~:text=Create%20a%20template%20for%20unique%20CVEs%20index) from source `vulnerability` datastream into `rapid7-tc-unique-cves` indices. This is provided in the README. The retention period specified in the transform is `180d`.
    - _This latest transform can be shipped inside the package. The retention can be based on a user-configurable value defaulted to `180d`._
2. [Shipped dedicated rule](https://github.com/elastic/integrations/blob/main/packages/ti_rapid7_threat_command/kibana/security_rule/eaecc8f0-6704-11ed-80b2-9bbc46f73b72.json) for vulnerability matches from `rapid7-tc-unique-cves` indices.
    - _We don't have a prebuilt rule that matches all CVEs/vulnerabilities. Hence this rule must be present._
3. [Another latest transform `ti_rapid7_threat_command_cve_rule_transform `](https://github.com/elastic/integrations/tree/main/packages/ti_rapid7_threat_command/docs#:~:text=Create%20a%20transform%20for%20CVE%20detection%20Rule) for storing CVE correlations (based on above rule matches). Runs on source `.internal.alerts-security.alerts*` indices into `rapid7-tc-cve-correlations` indices.
    - _This transform is for dashboards usage in below step. This can be deleted._
4. Dashboards for IOC correlations using `rapid7-tc-ioc-correlations` indices.
    - _These dashboards can be deleted. [`Security Alerts`](https://www.elastic.co/guide/en/security/current/visualize-alerts.html) view should give a decent picture of these CVEs correlations i.e., matches found by the custom CVE rule in step 2._

**Comment by P1llus** [comment]
I don't have any strong opinions as to why we shouldn't do it, and it certainly would make the integration better and easier to manage!

I believe the discussion on removing the included rules is something we have had a few times, but never got around to doing it, so that would be a 👍 from me at least.

Together with those changes, the updates to the documentation should maybe have some notes around this, if you are removing the old docs for the manual implementation, for anyone that might revisit the docs and see its gone would be confusing.

I guess outside of my own opinion, I would say its good to do a test run on how the upgrade process would affect current users, as dashboards etc would also be removed, and I assume that users would then be running their manual transforms + these new transforms?

Do the transforms have the same setup as the other TI packages in terms of their destination index name etc?

**Comment by kcreddy** [comment]
>  I would say its good to do a test run on how the upgrade process would affect current users, as dashboards etc would also be removed, and I assume that users would then be running their manual transforms + these new transforms?

This certainly is the case and requires testing. I will add a bunch of notes inside README documenting what is missing starting this new version and its alternative and also a link to previous version docs. 

> Do the transforms have the same setup as the other TI packages in terms of their destination index name etc?

The current version's transform names and its destination index names are not aligned with what we are using for other TI package transforms. So that should prevent from creating duplicate alerts in case of an upgrade.

**Comment by jamiehynds** [comment]
@approksiu we are making some enhancements to this integration to support IoC expiration. It's an unusual package, in that Rapid7 included some detection rules with the package. We are planning on removing some of the rules that ship with the package, as our indicator match rules are a better fit. However, there's one rule relating to vulnerabilities from Rapid7. Do you think we could look at shipping a similar rule out-of-the-box?

**Comment by approksiu** [comment]
@jamiehynds it is possible, @terrancedejesus could you take a look at this please?

**Comment by kcreddy** [comment]
Hey @terrancedejesus, this is the rule https://github.com/elastic/integrations/blob/main/packages/ti_rapid7_threat_command/kibana/security_rule/eaecc8f0-6704-11ed-80b2-9bbc46f73b72.json that must go into detection rule. Can you please let me know where this rule needs to be added? I can follow a similar change and come up with a PR.

**Comment by kcreddy** [comment]
This package's vulnerability rule could probably go inside: https://github.com/elastic/detection-rules/tree/main/rules/integrations. Once the new rule is added, we need to test for any duplicate alerts and update documentation for users on the best way to upgrade the integration.

**Comment by terrancedejesus** [comment]
@approksiu @kcreddy - Thanks for the ping. I don't see why not, we have the threat indicator rules and have migrated rules out of integration packages (i.e. advanced analytic ML rules) into detection-rules before. With the rule shared, let me dev this out a bit and follow up!

**Comment by terrancedejesus** [comment]
@approksiu @kcreddy - I've created the rule, updated some necessary things in our repo and it should be ready for review.

Ref: https://github.com/elastic/detection-rules/pull/3718

I did make some changes to the following:

- References: I added `https://docs.elastic.co/integrations/ti_rapid7_threat_command`
- Setup: I added a note about Max Signals as required by our unit tests
- Tags: I updated the tags to match what we use for unit tests
- Threat Query: I updated the threat query to match our other threat intel queries a bit such as specifying a timestamp range and adding `event.module: ti_rapid7_threat_command` to the query. I also removed the exclusion for alert indexes since it be using `rapid7-tc-unique-cves` -> Please confirm this is okay.
- Query: Adjusted this to `vulnerability: *` -> Please confirm this is okay,

Also, please take a look at the image below and confirm that the `Indicator filters` is correct? I attempted to move your filters according to our schemas which then converts to JSON during our artifact building. However, it says `NOT` which seems rather odd?

<img width="2199" alt="Screenshot 2024-05-29 at 4 33 10 PM" src="https://github.com/elastic/integrations/assets/99630311/5905e858-62a1-4db0-a4ed-d06bb12339ad">

**Comment by kcreddy** [comment]
@terrancedejesus, thanks for the inputs and also good to see the PR 😄

> I also removed the exclusion for alert indexes since it be using `rapid7-tc-unique-cves` -> Please confirm this is okay.

Exclusion on alert indices sounds good.  The index name itself is going to be different. I added this in my review: https://github.com/elastic/detection-rules/pull/3718#discussion_r1619973313. It will be the alias name of the transform's destination index: `logs-ti_rapid7_threat_command_latest.ioc`. This is the new naming convention.

> Query: Adjusted this to `vulnerability: *` -> Please confirm this is okay,

So, the query in our existing rule `vulnerability.id : *` seem to match the query inside new rule you created: `vulnerability.id : *`. This seems correct to me.

> Also, please take a look at the image below and confirm that the Indicator filters is correct? I attempted to move your filters according to our schemas which then converts to JSON during our artifact building. However, it says NOT which seems rather odd?

Thats a good catch. If I check the existing rule, I see the `filters` are defined with `negate: true` on `rapid7.tc.vulnerability.id exists`:

https://github.com/elastic/integrations/blob/f1f49f74235fe636d298d2e69cc474d2d4f3c9be/packages/ti_rapid7_threat_command/kibana/security_rule/eaecc8f0-6704-11ed-80b2-9bbc46f73b72.json#L7

But, the `threat_filters` is an empty array. I think the rule is just trying to avoid querying its own data because this data also come under `logs-*` and thus avoiding matching with them. So, in short, `NOT rapid7.tc.vulnerability.id exists` should go into `filters` and not `threat_filters`.

**Comment by kcreddy** [comment]
The PR https://github.com/elastic/detection-rules/pull/3718 wasn't supposed to close this issue, as this issue is for adding support for IOC expiration. Reopening the issue
