### ISSUE TITLE
[Couchbase] TSDB Enablement

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#7378]
## TSDB Enablement
 - [x] https://github.com/elastic/integrations/pull/7721

## Test Environment Setup
- [x] Creation of Test Environment

## Datastream : `bucket` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/7419
  - [x] Add metric_type mappings - Already exists
  
#### Verification and validation
  - [x] Verification of data in visualisation after enabling the TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Verify if the TSDB can be disabled using the API method
  - [x] Verify if the TSDB can be re-enabled after 4 hours, following disablement using API method, making use of package upgrade. 
  - [x] Add screenshots of dashboards (Recommended), if applicable. 

## Datastream : `cache` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/7430
  - [x] Add metric_type mappings - Already exists
 
#### Verification and validation
  - [x] Verification of data in visualisation after enabling the TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Verify if the TSDB can be disabled using the API method
  - [x] Verify if the TSDB can be re-enabled after 4 hours, following disablement using API method, making use of package upgrade. 
  - [x] Add screenshots of dashboards (Recommended), if applicable. 

## Datastream : `cbl_replication` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/7498
  - [x] Add metric_type mappings - Already exists
  
#### Verification and validation
  - [x] Verification of data in visualisation after enabling the TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Verify if the TSDB can be disabled using the API method
  - [x] Verify if the TSDB can be re-enabled after 4 hours, following disablement using API method, making use of package upgrade. 
  - [x] Add screenshots of dashboards (Recommended), if applicable. 

## Datastream : `cluster` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/7524/
  - [x] Add metric_type mappings - Already exists
  
#### Verification and validation
  - [x] Verification of data in visualisation after enabling the TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Verify if the TSDB can be disabled using the API method
  - [x] Verify if the TSDB can be re-enabled after 4 hours, following disablement using API method, making use of package upgrade. 
  - [x] Add screenshots of dashboards (Recommended), if applicable. 

## Datastream : `database_stats` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/7540
  - [x] Add metric_type mappings - Already exists
 
#### Verification and validation
  - [x] Verification of data in visualisation after enabling the TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Verify if the TSDB can be disabled using the API method
  - [x] Verify if the TSDB can be re-enabled after 4 hours, following disablement using API method, making use of package upgrade. 
  - [x] Add screenshots of dashboards (Recommended), if applicable. 

## Datastream : `miscellaneous` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/7606
  - [x] Add metric_type mappings - Already exists
  
#### Verification and validation
  - [x] Verification of data in visualisation after enabling the TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Verify if the TSDB can be disabled using the API method
  - [x] Verify if the TSDB can be re-enabled after 4 hours, following disablement using API method, making use of package upgrade. 
  - [x] Add screenshots of dashboards (Recommended), if applicable. 

## Datastream : `node` 
  -  No changes needed. It is based on httpjson.

## Datastream : `query_index` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/7608
  - [x] Add metric_type mappings - Already exists
  
#### Verification and validation
  - [x] Verification of data in visualisation after enabling the TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Verify if the TSDB can be disabled using the API method
  - [x] Verify if the TSDB can be re-enabled after 4 hours, following disablement using API method, making use of package upgrade. 
  - [x] Add screenshots of dashboards (Recommended), if applicable. 

## Datastream : `resource` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/7643
  - [x] Add metric_type mappings - already exists
  
#### Verification and validation
  - [x] Verification of data in visualisation after enabling the TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Verify if the TSDB can be disabled using the API method
  - [x] Verify if the TSDB can be re-enabled after 4 hours, following disablement using API method, making use of package upgrade. 
  - [x] Add screenshots of dashboards (Recommended), if applicable. 

## Datastream : `xdcr` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/7661
  - [x] Add metric_type mappings - Already avaiable
  
#### Verification and validation
  - [x] Verification of data in visualisation after enabling the TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Verify if the TSDB can be disabled using the API method
  - [x] Verify if the TSDB can be re-enabled after 4 hours, following disablement using API method, making use of package upgrade. 
  - [x] Add screenshots of dashboards (Recommended), if applicable.

**Comment by lalit-satapathy** [comment]
@kush-elastic,

For the couchbase package here, can you confirm that the metric types are complete and up-to-date and cross-check the dimension PRs above once.

**Comment by kush-elastic** [comment]
> For the couchbase package here, can you confirm that the metric types are complete and up-to-date and cross-check the dimension PRs above once.

Sure, @lalit-satapathy

**Comment by kush-elastic** [comment]
Hey @agithomas @lalit-satapathy,
I went over the PRs mentioned in this issue and also checked all the metric types.
They look good to me.
