### ISSUE TITLE
[Cloud Security] [CIS GCP] Add organization id input var to GCP's manifest

### ISSUE THREAD

**Issue by uri-weisman** [elastic/integrations#7398]
In order to support org level misconfiguration assessment the user should input the organization id.
This param should be optional (will be required by the UI only in the cloudshell deployment flow) and without a default value.

**Comment by kfirpeled** [comment]
- verify the org id is propagated to the cloud shell command

**Comment by Omolola-Akinleye** [comment]
Org id is propagated to cloud shell command
![Image](https://github.com/elastic/integrations/assets/17135495/ad56dc13-28b2-4f8c-bbda-59ace0168e8e)
