### ISSUE TITLE
Make Apache Spark GA

### ISSUE THREAD

**Issue by harnish-elastic** [elastic/integrations#7406]
- Make Apache Spark GA with the following data streams
   - Metrics:
       - application 
       - executor
       - driver
       - node

### Issue & Enhancements

- https://github.com/elastic/integrations/issues/7407
- https://github.com/elastic/integrations/issues/7409
- https://github.com/elastic/integrations/issues/7411
- https://github.com/elastic/integrations/issues/7410
- https://github.com/elastic/integrations/issues/7408
- https://github.com/elastic/integrations/issues/8116

**Comment by muthu-mps** [comment]
@harnish-elastic - 
- Verify the logo for the apache spark.
- As per this [PR](https://github.com/elastic/integrations/issues/7411) we need to create pipeline test for datastreams. Do we really need pipeline tests for metrics datastream? Will this be a blocker for GA migration ?

**Comment by harnish-elastic** [comment]
> * Verify the logo for the apache spark.

While the Apache Spark package was made, there are the following logo was present on the Apache Spark site that we had used. 
![image](https://github.com/elastic/integrations/assets/118714680/7471ddc9-394d-4577-b281-9ee662560345)

Currently, the following logo is present on the Apache Spark site.
![image](https://github.com/elastic/integrations/assets/118714680/631083f1-19c6-4c15-b19b-c9131e16e6dd)

Let me know if you think we need to update the logo for Apache Spark integration.

> * As per this [PR](https://github.com/elastic/integrations/issues/7411) we need to create pipeline test for datastreams. Do we really need pipeline tests for metrics datastream? Will this be a blocker for GA migration ?

No @muthu-mps if the pipeline tests are not present, we can still proceed with the GA migration. Pipeline tests are not blockers to make GA.

**Comment by muthu-mps** [comment]
> > * Verify the logo for the apache spark.
> 
> While the Apache Spark package was made, there are the following logo was present on the Apache Spark site that we had used. ![image](https://user-images.githubusercontent.com/118714680/267641613-7471ddc9-394d-4577-b281-9ee662560345.png)
> 
> Currently, the following logo is present on the Apache Spark site. ![image](https://user-images.githubusercontent.com/118714680/267642213-631083f1-19c6-4c15-b19b-c9131e16e6dd.png)
> 
> Let me know if you think we need to update the logo for Apache Spark integration.
> 
> > * As per this [PR](https://github.com/elastic/integrations/issues/7411) we need to create pipeline test for datastreams. Do we really need pipeline tests for metrics datastream? Will this be a blocker for GA migration ?
> 
> No @muthu-mps if the pipeline tests are not present, we can still proceed with the GA migration. Pipeline tests are not blockers to make GA.

yes, we need to update the logo to the latest one.

**Comment by harnish-elastic** [comment]
Hey @muthu-mps Raised a PR to update Apache Spark Logo https://github.com/elastic/integrations/pull/7830
