### ISSUE TITLE
Pipeline fails to dissect NTP messages

### ISSUE THREAD

**Issue by C0FFEEC0FFEE** [elastic/integrations#7460]
When ingesting Cisco IOS logs via an Elastic Agent (data_stream.dataset: cisco_ios.log) the NTP log messages cannot be dissceted.

Error message:
```
Processor "dissect" with tag "dissect_header" in pipeline "logs-cisco_ios.log-1.17.0" failed with message "Unable to find match for dissect pattern: %{_temp_.header} %%{message} against source: <191>2637085: rt401-rk30409: Aug 18 07:15:04.461 CEST: NTP Core (NOTICE): Clock synchronization lost."
```

Example logs:
```
<191>2637085: rt401-rk30409: Aug 18 07:15:04.461 CEST: NTP Core (NOTICE): Clock synchronization lost.
<191>2637086: rt401-rk30409: .Aug 18 07:15:04.461 CEST: NTP Core (INFO): 10.200.1.105 961A 8A sys_peer
<191>2637087: rt401-rk30409: .Aug 18 07:15:04.461 CEST: NTP Core (NOTICE): Clock is synchronized.

```

**Comment by efd6** [comment]
It's not clear to me how important it is to retain these logs, however there's a change at #7466 that adds support for this. Please note that the second and third log line in your examples are not valid (dot before the month name).

**Comment by C0FFEEC0FFEE** [comment]
> It's not clear to me how important it is to retain these logs, however there's a change at #7466 that adds support for this. Please note that the second and third log line in your examples are not valid (dot before the month name).

Thanks.
