### ISSUE TITLE
[meta] Upgrade integrations to ECS 8.10

### ISSUE THREAD

**Issue by ebeahan** [elastic/integrations#7480]
Track ECS 8.10 updates to integration packages maintained by the `elastic/security-external-integrations` team.

## ECS 8.10 Changes

This is a summary of the changes in ECS 8.10. You can view the official changelog [here](https://github.com/elastic/ecs/blob/8.9/CHANGELOG.md) (invalid link for now - will update).

#### Added
* Added `container.security_context.privileged` to indicated whether a container was started in privileged mode. #2219, #2225, #2246
* Added `process.thread.capabilities.permitted` to contain the current thread's possible capabilities. #2245
* Added `process.thread.capabilities.effective` to contain the current thread's effective capabilities. #2245
 

This issue will be updated once the necessary work to be done is evaluated.

**Comment by kgeller** [comment]
All ECS update PRs have been merged
