### ISSUE TITLE
Add asset tags to security integrations

### ISSUE THREAD

**Issue by narph** [elastic/integrations#7483]
With the merge of https://github.com/elastic/kibana/pull/162643 we are now able to add automatic tagging to our integration packages.

Currently there are 3 tasks that needs to be performed.
1. Try adding it to an integration, and ensure that the integration still are able to be installed (though without tags) on older versions like 8.8 or 8.7, then once more on 8.10 to confirm the correct tag is added.
2. Once confirmed, we should use some sort of tooling to add a few specific things to integrations that we own all datastreams for:
Bump format_version to 2.10.0+
Add a tags.yml in the kibana folder of the integration, and fill it with:
```
 - text: Security Solution
  asset_types:
    - dashboard
    - search
```
This should tag all our asset types needed to view them, we can check by going to the Security Solution UI, and click "Dashboards".
3. Once step 2 is performed, we can manually add the `tags.yml` to the integration packages with multiple owners, but here we have to specify the dashboard ID of the assets we want to tag:
```
- text: Security Solution
  asset_ids:
    - id1
    - id2
```

**Comment by marc-gr** [comment]
> 1. Try adding it to an integration, and ensure that the integration still are able to be installed (though without tags) on older versions like 8.8 or 8.7, then once more on 8.10 to confirm the correct tag is added.

The minimum kibana version for this to be supported is 8.10.0, including validation, so for any package we want to include the tags.yml, we will need to bump kibana version to 8.10.0 along the way, otherwise the package can't be built with an error like 

```
Error: building package failed: invalid content found in built zip package: found 1 validation error:
   1. conditions.kibana.version must be ^8.10.0 or greater to include saved object tags file: kibana/tags.yml
```

So they won't be able to be installed in < 8.10 with the file present.

**Comment by marc-gr** [comment]
I created a PR to relax that validation and prevent forcing to bump kibana version on all packages https://github.com/elastic/package-spec/pull/577

**Comment by ebeahan** [comment]
@marc-gr any more work that needs to happen around tagging here?

**Comment by marc-gr** [comment]
> @marc-gr any more work that needs to happen around tagging here?

Only package missing is windows, it is pending to solve the same issue mentioned [here](https://github.com/elastic/integrations/pull/8291#discussion_r1371974310) so it can be upgraded to spec v3. Any other work is done related to this.

**Comment by ebeahan** [comment]
Filed a separate issues to continue tracking the `windows` work, which includes setting the asset tags: https://github.com/elastic/integrations/issues/8677.

Closing this meta issue.
