### ISSUE TITLE
More Mapping Conflicts (7.11.1) - event.ingested

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/integrations#750]
Hi all,
There is again a mapping conflict in fleets for the cisco.asa and the other indices
![image](https://user-images.githubusercontent.com/7324088/109488435-da801c00-7a85-11eb-9b06-5f1f330a4dbe.png)

Cheers,
Marcus

**Comment by andrewkroh** [comment]
What version of the Cisco package do you have installed?

**Comment by MarcusCaepio** [comment]
Elastic-Agent 7.11.1
Cisco Integration 0.7.7
Apache 0.3.4
Endpoint 0.17.1
Elastic Agent 0.0.5
Mysql 0.3.6
System 0.10.9
All installed integrations are shown as uptodate

**Comment by andrewkroh** [comment]
This will be fixed in the Cisco 0.8.0 package from #775.
