### ISSUE TITLE
'linux.socket' dataset for Linux integration not sending data to ES as per Period value set on Edit Integration Page.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#751]
**Kibana version:**
7.12 BC2 Kibana Cloud environment 

**Host OS and Browser version:**
Linux Centos 7.6, All

**Preconditions**
1.  7.12 BC2 Kibana Cloud environment should be available.
```
BUILD 39000
COMMIT 4f65a5a1268fa78f1af9117d12312e1cee433376
Artifact link: https://staging.elastic.co/7.12.0-37f40745/downloads/beats/elastic-agent/elastic-agent-7.12.0-linux-x86_64.tar.gz
```
2. User policy having Linux integration should exist.

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Data streams. 
3. Observe, Linux datasets are available and streaming data on Data stream page.
4. Go to Policies. Select Agent policy and edit Linux integration.
5. Observe, by default Period value is set to 10s for Linux host socket metrics under 'Collect system metrics from Linux instances' section.

Expected Result:
Data Stream should be available as per Period value set in integration page for Linux host socket metrics 

**Screenshots:** 
![image](https://user-images.githubusercontent.com/72375798/109493797-02d23f80-7ab3-11eb-97e4-6ca5e58872a8.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please Review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by fearful-symmetry** [comment]
I think we've had this issue opened a few times? `socket` is weird compared to the rest of metricbeat, it'll only send data if a new network socket is opened.

**Comment by EricDavisX** [comment]
ok, fair enough, thanks Alex.   

@dikshachauhan-qasource can you check out the info in this stack exchange post:
https://unix.stackexchange.com/questions/214471/how-to-create-a-tcp-listener
 - and try it out?  either the local netcat call or python, whichever you may prefer.  If it works after this we can update test steps that relate.  If broken we can assign back to Alex for review.

**Comment by dikshachauhan-qasource** [comment]
Hi @fearful-symmetry 

We had a discussion on this prior, however had no ticket opened up on this. So thought of to log and get proper steps if we are missing anything.

Further, Thanks @EricDavisX  for the guide page. I've gone through others help guides too and attempted below commands to create a new network socket. 

**Commands used on Centos 7 to open a port:**
sudo firewall-cmd --zone=public --permanent --remove-port=5555/tcp
sudo firewall-cmd --reload
netstat -lntu | grep 5555

**Logs are as follows:**
[SocketOpenCommandsOnLinux7.6.txt](https://github.com/elastic/integrations/files/6068344/SocketOpenCommandsOnLinux7.6.txt)


We have observed though the port is not enable as per warning in few attempts, however, whenever success message is displayed on running command 'sudo firewall-cmd --zone=public --permanent --remove-port=6000/tcp', dataset gets updated on Fleet side.

@fearful-symmetry , can you please confirm if we are doing it right way. So that we can update our testcases.

Thanks
QAS

**Comment by fearful-symmetry** [comment]
If the dataset is reporting the new socket, I'd say that's right, yah.

**Comment by dikshachauhan-qasource** [comment]
Hi @fearful-symmetry 

Thanks for the feedback.

We have updated 01 testcase as per the feedback to cover 'Linux.socket' dataset more precisely. Test case link is as follows:

- [C284097](https://elastic.testrail.io/index.php?/tests/view/284097)

@EricDavisX,  As issue is resolved with the updated content, so we are closing this ticket.

Thanks
QAS
