### ISSUE TITLE
[ProblemChild] Two Detection Rules Querying Invalid Indices

### ISSUE THREAD

**Issue by MakoWish** [elastic/integrations#7520]
## Describe the Issue

Two of the Detection Rules supplied in the ProblemChild Integration look for `logs-endpoint.events.process.*`, but that final period is invalid and will not match an Elastic Endpoint index. This should be either `logs-endpoint.events.process*` or `logs-endpoint.events.process-*`.

## Screenshots

![incorrect_index_listing](https://github.com/elastic/integrations/assets/26614684/0a7f4208-cc92-439f-8e89-910d505429fc)

**Comment by andrewkroh** [comment]
This appears to have been fixed by https://github.com/elastic/integrations/pull/7521. Closing.
