### ISSUE TITLE
Create dashboards for test results

### ISSUE THREAD

**Issue by ycombinator** [elastic/integrations#755]
Test results from CI runs on the `master` branch are being indexed into an Elastic-internal Elasticsearch cluster. It would be great to have some dashboards that visualize these results as a way of understanding progress over time + quickly determining packages that need more test coverage.

**Comment by sorantis** [comment]
+1 one of the integrations we're planning to add in the future is Jenkins (including dashboards). Do you see this as something related?

**Comment by ycombinator** [comment]
> +1 one of the integrations we're planning to add in the future is Jenkins (including dashboards). Do you see this as something related?

I'm not sure. I imagine the Jenkins integration, at least to start off, might be fairly basic — in that it might involve ingesting metrics exposed by something like https://github.com/jenkinsci/metrics-plugin ? If so, I don't see anything specific to test results in there (not surprising as Jenkins is quite a generic workflow automation tool).

**Comment by mtojek** [comment]
@v1v Maybe you know where these metrics data can be stored? I tried the link posted in: 

but it failed with:

```{"statusCode":429,"error":"Too Many Requests","message":"[[parent] Data too large, data for [<http_request>] would be [2061694776/1.9gb], which is larger than the limit of [2040109465/1.8gb], real usage: [2061694776/1.9gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, model_inference=0/0b, accounting=0/0b]: circuit_breaking_exception]: [parent] Data too large, data for [<http_request>] would be [2061694776/1.9gb], which is larger than the limit of [2040109465/1.8gb], real usage: [2061694776/1.9gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, model_inference=0/0b, accounting=0/0b]"}

**Comment by v1v** [comment]
I'll create a dashboard similar to the ones we created for others and I'll raise a PR in the internal repository then you can review it

**Comment by mtojek** [comment]
SGTM!

**Comment by v1v** [comment]
> It would be great to address requirements defined in this task: visualize total test coverage for integrations (pipeline tests, system tests, no tests). I understand if we need to collect more reference data.

Test coverage is not collected in the CI, but only, the build details, test stats summary and test failures.

For instance, given the [build 561](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/master/561) then all the data is gathered and transformed in `json` files, and those files are the ones that are sent to ES, such as:
- https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/master/561/artifact/ci-build-report.json , for the build details
- https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/master/561/artifact/ci-test-report-bulk.json, for the test failures


`ci-build-report.json` aggregates some other files, such as: https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/master/561/artifact/tests-summary.json and so on.

The index mapping can be found in -> https://github.com/elastic/apm-pipeline-library/blob/master/resources/ci-builds-mapping.json

**Comment by mtojek** [comment]
Build info is also useful (successful, skipped, failed tests + date) and would be great to setup a dashboard for it.

As the goal of this issue is to implement visualization for test coverage, do you have any recommendations in terms of Jenkins plugins? I can work on the missing transformation/scripting.

**Comment by v1v** [comment]
> As the goal of this issue is to implement visualization for test coverage, do you have any recommendations in terms of Jenkins plugins? I can work on the missing transformation/scripting.

Test coverage can be visualise in Jenkins itself, for instance with https://plugins.jenkins.io/cobertura/

IIRC, some teams already use it:
- Specific for a build -> https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/master/1087/cobertura/
- A trend -> https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/master/cobertura/graph
- Another plugin -> https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/master/560/coverage/

Regarding the transformation, there is a limitation with the existing implementation that runs as a post-build step, and it's related to how much data is ingested, that's the main reason we didn't send all the test data but the failed tests.

**Comment by mtojek** [comment]
This will be a custom setup. In Cobertura there are: *packages-classes-methods-line*. Here we will have: *packages-test_types-tests*. We won't use it specifically to cover lines of package sources with tests, but rather verify if tests are there - like a checklist.

1. WDYT if I implement logic that will collect these stats similarly to [Junit results](https://github.com/elastic/integrations/blob/master/.ci/Jenkinsfile#L94) instead of running any `cobertura.jar`? Will the plugin visualize it based on the homebrew XML report? 

2. Do you it's possible to have multiple XML report files (also similarly to JUnit reports)? I'm asking as it will simplify the implementation.

**Comment by v1v** [comment]
> Do you it's possible to have multiple XML report files (also similarly to JUnit reports)? I'm asking as it will simplify the implementation.

Yes, IIRC, `junit` or `coberage`/`cobertura` allow to use file path patterns.

> WDYT if I implement logic that will collect these stats similarly to Junit results instead of running any cobertura.jar? Will the plugin visualize it based on the homebrew XML report?

Let's try it simple with some synthetic generated XML report and see if it works as you expected

If you need help with the setup let me know, and we can go through how I develop locally with Jenkins

**Comment by mtojek** [comment]
I played a bit with Cobertura and static fake reports and I can confirm that Jenkins shows reports correctly. I mean, we can read from bars where we have gaps (missing pipeline or system test), even though the domain language (package/class/method) is different.

Legend:
package  - an integration/an Elastic package
class - kind of test: pipeline or system
method - test name, e.g. test-access-event, test-default-config

I had to add fake `no-test` method entries to signal a gap (missing test) to properly calculate coverage.

For reference: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package/detail/PR-440/8/pipeline

<img width="1800" alt="Zrzut ekranu 2021-07-20 o 14 41 03" src="https://user-images.githubusercontent.com/14044910/126325875-9ae72634-3c83-49f5-83d7-d70da83e8b51.png">
<img width="1464" alt="Zrzut ekranu 2021-07-20 o 14 41 09" src="https://user-images.githubusercontent.com/14044910/126325889-d16fcece-b585-4767-b912-6cb65a4553a7.png">
<img width="1243" alt="Zrzut ekranu 2021-07-20 o 14 41 16" src="https://user-images.githubusercontent.com/14044910/126325892-59894575-4bee-4541-aaa4-88714b6cc898.png">


Let me know what do you think!  

cc @jsoriano

**Comment by v1v** [comment]
It could be possible to ingest the coverage stats to Elasticsearch and then they can be accessible in the same manner like the test failures and other things in Kibana.

For instance:

Given the build [8](https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/PR-440/8/)

The coverage api is accessible in:
- `https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/PR-440/8/cobertura/api/json?tree=results[elements[name,ratio,denominator,numerator]]&depth=3&pretty=true`


```bash
curl  'https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/PR-440/8/cobertura/api/json?tree=results\[elements\[name,ratio,denominator,numerator\]\]&depth=3&pretty=true'
{
  "_class" : "hudson.plugins.cobertura.targets.CoverageResult",
  "results" : {
    "elements" : [
      {
        "denominator" : 0.0,
        "name" : "Packages",
        "numerator" : 0.0,
        "ratio" : 100.0
      },
      {
        "denominator" : 0.0,
        "name" : "Files",
        "numerator" : 0.0,
        "ratio" : 100.0
      },
      {
        "denominator" : 0.0,
        "name" : "Classes",
        "numerator" : 0.0,
        "ratio" : 100.0
      },
      {
        "denominator" : 17.0,
        "name" : "Methods",
        "numerator" : 11.0,
        "ratio" : 64.70588
      },
      {
        "denominator" : 0.0,
        "name" : "Lines",
        "numerator" : 0.0,
        "ratio" : 100.0
      },
      {
        "denominator" : 0.0,
        "name" : "Conditionals",
        "numerator" : 0.0,
        "ratio" : 100.0
      }
    ]
  }
}
```

In case the above it can be helpful

**Comment by mtojek** [comment]
Nice! We could adjust all labels to our domain language. I like this idea :)

Anyway, I'm going with the right implementation of this feature.

**Comment by v1v** [comment]
We have just enabled recently the population of the coverage stats (see https://github.com/elastic/apm-pipeline-library/pull/1214 for further details).

Therefore those `%` values are now available in the Build dashboards we created in Kibana, for instance:

![image](https://user-images.githubusercontent.com/2871786/127280012-34dbd792-f15d-4ce4-b8a7-7f33e81c291f.png)

It's just presenting the same data that it's seeing in Jenkins:

![image](https://user-images.githubusercontent.com/2871786/127280264-309d8122-6918-48ea-8db3-1ead03f6042b.png)

 https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/master/lastSuccessfulBuild/cobertura/graph
