### ISSUE TITLE
Support improved config generation UX for standalone agent use cases 

### ISSUE THREAD

**Issue by mukeshelastic** [elastic/integrations#756]
### Problem:

The configuration of the Elastic Agent is a list of inputs unlike beat modules which contained configuration. These configurations are now moved to integrations managed in fleet Kibana app. The Elastic Agent itself has only knowledge of inputs. When you add  integrations from fleet kibana app, it generates the agent configuration and so users do not need to hand write it. But for cases where you do not want to use fleet app, generating agent config is a cumbersome experience. Any auto-discover use case will fall in this bucket where agent needs to generate the configuration for auto-discovered integrations dynamically. In this [issue](https://github.com/elastic/beats/issues/24054) agent will support template input type for simplifying config generation in such standalone use cases.

 This issue is to figure out:
-  How these templates are generated?
-  What is its structure?
-  How are configuration options such as enable only specific dataset or other configuration parameter are passed into template etc. 
- How there configuration are included and shipped with the Elastic Agent.

**Comment by mukeshelastic** [comment]
@ruflin @blakerouse @ph Feel free to edit the problem description as you see fit.

**Comment by ph** [comment]
Lets not forget @masci @exekias in theses issue.
