### ISSUE TITLE
[ProblemChild] Bug in Ingest Pipeline for `blocklist_label` String/Integer

### ISSUE THREAD

**Issue by MakoWish** [elastic/integrations#7576]
I just started using the ProblemChild integration last week, and I noticed no events are being tagged with the `blocklist_label` field when I have actually seen events that should match. After investigating this, I can see the `problem_child_inference_pipeline.yml` pipeline is looking for an integer match:

https://github.com/elastic/integrations/blob/f72c98b5ef4f1c7385c120f0a3ddfad31b5b0cbe/packages/problemchild/elasticsearch/ingest_pipeline/problem_child_inference_pipeline.yml#L353C1-L354C50

The problem is, if `problemchild.prediction` is being set, it is set as a string value and therefore will never match.

**Comment by andrewkroh** [comment]
This appears to have been fixed by https://github.com/elastic/integrations/pull/7618. Closing.
