### ISSUE TITLE
[O11y][Azure] Remove `[Azure Metrics]` suffix to the panels titles

### ISSUE THREAD

**Issue by rajvi-patel-22** [elastic/integrations#7585]
## Description
The `VM Disk Reads [Azure Metrics]` is the only panel having the `[Azure Metrics]` suffix from Compute VMs Overview dashboard.
According to the best practices "[Azure Metrics]" suffix should be added to the all panel titles.

### Screenshots
![image](https://github.com/elastic/integrations/assets/124889398/ceec7b02-ee75-4cb5-93db-d09161ff8420)

**Comment by agithomas** [comment]
I am not sure if this is a great idea to include "Repetitive titles". I take reference from [here](https://github.com/elastic/integrations/blob/main/docs/dashboard_guidelines.md)


@SubhrataK , what is you think? 

I would suggest to remove "[Azure Metrics]" from the title.


cc @rameshelastic

**Comment by milan-elastic** [comment]
> I am not sure if this is a great idea to include "Repetitive titles". I take reference from [here](https://github.com/elastic/integrations/blob/main/docs/dashboard_guidelines.md)
> 
> @SubhrataK , what do you think?
> 
> I would suggest to remove "[Azure Metrics]" from the title.
> 
> cc @rameshelastic

@SubhrataK Based on the [doc](https://github.com/elastic/integrations/blob/main/docs/dashboard_guidelines.md) and in general, I think we should remove "[Azure Metrics]" suffix from the visualization titles, as it is already present at the dashboard title! Let me know if WDYT!
