### ISSUE TITLE
[Azure] [Docs] extend the storage account requirements in the Azure Logs documentation

### ISSUE THREAD

**Issue by zmoog** [elastic/integrations#7586]
Some users reported they need to learn how to configure the storage account required to run the Azure module or the Azure Logs integration.

For example, users are looking for guidance on [storage account settings](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal#advanced-tab) like:

- Minimus TLS version
- Permitted scope for copy operations
- Access Tier

We must add this information to the current documentation.

Here's a list of the current version for Filebeat and Agent:

- https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-azure.html
- https://docs.elastic.co/integrations/azure#create-a-storage-account-container

**Comment by zmoog** [comment]
The `azure-eventhub` input uses a storage account as a checkpoint store for the Event Processor Host (EPH). See https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-event-processor-host for more.

Recommendations:

> Don't enable the soft delete feature on the storage account that's used as a checkpoint store.

**Comment by zmoog** [comment]
Also, from https://learn.microsoft.com/en-us/azure/event-hubs/event-processor-balance-partition-load#checkpoint (this doc is for the newer Azure SDK, but they may apply to the legacy checkpointing implementation):

> On the Storage account page in the Azure portal, in the Blob service section, ensure that the following settings are disabled.
>
>   - Hierarchical namespace
>   - Blob soft delete
>   - Versioning

**Comment by zmoog** [comment]
As a starting point, here's the recommended default settings:

- Access tier: Hot
- Enable hierarchical namespace: no
- Minimum TLS version: version 1.2 is okay
- Enable soft delete for blobs: no
- Enable soft delete for containers: no

Use the storage account as checkpoint store only.

**Comment by TomonoriSoejima** [comment]
In addition, please  also consider adding required port based on 
https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-faq#what-ports-do-i-need-to-open-on-the-firewall

**Comment by alaudazzi** [comment]
@zmoog and I met on Nov 22 and 23. Meeting notes:

- contextualized the need for a [storage account settings](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal#advanced-tab) 

![Image](https://github.com/elastic/integrations/assets/46651782/05ff61c6-0ce3-4e8b-a843-68a5fdbf8615)
- shared notes on how to document specific requirements for the storage account (https://elastic.slack.com/archives/C0D8SUKB2/p1693257411108399)
- identified additional doc areas for improvement related to:
   - specialized vs generic integrations (https://github.com/elastic/integrations/pull/8553/files)
   - how to pick up the right integration (https://elastic.slack.com/archives/CJZ9U5G9X/p1700531235515779)

**Comment by alaudazzi** [comment]
@zmoog 
Which Azure integrations are impacted by these doc changes?

**Comment by zmoog** [comment]
Here is the list of integrations that the page https://docs.elastic.co/integrations/azure helps to set up:

```
$ tree -L 1  packages/azure/data_stream/
packages/azure/data_stream/
├── activitylogs
├── application_gateway
├── auditlogs
├── eventhub
├── firewall_logs
├── identity_protection
├── platformlogs
├── provisioning
├── signinlogs
└── springcloudlogs

10 directories, 0 files
```

**Comment by alaudazzi** [comment]
@zmoog 
thank you again for you great intro to Azure integrations in general, and for providing me with access to the Azure portal to test and update the doc procedure.

Here is the [doc fix ](https://docs.google.com/document/d/1dVftW_6UjU68m3XeeSYjj5hOXiL6t3-MEES2pL-YM9Y/edit) for the section on [storage account settings](https://docs.elastic.co/integrations/azure#create-a-storage-account-container). 
This setup procedure is documented in the main Azure Logs page, but there are 10 Azure doc pages that reference it.
As soon as you give me your 👍I'll push a doc PR.

@TomonoriSoejima let's clarify how to integrate your point about the port.

While working on this, I realized that the entire Azure Logs page might be refreshed. I'll create a follow-up issue for that.

**Comment by TomonoriSoejima** [comment]
@alaudazzi 

While I think having a reference to https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-faq#what-ports-do-i-need-to-open-on-the-firewall would be sufficient to check for ports, there is a risk of dead link if Microsoft decides to change the page structure.

So I think it does not hurt to drop the port information. If we support team receives a case, we can easily assume what to do in case of an issue that is caused by a closed port and so forth.

**Comment by alaudazzi** [comment]
Thank you @TomonoriSoejima! 
would you mind updating the [gdoc](https://docs.google.com/document/d/1dVftW_6UjU68m3XeeSYjj5hOXiL6t3-MEES2pL-YM9Y/edit) with the info required to check ports?

**Comment by TomonoriSoejima** [comment]
So for the port requirement I wanted to clarify was for how to integrate with eventhub and not related to storage account requirements and not applicable to be added for this https://docs.google.com/document/d/1dVftW_6UjU68m3XeeSYjj5hOXiL6t3-MEES2pL-YM9Y/edit

**Comment by zmoog** [comment]
@alaudazzi, I read through the doc: the flow is smooth, and the steps are crystal clear. I only left a nit comment.

**Comment by alaudazzi** [comment]
Thank you for your feedback @zmoog!
After discussion with @SubhrataK, it might be better to keep these instructions as generic as possible, and not too specific to the UI of a 3rd-party vendor that - as we already discussed -- is out of our control might go quickly out of sync with our docs.

**Comment by zmoog** [comment]
Makes sense. 

This version retains the core information in step 2 and still has enough guidance for the average Azure user. Kudos @alaudazzi!
