### ISSUE TITLE
MongoDB Integration using old ECS Version

### ISSUE THREAD

**Issue by jamesspi** [elastic/integrations#761]
Community user has pointed out the the current MongoDB integration (`0.27`) available in fleet is using ecs `1.5.0`, whilst others are using `1.8.0`.

Additionally, the `host.hostname` field in the MongoDB data stream is not using the FQDN of the host, as other integrations do.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/20421688/110097474-5ee0e080-7d9f-11eb-8753-d01ff26a662d.png">

**Comment by zez3** [comment]
The same goes for fortiManager(1.6.0) and Fortigate(1.7.0) and system logs(1.5.0)

**Comment by ManojS-shetty** [comment]
Hi @jamesspi 

``Additionally, the host.hostname field in the MongoDB data stream is not using the FQDN of the host, as other integrations do.``

Can you please elaborate a little about this statement to understand and proceed investigating this.?

**Comment by ManojS-shetty** [comment]
The ECS version is updated already. Handling fqdn mapped in the above PR. #4216
