### ISSUE TITLE
[O11y] Remove forwarded tag for metrics data streams

### ISSUE THREAD

**Issue by harnish-elastic** [elastic/integrations#7635]
The forwarded tag will enable the `publisher_pipeline.disable_host: true`, which is the functionality of a Filebeat input setting that only applies to Filebeat-based integrations.

However, there are Metricbeat-based integrations that have the forwarded tag. For those integrations need to remove the forwarded tag since it actually misleads the user.

- [x] https://github.com/elastic/integrations/pull/7823
- [x] https://github.com/elastic/integrations/pull/7824
- [x] https://github.com/elastic/integrations/pull/7825
- [x] https://github.com/elastic/integrations/pull/7826
- [x] https://github.com/elastic/integrations/pull/7827
- [x] https://github.com/elastic/integrations/pull/7828
- [x] https://github.com/elastic/integrations/pull/7829

**Comment by agithomas** [comment]
> For those integrations need to remove the forwarded tag since it actually misleads the user.

Can we have the list of the impacted metricbeat based integrations?

**Comment by harnish-elastic** [comment]
> > For those integrations need to remove the forwarded tag since it actually misleads the user.
> 
> Can we have the list of the impacted metricbeat based integrations?

Here is the list of impacted metricbeat-based integrations

- activemq
- apache_tomcat
- couchbase
- couchdb
- hadoop
- ibmmq
- websphere_application_server

**Comment by ishleenk17** [comment]
Lets create one PR for this change. 
As we discussed forward tag makes sense for filebeat and not for metricbeat.

**Comment by harnish-elastic** [comment]
All PRs are approved and merged. Hence closing this issue.
