### ISSUE TITLE
Beats import script is producing package files that immediately need linting/formatting changes

### ISSUE THREAD

**Issue by ycombinator** [elastic/integrations#765]
I am working on a module->package migration for the `traefik` integration in https://github.com/elastic/integrations/pull/763.

I ran the Beats import script like so:

```
PACKAGES=traefik mage ImportBeats
```

This created a `packages/traefik` folder and sub-folders and files under it, as expected.

However, right after this step, I ran `elastic-package lint` in the `packages/traefik` folder and it produced this output:
```
$ elastic-package lint
Lint the package
Error: linting package failed: found 4 validation errors:
   1. file "/Users/shaunak/development/github/integrations/packages/traefik/manifest.yml" is invalid: field screenshots.0: Additional property path is not allowed
   2. file "/Users/shaunak/development/github/integrations/packages/traefik/manifest.yml" is invalid: field categories: Invalid type. Expected: array, given: null
   3. file "/Users/shaunak/development/github/integrations/packages/traefik/manifest.yml" is invalid: field icons.0: Additional property path is not allowed
   4. expecting to find [changelog.yml] file in folder [/Users/shaunak/development/github/integrations/packages/traefik]
```
   
Similarly, running `elastic-package check` in the `packages/traefik` folder produces this output:
```
$ elastic-package check
Format the package
Error: checking package failed: formatting the integration failed (path: /Users/shaunak/development/github/integrations/packages/traefik, failFast: true): walking through the integration files failed: formatting file failed (path: /Users/shaunak/development/github/integrations/packages/traefik/data_stream/access/fields/ecs.yml): file is not formatted (path: /Users/shaunak/development/github/integrations/packages/traefik/data_stream/access/fields/ecs.yml)
```

For a better developer experience we should ensure that the files produced by `mage ImportBeats` immediately pass `elastic-package lint` and `elastic-package check`.

**Comment by ycombinator** [comment]
cc: @mtojek

**Comment by ycombinator** [comment]
Of the errors reported in the issue description, I think this one is acceptable:

```
   2. file "/Users/shaunak/development/github/integrations/packages/traefik/manifest.yml" is invalid: field categories: Invalid type. Expected: array, given: null
```

That's because there isn't a good way for the Beats import script to know or guess the right categories for the integration.

**Comment by mtojek** [comment]
> For a better developer experience we should ensure that the files produced by mage ImportBeats immediately pass elastic-package lint and elastic-package check.

Yes, that should be a quick win. I wouldn't focus much on improving that part of code base as we need it only for one-time migration. If you ask me, this can be also a step in instruction/guide, not necessarily part of `import-beats`.

**Comment by ycombinator** [comment]
Resolved via https://github.com/elastic/package-registry/pull/684 and https://github.com/elastic/integrations/pull/810.
