### ISSUE TITLE
[Microsoft Exchange Online Message Trace] Improve docs for OAuth2 support

### ISSUE THREAD

**Issue by bhapas** [elastic/integrations#7658]
Lately, We have been seeing similar issues reported in SDHs regarding 
`Error while processing http request: failed to execute rf.collectResponse: failed to execute http client.Do: server responded with status code 401: ..... - Unauthorized: Access is denied due to invalid credentials.`

Although customer is trying to follow our docs [^1] , they are facing issues regarding the correct setup.

It might be a good way to correct few things:

- More guidance (a tutorial-like approach would help)
- More external links to what we need (e.g. https://learn.microsoft.com/en-us/previous-versions/office/developer/o365-enterprise-developers/jj984325(v=office.15)#get-started-with-reporting-web-service)
- A way to validate the OAuth2 credentials and permissions are valid from command line interface (a sort of self check)

[^1]: https://docs.elastic.co/integrations/microsoft_exchange_online_message_trace#steps-

**Comment by jamiehynds** [comment]
Great suggestions @bhapas! For the tutorial, it's worth checking out [this blog](https://www.elastic.co/security-labs/google-workspace-attack-surface-part-two)on configuring the Google Workspace integration. There's a section on how to configure OAuth consent in Workspace. A similar level of detail would be great. 

Really like the idea around validating credentials and permissions, long-term it would be great to validated this either during the integration config or when you save the integration. Having a user-friendly message there and some guidance if the validation fails, would be great (across our integrations, not just Exchange)
