### ISSUE TITLE
"windows.powershell_operational" logs are generated for past timestamp under Data Streams on 7.12.0 Snapshot Kibana.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#768]
**Kibana version:** Kibana: 7.12.0 Snapshot Cloud environment

**Host OS and Browser version:** Windows 10, All

**Build Details:**
```
    Artifact link used: https://snapshots.elastic.co/7.12.0-07994102/downloads/beats/elastic-agent/elastic-agent-7.12.0-SNAPSHOT-windows-x86_64.zip
    Build: 39220
    Commit: 10e035085b6ab636765b76500803c9db19492c8b
```

**Preconditions:**

1. 7.12.0 Snapshot Cloud environment should be available.
2. RDP Test signing should be "ON".
3. Policy must have System, Windows integration.

**Integration Versions:**
**Integration** | **Version**
-- | --
System | 0.10.9
Endpoint Security | 0.18.0
Windows | 0.4.1

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Navigate to Fleet>Agents tab.
3. Install agent with policy having System and Windows integration.
4. Navigate to Data Streams tab.
5. Observe "windows.powershell_operational" logs  be generated for past timestamp.

**Expected Result:**
"windows.powershell_operational" logs should be generated for present timestamp under Data Streams.

**Screenshot:**
![8](https://user-images.githubusercontent.com/77374876/110310378-7c74ab00-8028-11eb-9cf3-be7738dfc9ca.JPG)

**Below attached Agent Policy:**
[elastic-agent (1).zip](https://github.com/elastic/integrations/files/6100790/elastic-agent.1.zip)

**Below attached Agent logs:**
[elastic-agent-json.log](https://github.com/elastic/integrations/files/6100894/elastic-agent-json.log)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
Thanks for logging - we'll ping the Integrations team for review.  @masci can check if / how bad it is and prioritize.

**Comment by andrewkroh** [comment]
It looks like these dates are based on the `@timestamp`, if we used `event.ingested` this would be more accurate.

**Comment by ruflin** [comment]
@marc-gr ^ You seem to be working on the windows package. Any comments?

**Comment by marc-gr** [comment]
As @andrewkroh mentioned, it seems to be using `@timestamp`, which is extracted from the original winevent, meaning it can be set in the past. I think @andrewkroh suggestion of using `event.ingested` would be the right way to go in this case.

**Comment by jen-huang** [comment]
Closing as #116468 was fixed.
