### ISSUE TITLE
Add metrics to `windows` package

### ISSUE THREAD

**Issue by narph** [elastic/integrations#77]
There's currently a `windows` package containing modules migrated from `winlogbeat`. The goal of this issue is to migrate the metrics datasets from the metricbeat `windows` module.

# Package / Dataset creation or update checklist

This checklist is intended for Devs which create or update a package to make sure they are consistent.

* [ ] Required Kibana version set to target version: 7.11.0

## All Changes

* [ ] Change follows [development guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines)
* [ ] Supported versions of the subject being monitored are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
* [ ] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] At least a manual test with ES / Kibana / Agent has been performed.
* [ ] The required Kibana version is set to the lowest version used in the manual test.

### Dashboards

* [ ] Dashboards exists (if applicable)
* [ ] Screenshots of added / updated dashboards
* [ ] Datastream filters added to visualizations

## Log datasets

* [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
* [ ] Test log files exist for the grok patterns
* [ ] Generated output for at least 1 log file exists

## Metric datasets

This entry is currently _recommended_. It will be mandatory once we provide better support for it.

* [ ] Sample event (`sample_event.json`) exists

## New Packages

* [ ] Screenshot of the Fleet "Add Integration" Page.

**Comment by mtojek** [comment]
I think we can close this one.

**Comment by narph** [comment]
I think we planned to tackle this in 7.11 or close future, is this still the case @andresrc ?

**Comment by mtojek** [comment]
Sorry, I understood that the scope of this task is covered.

**Comment by andresrc** [comment]
Hi, yes, I'm waiting for https://github.com/elastic/integrations/pull/342 to start creating the issues for 7.11. Leave this open, I will reuse it and update the content. Thanks

**Comment by narph** [comment]
will close this as metrics have been added and open `migrate windows package` issue
