### ISSUE TITLE
[Cassandra] Incorrect field type for log.flags

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#7712]
Assuming this field is produced by the `log` input in Filebeat then the type should be `keyword`. Currently the data type is in conflict with every other data stream that declares the `log.flags` field.

https://github.com/elastic/integrations/blob/74e55abc934ea82ba69e96cf005793b35f876444/packages/cassandra/data_stream/log/fields/agent.yml#L7-L9

**Comment by aliabbas-elastic** [comment]
Closing this as completed via #7787
