### ISSUE TITLE
[Barracuda] Rename to Barracuda WAF

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#7724]
Our [Barracuda package ](https://github.com/elastic/integrations/tree/main/packages/barracuda)used to include several datastreams for several products, but is now limited to Barracuda Web Application Firewall. Can we update the title and description of the package:

Title: Barracuda Web Application Firewall
Description: Collect logs from Barracuda Web Application Firewall with Elastic Agent.

**Comment by vinit-chauhan** [comment]
Hey @jamiehynds - I can take this one up. 
Could you let me know if the following sounds right?
Package name: `barracuda_waf`
data-stream name: `logs`
package-version: `1.0.0` or `2.0.0` ?

**Comment by jamiehynds** [comment]
Thanks @vinit-chauhan, `barracuda_waf` sounds good. The package version is currently 1.5.0 so with this change we can push to 1.6.0

**Comment by vinit-chauhan** [comment]
Hey @jamiehynds - that Makes sense! I'll update the draft PR.
