### ISSUE TITLE
[Lateral Movement Detection] Two Detection Rules Missing Index Definitions

### ISSUE THREAD

**Issue by MakoWish** [elastic/integrations#7729]
I just attempted to enable the "Remote File Creation on a Sensitive Directory" and "Malicious Remote File Creation" detection rules included in the Lateral Movement Detection integration, but both these rules are missing index definitions. This is causing an error when attempting to enable the rules. 

![rule_error](https://github.com/elastic/integrations/assets/26614684/785a8887-04e9-4cb3-bd87-a068e1523de5)

**Comment by sodhikirti07** [comment]
@MakoWish We are currently in the process of migrating the detection rules from the integration packages to the `detections-rules` repository. We can handle this bug as a part of this effort. Given this, would you please consider closing this [PR](https://github.com/elastic/integrations/pull/7730)?
