### ISSUE TITLE
[O11y][Microsoft SQL Server] Issues and enhancements for `[Metrics Microsoft SQL Server] Transaction log` Dashboard

### ISSUE THREAD

**Issue by aliabbas-elastic** [elastic/integrations#7738]
While testing out the scenarios for this [issue](https://github.com/orgs/elastic/projects/899/views/1?filterQuery=8.11&pane=issue&itemId=37096632), I came across the Transaction Log dashboard of the **Microsoft SQL Server** integration.
This is the issue that tracks the enhancements which will be required for the `[Metrics Microsoft SQL Server] Transaction log` Dashboard.

### Issues and enhancements

1. For most of the visualizations, I have observed that the `Rank By` functionality is set to use the default applied settings. For example, consider the visualization `Total Log Space Usage [Metrics Microsoft SqlServer]` which uses the default `Rank By` settings. It can be changed to sort the databases according to the **Total Log Space Usage** itself.

#### Before
![image](https://github.com/elastic/integrations/assets/124054599/ebf41ba4-c331-46d9-a951-cb6051319410)
#### After
![image](https://github.com/elastic/integrations/assets/124054599/0800f2c0-e52a-4e82-bf4a-a8e54cf6ae8b)

2. For some of the visualizations, `Area Stacked` chart can be improved to `Area` chart only so that there can be better user interpretation.

#### Before
![image](https://github.com/elastic/integrations/assets/124054599/d0736bfa-c010-4d25-9795-76eb5a6b18e4)
#### After
![image](https://github.com/elastic/integrations/assets/124054599/4b2a46f3-87af-438c-9a13-c09aa24d1277)

3. The `Percentage of Used Space [Metrics Microsoft SqlServer]` visualization shows inappropriate values for percentage.

#### Before
![image](https://github.com/elastic/integrations/assets/124054599/a0544a2c-0e93-4803-b21c-66c3d022c9c7)
#### After
![image](https://github.com/elastic/integrations/assets/124054599/d39ec27f-0325-4c54-8f66-6a85a64196c7)

4. Legend width is not sufficient to accumulate the values. Need to change it to `Large` size.

#### Before
![image](https://github.com/elastic/integrations/assets/124054599/69deb03c-563b-4f1a-b289-1cb79b7dee9b)
#### After
![image](https://github.com/elastic/integrations/assets/124054599/bd0a982c-fdb9-41c6-9385-c21894a5c516)

5. Colors used in the visualization can be updated to use **Default color** palette instead.

Let me know anyone's thoughts on these above points if they look appropriate to be enhanced.

**Comment by shmsr** [comment]
The enhancements proposed look good. Thanks for voluntarily picking this up.
