### ISSUE TITLE
[Zookeeper] TSDB Enablement

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#7752]
## TSDB Enablement
 - [x] PR link - https://github.com/elastic/integrations/pull/8104
## Test Environment Setup
- [x] Creation of Test Environment

## Datastream : `connection` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/8059
  - [x] Add metric_type mappings - https://github.com/elastic/integrations/pull/7765
  - [x] TSDB Package test completion

## Datastream : `mntr` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/8069
  - [x] Add metric_type mappings - https://github.com/elastic/integrations/pull/7779
  - [x] TSDB Package test completion

## Datastream : `server` 
  - [x] Add dimension fields - https://github.com/elastic/integrations/pull/8081/
  - [x] Add metric_type mappings - https://github.com/elastic/integrations/pull/7885
  - [x] TSDB Package test completion

**Comment by lalit-satapathy** [comment]
Hi @agithomas,

Can we cross-check and explain the metric type mapping of the following fields currently marked as gauge (but seemingly counters)?

- num_alive_connections
- packets.received
- packets.sent
- znode_count
- node_count

**Comment by agithomas** [comment]
> * num_alive_connections

![image](https://github.com/elastic/integrations/assets/101976829/0ff600e3-9509-40a1-89b3-716587bd990a)

**Comment by agithomas** [comment]
> * znode_count
Explanation i found : 
zk_znode_count is the total count of znodes stored in the ZooKeeper ensemble. Every time a client creates a new znode, this counter will increment. Every time a client deletes a new znode (either explicitly or by dropping its ephemeral znodes after disconnection), this counter will decrement.

**Comment by agithomas** [comment]
> * node_count

This is the explanation i found. node count is the number of znodes in the ZooKeeper namespace (the data). On basis of the [comment](https://github.com/elastic/integrations/issues/7752#issuecomment-1734936826), it is hence treated as a Gauge field. Also, during the testing, i never witnessed a monotonically incrementing value for this field.
