### ISSUE TITLE
how install integration at offline?

### ISSUE THREAD

**Issue by lzj960515** [elastic/integrations#7756]
Hello, I install elastic on my linux system, and the linux system can not access internet, so ,when I install integration, the page can not load, I debug find the page request elastic web site. I want to install apm, How should I solve this problem?  Thank you

![WechatIMG579](https://github.com/elastic/integrations/assets/38074718/5e6a0da2-5517-4b04-ad61-864eba5253a9)
![WechatIMG580](https://github.com/elastic/integrations/assets/38074718/66dacb86-48a3-437f-9e34-8d940d9b4bef)
![WechatIMG581](https://github.com/elastic/integrations/assets/38074718/23cba938-521f-4b9e-afc7-1989f26e6fb1)
![WechatIMG582](https://github.com/elastic/integrations/assets/38074718/7cb5e149-7b47-47a7-bbd9-3d283a7ddfc7)

**Comment by lzj960515** [comment]
version 8.9.1, can someone help me?

**Comment by andrewkroh** [comment]
See https://www.elastic.co/guide/en/fleet/current/air-gapped.html.

**Comment by lzj960515** [comment]
I read document and  configed  xpack.fleet.registryProxyUrl, but it's not work .
This is kibana log : https://epr.elastic.co/package/apm/8.9.1/   response: package revision not found, 
I try  request https://epr.elastic.co/package/apm/8.3.0/ response data.  
Could you please help me.

**Comment by lzj960515** [comment]
> See https://www.elastic.co/guide/en/fleet/current/air-gapped.html.

I read document and configed xpack.fleet.registryProxyUrl, but it's not work .
This is kibana log : https://epr.elastic.co/package/apm/8.9.1/ response: package revision not found,
I try request https://epr.elastic.co/package/apm/8.3.0/ response data.
Could you please help me.
