### ISSUE TITLE
[AWS] [API Gateway] CloudWatch metrics documents for REST APIs

### ISSUE THREAD

**Issue by lucian-ioan** [elastic/integrations#7772]
Ingesting data for AWS API Gateway while making requests to a REST API, the following behavior can be observed:
![4_documents](https://github.com/elastic/integrations/assets/59661554/c77bb303-3c5f-4362-bfa2-0adb7bd6a394)

We get 4 documents, each with varying dimensions. This is similar to the `ApiGateway` CloudWatch metric groupings for REST APIs:
- Across All APIs (no dimensions, only Count and Data processed metrics)
- By Api Name (ApiName dimension)
- By Stage (ApiName, Stage dimensions)
- By Method (ApiName, Stage, Resource, Method dimensions)

For example for `Across All APIs`, if there were multiple APIs being called, the Count will be the sum of calls across all APIs and no dimension will be present in the document ingested:
![5_documents](https://github.com/elastic/integrations/assets/59661554/bf8de601-f7df-4850-9b66-0b42751fa103)

If the `Detailed metrics` option is set to Inactive in the Logs and tracing settings for the API Stage, then only 3 documents will be present (as that option enables metrics tracing for each specific method):
![3_documents](https://github.com/elastic/integrations/assets/59661554/2371b0a1-2c4a-4afb-a554-b95cda7b0e73)

Since we can't guarantee the end user will enable `Detailed metrics`, we can't just consider only the documents will all dimensions. 

Questions:
1) Has this behavior been observed for other Cloud Integrations using the `cloudwatch` metricset and having different metric groupings in CloudWatch? And if yes, how were the documents handled?
2) How to properly visualize the data for these documents?

Note that this behavior is not exclusive to REST APIs since there are also metric groups in CloudWatch that use the apiId dimension (specific to HTTP/WebSocket type APIs).

**Comment by lucian-ioan** [comment]
@zmoog, @girodav, @kaiyan-sheng Would appreciate any input provided here.

**Comment by kaiyan-sheng** [comment]
> 1. Has this behavior been observed for other Cloud Integrations using the cloudwatch metricset and having different metric groupings in CloudWatch? And if yes, how were the documents handled?

Having different metric groupings/group of dimensions is per design by CloudWatch. For example in CloudWatch under Metrics, if you click `ApiGateway` you can see:
<img width="1104" alt="Screenshot 2023-09-12 at 8 33 17 PM" src="https://github.com/elastic/integrations/assets/14081635/1e7270ea-2384-4a9e-ac39-526c1dd04def">

This means CloudWatch has metrics for ApiGateway grouped by method, apiId, stage, API name separately. Also it has metrics across all apis, which means no dimension. Then it also has metrics grouped by apiId, route and stage, or apiId and stage. 

It is common for cloudwatch metrics to have different dimensions but with this many different kinds of grouping and sometimes overlap, it's not so common. For example Redshift is similar:
<img width="1108" alt="Screenshot 2023-09-12 at 8 41 16 PM" src="https://github.com/elastic/integrations/assets/14081635/d399c91e-44e0-47b0-a504-9f60cb666151">

We report documents the way we collect them from CloudWatch so no aggregations. If this cloudwatch metric is collected with this set of dimensions, we look for all data points with the same dimensions and then put them in one document and send them to ES.

> 2. How to properly visualize the data for these documents?

For the APIGateway `IntegrationLatency` case, by looking at CloudWatch, AWS does not report them based on gateway type. So we can't distinguish which metric is from which kind of gateway (HTTP or websocket). But we can tell which API ID it comes from. Maybe we should not think about plotting `IntegrationLatency` based on type? I wonder if plotting it based on API ID and name would be more helpful. Or even plot method/stage depends on the use case. 
<img width="1986" alt="Screenshot 2023-09-12 at 9 48 28 AM" src="https://github.com/elastic/integrations/assets/14081635/dc4480df-d31a-4970-af3b-04dd67a12c7e">

**Comment by lucian-ioan** [comment]
I guess this can be closed. Thank you for the details @kaiyan-sheng :+1:
