### ISSUE TITLE
[O11y][Apache Tomcat] Make Access log custom format `%A %X %T` fields optional

### ISSUE THREAD

**Issue by harnish-elastic** [elastic/integrations#7773]
In the Apache Tomcat Access Logs, the currently supported log formats are as follows:
- Common Log Format :- `%h %l %u %t "%r" %s %b`
- Combined Log Format :- `%h %l %u %t "%r" %s %b "%{Referrer}i" "%{User-Agent}i"`
- Combined Log Format + X-Forwarded-For header :- `%h %l %u %t "%r" %s %b %A %X %T "%{Referer}i" "%{User-Agent}i" X-- Forwarded-For="%{X-Forwarded-For}i"`

The `Combined Log Format + X-Forwarded-For header` is a custom log format that the user can customize by configuring the access log pattern. But there are `%A %X %T` fields that are currently required fields to pass the grok pattern. As per the analysis, the `%A %X %T` should be optional if the user doesn't have any of them. Hence need to make `%A %X %T` optional in the existing grok pattern.

**Comment by muralidharanvenkataraman** [comment]
Hi There,

Any updates on this request?

**Comment by ishleenk17** [comment]
> Hi There,
> 
> Any updates on this request?

@SubhrataK

**Comment by SubhrataK** [comment]
Hi @muralidharanvenkataraman This item is currently in our backlog, but we cannot provide a definite timeline commitment at this moment. We will update here once we have prioritised this request.

**Comment by muralidharanvenkataraman** [comment]
Hi @SubhrataK - Thank you for this update.

**Comment by ishleenk17** [comment]
> Hi There,
> 
> Any updates on this request?

@muralidharanvenkataraman : the fix to this has been checked in.

**Comment by muralidharanvenkataraman** [comment]
thanks for the update.
