### ISSUE TITLE
[O11y][Azure Metrics] Azure Storage Account Lens migration Dashboards use wrong aggregation

### ISSUE THREAD

**Issue by kush-elastic** [elastic/integrations#7788]
- Need to remove suffix `[Azure Metrics]` from the dashboard as per this [comment](https://github.com/elastic/integrations/pull/9445#discussion_r1547153948).

- Azure Storage Account Lens migration Dashboards use the wrong aggregation.
As mentioned below dashboards and visualizations list found while doing manual lens migration.
List of dashboards:

## Queue Storage Overview dashboard
- [ ] Storage Queue Message Count
- [ ] Storage Queue  Count 

## Table Storage Overview
- [ ] Storage Table Count
- [ ] Storage Table Entity Count 

## File Storage Overview
- [ ] Storage File Count
- [ ] Storage File Share Count

## Verification and Validation
  - [ ] Verification of functionality remains the same after changing aggregation of the visualization in Kibana
  
## Screen Shots
Queue Storage Overview dashboard
![image](https://github.com/elastic/integrations/assets/89848966/b0d37b71-8bca-4869-b3d9-8b3c00983dcd)

Table Storage Overview
![image](https://github.com/elastic/integrations/assets/89848966/54411698-873b-4d7a-b27d-2978c5f8cc5c)

File Storage Overview
![image](https://github.com/elastic/integrations/assets/89848966/7665661e-b6b5-4254-b7f3-6e6fd90b44ba)

**Comment by harnish-elastic** [comment]
Need to remove suffix `[Azure Metrics]` from the dashboard while updating the aggregation as per this [comment](https://github.com/elastic/integrations/pull/9445#discussion_r1547153948).

**Comment by harnish-elastic** [comment]
Closing as completed!
