### ISSUE TITLE
[Meta] Integrations Repository Releases

### ISSUE THREAD

**Issue by EricDavisX** [elastic/integrations#78]
This issue is intended to track the process around and the schedule for when Elastic will include Integration package changes into a given release (either experimental or prod).  

It is a place-holder for now as the team hashes out some initial thoughts we can post back.  We will be interested in any feedback from contributors and consumers.

**Comment by mtojek** [comment]
Not sure what is the intention of this issue. Could you provide a sample information you'd like to see? BTW I think we used to track scope and goals differently.

**Comment by EricDavisX** [comment]
Hi, Marcin - sorry for the delay in reply.  

This is intended to host info that is public, is a best-practice for how Elastic Registry can be used, how it can be populated by packages (and relating process) and how Elastic will support its own epr.co registry to serve the Kibanas of the world.  Its not intended to tell users / admins what they can't do, but provide a layout for what has worked for us, in our internal package development.

As of this writing, we are waiting on details on a revamp of our process to be sorted out, discussed, implemented and we can post back here.  If this isn't the desired forum for hosting this, thats ok by me, I'm just looking to know what we'll do, how we'll do it, how we'll communicate to the outside world and how we'll develop packages and ship them.

We may want to form this into a 'contributing.md' in the correct Packages / Registry (or both) relating repos?  And we may want some of it in the formal Elastic Docs for 7.9 (starting from 7.8 and beyond, when Ingest Manager was released).  I'd appreciate any help on this, or if I should stand-down and let the core Integrations team take this on?  I know @ruflin is on the job and we hope to see some news within a week perhaps.

**Comment by ph** [comment]
@EricDavisX it is an ongoing issues or something we track for a specific releases?

**Comment by ph** [comment]
Yes, I think we can close this because of your proposal. cc @EricDavisX
