### ISSUE TITLE
Invalid ECS field usages at root-level

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#7808]
Across packages owned by elastic/security-external-integrations the following fields are being used at the document root, but according to ECS they are only allowed be nested under other ECS namespaces like `host` or `source`. These usages need to be changed to align with ECS. And fixing these issues will be required to move to package-spec 3.0.0.

|   Field Name               |   Usage count |
|----------------------------|---------------|
|   as.number                |   2           |
|   geo.city_name            |   6           |
|   geo.continent_name       |   4           |
|   interface.id             |   2           |
|   interface.name           |   3           |
|   os.family                |   3           |
|   os.name                  |   7           |
|   os.type                  |   2           |
|   vlan.id                  |   2           |
|   x509.issuer.common_name  |   2           |

This was detected by looking at fields.yml mappings only. It's possible that the fields are not actually used in some cases. If I accidentally included a deprecated or rsa2elk package then please ignore that field.

### Source Locations

| Package                | Data Stream     | Field                   | Github Source                                                                                                                                                    |
|------------------------|-----------------|-------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1password              | item_usages     | os.name                 | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/1password/data_stream/item_usages/fields/ecs.yml#L23             )|
| 1password              | signin_attempts | os.name                 | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/1password/data_stream/signin_attempts/fields/ecs.yml#L25         )|
| azure_frontdoor        | access          | geo.city_name           | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/azure_frontdoor/data_stream/access/fields/ecs.yml#L77            )|
| azure_frontdoor        | access          | geo.continent_name      | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/azure_frontdoor/data_stream/access/fields/ecs.yml#L69            )|
| azure_frontdoor        | waf             | geo.city_name           | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/azure_frontdoor/data_stream/waf/fields/ecs.yml#L77               )|
| azure_frontdoor        | waf             | geo.continent_name      | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/azure_frontdoor/data_stream/waf/fields/ecs.yml#L69               )|
| bluecoat               | director        | geo.city_name           | [View Source](https://github.com/elastic/integrations/blob/759ab32c525b8954dd799c1331f1a7ccedc5189e/packages/bluecoat/data_stream/director/fields/ecs.yml#L85                 )|
| carbonblack_edr        | log             | os.type                 | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/carbonblack_edr/data_stream/log/fields/ecs.yml#L67               )|
| cisco_aironet          | log             | interface.id            | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/cisco_aironet/data_stream/log/fields/ecs.yml#L53                 )|
| cisco_meraki           | events          | geo.city_name           | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/cisco_meraki/data_stream/events/fields/ecs.yml#L93               )|
| cisco_meraki           | log             | geo.city_name           | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/cisco_meraki/data_stream/log/fields/ecs.yml#L93                  )|
| cloudflare_logpush     | network_session | vlan.id                 | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/cloudflare_logpush/data_stream/network_session/fields/ecs.yml#L97)|
| crowdstrike            | fdr             | os.type                 | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/crowdstrike/data_stream/fdr/fields/ecs.yml#L121                  )|
| f5                     | bigipafm        | geo.city_name           | [View Source](https://github.com/elastic/integrations/blob/759ab32c525b8954dd799c1331f1a7ccedc5189e/packages/f5/data_stream/bigipafm/fields/ecs.yml#L85                       )|
| f5                     | bigipapm        | geo.city_name           | [View Source](https://github.com/elastic/integrations/blob/759ab32c525b8954dd799c1331f1a7ccedc5189e/packages/f5/data_stream/bigipapm/fields/ecs.yml#L85                       )|
| fireeye                | nx              | interface.name          | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/fireeye/data_stream/nx/fields/ecs.yml#L123                       )|
| infoblox_nios          | log             | interface.name          | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/infoblox_nios/data_stream/log/fields/ecs.yml#L43                 )|
| juniper_junos          | log             | geo.city_name           | [View Source](https://github.com/elastic/integrations/blob/759ab32c525b8954dd799c1331f1a7ccedc5189e/packages/juniper_junos/data_stream/log/fields/ecs.yml#L85                 )|
| juniper_netscreen      | log             | geo.city_name           | [View Source](https://github.com/elastic/integrations/blob/759ab32c525b8954dd799c1331f1a7ccedc5189e/packages/juniper_netscreen/data_stream/log/fields/ecs.yml#L85             )|
| juniper_srx            | log             | as.number               | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/juniper_srx/data_stream/log/fields/ecs.yml#L15                   )|
| juniper_srx            | log             | geo.city_name           | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/juniper_srx/data_stream/log/fields/ecs.yml#L429                  )|
| juniper_srx            | log             | geo.continent_name      | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/juniper_srx/data_stream/log/fields/ecs.yml#L431                  )|
| juniper_srx            | log             | interface.id            | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/juniper_srx/data_stream/log/fields/ecs.yml#L527                  )|
| juniper_srx            | log             | interface.name          | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/juniper_srx/data_stream/log/fields/ecs.yml#L529                  )|
| juniper_srx            | log             | os.family               | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/juniper_srx/data_stream/log/fields/ecs.yml#L663                  )|
| juniper_srx            | log             | os.name                 | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/juniper_srx/data_stream/log/fields/ecs.yml#L669                  )|
| juniper_srx            | log             | vlan.id                 | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/juniper_srx/data_stream/log/fields/ecs.yml#L1261                 )|
| juniper_srx            | log             | x509.issuer.common_name | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/juniper_srx/data_stream/log/fields/ecs.yml#L1293                 )|
| lyve_cloud             | audit           | os.name                 | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/lyve_cloud/data_stream/audit/fields/ecs.yml#L37                  )|
| netflow                | log             | as.number               | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/netflow/data_stream/log/fields/ecs.yml#L13                       )|
| netflow                | log             | geo.city_name           | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/netflow/data_stream/log/fields/ecs.yml#L287                      )|
| netflow                | log             | geo.continent_name      | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/netflow/data_stream/log/fields/ecs.yml#L289                      )|
| netflow                | log             | os.family               | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/netflow/data_stream/log/fields/ecs.yml#L471                      )|
| netflow                | log             | os.name                 | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/netflow/data_stream/log/fields/ecs.yml#L477                      )|
| panw                   | panos           | x509.issuer.common_name | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/panw/data_stream/panos/fields/ecs.yml#L283                       )|
| sentinel_one           | activity        | os.family               | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/sentinel_one/data_stream/activity/fields/ecs.yml#L37             )|
| sentinel_one           | alert           | os.name                 | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/sentinel_one/data_stream/alert/fields/ecs.yml#L39                )|
| trend_micro_vision_one | detection       | os.name                 | [View Source](https://github.com/elastic/integrations/blob/8143f223c4fb51515c05bec2e3cf04e24307e9e2/packages/trend_micro_vision_one/data_stream/detection/fields/ecs.yml#L47  )|

(List generated with an agg on top of query `@attributes.deprecated:false and @attributes.rsa2elk:false and @owner:elastic/security-external-integrations and @type:field and name:(vlan.id or geo.continent_name or os.type or interface.id or os.name or interface.name or as.number or os.name or os.name or as.number or os.family or os.type or interface.name or x509.issuer.common_name or geo.city_name)` to https://github.com/andrewkroh/go-examples/tree/main/fleetpkg-indexer)

**Comment by kgeller** [comment]
Just for my own record keeping sake I am converting the above table into a list of the integrations in need of updating

Integrations in need of update:
- [ ] 1password https://github.com/elastic/integrations/pull/7963
- [ ] azure_frontdoor
- [ ] bluecoat
- [ ] carbonblack_edr
- [ ] cisco_aironet
- [ ] cisco_meraki
- [ ] cloudflare_logpush
- [ ] crowdstrike
- [ ] f5
- [ ] fireeye
- [ ] infoblox_nios
- [ ] juniper_junos
- [ ] juniper_netscreen
- [ ] juniper_srx
- [ ] lyve_cloud
- [ ] netflow
- [ ] panw
- [ ] sentinel_one
- [ ] trend_micro_vision_one

**Comment by kgeller** [comment]
All non-deprecated packages noted above have now been updated.

**Comment by andrewkroh** [comment]
`juniper_srx` and `netflow` still have issues.

```
packages/juniper_srx/data_stream/log/fields/ecs.yml:15:3 as.organization.name
packages/juniper_srx/data_stream/log/fields/ecs.yml:81:3 code_signature.exists
packages/juniper_srx/data_stream/log/fields/ecs.yml:83:3 code_signature.status
packages/juniper_srx/data_stream/log/fields/ecs.yml:85:3 code_signature.subject_name
packages/juniper_srx/data_stream/log/fields/ecs.yml:87:3 code_signature.trusted
packages/juniper_srx/data_stream/log/fields/ecs.yml:89:3 code_signature.valid
packages/juniper_srx/data_stream/log/fields/ecs.yml:367:3 hash.md5
packages/juniper_srx/data_stream/log/fields/ecs.yml:369:3 hash.sha1
packages/juniper_srx/data_stream/log/fields/ecs.yml:371:3 hash.sha256
packages/juniper_srx/data_stream/log/fields/ecs.yml:373:3 hash.sha512
packages/juniper_srx/data_stream/log/fields/ecs.yml:555:3 pe.architecture
packages/juniper_srx/data_stream/log/fields/ecs.yml:557:3 pe.company
packages/juniper_srx/data_stream/log/fields/ecs.yml:559:3 pe.description
packages/juniper_srx/data_stream/log/fields/ecs.yml:561:3 pe.file_version
packages/juniper_srx/data_stream/log/fields/ecs.yml:563:3 pe.imphash
packages/juniper_srx/data_stream/log/fields/ecs.yml:565:3 pe.original_file_name
packages/juniper_srx/data_stream/log/fields/ecs.yml:567:3 pe.product
packages/netflow/data_stream/log/fields/ecs.yml:13:3 as.organization.name
packages/netflow/data_stream/log/fields/ecs.yml:283:3 geo.city_name
packages/netflow/data_stream/log/fields/ecs.yml:285:3 geo.continent_name
packages/netflow/data_stream/log/fields/ecs.yml:287:3 geo.country_iso_code
packages/netflow/data_stream/log/fields/ecs.yml:289:3 geo.country_name
packages/netflow/data_stream/log/fields/ecs.yml:291:3 geo.location
packages/netflow/data_stream/log/fields/ecs.yml:293:3 geo.name
packages/netflow/data_stream/log/fields/ecs.yml:295:3 geo.region_iso_code
packages/netflow/data_stream/log/fields/ecs.yml:297:3 geo.region_name
packages/netflow/data_stream/log/fields/ecs.yml:305:3 hash.md5
packages/netflow/data_stream/log/fields/ecs.yml:307:3 hash.sha1
packages/netflow/data_stream/log/fields/ecs.yml:309:3 hash.sha256
packages/netflow/data_stream/log/fields/ecs.yml:311:3 hash.sha512
packages/netflow/data_stream/log/fields/ecs.yml:467:3 os.family
packages/netflow/data_stream/log/fields/ecs.yml:469:3 os.full
packages/netflow/data_stream/log/fields/ecs.yml:471:3 os.kernel
packages/netflow/data_stream/log/fields/ecs.yml:473:3 os.name
packages/netflow/data_stream/log/fields/ecs.yml:475:3 os.platform
packages/netflow/data_stream/log/fields/ecs.yml:477:3 os.version
```
