### ISSUE TITLE
[SEI] Integrations requiring manual testing for spec 3.0

### ISSUE THREAD

**Issue by P1llus** [elastic/integrations#7814]
This is a list of integrations that should be manually tested to some extent, what should be tested is listed below each integration, this extends the amount of testing already listed in the communicated list of tests.

- [x] network_traffic: Includes custom data-view/index pattern. Once installed, ingest some data to ensure that the data-view in the dashboards are still assigned correctly. Also ensure that the data-view is in the list of available data-views in for example the data-view list.

- [x] ti_maltiverse: Has its own ILM (that should be converted) and transforms, need to ensure the transforms are installed and running after the integration is configured. Try to add in at least one sample document as well, either manually or through the agent system tests.

- [x] ti_anomali: Has its own ILM (that should be converted) and transforms, need to ensure the transforms are installed and running after the integration is configured. Try to add in at least one sample document as well, either manually or through the agent system tests.

- [x] ti_recorded_future Has its own ILM (that should be converted) and transforms, need to ensure the transforms are installed and running after the integration is configured. Try to add in at least one sample document as well, either manually or through the agent system tests.

- [x] ti_rapid7: Has its own security detection rules, while these should be removed at some point as they are somewhat duplicates of the built-in SIEM rules for indicator match, currently we need to ensure they are installed and available in the SIEM UI.

- [x] cel: Input type package, try to change common options there like dataset name or ingest pipeline, ensure that they are applied to the relevant index templates and data still comes in.

- [x] 1-2 integrations that uses dynamic ECS templates (import_mappings: true in build.yml). For simplicity we could pick any that has log/file input for example, to simplify the process. We should ensure the dynamic template is added correctly to its relevant index templates, and that the results are as we expect them to be

**Comment by kcreddy** [comment]
**ti_recordedfuture**
- Transforms:
    - [x] Installed: Transform is getting installed correctly when integration is installed.
    - [x] Running: Transform automatically starts running in continuous mode as expected.
    - [x] Data Ingestion: Indicators are correctly ingested into source datastream.
    - [x] Transform working: Latest transform able to move latest indicators into new destination index.
    - [ ] ILM: ILM is missing on source datastream. Since ILM policies cannot be viewed navigating via UI here, this is a screenshot taken from Project Settings -> Index Management -> Data streams -> select "logs-ti_recordedfuture.threat-default"
<img width="484" alt="Screenshot 2023-09-14 at 2 40 03 PM" src="https://github.com/elastic/integrations/assets/11301409/a5f0021d-8b3d-4090-9d9d-42feb0c327af">

**Comment by P1llus** [comment]
@kcreddy the ILM policies needs to be changed to DLM 👍

**Comment by kcreddy** [comment]
@P1llus Considering the warning for ti_rapid7 [above](https://github.com/elastic/integrations/issues/7814#:~:text=The%20rules%20complains%20about%20possible%20lack%20of%20permission%20for%20**%20indices%20which%20the%20rule%20is%20trying%20to%20read) , I haven't merged its PR. Should I update the rule's index pattern to `"auditbeat-*", "endgame-*", "filebeat-*", "logs-*", "packetbeat-*", "winlogbeat-*"` instead of `**`?

**Comment by P1llus** [comment]
@kcreddy at some point we should just remove the rules, from what I understand they are a copy of the rules already included by default. @jamiehynds wdyt?

**Comment by kcreddy** [comment]
Hey @P1llus, based on Andrew's suggestion, I updated the indices with prebuilt Indicator Match Rules index patterns.

**Comment by andrewkroh** [comment]
What is the status on the last remaining bullet ("1-2 integrations that uses dynamic ECS templates")? Is this done?

**Comment by kcreddy** [comment]
Verified by installing `Custom Azure Blob Storage` and `ZScaler ZIA` integrations which both have dynamic ECS templates `(import_mappings: true in build.yml)`:

- [x] Installation: Able to install and find the dynamic templates `_embedded_ecs-*`
- [x] Tests: Ran system tests successfully. Checked the fields are getting applied the expected dynamic mapping.
