### ISSUE TITLE
Move winlog package to `type: input`

### ISSUE THREAD

**Issue by hop-dev** [elastic/integrations#7820]
The [winlog](https://github.com/elastic/integrations/blob/fb1a574e9e7e6d76bd5f6307bc9ae53135da77f7/packages/winlog) pacage allows dataset to be customized, it should therefore be migrated to an input package, the same as custom logs or promethius_input.

**Comment by jlind23** [comment]
@P1llus @narph is there any specific label I should add in order to let you take care of this?
