### ISSUE TITLE
Azure Event Hub Input Package

### ISSUE THREAD

**Issue by muthu-mps** [elastic/integrations#7821]
- Enhancement

This PR is to create new input package for Azure Event Hubs to collect logs exported from the Azure services.

**Comment by muthu-mps** [comment]
@Linu-Elias has started looking into this issue. 
- As we plan to create a custom Event hub input we may need to think of how do we show the new input in Kibana.
- This input will use the `routing_rules` to route data from different log type to a specific data stream.
- Once @zmoog shares the design document, We will have more clarity on the pain points to be addressed as part of the new event hub input.

cc: @zmoog

**Comment by zmoog** [comment]
@muthu-mps, it seems input packages [don't support](https://github.com/elastic/package-spec/blob/main/spec/input/spec.yml) `routing_rules.yml`. Since they don't support data stream as well, I am struggling to find a way to add a pipeline with reroute processor OOTB.

Any suggestion?

**Comment by ishleenk17** [comment]
> [@muthu-mps](https://github.com/muthu-mps), it seems input packages [don't support](https://github.com/elastic/package-spec/blob/main/spec/input/spec.yml) `routing_rules.yml`. Since they don't support data stream as well, I am struggling to find a way to add a pipeline with reroute processor OOTB.
> 
> Any suggestion?

@zmoog : Ideally in Input Packages, we don't want to add any OOTB Pipeline, We leave it upto the user.
Which specific pipeline is a pre requisite for this Input Package ?

**Comment by zmoog** [comment]
> > [@muthu-mps](https://github.com/muthu-mps), it seems input packages [don't support](https://github.com/elastic/package-spec/blob/main/spec/input/spec.yml) `routing_rules.yml`. Since they don't support data stream as well, I am struggling to find a way to add a pipeline with reroute processor OOTB.
> > Any suggestion?
> 
> [@zmoog](https://github.com/zmoog) : Ideally in Input Packages, we don't want to add any OOTB Pipeline, We leave it upto the user. Which specific pipeline is a pre requisite for this Input Package ?

In a previous [comment](https://github.com/elastic/integrations/issues/7821#issuecomment-2236219006), we say:

> This input will use the routing_rules to route data from different log type to a specific data stream.

If I'm not missing something, input packages do not support routing_rules.yml or pipeline to provide OOTB routing capabilities in this input. So I guess we can't "route data from different log type to a specific data stream". 

I wanted to bring this up if you will update the input specs.

**Comment by zmoog** [comment]
We [released](https://github.com/elastic/integrations/pull/11552#issuecomment-2464543958) v0.1.0 of the Custom Azure Logs input package on Nov 8.
