### ISSUE TITLE
Add checks to rename processor for the message field for all Observability Integrations

### ISSUE THREAD

**Issue by ishleenk17** [elastic/integrations#7822]
This ticket is created as a followup of https://github.com/elastic/integrations/issues/3451 
The rename processor (renaming message to event.original) in the ingest pipelines for log datastreams don't have an if/ignore_missing check

**Current state:** 
- rename:
    field: message
    target_field: event.original

**Expected State:** 
- rename:
      field: message
      target_field: event.original
      ignore_missing: true
      if: 'ctx.event?.original == null'
     description: 'Renames the original `message` field to `event.original` to store a copy of the original message. The `event.original` field is not touched if the document already has one; it may happen when Logstash sends the document.'

Below are the Observability Integrations which need this change

#### Phase1 updates: 

- [x] apache https://github.com/elastic/integrations/pull/7845/ 
- [x] apache_tomcat https://github.com/elastic/integrations/pull/7845/
- [x] cassandra https://github.com/elastic/integrations/pull/7845/
- [x] ceph https://github.com/elastic/integrations/pull/7845/
- [x] citrix_adc https://github.com/elastic/integrations/pull/7845/
- [x] golang https://github.com/elastic/integrations/pull/7845/
- [x] hadoop https://github.com/elastic/integrations/pull/7845/
- [x] haproxy https://github.com/elastic/integrations/pull/7845/
- [x] iis https://github.com/elastic/integrations/pull/7845/
- [x] kafka https://github.com/elastic/integrations/pull/7845/
- [x] microsoft_sqlserver https://github.com/elastic/integrations/pull/7845/
- [x] nginx https://github.com/elastic/integrations/pull/7845/
- [x] oracle https://github.com/elastic/integrations/pull/7845/
- [x] oracle_weblogic https://github.com/elastic/integrations/pull/7845/
- [x] php_fpm https://github.com/elastic/integrations/pull/7845/
- [x] postgresql https://github.com/elastic/integrations/pull/7845/
- [x] rabbitmq https://github.com/elastic/integrations/pull/7845/
- [x] redis https://github.com/elastic/integrations/pull/7845/
- [x] traefik https://github.com/elastic/integrations/pull/7845/
- [x] nagios_xi https://github.com/elastic/integrations/pull/7845/

#### Cloud Monitoring: 

- [x] aws https://github.com/elastic/integrations/pull/7933
- [x] azure_frontdoor https://github.com/elastic/integrations/pull/7953
- [x] gcp https://github.com/elastic/integrations/pull/7934

#### Cloud Native: 

- [x] istio https://github.com/elastic/integrations/pull/7956
- [x] nats https://github.com/elastic/integrations/pull/7956
- [x] nginx_ingress_controller https://github.com/elastic/integrations/pull/7956
- [x] stan https://github.com/elastic/integrations/pull/7956

#### Phase2 updates: 

- [x] activemq https://github.com/elastic/integrations/pull/8624
- [x] coredns https://github.com/elastic/integrations/pull/8624
- [x] ibmmq https://github.com/elastic/integrations/pull/8624
- [x] mongodb https://github.com/elastic/integrations/pull/8624
- [ ] mysql https://github.com/elastic/integrations/issues/8626
- [x] salesforce https://github.com/elastic/integrations/pull/8624
- [x] spring_boot https://github.com/elastic/integrations/pull/8624
~~- [ ] tomcat~~ Will soon be deprecated.
- [x] vsphere https://github.com/elastic/integrations/pull/8624

**Comment by lalit-satapathy** [comment]
Adding @ritalwar for phase 2.

**Comment by ritalwar** [comment]
Implemented null checks for all the mentioned packages in this [PR](https://github.com/elastic/integrations/pull/8624). 

Due to the upcoming deprecation of Tomcat Netwitness logs, with a recommendation to switch to Apache Tomcat, we won't include these checks there.

As of now, there is no existing rename or set processor to manage event.original in the MySQL package. This will be taken care in a separate [issue](https://github.com/elastic/integrations/issues/8626). Therefore, I'm closing this one.
