### ISSUE TITLE
The overview tab for Fleet Server integration is empty.

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/integrations#787]
**Describe the bug**
The overview tab for Fleet Server integration is empty

**Build Details:**
```
Version: 7.12.0 BC4
Commit: 99ac38d70e426f589bb61a034c96e602d759cfab
Build number: 39242
Artifact: https://staging.elastic.co/7.12.0-336ff10d/summary-7.12.0.html
```

**Browser Details**
All

**Preconditions**
1. Elastic Cloud 7.12.0 environment should be deployed

**Steps to Reproduce**
1. Navigate to the Integrations tab under fleet
2. Select the Fleet Server integration
3. Observe the overview page is empty.

**Test data**
N/A

**Impacted Test case(s)**
N/A

**Actual Result**
The overview tab for Fleet Server integration is empty

**Expected Result**
The overview tab for Fleet Server integration should show related details

**What's Working**
Works for other integrations:
![Windows](https://user-images.githubusercontent.com/60252716/110760941-38c2b100-8275-11eb-87e4-da0edf92e612.PNG)

**What's not Working**
N/A

**Screenshot**
![FleetServerPackageOvervieww](https://user-images.githubusercontent.com/60252716/110760821-1fba0000-8275-11eb-8c3b-36c70e4c3ed2.PNG)

**Logs**
N/A

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by ph** [comment]
@skh is right.  Going to keep it open and redirect it to the Agent work.

**Comment by EricDavisX** [comment]
I think it would be worthwhile to push a manifest change and new package version to prod for Fleet-server package to be ^7.13.0 so we don't end up with accidental usage in 7.12 when we know it won't work due to known issues?  @ph ... and the docs work too, need that at some point.  :)

**Comment by mostlyjason** [comment]
@ph can we just get a short description here in 7.13 so it doesn't look broken? Here is some content you can plug in:

> Fleet Server is a component of the Elastic Stack used to centrally manage Elastic Agents. It’s launched as part of an Elastic Agent on a host intended to act as a server. One Fleet Server process can support many Elastic Agent connections, and serves as a control plane for updating agent policies, collecting status information, and coordinating actions across Elastic Agents. 
> 
> To add this integration to an Elastic Agent, just add it to an agent policy. The Elastic Agents enrolled into that policy must run with additional credentials such as a service token. Learn how to add a Fleet Server our [documentation](https://www.elastic.co/guide/en/fleet/current/fleet-server.html).
>
> **Compatibility**
> Fleet Server is compatible with the Elastic Stack and Elastic Agents version 7.13 or higher.

**Comment by ruflin** [comment]
@mostlyjason Want to directly open a PR?

**Comment by urso** [comment]
@mostlyjason `s/and serves as a control plane for //`

**Comment by muskangulati-qasource** [comment]
Hi @mostlyjason,

We tested this ticket on the latest 7.13.0 BC9 build & found that issue is still occuring. Please find below the exact testing details:

**Build Details**:
```
VERSION: 7.13.0 BC9
BUILD: 40865
COMMIT: 9863e88bd63ad546b9d36e6b0c0c55cb65dd9081
ARTIFACT: https://staging.elastic.co/7.13.0-c04b1ebc/summary-7.13.0.html
```

**Screenshots**
![Overview](https://user-images.githubusercontent.com/60252716/118937839-948f7180-b96b-11eb-91f4-8823e39b4f4e.JPG)

Can you please confirm if there is one more BC lined up or is the merge going to next release??

Thanks

**Comment by mostlyjason** [comment]
@ruflin @urso can you help me with a backport to 7.13? I'm not familiar with the process.

**Comment by ruflin** [comment]
@mostlyjason Already in progress. It's not a backport is a promotion ;-) https://github.com/elastic/package-storage/pull/1350

**Comment by jen-huang** [comment]
This is now fixed, closing:

![image](https://user-images.githubusercontent.com/1965714/126022015-7a079cae-b7d4-43b7-a3d2-5dca97cc5c00.png)
