### ISSUE TITLE
[cisco_secure_email_gateway] Missing event.start mapping

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#7877]
It appears that a mapping is missing for `event.start` in the cisco_secure_email_gateway integration.

<img width="747" alt="Screenshot 2023-09-19 at 14 35 55" src="https://github.com/elastic/integrations/assets/4565752/2d6eda45-1ca7-476e-8b09-fd31d9aa600f">

**Comment by efd6** [comment]
Fixing this in #7809. The issue is that `event.{start,end}` are not converted to a date.
