### ISSUE TITLE
Table format is broken on "Elastic Agent" integration "Overview" page.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#792]
**Kibana version:** Kibana: 7.12.0 BC-4 Kibana Cloud environment

**Build Details:**
```
    Build: 39242
    Commit: 99ac38d70e426f589bb61a034c96e602d759cfab
```

**Preconditions:**
1. 7.12.0 BC-4 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Integrations and search for "Elastic Agent".
3. Click on "Elastic Agent" integration.
4. Scroll down on "Elastic Agent"  overview page till Metrics>process.
5. Observe broken table formatting.

**Expected Result:**
Table format should not be broken on "Elastic Agent" integration "Overview" page.

**Screenshots:**
![3](https://user-images.githubusercontent.com/77374876/111306580-6301dd80-867e-11eb-8498-d1d3a62c5669.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @EricDavisX

**Comment by EricDavisX** [comment]
@ph what do you think?

**Comment by ph** [comment]
thanks @nchaulet for looking into this, is that a problem in our markdown handling or a formatting error in the integration packages?

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 

We have revalidated this on 7.14.0 Snapshot and found it **fixed**.

**Observation:**
Metrics and Process information is now available in tabular format for "Elastic Agent" integration under "Overview" page.

**Screenshot:**
![3](https://user-images.githubusercontent.com/77374876/121310510-121e2000-c921-11eb-8455-62254e5c798c.JPG)

Thanks
QAS
