### ISSUE TITLE
Make Kubernetes integration settings resource centric

### ISSUE THREAD

**Issue by mlunadia** [elastic/integrations#7936]
## Context
Kubernetes has several endpoints where Observability data is collected by Elastic Agent as instructed in the Kubernetes integration. The current Kubernetes integration settings revolve around this variety of endpoints and Elastic data streams that are not self-explanatory about the data they collect and ingest. 

This results in users having to gain expertise on how Kubernetes exposes telemetry data and the Kubernetes integration different data streams if they want to tailor their ingestion according to their needs.

## User experience
As an Elastic Agent user I want to collect and ingest Kubernetes containers' telemetry.
 
### Current flow
A user has to edit the integration policy whilst understanding that container telemetry is collected under 3 different sections: 

- kubelet > container metrics
- kube-state-metrics > container metrics
- container logs > /var/log/containers/*${kubernetes.container.id}.log

They will then need to go deep into the [Kubernetes Integration documentation](https://docs.elastic.co/integrations/kubernetes-intro) and find the data in each data stream to understand the difference between metrics collected from kubelet and ksm so they can decide which data is relevant.

![image](https://github.com/elastic/integrations/assets/39376769/897e3ff1-b367-4305-b79b-453379da5b1c)

#### Kubernetes Container metrics - Different data yet the same ambiguous title
<img width="705" alt="image" src="https://github.com/elastic/integrations/assets/39376769/a72d8010-667c-40c4-b935-81677b4bf178">
<img width="662" alt="image" src="https://github.com/elastic/integrations/assets/39376769/bad5e84b-084c-4e61-8a94-19b6a591b015">

### User-centric flow (requirements)
As an Elastic Agent user I want to collect and ingest Kubernetes telemetry with user prompts centered around the assets I want to monitor (eg. containers) so that I don't have to learn how Kubernetes exposes telemetry and how the Elastic integration is implemented.

![image](https://github.com/elastic/integrations/assets/39376769/161b1164-c7ea-4c19-a874-a48a24fb475c)

**Comment by gizas** [comment]
Outcome of analysis: Diffrent input types can not be grouped under same title. So for eg. for containers we can not group container_logs and container metrics as belong to diffrent input type.

See draft PR #9171 

Let me know if you like the outcome the changes below

![Screenshot 2024-02-15 at 5 16 24 PM](https://github.com/elastic/integrations/assets/1685415/d2929039-1ca1-40dd-a0b3-bac0bcf439fb)

**Comment by mlunadia** [comment]
@gizas is there a sub menu underneath these options? I'm thinking about things like where would users configure ingestion from kube-state-metrics?

**Comment by gizas** [comment]
All the sub menus are the same as the current integration. Nothing changes underneath. 
We only change the grouping of options and labels

**Comment by gizas** [comment]
Indeed this is what is already happening, you need to provide config per datastream

**So in the latest update, Containers> You change the state_container datastream**
![Screenshot 2024-04-23 at 1 57 30 PM](https://github.com/elastic/integrations/assets/1685415/f7b0baaa-5844-4ec1-baeb-be752e8f90fa)

**Inside Pods > You can change the state_cronjob, state_daemonset etc**
![Screenshot 2024-04-23 at 1 58 06 PM](https://github.com/elastic/integrations/assets/1685415/6065ae47-259a-4229-b198-46695a5cf882)

**Comment by mlunadia** [comment]
Sounds good, if we are confident with the testing for green and updates let's move forward with the change. Good work on this one!

**Comment by gizas** [comment]
Thanks @mlunadia . Please approve this https://github.com/elastic/integrations/pull/9171 in order to merge this

**Comment by gizas** [comment]
Closing this issue as the related changes in the Integration side imply that the new policy needed will introduce breaking changes for our users in case of upgrading from previous versions of the integration. 

In more details, the new policy will include new ids and datasets groups that can not be matched with existing policy ids. Thus during the upgrade the integration will start with default values in datastreams with new ids and might lead to data loss for our users that have applied configuration other than the default
