### ISSUE TITLE
[O11y][System]: Improve descriptions in documentation

### ISSUE THREAD

**Issue by shmsr** [elastic/integrations#7950]
While reviewing https://github.com/elastic/integrations/pull/7941 I came across some field descriptions that are not correct. 

For example:
> The total number of of milliseconds spent doing I/Os.

There are two errors:

- Repetition of `of`
- The usage of `milliseconds` in this context is not precise; could be better. For example: "The total amount of time (measured in milliseconds) spent doing I/Os."

There are many such descriptions that could be improved.

**Comment by bmorelli25** [comment]
@shmsr Where are these field descriptions sourced from? I'm wondering if this might be something that a technical writer can pick up.

**Comment by shmsr** [comment]
@bmorelli25 

Here: https://github.com/elastic/integrations/blob/2afadab8e1a58c92416c9bc640aa8f0e9a28d169/packages/system/data_stream/diskio/fields/fields.yml

See the last line?

Inside the `system` package, I think there would be more such errors in field descriptions.

**Comment by bmorelli25** [comment]
Ah. Okay, thanks. I wasn't sure if field descriptions were sourced from ECS or somewhere else.

**Comment by alaudazzi** [comment]
@shmsr I fixed the wording as discussed. I think I covered all the occurrences, but please let me know if I missed anything.
