### ISSUE TITLE
7.11.2 - Integrations Cisco - Agent cannot parse RFC 5424 timestamps

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/integrations#796]
Hi all,
Investigating further my previous created issues, I notice, that the agent cannot parse RFC 5424 formatted timestamps.
I have tons of logs in the filebeat_monitor-json.log saying:

`{"log.level":"error","@timestamp":"2021-03-22T13:31:24.675+0100","log.logger":"jsonhelper","log.origin":{"file.name":"jsontransform/jsonhelper.go","file.line":62},"message":"JSON: Won't overwrite @timestamp because of parsing error: parsing time \"2021-03-22T13:31:24.301+0100\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"+0100\" as \"Z07:00\"","ecs.version":"1.6.0"}
`

Also, I don't know, why it wants to parse it as year 2006. I unfortunately see, from which original message this error comes from (hints welcomed :) ). 

Cheers,
Marcus

**Comment by jamiehynds** [comment]
Closing, as we've since added support for RFC5424.
