### ISSUE TITLE
[Elastic Agent] TSDB metrics dimensions do not create unique time series

### ISSUE THREAD

**Issue by cmacknz** [elastic/integrations#7977]
There are currently not enough TSDB dimensions for Elastic Agent metrics to create unique time series.

Looking at the filebeat metrics data stream for example, the only defined dimension is `agent.id`:

https://github.com/elastic/integrations/blob/9e5b21d12cb868bd08c5b8017e6e3ee285f56ba6/packages/elastic_agent/data_stream/filebeat_metrics/fields/ecs.yml#L7-L9

Other Beats use both `agent.id` and `service.address`, looking at metricbeat for example:

https://github.com/elastic/integrations/blob/9e5b21d12cb868bd08c5b8017e6e3ee285f56ba6/packages/elastic_agent/data_stream/metricbeat_metrics/fields/ecs.yml#L7-L9

https://github.com/elastic/integrations/blob/9e5b21d12cb868bd08c5b8017e6e3ee285f56ba6/packages/elastic_agent/data_stream/metricbeat_metrics/fields/ecs.yml#L18-L20

Even the addition of the `service.address` field does not help because it is frequently the same given the address can be a named pipe on Windows, for example:

```json
  "agent": {
    "name": "agent",
    "type": "metricbeat",
    "version": "8.9.1"
  },
  "service": {
    "name": "beat",
    "type": "beat",
    "address": "http://npipe/stats"
  },
```

The dimensions used need to handle the cases where:

1. There are multiple instances of a beat running, as is usually the case for Filebeat and Metricbeat running under agent. To tell the different instances apart I believe we'll need to start reporting the `component.id` field from Elastic Agent, which is currently only present in the logs data streams: 

https://github.com/elastic/integrations/blob/9e5b21d12cb868bd08c5b8017e6e3ee285f56ba6/packages/elastic_agent/data_stream/elastic_agent_logs/fields/fields.yml#L28-L35

2. Multiple metricsets are written to the same datastream by the same process. The monitoring Beats configured by agents collect both the `state` and `stats` output from each Beat and this data can be written in the same second. For example see the two metrics reports below with the same timestamp from the same Beat:

```json
{
  "metricset": {
    "name": "stats",
    "period": 10000
  },
  "@timestamp": "2023-09-14T13:31:36.083Z",
  "elastic_agent": {
    "process": "filebeat",
    "snapshot": false,
    "version": "8.9.1"
  },
  "beat": {
    "type": "filebeat",
    "id": "14594cde-9309-4c9d-9f31-ce366c0d523a",
    "stats": {
      "system": {
        "cpu": {
          "cores": 8
        },
        "handles": {
          "open": 284
        }
      }
    }
  }
}
```
```json
{
  "metricset": {
    "name": "state",
    "period": 10000
  },
  "@timestamp": "2023-09-14T13:31:36.083Z",
  "elastic_agent": {
      "process": "filebeat",
      "snapshot": false,
      "version": "8.9.1"
  },
  "beat": {
    "state": {
      "beat": {
        "type": "filebeat",
      },
      "management": {
        "enabled": true
      },
      "output": {
        "name": "logstash"
      },
      "queue": {
        "name": "mem"
      }
    }
  }  
}
```

**Comment by joshdover** [comment]
> 1. To tell the different instances apart I believe we'll need to start reporting the `component.id` field from Elastic Agent, which is currently only present in the logs data streams:

I just noticed this while debugging some metrics in production. This is resulting in the Elastic Agent dashboards and Fleet UI being completely inaccurate if there are multiple input types that use the same binary. I have a draft PR I can push that has just this part of the change as a jumping off point @belimawr

**Comment by joshdover** [comment]
@kpollich We will need to adjust Fleet's metric queries once this change rolls out. We need to decide how it should work with older agents that aren't reporting this field. I'm not sure if reporting wrong metrics is worse than no metrics. There are some use cases where the metrics are correct, so maybe we just need to make sure the query works with and without this field present.
