### ISSUE TITLE
[Carbon Black Cloud] API Updates

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#7997]
Our Carbon Black Cloud integration currently relies on Alerts API (v6), Audit Log Events (v3) and Vulnerability Assessment (v1) API's from Carbon Black. 

**Alerts API**: Carbon Black have announced deprecation of the Alerts API v6. We need to migrate to Alerts API v7. More information available here: [Alerts API V7](https://developer.carbonblack.com/2023/06/announcing-vmware-carbon-black-cloud-alerts-v7-api/). They also announced a new [Data Forwarder schema](https://developer.carbonblack.com/2023/07/announcing-the-v2-alert-data-forwarder-schema/) which mirrors the v7 API. We could look at this as an alternative to the API. 

**Audit logs:** The Audit Log API has been updated to authenticate using a Custom type API key that has been granted the org.audits permission. The legacy API type key has been deprecated and will continue to work for at least 12 months from July 2023. _Any changes required on our end?_ 

For more information on the API deprecation and migration steps, please see here: [Carbon Black API Migration Guide](https://developer.carbonblack.com/reference/carbon-black-cloud/api-migration)

**Comment by jamiehynds** [comment]
FYI @piyush-elastic to add to our enhancements backlog.

**Comment by ShourieG** [comment]
@jamiehynds @narph  The migration to v7 will be a breaking change as there has been a very big update to the base alerts schema from v6 -> v7 as documented [here](https://developer.carbonblack.com/reference/carbon-black-cloud/guides/api-migration/alerts-migration/). The alert type "**Observed Alerts**" has also been removed completely from the v7 Alert search api as documented [here](https://carbonblack.vmware.com/blog/announcing-alerts-v7-api-and-%E2%80%9Cobserved-alerts%E2%80%9D-become-%E2%80%9Cobservations%E2%80%9D), however they will continue to exist for the v6 apis. As for the **data forwarder** api, we already support v1 data forwarder api via s3 buckets, updating the mappings for v7 schema should automatically support the **data forwarder v2** api as documented [here](https://developer.carbonblack.com/2023/07/announcing-the-v2-alert-data-forwarder-schema/). 

This however is not a trivial change as  there are many new base fields added and some old fields and alert types removed. We need to overhaul the entire mapping for the alerts schema carefully to match the v7 schema, update our pipeline and system tests accordingly.

**Comment by jamiehynds** [comment]
@ShourieG thanks for the initial research. Although it's a breaking change, I don't think we can avoid it on our side given that the changes we're making on our side reflect the updates to the v7 API. The v6 API is due for deactivation on July 31st, so at least we have some time before that hard cut off.
