### ISSUE TITLE
[Proposal] Fleet Go Client

### ISSUE THREAD

**Issue by jalvz** [elastic/integrations#800]
We have a number of projects consuming the Kibana Fleet API from Go. Some that I know of: [elastic-package](https://github.com/elastic/elastic-package), [e2e-testing](https://github.com/elastic/e2e-testing), [apm-server](https://github.com/elastic/apm-server), [apm-integration-testing](https://github.com/elastic/apm-integration-testing). 

I'd expect more projects will need it, and the maintenance burden to increase as Fleet evolves. I'd like to suggest a Fleet Go Client that all projects can benefit from. 
The most complete implementation at the time of writing appears to be [elastic-package](https://github.com/elastic/elastic-package/tree/master/internal/kibana). We could start from there, and eventually auto-generate the code out of the [API spec](https://github.com/elastic/kibana/blob/master/x-pack/plugins/fleet/common/openapi/bundled.json).

Thoughts?

**Comment by ycombinator** [comment]
++ to this idea. It might also help with providing a single interface to the original Kibana Fleet API and the newer Fleet Server Fleet API.

**Comment by jfsiii** [comment]
:kool_aid_man: did someone say OpenAPI? 

I'm more familiar with the choices for golang servers than clients, but there is [a golang client](https://openapi-generator.tech/docs/generators/go) for OpenAPI Generator. [The docs have examples](https://openapi-generator.tech/#try) for trying the generator locally with `npm`, `brew`, or `docker`. 

Even if we choose to write a client versus using a generated one, that code can still benefit from importing the published spec. 

[bundled.json](https://raw.githubusercontent.com/elastic/kibana/master/x-pack/plugins/fleet/common/openapi/bundled.json) has some small gaps but should work great. I'm happy to hear about new users & use cases. Please file any issues with the spec/types in https://github.com/elastic/kibana & label with `Team:Fleet`

**Comment by jalvz** [comment]
Excellent, thanks @jfsiii !

**Comment by jalvz** [comment]
Very late update (sorry for that):

I gave this a shot a couple of months ago (see backlink above), but unfortunately code generation doesn't work 100%... it's more like 95%, but even if it is easy enough to glue by hand the broken bits, it means that it will take a bit more effort to maintain than what I hoped.

Another option would be to extract the relevant code out of elastic-package. 
I think that either way, it would be good  to unify how we approach the Fleet API given the sprawling number of projects using it, and that everyone needs to keep up with API changes, support any versions, etc.

**Comment by ruflin** [comment]
++ on coming up with a single Kibana client. I would expect it at first to only contain the functions really needed but it could be shared across multiple projects. Starting to extract it from elastic-agent sounds like a good idea.

**Comment by ycombinator** [comment]
> Starting to extract it from elastic-agent sounds like a good idea.

@ruflin Did you mean elastic-package? 📎

**Comment by ruflin** [comment]
Yes 🤦 But to be fair, elastic-agent also has Kibana bits inside ...

**Comment by Mpdreamz** [comment]
cc @Anaethelion I know generating go clients has your focus now too.

**Comment by andrewkroh** [comment]
I have been experimenting with generating some Go client code based on the OpenAPI definition for a small subset of the Fleet APIs. I was trying out github.com/deepmap/oapi-codegen/cmd/oapi-codegen.

https://github.com/andrewkroh/terraform-provider-elasticstack/tree/feature/fleet-resource/internal/clients/kibana/fleet/fleetapi
