### ISSUE TITLE
[Custom HTTP Endpoint] Supporting PUT method

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#8066]
The current custom [HTTP endpoint integration (http_endpoint) ](https://docs.elastic.co/integrations/http_endpoint)accepts only the `post` HTTP method. Some vendors who support pushing to a http endpoint don't support `post`, and rely on using `put` or `patch`

Can we add support to our HTTP Endpoint integration to accept `put` and `patch`. We also need to ensure we document that you don’t get the HTTP semantics for `patch` (updates) and `put` (idempotent).

**Comment by efd6** [comment]
@jamiehynds The necessary change to filebeat has been merged and will be in 8.12 when it is released. At that point we can add the configuration option to the integration either with documentation explaining that it is only meaningful on an 8.12 agent, or we can limit by stack version.

**Comment by zez3** [comment]
@efd6 
Did this caught the 8.12 release?

I am on 8.12.2 and it looks like it's not working as I get `HTTP/1.1 405 Method Not Allowed\r\n`

**Comment by zez3** [comment]
@jamiehynds I think we still need a change in the integration
