### ISSUE TITLE
[Change Proposal] Add processor descriptions to Elastic-provided ingest node pipelines

### ISSUE THREAD

**Issue by cjcenizal** [elastic/integrations#807]
## Problem

There's a new-ish feature in the Ingest Node Pipelines UI that allows you to define a `description` for each individual processor in a pipeline (https://github.com/elastic/elasticsearch/pull/57906). A Kibana user has recently complained that none of the pipelines we ship use this feature, which makes it difficult for them to understand what a pipeline is doing (https://github.com/elastic/kibana/issues/94432). We have an opportunity to provide a more pleasant and productive UX to our users by updating our Elastic-provided pipelines with processor descriptions. Here's a visual example of the opportunity:

![image](https://user-images.githubusercontent.com/1238659/112362155-5c342580-8c91-11eb-9a9d-1e2391c17e6d.png)

## Solution

This solution requires updating the pipelines provided by Elastic with `description` content for each processor. This description will help users understand the purpose of a processor in the context of its pipeline.

**Comment by ycombinator** [comment]
I'm ++ for the immediate action to be adding a recommendation in the package contributing documentation, specifically [this section](https://github.com/elastic/integrations/blob/master/docs/fine_tune_integration.md), about adding descriptions to ingest pipeline processors.

@mtojek as part of working on https://github.com/elastic/elastic-package/issues/3, do you plan to create a sample/fake Elasticsearch ingest pipeline? If so, maybe that could include a sample processor with a description field that says "TODO" or something?

Also ++ on longer term having `elastic-package lint` be able to show warnings (right now it either passes or fails), and one of these warnings could be when it detects ingest pipeline processors with no descriptions. I've created https://github.com/elastic/elastic-package/issues/298 to track this.

**Comment by andrewkroh** [comment]
I think for the majority of the processors it would be possible to generate a useful description if one is not specified in the pipeline. For example, a convert processor for source.port to long could show "convert source.port to long" which provides a lot of context when viewing the pipeline. As package developers I think we would find it difficult to maintain descriptions like this if we put them into every pipeline.

In pipelines we should do more to provide descriptions for things like `script` processors that can be doing anything.

**Comment by cjcenizal** [comment]
I've created https://github.com/elastic/kibana/issues/95486 to track the enhancement of dynamically generating simple descriptions for processors where one hasn't been defined.

**Comment by andrewkroh** [comment]
Kibana now has the generated descriptions for processors. 

> Also ++ on longer term having elastic-package lint be able to show warnings (right now it either passes or fails), and one of these warnings could be when it detects ingest pipeline processors with no descriptions. 

If we get the warning capability I think we should add a warning for missing `script` processor `description` fields since it just has a generic "`Runs a script on incoming documents.`" value.
