### ISSUE TITLE
[meta] Upgrade integrations to ECS 8.11

### ISSUE THREAD

**Issue by narph** [elastic/integrations#8150]
Track ECS 8.11 updates to integration packages maintained by the `elastic/security-external-integrations` team.

## ECS 8.11 Changes

This is a summary of the changes in ECS 8.11. You can view the official changelog [here](https://github.com/elastic/ecs/blob/8.11/CHANGELOG.md) (invalid link for now - will update).

#### Bugfixes
- Remove `expected_values` from `threat.*.indicator.name` fields. https://github.com/elastic/ecs/pull/2281

#### Added
- Added `volume.*` as beta field set. https://github.com/elastic/ecs/pull/2269

#### Bugfixes
- Respect reusable.top_level in Beats generator. https://github.com/elastic/ecs/pull/2278

This issue will be updated once the necessary work to be done is evaluated.

**Comment by chemamartinez** [comment]
Opened PRs with all the packages owned by SEI updated, apart from the deprecated ones:
- bluecoat
- f5
- juniper_junos
- juniper_netscreen
