### ISSUE TITLE
[Google Cloud] Add GKE integration

### ISSUE THREAD

**Issue by sorantis** [elastic/integrations#816]
The customer utilizes the Google Cloud Platform(GCP) module that includes various metric sets, but none for Google Kubernetes Engine(GKE). Since we already have a GCP module, the customer would like there to be a metric set for GKE as well.

Available Kubernetes metrics: https://cloud.google.com/monitoring/api/metrics_kubernetes#kubernetes-kubernetes

**Comment by endorama** [comment]
Backport to 7.x (7.16) https://github.com/elastic/beats/pull/27521
Backport to 7.15 https://github.com/elastic/beats/pull/27522

**Comment by endorama** [comment]
@sorantis This issue refers to Beat metricset and not integration (at the moment there are no metrics integrations available for GCP), so I closed it by merging the change in beats.
