### ISSUE TITLE
[aws] Support VPC endpoint for `aws-s3` input SQS queue url

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#8183]
AWS customers can now access [Amazon Simple Queue Service](https://aws.amazon.com/sqs/) (Amazon SQS) from their [Amazon Virtual Private Cloud](https://aws.amazon.com/vpc/) (Amazon VPC) using VPC endpoints, without using public IPs, and without needing to traverse the public internet. This issue is to add support for `aws-s3` input to accept VPC endpoint format for SQS queue URL.

Error when trying to use vpce with current integration:
```
[elastic_agent.filebeat][error] Input 'aws-s3' failed with: failed to get AWS region from queue_url: QueueURL is not in format: https://sqs/.{REGION_ENDPOINT}.{ENDPOINT}/{ACCOUNT_NUMBER}/{QUEUE_NAME}
```

For example:
```
sqs queue: https://sqs.us-east-2.amazonaws.com/12345678912/sqs-queue
vpce: https://vpce-test.sqs.us-east-2.vpce.amazonaws.com/12345678912/sqs-queue
```

**Comment by knohub** [comment]
Howdy! @kaiyan-sheng Just wanted to give you an FYI that I got another US Federal Customer having the same issue like https://github.com/elastic/enhancements/issues/20973.  So I created an [ER](https://github.com/elastic/enhancements/issues/21469) per Customer's request for you to review and consider.  Thanks!
