### ISSUE TITLE
Update System Overview Dashboard

### ISSUE THREAD

**Issue by sorantis** [elastic/integrations#819]
The Cloud Team provided the following feedback on the System overview dashboard:

The “[Metricbeat System] Host overview ECS” dashboard is quite problematic from an administrator point of view:
- There’s a diskIO graph but diskIO module is not enabled by default on system module
- There are multiple gauges in the top of the dashboard that don’t help an administrator get a quick historic view of changes of values. Gauges are closer to a “managerial” view of resources
- There are gauges on top for metrics that are not graphed with histograms below, eg “Disk used [Metricbeat System] ECS”, “Swap usage [Metricbeat System] ECS”, “Packetloss [Metricbeat System] ECS”.
- Traffic per interface would be more helpful if it was a visualization with a histogram
- Default dashboard does not visualize socket_summary metrics which are collected by default
- No dashboard(s) to include visualizations for “extended” metricsets like: entropy, core, service which could be really useful to visualize performance of a system.
- “[Metricbeat System] Containers overview ECS” has absolutely no historical view/visualization of data. It’s really hard to tell what these numbers refer to, many columns don’t even have units.

**Comment by fearful-symmetry** [comment]
> There’s a diskIO graph but diskIO module is not enabled by default on system module

This is a bug. I did some searching around, and it looks like `diskio` is default on integrations, but not on metricbeat, which might explain this. We might just want to enable it by default on metricbeat?

> “[Metricbeat System] Containers overview ECS” has absolutely no historical view/visualization of data. It’s really hard to tell what these numbers refer to, many columns don’t even have units.

I think we discussed this dashboard a while ago--it's an odd vestigial organ and I think at one point a few of us discussed taking it out entirely. I'm not sure what users might want that isn't currently cover by the Kibana observability apps themselves. 


So, a lot of this stuff sort of broaches something I've discussed with @masci a few times, which is how we make metrics presentable and discoverable to users. I don't think the solution is to say, tack on an extra dashboard for things like `entropy` but to create a dynamic "discovery" system that presents whatever is available, a la https://github.com/netdata/netdata In the long term, giving users a single place where they can "dive deep" is more discoverable and lower-friction than a growing collection of dashboards that operate on delineations that might not make sense for everyone.

A lot of this feedback also involves questions about what exactly the use case of the dashboards are, compared to the Kibana host visualizations. Frankly, I don't have a good idea what what exactly that use case is. We've discussed "managerial overview vs diagnostics" a few times. Like, how do we distinguish between what enhancements go in the dashboards, vs what goes in the Kibana host overviews?

**Comment by sorantis** [comment]
@fearful-symmetry Agreed, we should strive to maintain consistency between a module and corresponding integration. 

I don't think we should always compare Kibana visualizations with the dashboards. In many cases users only use dashboards and are not particularly familiar with curated views like Logs or Metrics UIs. System is one of the better dashboards we have and I think improving it by adding more view and updating existing ones is the way forward.

**Comment by fearful-symmetry** [comment]
> Agreed, we should strive to maintain consistency between a module and corresponding integration.

Yah. Since it's already in the dashboard, I think enabling the module in metricbeat might be the way forward here.


> I don't think we should always compare Kibana visualizations with the dashboards.

Agreed, I'm just not 100% clear on what we consider the use cases to be for the two different products.
