### ISSUE TITLE
[New Integration] Symantec EDR Cloud

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#8229]
### Description
Symantec EDR exposes advanced attacks with precision machine learning and global threat intelligence minimizing false positives and helps ensure high levels of productivity for security teams. Symantec EDR capabilities allow incident responders to quickly search, identify and contain all impacted endpoints while investigating threats using a choice of on-premises and cloud-based sandboxing. Also, Symantec EDR enhances investigator productivity with automated investigation playbooks and user behavior analytics that brings the skills and best practices of the most experienced security analysts to any organization. 

### Architecture
Symantec provide an [API](https://apidocs.securitycloud.symantec.com/#/doc?id=incident_events_resource) to pull incidents, events and audit events. Pushing data to object storage such as S3, Azure Blob and GCS buckets are also supported. 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by ebeahan** [comment]
A `symantec_edr_cloud` integration shipped with the `incidents` data stream calling the [`/v1/incidents` API.](https://apidocs.securitycloud.symantec.com/#/doc?id=edr_incidents) in #8267.

Future work will add an additional data stream calling the [`/v1/event-export/stream/{stream_guid}/{channel_id}` Event Stream API](https://apidocs.securitycloud.symantec.com/#/doc?id=ses_event_stream).

**Comment by jamiehynds** [comment]
@ebeahan this is something actively being worked on my @piyush-elastic and team.

**Comment by ebeahan** [comment]
@jamiehynds got it - I missed https://github.com/elastic/integrations/issues/8972.
