### ISSUE TITLE
Improve CloudFlare Logpush Documentation

### ISSUE THREAD

**Issue by deonnazworth** [elastic/integrations#8342]
I had a customer that recently upgraded Elastic Integration for CloudFlare Logpush from 1.15.0 to 1.16.0, and after the upgrade started receiving connection failures from Cloudflare.  No settings were changed during or after the upgrade and the error they received was:

```
"error_message": "error 415: error pushing: error uploading to https: 415 {\"message\":\"wrong Content-Type header, expecting application/json\"}",
```

It looks like in the newer version of the Elastic Agent the connection now requires there to be the content-type header specified, where it did not before. The customer has requested a document review and possible update to the docs to include that you need to have it added into the destination_conf for the Cloudflare job setup.

Specific doc: https://docs.elastic.co/integrations/cloudflare_logpush#to-collect-data-from-the-cloudflare-http-endpoint-follow-the-below-steps

In the Current Documentation - Your specified Destination_conf:
```
"destination_conf": "https://<public domain>:<public port>/<dataset path>?header_<secret_header>=<secret_value>",
```
what needs to be modified:
```
header_Content-Type=application/json&
```
so, the original example modified would be:
```
"destination_conf": "https://<public domain>:<public port>/<dataset path>?header_Content-Type=application/json&header_<secret_header>=<secret_value>",
```

If you can verify if this updated info should be included in the documentation, or possibly add a note stating that the content-type header may need to be specified, I think this would help users in the future.

**Comment by jamiehynds** [comment]
@chemamartinez would you mind taking a look at this issue please?

**Comment by chemamartinez** [comment]
Hi @deonnazworth,

Before updating the docs I would like to understand in a more precise way what's the source of this issue.

You mentioned that this started happening after upgrading from 1.15.0 to 1.16.0, that version contains a change for the AWS input, but from your feedback I assume the customer is fetching the data through the Cloudflare HTTP endpoint, is that correct?

> It looks like in the newer version of the Elastic Agent the connection now requires there to be the content-type header specified, where it did not before.

Regarding this, I've checked the [Elastic Agent changelog](https://github.com/elastic/elastic-agent/tree/main/changelog) and haven't found anything related to this. Did the customer upgrade any other component before the errors started to appear?

Finally, just to confirm, adding the content-type header to the URL did solve the issue?

Thanks!

**Comment by deonnazworth** [comment]
Hi @chemamartinez,

The customer upgraded the Elastic Integration for CloudFlare Logpush from 1.15.0 to 1.16.0.  After the upgrade they started experiencing connection failures from Cloudflare. They are using the HTTP Endpoint Integration.

The error they started receiving after the upgrade is:
```
"error_message": "error 415: error pushing: error uploading to https: 415 {\"message\":\"wrong Content-Type header, expecting application/json\"}",
```
The customer said that:   No settings were changed on the Cloudflare side.

The customer also stated that it looks like the Elastic Agent connection after the upgrade now requires there to be the content-type header specified, where it did not before. 

They suggested the update to the docs based on their findings.

The doc in question : https://docs.elastic.co/integrations/cloudflare_logpush#to-collect-data-from-the-cloudflare-http-endpoint-follow-the-below-steps

In the Current Documentation it states the following
```
"destination_conf": "https://<public domain>:<public port>/<dataset path>?header_<secret_header>=<secret_value>",
```
what needs to be modified:
```
header_Content-Type=application/json&
```
so, the original example modified would be:
```
"destination_conf": "https://<public domain>:<public port>/<dataset path>?header_Content-Type=application/json&header_<secret_header>=<secret_value>",
```
Here is a screenshot showing the section that needs to be modified, or have a special note stating the content header may be needed.
<img width="794" alt="Screenshot 2023-11-08 at 3 20 02 PM" src="https://github.com/elastic/integrations/assets/81386932/404927f5-e29d-4d3e-9d72-17e767e9b9bb">


The customer stated that after adding the content-type header it did resolve the issue for them.

Here is the case number in case it helps `01506614`

**Comment by chemamartinez** [comment]
Thanks for the update, @deonnazworth.

I read in the case that the customer also upgraded the stack from 8.8.2 to 8.10.4, but I still couldn't find any change related to this issue.

I suspect that something has changed on the Cloudflare side that makes incoming HTTP messages not include the `Content-Type` header or add a different one to `application/json` if the `Content-type` is not explicitly specified when configuring the Logpush.
