### ISSUE TITLE
[BUG] Missing _tier filter to exclude cold and frozen

### ISSUE THREAD

**Issue by arisonl** [elastic/integrations#8427]
We are working to find out why ML related queries from the Security solution UI are hitting Cold nodes. 

The problem with the ML data recognizer being called and hitting cold nodes from the security solution is coming from here: https://github.com/elastic/integrations/blob/dc4663f7947a9f5207fb09c15cea69732e549edb/packages/ded/kibana/ml_module/ded-ml.json#L10

Please include a filter like:

`"must_not": { "terms": { "_tier": [ "data_frozen", "data_cold" ] } }
`

There are also another 3 packages in that same repo that don't have this filter, namely:

1. `packages/lmd/kibana/ml_module/lmd-ml.json`
2. `packages/dga/kibana/ml_module/dga-ml.json`
3. `packages/problemchild/kibana/ml_module/problemchild-ml.json`

If these are not your responsibility, let us know which team should be contacted.

cc @insukcho @paulewing

**Comment by insukcho** [comment]
I will create a new one for this.
