### ISSUE TITLE
[sophos][utm] parsing fails completely, grok error

### ISSUE THREAD

**Issue by StefanSa** [elastic/integrations#8430]
Hi there.
The `sophos utm` integration fails completely with grok error.
Just one example of many.
```
Processor "grok" with tag "grok_syslog_header" in pipeline "logs-sophos.utm-3.5.0" failed with message "Provided Grok expressions do not match field value: [<30>2023:11:08-08:59:57 test-utm-01-1 ulogd[10589]: id=\"2002\" severity=\"info\" sys=\"SecureNet\" sub=\"packetfilter\" name=\"Packet accepted\" action=\"accept\" fwrule=\"8\" initf=\"eth1\" outitf=\"eth0\" srcmac=\"1a:c2:41:3b:18:08\" dstmac=\"00:1a:8c:f0:23:81\" srcip=\"11.12.204.152\" dstip=\"192.168.70.6\" proto=\"6\" length=\"52\" tos=\"0x00\" prec=\"0x00\" ttl=\"125\" srcport=\"51846\" dstport=\"445\" tcpflags=\"SYN\" ]"
```
elastic_agent.version: 8.10.4
Sophos Integration: 3.5.0

This integration cannot currently be used in this way.
In Filebeat version 8.10.2 this integration works, albeit with some missing and converted ecs fields.
Can someone please check so that you can use this module ?

regards
StefanS

**Comment by jamiehynds** [comment]
@StefanSa can you confirm that you are running the latest version of the Sophos integration, i.e. v3.5.0? We rewrote the UTM integration from scratch, as the previous integration (and Filebeat module) were technical preview with known issues. 

Looking at the sample above, it aligns with the packet filter [sample data ](https://github.com/elastic/integrations/blob/main/packages/sophos/data_stream/utm/_dev/test/pipeline/test-sophos-utm-packetfilter.log). Once you confirm that you're on the latest integration, we can go from there. (cc @chemamartinez)

**Comment by StefanSa** [comment]
Hi @jamiehynds 
Yes, i can confirm that this is the latest version v3.5.0
![image](https://github.com/elastic/integrations/assets/6105075/1fbf77ce-35ea-42fb-9418-eb3076b16e6d)
native filebeat does not have these problems.
If you are already looking for the error, please add the missing field `event.action`, this would also be important.

**Comment by chemamartinez** [comment]
Hi @StefanSa,

Thank you for reporting this issue. That `grok` processor is failing because it doesn't expect the syslog priority at the start of the event. I've already raised a pull request to fix it: https://github.com/elastic/integrations/pull/8437

Regarding the `event.action` field, it is currently mapped by the integration with the incoming `action` field [here](https://github.com/elastic/integrations/blob/main/packages/sophos/data_stream/utm/elasticsearch/ingest_pipeline/packetfilter.yml#L15-L19). Once the pull request is merged and the header issue gets solved, please let us know if you still miss it.

**Comment by StefanSa** [comment]
Hola @chemamartinez 
Thanks for the quick feedback, i will wait until the pull request is complete.
As for the `event.action` field, this is missing at least in the latest native filebeat version.
![image](https://github.com/elastic/integrations/assets/6105075/af0feb38-fff9-4ba9-9b6e-9a8a75e9eace)
One of you should take a closer look.

Saludos desde Alemania
Stefan
