### ISSUE TITLE
[meta] [etcd] GA Migration

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#8441]
Etcd integration is currently in beta. 

Following are the details of tasks presently known and associated with etcd integration package.  

This meta issue links all the related issues and tasks associated with Etcd package, discusses API support, and rollout plans.

| Link | Description | Type | Status |
| ---- | ----------- | ---- | ------ |
| [Issue](https://github.com/elastic/integrations/issues/8373) | Fix incorrect field mappings in leader dataset | Bug | Closed |
| [Issue](https://github.com/elastic/integrations/issues/8445) | Update metrics dataset to use prometheus integration package | Enhacement |Done|
| [PR Link](https://github.com/elastic/integrations/pull/8438) | Fix the `metric_type` mapping of various fields in `metrics` dataset especially mapping to histogram type | Bug Fix | Done | 
| [Issue](https://github.com/elastic/integrations/issues/8327)|  TSDB Enablement | Enahcement | Done | 
| [Issue](https://github.com/elastic/integrations/pull/8955) | Make ETCD GA | Enhancement | Done |
| [Issue](https://github.com/elastic/integrations/issues/8458) | Deprecation of V2 API based datasets.  | Discussion | Done |

**Comment by shmsr** [comment]
Before GA, [this](https://github.com/elastic/integrations/issues/8028#:~:text=SVR00002%2CSVR00004-,Other%20non%2Dblocking%20issues%20that%20should%20be%20fixed%20in%20the%20future,-%5Betcd%5D%3A%20While%20migrating) needs to be fixed too. Tom and I noticed this when we were discussing one blocker in etcd's package-spec upgrade.

> [etcd]: While migrating we noticed the type {backend_commit_duration,wal_fsync_duration}.ns.{count,sum} is set to long but it should be float instead. ([ref](https://github.com/prometheus/prometheus/blob/main/model/histogram/histogram.go#L64))
