### ISSUE TITLE
Fortinet Fortigate Integration Event Module Name

### ISSUE THREAD

**Issue by weslambert** [elastic/integrations#8453]
Right now, the event module value for the Fortinet Fortigate integration is `fortinet`.

https://github.com/elastic/integrations/blob/ce2f88171a247b9bbeedc9035ec5204f91b35daa/packages/fortinet_fortigate/data_stream/log/fields/base-fields.yml#L13

Should the event module name for the integration be `fortinet_fortigate`, similar to the Cisco ASA integration?

https://github.com/elastic/integrations/blob/ce2f88171a247b9bbeedc9035ec5204f91b35daa/packages/cisco_asa/data_stream/log/fields/base-fields.yml#L13

**Comment by xtruthx** [comment]
sounds like a valid suggestion. I suspect this comes from the times when there was "only" the Fortinet Fortigate module
