### ISSUE TITLE
[New Integration] ThreatConnect

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#8455]
Create a new threat intel (TI) integration for [ThreatConnect](https://threatconnect.com/).

I didn't see any publicly available API documentation so I think we would need to establishing some form of relationship with the company in order to build and test the integration.

**Comment by jamiehynds** [comment]
@andrewkroh we've been working with ThreatConnect recently and have access to an instance. Piyush and team are starting on the integration very soon.

**Comment by jamiehynds** [comment]
PR for ThreatConnect is up and ready for review: https://github.com/elastic/integrations/pull/8925

**Comment by jamiehynds** [comment]
Closed via https://github.com/elastic/integrations/pull/8925
