### ISSUE TITLE
[Bug] Okta Integration - We are not collecting the RequestApiTokenId field

### ISSUE THREAD

**Issue by aarju** [elastic/integrations#8459]
The Infosec team [found ](https://github.com/elastic/infosec/issues/15229) found that the Okta integration does not include the `event.system.transaction.detail.requestApiTokenId` field in the event logs being collected. This field is critical to identifying activity from an Admin API Token in Okta. Without this field we cannot track what actions were taken with an API Token or build detections to alert on a compromised token.

Please update the integration to collect the `event.system.transaction.detail.requestApiTokenId` field and map it as `okta.transaction.detail.requestapiid`. 

![image](https://github.com/elastic/integrations/assets/14032876/db3be923-c418-43d4-a3bd-af8bce533e21)

**Comment by andrewkroh** [comment]
Docs: https://developer.okta.com/docs/reference/api/system-log/#transaction-object

The original field name found in our existing samples is `.transaction.detail.requestApiTokenId`. 

`requestApiTokenId` is the only field found under `details` in our current samples.

**Comment by andrewkroh** [comment]
PR: https://github.com/elastic/integrations/pull/8467

**Comment by aarju** [comment]
Our integration has been updated and I can confirm that we now have the API information in the logs. Thanks for the quick update!
