### ISSUE TITLE
Apache integration Provided Grok expressions do not match field value

### ISSUE THREAD

**Issue by zez3** [elastic/integrations#8512]
I've got some error popping when I started using the Apache Integration:

for log.file.path : `/var/log/apache2/access.log` :

event.original : ```1.1.1.29 - - [13/Nov/2023:10:44:01 +0000] "<SCRIPT>NXSSTEST</SCRIPT> / HTTP/1.1" 400 3386 "-" "-"```
error.message : ```Provided Grok expressions do not match field value: [1.1.1.29 - - [13/Nov/2023:10:44:01 +0000] \"<SCRIPT>NXSSTEST</SCRIPT> / HTTP/1.1\" 400 3386 \"-\" \"-\"]```

and

for log.file.path : `/var/log/apache2/error.log`
event.original : ```AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message```
error.message : ```Provided Grok expressions do not match field value: [AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message]```

and

for log.file.path: `/var/log/apache2/other_vhosts_access.log`
event.original: ```127.0.1.1:80 1.1.1.29 - - [13/Nov/2023:10:44:31 +0000] "\x16\x03\x03\x01\x8f\x01" 400 483 "-" "-"```
event.original: ```127.0.1.1:80 1.1.1.29 - - [13/Nov/2023:10:44:01 +0000] "<SCRIPT>NXSSTEST</SCRIPT> / HTTP/1.1" 400 483 "-" "-"```
error.message: ```Provided Grok expressions do not match field value: [127.0.1.1:80 1.1.1.29 - - [13/Nov/2023:10:44:31 +0000] \"\\x16\\x03\\x03\\x01\\x8f\\x01\" 400 483 \"-\" \"-\"]```
error.message: ```Provided Grok expressions do not match field value: [127.0.1.1:80 130.92.254.29 - - [13/Nov/2023:10:44:01 +0000] \"<SCRIPT>NXSSTEST</SCRIPT> / HTTP/1.1\" 400 483 \"-\" \"-\"]```

**Comment by zez3** [comment]
@andrewkroh can you please flag this as bug and assign a team.
Thanks 🙏

**Comment by samhop** [comment]
Hi. We are experiencing the same issue. Is this bug being investigated?

event.original: `207.90.244.17 - - [22/May/2024:08:21:14 +0300] \"\\n\" 400 226 98`

error.message: `Provided Grok expressions do not match field value: [207.90.244.17 - - [22/May/2024:08:21:14 +0300] \"\\n\" 400 226 98]`

**Comment by harnish-elastic** [comment]
> Hi. We are experiencing the same issue. Is this bug being investigated?
> 
> event.original: `xxx.xx.xxx.xx - - [22/May/2024:08:21:14 +0300] \"\\n\" 400 226 98`
> 
> error.message: `Provided Grok expressions do not match field value: [xxx.xx.xxx.xx - - [22/May/2024:08:21:14 +0300] \"\\n\" 400 226 98]`

Found similar issue: https://github.com/elastic/integrations/issues/9952

**Comment by harnish-elastic** [comment]
Hey @zez3 @samhop,

Can I get the following details for further investigation?

- Apache version that you are using
- Log pattern of the provided logs (access logs and error logs) are default? Are there any modification happened manually in the Apache instance? If yes please let me know.

**Comment by samhop** [comment]
> Hey @zez3 @samhop,
> 
> Can I get the following details for further investigation?
> 
> * Apache version that you are using
> * Log pattern of the provided logs (access logs and error logs) are default? Are there any modification happened manually in the Apache instance? If yes please let me know.

We have CustomLog logs/ssl_access_log combined

Server version: Apache/2.4.57 (Red Hat Enterprise Linux)

**Comment by harnish-elastic** [comment]
Hey @zez3 @samhop,

For the access logs, I am able to collect data by changing the grok pattern. I will raise PR for it in short time. But for the error logs, Can you please provide me log format as well as the sample logs to debug more?

**Comment by zez3** [comment]
> For the access logs, I am able to collect data by changing the grok pattern.

That was also temporary(on next update they will be gone) my workaround, I just added in `logs-apache.access-1.18.0` a second line with my custom format:

```
%{IPORHOST:source.address} - %{DATA:user.name} \[%{HTTPDATE:apache.access.time}\] "-" %{NUMBER:http.response.status_code:long} -
```

and in `logs-apache.error-1.18.0` pipeline:

```
\[%{APACHE_TIME:apache.error.timestamp}\] \[%{DATA:apache.error.module}:%{APACHE_LOGLEVEL:log.level}\] \[pid %{NUMBER:process.pid:long}(:tid %{NUMBER:process.thread.id:long})?\]( \[client %{IPORHOST:source.address}(:%{POSINT:source.port})?\])? %{GREEDYDATA:message}
```

but I think we need a different solution so that any user can easily customize this in the custom pipeline `logs-apache.access@custom` respectively `logs-apache.error@custom`

@andrewkroh What do you think? would something like this be possible?

**Comment by harnish-elastic** [comment]
Hey @zez3 @samhop, 

I have raised draft PR for access log grok support https://github.com/elastic/integrations/pull/10228.

For the error logs I still need raw logs as well as apache instance error log pattern to create generic grok pattern in elastic. Can you please provide me so that I can investigate more?

**Comment by harnish-elastic** [comment]
> Hey @zez3 @samhop,
> 
> I have raised draft PR for access log grok support #10228.
> 
> For the error logs I still need raw logs as well as apache instance error log pattern to create generic grok pattern in elastic. Can you please provide me so that I can investigate more?

Hey @zez3 @samhop Do I have any updates?

**Comment by zez3** [comment]
@harnish-elastic 

Here some access logs:

```
1.2.3.4 - - [02/Jul/2024:14:17:11 +0000] "GET / HTTP/1.1" 304 478 "https://my.dom.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"

2.3.4.5 - - [02/Jul/2024:14:17:08 +0000] "GET /favicon.ico HTTP/1.1" 404 583 "https://my.dom.tld/dir/data/2007/dir/file.pdf" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"

3.4.5.6 - - [02/Jul/2024:14:33:33 +0000] "-" 408 323 "-" "-"
```

and error

```
[Tue Jul 02 00:00:07.495837 2024] [ssl:warn] [pid 1369] AH01909: docs:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jul 02 00:00:07.500391 2024] [ssl:warn] [pid 1369] AH01909: wiki:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jul 02 00:00:07.502629 2024] [ssl:warn] [pid 1369] AH01909: operations:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jul 02 00:00:07.553695 2024] [mpm_prefork:notice] [pid 1369] AH00163: Apache/2.4.59 (Ubuntu) OpenSSL/3.0.2 configured -- resuming normal operations
[Tue Jul 02 00:00:07.553712 2024] [core:notice] [pid 1369] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 02 00:23:48.292803 2024] [access_compat:error] [pid 82488] [client 1.2.3.4:55380] AH01797: client denied by server configuration: /var/www/operations/
[Tue Jul 02 02:02:52.832546 2024] [access_compat:error] [pid 82488] [client 1.2.3.4:48816] AH01797: client denied by server configuration: /var/www/operations/
[Tue Jul 02 02:26:14.475592 2024] [php:error] [pid 82487] [client 1.2.3.4:47034] script '/var/www/operations/index.php' not found or unable to stat
[Tue Jul 02 02:26:14.523031 2024] [php:error] [pid 82487] [client 1.2.3.4:47034] script '/var/www/operations/signin.php' not found or unable to stat
[Tue Jul 02 02:26:14.539911 2024] [php:error] [pid 82487] [client 1.2.3.4:47034] script '/var/www/operations/index.php' not found or unable to stat
[Tue Jul 02 02:26:14.647394 2024] [php:error] [pid 82640] [client 1.2.3.4:47040] script '/var/www/operations/index.php' not found or unable to stat
[Tue Jul 02 02:27:32.439199 2024] [authz_core:error] [pid 83920] [client 1.2.3.4:46576] AH01630: client denied by server configuration: /var/www/operations/server-status
[Tue Jul 02 02:27:32.450834 2024] [authz_core:error] [pid 83920] [client 1.2.3.4:46568] AH01630: client denied by server configuration: /var/www/operations/server-status
[Tue Jul 02 02:27:32.461237 2024] [authz_core:error] [pid 83920] [client 1.2.3.4:46586] AH01630: client denied by server configuration: /var/www/operations/server-status
[Tue Jul 02 02:27:32.472028 2024] [evasive20:error] [pid 83920] [client 1.2.3.4:46590] client denied by server configuration: /var/www/operations/server-status
[Tue Jul 02 02:27:32.517881 2024] [evasive20:error] [pid 83920] [client 1.2.3.4:46650] client denied by server configuration: /var/www/operations/server-status
[Tue Jul 02 02:27:33.140438 2024] [evasive20:error] [pid 83920] [client 1.2.3.4:46800] client denied by server configuration: /var/www/operations/login
[Tue Jul 02 02:27:33.618845 2024] [authz_core:error] [pid 83969] [client 1.2.3.4:46636] AH01630: client denied by server configuration: /var/www/operations/server-status
[Tue Jul 02 02:27:33.683928 2024] [authz_core:error] [pid 83969] [client 1.2.3.4:46630] AH01630: client denied by server configuration: /var/www/operations/server-status
[Tue Jul 02 02:27:33.693840 2024] [evasive20:error] [pid 83920] [client 1.2.3.4:46942] client denied by server configuration: /var/www/operations/
[Tue Jul 02 02:27:33.716705 2024] [evasive20:error] [pid 83920] [client 1.2.3.4:46778] client denied by server configuration: /var/www/operations/Telerik.Web.UI.WebResource.axd
[Tue Jul 02 02:27:33.751833 2024] [evasive20:error] [pid 83920] [client 1.2.3.4:46916] client denied by server configuration: /var/www/operations/c99.php
[Tue Jul 02 02:27:33.882934 2024] [evasive20:error] [pid 83920] [client 1.2.3.4:46962] client denied by server configuration: /var/www/operations/cgi-bin
```

I still believe we should allow the user to configure it's custom pipeline with own specific formatting. Or at least have a note somewhere that he could/should do that

**Comment by harnish-elastic** [comment]
@zez3 Thank you for providing the logs. However these logs are getting ingested on first go by apache integration error logs pipeline. But I have find interesting thing on apache environment that error log is also throwing the warning logs in error logs file. Please refer [this](https://askubuntu.com/questions/1491562/ah00558-apache2-could-not-reliably-determine-the-servers-fully-qualified-doma/1491614#:~:text=1%20Answer&text=This%20is%20not%20an%20error,machine%20IP%20as%20the%20same.&text=If%20you%20want%20to%20remove,have%20to%20configure%20your%20ServerName%20) quote. 

The log that is occuring error is starting directly from error code. So if we want to ingest these logs, we strongly need to make the timestamp and pther fields as optional from apache grok pattern. I will work on that changes.

Warning log example:
`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message`

**Comment by harnish-elastic** [comment]
@zez3 @samhop FYI, I have raised a PR to support new log formats. https://github.com/elastic/integrations/pull/10228
