### ISSUE TITLE
Error in Pipeline used within Cisco Umbrella Integration - timestamp not mapped correctly

### ISSUE THREAD

**Issue by agmic** [elastic/integrations#8517]
Cisco Umbrella Integration version: 1.21.0
Following up on this report from Digital Thought on the elastic forum https://discuss.elastic.co/t/error-in-pipeline-used-within-cisco-umbrella-integration/344853 

The current ingest pipeline for the Cisco Umbrella Integration will not properly set the timestamp to the value from the csv. The value is read from the csv into "cisco.umbrella._tmp.time", however "cisco.umbrella._tmp" is wiped to create a new array before the value is parsed into @timestamp. ingest_pipeline/default.yml line 239

This looks to have snuck in on this commit https://github.com/elastic/integrations/pull/6600 as the code was placed before the timestamp value is extracted.

I've fixed this locally by moving the set timestamp script above the identities handling, but this messes up the sections in the yml. Alternatively a new variable could be used to store the tmp.time value as the original poster used.

**Comment by jamiehynds** [comment]
@efd6 could this be an unintended consequence of the `event.kind` PR listed above? (https://github.com/elastic/integrations/pull/6600)

**Comment by efd6** [comment]
I don't see any way that that change would have the effect of causing this failure. However, #6119 does. Sending a fix.
