### ISSUE TITLE
[Redis Enterprise] Fix dashboard visualizations

### ISSUE THREAD

**Issue by harnish-elastic** [elastic/integrations#8603]
Observations:

- [x] The dashboard visualizations have static intervals of `1m` rather than Auto. Is this intentional? if not, need to make it 'Auto'
![image](https://github.com/elastic/integrations/assets/118714680/39294e50-63fa-4ad5-b725-13b3aa33a6ae)

- [x] The visualization `Total client connections` has an `average` operation type which seems inappropriate. We can use `last_value` instead of `average`!

**Comment by agithomas** [comment]
@harnish-elastic / @milan-elastic , any update on this?

**Comment by harnish-elastic** [comment]
> @harnish-elastic / @milan-elastic , any update on this?

@agithomas The issue is in the backlog. This issue is yet to be picked up.
