### ISSUE TITLE
[Exchange Online Message Trace] #8550/1.17.0 Breaks Integration

### ISSUE THREAD

**Issue by BenB196** [elastic/integrations#8633]
Upgrading the Exchange Online Message Trace integration to `1.17.0` generated by #8550, results in the integration throwing the following error;

```json
{"log.level":"error","@timestamp":"2023-12-01T19:50:02.990Z","message":"error processing response: server responded with status code 400: {\"odata.error\":{\"code\":\"\",\"message\":{\"lang\":\"en-US\",\"value\":\"Incorrect format for $top argument '1000]'.\"}}}","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"httpjson-a5dd7be0-64fe-11ed-ab11-d7fe3acf785c","type":"httpjson"},"log":{"source":"httpjson-a5dd7be0-64fe-11ed-ab11-d7fe3acf785c"},"log.origin":{"file.line":524,"file.name":"httpjson/request.go"},"service.name":"filebeat","input_source":"https://reports.office365.com/ecp/reportingwebservice/reporting.svc/MessageTrace","ecs.version":"1.6.0","log.logger":"input.httpjson-cursor","id":"httpjson-microsoft_exchange_online_message_trace.log-05353573-19d2-4192-8058-4ad4b8ee7719","input_url":"https://reports.office365.com/ecp/reportingwebservice/reporting.svc/MessageTrace","ecs.version":"1.6.0"}
```

Can also be observed through data ingest;

![image](https://github.com/elastic/integrations/assets/8277432/b6332bdb-79d0-4de1-b859-02a616c9d3e5)

Integration was updated ~14:05

**Comment by BenB196** [comment]
The two offending lines;

https://github.com/elastic/integrations/blob/0663a7e540c22702ee1fc4e594673c44f1c8c616/packages/microsoft_exchange_online_message_trace/data_stream/log/agent/stream/httpjson.yml.hbs#L61
https://github.com/elastic/integrations/blob/0663a7e540c22702ee1fc4e594673c44f1c8c616/packages/microsoft_exchange_online_message_trace/data_stream/log/agent/stream/httpjson.yml.hbs#L65

Both of these have an extra trailing `]`

```diff
- "]]]
+ "]]
```

**Comment by ShourieG** [comment]
@BenB196 thanks for pointing this out, will push out a quick fix.

**Comment by ShourieG** [comment]
Hi @BenB196, the fix has been merged. Could you check out version 1.17.1 and let us know if the issue is resolved for you ?

**Comment by ShourieG** [comment]
closing the issue, since fix is merged now.

**Comment by ShourieG** [comment]
@BenB196 the terminate pagination error can be ignored as that only happens as a byproduct of how httpjson handles end of page or when no data is available in the response. 

In the 1st error I can however see that there is an extra query param test, in addition to what is supplied by the integration. Was this added manually? Is a smaller batch size helping here? Is the integration ingesting any data ?

**Comment by BenB196** [comment]
Hi @ShourieG let me get some more debugging data, but to answer some of your questions up front;

> Also which version of elastic stack are you using?

Everything is `8.10.4`.

The integration is being upgraded from `1.16.0`, I'll try upgrading then creating a fresh version of the install. Maybe something is being carried over?

**Comment by BenB196** [comment]
One additional note though, the polling interval and lookback (not the initial lookback, but subsequent lookbacks), should be configurable as two different settings, right now they're both tied to the polling interval, however, these logs work on eventual consistency, so you generally want a longer lookback window then polling interval to pick up potentially missed logs.

The logs are already deduped as part of the pipeline here;

https://github.com/elastic/integrations/blob/f8404d73d03ca3a0611e051c6a0a04e7aeef3498/packages/microsoft_exchange_online_message_trace/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L273-L283

So having overlapping lookbacks shouldn't affect the data.

**Comment by ShourieG** [comment]
@BenB196, would you mind opening a separate issue with details of the configurable look back window and tag me on it. I'll get it assigned accordingly. 

Could you give any other feedback on the state of the integration as of version 1.17.1 ? Is the data ingestion ok, are there any other issues.

**Comment by BenB196** [comment]
Hi @ShourieG I'm not seeing any additional errors anymore, so I think `1.17.1` is working as expected after creating a fresh integration definition
