### ISSUE TITLE
[Recorded Future] Decode Evidence_Details

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#8660]
Our Recorded Future integration currently stores `evidence_details` within a single object, however there is some valuable fields within this objects that users would like to use as the basis for some visualisations (e.g. Criticality). 

Can we adjust our pipeline to decode this object into individual fields to make the fields more usable?

![RF Evidence Details](https://github.com/elastic/integrations/assets/62879768/ef8d1015-99e2-4b60-b91c-6b0523f0cde8)

**Comment by dave-dickens** [comment]
Hi Team,

I have a customer (THE BANK OF N.T. BUTTERFIELD & SON LIMITED) who have a requirement for this integration enhancement. This is a request that has come from the CISO directly.
