### ISSUE TITLE
[Exchange Online Message Trace] Split Polling Interval into two settings, Polling Interval & Lookback Interval

### ISSUE THREAD

**Issue by BenB196** [elastic/integrations#8674]
Split from #8633 (https://github.com/elastic/integrations/issues/8633#issuecomment-1845606692)

The Exchange Online Message Trace integration currently ties Polling Interval to both Polling and Lookback. The issue here is that these events are eventually consistent, meaning that some data can be missed on first lookup.

It should be possible to define the Poll Interval and Lookback interval as two different settings so that the lookback interval can be set longer than the poll interval.
```[tasklist]
### Tasks
- [ ] Look into adding separate configurable lookback intervals (separate from the initial_interval lookback), that work along side with the standard polling interval.
```

Edit: For reference here is the official document which mentions that events can "lag" by [up to 24 hours](https://learn.microsoft.com/en-us/previous-versions/office/developer/o365-enterprise-developers/jj984335(v=office.15)#data-granularity-persistence-and-availability). This may however, be mitigated by the `StartDate` and `EndDate` fields (per their descriptions)

**Comment by ShourieG** [comment]
@BenB196 Currently the **Initial interval** actually works as the look-back interval, and it can be configured safely upto 200h without server errors as stated in the document. So atm you currently have **interval** which is the polling interval and **initial_interval** which serves as your Lookback.
