### ISSUE TITLE
[bitdefender] the pushed notification isn't ingested because it lacks Content-Type and Authorization headers

### ISSUE THREAD

**Issue by drizzthacker** [elastic/integrations#8696]
Hi,

I've configured the Bitdefender API to send push notifications, but It isn't ingested into Elasticsearch.

After some try and error, I've found that if I enable the Authorization Value in the integration, it fails to reach the HTTP listener because the POST that Bitdefender sent is lacking that Authorization header (I've configured the Authorization option in Bitdefender API as per documentation)
If I left blank the Authorization value, the error is that the HTTP listener don't know the type of content that Bitdefender sent in it's POST.

As temporal workaround I've solved it by putting a reverse proxy between Bitdefender and the HTTP listener that handles the Bitdefender POST, adds that 2 headers and send it to the integration HTTP listener, This is the way I've configured the Apache2 to act as a reverse proxy and debug the problem (I'm sure this is not an optimum way to put a reverse proxy, but it's working):

```
Listen 9090
<VirtualHost 192.168.5.222:9090>
        LogLevel dumpio:trace7
        ErrorLog ${APACHE_LOG_DIR}/error_proxy.log
        CustomLog ${APACHE_LOG_DIR}/access_proxy.log combined
        SSLEngine on
        SSLCertificateFile      /certs/backup.pem
        SSLCertificateKeyFile /certs/backup.key

        SSLProxyEngine On
        ProxyPreserveHost On

        ProxyPass "/" "https://backup.xxx.es:9092/"
        ProxyPassReverse "/" "https://backup.xxx.es:9092/"

        ServerName backup.xxx.es:9090

        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off

        ForensicLog ${APACHE_LOG_DIR}/forensic_proxy.log
        DumpIOInput On
        DumpIOOutput On

        RequestHeader set Authorization "Basic xxx"
        RequestHeader set Content-Type "application/json"


</VirtualHost>
```

I've opened a case with Bitdefender and they told me that the API don't support send Authorization headers. Also, the integration documentation tells that the api url is this one: https://cloud.gravityzone.bitdefender.com/api/v1.0/jsonrpc/push, while in Europe is this one instead: https://cloudgz.gravityzone.bitdefender.com/api/v1.0/jsonrpc/push/

May be any difference between USA and Europe?

If I send a POST with test data including both headers with Postman, it ingests ok in Elastic.

Thanks

**Comment by SzakyRo** [comment]
Hello,
Encountered the same issue, used a Reverse proxy with NGINX for adding the content-type header and that solved the issue, the events are being received.

**Comment by SzakyRo** [comment]
Hello @bhapas,

I was able to reproduce this behaviour on my side and while intercepting the calls I was able to see that the headers were missing.

The error returned was 415, this issue is currently being investigated by Bitdefender as well.

If something comes up I will post an update here.

**Comment by bhapas** [comment]
@SzakyRo Thanks for the update. Meanwhile I have created a PR that updates BitDefender integration to `disable content-type check` https://github.com/elastic/integrations/pull/8974

**Comment by 7err0x** [comment]
I can confirm that it works on my side after commit #8974 , events do appear in Kibana dashboard. I had to update the integration to version 1.11 and do again a [setPushEvent](https://www.bitdefender.com/business/support/en/77209-135319-setpusheventsettings.html)on Bitdefender side to reactivate it.

**Comment by SzakyRo** [comment]
Hello @bhapas, everything works as it should now. Thank you for the changes 👍

**Comment by bhapas** [comment]
@drizzthacker closing the issue since couple of users reported that the fix works. Please reopen if it does not work for you.
