### ISSUE TITLE
[Rally] Add benchmarking templates to data streams for set of packages

### ISSUE THREAD

**Issue by aliabbas-elastic** [elastic/integrations#8719]
As per the main Meta [issue](https://github.com/elastic/integrations/issues/8636), need to add benchmarks to integrations. Initially adding one log ( nginx.error ) and one metric ( mysql.performance ) data streams as per discussion with @lalit-satapathy .

```[tasklist]
### Nginx
- [x] nginx.error - [PR](https://github.com/elastic/integrations/pull/8762)
- [x] nginx.access - [PR](https://github.com/elastic/integrations/pull/9032)
- [x] nginx.stubstatus - [PR](https://github.com/elastic/integrations/pull/8800)
```
```[tasklist]
### MySQL
- [x] mysql.performance - [PR](https://github.com/elastic/integrations/pull/8761)
- [x] mysql.error - [PR](https://github.com/elastic/integrations/pull/8957)
- [x] mysql.galera_status - [PR](https://github.com/elastic/integrations/pull/8923)
- [x] mysql.slowlog - [PR](https://github.com/elastic/integrations/pull/9024)
- [x] mysql.status - [PR](https://github.com/elastic/integrations/pull/8868)
```

**Comment by tommyers-elastic** [comment]
it's fine to use this issue for more granular internal tracking, but please ensure the parent meta issue is updated too as this work progresses. :)

**Comment by aliabbas-elastic** [comment]
> it's fine to use this issue for more granular internal tracking, but please ensure the parent meta issue is updated too as this work progresses. :)

Sure I'll update the main Meta as well as so as to keep in sync

**Comment by agithomas** [comment]
@tommyers-elastic  / @ruflin , 

Is the final goal to have Rally benchmarking for all integrations (including AWS / GCP / Azure integration packages)?

**Comment by tommyers-elastic** [comment]
i don't think that's realistic - but i think we should have benchmarks for our most popular/valuable integrations.

**Comment by agithomas** [comment]
> i don't think that's realistic - but i think we should have benchmarks for our most popular/valuable integrations.

When we did the TSDB enablement, aligned certain integrations as P0 priority. If my understanding is right, the priority is defined based on the usage stats. Can those priority assignments be considered here as well?

**Comment by ruflin** [comment]
>  Can those priority assignments be considered here as well?

I think the simple answer is yes. We should look at it case by case but the P0 integrations should also be the one where we fully understand changes and how they perform.

**Comment by lalit-satapathy** [comment]
Any suggestions, should we keep this low level issue going forward as there is also another top level [issue](https://github.com/elastic/integrations/issues/8636) existing for tracking the rally enablement. Or should these be merged?

**Comment by ruflin** [comment]
I suggest we merge into https://github.com/elastic/integrations/issues/8636 as I assume this one is a subset of the other one? Happy to keep this one until PR's are merged.

I like how the tracking is added to this issue, maybe we can do the same for the other?

**Comment by aliabbas-elastic** [comment]
Closing this issue as we have the Main [meta](https://github.com/elastic/integrations/issues/8636) to track all the benchmarking PRs.
cc:- @lalit-satapathy
