### ISSUE TITLE
Automate creation of backport branches

### ISSUE THREAD

**Issue by jsoriano** [elastic/integrations#8721]
Background
---

During the migration to Buildkite we changed the branch protection model for the repository, making it more restrictive. At the moment only admins can create branches that trigger publishing pipelines. This affects backport branches.

We also found during the migration to Buildkite, that backport branches pose a risk of using old CI configurations, what may include from small meaningless changes, to credential changes or full revamps as is the case. So we should add a step of migrating the CI scripts when creating the branch.

Now that creation of backport branches is restricted, we may take the opportunity to automate the creation of these branches. In the meantime, these branches will have to be created by the ecosystem team.

Task
---

The automation could be a buildkite job, that can be triggered by anyone in the company. It would receive as parameters the base package name and the version. With this information, the job would:
* Check that the mentioned package name and version are actually published in the package registry.
* Look for the changeset where the version of the package was created.
* Create a local branch with this changeset.
* Migrate the CI scripts, and commit these changes. We have to decide if this migration can consist on just checking out the files from main.
* [TBD: Remove all the rest of packages so this branch can only be used for this package?]
* Create the branch by pushing this changeset.

With this approach we limit the creation of backport branches to commits that are in the main branch and have already passed CI.

Once the branch is created the process to update it is the same as usual, through PRs.

Documentation in https://github.com/elastic/integrations/blob/main/docs/developer_workflow_bug_fix_older_package_version.md will need to be updated.

cc @elastic/ecosystem @sharbuz

**Comment by mrodm** [comment]
@sharbuz when updating the docs about backport branches, it would be interesting to add a section indicating some errors that could raise in the CI pipelines when a developer creates a PR from a backport branch.

Updating the current backport branches in the integrations repository, I found these errors:

1. Missing `shellinit` command:
    - Error: https://buildkite.com/elastic/integrations/builds/7634#018c87f4-7b0c-4d6f-8ddd-b779a9a7a019/507-512
      ```
      Error: could not create kibana client: undefined environment variable: ELASTIC_PACKAGE_KIBANA_HOST. If you have started the Elastic stack using the elastic-package tool, please load stack environment variables using 'eval "$(elastic-package stack shellinit)"' or set their values manually
      ```
    - Solution: add `elastic-package stack shellinit` command in `.buildkite/scripts/common.sh. Example:
https://github.com/elastic/integrations/blob/0226f93e0b1493d963a297e2072f79431f6cc443/.buildkite/scripts/common.sh#L828
2. Not found license file:
    - Error: https://buildkite.com/elastic/integrations/builds/7644#018c883c-546f-4d32-ab4a-71e919ddebf8/270-309
      ```
      Error: checking package failed: building package failed: copying license text file: failure while looking for license "licenses/Elastic-2.0.txt" in repository: failed to find repository license: stat /opt/buildkite-agent/builds/bk-agent-prod-gcp-1703092724145948143/elastic/integrations/licenses/Elastic-2.0.txt: no such file or directory
      ```
    - Required to remove line defining `ELASTIC_PACKAGE_REPOSITORY_LICENSE` environment variable:
https://github.com/elastic/integrations/blob/0daff27f0e0195a483771a50d60ab28ca2830f75/.buildkite/pipeline.yml#L17
