### ISSUE TITLE
[ti_opencti] Integration pulls in indicators with opencti.indicator.revoked: true

### ISSUE THREAD

**Issue by semtex1987** [elastic/integrations#8747]
As title says, I've noticed the opencti index getting extremely bloated with tons of revoked or expired indicators that shouldn't be getting ingested. I've tested rolling over the index and purging all indicators, the integration then re-pulls all of the indicators back into a new index, including all the revoked indicators.

I have no idea how this is supposed to be handled, not a developer, so I'm unsure if the integration should be checking for revoked status and dropping the indicators in the ingest pipeline or if this is something that should be getting handled within OpenCTI itself.

I did add a custom processor to the logs.opencti@custom ingest pipline that drops logs with opencti.indictaor.revoked: true which seems to be working to stop the issue moving forward.

**Comment by kcreddy** [comment]
Hey @semtex1987 thanks for oenning this and also providing your feedback on how the indicator should be expired. 
We have an open issue which tracks the expiration of indicators for our Threat Intel packages https://github.com/elastic/integrations/issues/5369.
@jamiehynds I have added `ti_opencti` to the tracking list now. Feel free to change its priority and I can pick it up.

**Comment by semtex1987** [comment]
> Hey @semtex1987 thanks for oenning this and also providing your feedback on how the indicator should be expired. We have an open issue which tracks the expiration of indicators for our Threat Intel packages #5369. @jamiehynds I have added `ti_opencti` to the tracking list now. Feel free to change its priority and I can pick it up.

Perfect thank you! I did figure out that OpenCTI has a retention policy engine that I've configured to auto-purge expired IOCs so Elastic never even sees them, but having some logic on the elastic side as a failsafe wouldn't hurt! No rush, thanks!

**Comment by chrisberkhout** [comment]
@kcreddy Thanks! In addition to `opencti.indicator.revoked` there's `opencti.indicator.valid_until`. There's also `opencti.indicator.valid_from` but I assume those would generally have historical values.

Some background info related to "the integration then re-pulls all of the indicators back into a new index"...

When the integration starts up, it will have no cursor data and will start fetching indicators, ordered by `modified` ascending. Each page will have a cursor that's saved and used on the following request. Once the end is reached, an empty page with no cursor will be returned. This empty cursor is returned to the CEL input, but when there are no results the cursor is not saved. After an interval when a new request is made, it should reuse the cursor value from the last non-empty page. The cursor data should persist between restarts, but if it's cleared, fetching will start from the beginning again.

**Comment by kcreddy** [comment]
> In addition to opencti.indicator.revoked there's opencti.indicator.valid_until. There's also opencti.indicator.valid_from but I assume those would generally have historical values.

@chrisberkhout, Noted! Thanks for taking a look into this.

**Comment by chrisberkhout** [comment]
ICO expiration for OpenCTI is implemented in version 1.1.0 of the integration: https://github.com/elastic/integrations/pull/8920. That will run against OpenCTI versions before v5.12.24.

Support for OpenCTI v5.12.24 will arrive soon: https://github.com/elastic/integrations/pull/9088.
