### ISSUE TITLE
[GCP] New datasets should not be enabled by default.

### ISSUE THREAD

**Issue by leandrojmp** [elastic/integrations#8769]
Hello,

Everytime a new dataset is added to the GCP integration it is enabled by default, since those datasets may require aditional permissions that are not enabled on the credentials being used, this will make the agent running the integrations to be unhealthy and require manual intervention.

For example, we use the GCP integration to only get GCP audit logs, a new dataset, Cloud Run Metrics, was added on version [2.31.1](https://github.com/elastic/integrations/pull/8096), and our credentials do not have permissions to this kind of data, and it also seems to need extra configurations, so this made the Agent to be Unhealthy because of this error.

It would be better for the new datasets to not be enabled by default when upgrading the integration.

**Comment by andrewkroh** [comment]
I agree. New datasets enabled by default creates the same problems we had with Filebeat modules (https://github.com/elastic/beats/issues/17256).

**Comment by leandrojmp** [comment]
Hello @andrewkroh 

Just an update, this also happens on other integrations, we updated our AWS integration and one of the changes is that a new integration for the MSK was added, and this was enabled by default, since we do not use MSK and our credentials do not have permission to its metrics, the agent entered on an UNHEALTHY state.

Is there a generic issue about this?

**Comment by andrewkroh** [comment]
I'm not aware of a generic issue. But perhaps the Fleet team is aware of the issue and tracking it somewhere. @elastic/fleet?

**Comment by andrewkroh** [comment]
Closing. We can track this with #6104.
