### ISSUE TITLE
[Oracle Weblogic] Failure in dashboards after change in message datatype

### ISSUE THREAD

**Issue by ishleenk17** [elastic/integrations#8779]
In oracle weblogic Integration, there was a [change](https://github.com/elastic/integrations/pull/7971) of datatype of message field to comply with the ECS. Following this change, failure of dashboards was observed  `match_only_text fields do not support sorting and aggregations`. 

The failure happens since there are panels where aggregation (last_value) is being performed on the message field which now is match_only_text instead of keyword. 

Failure Screenshot: 
![image](https://github.com/elastic/integrations/assets/102962586/58df4fdd-f1d9-452c-9e5c-e4968c3aca4a)

![image (1)](https://github.com/elastic/integrations/assets/102962586/f188efee-47d9-4c76-905e-c2a2a5ee54d2)

![image (2)](https://github.com/elastic/integrations/assets/118714680/3b5366a1-875c-4a97-9feb-d11450ee9553)

cc: @andrewkroh, fyi

**Comment by harnish-elastic** [comment]
### Proposed solution

1. Convert table visualizations containing message fields to saved search. Going with this approach, the dashboard having issues will be fixed and users only need to upgrade the package. (Recommended)

2. Introduce a new field with a `keyword` data type and set the value of the message field. This allows the user to aggregate the new field in the dashboard. Going with this approach, the user will need to perform update by query/reindexing steps that would be more complicated for the user, because the already ingested data needs to be transferred to the new field that has keyword data type.

**Comment by ishleenk17** [comment]
@harnish-elastic : Lets go ahead with the 1st approach. Couple of things to keep in mind: 
1. All the other fields remain intact in the saved search
2. The titles of the columns should match the existing ones for ease of transitioning for the user. 

Please upload the screenshot of how the new saved search would look like

**Comment by harnish-elastic** [comment]
> 2. The titles of the columns should match the existing ones for ease of transitioning for the user.
There is no option to change the column title. However, the user can update the title for the saved search by adding a custom label to the field in the data view itself. Please refer to the below steps and ss.

- Go to the data view. Select the particular field enable Set custom label and provide the label to the field.
![image](https://github.com/elastic/integrations/assets/118714680/be8ecd39-0fa1-46e7-a5b1-c60350b0af41)

- Output will look like this
![image](https://github.com/elastic/integrations/assets/118714680/484fb13a-8844-4b40-ab4b-eaba82924093)

Note: If the user sets the custom label to the field, the discover will look as per the below ss. FYI, queries and filters use the original field name.

![image](https://github.com/elastic/integrations/assets/118714680/a797da5a-e087-4068-8e62-c5a2b255f16b)
![image](https://github.com/elastic/integrations/assets/118714680/ce1c845f-3772-451a-bd08-f11a014eb220)

**Comment by ishleenk17** [comment]
> Note: If the user sets the custom label to the field, the discover will look as per the below ss

If field name itself changes, I don't think its a good idea. 



> 2\. Introduce a new field with a `keyword` data type and set the value of the message field. This allows the user to aggregate the new field in the dashboard. Going with this approach, the user will need to perform update by query/reindexing steps that would be more complicated for the user, because the already ingested data needs to be transferred to the new field that has keyword data type.

Here, you mention that reindexing will be needed. In any case since there will be other places as well where message field will be used. So, I suppose reindexing will be required anyhow.

**Comment by harnish-elastic** [comment]
> Here, you mention that reindexing will be needed. In any case since there will be other places where message field will be used. So, I suppose reindexing will be required anyhow.

I agree we need to do reindexing steps for type-conversion of the message field (keyword to match_only_text). But if we want to achieve the second approach mentioned [here](https://github.com/elastic/integrations/issues/8779#issuecomment-1866041141), we need to give the user additional custom reindexing steps to copy data to the new field that we introduce (new keyword field).

**Comment by ishleenk17** [comment]
@harnish-elastic : Lets go ahead with approach 1
