### ISSUE TITLE
[System] Reduce configs we show user by default

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#88]
At the moment in the system package we show the user most configs by default. Instead I would propose that most of the ones we don't expect users to change often, we hide. Taking cpu as an example, I suggest to hide both `period` and `cpu Metrics`. This will make the system configuration much more compact.

![Screenshot 2020-06-17 at 10 19 06](https://user-images.githubusercontent.com/244900/84873884-29b32780-b084-11ea-8aff-e44d42575999.png)

**Comment by fearful-symmetry** [comment]
@ruflin sorry, I didn't see this until the auto-ping above. Do we do this on other integrations? I wonder if we should have some "show advanced options" toggle or something.

**Comment by ruflin** [comment]
We have this an use it for example in nginx:
![image](https://user-images.githubusercontent.com/244900/103517232-19249c00-4e72-11eb-833b-90aecca4d937.png)
