### ISSUE TITLE
User is navigated to inactive Links from Integration's overview page.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#880]
**Kibana version:**
7.13 snapshot Kibana Cloud environment 

**Host OS and Browser version:**
Windows, All

**Preconditions**
1.  7.13 Kibana Cloud environment should be available.
```
BUILD 39998
COMMIT 5443379a381211da2872be856417bdbfa656a7dd
```

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Integrations tab.
3. Look for 'Zeek' integration and navigate to integration overview page.
4. Click on link provided under heading 'Zeek Integration'. [Refer screenshot]

**NOTE:** Similar issue was observed under NATS integration.

Actual Result:
User is navigated to page having '404 Results found' message.

Expected Result: 
User should be navigated to Links that are active in state and helpful when referred.

**Screenshots:** 
![image](https://user-images.githubusercontent.com/72375798/113415941-e2f9a880-93dd-11eb-8fb7-6d055fe41aa8.png)

![image](https://user-images.githubusercontent.com/72375798/113415959-e9882000-93dd-11eb-8337-b27c3b21b1f0.png)

**Comment by EricDavisX** [comment]
This isn't a 'docs' issue for the Docs team, it is part of the Integration package, so moving to Integrations repo and it is 2 separate issues, too.  Team can process it onward as desired from here.  Thanks Diksha for logging!

**Comment by ph** [comment]
@andrewkroh Where should we send theses issues? Do you have specific board?

**Comment by andrewkroh** [comment]
@ph The team label for us is `Team:Security-External Integrations`. And we have a board called `Security External Integrations team planning`.

**Comment by simranvaseer-qasource** [comment]
Hi Team,
We have revalidated this issue on latest 8.5 Snapshot kibana Cloud environment and found it **fixed** for Zeek integrations.

- However, for Nats integration, user navigates to 'Page not found'.

**Build Details:**
BUILD: 56489
COMMIT: ac5064b771f6edc2a2ea71da9f68e1afcd08a539

**Screenshots:**
Zeek integration
![Untitled](https://user-images.githubusercontent.com/102019374/191429436-a02a5ca2-73dd-4183-b9d6-78c99be32002.png)



NATS integration
![1](https://user-images.githubusercontent.com/102019374/191429066-6d7eb126-1208-4905-bdec-e81bd1c5dcb1.png)

Please let us know if we are missing anything.
Thanks
