### ISSUE TITLE
[MISP] email-subject value (populated from a MISP server) in Elasticsearch named as the misp.attribute.value

### ISSUE THREAD

**Issue by SergeyDrachuk** [elastic/integrations#8808]
MISP (Elasticsearch Agent) Integration ver 1.28.0
Elasticsearch ver 8.11.1

Expecting a "threat.indicator.email.subject" (or similar) field  to be populated from a MISP server email-subject attribute.
But is exists in Elasticsearch only as the "misp.attribute.value" field

Request to the MISP server:

```
curl  --noproxy -k --insecure -X POST --header "Authorization: foobar" --header "Accept: application/json" --header "Content-Type: application/json" -d '
{
"type": "email-subject",
"value": "Subject Payment"
}'       https://10.1.1.31/attributes/restSearch
```
Response from the MISP server:
`{"response": {"Attribute": [{"id":"420552","event_id":"2396","object_id":"20596","object_relation":"subject","category":"Payload delivery","type":"email-subject","to_ids":false,"uuid":"dee0290e-7bba-4ab4-ac41-1a76449b5d81","timestamp":"1678803148","distribution":"5","sharing_group_id":"0","comment":"","deleted":false,"disable_correlation":false,"first_seen":null,"last_seen":null,"value":"Subject Payment","Event":{"org_id":"1","distribution":"1","id":"2396","info":"Email | RemcosRAT | \u0412\u0456\u0434\u0431\u0443\u043b\u043e\u0441\u044f \u0440\u043e\u0437\u0441\u0438\u043b\u0430\u043d\u043d\u044f \u043b\u0438\u0441\u0442\u0456\u0432, \u0449\u043e \u043c\u0456c\u0442\u044f\u0442\u044c \u0448\u043a\u0456\u0434\u043b\u0438\u0432\u0438\u0439 \u0432\u043a\u043b\u0430\u0434\u0435\u043d\u0438\u0439 .XLSX \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442. \u041f\u0440\u0438 \u0432\u0456\u0434\u043a\u0440\u0438\u0442\u0442\u0456 \u0432\u043a\u043b\u0430\u0434\u0435\u043d\u043e\u0433\u043e \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430 \u0435\u043a\u0441\u043f\u043b\u0443\u0430\u0442\u0443\u0454\u0442\u044c\u0441\u044f \u0432\u0440\u0430\u0437\u043b\u0438\u0432\u0456\u0441\u0442\u044c CVE 2017-11882 \u0434\u043b\u044f \u0437\u0430\u0432\u0430\u043d\u0442\u0430\u0436\u0435\u043d\u043d\u044f \u0428\u041f\u0417 RemcosRAT \u0456\u0437 \u0437\u043e\u0432\u043d\u0456\u0448\u043d\u044c\u043e\u0433\u043e \u0440\u0435\u0441\u0443\u0440\u0441\u0443, \u044f\u043a\u0435 \u0437\u0430\u043f\u0443\u0441\u043a\u0430\u0454\u0442\u044c\u0441\u044f, \u0437\u0430\u0432\u0430\u043d\u0442\u0430\u0436\u0443\u0454 \u0434\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u043c\u043e\u0434\u0443\u043b\u0456, \u0437\u0431\u0438\u0440\u0430\u0454 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044e \u043f\u0440\u043e \u043a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447\u0430 \u0456 \u0441\u0438\u0441\u0442\u0435\u043c\u0443 \u0442\u0430 \u0432\u0438\u043a\u043e\u043d\u0443\u0454 \u04212 \u043a\u043e\u043c\u0443\u043d\u0456\u043a\u0430\u0446\u0456\u044e. \u0423\u0437\u0430\u0433\u0430\u043b\u044c\u043d\u0435\u043d\u0438\u0439 \u043c\u0435\u0445\u0430\u043d\u0456\u0437\u043c \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438: Email --> XLSX --> URL --> EXE (RemcosRAT) -->C2.","orgc_id":"4","uuid":"8f8b970e-074d-42bd-93b5-463476142be7"},"Object":{"id":"20596","distribution":"5","sharing_group_id":"0"}}]}}`

From above the "value":"Subject Payment" exists in the MISP server with {"Attribute": [{"id":"420552","event_id":"2396", ...}]

Elasticsearch search shows the corresponding document with the "misp.attribute.value": "Subject Payment":

```
"_index": ".ds-logs-ti_misp.threat_attributes-default-2023.10.08-000050",
  "_id": "PLlLDLVMSwp64tiLd2qGSpbD0Cs=",
  "_version": 1,  "_score": 0,
  "_source": {
    "input": {      "type": "httpjson"    },
    "agent": {
      "name": "SIEM-INTEGR-1",
      "id": "0b30804e-ee26-42a1-acb1-8f76af13f78c",
      "type": "filebeat",
      "ephemeral_id": "0057fe59-9d93-42f3-be82-652cd084f7ef",
      "version": "8.10.2"
    },
    "@timestamp": "2023-03-14T14:12:28.000Z",
    "ecs": {      "version": "8.10.0"    },
    "data_stream": {
      "namespace": "default",
      "type": "logs",
      "dataset": "ti_misp.threat_attributes"
    },
    "organization": {     "id": "1"    },
    "elastic_agent": {
      "id": "0b30804e-ee26-42a1-acb1-8f76af13f78c",
      "version": "8.10.2",
      "snapshot": false
    },
    "misp": {
      "attribute": {
        "distribution": 5,
        "type": "email-subject",
        "object_id": "20596",
        "uuid": "dee0290e-7bba-4ab4-ac41-1a76449b5d81",
        "object_relation": "subject",
        "to_ids": false,
        "disable_correlation": false,
        "deleted": false,
        "event_id": "2396",
        "sharing_group_id": "0",
        "comment": "",
        "id": "420552",
        "category": "Payload delivery",
        "value": "Subject Payment"
      },
      "event": {
        "id": "2396",
        "distribution": 1,
        "orgc_id": "4",
        "uuid": "8f8b970e-074d-42bd-93b5-463476142be7",
        "info": "Email | RemcosRAT | ...: Email --> XLSX --> URL --> EXE (RemcosRAT) -->C2."
      },
      "object": {
        "sharing_group_id": "0",
        "id": "20596",
        "distribution": 5
      }
    },
    "threat": {
      "indicator": {
        "provider": "misp",
        "type": "email-message"
      },
      "feed": {
        "name": "MISP"
      }
    },
    "event": {
      "agent_id_status": "verified",
      "ingested": "2023-10-08T18:59:48Z",
      "created": "2023-10-08T18:59:38.547Z",
      "kind": "enrichment",
      "category": [        "threat"      ],
      "type": [        "indicator"      ],
      "dataset": "ti_misp.threat_attributes"
    },
    "tags": [      "forwarded",      "misp-threat_attributes"    ]
  },
  "fields": {
    "misp.attribute.to_ids": [      false    ],
    "misp.object.distribution": [      5    ],
    "elastic_agent.version": [      "8.10.2"    ],
    "event.category": [      "threat"    ],
    "misp.object.id": [      "20596"    ],
    "threat.indicator.provider": [      "misp"    ],
    "misp.event.info": [      "Email | RemcosRAT | ... : Email --> XLSX --> URL --> EXE (RemcosRAT) -->C2."    ],
    "agent.name": [      "SIEM-INTEGR-1"    ],
    "misp.attribute.value": [      "Subject Payment"    ],
    "event.agent_id_status": [      "verified"    ],
    "event.kind": [      "enrichment"    ],
    "misp.attribute.deleted": [      false    ],
    "threat.feed.name": [      "MISP"    ],
    "misp.attribute.disable_correlation": [      false    ],
    "misp.event.id": [      "2396"    ],
    "input.type": [      "httpjson"    ],
    "data_stream.type": [      "logs"    ],
    "misp.event.uuid": [      "8f8b970e-074d-42bd-93b5-463476142be7"    ],
    "tags": [      "forwarded",      "misp-threat_attributes"    ],
    "misp.attribute.id": [      "420552"    ],
    "misp.attribute.type": [      "email-subject"    ],
    "agent.id": [      "0b30804e-ee26-42a1-acb1-8f76af13f78c"    ],
    "ecs.version": [      "8.10.0"    ],
    "misp.attribute.uuid": [      "dee0290e-7bba-4ab4-ac41-1a76449b5d81"    ],
    "event.created": [      "2023-10-08T18:59:38.547Z"    ],
    "misp.attribute.comment": [      ""    ],
    "organization.id": [      "1"    ],
    "agent.version": [      "8.10.2"    ],
    "threat.indicator.type": [      "email-message"    ],
    "misp.attribute.object_id": [      "20596"    ],
    "misp.attribute.distribution": [      5    ],
    "misp.attribute.category": [      "Payload delivery"    ],
    "misp.object.sharing_group_id": [      "0"    ],
    "agent.type": [      "filebeat"    ],
    "event.module": [      "ti_misp"    ],
    "misp.attribute.sharing_group_id": [      "0"    ],
    "elastic_agent.snapshot": [      false    ],
    "elastic_agent.id": [      "0b30804e-ee26-42a1-acb1-8f76af13f78c"    ],
    "data_stream.namespace": [      "default"    ],
    "misp.attribute.object_relation": [      "subject"    ],
    "misp.event.orgc_id": [      "4"    ],
    "event.ingested": [      "2023-10-08T18:59:48.000Z"    ],
    "@timestamp": [     "2023-03-14T14:12:28.000Z"    ],
    "threat.feed.dashboard_id": [      "ti_misp-56ed8040-6c7d-11ec-9bce-f7a4dc94c294"    ],
    "misp.attribute.event_id": [      "2396"    ],
    "misp.event.distribution": [      1    ],
    "data_stream.dataset": [      "ti_misp.threat_attributes"    ],
    "event.type": [      "indicator"    ],
    "agent.ephemeral_id": [      "0057fe59-9d93-42f3-be82-652cd084f7ef"    ],
    "event.dataset": [      "ti_misp.threat_attributes"    ]
  }

```

MISP API Filters:

```
type:
  OR:
  - ip-src
  - ip-dst
  - domain
  - url
  - sha256
  - link
  - text
  - comment
  - yara
  - windows-scheduled-task
  - filename
  - md5
  - sha1
  - mime-type
  - attachment
  - hostname
  - datetime
  - uri
  - user-agent
  - email-src
  - email-subject
  - other
  - authentihash
  - vhash
  - imphash
  - regkey
```

**Comment by bhapas** [comment]
@SergeyDrachuk The field `threat.indicator.email.subject` is missing in ECS and hence it is temporarily mapped like this.

Its mentioned here too - https://github.com/elastic/integrations/blob/main/packages/ti_misp/data_stream/threat_attributes/elasticsearch/ingest_pipeline/default.yml#L501-L503

**Comment by SergeyDrachuk** [comment]
![image](https://github.com/elastic/integrations/assets/40959528/f71aa8b3-7b7f-4048-84af-2a87a5b92d16)
The screenshot is from real prod server (integration pullі only 2 MISP feeds).
We can see the "misp.attribute.value" holds many different types of non email-subject values.
The "misp.attribute.value" is the last important indicator without its own name.
Please consider possibility giving the "email-subject" any separate unique name to minimize
- a CPU utilization
- a "false positive" probability
by leaving matching the all non email-subject data in the "misp.attribute.value"

**Comment by bhapas** [comment]
@SergeyDrachuk Thanks for the info. Created a PR to fix this - https://github.com/elastic/integrations/pull/8837
