### ISSUE TITLE
Grok bug cisco_aironet.log version 1.12.1

### ISSUE THREAD

**Issue by aquintananieves2** [elastic/integrations#8828]
Provided Grok expressions do not match field value: [<190>201477: Jan  4 17:25:42.866: %CLIENT_ORCH_LOG-6-CLIENT_ADDED_TO_RUN_STATE: Chassis 2 R0/0: wncd: Username entry (00-00-00-00-00-00) joined with ssid (System-110) for device with MAC: 0000.0000.0000]

```[tasklist]
### Tasks
```

**Comment by bhapas** [comment]
@aquintananieves2 Thanks for raising the issue. Can you point us to the official source of this log pattern?

**Comment by sinzzor** [comment]
Same issue here @ Cisco Catalyst 9800-CL Wireless Controller 17.9.3
