### ISSUE TITLE
[Azure docs] Document how to collect any metrics using the generic Azure Monitor integration

### ISSUE THREAD

**Issue by zmoog** [elastic/integrations#8849]
## Situation

The [Azure Resource Metrics integration package](https://github.com/elastic/integrations/tree/main/packages/azure_metrics) supports collecting metrics for several Azure services. As of today, it supports:

- Compute VM
- Compute VM Scaleset
- Container instance
- Container registry
- Container services
- Database account
- Storage account

For all other Azure services, Elastic provides a generic [Azure Monitor integration](https://github.com/elastic/integrations/tree/main/packages/azure_metrics/data_stream/monitor) that users can set up to collect any metrics available on [Azure Monitor](https://learn.microsoft.com/en-us/azure/azure-monitor/overview).

## Problem

However, setting up the generic Azure Monitor integration requires:

1. Search the Azure Monitor [docs](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-compute-virtualmachines-metrics) for namespace and metrics information.
2. Write a YAML configuration snippet, including metric names, dimensions, and time grain.
3. Test and troubleshoot the configuration.

Some proactive users can accomplish these tasks, and others reach out to support.

## Solution?

We should provide a document to guide users from a list of metrics they're interested in to a running integration with as low friction as possible.

For example:

- Show where to search for namespace and metrics.
- Show how to turn the information in the Azure docs into a YAML config.
- Share how to set up dimensions, time grain, and collection interval.
- Describe common errors and how to deal with them.

CC @muthu-mps

**Comment by alaudazzi** [comment]
@zmoog and I met to discuss and agree on the following action plan:
1. [Maurizio] Draft the step-by-step procedure on how to collect metrics using the generic Azure Monitor integration
    Look for an example https://github.com/zmoog/public-notes/issues/74
2. [Arianna] Figure out the right format to apply to the new procedure
3. [Arianna] Add the new  procedure to the generic integration 
https://docs.elastic.co/integrations/azure_metrics/monitor [Monitor metrics](https://docs.elastic.co/integrations/azure_metrics/monitor)

**Comment by alaudazzi** [comment]
@zmoog 
As a side note to the discussion we had, on the Azure metrics docs I noticed that the initial block of text is duplicated on these Azure doc pages:
- [Container registry metrics](https://docs-elastic-blynkp9lb-elastic-dev.vercel.app/integrations/azure_metrics/container_registry)
- [Container service metrics](https://docs-elastic-blynkp9lb-elastic-dev.vercel.app/integrations/azure_metrics/container_service)
- [Database Account metrics](https://docs-elastic-blynkp9lb-elastic-dev.vercel.app/integrations/azure_metrics/database_account)
- [Monitor metrics](https://docs-elastic-blynkp9lb-elastic-dev.vercel.app/integrations/azure_metrics/monitor)
- [Resource metrics](https://docs-elastic-blynkp9lb-elastic-dev.vercel.app/integrations/azure_metrics)
- [Storage Account metrics](https://docs-elastic-blynkp9lb-elastic-dev.vercel.app/integrations/azure_metrics/storage_account)
- [Virtual machines metrics](https://docs-elastic-blynkp9lb-elastic-dev.vercel.app/integrations/azure_metrics/compute_vm)

**Short-term plan:**

1. Fix the link formatting
2. Improve the wording 
3. Harmonize the spelling:
    - `Resource Manager Endpoint` VS `Resource_manager_endpoint`
    - `Active Directory Endpoint` VS `active_directory_endpoint`

**Long-term plan:**
Figure out if and how this block of content can be single-sourced and referenced from each integration. It has to be noted that the current doc system has limitations that prevent us from reorganizing the Integrations doc nav tree into a more intuitive and logical structure.

CC @SubhrataK @bmorelli25

**Comment by alaudazzi** [comment]
Reporting [here](https://github.com/zmoog/public-notes/issues/69) a thread with the essential steps that @zmoog has drafted.
To be clarified:
1. how to consolidate this content
2. where to put it

**Comment by alaudazzi** [comment]
@zmoog thank you for the suggestion.
We also need to consider that whatever goes into a blog post is less maintainable from a doc perspective.
Happy to contribute whenever we get an agreement on how to handle this content. For the time being, I'll revert the status of this ticket to backlog.

**Comment by alaudazzi** [comment]
Sync with @zmoog on Apr 6 to identify the next steps:

1. In the **Integrations docs**, on the [Azure Resource Metrics](https://docs.elastic.co/integrations/azure_metrics) page add a section to distinguish generic metrics vs specialized metrics 
=> get initial input from https://github.com/elastic/integrations/pull/8553

2. In the **Observability guide**, create a new Azure monitoring section, similar to [AWS monitoring](https://www.elastic.co/guide/en/observability/current/monitor-amazon-web-services.html) to:
   - Show where to search for namespace and metrics.
   - Show how to turn the information in the Azure docs into a YAML config.
   - Share how to set up dimensions, time grain, and collection interval.
   - Describe common errors and how to deal with them.
=> get initial input from https://github.com/zmoog/public-notes/issues/69

**Comment by alaudazzi** [comment]
@zmoog Follow-up on our conversation yesterday:

In the Observability guide, we plan to create a new Azure monitoring section, similar to [AWS monitoring](https://www.elastic.co/guide/en/observability/current/monitor-amazon-web-services.html) that would include the existing Azure tutorials and a new use case on how to collect any metric using the Azure Monitor. The new structure would look like this:

- Azure Monitoring
   - [Monitor Microsoft Azure with Elastic Agent](https://www.elastic.co/guide/en/observability/current/monitor-azure-elastic-agent.html) 
      - How to collect any metric using the Azure Monitor
   - [Monitor Microsoft Azure with the Azure Native ISV Service](https://www.elastic.co/guide/en/observability/current/monitor-azure-native.html)
   - [Monitor Microsoft Azure with Beats](https://www.elastic.co/guide/en/observability/current/monitor-azure.html)

Can you confirm?

**Comment by alaudazzi** [comment]
cc @dedemorton

**Comment by alaudazzi** [comment]
As this work is evolving into two different documentation sets -- Observability Guide and Integrations docs -- I'll close this issue in favor of:
- https://github.com/elastic/integration-docs/issues/376
- https://github.com/elastic/observability-docs/issues/3742
