### ISSUE TITLE
Pulse Secure Integration enhancement/bug for session

### ISSUE THREAD

**Issue by zez3** [elastic/integrations#8858]
On Ivanti/Pulse Secure
22.6R2.1 (build 2487)

I've got the following event.original log:

` <134>1 2024-01-11T14:23:28+01:00 ssl-vpn01.mydom.mytld PulseSecure: - - - 2024-01-11 14:23:28 - ssl-vpn01 - [1.1.1.1] user.name@mydom.mytld(Admin SSO)[.Administrators][64e62c265e] - Session timed out for user.name@mydom.tld/Admin SSO (session:sidbe3ce20a68202d1b91a4be7060b78c4a2825ce9100000000) due to inactivity (last access at 13:51:42 2024/01/11). Idle session identified during routine system scan.`

In https://github.com/elastic/integrations/blob/main/packages/pulse_connect_secure/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L24

we need a second line that should/would contain the `\[%{DATA:pulse_secure.session}\] `

eg
```
'^(<%{NONNEGINT:log.syslog.priority:long}>%{NUMBER}?|%{SYSLOGTIMESTAMP} %{SYSLOGHOST:host.hostname} %{INT}) %{TIMESTAMP_ISO8601:_tmp.timestamp} (%{IP:observer.ip}|%{HOSTNAME:observer.hostname}) PulseSecure: - - - %{DATE2} - %{SYSLOGHOST:observer.name} - \[%{IPORHOST:client.address}\] (%{DATA}::)?(%{HOSTNAME:user.domain}\\)?%{USERNAME:user.name}?(@%{USERNAME:user.domain})?\(%{DATA:pulse_secure.realm}?\)\[%{DATA:pulse_secure.role}\]\[%{DATA:pulse_secure.session}\] - %{GREEDYDATA:message}'
```

**Comment by bhapas** [comment]
@zez3 Are you using any specific format to export these logs? Or a default format?

**Comment by zez3** [comment]
@bhapas nope, defaut all. One note, I see the new hardware has JSON export option. Perhaps that would be better for the future but for legacy boxes we should keep the integration as is.
Or better could we detect if the formst is json?
