### ISSUE TITLE
[mysql] Add replication status to mysql integration

### ISSUE THREAD

**Issue by jkochraleo** [elastic/integrations#8890]
I do need to monitor a mysql (or to be correct a mariadb) replication server.

For this it would be good to get the data from `SHOW REPLICA STATUS;` to elasticsearch/kibana.

https://dev.mysql.com/doc/refman/8.0/en/show-replica-status.html
https://mariadb.com/kb/en/show-replica-status/

As far as I can see this isn't currently implemented in the mysql integration.

Could this feature please be added? I'm willing to help where I can, but I don't know the codebase yet.

**Comment by muthu-mps** [comment]
cc: @SubhrataK, @lalit-satapathy

**Comment by niraj-elastic** [comment]
Hey @jkochraleo, I looked into the issue and i am planning to add Replica status data stream to current MySQL integration. I'll let you know more details soon.

**Comment by niraj-elastic** [comment]
Closing this issue since enhancement in done in this [PR](https://github.com/elastic/integrations/pull/10344).
