### ISSUE TITLE
Error page shows up on navigating to 'Add integration' page for Cisco package.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#891]
**Kibana version:**
8.0 snapshot Kibana Cloud environment 

**Host OS and Browser version:**
Windows, All

**Preconditions**
1.  8.0 Kibana Cloud environment should be available.
```
BUILD 41814
COMMIT f1d662932133c49f3c2efe334b60201eeaa20a7d
```

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Integrations tab.
3. Look for 'Cisco' integration and navigate to 'Add integration' page.

**Actual Result:**
Error page shows up on navigating to 'Add integration' page for Cisco package.

**Expected Result:** 
No error page should be displayed on landing to 'Add integration' page for Cisco package.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/113851413-1d39c000-97b9-11eb-97e9-cbf2cc1137fd.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
other Integrations work ok (did not test all tho) - Did the Cisco Integration get updated recently?  pinging @masci

**Comment by mtojek** [comment]
@EricDavisX

Hint:

You can look at the package "owner" field to find the team responsible for maintenance: https://github.com/elastic/integrations/blob/master/packages/cisco/manifest.yml#L42

**Comment by EricDavisX** [comment]
Thanks so much @mtojek - I *think* that means... @andrewkroh are you the team lead to ping for this then?

**Comment by andrewkroh** [comment]
There was a recent change in https://github.com/elastic/integrations/pull/775. @P1llus can you please have a look to see if you can figure out the cause. When I click "Add Integration" for Cisco 0.8.0 I can reproduce. This is what's in the dev console:

<img width="1363" alt="Screen Shot 2021-04-08 at 9 50 05 AM" src="https://user-images.githubusercontent.com/4565752/114038480-e793e600-984f-11eb-8995-d0050df28145.png">

**Comment by P1llus** [comment]
@andrewkroh Il see if I can find the issue yeah!

**Comment by dikshachauhan-qasource** [comment]
Closing this.. As it was fixed.
