### ISSUE TITLE
Add process.name.caseless to logs-system.* mapping

### ISSUE THREAD

**Issue by mbudge** [elastic/integrations#8913]
Please can we add process.name.caseless to the logs-system.* so we can get security rules which use this field working?

https://github.com/elastic/detection-rules/pull/3390

**Comment by w0rk3r** [comment]
Changes were incorporated in ECS: https://github.com/elastic/ecs/pull/2341.

They will probably be in 8.16, as this is not blocking any work and is an enhancement. I closed https://github.com/elastic/integrations/pull/9850 and will wait for the ECS release to modify the related rules.
