### ISSUE TITLE
Add EKS support to AWS Fargate integration

### ISSUE THREAD

**Issue by sorantis** [elastic/integrations#892]
AWS Fargate can work with both ECS and EKS container services. 
The previously added AWS Fargate integration focused mainly on ECS support. While ECS is a popular container service on AWS, we should also add support for EKS to our Fargate integration.

- [ ] AWS Fargate metrics for EKS
- [ ] AWS Fargate logs for EKS

**Comment by ravikesarwani** [comment]
Closing as stale. We will look at this as part of work we are doing with https://github.com/elastic/integrations/issues/2561
