### ISSUE TITLE
[Symantec EDR] Improve handling of timezones

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#8929]
When setting the timezone in the Symantec Endpoint Protection Integration (v2.13.0) to the expected zone, it doesn't work. Trying ET/EDT/EST produce the following error:
```
"@timestamp","data_stream.dataset","error.message"
"Dec 11, 2023 @ 12:55:49.701","symantec_endpoint.log","processor conditional: Unknown time-zone ID: ET"
```
Setting it manually to -5:00 works, but this requires manual adjust this for daylight savings time which isn't ideal.

This seems to relate to certain 3-letter timezone conventions not being defined in Java. If we look up [ZoneId](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/ZoneId.html), it supports “GMT”, “UTC”, or “UT”, or “”. As a test, it throws Unknown time-zone ID: ET if you call ZoneId.of(“ET”). So the approach of setting up a timezone like -05:00 is the correct and supported way.

Short zone IDs have been deprecated, but there is EST (mapping to -05:00), but this does not include daylight savings per (SHORT_IDS in the [ZoneId](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/ZoneId.html) doc). 

Can our integration support Short zone IDs such as ET/EDT/EST and this avoids manual timezone changes when daylight savings kicks in?

**Comment by efd6** [comment]
AFAICS this is working as intended. If the user uses the IANA identifier for their timezone then the pipeline is successful. For example with the pipeline tests modified so
```diff
diff --git a/packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-common-config.yml b/packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-common-config.yml
index 23ea05947..14d7aebd4 100644
--- a/packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-common-config.yml
+++ b/packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-common-config.yml
@@ -5,4 +5,4 @@ fields:
     - forwarded
     - preserve_original_event
   _conf:
-    tz_offset: UTC
+    tz_offset: America/New_York
```
We correctly see the ET time zone used, applying DST as appropriate.

The reason that full IANA labels should be used is that informal broad swath timezone labels like ET are ambiguous (there may well be another ET globally) and fail to take into account local regulatory differences in time zone application (for example late or early changes in daylight saving time use).

The current list of IANA timezone labels is available [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

**Comment by narph** [comment]
@jamiehynds , @efd6 can we close this issue?

**Comment by efd6** [comment]
I think so, but wait for @jamiehynds.
