### ISSUE TITLE
elastic/obs-infraobs-integrations: Address skipped validation SVR00004 (batch 2)

### ISSUE THREAD

**Issue by shmsr** [elastic/integrations#8938]
Inline the visualizations in packages as "by values" panels using https://github.com/elastic/visualizations_integrations_tools.

Please find the list of packages that requires inlining viz in the description of this https://github.com/elastic/integrations/issues/8452. Also see https://github.com/elastic/integrations/pull/8423 where already 8 packages have inlined viz. Multiple packages were left out in this PR as support for inlining saved searches was not there when making the change but the required enhancement is [merged](https://github.com/elastic/visualizations_integrations_tools/issues/2) to the inlining tool.

Please see "Tip" in the [description](https://github.com/elastic/integrations/pull/8423#issue-1981874775) to learn how to use this tool to make the change. Please make sure to create separate commits for separate packages.

Relates:

- https://github.com/elastic/integrations/issues/8452#issuecomment-1903629921
- https://github.com/elastic/integrations/issues/8452
- https://github.com/elastic/integrations/pull/8423

**Comment by harnish-elastic** [comment]
Here is a list of packages (11 packages) that have SVR00004 with the kibana.version and will be covered in this sprint:

```
activemq == ^8.8.0
apache_tomcat == ^8.8.0
cassandra == ^8.8.0
kafka == ^8.8.0
microsoft_sqlserver == ^8.10.2
mongodb == ^8.8.0
mysql == ^8.8.2
nginx == ^8.8.0
postgresql == ^8.8.0
redis == ^8.10.2
system == ^8.10.2
```

**Comment by harnish-elastic** [comment]
I have installed node 16.14.2 (mentioned as pre-requisites) and ran the command `KIBANA="<kibana connection string>" node inline.js <path to kibana folder>` with stack `8.8.0` for activemq. The script has modified the dashboard and while doing stack up, I am facing the attached error in the dashboard!

![image](https://github.com/elastic/integrations/assets/118714680/b368bc7e-eae2-436d-bbe2-79736deb0896)
[activemq-eac72840-f916-11ec-9736-016ee09668f5.json](https://github.com/elastic/integrations/files/14021977/activemq-eac72840-f916-11ec-9736-016ee09668f5.json)

cc: @drewdaemon

**Comment by drewdaemon** [comment]
As mentioned outside this thread, support for inline saved searches wasn't added until Kibana `8.10` ([PR](https://github.com/elastic/kibana/pull/146849)).

**Comment by harnish-elastic** [comment]
> As mentioned outside this thread, support for inline saved searches wasn't added until Kibana `8.10` ([PR](https://github.com/elastic/kibana/pull/146849)).

Thank you for the help @drewdaemon!

@lalit-satapathy Based on the inline saved searches that added after 8.10 Kibana, we need to bump the Kibana to at least 8.10 to fix validation SVR00004. Here is the list of packages that need strict bump up from 8.8.0 to 8.10.0! Also if we bump the Kibana from 8.8 to 8.10, Users won't get any new release in 8.8.0 for that package as well user must need to update stack to 8.10 if they want future release! Let me know your thoughts on this!

```
activemq == ^8.8.0
apache_tomcat == ^8.8.0
cassandra == ^8.8.0
kafka == ^8.8.0
mongodb == ^8.8.0
mysql == ^8.8.2
nginx == ^8.8.0
postgresql == ^8.8.0
```

**Comment by lalit-satapathy** [comment]
We need Kibana 8.10 for supporting pass-by-value in dashboard, in these packages? Is there something unique in these packages which require this [PR](https://github.com/elastic/kibana/pull/146849) fix?

We enabled the pass-by-value in host of other [packages](https://github.com/elastic/integrations/pull/8423/) without stack upgrade right? 

I am fine with these stack upgrades, if absolutely needed, as we did similar for Lens & TSDB.

CC: @tommyers-elastic

**Comment by drewdaemon** [comment]
As far as I understand, `SVR00004` expresses a preference from the Fleet team for by-value panels.

All the panel types which are [checked by that rule](https://github.com/elastic/package-spec/blob/main/code/go/internal/validator/semantic/validate_visualizations_used_by_value.go#L78) can be by-value prior to Kibana `8.10` with the exception of saved searches.

So, it seems to me that we could either
- convert all by-reference panels to by-value _except_ saved searches and keep skipping `SVR00004`
- convert all saved searches to by-value, bump the minimum Kibana version to `8.10` and unskip `SVR00004`

Just depends on the priority of making those saved searches by-value vs continuing to support `8.8` and `8.9`.

**Comment by tommyers-elastic** [comment]
i would vote to keep saved searches by reference and avoid bumping stack version. it's a bit annoying though that we have to keep skipping the rule which means we don't get alerted if we added a new by-ref visualisation in the future.

**Comment by drewdaemon** [comment]
Could always [propose a change](https://github.com/elastic/package-spec/issues/new?assignees=&labels=discuss&projects=&template=Change_Proposal.md&title=%5BChange+Proposal%5D+) to package-spec so that `SVR00004` only checks saved searches if the stack version is `8.10` or greater.

**Comment by lalit-satapathy** [comment]
> i would vote to keep saved searches by reference and avoid bumping stack version. it's a bit annoying though that we have to keep skipping the rule which means we don't get alerted if we added a new by-ref visualisation in the future.

I agree to not bump the version unless we are already at a stack version >= 8.10.

For the remaining ones, we still need to skip SVR00004? is that correct.

**Comment by harnish-elastic** [comment]
> > i would vote to keep saved searches by reference and avoid bumping stack version. it's a bit annoying though that we have to keep skipping the rule which means we don't get alerted if we added a new by-ref visualisation in the future.
> 
> I agree to not bump the version unless we are already at a stack version >= 8.10.
> 
> For the remaining ones, we still need to skip SVR00004? is that correct.

@lalit-satapathy, I have raised a separate [PR](https://github.com/elastic/integrations/pull/9053) for fix validation SVR00004 whose Kibana is already > 8.10 (redis, system and microsoft_sqlserver)

For the [remaining 8 packages](https://github.com/elastic/integrations/issues/8938#issuecomment-1907554969), I have converted the [PR](https://github.com/elastic/integrations/pull/9011) to draft.

cc: @tommyers-elastic

**Comment by lalit-satapathy** [comment]
@harnish-elastic, @shmsr, 

What is the next step plan for closing this issue?

**Comment by harnish-elastic** [comment]
> @harnish-elastic, @shmsr,
> 
> What is the next step plan for closing this issue?

SVR00004 validation is for the following list is already addressed as per this task. https://github.com/elastic/integrations/issues/9323

```
activemq
apache_tomcat
cassandra
kafka
mongodb
mysql
nginx
postgresql
```

@shmsr We can close this issue.

**Comment by shmsr** [comment]
Thanks @harnish-elastic 🙌🏽
