### ISSUE TITLE
Dashboard issues with "[Windows AppLocker] Audited and Blocked Applications" dashboard as provided by "Windows" integration 1.44.1

### ISSUE THREAD

**Issue by eriroley** [elastic/integrations#8969]
there appears to be an insufficient filter on the "Top File names by Application Execution Count" (especially since I only have a single host that is reporting AppLocker events right now)
![image](https://github.com/elastic/integrations/assets/20193894/77067048-b1c9-49cd-a9d1-0ec3f8cf1757)
When I examine the data in Discover, I see that it is looking in logs-* for "File.name":*
![image](https://github.com/elastic/integrations/assets/20193894/8a707786-d220-43bf-844b-4fd43cb7d413)

I suggest adding the filter for "event.provider:Microsoft-Windows-Applocker" (which I had to edit in Lens)
![image](https://github.com/elastic/integrations/assets/20193894/6a665221-e516-4868-9f92-4914fe508227)

A similar filter probably needs to be added to file publishers based on FQBN by application execution count, and honestly, probably all of the panels

**Comment by jamiehynds** [comment]
@nicpenning is this something you've seen with the AppDocker dashboards you created awhile back?

**Comment by nicpenning** [comment]
@jamiehynds Yes, this was a good catch. I can try and find the time to correct this and send out the PR.

**Comment by nicpenning** [comment]
@eriroley - new package for this should be available.  Please let us know if the issue persists!
