### ISSUE TITLE
[Reindexing] Replace list of steps with a reference link of reindexing in packages

### ISSUE THREAD

**Issue by aliabbas-elastic** [elastic/integrations#9025]
- As a part of providing reindexing steps to the user, packages were included with these steps which seem to be lengthier and repetitive work for every package to include them in README. Here is an [example](https://github.com/elastic/integrations/tree/main/packages/oracle_weblogic/docs#:~:text=123%2CkeyStoreType%3DJKS-,Troubleshooting,-Conflicts%20in%20any) of it.
- We can replace them with a better version of providing Elastic Doc link instead like it is done [here](https://github.com/elastic/integrations/blob/main/packages/apache_spark/docs/README.md#:~:text=Driver%20and%20Executor.-,Troubleshooting,-If%20host.ip).

Following is the list of integrations which would require this change.

### TSDB Related Reindexing Steps

- Oracle WebLogic 
   - Data streams 
      - Deployed Application
      - ThreadPool

### Non- TSDB Related Reindexing Steps

- Oracle WebLogic
   - Data streams
      - Managed Server
      - Admin Server
      - Domain
      - Access
- Ceph
- Golang
- Salesforce

cc:- @alaudazzi

**Comment by aliabbas-elastic** [comment]
@alaudazzi I think this issue can be marked as Duplicate as the work is already going on [here](https://github.com/elastic/integrations/issues/8017). Should we close this one instead?

**Comment by bmorelli25** [comment]
duplicate
