### ISSUE TITLE
[Zeek] Kerberos dataset integration dissect processor fails if (opt) cert.client does not exist

### ISSUE THREAD

**Issue by predogma** [elastic/integrations#9026]
The [Zeek integration](https://docs.elastic.co/en/integrations/zeek) with match to the Zeek logs [kerberos](https://docs.elastic.co/en/integrations/zeek#kerberos) dataset. 

The cert.* are optional, based on the Zeek documentation the server.cert_subject, client.cert_subject are there with kerberos, though optional based on documentation
- https://docs.zeek.org/en/master/scripts/base/protocols/krb/files.zeek.html
- https://docs.zeek.org/en/master/scripts/base/protocols/krb/main.zeek.html
- https://github.com/zeek/zeek/blob/master/scripts/base/protocols/krb/main.zeek#L14-L51

The pipeline expects data similar to this [sample](https://github.com/elastic/integrations/blob/main/packages/zeek/_dev/deploy/docker/sample_logs/kerberos.log), which includes certs.client_subject, certs.server_subject.

If the raw incoming data, does not have cert.client, an error is thrown by pipeline.  There is a dependency in the dissect for the existence of the cert.client in pipeline causing error to occur.
```
...Error message: “cannot access method/field [contains] from a null def reference”...
```

zeek.kerberos field cert.client (ignore failure true)
- https://github.com/elastic/integrations/blob/main/packages/zeek/data_stream/kerberos/elasticsearch/ingest_pipeline/default.yml#L125

zeek.kerberos.client dissect fails, needs to be corrected if cert.client does not exist
- https://github.com/elastic/integrations/blob/main/packages/zeek/data_stream/kerberos/elasticsearch/ingest_pipeline/default.yml#L181

Workaround is to modify the dissect processor from
```
{
    "dissect": {
      "field": "zeek.kerberos.client",
      "pattern": "%{user.name}/%{user.domain}",
      "ignore_missing": true,
      "if": "ctx.zeek?.kerberos?.client.contains('/')"
    }
  }
```
To
```
{
    "dissect": {
        "field": "zeek.kerberos.client",
        "pattern": "%{user.name}/%{user.domain}",
        "ignore_missing": true,
        "if": "ctx.zeek?.kerberos?.client != null && ctx.zeek?.kerberos?.client.contains('/')"
    }
}
```

**Comment by taylor-swanson** [comment]
It looks like this was just fixed by #9005 and available in zeek `2.22.3`
(https://github.com/elastic/integrations/pull/9005/files)

Where there any other fields at fault here? It looks like `host.ip` and `source.ip` were also fixed as part of that change.

**Comment by taylor-swanson** [comment]
And in case we see this in any other integration, we have a parent issue that these are being tracked in: https://github.com/elastic/integrations/issues/8646

**Comment by predogma** [comment]
Bare with me, does this actually catch if the variable does not exist?
```
```

**Comment by taylor-swanson** [comment]
Oh I see what you're saying...

If the variable doesn't exist, it will catch that condition. If `zeek.kerberos.client` itself exists but is null, I'm not sure. Let me test that scenario quick. That might be an edge case we missed.

**Comment by taylor-swanson** [comment]
Oh of course, `client` needs to be `client?`. So that line should look like this:

```
if: ctx.zeek?.kerberos?.client?.contains('/') == true
```

With that expression, `client` can either be missing entirely or it does exist, but the value is `null`. I'll work on getting a fix out for that.
