### ISSUE TITLE
[Azure Firewall] Certain Logs are not being parsed correctly

### ISSUE THREAD

**Issue by Erikg346** [elastic/integrations#9037]
#### Describe the issue:
Azure firewall logs seem to skip the ingest pipeline that parses out fields 
It's possible grok patterns are missing from logs-azure.firewall_logs-1.8.3 ingest pipeline

Log Categories:
- AZFWDnsQuery
- AZFWNatRule
- AZFWNetworkRule
- AZFWApplicationRule

Example messages from event.original:
Network Rule:
![image](https://github.com/elastic/integrations/assets/91048673/0a46a8cc-a7fd-46ee-bab6-7ba70ccc564c)

Application Rule:
![image](https://github.com/elastic/integrations/assets/91048673/d69862fb-4d99-4c5b-8118-bf567a9bc820)

From initial look, looks like the pipeline uses grok processor on "json.properties.msg" but these example events don't contain nested msg:
![image](https://github.com/elastic/integrations/assets/91048673/705c3c76-8e39-47e7-a710-824953a63dba)

**Comment by zmoog** [comment]
@Erikg346, which log category did you select in the Azure Firewall diagnostic settings?

It would be great to have a screenshot like the following one (or list the category names, as you prefer):

![image](https://github.com/elastic/integrations/assets/25941/1bd49424-4a37-4e60-859d-170ca01216b4)

**Comment by zmoog** [comment]
We can infer the option they checked from the category name (i.e., AZFWNatRule —> "Azure Firewall Nat Rule"), but I'd love to know what you are most interested into

**Comment by zmoog** [comment]
My current understanding is the Azure Firewall integration does not support the new formats introduced by the [Resource Specific Structured Logging](https://techcommunity.microsoft.com/t5/azure-network-security-blog/exploring-the-new-resource-specific-structured-logging-in-azure/ba-p/3620530) yet. Still, I'm double-checking with the security integrations team to know more.

**Comment by Erikg346** [comment]
@zmoog yes you are correct the current Elastic Integration doesn't support the new formats. The weird part is we have the setting enabled for 'Azure Diagnostics', not 'Resource Specific'.
![image](https://github.com/elastic/integrations/assets/91048673/639fcafd-ac66-4989-940d-37011a4e330a)

**Comment by muthu-mps** [comment]
The firewall logs integration doesn't support the structured logs introduced in [Azure](https://techcommunity.microsoft.com/t5/azure-network-security-blog/exploring-the-new-resource-specific-structured-logging-in-azure/ba-p/3620530). We will enhance the ingest pipeline to provide support for structured format in such a way that both the log formats will be supported.
