### ISSUE TITLE
[Pulse Connect Secure] integration stopped loggin after update to 1.18.2

### ISSUE THREAD

**Issue by olmanolsztyn** [elastic/integrations#9043]
I noticed that after upgrade Pulse Secure Integration to 1.18.2 version stopped logging events.

**Comment by jamiehynds** [comment]
Hey @olmanolsztyn - do you know what version you upgraded from? 1.18.2 was a minor documentation change on our side and didn't update any of the pipeline logic so it's unlikely that update would impact ingestion. 

Would you be able to raise a support issue and provide debug logs so we can take a closer look?

tagging @legoguy1000 as the original developer Pulse Secure integration and may have some thoughts.

**Comment by legoguy1000** [comment]
I just built it based off the documentation. What's actually broken? It's just a TCP/UDP input for syslog.

**Comment by legoguy1000** [comment]
I would check the agent logs. If needed enable debug logging and hopefully you'll see an error reported that explains why nothing is getting indexed.

**Comment by rkerr** [comment]
Am seeing the same, I think this actually broke in 0.18.1 as a result of pull request #8873. In my case I'm ingesting via logstash and getting:

> "error"=>{"type"=>"document_parsing_exception",
> "reason"=>"[1:228] object mapping for [pulse_secure.session] tried to parse field [session] as object, but found a concrete value"}

I guess the error would be slightly different without logstash in the way but the basic issue will be the same - there is already a field pulse_secure.session.id defined for storing session IDs, but the pull is using pulse_secure.session and trying to define it as a keyword when it already exists as an object.

In addition to that there seem to be a some other issues here:

* The changlog for 0.18.1 references the wrong pull request (8434 instead of 8873)
* The changes that have been made are matching anything in brackets as a session ID, which isn't always the case

I would guess the original change would be better implemented as a change to the grok on message not the one for event.original and using the existing SESSION pattern_definition rather than just capturing anything in brackets.

**Comment by olmanolsztyn** [comment]
I found something like this: "Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Date(2024, time.February, 5, 12, 51, 42, 340930324, time.Local), Meta:{"raw_index":"logs-pulse_connect_secure.log-default","truncated":false}"

**Comment by rkerr** [comment]
Digging a bit I see #8873 is related to #8858 and this message:

> <134>1 2024-01-11T14:23:28+01:00 10.5.2.3 PulseSecure: - - - 2024-01-11 14:23:28 - ssl-vpn01 - [89.160.20.156] user.name@mydom.mytld(Admin SSO)[.Administrators][64e62c265e] - Session timed out for user.name@mydom.tld/Admin SSO (session:sidbe3ce20a68202d1b91a4be7060b78c4a2825ce9100000000) due to inactivity (last access at 13:51:42 2024/01/11). Idle session identified during routine system scan.

It seems like the issue may be there are two different sessions IDs here: 64e62c265e and sidbe3ce20a68202d1b91a4be7060b78c4a2825ce9100000000

Unfortunately I can't seem to find much documentation on what these session IDs mean or why you'd need two different session IDs.

Prior to 0.18.1 you'd usually end up with the longer session id in pulse_secure.session.id and `.Administrators][64e62c265e` in pulse_secure.role which doesn't seem correct either.

It probably does make sense to modify the event.original grok as had been done, but the result can't be stored as pulse_secure.session (as this is an object) or pulse_secure.session.id (as this is already used for the longer session id). Maybe create a new field? something like pulse_secure.session.id_short ?

**Comment by austintp** [comment]
I was able to get around the error "object mapping for [pulse_secure.session] tried to parse field [session] as object, but found a concrete value" with the following change to the ingest pipeline:

https://github.com/elastic/integrations/blob/main/packages/pulse_connect_secure/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L24

`        - '^(<%{NONNEGINT:log.syslog.priority:long}>%{NUMBER}?|%{SYSLOGTIMESTAMP} %{SYSLOGHOST:host.hostname} %{INT}) %{TIMESTAMP_ISO8601:_tmp.timestamp} (%{IP:observer.ip}|%{HOSTNAME:observer.hostname}) PulseSecure: - - - %{DATE2} - %{SYSLOGHOST:observer.name} - \[%{IPORHOST:client.address}\] (%{DATA}::)?(%{HOSTNAME:user.domain}\\)?%{USERNAME:user.name}?(@%{USERNAME:user.domain})?\(%{DATA:pulse_secure.realm}?\)\[%{DATA:pulse_secure.role}\](?::?\[%{DATA:pulse_secure.session.id}\])? - %{GREEDYDATA:message}'`

In the current pipeline it tries to map a value to pulse_secure.session but the pulse_secure.session is defined as an object in the template mappings.

**Comment by bhapas** [comment]
> Digging a bit I see #8873 is related to #8858 and this message:
> 
> > <134>1 2024-01-11T14:23:28+01:00 10.5.2.3 PulseSecure: - - - 2024-01-11 14:23:28 - ssl-vpn01 - [89.160.20.156] [user.name@mydom.mytld](mailto:user.name@mydom.mytld)(Admin SSO)[.Administrators][64e62c265e] - Session timed out for [user.name@mydom.tld](mailto:user.name@mydom.tld)/Admin SSO (session:sidbe3ce20a68202d1b91a4be7060b78c4a2825ce9100000000) due to inactivity (last access at 13:51:42 2024/01/11). Idle session identified during routine system scan.
> 
> It seems like the issue may be there are two different sessions IDs here: 64e62c265e and sidbe3ce20a68202d1b91a4be7060b78c4a2825ce9100000000
> 
> Unfortunately I can't seem to find much documentation on what these session IDs mean or why you'd need two different session IDs.
> 
> Prior to 0.18.1 you'd usually end up with the longer session id in pulse_secure.session.id and `.Administrators][64e62c265e` in pulse_secure.role which doesn't seem correct either.
> 
> It probably does make sense to modify the event.original grok as had been done, but the result can't be stored as pulse_secure.session (as this is an object) or pulse_secure.session.id (as this is already used for the longer session id). Maybe create a new field? something like pulse_secure.session.id_short ?

@rkerr Yeah. There was missing documentation and yes , what you pointed seems right. There is already a `pulse_secure.session` object being created when `pulse_secure.session.id` is mapped. So will change the new `shorter session id` - which I am not sure where it comes from due to lack of documentation.

**Comment by bhapas** [comment]
@olmanolsztyn #9107 created to fix the issue

**Comment by bhapas** [comment]
New version `1.18.3` is released. Please upgrade and test.

**Comment by olmanolsztyn** [comment]
> New version `1.18.3` is released. Please upgrade and test.

Works like charm. Thank you.
