### ISSUE TITLE
[Kubernetes audit logs] Additional Fields mapping for detection

### ISSUE THREAD

**Issue by ynirk** [elastic/integrations#9046]
I'm using the Kubernetes Audit Log integration for creating Detection Rules.
There are some fields that would be beneficial for creating rules and for the general analyst experience.

- `kubernetes.audit.requestObject.spec.containers.image`
    It would be helpful to have the field as a keyword to be able to match specific image like `docker.elastic.co/beats/elastic-agent:*`

- additional mappings

```
kubernetes.audit.requestObject.spec.containers.command | text (to detect specific command like nsenter)
kubernetes.audit.requestObject.spec.containers.name | keyword
kubernetes.audit.requestObject.spec.containers.securityContext.seccompProfile.type | keyword (to detect unconfined)
kubernetes.audit.requestObject.roleRef.name | keyword (detect cluster-admin being granted)
```

**Comment by StephanErb** [comment]
Please also add `labels.*` to the mapping so that custom labels can be ingested and used for filtering.

**Comment by MichaelKatsoulis** [comment]
@ynirk this issue is about fixing some mappings and add some others (we don't have mappings set for all these fields) ?
So the fields are already there but with wrong/not useful mappings ? 
Except from the ecs fields.

**Comment by ynirk** [comment]
@MichaelKatsoulis here are some details

- `kubernetes.audit.requestObject.spec.containers.image` already exists as a text but would be more useful as a keyword

The following are extracted as part of the JSON processor but they don't have mappings in index/datastream template

- kubernetes.audit.requestObject.spec.containers.command | text (to detect specific command like nsenter)
- kubernetes.audit.requestObject.spec.containers.name | keyword
- kubernetes.audit.requestObject.spec.containers.securityContext.seccompProfile.type | keyword (to detect unconfined)
- kubernetes.audit.requestObject.roleRef.name | keyword (detect cluster-admin being granted)

**Comment by tetianakravchenko** [comment]
> Also it would be great to map some fields to ECS fields for better management in SIEM:
> 
> kubernetes.audit.requestObject.spec.containers.image -> container.image.name
> kubernetes.audit.requestObject.spec.containers.name -> container.name
> kubernetes.audit.requestObject.spec.containers.securityContext.privileged -> container.security_context.privileged
> 
> kubernetes.audit.annotations.authorization_k8s_io/decision -> event.outcome
> kubernetes.audit.verb -> event.action
> 
> kubernetes.audit.sourceIPs -> client.ip & source.ip
> 
> kubernetes.audit.user.uid -> user.id
> kubernetes.audit.user.username -> user.name
> kubernetes.audit.userAgent ->  user_agent processor

Hey @ynirk I've opened this PR - https://github.com/elastic/integrations/pull/10138
few questions regarding the ecs fields:
> kubernetes.audit.annotations.authorization_k8s_io/decision -> event.outcome

as I understand possible values of the `authorization_k8s_io/decision` are `[forbid](https://kubernetes.io/docs/reference/labels-annotations-taints/audit-annotations/#authorization-k8s-io-decision)` and `allow`, there are no other possible values, correct?
`event.outcome` field has a list of allowed values - https://www.elastic.co/guide/en/ecs/8.11/ecs-allowed-values-event-outcome.html

> kubernetes.audit.userAgent ->  user_agent processor

I've tried to use `user_agent`, but seems that used format of the `kubernetes.audit.userAgent` (example: `kindnetd/v0.0.0 (linux/amd64) kubernetes/$Format`, `kube-controller-manager/v1.29.1 (linux/amd64) kubernetes/bc401b9/leader-election`, `kube-probe/1.29`) doesn't follow the usual format, so a lot of fields, produced by the `user_agent` processor had value `Other`, I've decided to use the `set` processor and set `user_agent.original` only. Let me know what do you think

**Comment by ynirk** [comment]
> as I understand possible values of the authorization_k8s_io/decision are [forbid](https://kubernetes.io/docs/reference/labels-annotations-taints/audit-annotations/#authorization-k8s-io-decision) and allow, there are no other possible values, correct?

that's my understanding as well.
I don't know if it's possible to have `authorization_k8s_io/decision: forbid` mapped to `event.outcome: failure` (and allow to success)

> kubernetes.audit.sourceIPs is of type text at the moment, I've added convert processor to create source.ip of type ip, let me know if you think kubernetes.audit.sourceIPs type should be changed

As long as source.ip and client.ip are mapped as type ip, I think it's enough

> I've tried to use user_agent, but seems that used format of the kubernetes.audit.userAgent (example: kindnetd/v0.0.0 (linux/amd64) kubernetes/$Format, kube-controller-manager/v1.29.1 (linux/amd64) kubernetes/bc401b9/leader-election, kube-probe/1.29) doesn't follow the usual format, so a lot of fields, produced by the user_agent processor had value Other, I've decided to use the set processor and set user_agent.original only. Let me know what do you think

user_agent.original sounds good
Thanks for the PR

**Comment by tetianakravchenko** [comment]
@ynirk thank you for the reply!

> I don't know if it's possible to have authorization_k8s_io/decision: forbid mapped to event.outcome: failure (and allow to success)

I've added it in the ingest pipeline

also regarding this remapping:
```
kubernetes.audit.requestObject.spec.containers.image -> container.image.name
kubernetes.audit.requestObject.spec.containers.name -> container.name
kubernetes.audit.requestObject.spec.containers.securityContext.privileged -> container.security_context.privileged
```

I needed to remove this mapping, because kubernetes.audit.requestObject.spec.containers.* fields are arrays, and this processor:
```
- set:
    field: container.image.name
    copy_from: kubernetes.audit.requestObject.spec.containers.image
    ignore_empty_value: true
```
cause error:
<img width="1617" alt="Screenshot 2024-06-27 at 12 41 48" src="https://github.com/elastic/integrations/assets/28299531/47a7e280-bcdc-4337-86ac-6742e9f2dfa8">

It also might be confusing to have `container.name` as an array

**Comment by ynirk** [comment]
> need to remove the mapping kubernetes.audit.requestObject.spec.containers.image -> container.image.name

That shouldn't be an issue for detection as `kubernetes.audit.requestObject.spec.containers.image` will be mapped as keyword - it was an attempt to be ECS compliant
