### ISSUE TITLE
Integrations with missing owner.type field

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/integrations#9049]
The following Deployment and Devices-owned integrations are missing the `owner.type` field in `manifest.yml`:

| Integration | Expected Value |
| --- | --- |
| fortinet_forticlient | elastic |
| netscout | (skip, mark as deprecated) |
| radware | (skip, mark as deprecated) |
| squid | elastic |

**Comment by taylor-swanson** [comment]
@jamiehynds, would you know the values for `netscout` and `radware`? I looked at our spreadsheet, but didn't see them listed there. Based on the commit history, I think both would be `elastic`?

**Comment by jamiehynds** [comment]
Hey @taylor-swanson - they are both `elastic` but they were tech preview packages (RSA2ELK) that I believe were removed/deprecated some time ago?

**Comment by taylor-swanson** [comment]
Thanks, @jamiehynds.

It doesn't look like we have marked them as deprecated yet. Looks like `squid` is also an rsa2elk package. Looking at elastic/security-team#5447, we should indeed mark `radware` and `netscout` as deprecated, `squid` should be rewritten.

**Comment by taylor-swanson** [comment]
Closing as there is nothing to do here. All integrations listed are rsa2elk integrations that are either slated to be deprecated or rewritten.
