### ISSUE TITLE
Add secrets support to the Kubernetes integation

### ISSUE THREAD

**Issue by gizas** [elastic/integrations#9054]
This issue will track the work needs to be done to update sensitive fields that the kubernetes Integration is using as secrets.

The variables that will need to be defined as secrets are defined [here](https://github.com/elastic/integrations/issues/8610) in section Codeowner: @elastic/obs-cloudnative-monitoring

We will need to:
- Bump the package-spec version to 3.0.2 (secrets requirement)
- Bump min stack version to ^8.12.0 to avoid known bugs

**Relevant story:**
- https://github.com/elastic/integrations/pull/9022

**Comment by tetianakravchenko** [comment]
`_file$` fields will be excluded from the validation - https://github.com/elastic/package-spec/pull/712

so the option is to set explicitly `secret: false` for the `bearer_token_file` fields when setting the latest `format_version`, or wait when the mentioned above will be merged/released

**Comment by tetianakravchenko** [comment]
New scope of this issue: update the `format_version` of the k8s integration with the version that includes the [fix](https://github.com/elastic/package-spec/pull/712)
