### ISSUE TITLE
Remove explicit ECS mappings from existing integrations

### ISSUE THREAD

**Issue by gsantoro** [elastic/integrations#9071]
Existing integrations should remove explicit ECS mappings and rely on the source of truth ecs@mappings template shipped with the Stack version.

Currently, if I remove the file `packages/<package>/data_stream/<datastream>/fields/ecs.yml` which contains the reference to the external ecs fields and run integrations tests I get an error that all fields currently imported in ecs.yml are not defied.

One way to silence those errors involves adding a reference to the ecs mappings in a file at `packages/<package>/_dev/build/build.yml` like below

```yml
dependencies:
  ecs:
    reference: "git@v8.11.0"
    import_mappings: true
```

This issue is blocked by https://github.com/elastic/elastic-package/issues/1649 to solve the problem of importing ecs mappings from the component template `ecs@mappings` defined by the Elastic stack.

For metrics datastream we need to resolve https://github.com/elastic/integrations/issues/8623 before removing ecs.yml

Linked to https://github.com/elastic/integrations/issues/8542

**Comment by zmoog** [comment]
We agreed not to perform the change ourselves but to provide all the information the package owners need to do it themselves.

I will add a link to the docs when they are available.
