### ISSUE TITLE
[Snyk] Migrating from deprecated V1 API

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#9083]
Our Snyk integration collects vulnerability and audit logs from Snyk and relies on their V1 API, which has now been deprecated. Snyk are encouraging all partners to move to their [V3 API](https://docs.snyk.io/snyk-api#snyk-rest-api) to ensure no interruption to ingestion once the V1 API is fully end of life. 

We need to update our integration to point to the V3 API and ensure all authentication, data collection, normalisation, etc continues to work once on the V3 API. Snyk have agreed to give us an enterprise license in order to carry out the migration.

**Comment by gui-elastic** [comment]
Hello @chemamartinez, is there any ETA of when this feature will be merged?

**Comment by chemamartinez** [comment]
Hi @gui-elastic,

This is currently in our short-term planning and it will be started soon. I estimate it should be merged within a month.

**Comment by efd6** [comment]
It's planned.
