### ISSUE TITLE
[Sophos_Central] Request time not as aspected on request

### ISSUE THREAD

**Issue by crazyworlds** [elastic/integrations#9140]
Using this integration we have found a strange behavior.
On integration configuration we have set this settings :
interval : 360s
Initial Interval : 12h
Setting integration in trace mode we have found that the parameters don't comply with this settings, but the request set the parameter **from_date** at five months previously : 

The request : 
`"log.level":"debug","@timestamp":"2024-02-13T15:25:50.346+0100","message":"HTTP request","transaction.id":"XXXXXXXX-4","url.original":"https://api-eu02.central.sophos.com/siem/v1/alerts?from_date=1699541723&limit=200","url.scheme":"https","url.path":"/siem/v1/alerts","url.domain":"api-eu02.central.sophos.com","url.port":"","url.query":"from_date=1699541723&limit=200","http.request.method":"GET","user_agent.original":"Elastic-Filebeat/8.11.4 (linux; amd64; XXXXXXXXXXXXXXXXXXXXXXXXXX; 2024-01-06 03:20:45 +0000 UTC)","http.request.body.content":"","http.request.body.bytes":0,"http.request.mime_type":"","event.original":"GET /siem/v1/alerts?from_date=1699541723&limit=200 HTTP/1.1\r\nHost: api-eu02.central.sophos.com\r\nUser-Agent: Elastic-Filebeat/8.11.4 (linux; amd64; XXXXXXXXXXXXXXXXXXXXx; 2024-01-06 03:20:45 +0000 UTC)\r\nAccept: application/json\r\nAuthorization: Bearer `

And the response : 

`{"log.level":"debug","@timestamp":"2024-02-13T15:25:50.488+0100","message":"HTTP response","transaction.id":"XXXXXXXXX-4","http.response.status_code":400,"http.response.body.content":"{\n    \"error\": \"badRequest\",\n    \"correlationId\": \"XXXXXXXXXXXXXXXXXX\",\n    \"requestId\": \"XXXXXXXXXXXx\",\n    \"message\": \"From date should fall within last 1 day, 'fromDate': 1699541723\"\n}","http.response.body.bytes":229,"http.response.mime_type":"application/json","event.original":"HTTP/1.1 400 \r\nConnection: close\r\nContent-Length: 229\r\nContent-Type: application/json\r\nDate: Tue, 13 Feb 2024 14:25:50 GMT\r\nX-Correlation-Id: XXXXXXXXXXX\r\nX-Request-Id: XXXXXXXXXXXXXXXXXXXX\r\n\r\n","ecs.version":"1.6.0"}
`

The integration work until some months ago.
There is a way to solve this problem?

**Comment by efd6** [comment]
@crazyworlds I have merged a change that should fix this. It will be available soon as version v1.13.2. Please try with that version when it becomes available (this should be in the next hour or so).
