### ISSUE TITLE
[clarification] netflow.ip_class_of_service field values

### ISSUE THREAD

**Issue by LizardNerd** [elastic/integrations#9186]
Hello, I need some clarification about the field specified in the title.

When I look to "Traffic Analisys" dashboard, I see "Types of Service" charts which are made of values taken from the "netflow.ip_class_of_service". 

Why that values are numbers? How can I read those charts? I would expect to see values like "http, https, dns ecc.", so the protocol which generate the traffic and the bytes transmitted.

Could you please explain this to me? Thank you very much!

**Comment by andrewkroh** [comment]
I think that field contains the information describe here: https://www.rfc-editor.org/rfc/rfc5102.html#section-5.4.19

**Comment by LizardNerd** [comment]
Thank you @andrewkroh for pointing me this rfc doc!
