### ISSUE TITLE
[PingOne] Update documentation based on new Ping console layout

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#9191]
Our [PingOne documentation](https://docs.elastic.co/integrations/ping_one) walks through the steps the follow within the PingOne console to set up an application and gather the required info by our integration (client secret, etc). Ping have recently updated their console with new workflows and layout, and as a result our documentation is no longer accurate. 

We have access to a new PingOne console. Can we use this to update our documentation with the necessary steps, based on the new PingOne layout. 

Users should have clear steps to:

- Create a "worker" application
- Gather Token Endpoint
- Gather Environment ID, Client ID and Client Secret
- Configure our integration with the information gathered from Ping

**Comment by chrisberkhout** [comment]
@jamiehynds Can you please send me the PingOne console credentials? Or is there somewhere else I should get them?
