### ISSUE TITLE
Add documentation about CI pipelines run for every PR and on a daily basis

### ISSUE THREAD

**Issue by mrodm** [elastic/integrations#9262]
Add documentation about the CI pipelines that are defined for this repository into the CONTRIBUTING guide.

- CI pipelines that are being run for every Pull Request and merge to main or backport branches.:
    - Which Elastic stack versions are run for every package
    - How they can be re-triggered (github comments).
    - Which packages are being tested in each PR.
    - Add links to Buildkite jobs.
    - Definitions:
        - [Main pipeline](https://github.com/elastic/integrations/blob/22893c20773fc37e2086c89c59b71fb9fe8f3512/.buildkite/pipeline.yml)
- CI pipelines that are being run on a daily basis:
    - Which pipelines are triggered (currently, for Serverless and local Elastic stacks)
    - Which Elastic stack versions are tested in those pipelines triggered.
    - Which Serverless projects are tested.
    - Exceptions in Serverless projects (e.g. system test are not executed or geoip databases).
    - Add links to Buildkite jobs.
    - Definitions:
        - [Schedule daily job](https://github.com/elastic/integrations/blob/22893c20773fc37e2086c89c59b71fb9fe8f3512/.buildkite/pipeline.schedule-daily.yml)
        - [Serverless job](https://github.com/elastic/integrations/blob/22893c20773fc37e2086c89c59b71fb9fe8f3512/.buildkite/pipeline.serverless.yml)

**Comment by mrodm** [comment]
Where should these docs about the CI pipelines be added? Recently, documentation in the `docs` folder (CONTRIBUTING guide) has been moved to the observability-docs repository (#9796).

As this information is more about the how CI works (not so much use facing as probably other docs in the previous docs folder?), I was wondering if this fits in the README or in another location.

Should it be added a new section in the [README file](https://github.com/elastic/integrations/blob/6206668cd49b9943f2465c16a5eaccca91374a35/README.md) about CI since it is information more "local" to this repository? Or, 
should it be written in observability-docs a new file/section under ["Developer workflows"](https://www.elastic.co/guide/en/integrations-developer/current/developer-workflows.html)? WDYT @bmorelli25 @jsoriano ?

**Comment by bmorelli25** [comment]
Good questions. Apologies for the late reply, I've been on PTO.

I think it's important to point out that we want to move the source files for the Integration developer guide out of the observability-docs repo and into this repo. The source content for that guide makes more sense living here, along side most of the integration code.

Does knowing that ⬆️ change your opinion on where this content should land? Does that make the Developer Workflows section a more attractive place for this content to live? I think if the answer is yes, we should land it there. If you still believe this content is too separate from what we currently have in the IDG, then I think the readme is the right answer.
