### ISSUE TITLE
Metricbeat error when graphite metric value is `NaN`

### ISSUE THREAD

**Issue by masci** [elastic/integrations#931]
We had metrics like this coming out of graphite:

```
cassandra.org.apache.cassandra.metrics.CommitLog.WaitingOnSegmentAllocation.mean NaN 1617051654
```

and metricbeat wasn't able to process the corresponding event:

```
2021-03-17T23:28:21.920Z	ERROR	[publisher_pipeline_output]	pipeline/output.go:180	failed to publish events: unsupported float value: NaN
```

A fix [was added](https://github.com/elastic/go-structform/pull/28) and released with 7.13 to mitigate the problem, converting any `NaN`-like value to the JSON-valid value `null` but `graphite` might not be the only integration affected and the fix might not fit all use cases.

Filing this issue to assess if we're good with the fix linked above or if we should provide a different solution.

**Comment by sorantis** [comment]
> graphite might not be the only integration affected and the fix might not fit all use cases.

what are other integration that can potentially be impacted? and why would this solution not work for others?
