### ISSUE TITLE
Need to add data_stream.dataset filter in dashboards across all the integrations that have it missing.

### ISSUE THREAD

**Issue by lalit-satapathy** [elastic/integrations#9323]
As part of this task, need to add the data_stream.dataset filter across all the integrations.

Following integration will be covered as part of this 
As part of this https://github.com/elastic/integrations/issues/8751 work will be completed as well.
This issue will cover the integration those has owner obs-infraobs-integrations 
also please find the cloud packages list here: https://github.com/elastic/integrations/issues/10200

Following Packages either not dashboard or already having the data_stream.dataset filter:
- [x] Awsfargate
- [x] azure_app_service
- [x] azure_billing
- [x] Etcd
- [x] jolokia_input
- [x] kafka_log
- [x] prometheus_input
- [x] sql_input
- [x] stasd_input
- [x] Tomcat (Deprecated. Hence no need to update dashboards)
- [x] Salesforce
- [x] Redisenterprise
- [x] nagios_xi
- [x] Haproxy
- [x] Ibmmq
- [x] prometheus - https://github.com/elastic/integrations/pull/9995
- [x] oracle_weblogic - https://github.com/elastic/integrations/pull/9995
- [x] containerd -https://github.com/elastic/integrations/pull/9995
- [x] azure_application_insights - https://github.com/elastic/integrations/pull/9995
- [x] mysql - https://github.com/elastic/integrations/pull/9995
- [x] springboot - https://github.com/elastic/integrations/pull/9995
- [x] nginx ingress controller - https://github.com/elastic/integrations/pull/9995
- [x] nginx - https://github.com/elastic/integrations/pull/9995
- [x] istio - https://github.com/elastic/integrations/pull/9995
- [x] traefik - https://github.com/elastic/integrations/pull/9995
- [x] Kafka - https://github.com/elastic/integrations/pull/10075
- [x] microsoft_sqlserver - https://github.com/elastic/integrations/pull/10075
- [x] Mongodb -  https://github.com/elastic/integrations/pull/10075
- [x] php_fpm -  https://github.com/elastic/integrations/pull/10075
- [x] Postgresql - https://github.com/elastic/integrations/pull/10075
- [x] Rabbitmq - https://github.com/elastic/integrations/pull/10075
- [x] Redis - https://github.com/elastic/integrations/pull/10075
- [x] vsphere - https://github.com/elastic/integrations/pull/10075
- [x] websphere_application_server - https://github.com/elastic/integrations/pull/10075
- [x] azure_functions - https://github.com/elastic/integrations/pull/10075
- [x] mongodb_atlas - https://github.com/elastic/integrations/pull/10075
- [x] System - https://github.com/elastic/integrations/pull/9573
- [x] Oracle - https://github.com/elastic/integrations/pull/9655
- [x] Stan - https://github.com/elastic/integrations/pull/9869
- [x] Nats - https://github.com/elastic/integrations/pull/9869
- [x] Golang - https://github.com/elastic/integrations/pull/9869
- [x] Couchbase - https://github.com/elastic/integrations/pull/9869
- [x] Couchdb - https://github.com/elastic/integrations/pull/9869
- [x] IIS - https://github.com/elastic/integrations/pull/9869
- [x] Memcached - https://github.com/elastic/integrations/pull/9869
- [x] Zookeeper - https://github.com/elastic/integrations/pull/9869
- [x] InfluxDB - https://github.com/elastic/integrations/pull/9869
- [x] Coredns - https://github.com/elastic/integrations/pull/9869
- [x] ActiveMQ - https://github.com/elastic/integrations/pull/9768/
- [x] Apache Spark - https://github.com/elastic/integrations/pull/9768/
- [x] Apache Tomcat - https://github.com/elastic/integrations/pull/9768/
- [x] Hadoop - https://github.com/elastic/integrations/pull/9768/
- [x] Airflow - https://github.com/elastic/integrations/pull/9768/
- [x] Apache - https://github.com/elastic/integrations/pull/9768/
- [x] Cassandra - https://github.com/elastic/integrations/pull/9768/
- [x] Ceph - https://github.com/elastic/integrations/pull/9768/
- [x] Citrix ADC - https://github.com/elastic/integrations/pull/9768/
- [x] CockroachDB - https://github.com/elastic/integrations/pull/9768/

**Comment by milan-elastic** [comment]
> @milan-elastic, Lets target this for next sprint. Please update the description with details.
> 
> Looks overlap of: #8751

Sure! @lalit-satapathy

**Comment by lalit-satapathy** [comment]
Another duplicate: https://github.com/elastic/integrations/issues/7400

**Comment by lalit-satapathy** [comment]
Duplicate: https://github.com/elastic/integrations/issues/7217

**Comment by milan-elastic** [comment]
For the data_stream.dataset filter, I have found the couple of scenarios as mentioned below,

- There would be some dashboards where event.dataset is present instead of data_stream.dataaset so we will update that filter from event.dataset to data_stream.dataset
- If the dashboard contains the multiple data stream fields, we will add the data stream filters with OR operator,
  For example, if the dashboard is having session and memory data stream fields we will add e.g. `data_stream.dataset: apache_tomcat.session OR data_stream.dataset: apache_tomcat.memory`
  
From a PR perspective, we will structure our PRs as follows, categorizing them into the following groups of packages:
    - AWS 
    - Azure
    - GCP
    - Cloud Native packages
    - Infra-Obs packages 

If the PRs are too big, we'll divide them further.
CC: @lalit-satapathy @tommyers-elastic

**Comment by shmsr** [comment]
Duplicate https://github.com/elastic/integrations/pull/8348?

**Comment by ishleenk17** [comment]
> * There would be some dashboards where event.dataset is present instead of data_stream.dataset so we will update that filter from event.dataset to data_stream.dataset

Are the event.dataset and data_stream.dataset values always the same? To confirm that it doesn't break dashboards for existing users.

**Comment by milan-elastic** [comment]
> > * There would be some dashboards where event.dataset is present instead of data_stream.dataset so we will update that filter from event.dataset to data_stream.dataset
> 
> Are the event.dataset and data_stream.dataset values always the same? To confirm that it doesn't break dashboards for existing users.

So far we have noticed that it has the same values, but if we see if it's different I'll mention that explicitly in PR

**Comment by lalit-satapathy** [comment]
@milan-elastic, Can we close the Meta issue?

**Comment by milan-elastic** [comment]
> @milan-elastic, Can we close the Meta issue?

I can close this and keep the cloud packages separately like this: https://github.com/elastic/integrations/issues/10200

**Comment by lalit-satapathy** [comment]
Ok, closing per above.
