### ISSUE TITLE
Living off the Land Detection - Update supported data (documentation)

### ISSUE THREAD

**Issue by susan-shu-c** [elastic/integrations#9359]
## Overview

For the [ProblemChild](https://github.com/elastic/integrations/tree/main/packages/problemchild) (Living off the land detection) integration package, look into support for Elastic agent - Windows, aka [Windows agent integration](https://docs.elastic.co/en/integrations/windows).

Currently the package explicitly support `winlogbeat` and `Elastic Defend`.

- [x] ~~Elastic Defend `user.id` is inconsistent between `string` and `int`, while the package expects `string`, leading to errors when the `user.id` type is `int`~~ (see discussion below)
- [ ] Windows agent integration coverage is same if not more than winlogbeat, and we should consider testing the indices the package looks at to support integrations including (but not limited to) agent. This includes testing, updating documentation wording, and editing the package if needed.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists, [useful guidelines](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md) to follow
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

**Comment by jmcarlock** [comment]
> Elastic Defend user.id is inconsistent between string and int, while the package expects string, leading to errors when the user.id type is int

After following up with @susan-shu-c and @sodhikirti07 it turns out this isn't an issue. Elastic Defend provides `user.id` of `int` on POSIX and `user.id` of `keyword` on Windows. The [failed simulation](https://elastic.slack.com/archives/C05ASDWGY4S/p1708026008803409?thread_ts=1708025214.648069&cid=C05ASDWGY4S) was due to the ingest pipeline filtering this out as a POSIX record, as the [ingest pipeline](https://github.com/elastic/integrations/blob/a5d082a5f3335ecce6471469cf6c6ae083796682/packages/problemchild/elasticsearch/ingest_pipeline/problem_child_ingest_pipeline.yml#L5) for LotL/ProblemChild (shown below unrolled for clarity) only supports Windows records.

```
description: "Pipelines for ProblemChild detection"
processors:
  - pipeline:
      if: ctx.containsKey('event') && 
      ctx['event'].containsKey('kind') && 
      ctx['event'].containsKey('category') && 
      ctx['event']['kind'] == 'event' && 
      ctx['event']['category'].contains('process') && 
      ctx.containsKey('host') &&
      ctx['host'].containsKey('os') &&
    (ctx['host']['os'].containsKey('type') || 
        ctx['host']['os'].containsKey('family') ||
        ctx['host']['os'].containsKey('platform')) && 
    (ctx['host']['os']['type'] == 'windows' || 
        ctx['host']['os']['type'] == 'Windows' ||
        ctx['host']['os']['family'] == 'windows' || 
        ctx['host']['os']['family'] == 'Windows' || 
        ctx['host']['os']['platform'] == 'windows' || 
        ctx['host']['os']['platform'] == 'Windows')
```

@sodhikirti07 verified that Elastic Defend was [working](https://elastic.slack.com/archives/C05ASDWGY4S/p1708446829474839?thread_ts=1708025214.648069&cid=C05ASDWGY4S) with the integration.

>  Windows agent integration coverage is same if not more than winlogbeat, and we should consider testing the indices the package looks at to support integrations including (but not limited to) agent. This includes testing, updating documentation wording, and editing the package if needed.

The testing pipeline portion of this task would be covered by:
* https://github.com/elastic/security-team/issues/8774

I would suggest closing this issue.

**Comment by susan-shu-c** [comment]
Thanks for testing!

As for updating documentation wording, it seems that we can say that we support `Windows Agent` then as part of this ticket. Or, do you mean you want to install `Windows Agent` separately and test end to end as part of https://github.com/elastic/security-team/issues/8774 ? (Regardless, saying we support Windows Agent should be outside of https://github.com/elastic/security-team/issues/8774

**Comment by jmcarlock** [comment]
@susan-shu-c That's a good point, the agent integrations aren't mentioned in https://github.com/elastic/security-team/issues/8774, only checking if a package conforms to ECS. So you're right, it wouldn't fall under #8774.

This ticket is a good place to start for testing agent integrations, along the way I would suggest writing some team documentation on this process for repeatablilty.

After this we could also check how `Windows Agent` affects any other EA integration packages. (It provides [DNS records](https://github.com/elastic/integrations/tree/main/packages/windows#sysmonoperational) so it would probably support [DGA](https://github.com/elastic/integrations/blob/main/packages/dga/elasticsearch/ingest_pipeline/ml_dga_ingest_pipeline.yml), for instance.) 

Lastly, we could consider providing [system tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) for the common data stream providers (IE `Windows Agent`, `Elastic Defend`, `winlogbeat`) for all of the EA packages.

**Comment by susan-shu-c** [comment]
Windows VM with parallels: https://docs.google.com/document/d/142QvljTG7XkL-xHoRRiRvkk0hCuhQxU_sdq_OApiK4Q/edit#heading=h.ms18otpfijdi

**Comment by jmcarlock** [comment]
It was difficult to get the Elastic Windows Agent up and running. Thank you @sodhikirti07 for the help today and Friday! A couple of the older guides no longer work for this purpose. Here is a list of everything I tried:

1. [Install an Agent and Endpoint using Parallels](https://docs.google.com/document/d/142QvljTG7XkL-xHoRRiRvkk0hCuhQxU_sdq_OApiK4Q/edit#heading=h.ms18otpfijdi) - In this guide you setup a Kibana dev environment with the latest snapshot on your local machine and connect the Parallels Windows VM to that. It no longer works on step 12.
1. Tried substituting the Kibana dev environment for elastic-package using [Creating, testing and publishing Fleet integration packages](https://docs.google.com/document/d/1Z01Ga2VuHuofhf9y26q7UJJRcTrXOVSr4ZlSpbF-lHE/edit#heading=h.ydta45c6ljjv). It no longer works on 3a, and there is an open issue https://github.com/elastic/elastic-package/issues/1262. I was able to get the agent port open using https://github.com/elastic/elastic-package/pull/1795, but not the one needed for fleet.
1. I looked into running the Kibana dev environment on the Windows using Parallels. However, this needed to use another layer of virtualization and seemed overly complicated for what I was trying to do.
1. I was able to get Windows Agent in a ARM VM sending some data to Elastic Cloud. I am looking into if the correct fields are being sent.

If the approach in 4 send the correct data there are two other things I can try:
1. If the Windows VM doesn't work for the Windows Agent, I will look at starting a Windows instance in the cloud and connecting it to Elastic Cloud.
1. I believe it is possible to use #2 to install an [agent without Fleet](https://www.elastic.co/guide/en/fleet/current/install-standalone-elastic-agent.html).

**Comment by susan-shu-c** [comment]
Thanks for sharing these points!

## Notes from meeting:

* Reach out to follow up on https://github.com/elastic/elastic-package/issues/1262 
* Is there a new document for the [Parallels setup]([Install an Agent and Endpoint using Parallels](https://docs.google.com/document/d/142QvljTG7XkL-xHoRRiRvkk0hCuhQxU_sdq_OApiK4Q/edit#heading=h.ms18otpfijdi)) ? The person that created it seems to be Kevin Logan, who doesn't seem to be at Elastic any more. Slack #elastic-agent should also be the correct place to ask

**Comment by jmcarlock** [comment]
I was able to gather some sample logs from the Windows integration, along with a log to compare with from Elastic Defend.

- [Windows Integration - Sysmon (x86)](https://gist.github.com/jmcarlock/3c612e4b2d232845aa0d1db58a286b18)
- [Windows Integration - PowerShell (x86)](https://gist.github.com/jmcarlock/0234cc9f0d177bfdbb81280a7f5e29a8)
- [Elastic Defend (x86)](https://gist.github.com/jmcarlock/7f005bbba23717328a98e6ed6d2d273b)

I confirmed that neither sysmon or PowerShell in the Windows Integration work with the inference pipeline in LotL as is, but I believe they have the appropriate data. I will verify this and investigate what changes need to be made to support them.

**Comment by jmcarlock** [comment]
The inference pipeline of Living off the Land works fine with the Windows integration using sysmon. Looking into updates to the documentation.

**Comment by jmcarlock** [comment]
Here is the difference in featurization:

  | windows integration - sysmon | windows integration - powershell | elastic defend
-- | -- | -- | --
feature_command_line | c:\win_system_dir\notepad.exe | powershell start-process notepad.exe | powershell.exe  start-process notepad.exe
feature_elevated | FALSE | FALSE | FALSE
feature_elevation_type | unknown | unknown | unknown
feature_ends_with_exe | TRUE | FALSE | TRUE
feature_event_action | Process creation | Engine Lifecycle | start
feature_filename_mismatch | TRUE | FALSE | TRUE
feature_integrity_level | High | unknown | high
feature_normalized_ppath | win_system_dir | unknown | win_system_dir
feature_process_executable | c:\win_system_dir\notepad.exe | unknown | c:\win_system_dir\windowspowershell\v1.0\powershell.exe
feature_process_name | notepad.exe | unknown | powershell.exe
feature_process_parent_executable | c:\win_system_dir\windowspowershell\v1.0\powershell.exe | unknown | c:\win_system_dir\cmd.exe
feature_process_parent_name | powershell.exe | unknown | cmd.exe
feature_process_pe_original_file_name | NOTEPAD.EXE | unknown | PowerShell.EXE
feature_process_signed | FALSE | FALSE | TRUE
feature_process_signer_trusted | FALSE | FALSE | TRUE
feature_running_as_system | TRUE | FALSE | FALSE
feature_user_id | S-1-5-18 | unknown | S-1-5-21-3261892665-114283024-1478164545-1000

**Comment by jmcarlock** [comment]
Added a more [rigorous test](https://github.com/elastic/security-ml/blob/7249b5402c6748e21580f502335a6c84806b3527/projects/test_ea_integrations/test_lotl.ipynb) (under "Test on live data from Elastic integrations") and I was able to collect the results from the same run of `powershell.exe Start-Process notepad.exe`.

  | feature_command_line | feature_elevated | feature_elevation_type | feature_ends_with_exe | feature_event_action | feature_filename_mismatch | feature_integrity_level | feature_normalized_ppath | feature_process_executable | feature_process_name | feature_process_parent_executable | feature_process_parent_name | feature_process_pe_original_file_name | feature_process_signed | feature_process_signer_trusted | feature_running_as_system | feature_user_id | prediction | prediction_score | model_id | prediction_probability | index | @timestamp |
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | powershell.exe start-process notepad.exe | FALSE | unknown | TRUE | Process creation | TRUE | High | win_system_dir | c:\win_system_dir\windowspowershell\v1.0\power... | powershell.exe | c:\win_system_dir\cmd.exe | cmd.exe | PowerShell.EXE | FALSE | FALSE | TRUE | S-1-5-18 | 0 | 0.057775 | problemchild_20210526_1.0 | 0.996874 | logs-windows.sysmon* | 2024-07-01T17:43:05.499Z
1 | powershell.exe start-process notepad.exe | FALSE | unknown | FALSE | Provider Lifecycle | FALSE | unknown | unknown | unknown | unknown | unknown | unknown | unknown | FALSE | FALSE | FALSE | unknown | 0 | 0.054858 | problemchild_20210526_1.0 | 0.946549 | logs-windows.powershell* | 2024-07-01T17:43:09.643Z
2 | powershell.exe start-process notepad.exe | FALSE | unknown | FALSE | Provider Lifecycle | FALSE | unknown | unknown | unknown | unknown | unknown | unknown | unknown | FALSE | FALSE | FALSE | unknown | 0 | 0.054858 | problemchild_20210526_1.0 | 0.946549 | logs-windows.powershell* | 2024-07-01T17:43:09.645Z
3 | powershell.exe start-process notepad.exe | FALSE | unknown | FALSE | Provider Lifecycle | FALSE | unknown | unknown | unknown | unknown | unknown | unknown | unknown | FALSE | FALSE | FALSE | unknown | 0 | 0.054858 | problemchild_20210526_1.0 | 0.946549 | logs-windows.powershell* | 2024-07-01T17:43:09.645Z
4 | powershell.exe start-process notepad.exe | FALSE | unknown | FALSE | Provider Lifecycle | FALSE | unknown | unknown | unknown | unknown | unknown | unknown | unknown | FALSE | FALSE | FALSE | unknown | 0 | 0.054858 | problemchild_20210526_1.0 | 0.946549 | logs-windows.powershell* | 2024-07-01T17:43:09.649Z
5 | powershell.exe start-process notepad.exe | FALSE | unknown | FALSE | Provider Lifecycle | FALSE | unknown | unknown | unknown | unknown | unknown | unknown | unknown | FALSE | FALSE | FALSE | unknown | 0 | 0.054858 | problemchild_20210526_1.0 | 0.946549 | logs-windows.powershell* | 2024-07-01T17:43:09.653Z
6 | powershell.exe start-process notepad.exe | FALSE | unknown | FALSE | Provider Lifecycle | FALSE | unknown | unknown | unknown | unknown | unknown | unknown | unknown | FALSE | FALSE | FALSE | unknown | 0 | 0.054858 | problemchild_20210526_1.0 | 0.946549 | logs-windows.powershell* | 2024-07-01T17:43:09.670Z
7 | powershell.exe start-process notepad.exe | FALSE | unknown | FALSE | Engine Lifecycle | FALSE | unknown | unknown | unknown | unknown | unknown | unknown | unknown | FALSE | FALSE | FALSE | unknown | 0 | 0.054858 | problemchild_20210526_1.0 | 0.946549 | logs-windows.powershell* | 2024-07-01T17:43:09.709Z
8 | powershell.exe start-process notepad.exe | FALSE | unknown | TRUE | start | TRUE | high | win_system_dir | c:\win_system_dir\windowspowershell\v1.0\power... | powershell.exe | c:\win_system_dir\cmd.exe | cmd.exe | PowerShell.EXE | TRUE | TRUE | FALSE | S-1-5-21-3261892665-114283024-1478164545-1000 | 0 | 0.057775 | problemchild_20210526_1.0 | 0.996874 | logs-endpoint* | 2024-07-01T17:43:05.4994991Z

Now the predictions are returning similar results, however there are still two differences:
- Featurization is different for the Windows Integration with sysmon and PowerShell.
- The PowerShell part of the integration is significantly different and returns multiple records when running a command.

**Comment by susan-shu-c** [comment]
Hi Gus, so it seems like we can't simply claim that it'll work with Windows Agent (Elastic Agent) due to some of these differences. Thanks a lot for finding them!

I think we can close this ticket for now.

Next steps: I'm currently reaching out to people working on Windows Agent to see who I can track down to answer if these differences are intentional; and what we need to keep in mind if we go down the route of supporting Windows Agent.

I'll keep you in the loop once I get any info.

**Comment by jmcarlock** [comment]
Thanks @susan-shu-c !
