### ISSUE TITLE
Default configuration causing an ingestion error

### ISSUE THREAD

**Issue by clement-fouque** [elastic/integrations#9365]
For both Qualys VMDR Knowledge Base and Asset Host Detection, the default timeout option is set to `30s`. As calls are taking more time (especially for the knowledge base), it should be increased to the following:

## Request
Can we implement the following 2
### Change default values
| Module | Current value | New value |
|--------|--------|--------|
| Knowledge Base | 30s | 10m |
| Asset Host Detection | 30s | 10m |  

### Add a timeout error message
It would be nice if we could add a specific error message that the query failed because of the timeout.

## Error message
```json 
"error": {
      "message": [
        "failed eval: context deadline exceeded (Client.Timeout or context cancellation while reading body)",
        "Processor json with tag json_message in pipeline logs-qualys_vmdr.asset_host_detection-2.0.0 failed with message: field [message] not present as part of path [message]"
      ]
    },
```

**Comment by clement-fouque** [comment]
Knowledge base default value:

https://github.com/elastic/integrations/blob/0461976c59a84f1b20b0aad675899c46de093f1c/packages/qualys_vmdr/data_stream/knowledge_base/manifest.yml#L38

Asset Host Detection default value: 
https://github.com/elastic/integrations/blob/78e918dcd269eebc474a65afafdffd44e8e94017/packages/qualys_vmdr/data_stream/asset_host_detection/manifest.yml#L38

**Comment by efd6** [comment]
The current default for knowledge base is 3m, but will bump to 10m.

> It would be nice if we could add a specific error message that the query failed because of the timeout.

AFAICS this is already the case, "failed eval: context deadline exceeded (Client.Timeout or context cancellation while reading body)" says exactly this.

**Comment by clement-fouque** [comment]
> The current default for knowledge base is 3m, but will bump to 10m.

Thanks!

> AFAICS this is already the case, "failed eval: context deadline exceeded (Client.Timeout or context cancellation while reading body)" says exactly this.

Good point, I misunderstood our conversation and missed this! It's perfect!
