### ISSUE TITLE
EnvoyProxy Integration

### ISSUE THREAD

**Issue by SubhrataK** [elastic/integrations#9383]
This issue is to migrate the EnvoyProxy module from beats to agent-based integration.

**Comment by tehbooom** [comment]
Started development of this integration. For metrics will be following a similar model as the [Airflow](https://github.com/elastic/integrations/tree/main/packages/airflow) package.

PR to follow.

**Comment by tehbooom** [comment]
Metrics currently a blocker per 

https://github.com/elastic/beats/issues/39473

**Comment by ritalwar** [comment]
Just a quick question: I see we already have an EnvoyProxy Beats module, and we just want to create an agent-based integration for it. Why are we planning to use StatsD instead of using the existing EnvoyProxy Beats module for creating this integration?

**Comment by tehbooom** [comment]
@ritalwar The way our module was collecting the logs was simply doing a request to `/stats` with maybe 20 or so fields. 

Envoy does [support Statsd](https://www.envoyproxy.io/docs/envoy/latest/operations/stats_overview) and states it's typically how the metrics are collected. 

I did try to use the metric beat module but I noticed I was missing a lot of fields and they were in "Statsd format". So I thought it might be best to simply redo the metrics using Statsd or recreate the module using CEL input. 

I think Statsd is the way to forward here as it's what envoy is supporting and other applications are using Statsd as an input like DataDog.

**Comment by ritalwar** [comment]
If statsd seems like the best way forward based on your analysis, let's go with that, although we can update this [schema](https://github.com/elastic/beats/blob/9b338cd98efc3b44804817792bdce6d3e251f64d/metricbeat/module/envoyproxy/server/data.go#L30) to include more/missing fields if necessary.

**Comment by ritalwar** [comment]
> I think that would be more work in the long run to basically recreate our statsd module to parse out "statsd like" fields.

Agree! let's modify the existing one for this integration unless there's a better solution suggested.
