### ISSUE TITLE
Cisco Meraki Integration - shared secret not working

### ISSUE THREAD

**Issue by spfagetty** [elastic/integrations#9388]
Affects: Cisco Meraki integration
https://docs.elastic.co/en/integrations/cisco_meraki
Version: 1.21.0

The Meraki integration only works when not using a shared secret to authenticate the web-hook.
The issue was already reported in the community (without answer): https://discuss.elastic.co/t/cisco-meraki-webhooks-integration-fails-when-using-shared-secrets/347007

### Description of the issue from the community link

I've been testing the Cisco Meraki webhooks integration lately, and while it works just fine without specifying a shared secret, it stops working immediately once any text is entered in secret_value as described in [https://docs.elastic.co/en/integrations/cisco_meraki#configure-the-cisco-meraki-integration 5](https://docs.elastic.co/en/integrations/cisco_meraki#configure-the-cisco-meraki-integration)

As far as I can tell, this is because Cisco Meraki sends the shared secret as a JSON attribute sharedSecret, as shown in the [test-mx-events.json 1](https://github.com/elastic/integrations/blob/34242b32eaca2fca20535aa861d54c8d3073cc69/packages/cisco_meraki/data_stream/events/_dev/test/pipeline/test-mx-events.json#L6) file included in the integration package:

```
{
    "events": [
        {
            "json": {
                "version": "0.1",
                "sharedSecret": "secret",
                "sentAt": "2021-10-07T08:42:00.926325Z",
[...]
```
http_endpoint.yml.hbs, on the other hand, [looks for the shared secret 2](https://github.com/elastic/integrations/blob/34242b32eaca2fca20535aa861d54c8d3073cc69/packages/cisco_meraki/data_stream/events/agent/stream/http_endpoint.yml.hbs#L15-L18) in a non-existing Authorization header:

```
{{#if secret_value}}
secret.header: Authorization
secret.value: "{{secret_value}}"
{{/if}}
```

**Comment by brynjare** [comment]
I'm a bit late to the party here, but just wanted to show my appreciation for fixing this bug despite me never getting around to creating a ticket for it. Thank you to everyone involved!
