### ISSUE TITLE
Windows Integrations don't render the preserve_original_event tag even when it's toggled on

### ISSUE THREAD

**Issue by devamanv** [elastic/integrations#9425]
## Current behavior
An issue was recently reported in the system integration wherein a user would not see the `event.original` field in the ingested events for Windows(but was working fine for Mac and Linux). It was found that the `preserve_original_event` wasn't being rendered in the Agent config, even when the Preserve Original event toggle was on. This led to the removal of the `event.original` field from the ingested event. 

Read on for additional details.

On windows no event.original:
![image](https://github.com/elastic/integrations/assets/38116245/54695010-4294-4362-895f-45d0b577776c)

On Linux/Mac
![image](https://github.com/elastic/integrations/assets/38116245/52c6d332-4cdc-43b0-8a85-ba0d5d3ec8e5)

The issue was traced to the `event.original` getting deleted by the `.fleet_final_pipeline` [here](https://github.com/elastic/kibana/blob/main/x-pack/plugins/fleet/server/constants/fleet_es_assets.ts#L123-L128)

```
{
    "remove": {
      "description": "Remove event.original unless the preserve_original_event tag is set",
      "field": "event.original",
      "if": "ctx?.tags == null || !(ctx.tags.contains('preserve_original_event'))",
      "ignore_failure": true,
      "ignore_missing": true
    }
}
```

The winlog inputs use the `include_xml: true` config option. So, at the Agent level the original XML is added to the event, as seen in the [code](https://github.com/elastic/beats/blob/9c9ae3568309bb4c715fe1c25834eafd06f0f82a/winlogbeat/eventlog/eventlog.go#L104).  

As a fix, it was suggested to add "preserve_original_event" in the tags section for each of the 3 datastreams (Application, Security, System) in "Collect events from the Windows event log". This brought back the missing `event.original` field. 

![image](https://github.com/elastic/integrations/assets/38116245/a4aa28e2-729d-440d-9426-b1ce7190fa75)

## Expected behavior
The tags should be rendered in the Agent config when the Preserve Original Event toggle is turned on by the user. 

We need to check and revisit all the integrations that rely on include_xml(especially windows based integrations), and need to also set the tag preserve_original_event.

**Comment by leehinman** [comment]
Integrations that need work:

- `hid_bravura_monitor` winlog data_stream is missing the `include_xml` option
- `system` security data_stream is missing the `preserve_original_event` tag
- `system` system data_stream is missing the `preserve_original_event` tag
- `microsoft_sqlserver` audit data_stream is missing the `preserve_original_event` tag
- `winlog` data_stream is missing the `preserve_original_event` tag
- `windows` sysmon_operational data_stream is missing the `preserve_original_event` tag
- `windows` powershell_operational data_stream is missing the `preserve_original_event` tag
- `windows` powershell data_stream is missing the `preserve_original_event` tag
- `windows` forwarded data_stream is missing the `preserve_original_event` tag
- `windows` applocker_exe_and_dll data_stream is missing the `preserve_original_event` tag
- `windows` applocker_packaged_app_deployment data_stream is missing the `preserve_original_event` tag
- `windows` applocker_msi_and_script data_stream is missing the `preserve_original_event` tag
- `windows` applocker_packaged_app_execution data_stream is missing the `preserve_original_event` tag

**Comment by andrewkroh** [comment]
Good find @leehinman.

----

> The issue was traced to the event.original getting deleted by the .fleet_final_pipeline

This is a surprising change in the behavior of Fleet that `preserve_original_event` is necessary for the `event.original` field to pass through the final pipeline. My wish is that changes like this would be announced through the fleet-contributors mailing list.

**Comment by devamanv** [comment]
> system security data_stream is missing the preserve_original_event tag
system system data_stream is missing the preserve_original_event tag
system application data_stream is missing the preserve_original_event tag

These data_streams under the system package have been taken care with this PR.

**Comment by nicpenning** [comment]
👀

**Comment by andrewkroh** [comment]
Relates: https://github.com/elastic/kibana/commit/16b4f1a0cdc18b9909dbf0668d31390de9c64aaa#diff-22ac0479cb88faddaa2c678b27fe8d94db148a5a898930190336fa4ba6d37770R111-R116
