### ISSUE TITLE
[cisco_asa] Improve ECS categorization

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/integrations#9461]
Of the 121 message types currently handled by the integration, only about half or so actually have proper ECS categorization. The rest receive a generic categorization that often does not accurately reflect the nature of the message. Assigning categorization fields is mostly driven by the `event.action` assigned to an event, which then pivots on this value to assign other fields, such as `event.kind`, `event.category`, and `event.type`. There are also cases where `event.outcome` is used to assign fields. As a result, it is not trivial to figure out what values each message type will be assigned. Extending the ASA pipeline further with additional message types (there are over 2300 that ASA can potentially produce) is also difficult given the current structure. One potential improvement that can be explored is using a parameter table with a script processor, which would build up a table of message types to ECS fields. This has been used successfully in other integrations, such as Windows.

While reviewing the ingest pipeline, it was observed that all of the Cisco FTD code is dead code, a leftover of when this pipeline originated from beats and was shared with the FTD module. This code should be removed.

Based on the issues reported in elastic/enhancements#19899

**Comment by taylor-swanson** [comment]
After more investigations, I'm not entirely sure what to do with the FTD-related code in the ASA pipeline. I don't have enough information on how ASA devices work and if it is expected that the ASA integration is supposed to handle FTD logs. It's still possible that the FTD code is left over from the beats days where the pipeline was shared (although the ASA and FTD datasets each had tests for both products).

@jamiehynds or @andrewkroh, do either of you know the history of these integrations/beats module and why ASA and FTD are essentially mirrors of each other? I can understand to some degree why FTD has to handle ASA, as it was stated (somewhere in a git commit) that FTD logs are a superset of ASA logs. I don't understand why ASA needs to handle FTD logs, though.

**Comment by andrewkroh** [comment]
I'm not 100% sure without doing some git archeology, but I think FTD leaks into ASA because they were originally shared in Beats.
