### ISSUE TITLE
[AWS] S3 input consumes significant amount of memory

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#9463]
Filebeat memory usage of their Agent increases continuously until it becomes unresponsive and they restart the Agent, after which this behavior repeats. Based on the hprof data, looks like S3 integration consumes up to 10GB memory, mostly from `GetStates`. Similar behavior in performance testing @zmoog did with aws-s3 input in polling mode: https://github.com/zmoog/public-notes/issues/77

**Comment by andrewkroh** [comment]
How can I help? What do you need me to do? I know the SQS mode of the `aws-s3` input, and have not worked on the S3 listing mode.

If it is possible to switch to SQS mode for the use-case, then I would recommend that. It's a lot simpler when AWS tells the input what to read and it is stateless (so you it scale it horizontally).

**Comment by kaiyan-sheng** [comment]
Hi @andrewkroh thanks for offering to help! We want help to identify if there is a memory leak in the s3 input for s3 polling mode. So far from @zmoog's perf testing, we do see an increase in memory over time but we haven't got a chance to check if this is a memory leak or it's by design.

**Comment by andrewkroh** [comment]
My main question is how was it designed to store state. Does it keep a record of every S3 object (that would be bad) or does it use some techniques to limit state based on time? If its the latter, then what assumptions does it make (like that no older data is expected to be read)?

I will try to spend some time understanding that code.

**Comment by andrewkroh** [comment]
The state tracking in the input is complex. I didn't do any tracing in a debugger or other profiling so there may be some things I'm not understanding at this point.

> Does it keep a record of every S3 object (that would be bad) or does it use some techniques to limit state based on time?

As it is reading pages of the S3 listing it is [storing](https://github.com/elastic/beats/blob/5f1e656e06fc07a0dee6a180bcb381853bd741dd/x-pack/filebeat/input/awss3/s3.go#L220) a state for each S3 object. When it finishing writing all of the S3 objects to ES it exchanges the individual S3 object states for a newest `LastModified` timestamp found on a given S3 prefix.

Then when it lists objects again, it will check if the objects are modified after that stored timestamp. If so it will read them.

As far as memory usage goes, I can see where it might need a lot memory to track all of the S3 object states while it is reading and persisting. The input will be holding one `state` object in a slice and then mapping of state IDs to indices within that slice ([src](https://github.com/elastic/beats/blob/01f9d43c96bdbcb46ed4f1d6e75363906a34112b/x-pack/filebeat/input/awss3/states.go#L39-L43)). Changes to the `states` slice, like [Delete](https://github.com/elastic/beats/blob/01f9d43c96bdbcb46ed4f1d6e75363906a34112b/x-pack/filebeat/input/awss3/states.go#L100-L103), trigger a new map allocation which could be expensive in terms of memory use.

When the state information is persisted to the Filebeat state store it makes a full [copy](https://github.com/elastic/beats/blob/01f9d43c96bdbcb46ed4f1d6e75363906a34112b/x-pack/filebeat/input/awss3/states.go#L254-L255) of the states. This could cause a big malloc too. I think this is what was observed in this comment:

> looks like S3 integration consumes up to 10GB memory, mostly from GetStates

I suspect it makes a copy to avoid needing to hold a lock and block other operations while persisting the state. This might not be an ideal tradeoff to make when there is a lot state to copy.

----------

Another avenue of investigation is to check if any S3 object states are orphaned in the registry. IIUC upon successful completion of a poll loop the registry should be left only with keys like `filebeat::aws-s3::writeCommit::` and no `filebeat::aws-s3::state::` keys ([src](https://github.com/elastic/beats/blob/01f9d43c96bdbcb46ed4f1d6e75363906a34112b/x-pack/filebeat/input/awss3/states.go#L19-L20)). Does anything go wrong if the input is interrupted and has to restart? Orphaned states would lead to an effective memory leak.

**Comment by faec** [comment]
Met with @andrewkroh to hand off context on this one, I'll be picking up the fix as part of my overall AWS cleanup work
