### ISSUE TITLE
[universal profiling agent] Allow configuring `disable-tls` option as an input

### ISSUE THREAD

**Issue by inge4pres** [elastic/integrations#9500]
**Describe the current state**

We have users requesting to run the Universal Profiling host-agent without encrypted connections to the collector.
This would be achieved with the `disable-tls` optiopn as part of the `pf-host-agent` input.

The use case for it is mostly self-contained Kubernetes clusters where the overlay network is used and there is no egress connection outside of the cluster.

At the the inputs list is not containing the option to disable TLS encryption.

**Describe the desired state**

- [x] add a `disable-tls` input in the input template
- [x] add it as a field in the integration to allow users to set it through the Fleet UI or API

**Comment by florianl** [comment]
All relevant code changes were merged and backported.
