### ISSUE TITLE
[Custom AWS Logs] No option to specify decoding or custom settings

### ISSUE THREAD

**Issue by ajoliveira** [elastic/integrations#9509]
Filebeat recently added support for `decoding`settings [docs](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-aws-s3.html#input-aws-s3-decoding), however, there appears to be no way to be able specify these via the Custom AWS Logs integration.

After review with Dev, need a way to add these settings directly or other mechanism to add them as a custom setting that can be passed down to Filebeat ... refs:
- [Template](https://github.com/elastic/integrations/blob/618de99e6a85b44be47bf47e1878bd3b9fa09c0e/packages/aws_logs/data_stream/generic/agent/stream/aws-s3.yml.hbs) (missing variable)
- [Log Input](https://github.com/elastic/integrations/blob/618de99e6a85b44be47bf47e1878bd3b9fa09c0e/packages/log/agent/input/input.yml.hbs#L28) ... has `custom` support
- [Log manifest](https://github.com/elastic/integrations/blob/618de99e6a85b44be47bf47e1878bd3b9fa09c0e/packages/log/manifest.yml#L63-L69)

**Comment by andrewkroh** [comment]
PR: https://github.com/elastic/integrations/pull/9512
