### ISSUE TITLE
[New Integration] Blue Coat ProxySG

### ISSUE THREAD

**Issue by mjwolf** [elastic/integrations#9511]
# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [x] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists, [useful guidelines](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md) to follow
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to: 8.13

### New Package

- [x] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [x] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists

# Notes

Supported log formats are described [here](https://techdocs.broadcom.com/us/en/symantec-security-software/web-and-network-security/edge-swg/7-3/getting-started/page-help-administration/page-help-logging/log-formats/default-formats.html).

The log field definitions are [here](https://techdocs.broadcom.com/us/en/symantec-security-software/web-and-network-security/edge-swg/7-3/getting-started/page-help-administration/page-help-logging/log-formats.html).

**Comment by mjwolf** [comment]
Hi @jamiehynds, just an update on this. I'm still working on developing this integration.  I have a ProxySG system running, and generating some admin messages, but so far I haven't been able to get it working completely properly as a functional proxy. 

With the sample logs you've provided and the admin logs I can generate, I should be able to do most of the work to finish developing the integration. But I would like to get my ProxySG system fully working, so I can do some end-to-end testing before this is released. 

Do you know anyone who could help me get ProxySG fully running and proxying data?

**Comment by jamiehynds** [comment]
Thanks for the update @mjwolf. Not sure who could help get the virtual appliance fully running - @LucaWintergerst maybe?

**Comment by LucaWintergerst** [comment]
I won't be of much help I'm afraid. I haven't done any work with virtual appliances in the past. If you provide more info or logs of what's not working as expected I'm happy to give it a try, but maybe someone can think of others that have more experience in this space?

**Comment by mjwolf** [comment]
## Integration Screenshot

![Image](https://github.com/user-attachments/assets/b5bab44d-12ea-4366-afff-8c88222c22a4)

## Dashboard screenshot

![Image](https://github.com/user-attachments/assets/64b6f83a-17de-43a7-80bb-26b62d389c5d)
