### ISSUE TITLE
Deploy default ILM policy in Elastic Agent package to manage Agent observability data lifecycle

### ISSUE THREAD

**Issue by ravikesarwani** [elastic/integrations#952]
As part of the Elastic Agent package we should install a default ILM policy to cleanup Agent observability data.
Agent observability data includes metrics and logs from Agent and all of it subprocesses (filebeat, metricbeat ...). The ILM policy will ensure that the collected Agent observability data doesn't take up too much space on the production cluster.

The Agent observability data is sent to the same production cluster in 7.x. As part of transition from beats to Agent this data in some use cases will be additional data that will now need to be stored in the production cluster and hence having a default ILM policy is critical.

- Create an ILM policy to store Agent and its subprocesses(filebeat, metricbeat ...) metrics data for 7 days, by default.
- Create an ILM policy to store Agent and its subprocesses(filebeat, metricbeat ...) logs data for 7 days, by default.

The 2 separate ILM policy provides flexibility to the users in terms of controlling different retention for logs and metrics data if they wish to change the defaults based on any compliance or other policy requirements.

The user should be able to change the default ILM policies to store less (say 3 days) or more (say 14 days) data using the stack management UI.

As part of Agent upgrade or reinstall the ILM policies should not be overwritten if the defaults were changed by the user.

cc: @ph @nchaulet

**Comment by jen-huang** [comment]
I went ahead and transferred this to integrations. In Kibana, we already support installing ILMs at the package and data stream levels: https://github.com/elastic/kibana/blob/31660419eafdd8c74c68123745fc699e7ee8cf2e/x-pack/plugins/fleet/server/services/epm/packages/_install_package.ts#L121

But I guess no packages take advantage of this yet! (Based on a cursory search in this repo)

**Comment by mtojek** [comment]
Both elastic-agent and fleet-server don't use any tests to verify if the package works as expected. Do you think you could improve the test coverage, at least partially, in the scope of this feature?

**Comment by ph** [comment]
@mtojek could we add it to the integration test suite?

**Comment by mtojek** [comment]
> @mtojek could we add it to the integration test suite?

I'm not sure if I understand you, what do you mean by the "integration test suite"?

**Comment by ph** [comment]
> Both elastic-agent and fleet-server don't use any tests to verify if the package works as expected. Do you think you could improve the test coverage, at least partially, in the scope of this feature?

Since we have an integrations for both Elastic Agent and Fleet server, could it be possible to add test to verify that it's working correctly from the integration repository?

**Comment by mtojek** [comment]
> @mtojek could we add it to the integration test suite?

Ah, I see now!

Sure, you can define some system tests for both. I think that system tests should be the best option: https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md . There are many packages using them to verify if they're working correctly. It's up to package owners to decide and (if interested) write system tests.

**Comment by ruflin** [comment]
What @ravi-elastic describes here sounds a lot like what we discussed around integration granularity + policy for logs / metrics. @sorantis please have a look at this. So I'm wondering if we should implement something specific to agent logs/metrics or can use the generic solution directly as we are heading this path down anyways.

I would also split up this discussion into two parts:

* Ship default ILM policies for certain data streams / packages / policies / *? 
* What should be the defaults of it.

So far we mostly stayed away from deleting data of our users by default. The exception here is/was the internal stack monitoring. But just today @graphaelli mentioned this too in another context.

**Comment by sorantis** [comment]
I would wait with a generic solution for integration for now since the ES team is working on Rollups being an ILM action, which all our integrations will also need. cc @exekias
