### ISSUE TITLE
Elastic Agent package doesn't contain all possible agent data streams

### ISSUE THREAD

**Issue by jen-huang** [elastic/integrations#953]
In Kibana > Stack Management > Index Management, with just a Fleet Server agent enrolled and running, only the `metrics-elastic_agent.elastic_agent-default` has a specific index template attached to it:

![image](https://user-images.githubusercontent.com/1965714/116300864-3bf5fb80-a754-11eb-831d-fa5899f6c159.png)

The other ones just have the generic logs or metrics index template:

![image](https://user-images.githubusercontent.com/1965714/116300907-4d3f0800-a754-11eb-8d8e-eccee9854c44.png)

This is because the Elastic Agent package only ships `elastic_agent` data stream:
https://github.com/elastic/integrations/tree/d7e83a6aa3b94cb9a4a94c205c0c580ace6a7cee/packages/elastic_agent/data_stream

(also, the `elasticsearch.index_template` setting should be removed as it is invalid)
```diff
title: Elastic Agent
dataset: elastic_agent.elastic_agent
type: metrics
-elasticsearch:
-  index_template:
-    mappings:
-      dynamic: false
```

It should ship all the other data streams too so that Fleet can install index templates properly for all of them.

**Comment by ruflin** [comment]
Started a PR to get this fixed here: https://github.com/elastic/integrations/pull/1298

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/integrations/pull/1298 was merged and @nchaulet did a few follow up fixes.
