### ISSUE TITLE
Add support for Cloudwatch metrics streams

### ISSUE THREAD

**Issue by exekias** [elastic/integrations#956]
Amazon recently announced their new feature to allow cloudwatch metrics to be streamed live to several destinations, including Kinesis Firehose:
https://aws.amazon.com/blogs/aws/cloudwatch-metric-streams-send-aws-metrics-to-partners-and-to-your-apps-in-real-time/

We want to check the feasibility of this approach and potentially add support for it.

**Comment by kaiyan-sheng** [comment]
Testing `/firehose` endpoint can be done with 8.0.0-SNAPSHOT deployment in GCP us-west2 now. Here are the CloudWatch metric streams data ingested into Elasticsearch:
<img width="2559" alt="Screen Shot 2021-11-10 at 8 47 10 AM" src="https://user-images.githubusercontent.com/14081635/141153581-42df72a0-ffb1-4bc8-b002-b4d1d0843551.png">

**Comment by RichiCoder1** [comment]
It looks like support for this was removed from the APM Service. Is it planned to land elsewhere?
