### ISSUE TITLE
Fix affected _ignored fields due to new check in system tests

### ISSUE THREAD

**Issue by narph** [elastic/integrations#9572]
Following  [this PR](https://github.com/elastic/elastic-package/pull/1738) which adds a check whether any indexed docs have an _ignored field - this would indicate a mapping problem:

Example output:

Error: error running package system tests: could not complete test run: found _ignored fields in data stream logs-cel.cel-ep

Also relevant https://github.com/elastic/elastic-package/issues/1276

The following integration tests are failing with affected fields:

* ti_threatconnect: `threat_connect.indicator.tags.data.description ` (cc @elastic/security-service-integrations )
* tenable_io: `tenable_io.vulnerability.plugin.description vulnerability.description` (cc @elastic/security-service-integrations )
* tanium: `tanium.threat_response.other_parameters.log_details.payload`, `tanium.threat_response.other_parameters.original` (cc @elastic/security-service-integrations )
* panw: `panw.panos.after_change_detail` (cc @elastic/sec-deployment-and-devices )
* m365_defender: `m365_defender.incident.alert.recommended_actions` (cc @elastic/security-service-integrations )
* fortinet_fortimanager: `fortimanager.log.changes` (cc @elastic/sec-deployment-and-devices)
* crowdstrike: `crowdstrike.ConfigStateData`, `crowdstrike.FeatureVector`, `crowdstrike.OSVersionFileData`, `process.command_line` (cc @elastic/security-service-integrations )

Steps:
- run the system tests to analyze the  _ignored data and why is failing to index
- fix potential issues with the fields affected or ignore these usecases

**Comment by flash1293** [comment]
@ShourieG what about setting all of these fields to `index: false`? I'm not sure I'm seeing the value of indexing these fields if they are often ignored. This isn't tied to the PR of muting these errors.

**Comment by ShourieG** [comment]
> @ShourieG what about setting all of these fields to `index: false`? I'm not sure I'm seeing the value of indexing these fields if they are often ignored. This isn't tied to the PR of muting these errors.

Will have to discuss this with the team and will take the call accordingly, any thought @andrewkroh ?

**Comment by andrewkroh** [comment]
If the fields are chronically unindexable due to length then we should consider changing them to different more usable data type. Or if there is no search use-case for making the data indexed then turn off index entirely. [Wildcard](https://www.elastic.co/guide/en/elasticsearch/reference/8.13/keyword.html#wildcard-field-type) or `match_only_text` would likely be best types to consider based on use-case.
