### ISSUE TITLE
Create a "best practices" style guide for package authors

### ISSUE THREAD

**Issue by hbharding** [elastic/integrations#958]
To ensure consistency in style and content between Integration packages, it would be beneficial to our authors if they had some documentation to follow. While packages will vary in content, they should look, feel, and generally read the same. There are some intricacies in the design that might not be obvious to our authors that i'd like to call out. Some examples:

- READMEs should begin with an H1 `#`. Top level headings create sections that are added to the navigation.
- READMEs should follow a similar structure. For example, `# About` --> `# Compatability` --> `...` --> `# Questions and Contributions`
- Try not to use more than 3 heading levels. We support 4 styles. H5 and H6 look the same as H4.
- When using code snippets, specify a language after the three ticks to enable syntax highlighting.
- Screenshots should be taken at X*Y resolution, etc. 
- Inline images should include `title` and  `alt` text. The `title` gets rendered as a caption below the image, and `alt` is used by screen readers.

The list goes on... Where should this 'guide' live? a Google doc? a CONTRIBUTING.md file in our codebase?

I'm happy to take lead on this for the design related bits, but I also thought this may be an appropriate place for @Titch990 to weigh in. I'm not sure if we have existing writing guides we can follow, or if we should make one specific to Integration package READMEs that is included in this guide. Regardless, I'd love to work with you and get your input on this effort :)

It would be helpful to have 1-3 examples of real content to work from (I believe @ruflin has these).

**Comment by jen-huang** [comment]
I'm transferring this to integrations repo as it's more relevant here. But, this issue is pretty old so @elastic/integrations, I'll leave it to you to triage if this is something we still need.
