### ISSUE TITLE
[juniper_junos.log] field "log.file.device_id" is undefined

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#9582]
There is a CI test failure under 8.13. 

`system test: logfile in juniper_junos.log:`

`one or more errors found in documents stored in logs-juniper_junos.log-ep data stream: [0] field "log.file.device_id" is undefined
[1] field "log.file.inode" is undefined`

https://buildkite.com/elastic/integrations/builds/10363
https://buildkite.com/elastic/integrations/builds/10563

**Comment by andrewkroh** [comment]
Same problem in 


`system test: logfile in juniper_netscreen.log`

```
one or more errors found in documents stored in logs-juniper_netscreen.log-ep data stream: [0] field "log.file.device_id" is undefined
[1] field "log.file.inode" is undefined
```

**Comment by andrewkroh** [comment]
Relates to 

- https://github.com/elastic/integrations/issues/7687
- https://github.com/elastic/elastic-agent/issues/3934#issuecomment-1876220456

**Comment by pkoutsovasilis** [comment]
I have prepared the referenced PR to address this issue @andrewkroh , but it was brought to my attention by @taylor-swanson (ty ty) that these two integration are basically deprecated. So I think this question is for you @jamiehynds, should we remove completely these two integration or let the fixes go into main and postpone their removal?

**Comment by andrewkroh** [comment]
I think we should go ahead and merge those small PRs to fix CI. And keep this open to reach a decision on whether to delete or not.

**Comment by pkoutsovasilis** [comment]
@andrewkroh both PRs got merged so these two should come up green now 🙂

**Comment by pkoutsovasilis** [comment]
this is fixed by these two https://github.com/elastic/integrations/pull/9657 and https://github.com/elastic/integrations/pull/9658
