### ISSUE TITLE
[zeek.http] Error - field [url.domain] already exists

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#9602]
zeek.http occasional will emit events with

> error.message: field [url.domain] already exists

This error was experienced on a 7.17 stack that was running version 1.8.0 of the Zeek integration. So it is possible that the error has already been fixed in the latest version.

`{"ts":1713186227.890412,"uid":"CTgK9213q9Lpa7PK5f","id.orig_h":"10.100.11.223","id.orig_p":55524,"id.resp_h":"192.124.249.41","id.resp_p":80,"trans_depth":1,"method":"GET","host":"ocsp.godaddy.com","uri":"//MEAwPjA8MDowODAHBgUrDgMCGgQUHSNvjgZLlx/d36EVI+Gu5QK+KxsEFDqahQcQZyi27/a9BUFuIMGU2g/eAgEH","version":"1.1","user_agent":"com.apple.trustd/3.0","request_body_len":0,"response_body_len":2061,"status_code":200,"status_msg":"OK","tags":[],"resp_fuids":["F8XoFe1ZpACrfBpCNk"],"resp_mime_types":["application/ocsp-response"]}`

**Comment by pkoutsovasilis** [comment]
@andrewkroh I run the elastic-package system test against the latest integration version and with stack @ v8.13.0; none of the elastic-package, elastic-agent and elasticsearch complained. However, I can see `url.domain` being defined in the ecs fields of zeek http datastream. Should I look elsewhere?
