### ISSUE TITLE
[Okta] Moving to OAuth 2.0

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#9608]
Our current Okta integration relied on a static SSWS token, which typically inherits the permission of a superuser/admin account, creating a security risk. We shouldn't settle for a single bearer token being the only credential required.

Okta now recommends using OAuth 2.0, and what they call an Okta Service Integration. You can view information on tokens vs OAuth in Okta's blog here: https://developer.okta.com/blog/2023/09/25/oauth-api-tokens

Can we update our integration to become an [Okta API Service integration](https://developer.okta.com/docs/guides/oin-api-service-overview/) - developer guide [here](https://developer.okta.com/docs/guides/build-api-integration/main/).

**Comment by ShourieG** [comment]
@jamiehynds @narph, Didn't we already do this a while back, I remember adding OAuth2 support for Okta system datastream last year in this PR - https://github.com/elastic/integrations/pull/7542. We still have support for the static token/api key but we also support OAuth2.

**Comment by ShourieG** [comment]
@narph, @efd6, I went through all the Okta documentation and from the current integration OAuth2 support we are fine, I think want we actually want here is having Elastic be a part of their new Service Integrations Platform via which there is an easier automation established. As you can see in the image, If I click we Datadog and and grant it access, a service integration is instantly created in the backend that allows seamless data flow between Okta and Datadog without the user having to jump all over and create JWTs/PEM keys etc.

<img width="1384" alt="Screenshot 2024-05-06 at 4 40 47 PM" src="https://github.com/elastic/integrations/assets/105607378/163f4060-b79e-4125-828c-1084b8aaaadb">

@jamiehynds, Are our assumptions correct here ?

**Comment by jamiehynds** [comment]
Sorry @ShourieG - you're right, I forgot we added Oauth2 some time ago but agree the Okta Integration Network (OIN) workflow is a cleaner and it's also Okta's recommended approach. How would the flow look for us today with an OIN integration, given that agent has to sit somewhere between us an Okta. Could be a great test for agentless, i.e. how the UX looks between an OIN integration and agentless on our side.

**Comment by efd6** [comment]
Available here: https://www.okta.com/integrations/elastic-agent/
