### ISSUE TITLE
[Cisco Duo] Integration Updates

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#9609]
Our Cisco Duo integration was developed some time ago and now relies on 'legacy' API's. The integration needs to be reviewed and updated to ensure we're inline with the latest updates from Cisco. 

- V2 API docs are available [here](https://duo.com/docs/adminapi#logs) and we need to ensure our integration supports the v2 API
- Trust Monitor events are not currently supported, and need to be added (docs [here](https://duo.com/docs/adminapi#trust-monitor))
- Dashboards can be reviewed to ensure relevance 
- Docs need to be reviewed to ensure accuracy on steps to follow within the Duo UI

**Comment by chemamartinez** [comment]
Expanding the information for this issue:

### Current data stream

Status of current data streams and the need to update to v2 API:

- **Admin**: there is no v2 of the API yet for this endpoint
- **Auth**: already using the v2 of the API, no need of update for it
- **Offline Enrollment**: there is no v2 of the API yet for this endpoint
- **Summary**: there is no v2 of the API yet for this endpoint
- **Telephony**: currently uses v1, and v2 is available so we need to update this data stream

To access to v2 endpoints, which are in Public Preview phase, it may require a particular subscription or reaching the support team: https://help.duo.com/s/article/6720?language=en_US

From https://duo.com/docs/adminapi#about-the-admin-api:
> We have started implementing v2 handlers for endpoints. In these cases, the API v1 handler remains supported, but will be limited or deprecated in the future. We encourage use of the v2 endpoints where available and recommend migrating existing API implementations to the v2 handlers.

It means that we would need to keep an eye on further updates in the future for endpoints that don't have API V2 available yet.


### Support new endpoints

There are two API endpoints that we don't support yet.

- [**Activity logs**](https://duo.com/docs/adminapi#activity-logs)
- [**Trust Monitor**](https://duo.com/docs/adminapi#trust-monitor)

I am opening subtask issues for both of them.

### Dashboards and docs

Dashboards require a review and probably a small rework, with the following tasks:
- Update some visualisations and maps that are not using Lens.
- Add dashboards for new data streams.

In addition, documentation needs an update to include more information about current available data streams, how to collect data for them, and probably more detailed steps to go through the Duo UI.

**Comment by chemamartinez** [comment]
With the addition of three new data streams:
- Telephony v2
- Trust Monitor
- Activity

I wonder if this could be a good opportunity to also migrate from HTTPJSON to CEL for the existing data streams that already use the API v2 version, in this case just the Auth data stream, as well as for the new ones. V2 provides new querying capabilities that are not being used with the current implementation, as the pagination logic.

On the other hand, I would not migrate to CEL those data streams that still rely on the V1 API, as their logic is quite simple and we expect them to be migrated to V2 in the future, so we would have to make a double effort here.

cc: @andrewkroh @jamiehynds I would like to know your opinion on this.

**Comment by andrewkroh** [comment]
Definitely use CEL for the new data streams.

You can migrate the the `auth` data stream if you desire, but don't break the upgrade process for existing users. IIUC as long as you are not renaming existing config options for the auth data stream there won't be any upgrade issues. But do manually test upgrading. The cursor state will be lost, but we are mitigating duplicates with a fingerprint in auth (it's not a 100% guarantee of no duplicates through).

Lastly ensure that all new datasets are disabled by default to avoid breaking users during upgrade (https://github.com/elastic/kibana/issues/190790).
