### ISSUE TITLE
[Docker] Flaky test - field "docker.container.labels.name.text" is undefined 

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#9624]
Builds on the main branch under v8.14.0 are failing because of these errors from the Docker integration.

Owner: @elastic/obs-cloudnative-monitoring

```
one or more errors found in documents stored in metrics-docker.diskio-ep data stream: [0] field "docker.container.labels.name.text" is undefined

one or more errors found in documents stored in metrics-docker.healthcheck-ep data stream: [0] field "docker.container.labels.name.text" is undefined

one or more errors found in documents stored in metrics-docker.memory-ep data stream: [0] field "docker.container.labels.name.text" is undefined

one or more errors found in documents stored in metrics-docker.container-ep data stream: [0] field "docker.container.labels.name.text" is undefined

one or more errors found in documents stored in metrics-docker.cpu-ep data stream: [0] field "docker.container.labels.name.text" is undefined

one or more errors found in documents stored in metrics-docker.image-ep data stream: [0] field "docker.image.labels.name.text" is undefined

one or more errors found in documents stored in metrics-docker.network-ep data stream: [0] field "docker.container.labels.name.text" is undefined
```

https://buildkite.com/elastic/integrations/builds/10450

**Comment by MichaelKatsoulis** [comment]
This is strange. The fields are defined in the data_streams:
https://github.com/elastic/integrations/blob/cf070cc0450d3b9533310241bea547f33a0da8e0/packages/docker/data_stream/diskio/fields/fields.yml#L1
https://github.com/elastic/integrations/blob/cf070cc0450d3b9533310241bea547f33a0da8e0/packages/docker/data_stream/healthcheck/fields/fields.yml#L1
https://github.com/elastic/integrations/blob/cf070cc0450d3b9533310241bea547f33a0da8e0/packages/docker/data_stream/memory/fields/fields.yml#L1
They have been defined like this forever.  These are just labels added by the `add_docker_metadata` processor.

**Comment by MichaelKatsoulis** [comment]
@elastic/ecosystem do you know what could cause these errors? We still use `format_version: 1.0.0` in the docker package https://github.com/elastic/integrations/blob/9cb02c73c4d16b0b8ae07a81e98c418771746fe9/packages/docker/manifest.yml#L17

Those fields are declared as:
```
- name: docker.container.labels.*
  type: object
  release: ga
  description: |
    Container labels
```

**Comment by jsoriano** [comment]
> Those fields are declared as:
> 
> ```
> - name: docker.container.labels.*
>   type: object
>   release: ga
>   description: |
>     Container labels
> ```

We actually consider this as undefined, because it doesn't generate an actual mapping. This is only generating an ambiguous mapping:
```
          ...
          "docker": {
            "properties": {
              "container": {
                "properties": {
                  ...
                  "labels": {
                    "dynamic": true,
                    "type": "object"
                  },
                  ...
```
To avoid these ambiguities we are more strict on these kind of definitions in package spec v2 and v3.


Since 8.13, the `ecs@mappings` is included in all integrations, so probably [this mapping](https://github.com/elastic/elasticsearch/blob/eb6af0e6b549d0810d8b89791556bc791b766652/x-pack/plugin/core/template-resources/src/main/resources/ecs%40mappings.json#L211) is being applied to these fields:
```
        {
          "all_strings_to_keywords": {
            "mapping": {
              "ignore_above": 1024,
              "type": "keyword"
            },
            "match_mapping_type": "string"
          }
        }
```

Not sure though if this is enough to generate the `.text` multifields.

**Comment by mrodm** [comment]
I've tried to update the definition of that field in one of the Data Streams adding `object_type` and `object_type_mapping_type` and it worked successfully.

The field definition that I set is like this:
```yaml
- name: docker.container.labels
  type: object
  object_type: keyword
  object_type_mapping_type: "*"
  description: |
    Container labels
```

One note about that this is that all the labels under `docker.container.labels` will be set as `keyword`.

Would that be valid for this package ? @MichaelKatsoulis cc @jsoriano

It would be also good to try to update this package to one of the latest versions of the Package spec (`format_version` field). Currently, updating the Spec version would report some errors mainly related to the above field definitions.

**Comment by mrodm** [comment]
Probably, this is the mapping adding that `.text` (from the `ecs@mappings` component template):

```json
"ecs_path_match_keyword_and_match_only_text": {
        "path_match": [
          "*.title",
          "*.executable",
          "*.name",
          "*.working_directory",
          "*.full_name",
          "*file.path",
          "*file.target_path",
          "*os.full",
          "email.subject",
          "vulnerability.description",
          "user_agent.original"
        ],
        "mapping": {
          "fields": {
            "text": {
              "type": "match_only_text"
            }
          },
          "type": "keyword"
        },
        "unmatch_mapping_type": "object"
      }
    }
```

**Comment by mrodm** [comment]
Running again some tests updating just the data stream `container` with a fresh Elastic stack with version `8.14.0-SNAPSHOT`, and it looks like this could work (sorry for the noise :pray:):
```yaml
- name: docker.container.labels.*
  type: object
  object_type: keyword
  object_type_mapping_type: "*"
  release: ga
  description: |
    Container labels
```

I updated the field definition in `container` data stream and I ran these commands:

```shell
elastic-package stack down -v
elastic-package stack up -v -d --version 8.14.0-SNAPSHOT
elastic-package test system -v --data-streams container
```

**Comment by MichaelKatsoulis** [comment]
Thanks @mrodm ! This configurations was our initial thought as well. We will also test this with latest stack version.
