### ISSUE TITLE
[ibmmq.errorlog] Flaky test - Provided Grok expressions do not match field value: []

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#9653]
```
system test: logfile (variant: v9.2.4.0-r1-amd64) in ibmmq.errorlog

one or more errors found in documents stored in logs-ibmmq.errorlog-ep data stream: [0] found error.message in event: Provided Grok expressions do not match field value: []
```

https://buildkite.com/elastic/integrations/builds/10593

**Comment by andrewkroh** [comment]
This is the only failure remaining that prevents a green build under 8.14.

https://buildkite.com/elastic/integrations/builds/11081

<img width="1153" alt="Screenshot 2024-05-03 at 13 30 00" src="https://github.com/elastic/integrations/assets/4565752/3c38a016-033c-4a2f-b13e-a5bd31cfe74a">

**Comment by aliabbas-elastic** [comment]
@andrewkroh I figured out the reason to be the `message` field being empty in some cases which is causing the grok problem. Probably a `drop` processor would do the job. I'll raise the fix soon. Thanks for raising this!

**Comment by andrewkroh** [comment]
The test is passing. Thanks.
