### ISSUE TITLE
[TI_AbuseCH] Compilation error due to '.?' in cursor for IOC expiration

### ISSUE THREAD

**Issue by kubinks** [elastic/integrations#9708]
Since release with IOC expiration, AbuseCH integration compilation fails and leads to crashes. I'm not familiar with templating and syntax here, but it seems like question mark is excessive:

`failed to check program: failed compilation: ERROR: <input>:1:69: unsupported syntax '.?' | request("POST", state.url, '{ "query": "get_iocs", "days": ' + state.?cursor.days.orValue(state.initial_interval) + ' }' | ....................................................................^ accessing config`

@kcreddy 
MR that introduced the issue:
https://github.com/elastic/integrations/pull/7793

Lines that introduced the issue:
https://github.com/kcreddy/integrations/commit/c5db5d1ca04c8c5a2b993e1fe23c630ba18e70d7#diff-16c5df86b7d81de236c8a0f0e4fb308af1e59a5c407f48869ec265df9e2e2d4bR22
```[tasklist]
### Tasks
```

**Comment by efd6** [comment]
@kubinks I am unable to replicate this and would not expect this error; the syntax is valid and required. However, support for optional types was added in v8.12.0, and I would expect — and have replicated with v8.11.4[1] — this exact error if the integration is attempted to be used on a set-up with a pre-v8.12.0 version of filebeat. The manifest for the integration _does_ require v8.12.0 for `kibana.version`, but it is possible to have a lagging version of agent components such as filebeat even though the kibana version is at v8.12.0.

Please check that you have a version of filebeat installed that is at least v8.12.0.

[1]
> ```
> Unit state changed cel-default-cel-ti_abusech-8f8ad8ae-fa6b-4f9f-b0d0-cfe2a4f3b863 (STARTING->FAILED): failed to check program: failed compilation: ERROR: <input>:1:69: unsupported syntax '.?'
>  | request("POST", state.url, '{ "query": "get_iocs", "days": ' + state.?cursor.days.orValue(state.initial_interval) + ' }' 
>  | ....................................................................^ accessing config
> ```

**Comment by kubinks** [comment]
@efd6 Thanks, you're right - we've updated our stack and kibana to 8.13.2, but elastic agents were still on 8.11. Upgrade indeed helped
