### ISSUE TITLE
Create FireEye Network Security (NX) appliances package

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#975]
Create a package for FireEye Network Security (NX) appliances. There is a contribution to Beats in https://github.com/elastic/beats/pull/21366 that we can use as a starting point.

- https://www.fireeye.com/content/dam/fireeye-www/products/pdfs/pf/web/fireeye-network-threat-prevention-platform.pdf
- https://aws.amazon.com/marketplace/pp/B07X38BMTK?ref_=srh_res_product_title

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by jamiehynds** [comment]
Closing, as a FireEye NX package was released some time ago - https://docs.elastic.co/integrations/fireeye
