### ISSUE TITLE
@custom component template missing after installing atlassian jira integration

### ISSUE THREAD

**Issue by Alphayeeeet** [elastic/integrations#9833]
For confirmed bugs, please report:
- Version: 8.13.3
- Operating System: RHEL 8
- Steps to Reproduce: Install jira integration. Index template is referencing @custom component template, but this hasn't been installed.

Impact: It prevents our ILM automation from working, as we automatically clone the index templates based on data-stream namespaces.

![image](https://github.com/elastic/elastic-agent/assets/52979715/650d6706-cb1e-471b-bc63-2b77f2eb250f)
![image](https://github.com/elastic/elastic-agent/assets/52979715/c5241a49-73a7-438b-9e2e-03e50cafff2f)

**Comment by efd6** [comment]
This is not a Jira integration issue. All the integrations that I look at have the same behaviour.

**Comment by Alphayeeeet** [comment]
@efd6 Could you then please label this issue to the respective team which is responsible for base implementation?

**Comment by Alphayeeeet** [comment]
Apparently this was removed by #175469

**Comment by Alphayeeeet** [comment]
I will change our automation to automatically create the missing @custom component template accordingly. But actually I might consider this as a notable change, therefore would have adjusted the release notes as so.
