### ISSUE TITLE
[CEF Integration] Have a ignore failure option for the community ID processor in the integration pipeline #21582

### ISSUE THREAD

**Issue by greicefaustino** [elastic/integrations#9835]
**Problem**
When a document come through the logs-cef.log-2.16.2 ingest pipeline and fail on the Community ID processor, this causes the rest of the processors in the pipeline to be skipped, and therefore any @Custom pipeline is also skipped. As a consequence, the documents are not properly rerouted to the datastream. 

**Request**
Have the ignore failure option to be set to true or false for the community ID processor in the integration pipeline and do not overwrite this option during upgrades.

**Comment by andrewkroh** [comment]
Package cef - 2.17.1 containing this change is available at https://epr.elastic.co/search?package=cef.
