### ISSUE TITLE
[sql_input] Flaky test - cannot open connection: testing connection

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#9840]
The previous 3 builds under Elastic stack 8.14 have had sql_input system test failures.

```
system test: mysql in sql_input.

one or more errors found in documents stored in metrics-sql.sql-ep data stream: [0] found error.message in event: cannot open connection: testing connection: dial tcp 172.18.0.7:3306: connect: connection refused
```

https://buildkite.com/elastic/integrations/builds/11328
https://buildkite.com/elastic/integrations/builds/11351
https://buildkite.com/elastic/integrations/builds/11352

Code owner: @elastic/obs-infraobs-integrations

**Comment by ishleenk17** [comment]
Thanks Andrew for reporting it. 
Looks like health check is not present in the Integration. The service is not reachable.
The team is taking a look at it. 

@mrodm @jsoriano:  Is there a way of notifying the teams about the Integration nightly runs failure?

**Comment by jsoriano** [comment]
> @mrodm @jsoriano: Is there a way of notifying the teams about the Integration nightly runs failure?

WIP in https://github.com/elastic/integrations/issues/6071
