### ISSUE TITLE
[ThreatQuotient] Enable configurable page_size

### ISSUE THREAD

**Issue by adrianchen-es** [elastic/integrations#9921]
## Description

Update the ThreatQuotient module to allow user-configurable page_size

### Background

A customer requests an update that allows users to configure the `url.param.limit` via a `page_size` variable. 
A non-configurable hardcoded limit of 100 may be insufficient.

**Comment by efd6** [comment]
@adrianchen-es Confirming that #9922 closes this?

**Comment by adrianchen-es** [comment]
@efd6 Yes, it does
