### ISSUE TITLE
[Cisco ASA] Grok patterns do not account for group names with spaces

### ISSUE THREAD

**Issue by swg0101** [elastic/integrations#9929]
Currently, Grok patterns in the `logs-cisco_asa.log-2.34.0` pipeline start with:
`Group <%{NOTSPACE:source.user.group.name}>`
which only matches group names without spaces. When a group name does include spaces, the Grok patterns fail and cause the pipeline to fail.

Here are some examples of log entries with their matching tags (ASA event IDs):
```
Processor conditional with tag parse_716039 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access - ISE> User <*****> IP <125.51.103.106> Authentication: rejected, Session Type: WebVPN.]

Processor conditional with tag parse_722022-722023 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <jeffn292> IP <213.21.51.192> UDP SVC connection established without compression]

Processor conditional with tag parse_722033 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <jeffn292> IP <213.21.51.192> First UDP SVC connection established for SVC session.]

Processor conditional with tag parse_722051 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <jeffn292> IP <213.21.51.192> IPv4 Address <10.7.11.181> IPv6 address <::> assigned to session]

Processor conditional with tag parse_722022-722023 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <jeffn292> IP <213.21.51.192> TCP SVC connection established without compression]

Processor conditional with tag parse_722034 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <jeffn292> IP <213.21.51.192> New TCP SVC connection, no existing connection.]

Processor conditional with tag parse_722051 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <doni199> IP <132.21.15.55> IPv4 Address <10.1.11.92> IPv6 address <::> assigned to session]

Processor conditional with tag parse_722037 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <doni199> IP <132.21.15.55> SVC closing connection: Transport closing.]

Processor conditional with tag parse_722011 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <doni199> IP <132.21.15.55> SVC Message: 17/WARNING: Reconnecting the VPN tunnel..]

Processor conditional with tag parse_113029-113039 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <djoem> IP <12.15.99.10> AnyConnect parent session started.]

Processor conditional with tag parse_722037 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <owmens> IP <76.156.12.10> SVC closing connection: Max time exceeded.]

Processor conditional with tag parse_722022-722023 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <owmens> IP <76.156.12.10> TCP SVC connection terminated without compression]

Processor conditional with tag parse_722022-722023 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <owmens> IP <76.156.12.10> UDP SVC connection terminated without compression]

Processor conditional with tag parse_722037 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <skzhu> IP <156.103.160.10> SVC closing connection: User Requested.]

Processor conditional with tag parse_722037 in pipeline logs-cisco_asa.log-2.34.0 failed with message: Provided Grok expressions do not match field value: [Group <Remote Access Grp Policy ISE> User <jwatts> IP <174.56.3.60> SVC closing connection: DPD failure.]
```

It may make sense to change `NOTSPACE` to `DATA` for the group name variable to match the lines properly.

Please advise.

**Comment by jamiehynds** [comment]
@taylor-swanson - would you mind taking a look at these parsing errors and assess if they can be addressed via some tweaks to our ASA pipeline? I discussed with @swg0101 on Slack and advised to raise an issue.

**Comment by taylor-swanson** [comment]
@swg0101, is it just group names or would user names fall under this as well?

Would it also be safe to assume groups with spaces would only appear with angle brackets? We have patterns in the grok processors that also handle logs without angle brackets (`Group <TheGroupName>` vs `Group TheGroupName`). Without the angle brackets (or perhaps quotes), it would be difficult to write a pattern that extracted values reliably. (For example, if the group name contained the word `User`).

**Comment by swg0101** [comment]
@taylor-swanson - While usernames typically don't have spaces, I don't think there are any technical limitations requiring them not to have spaces. It probably would be wise to ingest that blob as a whole between the brackets to ensure there are no pipeline errors.

As far as the group names without brackets - I also noticed that in the Grok patterns as well, but I have not seen any log entries in real life where the group names and the usernames are not both bracketed at the same time. If you search for any of the log messages above, I couldn't find an example online of a log entry that contains either an unbracketed group or username.

That being said -- with the Grok pattern `Group %{GREEDYDATA:source.user.group.name} User %{GREEDYDATA:source.user.name} IP %{IP:source.address} SVC closing connection: %{GREEDYDATA:event.reason}\.`
against `Group Remote Access Grp Policy ISE User User doni199 User IP 132.21.15.55 SVC closing connection: Transport closing.`

The expression still matched with the appropriate fields matched, although things may get complicated if the username also starts with `User`. Perhaps modify the ones without brackets to support spaces and leave the other grok pattern intact. This probably would cover the majority of people generating these logs.

**Comment by taylor-swanson** [comment]
Thanks, @swg0101

I would agree, there shouldn't be any issue with switching user names to `DATA` as well. I'll keep the changes to patterns that use brackets. I was able to break the parser (not an error, it just extracted incorrectly) on the non-brackets cases, so it can certainly happen.

**Comment by swg0101** [comment]
Awesome, thank you.
