### ISSUE TITLE
[Elastic Agent] Broken dashboard

### ISSUE THREAD

**Issue by mostlyjason** [elastic/integrations#993]
The default dashboard shown for Elastic Agent is broken. The visualizations seem to be missing the time field. 

![image](https://user-images.githubusercontent.com/6370704/118300891-6d8af880-b4b0-11eb-8dff-1aa979b3a619.png)

Adding the time field fixes it
![image](https://user-images.githubusercontent.com/6370704/118300973-8693a980-b4b0-11eb-8c97-38f4fc1795c6.png)

**Comment by hop-dev** [comment]
I am having a bit of trouble reproducing this, so far I have tried:

- local dev setup (docker) with latest integrations
- Cloud 7.14 latest
- Cloud 7.15 latest

And the dashboard appears to be working fine. Any pointers @mostlyjason or additional steps to reproduce?

**Comment by mostlyjason** [comment]
This appears to be fixed in 7.13.4
