### ISSUE TITLE
[Azure] [OpenAI] Malformed FunctionAppLogs documents found in azure_openai.logs dataset

### ISSUE THREAD

**Issue by lucian-ioan** [elastic/integrations#9964]
In my analysis of Azure OpenAI logs, **21/91 documents** contain malformed JSONs, breaking the processing of the fields and displaying the same `error.message`: 

![Error Message](https://github.com/elastic/integrations/assets/59661554/6624427e-1c89-43f5-811c-1ffc9a41cf71)

The documents appear unrelated to Azure OpenAI (from `FunctionAppLogs` instead):
<img width="350" alt="document" src="https://github.com/elastic/integrations/assets/59661554/643c378c-f8d1-4066-b11e-c2249c271960">

The Azure OpenAI metrics contain **1153 documents**, all without the `error.message` field populated. This is likely because this issue is eventhub-specific and metrics use Azure Monitor.

<details>
  <summary>Elasticsearch Query</summary>

```json
GET ${exampleVariable1} // _search
{
  "size": 0,
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "data_stream.dataset": "azure.open_ai"
          }
        },
        {
          "term": {
            "data_stream.dataset": "azure_openai.logs"
          }
        }
      ]
    }
  },
  "aggs": {
    "datasets": {
      "terms": {
        "field": "data_stream.dataset",
        "size": 2
      },
      "aggs": {
        "error_message_exists": {
          "filter": {
            "exists": {
              "field": "error.message"
            }
          }
        },
        "error_message_not_exists": {
          "filter": {
            "bool": {
              "must_not": {
                "exists": {
                  "field": "error.message"
                }
              }
            }
          }
        }
      }
    }
  }
}
```
</details>

## Possible fix

This issue can likely be fixed by enabling [sanitization](https://github.com/elastic/beats/pull/34874) in the logs data stream. 

Right now it's missing from the `manifest.yml` file. I will test it and open a PR to add and enable it by default.

## Question

Why do the malformed JSONs that break the processing default to `data_stream.dataset: azure_openai.logs` in this case?

**Comment by muthu-mps** [comment]
@lucian-ioan - This logs are from the Azure function app. These logs are also getting pushed to the `event-hub` earlier for testing. I don't think we need to sanitise these unstructured logs which is not relevant to OpenAI service.

**Comment by lucian-ioan** [comment]
@muthu-mps the issue is the `event.dataset` and `data_stream.type `are the exact same as for normal OpenAI logs in these Function App Logs:

<img width="498" alt="dataset" src="https://github.com/elastic/integrations/assets/59661554/279dca67-dfe2-4a60-9c45-5df467642188">

**Comment by muthu-mps** [comment]
> @muthu-mps the issue is the `event.dataset` and `data_stream.type` are the exact same as for normal OpenAI logs in these Function App Logs:
> 
> <img alt="dataset" width="498" src="https://private-user-images.githubusercontent.com/59661554/333506165-279dca67-dfe2-4a60-9c45-5df467642188.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDQ3OTcsIm5iZiI6MTcxNjgwNDQ5NywicGF0aCI6Ii81OTY2MTU1NC8zMzM1MDYxNjUtMjc5ZGNhNjctZGZlMi00YTYwLTljNDUtNWRmNDY3NjQyMTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEwMDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0OGFkYmM0MzFjNDk1ZDQ2MWYxOGIzNGY4Y2JmM2MyNmJiNjFhZGViNDk1OGExY2Y3OTU4MzMxN2Y5ZDdjYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G5WBUkl2b6AgsihwHsusWD59fyBjHaUziU9dZwbYNto">

Seems like these logs are not getting dropped in the pipeline because of the errors. We can enable sanitisation and verify there is no malformed error logs.
