### ISSUE TITLE
[Proofpoint TAP] Empty array response should not generate an event

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#9965]
Each minute when there are no new events available, documents like this are indexed in Elasticsearch.

These are `event.original` values:

```json
{"messagesDelivered:":[],"queryEndTime":"2023-05-23T19:01:34Z"}
{"messagesDelivered:":[],"queryEndTime":"2023-05-23T19:02:34Z"}
```

This was observed with the other data streams in the integration too.

### References

- https://help.proofpoint.com/Threat_Insight_Dashboard/API_Documentation/SIEM_API

**Comment by andrewkroh** [comment]
FWIW this integration has a fairly short maximum look-back windows and uses deduplication prevention, so IMO it is a candidate for CEL conversion because the risk of mass duplication on update is low.

**Comment by andrewkroh** [comment]
#9974 might be fixing this. @chrisberkhout, can you confirm?

**Comment by chrisberkhout** [comment]
> #9974 might be fixing this. @chrisberkhout, can you confirm?

Correct
