### ISSUE TITLE
Infoblox NIOS - REFUSED logs missing ecs fields

### ISSUE THREAD

**Issue by willemri** [elastic/integrations#9989]
I'm looking into the Infoblox logs; and noticed when we have REFUSED logs, the ECS mapping isn't always complete.
i would expect some extra ecs fields (which we are missing now)

##Example of log line:
"Unable to add forward map from exampleHostName.exampledomain.subdomain to 10.1.1.1 by server 127.0.0.1#53: REFUSED"

event.action: REFUSED
related.hosts: exampleHostName.exampledomain.subdomain

##Example of log line:
"Reverse map update for 10.1.1.1 abandoned because of non-retryable failure: REFUSED"

event.action: REFUSED

**Comment by efd6** [comment]
@willemri Can you provide the complete syslog lines for these messages so that we can test the pipeline in context?

**Comment by willemri** [comment]
[131May 31 132152 10.54.17.251 dhcpd.txt](https://github.com/user-attachments/files/15512842/131May.31.132152.10.54.17.251.dhcpd.txt)
i've attached some syslog lines. I've obfuscated our domain;hostnames and ip.

**Comment by willem-dhaese** [comment]
Thanks @efd6 for the fast response..!!

**Comment by willemri** [comment]
<131>May 31 13:21:52 10.54.17.251 dhcpd[1122]: Unable to add forward map from PRinter12345.domain.subdomain.subsubdomain to 10.71.68.10 by server 127.0.0.1#53: REFUSED

the ECS field "related.hosts" is not being utilized. Instead, the hostname is being recorded in the field infoblox_nios.log.dhcp.forward_name.

Can you update the configuration to add the hostname to the related.hosts field?
